### ISSUE TITLE
Question: guava jar dependency for appium java-client

### ISSUE THREAD

**Issue by vsadineni1** [appium/java-client#1000]
## Description
We are in the process of upgrading our appium **java-client** jar from: **3.2.0** version to **5.0.4** version. (Yes, we are couple of releases behind.)
But when I try upgrading the appium java-client, I see that all the WebDriverWait validations are failing with a compilation error:
**java.lang.NoSuchMethodError for WebDriverWait().until(ExpectedCondition...)** 
https://github.com/SeleniumHQ/selenium/issues/3606

I followed the above thread and learned that it is todo with the guava jar version.
Currently we are using guava jar version: **19.0**

**My questions are:**
a. What is the recommended guava jar version if we want to upgrade our appium java-client from: 3.2.0 to 5.0.4??
b. In the appium java-client project **build.gradle** file, I do not a dependency on guava jar. Where is the guava jar dependecy coming from?

## Environment
* java client build version or git revision if you use some shapshot: 3.2.0
* Appium server version or git revision if you use some shapshot: 1.8.0
* Desktop OS/version used to run Appium if necessary: Linux 16.0.4
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS 11.2

**Comment by saikrishna321** [comment]
@vsadineni1 we no more support version 5.0.4. Please upgrade to the latest version 6.1.0 

Please raise questions in discuss.appium.io
