### ISSUE TITLE
With java-client 6.1.0 - error org.openqa.selenium.json.JsonOutput.write(Ljava/lang/Object;)Lorg/openqa/selenium/json/JsonOutput;

### ISSUE THREAD

**Issue by sunilpatro1985** [appium/java-client#1003]
OS - MAC 10.13.2
Java-client - 6.1.0
TestNG - 6.14.3
Selenium-java - 3.11 
Appium - 1.8.1

AppTest.java - https://pastebin.com/bR5qYEm8

Testng.xml

```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" > 
<suite name="Suite">  
    <test name="iOS">  
        <classes>  
           <class name="com.practice.Appium6.AppTest" />  
        </classes>  
    </test>   
</suite>
```

Error in out0put - 
java.lang.NoSuchMethodError: org.openqa.selenium.json.JsonOutput.write(Ljava/lang/Object;)Lorg/openqa/selenium/json/JsonOutput

Full trace is here - https://pastebin.com/sg6mUuqX

If I remove the dependency from the pom.xml, I m getting testng class not found exception.

Java-client untill 5.0.4 worked fine, I had some issue with scrolling, so updated to 6.1.0 and got the above error.

**Comment by saikrishna321** [comment]
Please remove selenium dependency as java-client comes with selenium version... 

The error your getting is because of dependency clash

**Comment by sunilpatro1985** [comment]
Had some issues with my maven repo, cleaned the repo and reimported, now it's working fine.
closing this issue.
