### ISSUE TITLE
io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.MobileElement

### ISSUE THREAD

**Issue by siddhantraut** [appium/java-client#1004]
## Description

java.lang.ClassCastException: io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.MobileElement

## Environment

 java client build version or git revision if you use some shapshot:5.0.4
Desktop OS/version used to run Appium: 1.6.1
Mobile platform/version under test:iOS 11.4.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: App

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

public static void logout() {
//	driver.navigate().back();

	MobileElement el2 = ((MobileElement) driver).findElementByAccessibilityId("Log out");
	el2.click();
 
	MobileElement el3 = ((MobileElement) driver).findElementByXPath("//XCUIElementTypeButton[@name=\"Log out\"]");
	el3.click();
} 

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/java-client/files/2306083/appium-server-logs.txt)

**Comment by 0neel** [comment]
You're casting `driver` to `MobileElement` which is not possible. The correct code will be (note that there are no brackets wrapping `(MobileElement) driver`):
```
MobileElement el2 = (MobileElement) driver.findElementByAccessibilityId("Log out");
el2.click();

MobileElement el3 = (MobileElement) driver.findElementByXPath("//XCUIElementTypeButton[@name=\"Log out\"]");
el3.click();
```
