### ISSUE TITLE
Unable to initialise PageFactory for PageObject

### ISSUE THREAD

**Issue by SapizonTechnologiesLLP** [appium/java-client#1007]
## Description

I have updated the java-client jar and tried to initialise PageFactory 

This is my screen  base class
`import org.openqa.selenium.By;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.pagefactory.AppiumFieldDecorator;

/**
 * ScreenBase.java contains method to start appium
 */
public class ScreenBase {

	public static AppiumDriver<MobileElement> driver;
	public WebDriverWait wait;

	  
	
	
	public void waitForElementPresent(long duration, String locator) {

		wait = new WebDriverWait(driver, duration);
		wait.until(ExpectedConditions.presenceOfElementLocated(By.id(locator)));
	}

	public ScreenBase(AppiumDriver<MobileElement> driver) {

		this.driver = driver;
		  PageFactory.initElements(new AppiumFieldDecorator(driver), this);

	}

	/**
	 * This method is to hide mobile Keyboard
	 */
	public void hideKeyboard() {

		driver.hideKeyboard();

	}

}`

This is my testbase class

`package com.sapizon.base;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import org.apache.commons.io.FileUtils;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;

import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import net.sourceforge.lept4j.util.LoadLibs;
import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;

import com.relevantcodes.extentreports.DisplayOrder;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.sapizon.utility.AppiumServer;
import com.sapizon.utility.Capablities;
import com.sapizon.utility.CommonUtils;
import com.sapizon.utility.Configration;
import com.sapizon.utility.ExtentManager;

public class AppiumTestBase {
	
	public static final Logger log = Logger.getLogger(AppiumTestBase.class.getName());
	static AppiumDriverLocalService services;
	public static AndroidDriver<MobileElement> driver;
	public static String destDir;
	public static String srcPath;
	
	Capablities caP;
	static AppiumServer aS;

	public static ExtentReports extent;
	public static ExtentTest test;
	public ITestResult result;
	public static String newFileName;
	public ExtentReports reo =ExtentManager.getInstance();
	public static ExtentTest tst;
	
	static {
		Calendar.getInstance();
		new SimpleDateFormat("dd_MM_yyyy_hh_mm_ss");
		extent = new ExtentReports(System.getProperty("user.dir") + "\\target\\surefire-reports\\html\\AppiumExtent.html",
				true, DisplayOrder.OLDEST_FIRST);
		extent.loadConfig(new File(System.getProperty("user.dir") + Configration.ReportsConfig));
	}
	
	
	public void initAndroid() throws IOException {
		AppiumServer.start();
		CommonUtils.setAndroidCapabilities();
	}
	
	public void initIOS() throws IOException {
		CommonUtils.loadIOSConfProp();
		CommonUtils.setIOSCapabilities();
		String log4jConfPath = Configration.log4jpath;
		PropertyConfigurator.configure(log4jConfPath);
	}
	
	public String captureScreen(String fileName) {
		if (fileName == "") {
			fileName = "blank";
		}
		File destFile = null;
		Calendar calendar = Calendar.getInstance();
		SimpleDateFormat formater = new SimpleDateFormat("dd_MM_yyyy_hh_mm_ss");
		File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
		try {
			String reportDirectory = new File(System.getProperty("user.dir")) + "\\target\\surefire-reports\\html\\";

			destFile = new File(
					(String) reportDirectory + fileName + "_" + formater.format(calendar.getTime()) + ".png");
			newFileName = fileName + "_" + formater.format(calendar.getTime()) + ".png";
			FileUtils.copyFile(scrFile, destFile);
			Reporter.log("<a href='" + destFile + "'> <img src='" + "_" + fileName + formater.format(calendar.getTime())
					+ ".png" + "' height='100' width='100'/> </a>");

		}

		catch (IOException e) {
			e.printStackTrace();
		}

		return destFile.toString();
	}
	public void log(String data) {
		log.info(data);
		Reporter.log(data);
	}
	public void getresult(ITestResult result) {
		if (result.getStatus() == ITestResult.SUCCESS) {
			test.log(LogStatus.PASS, result.getName() + "test is pass");
			captureScreen("");
			test.log(LogStatus.PASS, test.addScreenCapture(newFileName));

		} else if (result.getStatus() == ITestResult.SKIP) {
			test.log(LogStatus.SKIP,
					result.getName() + " test is skipped and skip reason is:-" + result.getThrowable());
			captureScreen("");
			test.log(LogStatus.SKIP, test.addScreenCapture(newFileName));
		} else if (result.getStatus() == ITestResult.FAILURE) {
			test.log(LogStatus.ERROR, result.getName() + " test is failed" + result.getThrowable());
			captureScreen("");
			test.log(LogStatus.FAIL, test.addScreenCapture(newFileName));
		} else if (result.getStatus() == ITestResult.STARTED) {
			test.log(LogStatus.INFO, result.getInstanceName() + "test is started" + result.getThrowable());

		}
	}
	 public String OCR(String srcPath2) throws TesseractException {
		  String imgName = takeScreenShot();
		  String result = null;
		  File imageFile = new File(srcPath, imgName);
		  System.out.println("Image name is :" + imageFile.toString());
		  ITesseract instance = new Tesseract();

		  File tessDataFolder = LoadLibs.extractNativeResources("tessdata"); 
		  instance.setDatapath(tessDataFolder.getAbsolutePath());
		  result = instance.doOCR(imageFile);
		  System.out.println(result);
		  return result;
		 }

	public String takeScreenShot() {
		
		  File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE); 
		  
		  SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy__hh_mm_ssaa");
		  new File(destDir).mkdirs(); 
		  srcPath = dateFormat.format(new Date()) + ".png"; 
		  try {
		   FileUtils.copyFile(scrFile, new File(destDir + "/" + srcPath)); 
		  } catch (IOException e) {
		   System.out.println("Image not transfered to screenshot folder");
		   e.printStackTrace();
		  }
		  return srcPath;
		 }
	
	public void hideKeyboard() {

		driver.hideKeyboard();

	}
	@AfterMethod()
	public void afterMethod(ITestResult result) {
	
		getresult(result);
		//driver.quit();
	}

	@BeforeMethod()
	public void beforeMethod(Method result) throws MalformedURLException {
		AppiumServer.start();
		driver =Capablities.setAndroidCapablities(driver);
		test = extent.startTest(result.getName());
		test.log(LogStatus.INFO, "open Application");
	}

	@AfterClass(alwaysRun = true)
	public void endTest() {
		
		extent.endTest(test);
		extent.flush();
	}
		
	}
	
	

`

This is my screen class
`package com.sapizon.screens.firecart;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

import com.sapizon.base.ScreenBase;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.pagefactory.AndroidFindBy;
import io.appium.java_client.pagefactory.AppiumFieldDecorator;

public class Signup_module extends ScreenBase{

	public Signup_module(AppiumDriver<MobileElement> driver) {
		super(driver);
		
		
	}

	@FindBy(id = "com.hitesh_sahu.retailapp:id/google_sign_in")
	public AndroidElement Signup_buttons;
	
	public void signUp_with_google() {
		 Signup_buttons.click();
	}
	
	
	@FindBy(id = "com.google.android.gms:id/account_name")
	public AndroidElement googleAcc;
	
	public void googleacc() {
		googleAcc.click();
	}

	@FindBy(xpath = "//*[@contentDescription='Navigate up']")
	public AndroidElement menuButtton;
	
	public void clickOnMenu() {
		 menuButtton.click();
	}

	@FindBy(xpath = "//*[@text='Logout']")
	public AndroidElement logout;
	
	public void clickOnLogout() {
		 logout.click();
	}
}
`

This is my test case

`package com.sapizon.testcases.firecart;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;

import com.sapizon.base.AppiumTestBase;
import com.sapizon.screens.firecart.Signup_module;

import io.appium.java_client.pagefactory.AppiumFieldDecorator;

public class T001_Signup_Module extends AppiumTestBase{
	
	
	@Test
	public void SignUp() {
		
		Signup_module sUp = PageFactory.initElements(driver, Signup_module.class);
		
		//hideKeyboard();
		//sUp.signUp_with_google();
		//sUp.googleacc();
		
		sUp.clickOnMenu();
		sUp.clickOnLogout();
	}

}
`
logs
"https://gist.github.com/SapizonTechnologiesLLP/f94c8c8bee6f8aa0b6dcecb330551c62.js"

**Comment by saikrishna321** [comment]
Please use discuss.appium.io to ask question. This place is for reporting bugs.
