### ISSUE TITLE
appium java-client is sending an empty firstMatch array: SeleniumGridException: java.lang.IllegalArgumentException: First match w3c capabilities is zero length

### ISSUE THREAD

**Issue by prohilla** [appium/java-client#1009]
## Description
Appium java-client is sending an empty firstMatch array. Which is causing selenium grid to throw a ` java.lang.IllegalArgumentException: First match w3c capabilities is zero length` exception

**From W3C spec:**
```
Let all first match capabilities be the result of getting the property "firstMatch" from capabilities request.

If all first match capabilities is undefined, set the value to a JSON List with a single entry of an empty JSON Object.

If all first match capabilities is not a JSON List with one or more entries, return error with error code invalid argument.
```

## Environment

* Appium java client build version: 6.1.0
* Appium server version: 1.9.0
* Selenium Standalone Jar: 3.14  (downgrading selenium doesn't help)
* Mobile platform: iOS/Android
* Real device or emulator/simulator: Simulator

## Ecxeption stacktraces
https://gist.github.com/prohilla/cb79dfec3a6a0fd27a7a172a89ed6614

## Selenium grid log: 
Notice _"firstMatch": []_ is an empty array instead it of "firstMatch": [{}]

> 2018-08-27 19:53:09.276:WARN:osjs.HttpChannel:qtp1206883981-18: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {
>   "desiredCapabilities": {
>     "platformVersion": "11.2",
>     "appium:deviceName": "iPhone 8",
>     "platformName": "iOS",
>     "appium:automationName": "XCUITest",
>     "appium:app": "Url to app",
>   },
>   "requiredCapabilities": {},
>   "capabilities": {
>     "desiredCapabilities": {
>       "platformVersion": "11.2",
>       "appium:deviceName": "iPhone 8",
>       "platformName": "iOS",
>       "appium:automationName": "XCUITest",
>       "appium:app": "Url to app",
>     },
>     "requiredCapabilities": {},
>     "alwaysMatch": {
>       "appium:deviceName": "iPhone 8",
>       "platformName": "iOS",
>       "appium:automationName": "XCUITest",
>       "appium:app": "URL to app"
>     },
>     **"firstMatch": []**
>   }
> }

### More details: Directly sending a post request using postman to grid session endpoint with the below mentioned  JSON payload works fine. So I am sure this is a java-client bug.

1. Works: W3C
> {
>   "capabilities": {
>     "alwaysMatch": {
>       "appium:deviceName": "iPhone 8",
>       "platformName": "iOS",
>       "appium:automationName": "XCUITest",
>       "appium:app": "Url to app"
>     },
>     "firstMatch": [{}]
>   }
> }

2 . Works: MJONWP

> {
>   "desiredCapabilities": {
>     "platformVersion": "11.2",
>     "appium:deviceName": "iPhone 8",
>     "platformName": "iOS",
>     "appium:automationName": "XCUITest",
>     "appium:app": "Url to app",
>   },
>   "requiredCapabilities": {}
> }

## Code To Reproduce Issue [ Good To Have ]

```
capabilities.setCapability("appium:"+MobileCapabilityType.DEVICE_NAME, MobileTestConfig.DEVICE_NAME());
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, MobileTestConfig.OS_VERSION());
        capabilities.setCapability("appium:"+MobileCapabilityType.AUTOMATION_NAME, MobileTestConfig.AUTOMATION_NAME());
        capabilities.setCapability("appium:"+MobileCapabilityType.APP, "Url to app");

driverThreadLocal.set(new IOSDriver<WebElement>(remoteServerURL, caps));
```

**Comment by prohilla** [comment]
@SrinivasanTarget  is this a known issue ? Asking because I see there havee been recent W3C related fixes done. Thanks for your help in advance.

**Comment by mykola-mokhnach** [comment]
Try appium@beta. It has some fixes for the grid

**Comment by mykola-mokhnach** [comment]
Can you please verify if https://github.com/appium/java-client/pull/1010/files works for you?

**Comment by prohilla** [comment]
Yes it did, I suspected that to be the issue. Thanks a lot @mykola-mokhnach for the quick response.

**Comment by saikrishna321** [comment]
@prohilla can you please re-test with the latest master commit.

https://github.com/appium/java-client#maven

**Comment by prohilla** [comment]
@saikrishna321 tested. It works. 👍
