### ISSUE TITLE
Unable to locate element and getting error No such element exception

### ISSUE THREAD

**Issue by shijithkannoth** [appium/java-client#1019]
## Description

When I try to inspect the element using uiautomatorviewr able to see the elements however when the run the script unable to find the element. It is not related to particular element any element which I try to find has the same issue but when the I get the page source it has the elements which I used while scripting.

## Environment
Im using Appium 1.9.0  and JDK 8, Platform version 8.1.0

## Details

below are the capabilities which I used. 

 DesiredCapabilities caps = new DesiredCapabilities();
    	 caps.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.9.0");
    	 caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
    	 caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, 8.1);
		 caps.setCapability(MobileCapabilityType.DEVICE_NAME,"Galaxy On Nxt");
    	 caps.setCapability(MobileCapabilityType.DEVICE_NAME,"OnePlus 5");
    	 caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
    	 caps.setCapability("appPackage", "com.level3.apps.mobility");
    	 caps.setCapability("appActivity", "com.level3.apps.mobility.MainActivity");
    	 caps.setCapability("noSign", true);
		 caps.setCapability("autoGrantPermissions", "true");
	//	 caps.setCapability("avd", "Nexus_6P_API_25");
		 caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 7200);
		//caps.setCapability(MobileCapabilityType.FULL_RESET, true);
    	
        /*caps.setCapability("deviceName", "OnePlus 5T");
        caps.setCapability("platformVersion", 8.1);
        caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UIAutomator2");
        caps.setCapability("noReset", "true");
        caps.setCapability("fullReset", "false");
      // caps.setCapability("unicodeKeyboard", "true");
      // caps.setCapability("resetKeyboard", "true");
        caps.setCapability("appPackage", "******");
        caps.setCapability("appActivity", "*******");
//        caps.setCapability("unicodeKeyboard", true);
//        caps.setCapability("resetKeyboard", true);

below are the info from the UIautomatorview :+1: 
Index : 0
text :  Username
resource-id : lbl-4
class : android.view.View

and the sample code is : 
Assert.assertTrue(Config.driver.findElementByClassName("android.view.View").isDisplayed(), "Username edit box is not displaying");

I have also tried the hard-coded code but still the result is same

"org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 345 milliseconds"

**Comment by SrinivasanTarget** [comment]
@shijithkannoth please raise questions on discuss forum.
