### ISSUE TITLE
Inconsistent use of MissingParameterException

### ISSUE THREAD

**Issue by 0x1mason** [appium/java-client#102]
java-client checks on the client side for missing parameters in MultiTouchAction::perform and throws a custom exception.  However, there aren't other checks for valid params.  We should check parameters consistently in the client or not at all.

Also, we should probably use `Preconditions.checkArgument(foo, msg);`, since this is part of the Guava idiom, and add `throws IllegalArgumentException` to function signatures that assert precondtions.

**Comment by TikhomirovSergey** [comment]
Fixed
