### ISSUE TITLE
Mobile element with Android annotation  e.g @AndroidBy(id="com.xyz.app.debug:id/skip") is not identified

### ISSUE THREAD

**Issue by JAidhy** [appium/java-client#1025]
## Description

I have created page object model/pattern framework for native application for both iOS and Android. The script when executed is able to locate iOS element however it does not identify Android mobile element.

Below is the code for the Landingpage-

public class LandingPage {
	
	
	
	public LandingPage(AppiumDriver driver){
		PageFactory.initElements(new AppiumFieldDecorator(driver),this);
	}

        @AndroidBy(id="com.xyz.app.debug:id/skip")
	@iOSFindBy(accessibility="SKIP")
	public MobileElement landingScreenSkip;

         public void clickLandinSkip(){
		landingScreenSkip.click();
		
	}

Below is the code of test class-
public class Login extends BaseTestClass{
	
	
	@Given("^I open the app$")
	public void i_open_the_app() throws Throwable {
		
		setUp();
		
		LandingPage landingObj = new LandingPage(driver());
                	landingObj.clickLandinSkip();

## Environment

* java client - 6.1.0
* Appium server -Version 1.6.3 (1.6.3)
* Desktop OS- Mac 10.13.6 
* Node.js version- v10.8.0
* Mobile platform/version under test: Nexus 6P/Android 7.1.1
* Simulator

[appium-server-logs.txt](https://github.com/appium/java-client/files/2398433/appium-server-logs.txt)
[Error.txt](https://github.com/appium/java-client/files/2398454/Error.txt)

**Comment by 0neel** [comment]
You should use `@AndroidFindBy` instead.

**Comment by JAidhy** [comment]
> You should use `@AndroidFindBy` instead.

Yes, I tried using @AndroidFindBy and it worked.
