### ISSUE TITLE
No suitable method found for longPress 

### ISSUE THREAD

**Issue by lakesierra96** [appium/java-client#1031]
## Code To Reproduce Issue [ Good To Have ]

    action.longPress(ele1).moveTo(ele2).release().perform();

## Link to Appium logs

Error:(60, 15) java: no suitable method found for longPress(org.openqa.selenium.WebElement)
method io.appium.java_client.TouchAction.longPress(io.appium.java_client.touch.LongPressOptions) is not applicable
(argument mismatch; org.openqa.selenium.WebElement cannot be converted to io.appium.java_client.touch.LongPressOptions)
method io.appium.java_client.TouchAction.longPress(io.appium.java_client.touch.offset.PointOption) is not applicable
(argument mismatch; org.openqa.selenium.WebElement cannot be converted to io.appium.java_client.touch.offset.PointOption)

**Comment by 0neel** [comment]
You're passing `WebElement` to `longPress` method while it accepts either `LongPressOptions` or `PointOption`.

**Comment by saikrishna321** [comment]
@lakesierra96 its answered here 
https://discuss.appium.io/t/no-suitable-method-found-for-longpress/23632
