### ISSUE TITLE
Android: Getting BatteryInfo gives Error.

### ISSUE THREAD

**Issue by WasiqB** [appium/java-client#1039]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot: 1.9.1
* Desktop OS/version used to run Appium if necessary: Linux Ubuntu 16.0.4
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:8.12.0 / 1.7.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device

## Details

When trying to get Battery Info for the device, an error is generated.

## Code To Reproduce Issue [ Good To Have ]

```java
	AndroidDriver <AndroidElement> driver = new AndroidDriver <> (new URL ("http://0.0.0.0:4723/wd/hub"), caps);
	BatteryState batteryInfo = driver.getBatteryInfo().getState();
	System.out.println(batteryInfo);
```

## Exception stacktraces

Appium Java client exception and Appium server logs can be found here: https://gist.github.com/WasiqB/4de519dd22d72ae4907c0063c3513dfa

**Comment by mykola-mokhnach** [comment]
This endpoint is only available with UIAutomator2

**Comment by WasiqB** [comment]
What happens in case of iOS? Is Battery info supported for iOS only in XCUITest driver?

**Comment by dmlemeshko** [comment]
@WasiqB You can find the answer in [official docs](http://appium.io/docs/en/commands/device/performance-data/get-performance-data/#get-performance-data)
