### ISSUE TITLE
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible

### ISSUE THREAD

**Issue by testfortest06** [appium/java-client#1040]
## Description

When running Appium scrip then getting an error :org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible

## Environment

* java client build version : java-client-6.1.0
* Appium server version : 1.9.0
* Desktop OS/version used to run Appium if necessary: Windows 7
* Mobile platform/version under test: Android/ 8.1.0
* Real device or emulator/simulator: Real Device
*Selenium version: 3.14.0

## Details
Please help me to resolve this issue.. i am stuck unable to proceed my coding..

## Code To Reproduce Issue [ Good To Have ]

public class FistTest {
    public WebDriver driver;
    DesiredCapabilities capabilities=new DesiredCapabilities();
    @BeforeMethod
    public void setup(){

        File app=new File("C://Eclipse_Setup//apk_file//Amazon.apk");
        capabilities.setCapability("deviceName","Redmi");
        capabilities.setCapability("platformVersion","8.1.0");
        capabilities.setCapability("platformName","Android");
        capabilities.setCapability("noReset","true");
        capabilities.setCapability("skipUnlock","true");
        capabilities.setCapability("app","getAbsolutePath()");

    }

    @Test
    public void testApp()  {
        try {
            driver=new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"),capabilities);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    @AfterMethod
    public  void quit(){
        driver.quit();
        driver.close();
    }

## Ecxeption stacktraces

org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'OFFICE-PC', ip: '192.168.100.3', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_152-release'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:195)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:209)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:93)

## Link to Appium logs

[info] [35m[Appium][39m Welcome to Appium v1.9.0
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"getAbsolutePath()","noReset":"true","platformVersion":"8.1.0","skipUnlock":"true","platformName":"Android","deviceName":"Redmi"},"capabilities":{"alwaysMatch":{"appium:app":"getAbsolutePath()","appium:deviceName":"Redmi","appium:noReset":"true","platformName":"android","appium:platformVersion":"8.1.0","skipUnlock":"true"},"firstMatch":[{}]}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"app":"getAbsolutePath()","noReset":"true","platformVersion":"8.1.0","skipUnlock":"true","platformName":"Android","deviceName":"Redmi"},null,{"alwaysMatch":{"appium:app":"getAbsolutePath()","appium:deviceName":"Redmi","appium:noReset":"true","platformName":"android","appium:platformVersion":"8.1.0","skipUnlock":"true"},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1539025148940 (00:29:08 GMT+0530 (India Standard Time))
[warn] [35m[BaseDriver][39m The capabilities ["skipUnlock"] are not standard capabilities and should have an extension prefix
[warn] [35m[BaseDriver][39m Boolean capability passed in as string. Functionality may be compromised.
[warn] [35m[Appium][39m Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[Appium][39m Creating new AndroidDriver (v3.7.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   platformName: android
[info] [35m[Appium][39m   skipUnlock: true
[info] [35m[Appium][39m   app: getAbsolutePath()
[info] [35m[Appium][39m   deviceName: Redmi
[info] [35m[Appium][39m   noReset: true
[info] [35m[Appium][39m   platformVersion: 8.1.0
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"getAbsolutePath()",... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[warn] [35m[BaseDriver][39m Boolean capability passed in as string. Functionality may be compromised.
[warn] [35m[BaseDriver][39m Boolean capability passed in as string. Functionality may be compromised.
[warn] [35m[BaseDriver][39m Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[warn] [35m[BaseDriver][39m Capability 'skipUnlock' changed from string to boolean. This may cause unexpected behavior
[info] [35m[BaseDriver][39m Session created with session id: ffdbc25c-67eb-42bd-8496-18a1b179061d
[info] [35m[AndroidDriver][39m Java version is: 1.8.0_91
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Looking for a device with Android '8.1.0'
[debug] [35m[ADB][39m Setting device id to 35924c6f0804
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 35924c6f0804 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 8.1.0
[info] [35m[AndroidDriver][39m Using device: 35924c6f0804
[debug] [35m[ADB][39m Setting device id to 35924c6f0804
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 35924c6f0804 shell getprop ro.build.version.sdk'
[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 27
[debug] [35m[ADB][39m Device API level: 27
[warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[debug] [35m[AndroidDriver][39m Shutting down Android driver
[debug] [35m[AndroidDriver][39m Called deleteSession but bootstrap wasn't active
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 35924c6f0804 shell am force-stop io.appium.unlock'[debug] [35m[AndroidDriver][39m Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1539025149562 (00:29:09 GMT+0530 (India Standard Time))
[error] [35m[W3C][39m Encountered internal error running command: Error: The application at 'getAbsolutePath()' does not exist or is not accessible
[error] [35m[W3C][39m     at Object.configureApp$ (C:\Users\Office\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\helpers.js:97:11)
[error] [35m[W3C][39m     at tryCatch (C:\Users\Office\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[error] [35m[W3C][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Office\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[error] [35m[W3C][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Office\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[error] [35m[W3C][39m     at GeneratorFunctionPrototype.invoke (C:\Users\Office\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[error] [35m[W3C][39m     at <anonymous>
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m624 ms - 1587[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by mykola-mokhnach** [comment]
> [error] �[35m[AndroidDriver]�[39m Error: The desired capabilities must include either an app, appPackage or browserName

the error message is pretty clear

**Comment by testfortest06** [comment]
Thanks @mykola-mokhnach  resolved previous issue..
But i am facing another issue is that when running script unable to lunch app, but two folder 1. Appium Setting 2. Unlock getting generated on my phone and appium server is getting closed automatically. I am using java-client-6.1.0..

Can you please help me how to resolve this issue.

**Comment by testfortest06** [comment]
Hello After set following below desired capabilities still unable to launch app still getting an error on console "**Exception in thread "main" org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible**"
However unable to get appium server log because of getting this error appium server getting closed automatically : 
I have captured video for appium server log during execution Please find screencast for that: https://www.screencast.com/t/4f8j8cEveZ

Please let me know where i am missing..
Following configuration i am using: Selenium 3.12.0
TestNg: 6.14.3
Appium Java-client: 6.1.0
Appium Server: 1.7.1
nodeJs: 6.4.1

public class launchApp {

    AndroidDriver<WebElement> driver;

    @BeforeClass
    public void beforeClass() throws MalformedURLException, InterruptedException {
        DesiredCapabilities capab = new DesiredCapabilities();

        capab.setCapability("deviceName", "Redmi Note 5");
        capab.setCapability("udid", "35924c6f0804");
        capab.setCapability("platformName", "Android");
        capab.setCapability("platformVersion", "8.1.0");
        capab.setCapability("appPackage", "com.miui.calculator");
        capab.setCapability("appActivity", "com.miui.calculator.cal.CalculatorActivity");
        driver = new AndroidDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capab);
        Thread.sleep(5000);

    }

    @Test
    public void m1() throws InterruptedException {
        System.out.println("kfd");
        Thread.sleep(2000);
       
    }
}

Please help me on this its urgent...

**Comment by bitweft** [comment]
I am facing the same issue on some Motorola devices but not on Samsung devices.

`org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
`

**Version details:**
- appium: 1.9.1
- java-client: 6.1.0
- node: 11.0.0
- real mobile device: Android 7

I could not reproduce this issue on a Samsung device but I could reproduce it consistently on some Motorola devices that I used (Moto G5 Plus, Moto G4 Plus with Android 7.0)

Does anyone have an idea why this would be the case and what I can do to fix it?

**Comment by SrinivasanTarget** [comment]
@bitweft Did you tried in latest appium java client commit? Refer [here](https://github.com/appium/java-client#maven)

**Comment by helenren** [comment]
Hit the same issue using java_client 6.1.0, while only repro to use remote appium server, like the simulator or real device in saucelabs. For my local ios simulator, it works fine.

**Comment by donedeal-ronan** [comment]
I'm getting the same error as the initial post on emulators.

TestNg: 6.14.3
Appium Java-client: 6.1.0
Appium Server: 1.7.1
SeleniumHQ Java: 3.12.0
Node: 10.11.0
Android versions under test: 8.1.0, 6.0, 6.1
Desktop OS/version: macOS High Sierra (10.13.6)

I've tried the latest version of the java-client too but it doesn't seem to resolve the issue.

Any help on this would be greatly appreciated.

**Comment by SrinivasanTarget** [comment]
Try https://github.com/appium/java-client#how-to-install-latest-java-client-betasnapshots

**Comment by VenkateshPS** [comment]
I am able to reproduce this issue with 
Appium 1.14.2 
Java client 7.2.0.
MacOS version 10.14.3.

@SrinivasanTarget please reopen this issue.

**Comment by emindedic** [comment]
I am able to reproduce too:
Appium v1.10.1
MacOS version: '10.14.2', 
Java.version: '1.8.0_201'
Real Device Samsung Galaxy S9,

**Comment by hp001** [comment]
I am seeing with Appium 1.15 for iOS. Any one know how to solve this issue.
