### ISSUE TITLE
InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session 

### ISSUE THREAD

**Issue by Madhavip3** [appium/java-client#1047]
## Description

 Updated Appium to the latest version and started seeing this issue. Tried using AppiumDriver and iOS Driver and still see the issue. Running Appium on native apps on both iOS and UWP. Currently we get this issue on iOS. Worked perfectly fine until the previous release.

## Environment

Java Client version: 6.1.0
Appium Server :Version 1.7.1 (1.7.1.20180926.9)
OS Version:10.13.6 (17G2112)
Mobile Platform version: IOS 11.4(iPads)
Device:Simulator

##Code used
currentSession.findElement(By.id(id)).click() --> this is how we are accessing the elements in the app. Also Tried findElementById() with IOSDriver and still see the same issue.

**Comment by Madhavip3** [comment]
I updated to the latest version and now the version is 
Version 1.8.0 (1.8.0.20181023.4)

**Comment by Madhavip3** [comment]
[appium-server-logs.txt](https://github.com/appium/java-client/files/2511634/appium-server-logs.txt)

**Comment by saikrishna321** [comment]
@Madhavip3 you cant use css selector for Native app its only applied on web context

**Comment by saikrishna321** [comment]
@Madhavip3 issue posted in #10874 was python client issue on selenium side.

I'm not able to reproduce the issue on latest java-client with latest appium beta.

```
[debug] [W3C (6f5b4adc)] Calling AppiumDriver.findElement() with args: ["id","org.wordpress.android:id/nux_username","6f5b4adc-c587-4c04-a26c-c91e46817060"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/83777206-3b39-4f8f-a12d-cff5b3f04d6e/element] with body: {"strategy":"id","selector":"org.wordpress.android:id/nux_username","context":"","multiple":false}
```

**Comment by Madhavip3** [comment]
@saikrishna321 What is the latest java client version you are using?

**Comment by Madhavip3** [comment]
I am trying this on iOS. I see that you have tried it on android. Can you try it on iOS as well?Thanks!

**Comment by saikrishna321** [comment]
```
[debug] [W3C (b6b18050)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"1D000000-0000-0000-1D64-010000000000"}
[HTTP] <-- POST /wd/hub/session/b6b18050-94e2-424b-9220-a06fb78e8280/element 200 89 ms - 88
[HTTP]
[HTTP] --> POST /wd/hub/session/b6b18050-94e2-424b-9220-a06fb78e8280/element
[HTTP] {"using":"id","value":"nextButton"}
[debug] [W3C (b6b18050)] Calling AppiumDriver.findElement() with args: ["id","nextButton","b6b18050-94e2-424b-9220-a06fb78e8280"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/786553E8-29B7-417A-A43E-751D994C9D5B/element] with body: {"using":"id","value":"nextButton"}
```

I use the latest master commit

https://github.com/appium/java-client#maven

**Comment by Madhavip3** [comment]
@saikrishna321 I tried with the latest commit and I still see the same issue. Is there anything else I am missing here?
[appium-server-logs.txt](https://github.com/appium/java-client/files/2512755/appium-server-logs.txt)

**Comment by helenren** [comment]
Hit the same issue once using appium from 1.8.1 to 1.9.0 trying to use by.name to find an element on a native context. 

For 1.8,1, for creating a new session, got this back:
org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
While for 1.9.0, got this back:
Oct 30, 2018 9:03:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C.
Feel since the new session using W3C, so use W3CHttpCommandCodec for the command encode, which make the command like this:
2018-10-31 04:03:32:328 - [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/de917d18-aa03-43da-915a-994f025a9506/elements[39m
2018-10-31 04:03:32:328 - [35m[HTTP][39m [90m{"value":"*[name='EULA.agree']","using":"css selector"} and hit this error: Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session.

**Comment by rahulcode** [comment]
@Madhavip3 
Is there any solution for your problem ?, I am also facing the same.

**Comment by saikrishna321** [comment]
@rahulcode how does your client code look like ?

**Comment by rahulcode** [comment]
Hi @saikrishna321 

Appium Version: 1.9.1
Java Client : 5.0.4

Below is the Error Log :
https://gist.github.com/rahulcode/819f373f5f22e31c9a0bdfe820fb5019

```
IOSAppiumConnection_Agent.driver.findElements(By.name("Safari"));
```
*It used to work with the previous version of appium*

Do let me know if we need more information to resolve this.

**Comment by Yakupvarli** [comment]
Is there any solution for your problem ?, 
Appium 1.9.1 
maven Project.
		<artifactId>java-client</artifactId>
			<version>5.0.0</version>
		<artifactId>selenium-java</artifactId>
			<version>2.3.4</version>
			<artifactId>javax.mail-api</artifactId>
			<version>1.5.5</version>

and as stated findby it gives an error:  css selector is not supported exception ,

**Comment by jtoal436** [comment]
Also having the same issue with Appium1.9.1
Has anyone found a way around this? 
"css selector' is not supported for this session" is appearing as the message but there is no css selectors being used in the project.

**Comment by saikrishna321** [comment]
Please update java-client to the latest and remove the selenium-java as java-client comes with supported selenium jars.

**Comment by Yakupvarli** [comment]
do you think there will be a definite solution

**Comment by jtoal436** [comment]
@saikrishna321 how do i Remove the selenium-java version? I am running on Mac OS and using appium with WebDriverAgent.

**Comment by saikrishna321** [comment]
if you have added selenium-java dependency along with java-client then you need to remove that from you pom.xml or gradle file. If you have not added just update the java-client to the latest

**Comment by iamravi28** [comment]
Removed selenium-java dependency. Still facing the same issue.

Appium : 1.10.0
java-client : 7.0.0(latest)
Error:Locator Strategy 'css selector' is not supported for this session.

**Comment by SrinivasanTarget** [comment]
@iamravi28 Update the entire logs here in form of gist.

**Comment by jtoal436** [comment]
@SrinivasanTarget see attached logs https://gist.github.com/jtoal436/5a33661f5ac53b7ee3c4520a4314e906
