### ISSUE TITLE
Java client 6.1.0 Create session throws WebDriverException frequently while running tests with remote session.

### ISSUE THREAD

**Issue by Saranraj-ITT** [appium/java-client#1048]
## Description

We are automating mobile app on iOS/Android by **creating a remote session**.
The tests are failing frequently with the exception:
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
Driver info: driver.version: IOSDriver
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.net.SocketException: Connection reset

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot: 1.9.1
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS 11.4.3 and Android 7.0, 7.1, 8.0 and 9.0
* Real device or emulator/simulator: Real device

## Details

This issue does not happen with all the tests that are run as part of suite. But, larger number of tests fail due to the above mentioned issue. 
Thus, our test environment is not reliable due to this issue.

**Comment by SrinivasanTarget** [comment]
Refer https://github.com/appium/java-client#how-to-install-latest-java-client-betasnapshots. Let us know if you still find issues on latest commit.
