### ISSUE TITLE
findelement byname does not work with appium 1.9.1

### ISSUE THREAD

**Issue by helenren** [appium/java-client#1050]
On a native page, my test tries to find an element via byname: command passed into driver is: findElement(By.name: EULA.agree), while I saw the command executed to the appium server is:

2018-10-25 03:23:24:329 - info: [HTTP] --> POST /wd/hub/session/22bd911d-ed10-47f6-bd77-f327b5562c48/elements
2018-10-25 03:23:24:329 - info: [HTTP] {"value":"*[name='EULA.agree']","using":"css selector"}

The same test works fine against appium 1.8.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: xcode 9.4.1, mac os version: 10.13.6
* Node.js version (unless using Appium.app|exe):v7.1.0
* Mobile platform/version under test: ios 9.4/9.2
* Real device or emulator/simulator: simulator
* java client verion: 6.1.0 and 5.0.4 both has this issue.

**Comment by helenren** [comment]
@jlipps  do you aware any issue related to? thanks

**Comment by saikrishna321** [comment]
name was deprecated in favor of accessiblity id

**Comment by helenren** [comment]
so, for ios, we should use by.accessibilityid or by.id? where we can find the info on change for search property support ? @saikrishna321

**Comment by saikrishna321** [comment]
@helenren this was very old change which went through, may be in version 5.0.0 BETAX not sure though.. But for sure this change was done long back.

**Comment by helenren** [comment]
Hmm, the change that you mentioned is for page object tools. While in my test, I use By.Name directly instead of @FindBy annotation.  I am kind lost. @saikrishna321

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/pull/313

**Comment by ndeztea** [comment]
I have the similiar issue on this like this : **NotImplementedError: Method is not implemented** 

anyone have the simliar issue as well ?

**Comment by helenren** [comment]
after configure via using capability: MobileCapabilityType.FORCE_MJSONWP to true to still use OSS instead of the default W3C, this issue has been gone for me.  @ndeztea

**Comment by michaeljohndamo1** [comment]
![Screen Shot 2020-06-04 at 1 33 32 PM](https://user-images.githubusercontent.com/58174436/83718628-ff1aa500-a667-11ea-882a-13fb3206dccc.png)
What could be wrong?

**Comment by mykola-mokhnach** [comment]
@michaeljohndamo1 The xpath locator is invalid. It only supports double quotes as string separators.

**Comment by michaeljohndamo1** [comment]
Hi @mykola-mokhnach sorry, i am still newbie please be patience on me. Can you please explain more? coz i really don't understand. I am still learning, btw this runs on browser but when i have changed the setup to mobile chrome. I am facing this error. I've been searching and trying all the stuff the i've searched on the internet but still no luck.

**Comment by mykola-mokhnach** [comment]
> Can you please explain more? coz i really don't understand

What exactly is not understandable?

**Comment by michaeljohndamo1** [comment]
@mykola-mokhnach sorry i cannot understand why i am facing this error. The answer that it only supports double quotes as string separators. I've tried to comment out the xpath / button if it will still continue to send keys. But i still face the error even without the xpath

**Comment by shibupanda** [comment]
Hi @michaeljohndamo1 could you please go with xpath instead of id. Let's have a try.
something like //*[@id='_username'].

**Comment by michaeljohndamo1** [comment]
> Hi @michaeljohndamo1 could you please go with xpath instead of id. Let's have a try.
> something like //*[@id='_username'].

Okay sir will try now, thank you :)

**Comment by michaeljohndamo1** [comment]
![Screen Shot 2020-06-04 at 6 03 13 PM](https://user-images.githubusercontent.com/58174436/83743997-0f457b00-a68e-11ea-8beb-9f3cc7c6bd6a.png)
![Screen Shot 2020-06-04 at 6 05 43 PM](https://user-images.githubusercontent.com/58174436/83744008-140a2f00-a68e-11ea-9178-3626b0289ada.png)


hi sir, the error has been changed. But it still cant find the xpath

**Comment by shibupanda** [comment]
@michaeljohndamo1 I can see the id is "username" but in code you have written "_username" please change it.

**Comment by michaeljohndamo1** [comment]
@shibupanda oh sir it works! thank you so much. This is my first time participating here in github i am really desperate and thanks to you, you have solved my problem. Sir may i know why id doesn't work earlier? and have to change to xpath? is it good to ask following question here?
