### ISSUE TITLE
androiddriver cannot be cast to org.openqa.selenium.interactions.hastouchscreen

### ISSUE THREAD

**Issue by CathyWY** [appium/java-client#1056]
## Description

the new version of appium java client does not support swipe function, instead using press moveTo release perform to simulate a swipe gesture.
when using press I found it last too long so it called out a floating window in my own app instead of expected flicking.
when I switched to flick function in selenium using selenium TouchActions, I meet a java.lang.ClassCastException: androiddriver cannot be cast to org.openqa.selenium.interactions.hastouchscreen

My code : 

AndroidDriver<AndroidElement> driver;

new TouchAction(driver).press(PointOption.point(startX, startY))
.moveTo(PointOption.point(endX, endY)).release().perform();
WORKS FINE BUT last too long to perform flick

BUT
new TouchActions(driver).flick(Element, 10, 0, 1);
MEETS java.lang.ClassCastException

AND
driver.executeScript("mobile:swipe", Element);
IS NOT supported.

I wonder if there is a appropriate way to perform a fast swiping gesture

or I can only use adb command like this:
adb shell input touchscreen swipe <x> <y> <x> <y> <durationMs> ？
https://stackoverflow.com/questions/48458726/classcastexception-with-new-appium-java-touchactions

please help, thanks ! 

## Environment

* java client build version ： 6.1.0
* Appium server version ：1.9.0
* Desktop OS/version ： centOS 7
* Node.js version ：v8.4.0
* Selenium version：3.12.0
* Real device or emulator/simulator: Real  device

**Comment by saikrishna321** [comment]
@CathyWY Please use W3C Actions API to perform gestures 

https://appiumpro.com/editions/29

https://github.com/saikrishna321/VodQaAdvancedAppium/blob/master/src/test/java/com/appium/gesture/GestureTest.java

Please ask for help in discuss.appium.io
