### ISSUE TITLE
How to hide keyboard in ios 

### ISSUE THREAD

**Issue by johanntony** [appium/java-client#1058]
How to hide keyboard in ios,i try some way to do this,but failed 
I try to ignore the keyboard to click the btn below the keyboard , the element be found by presenceOfElementLocated ,even the element not null, but still click failed ,so how to deal with it.
For help!

**Comment by mykola-mokhnach** [comment]
XCUITest does not provide any shortcuts to hide keyboard. You must do it same way a normal user of the application would do.

**Comment by johanntony** [comment]
so another question about presenceOfElementLocated, forget the keyboard

**Comment by mykola-mokhnach** [comment]
xctest won't allow you to click an element if it is covered by another one

**Comment by johanntony** [comment]
so how to do in common way!

**Comment by XiMouQiu** [comment]
hello , in my situation, when i enter a textfield, then show a keyBoard with type NumberPad. I've try many ways to hide the keyboard. Like: ((IOSDriver) driver).getKeyboard().pressKey(Keys.CANCEL);  ((IOSDriver) driver).hideKeyboard(HideKeyboardStrategy.TAP_OUTSIDE); and other solutions.But none of them works.Is there other ways to solve this problem? thanks.

**Comment by SrinivasanTarget** [comment]
@johanntony @XiMouQiu Did you tried `((IOSDriver) driver).hideKeyboard("Return");` ?

**Comment by XiMouQiu** [comment]
> @johanntony @XiMouQiu Did you tried `((IOSDriver) driver).hideKeyboard("Return");` ?

yes,I've tried this out. But it didn't work either.My appium version is 1.8.2

**Comment by XiMouQiu** [comment]
> @johanntony @XiMouQiu Did you tried `((IOSDriver) driver).hideKeyboard("Return");` ?

this is the log thar appium shows:

[HTTP] 
[HTTP] --> POST /wd/hub/session/27639ed1-bb65-4071-87b8-4c25cfa52c32/appium/device/hide_keyboard
[HTTP] {"keyName":"Return"}
[W3C] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,"Return","27639ed1-bb65-4071-87b8-4c25cfa52c32"]
[XCUITest] Executing command 'hideKeyboard'
[BaseDriver] Waiting up to 20000 ms for condition
[JSONWP Proxy] Matched '/element' to command name 'findElement'
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"8A000000-0000-0000-B52B-000000000000"},"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waiting up to 20000 ms for condition
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 249 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 1804 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 2700 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 3800 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 4799 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 5577 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 6363 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 7134 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 7929 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 8703 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 9495 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 10288 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 11356 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 12145 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 12960 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 13714 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 14502 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 15292 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 16066 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 16840 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 17627 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 18400 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 19172 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[BaseDriver] Waited for 19939 ms so far
[JSONWP Proxy] Matched '/element/8A000000-0000-0000-B52B-000000000000/elements' to command name 'findElementsFromElement'
[JSONWP Proxy] Proxying [POST /element/8A000000-0000-0000-B52B-000000000000/elements] to [POST http://localhost:61188/session/A8D619C5-25DE-4A7B-B97E-28C1873C3F72/element/8A000000-0000-0000-B52B-000000000000/elements] with body: {"using":"accessibility id","value":"Return"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"A8D619C5-25DE-4A7B-B97E-28C1873C3F72","status":0}
[W3C] Responding to client with driver.hideKeyboard() result: null

**Comment by SrinivasanTarget** [comment]
@XiMouQiu Try on latest version of appium server which is 1.9.2 beta 2.

**Comment by XiMouQiu** [comment]
> @XiMouQiu Try on latest version of appium server which is 1.9.2 beta 2.

hello, thanks for giving advise. I've tried appium server which is 1.9.2-beta.2. And it dosen't work for my problem. Is there any other way to figure out why and what to do next? Or should I need to provide more information about that? Thanks.

**Comment by SrinivasanTarget** [comment]
@XiMouQiu If you run out of all the options which appium provides natively then try to inspect the keyboard return button, find the element and click it.

**Comment by SrinivasanTarget** [comment]
@XiMouQiu Check in discuss forum if you get any other solutions that works for you.

**Comment by XiMouQiu** [comment]
> @XiMouQiu If you run out of all the options which appium provides natively then try to inspect the keyboard return button, find the element and click it.

![img_0227](https://user-images.githubusercontent.com/13887837/48746317-ecb96000-eca9-11e8-91ea-3d4da2029e6e.jpg)
the keyboard looks like that. There is no return button, it's numberPad that iOS system provides.

**Comment by XiMouQiu** [comment]
> @XiMouQiu Check in discuss forum if you get any other solutions that works for you.

ok, thanks.

**Comment by SrinivasanTarget** [comment]
Closing this as there is nothing pending that client or server could do here.
