### ISSUE TITLE
how to locate  element that is offscreen on tableView

### ISSUE THREAD

**Issue by XiMouQiu** [appium/java-client#1065]
## Description

hello, I had  trouble with find elements on tableView which is in the cell that offscreen.With Android there is a function like this
 "(MobileElement) driver.findElement(MobileBy.AndroidUIAutomator(
                "new UiScrollable(new UiSelector())."
                        + "scrollIntoView(new UiSelector().textContains(\"" + textToSearchInList + "\"))"));" could  
automaticly locate the cell even the cell is out of the screen. Does iOS has the same function that can do this?
## Environment

* Appium server version 1.9.1
* appium desktop version is 1.8.2
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: RealDevice

## Code To Reproduce Issue [ Good To Have ]
In ios I use 
        HashMap scrollObject = new HashMap<>();
        scrollObject.put("predicateString", "label CONTAINS[cd] '连子门店003'");
        driver.executeScript("mobile: scroll", scrollObject);

but it doesn't stop when the cell on the screen.

**Comment by SrinivasanTarget** [comment]
@XiMouQiu Please refer [this](http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/) I would suggest to use Actions API on these cases.

**Comment by saikrishna321** [comment]
Please use discuss.appium.io
