### ISSUE TITLE
Getting stale element reference issue when switched to java-client version 6.1.0 but working fine with 5.0.0-BETA9 version

### ISSUE THREAD

**Issue by shagupta92042** [appium/java-client#1066]
## Description

I am working on real android device and my code was working fine with java-client version 5.0.0-BETA9 on hybrid app but when i switched to 6.1.0 java-client version , i started getting stale element reference error .

## Environment

* java client build version : 6.1.0
* Appium server version : 1.8.0-BETA4
* Desktop OS/version : Windows 7
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.9.4
* Mobile platform/version under test: 8.1.0
* Real device or emulator/simulator: Real device

## Details

When we switched to 6.1.0 java-client version , we started getting error of stale element reference even now it does not wait for the element condition. The code is working fine with 5.0.0-BETA9 java-client

## Code To Reproduce Issue [ Good To Have ]

  WebElement selectInstrumentApp = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(text(),'" + exchangeName + "/" + contractName + "/" + contractDate + "')]")));
        common.fnclickableElementClick(selectInstrumentApp);

## Exception stacktraces

[debug] [35m[JSONWP Proxy][39m Proxying [GET /wd/hub/session/c064361c-d23b-4850-835c-6e8a5f9abe31/element/0.29851853247747995-8/displayed] to [GET http://127.0.0.1:8000/wd/hub/session/6abf6a86c6c418e81b2ae8426dde3f62/element/0.29851853247747995-8/displayed] with body: {}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"6abf6a86c6c418e81b2ae8426dde3f62\",\"status\":10,\"value\":{\"message\":\"stale element reference: element is not attached to the page document\\n  (Session info: chrome=70.0.3538.80)\\n  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64)\"}}"
[35m[JSONWP Proxy][39m Replacing sessionId 6abf6a86c6c418e81b2ae8426dde3f62 with c064361c-d23b-4850-835c-6e8a5f9abe31

## Link to Appium logs

https://gist.github.com/shagupta92042/075a1f2cb57055907a771d6b31b1093c

**Comment by SrinivasanTarget** [comment]
@shagupta92042 Please raise questions in appium discuss forum. See if you are getting error in latest [commit](https://github.com/appium/java-client#how-to-install-latest-java-client-betasnapshots).
