### ISSUE TITLE
Capabilities issue running through grid

### ISSUE THREAD

**Issue by cdnyoung** [appium/java-client#1069]
## The problem

When kicking off our test runs (via Bamboo) on a Selenium Grid, the device log returns an error that appears to be related to how the capabilities are being read. I've been trying to find examples of formatting for capabilities, but haven't really found anything definitive.  

1. Can anyone take a look at the log below and let me know where the issue might be? 
2. How are the 'first match' and 'always match' caps supposed to be formatted, and for that matter, how are all the caps supposed to be formatted? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10
* Last Appium version that did not exhibit the issue (if applicable): 1.8.2-beta
* Desktop OS/version used to run Appium: N/A
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Real Device (iPad)

## Details

Not sure as an older version of Appium (1.8.2-beta) works with my configuration..

## Link to Appium logs

https://gist.github.com/cdnyoung/243625ce1a75a31091d1f78670a716d3

**Comment by BrunoCarvalho18** [comment]
Mykola-Mokhnach,

I can help the gentlemen yes.

Thank You.

Best Regards,
Bruno Carvalho.

**Comment by BrunoCarvalho18** [comment]
@cdnyoung, I'm using this dependencies in my pom.xml: https://gist.github.com/BrunoCarvalho18/12c9a2d88fc6b4d550f1d117f3efe2db, it's workin now.

Best Regards,
Bruno Carvalho.

**Comment by BrunoCarvalho18** [comment]
@cdnyoung , show your console and logcat, please ?

**Comment by cdnyoung** [comment]
Hi @BrunoCarvalho18 here's a link to the latest device log using the latest appium java-client commit.

https://gist.github.com/cdnyoung/cf1c6bdbcfc5226b714b220c5cd5c09b

and the Appium log (which doesn't tell too much)...

https://gist.github.com/cdnyoung/8b66d47c6de87561a0cde160d7e4e947

Thanks for your help. We're going into the holiday break, so I may not be able to be as responsive but if you have any idea as to a proper configuration, I'd appreciate it. Like I mentioned before, I wasn't able to get the 6.0.0 version going, and I can't tell which of the capabilities it is getting stuck on, but I've triple-checked the device and it's configuration to make sure it's matching the capabilities listed. 

Do you think this is a compatibility issue with the appium server version, java-client version, etc? From what I understand, there is some combination that should work, but I must be missing something. 
Thanks!

**Comment by BrunoCarvalho18** [comment]
Hello @cdnyoung 

Yes, i'm think this issue with the appium server version and the java-client, i'm change my pom.xml, it´s working for me. Yes there is a combination that work.I'm using:

--Java- Client 6.0

   <dependency>
  <groupId>io.appium</groupId>
  <artifactId>java-client</artifactId>
  <version>6.0.0</version>
  </dependency>

-- My Appium Version is 1.8.2

Thanks!

**Comment by cdnyoung** [comment]
OK, thanks @BrunoCarvalho18, that config is also working for me, but there's an issue with running more than one real device at a time. Hopefully there is a fix for the newer versions coming soon. It's been about 4 months with this issue..

**Comment by BrunoCarvalho18** [comment]
Hello @cdnyoung 
 
Do you open an issue with this question ? 
Do you testing with other version the Appium ?

Thanks!!

**Comment by cdnyoung** [comment]
Hi @BrunoCarvalho18 not for that particular issue, no. I'd like to get the latest versions of appium running so hadn't really focused too much on that. I just run each of the devices separately for now.

I've tried multiple versions of appium (everything from 1.9-1.10 with 6.0.0-7.0.0 bindings), as well as the latest commits from master over the last month here. None have been successful, unfortunately...

**Comment by cdnyoung** [comment]
Just for anyone interested and having similar issues, we found that the capabilities request was malformed. We had moved from a quite a bit older version, so took awhile to find..

we had a capability: platform: "MAC", where it should be platformName: "iOS" instead, and remove platform altogether.

Our setup is working now with appium 1.10.1, java client: 7.0.0 and selenium grid v 3.141.59. Thanks!

**Comment by emzubair** [comment]
> Just for anyone interested and having similar issues, we found that the capabilities request was malformed. We had moved from a quite a bit older version, so took awhile to find..
> 
> we had a capability: platform: "MAC", where it should be platformName: "iOS" instead, and remove platform altogether.
> 
> Our setup is working now with appium 1.10.1, java client: 7.0.0 and selenium grid v 3.141.59. Thanks!

@cdnyoung Thanks for your comment, saved me a lot of trouble.
Your solution worked for me, I'm using `appium v1.17.0` & `selenium grid v3.141.59`.
Here is node config for `iOS`

> {
    "capabilities":
    [
        {
            "platformName": "iOS",
            "maxInstances": 1
        }
    ],
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "host": "127.0.0.1",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "127.0.0.1",
    "hubProtocol": "http"
}
