### ISSUE TITLE
wait.until not throwing exception when search takes more than specified timeout

### ISSUE THREAD

**Issue by sen4ik** [appium/java-client#1070]
## Description

I have following waiter.
```
By btn = By.xpath("//android.widget.TextView[@resource-id='com.rfi.sams.android:id/largeLabel' and contains(@text, 'Home')]");
WebDriverWait wait = new WebDriverWait(driver, 5);
long started = new Date().getTime();
wait.until(ExpectedConditions.visibilityOfElementLocated(btn));
logger.info("Element found within " + (new Date().getTime() - started) + " milliseconds");
```
The issue is that it waits for more than 20 seconds without throwing exception while timeout is set to 5 second.

I have googled that it might be related to implicit wait, so I tried setting up implicit wait to 5 seconds:
```
driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
```
... but that didn't help.

## Environment

* java client build version or git revision if you use some shapshot: b10f521
* Appium server version or git revision if you use some shapshot: 1.10.0
* Desktop OS/version used to run Appium if necessary: Windows 7 Ultimate 64-bit
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Node v10.14.1
* Mobile platform/version under test: Android 8.1 API 27
* Real device or emulator/simulator: Emulator

## Details

I expect wait to throw exception if element if not found within timeout, which in my case is 5 seconds.

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

NA

## Link to Appium logs

https://gist.github.com/sen4ik/87f0996cd934cdcb3a579b4fa35102a7

**Comment by sen4ik** [comment]
If i use same By to find element, it will take 10 seconds.

**Comment by sen4ik** [comment]
It looks like the issue exists only when there is tooltip present for one of the buttons.

![screenshot_1544758924](https://user-images.githubusercontent.com/6224852/49982174-23cd0b00-ff10-11e8-8a05-696e331815b2.png)

**Comment by mykola-mokhnach** [comment]
- Use UIA2/Espresso for Android 6+
- Element interactions might take more time (up to 10 seconds) if the application under test is not in idle state while accessibility operations are being performed.
