### ISSUE TITLE
Java client 6.1.0 stopped working with Browser mob proxy jars

### ISSUE THREAD

**Issue by venkatraman91g** [appium/java-client#1071]
## Description

We are getting "Method not Implemented" exceptions when browser mob proxy is used and driver is initiated with proxy.

## Environment

* Appium Java Client 6.1.0
* Appium 1.9.1
* MAC OS X 13.6
* iOS 11, 12
* Real device or emulator/simulator: Real Device

## Details

We are getting "Encountered internal error running command: NotImplementedError: Method is not implemented"  exceptions when iOS Driver is initiated with Browser Mob Proxy via proxy.

## Code To Reproduce Issue [ Good To Have ]

Capabilities:

[Appium] Capabilities:
[Appium]   app: /Users/user1/Downloads/xyz.ipa
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone 6S
[Appium]   maxTypingFrequency: 5
[Appium]   newCommandTimeout: 720
[Appium]   simpleIsVisibleCheck: true
[Appium]   udid: kdnsfksdfkldsflkdsmfkldsmf
[Appium]   usePrebuiltWDA: true
[Appium]   version: ABCDEFKJFS08
[Appium]   webkitResponseTimeout: 20000
[Appium]   platformName: ios
[Appium]   applicationName: ABCDEFKJFS08
[Appium]   forceMjsonwp: true

## Exception stacktraces

Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[debug] [W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [W3C]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[debug] [W3C]     at new Promise (<anonymous>)
[debug] [W3C]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[debug] [W3C]     at XCUITestDriver.callee$0$0 [as execute] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/commands/execute.js:27:30)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[debug] [W3C]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [W3C]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [W3C]     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [W3C]     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [W3C]     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [W3C]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [W3C]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [W3C]     at runCallback (timers.js:696:18)
[debug] [W3C]     at tryOnImmediate (timers.js:667:5)
[debug] [W3C]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/6d7922d3-834e-49c4-a58b-fdbef35371a5/execute/sync 405 13 ms - 2895

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by venkatraman91g** [comment]
@mykola-mokhnach issue is resolved changed the constructor so that HttpCommandExecutor is not used.
