### ISSUE TITLE
Get the recorded video path

### ISSUE THREAD

**Issue by hemanth-dunzo** [appium/java-client#1075]
@BeforeMethod
driver.launchApp();
driver.startScreenRecording();

@Test
.....

@AfterMethod
String result = driver.stopRecordingScreen();
driver.closeApp();

**Comment by saikrishna321** [comment]
@hemanth-dunzo 

https://github.com/saikrishna321/VodQaAdvancedAppium/blob/master/src/test/java/com/screen/RecordingTest.java#L23

Please ask questions in discuss.appium.io
