### ISSUE TITLE
How to restart IOS application without uninstalling. Please help on this.

### ISSUE THREAD

**Issue by SulariDlm** [appium/java-client#1078]
## Description
I have bellow capabilities.
noReset = true
fullReset = false

@AfterMethod I'm doing  driver.quit() and  driver.launchApp(). 
But always after method, ios application getting uninstall . I'm trying through simulator.

## Code To Reproduce Issue [ Good To Have ]

@AfterMethod
    public void getResult() throws Exception {
        ImplicitWait.waitFor(driver, 5);
        if (!avoidResetApp) {

            driver.quit();
            ImplicitWait.sleepFor(1000);
            driver.launchApp();
           
            //driver = createDriver();
        }
        avoidResetApp = false;
        boolean element = true;

        try {
            ImplicitWait.sleepFor(7000);
            driver.switchTo().alert().accept();
        } catch (NoAlertPresentException e) {
            e.printStackTrace();
        }

    }

    @Test(priority = 0)
    public void verifyUniversityRegistrationSpecificFields()  {
        test = Report.getInstance().getReportTest("verifyUniversityRegistrationSpecificFields");
        try {

            RegistrationElement.signUpLnk(driver).click();
            ImplicitWait.waitFor(driver, 1);

            RegistrationElement.fullNameTxt(driver).click();
            RegistrationElement.fullNameTxt(driver).sendKeys(TestData.getSafeString("FULL_NAME"));
            driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Next");
            ImplicitWait.waitFor(driver, 2);

            RegistrationElement.MobEmailTxt(driver).click();
            RegistrationElement.MobEmailTxt(driver).sendKeys(TestData.getSafeString("UUM_VALIDATION_MAIL"));
            driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Next");
            ImplicitWait.waitFor(driver, 2);

            RegistrationElement.CountryPickerWheel(driver).click();
            ImplicitWait.waitFor(driver, 1);

            RegistrationElement.PasswordTxt(driver).click();
            RegistrationElement.PasswordTxt(driver).sendKeys(TestData.getSafeString("KIPLE_PASSWORD"));
            driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Next");
            ImplicitWait.waitFor(driver, 2);

            RegistrationElement.ConfirmPasswordTxt(driver).click();
            RegistrationElement.ConfirmPasswordTxt(driver).sendKeys(TestData.getSafeString("KIPLE_PASSWORD"));
            driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Done");
            ExplicitWait.waitForElementPresence(driver,20,ElementData.getSafeString("RegistrationElement_signUpBtn"));

            //Screen shot before click on UUM SignUp
            String screenshotPathBeforeClickUUMSignUp = ScreenShot.createScreenShot(driver);
            String imageBeforeClickUUMSignUp = CommonMethods.getInstance().addScreenShotToReport(screenshotPathBeforeClickUUMSignUp,test);
            test.log(LogStatus.INFO, "Before click on 'Sign up with University Registration' button",imageBeforeClickUUMSignUp);

            KipleUNIRegistrationElement.uumSignUpBtn(driver).click();
            ExplicitWait.waitForElementPresence(driver,20,ElementData.getSafeString("KipleUNIElement_universityIdTxt"));

            CommonElement.PageScrollDown(driver);

            //Screen shot after click on UUM SignUp
            String screenshotPathAfterClickUUMSignUp = ScreenShot.createScreenShot(driver);
            String imageAfterClickUUMSignUp = CommonMethods.getInstance().addScreenShotToReport(screenshotPathAfterClickUUMSignUp,test);

            //Verify 3 University fields
            try {
                //University selection field
                Assert.assertEquals(KipleUNIRegistrationElement.dropDwnSelection(driver,5).getText(),"Select University");

                //Campus selection field
                Assert.assertEquals(KipleUNIRegistrationElement.dropDwnSelection(driver,6).getText(),"Select");

                //University Id field
                Assert.assertEquals(KipleUNIRegistrationElement.universityIdTxt(driver).getText(),"University ID");
                test.log(LogStatus.PASS, "Verify 3 University text boxes","University,Campus and University ID text boxes are available");
                test.log(LogStatus.INFO, "After click on 'Sign up with University Registration' button",imageAfterClickUUMSignUp);

            } catch (Exception e) {
                test.log(LogStatus.FAIL, "University or Campus or University ID text boxes are not available",imageAfterClickUUMSignUp);
                test.log(LogStatus.INFO, "Error : "
                        + e.getMessage());
            }catch (AssertionError e) {
                test.log(LogStatus.INFO, "Error : "
                        + e.getMessage(),imageAfterClickUUMSignUp);
                test.log(LogStatus.ERROR, e);
            }

            //Verify University dropdown
            try {
                KipleUNIRegistrationElement.dropDwnSelection(driver,5).click();
                //Verify close button in pickerWheel
                Assert.assertTrue(CommonElement.pageCloseBtn(driver,"'closeWhiteIco')]") !=null);

                String screenshotPathUniversityDropDown = ScreenShot.createScreenShot(driver);
                String imageUniversityDropDown = CommonMethods.getInstance().addScreenShotToReport(screenshotPathUniversityDropDown,test);
                test.log(LogStatus.PASS, "Verify University dropdown",imageUniversityDropDown);

                CommonElement.pickerwheelStep(driver,CommonElement.PickerWheel(driver),"next", 0.15);
                CommonElement.PickerWheel(driver).click();

            } catch (Exception e) {
                test.log(LogStatus.FAIL, "University dropdown not available",imageAfterClickUUMSignUp);
                test.log(LogStatus.INFO, "Error : "
                        + e.getMessage());
            }catch (AssertionError e) {
                test.log(LogStatus.INFO, "Error : "
                        + e.getMessage(),imageAfterClickUUMSignUp);
                test.log(LogStatus.ERROR, e);
            }

            //Verify Campus dropdown
            try {
                Assert.assertEquals(KipleUNIRegistrationElement.dropDwnSelection(driver,6).getText(),"Select Campus");
                KipleUNIRegistrationElement.dropDwnSelection(driver,6).click();

                //Verify close button in pickerWheel
                Assert.assertTrue(CommonElement.pageCloseBtn(driver,"'closeWhiteIco')]") !=null);

                String screenshotPathCampusDropDown = ScreenShot.createScreenShot(driver);
                String imageCampusDropDown = CommonMethods.getInstance().addScreenShotToReport(screenshotPathCampusDropDown,test);
                test.log(LogStatus.PASS, "Verify Campus dropdown",imageCampusDropDown);

                CommonElement.PickerWheel(driver).click();

            } catch (Exception e) {
                test.log(LogStatus.FAIL, "Campus dropdown not available",imageAfterClickUUMSignUp);
                test.log(LogStatus.INFO, "Error : "
                        + e.getMessage());
            }catch (AssertionError e) {
                test.log(LogStatus.INFO, "Error : "
                        + e.getMessage(),imageAfterClickUUMSignUp);
                test.log(LogStatus.ERROR, e);
            }

        } catch (Exception e) {
            String screenshot_path = ScreenShot.createScreenShot(driver);
            String image = null;
            try {
                image = CommonMethods.getInstance().addScreenShotToReport(screenshot_path,test);
            } catch (Exception e1) {
                e1.printStackTrace();
            }

            test.log(LogStatus.FAIL, "verifyUniversityRegistrationSpecificFields", image);
            test.log(LogStatus.INFO, "Error in test verifyUniversityRegistrationSpecificFields : "
                    + e.getMessage());
            Report.getInstance().endReportTest(test);
        }catch (AssertionError e) {
            test.log(LogStatus.INFO, "Error : "
                    + e.getMessage());
            test.log(LogStatus.ERROR, e);
            Report.getInstance().endReportTest(test);
        }

    }

**Comment by saikrishna321** [comment]
Please use discuss.appium.io for help and questions.
