### ISSUE TITLE
Can I get the whole information of an Element when I find it by one attribute?

### ISSUE THREAD

**Issue by tykuyh** [appium/java-client#1080]
## Description

For example:
driver.findElementById("name.gudong.translate:id/sp_translate_way").click();
this sentence can help me locate a widget. 
Can I get the whole information of this widget, such as xpath of this widget, activity of this widget, etc. by some API of Appium?
Or is there any way to modify java-client to help me get these information?
Thank you!
## Environment
Appium Java source code

**Comment by SrinivasanTarget** [comment]
@tykuyh Please raise questions in appium discuss forum.
