### ISSUE TITLE
Getting NoSuchElementException when I try to execute an iOS script in appium with @iOSXCUITBy annotation.

### ISSUE THREAD

**Issue by srikantharuban** [appium/java-client#1082]
Steps to recreate
1. Use following element locator code in the POM.

@iOSXCUITBy(xpath="//XCUIElementTypeStaticText[@name="John Appleseed"]")
public IOSElement e;
2. Write a script to click on the element.
3. Run the script and verify the output.

Actual results
Observed that execute got failed saying that (org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.id: e) even though I used xpath as an element locator. Find the attached appium log below. 
[appium-server-logs.txt](https://github.com/appium/java-client/files/2719057/appium-server-logs.txt)

@iOSXCUITBy(xpath="//XCUIElementTypeStaticText[@name="John Appleseed"]")
public IOSElement e;

Capability details
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("platformName", "iOS");
cap.setCapability("platformVersion", "12.1");
cap.setCapability("deviceName", "iPhone XR (12.1)");
cap.setCapability("udid", "5A972FE2-30B7-450E-BAC4-D36008CAD0B8");
cap.setCapability("bundleId", "com.apple.MobileAddressBook");
cap.setCapability("automationName", "XCUITest");

Appium version : Appium v1.9.1
Java client : 6.1.0
XCode : Version 10.1 (10B61)

**Comment by saikrishna321** [comment]
@srikantharuban Please refer this https://github.com/appium/java-client/blob/master/docs/Page-objects.md#mixed-chainany-locator-strategy

Should be 

```
@iOSXCUITFindBy(xpath="//XCUIElementTypeStaticText[@name="John Appleseed"]")
```
I would recommend to use  accesbilityId or iOSNsPredicate instead of 

```
@iOSXCUITFindBy(accessibility="John Appleseed")

@iOSXCUITFindBy(iOSNsPredicate = "name = 'John Appleseed'")
```

**Comment by srikantharuban** [comment]
Ok thanks and what is the use of @iOSXCUITBy annotation?

**Comment by saikrishna321** [comment]
```
@iOSXCUITFindAll(value = {@iOSXCUITBy(accessibility = "username"),
            @iOSXCUITBy(accessibility = "password")})
    public MobileElement userAndPassword;
```

Located by By.chained({By.all({By.AccessibilityId: username,By.AccessibilityId: password})})

**Comment by srikantharuban** [comment]
Thanks...
