### ISSUE TITLE
'io.appium.java_client.pagefactory.iOSFindBy' is deprecated

### ISSUE THREAD

**Issue by Suban5** [appium/java-client#1089]
## Description

In java-client 6.0.0, i am able to use 'io.appium.java_client.pagefactory.iOSFindBy' but in java client 7.0.0 it is depreciated. How we can iOSFindBy in version 7.0.0? Is there any alternative for this?

## Environment

* java client build version 7.0.0:
* Appium server version 1.9.0

**Comment by SrinivasanTarget** [comment]
You can use `iOSXCUITFindBy`.
