### ISSUE TITLE
@AndroidBy(accessibility = "accessibilityId") annotation is not using accessibility id strategy

### ISSUE THREAD

**Issue by shane51** [appium/java-client#1111]
## Description
AndroidFindBy annotation is not working when use  accessibility id.  code as below
 When I use ios, it works fine, but it's weird on android, which use id="tryALessionButton", looks like the AndroidFindBy annotation is not detected at all.
```java
    @iOSXCUITFindBy(accessibility = "tryALesson")
    @AndroidBy(accessibility = "tryALesson")
    public MobileElement tryALessionButton;

    @iOSXCUITFindBy(accessibility = "Allow")
    @AndroidBy(accessibility = "OK")
    public MobileElement acceptAlert;

    public OnBoardingPage(AppiumDriver<MobileElement> driver) {
        super(driver);
        PageFactory.initElements(new AppiumFieldDecorator(driver), this);

    }
```
From Appium log, it shows:
```
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8201/wd/hub/session/6308e6d8-5ffc-449d-a65f-8d1ef71764ce/element] with body: {"strategy":"id","selector":"tryALessionButton","context":"","multiple":false}
```

## Environment

* java client build version or git revision if you use some shapshot: 7.0.0
* Appium server version or git revision if you use some shapshot: 1.10.0/ 1.11.1
* Desktop OS/version used to run Appium if necessary: MacOS 10.14.2
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: node v8.15.0
* Mobile platform/version under test: android 7.0
* Real device or emulator/simulator: Samsung Galaxy Note8

## Appium Log
https://gist.github.com/shane51/c92551170c99f803ba6364ded89eb483

**Comment by scophotog** [comment]
For android if your id is "tryALessionButton" Then your annotation should be
@AndroidBy(id = "tryALesson")

Additionally I believe it should be using @AndroidFindBy and not @AndroidBy

**Comment by shane51** [comment]
Thanks @scophotog My mistake.. it should be @AndroidFindBy

**Comment by junghanChoi** [comment]
As the above comments say, 

AndroidBy not working for me.
AndroidFindBy works.
