### ISSUE TITLE
@WithTimeout does not change/affect driver.findElement time, Appium java client 6.1.0

### ISSUE THREAD

**Issue by sleknizi** [appium/java-client#1113]
I have a PageFactory class which is initiated like this:
**_HomePage homepage = new HomePage(driver);_**
**_PageFactory.initElements(new AppiumFieldDecorator(driver), this);_**
In fact, pages initialization command with timout «**_PageFactory.initElements(new AppiumFieldDecorator(driver,new TimeOutDuration(10, TimeUnit.SECONDS)),this);_**» is moved from appium new versions(I'm using appium version : 6.1.0).

 Then inside my homepage class, I have a variety of elements. Now I want to change(reduce) the TimeOut duration for some of them so I'm using
**_@WithTimeout(time = 5, chronoUnit = ChronoUnit.SECONDS)
@AndroidFindBy(xpath = "..")
@iOSFindBy(xpath = "...)
MobileElement element;_**

However this has no effect on the time the driver takes to search for the element, the duration is still 10 seconds(the value that I have set on the class constructor using
'**_driver.manage().timeouts().implicitlyWait(TIMEOUT_VALUE, TimeUnit.SECONDS);_**').  

any idea, why the @WithTimeout is not working anymore however it was working fine on Appium's version 4!!!!

**Comment by scophotog** [comment]
Where does `new TimeOutDuration(10, TimeUnit.SECONDS)` come from. I believe you should be using `Duration.ofSeconds(10)` instead.


I gave this one a shot using the API Demos App that comes with android emulators.

```
    @WithTimeout(time = 5, chronoUnit = SECONDS)
    @FindBy(id = "android:id/text100000") //Faking a missing element
    private WebElement textView;

    PageFactory.initElements(new AppiumFieldDecorator(driver, ofSeconds(10)), this);


        try {
            now = System.currentTimeMillis();
            textView.getAttribute("text");
        } catch (Exception e) {
            System.out.println(now - System.currentTimeMillis());
        }
```

When I ran the above code in an @Test method I got the timing to be 5 seconds. Do you have any more details?

**Comment by sleknizi** [comment]
Hello @scophotog,
Thanks for your reply, can you try to run this script : 

**_@WithTimeout(time = 5, chronoUnit = SECONDS)
    @FindBy(id = "android:id/text100000") //Faking a missing element
    private WebElement textView;
    PageFactory.initElements(new AppiumFieldDecorator(driver, ofSeconds(10)), this);
     try {
              now = System.currentTimeMillis();
              textView.getAttribute("text");
    } catch (Exception e) {
             System.out.println(now - System.currentTimeMillis());
    }
  driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
  try {
            now = System.currentTimeMillis();
            textView.getAttribute("text");
  } catch (Exception e) {
            System.out.println(now - System.currentTimeMillis());
   }_**

When you ran the above code in an @test method you will get 5 seconds on the first find and 10 seconds on the second find. this is how the driver.manage().timeouts()... affect the @withTimeout functionality. (FYI, I have tested the same script on Appium version 4 and I got 5 seconds as finding element time even I setted the driver timout using driver.manage().time...)

**Comment by scophotog** [comment]
I believe I see what is going on here.
When you use:
`@WithTimeout(time = 5, chronoUnit = SECONDS)`
That is putting an explicit wait on that element to wait for 5 seconds.

When you add
`driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);`
You're adding an implicit wait for all elements.

The explicit wait is polling the Appium server while expecting a NoSuchElementError for 5 seconds  then gives up after 5 seconds.
When the implicit wait is set a request it sent to get the element then the server is waiting for up to 10 seconds to find the element and then it will throw a NoSuchElementError

Mixing these two is not a good idea.

If you look at the Appium logs you can see in the first part where we only use the implicit wait, you can see the polling occurring. In the second half with the implicit wait you can see the server replying back to the client along with how much time it has waited.

Things are more interesting if you do this:
```
@WithTimeout(time = 10, chronoUnit = SECONDS)
@findby(id = "android:id/text100000") //Faking a missing element

driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
```

The explicit wait on the element is going to wait 10 seconds by sending a request to the server, then the server is going to respond by saying it's waiting for up to 5 seconds for the element to appear. When it fails to appear it returns a NoSuchElement error but there are still 5 more seconds from the explicit wait so it's going to send another request and then the implicit wait takes over again.  You get your total wait of 10 seconds.

**Comment by saikrishna321** [comment]
Please do not use implicit waits and please ask for questions and help in discuss.appium.io
