### ISSUE TITLE
Clarification : Hidekeyboard and presskeycode functions are missing in the java-client 7.0.0 latest.

### ISSUE THREAD

**Issue by srikantharuban** [appium/java-client#1114]
In latest 7.0.0 following methods are missing in the driver. 

  1. HideKeyboard
  2. PressKeyCode 

I tried using following code.

public static AndroidDriver<AndroidElement> androiddriver;
androiddriver=new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);

1. androiddriver.hideKeyboard()
2. androiddriver.PressKeycode()

**Comment by scophotog** [comment]
What version are you coming from? Are there no other methods missing? Did you rebuild your project after doing the upgrade?

Though presskeycode() looks like is now pressKey()

**Comment by srikantharuban** [comment]
<version>4.1.2</version> this is the version I have used previously for my project. After updating to latest 7.0.0 now above methods are not found. I couldn't find any related documentation for new functions which are replacing above. Could you please let me know the syntax for new functions. Even appium documentation also not updated for latest methods.

**Comment by scophotog** [comment]
Things have changed a lot since 4.1.2. I might suggest try incrementing versions. Like go to 5.0.0 then 6.0.0 etc and see where it breaks.

hideKeyboard() exists and is implemented.
        java-client/src/main/java/io/appium/java_client/HidesKeyboard.java

Though you should try instead pressKey() instead of pressKeyCode if you're using the latest client.

**Comment by scophotog** [comment]
No problem. AndroidDriver implements PressesKey which has pressKey()

**Comment by srikantharuban** [comment]
Got it thanks for the support. It works for me.
