### ISSUE TITLE
Add missing enums to Setting.java file

### ISSUE THREAD

**Issue by MoOoG** [appium/java-client#1119]
## Description

Some Settings API enums are missing in 'io.appium.java_client.Setting.java' file that needs to be added. These are documented here: [The Settings API](http://appium.io/docs/en/advanced-concepts/settings/)

Missing enums:
- mjpegServerScreenshotQuality
- mjpegServerFramerate
- screenshotQuality
- shouldUseCompactResponses
- elementResponseAttributes
- allowInvisibleElements
- enableNotificationListener
- 

## Environment

* java client version 7.0.0
## Code To Reproduce Issue [ Good To Have ]

`((AndroidDriver) driver).setSetting([Setting.enum], [value]);`

**Comment by saikrishna321** [comment]
PR merged. Closing
