### ISSUE TITLE
@FindBy locators is not working in the webview context when we have @AndroidFindBy and @IOSFindBy

### ISSUE THREAD

**Issue by fabytta** [appium/java-client#1122]
## @FindBy does not work any more

when I switch to the webview context, the appium client should use the locator defined in @FindBy and it should use the @AndroidFindBy and @iOSFindBy only when I'm in native contexts on Android and iOS platforms, but since we updated the appium-java client to 6.1.0, even in Webview context I get only @AndroidFindBy and @iosFindBy used

## Environment

* Appium version (or git revision) 6.1.0
* Last Appium version that did not exhibit the issue (if applicable): 4.1.2
* Desktop OS/version used to run Appium:  do not know : using a cloud service
* Node.js version (unless using Appium.app|exe): do not know : using a cloud service
* Npm or Yarn package manager: do not know : using a cloud service
* Mobile platform/version under test : all paltforms / OS versions
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: do not know : using a cloud service

## Code To Reproduce Issue [ Good To Have ]
define your elements :
   @FindBy(xpath = "//input[@id='personalInfo-firstName' or @id='addressInfo-firstName']")
    @AndroidFindBy(xpath = "//*[@resource-id='personalInfo-firstName']")
    @iOSFindBy(xpath = "//*[@label='personalInfo-firstName']")
    private MobileElement firstName;

in the test switch to webview context -> switch done sucessfully (and it's a webview page wrapped in the app)
try to find the element and send key -> in the report I find that the driver try to find the element by the  locator declared in the @AndroidFindBy (or @iOSFindBy when I'm on iOS) 

PS when I remove the two annotations @AndroidFindBy and @iOSFindBy, it looks then for the xpath declared in the @FindBy

**Comment by saikrishna321** [comment]
I'm unable to reproduce this using latest java-client and server. Can you please provide a sample code

**Comment by fabytta** [comment]
Hi 
to reproduce it you need to 
- have application with native and webviews contents so you can switch between the two context during the tests
- instantiate the driver as an adroid driver
- use both @AndroidFindBy and @FindBy annotation for the same elements 
- once you are on the webview page, switch to the webview context and try to interact with the element

in this situation, once on the webview context, the java client should search the element wit the xpath in the @FindBy annotation (at least that was the behaviro in the last version of java client we were using 4.1.2)

**Comment by saikrishna321** [comment]
Can you please post full logs

**Comment by saikrishna321** [comment]
Closing as Inactive. Please raise a new issue if still exists
