### ISSUE TITLE
click is not working with java_client 6.1.0 and appium 1.8.1

### ISSUE THREAD

**Issue by anilkn72** [appium/java-client#1124]
## Description
click is not happening using java client 6.1.0 and appium 1.8.1 

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:   6.0.1
* Real device or emulator/simulator:  Real device

## Details

click and Touch Action also not working

## Code To Reproduce Issue [ Good To Have ]
new TouchAction(baseClass.getDriver()).tap(tapOptions().withElement(element(storeElement)).perform();

or

touch.press(PointOption.point(541, 853)).waitAction(waitOptions(ofSeconds(3000))).release.perform();

# Link to Appium logs

https://gist.github.com/anilkn72/b07636fe93aafa8483ebc75913089c04

**Comment by saikrishna321** [comment]
Can you please the latest appium beta version

**Comment by anilkn72** [comment]
I have an issue, in which i search for a word which displays by entering 3 letters, how to click on the displayed word. The click and touchAction is also not working it.Can you please help me.

**Comment by saikrishna321** [comment]
Please use discuss.appium.io for questions an help.
