### ISSUE TITLE
Drag and drop issue

### ISSUE THREAD

**Issue by manjunathkonkalmatth** [appium/java-client#1131]
PointerInput finger = new PointerInput(PointerInput.Kind.TOUCH, "finger");
    Sequence dragNDrop = new Sequence(finger, 0);
    dragNDrop.addAction(finger.createPointerMove(Duration.ofSeconds(0),
            PointerInput.Origin.viewport(), source.x, source.y));
    dragNDrop.addAction(finger.createPointerDown(PointerInput.MouseButton.MIDDLE.asArg()));
    dragNDrop.addAction(new Pause(finger,Duration.ofMillis(600)));
    dragNDrop.addAction(finger.createPointerMove(Duration.ofSeconds(1),
            PointerInput.Origin.viewport(),target.x, target.y));
    dragNDrop.addAction(finger.createPointerUp(PointerInput.MouseButton.MIDDLE.asArg()));
    driver.perform(Arrays.asList(dragNDrop));

from the above code driver.perform(Arrays.asList(dragNDrop)); line is giving hot compiler error saying "The method perform(List<Sequence>) is undefined for the type WebDriver".

do we need to import any extra package here.

**Comment by krantos** [comment]
look into the java-client tests (this project), you will find a drag and drop test

[https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidTouchTest.java](url)

**Comment by krantos** [comment]
TouchAction class is who does the perform, not the driver.

**Comment by manjunathkonkalmatth** [comment]
ended with below shown exception

[W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "The '{
[W3C]     duration = 0;
[W3C]     type = pause;
[W3C] }' action item must be preceded by pointerMove item" UserInfo={NSLocalizedDescription=The '{
[W3C]     duration = 0;
[W3C]     type = pause;
[W3C] }' action item must be preceded by pointerMove item}

**Comment by krantos** [comment]
can you provide more info, system? appium version? android, ios or browser? etc...

**Comment by saikrishna321** [comment]
@manjunathkonkalmatth Pls use Point API - https://github.com/saikrishna321/VodQaAdvancedAppium/blob/master/src/test/java/com/appium/gesture/GestureTest.java#L61

https://appiumpro.com/editions/29
