### ISSUE TITLE
Feature: Add support for "driver.status()"

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#1137]
## Description

Please add support for driver status.

http://appium.io/docs/en/commands/status/
https://github.com/appium/appium/issues/12490

## Environment

* java client build version or git revision if you use some shapshot: 7.0.0
* Appium server version or git revision if you use some shapshot: 1.13.0-beta.3

**Comment by anilkrverma** [comment]
The implementation for this issue is merged in the master branch and should be live in next appium-java-client release.

**Comment by saikrishna321** [comment]
You can get the latest master commit from jitpack to use and need not wait for release.
