### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by Ljo2017** [appium/java-client#1162]
## Description

In Appium 1.13.0 tvOS support has been added, however I'm unable to launch WebDriverAgentRunner_tvOS.app successfully as xcodebuild fails. It appears that the 'platformName' capability gets overwritten as 'iOS' even though it's set to 'tvOS' in desired capability when calling IOSDriver(url, capabilities) therefore the option scheme is still set to WebDriverAgentRunner instead of WebDriverAgentRunner_tvOS. Guessing this override happens somewhere in setCapability() in the java-client?

In MobilePlatform.java, String TVOS = "tvOS" is defined in this pr #1142 but not used anywhere.

Just wanted to know whether I'm doing something wrong and need to dig more or it's simply not supported in java client yet.

## Environment

* java client build version: 7.0
* Appium server version : 1.13.0
* Desktop OS/version: MacOS 10.14.5
* Mobile platform/version under test: tvOS
* Real device or emulator/simulator: simulator

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/java-client/files/3321189/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
ah... around

https://github.com/appium/java-client/blob/9755c9842e38cc116aa37bd53d8f6d9d6c1bf772/src/main/java/io/appium/java_client/ios/IOSDriver.java#L84-L86

?

**Comment by Ljo2017** [comment]
I'm guesing so, either that or around https://github.com/appium/java-client/blob/9755c9842e38cc116aa37bd53d8f6d9d6c1bf772/src/main/java/io/appium/java_client/ios/IOSDriver.java#L215

**Comment by KazuCocoa** [comment]
The current master should work. @Ljo2017 
Could you try via jitpack?

**Comment by Ljo2017** [comment]
I can launch the tv app now thank you @KazuCocoa and @mykola-mokhnach
