### ISSUE TITLE
Appium_Error : Returned value cannot be converted to WebElement with Xcode 10.0

### ISSUE THREAD

**Issue by bindacharyaj** [appium/java-client#1168]
## The problem

Appium_Error : Returned value cannot be converted to WebElement with Xcode 10.0
Appium launches the app but not able to click on any of the native elements.

## Environment

Xcode Version : 10.0 
Appium Server Version : 1.9.1 / 1.13.0
Appium Client Version : 6.1.0 / 7.0.0
Selenium Version : 3.9.1 / 3.14.0
IOS Simulator Version : 11.4

## Details

If necessary, describe the problem you have been experiencing in more detail.

## No Error in Appium Logs for the same

Have tried with different versions as below:
Appium Server version : from 1.7.2 to 1.14.2 beta
Appium Client version : 5.0.4 to 7.0.0
Also tried to include implicit wait and explicit waits as well. No luck :(

Any help would be appreciated!!

Thanks in advance... !!!!

**Comment by bindacharyaj** [comment]
This is part of  pom.xml file:


<dependencies>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.1.0</version> 
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-text</artifactId>
			<version>1.6</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.14.0</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.11</version>
		</dependency>

**Comment by bindacharyaj** [comment]
@mykola-mokhnach : Any help with this details?

**Comment by KazuCocoa** [comment]
Could you try out the latest, 7.x, series?
https://github.com/appium/java-client#how-to-install-latest-java-client-betasnapshots

**Comment by bindacharyaj** [comment]
Had tried with 7.0.0 as well. No luck.
Any problem with XCode 10.0 ?

**Comment by bindacharyaj** [comment]
Tried with XCode version 10.2.1 and also with latest appium 1.14.0-beta2 and client 7.0.0 combination , still getting the same error @KazuCocoa  @mykola-mokhnach 
Please suggest something here 
Thanks!!

**Comment by KazuCocoa** [comment]
Returned format looked good.

```
[WD Proxy] Got response with status 200: {"value":{"ELEMENT":"2B000000-0000-0000-777A-000000000000"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":0}
[W3C (5fc229a9)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"2B000000-0000-0000-777A-000000000000","ELEMENT":"2B000000-0000-0000-777A-000000000000"}
[HTTP] <-- POST /wd/hub/session/5fc229a9-5c42-4b24-8d31-7ba0de473340/element 200 5845 ms - 137
```

Could you attach your the latest client log?

**Comment by bindacharyaj** [comment]
Any help guys @KazuCocoa  @mykola-mokhnach  please

**Comment by SrinivasanTarget** [comment]
> Build info: version: '3.5.2'

Above latest logs clearly says your selenium version is out of date. Invalidate cache and restart your IDE and get latest dependencies.

**Comment by bindacharyaj** [comment]
Thanks @SrinivasanTarget . Issue got resolved with Eclipse cache problem. 
Had to remove.m2 completely and re-built the project again.
