### ISSUE TITLE
Use new settings without selenium-4 dependency

### ISSUE THREAD

**Issue by ogasawara-shift** [appium/java-client#1178]
## Description

It is awesome that the version 7.1.0 provides the new settings like these:

> - TRACK_SCROLL_EVENTS, ALLOW_INVISIBLE_ELEMENTS, ENABLE_NOTIFICATION_LISTENER, NORMALIZE_TAG_NAMES and SHUTDOWN_ON_POWER_DISCONNECT Android Settings were added.
> - KEYBOARD_AUTOCORRECTION, MJPEG_SCALING_FACTOR, MJPEG_SERVER_SCREENSHOT_QUALITY, MJPEG_SERVER_FRAMERATE, SCREENSHOT_QUALITY and KEYBOARD_PREDICTION iOS Settings were added.
> - GET_MATCHED_IMAGE_RESULT, FIX_IMAGE_TEMPLATE_SCALE, SHOULD_USE_COMPACT_RESPONSES, ELEMENT_RESPONSE_ATTRIBUTES and DEFAULT_IMAGE_TEMPLATE_SCALE settings were added for both Android and iOS #1166, #1156 and #1120

However, the version also update dependency of selenium-java from 3 to 4 (even selenium-4 is still in alpha stage), thus our project can't use 7.1.0 (or higher, maybe).

(I guess this is an intentional change, as CHANGELOG explicitly mentions this dependency update)

Could you please consider to release the version (7.0.1 or something) which support these (at least some) settings but selenium-4-independent, if your release policy allows it?

## Environment

* java client build version: 7.1.0
* Appium server version: N/A
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: N/A
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A

**Comment by SrinivasanTarget** [comment]
@ogasawara-shift Thanks for raising a valid concern. Will think through and get back to you on this. But for now, you can still use 7.1.0 by excluding Selenium(alpha) dependency from java client and adding Selenium dependency(only the previous one i.e 3.141.59) directly in your pom.xml or Gradle file. FYI - If selenium dependency is downgraded further it might raise conflicts.

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/releases/tag/v7.2.0

**Comment by ogasawara-shift** [comment]
Cool, thanks!
