### ISSUE TITLE
Screen orientation does not work, for Java_client 1.7.0

### ISSUE THREAD

**Issue by priyankshah217** [appium/java-client#118]
Hi,

I want to change screen orientation, during tests on mobile web. As per server log it says unimplemented method.

Please find below link of my script:
https://github.com/priyankshah217/AppiumTestAutomation/blob/master/src/test/java/com/test/googlesearch/screens/AbstractScreen.java

Appium Server log:

info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/156419e631507860e6cce65f8bd816e4","method":"GET"}
info: [debug] Proxied response received with status 200: "{\"sessionId\":\"156419e631507860e6cce65f8bd816e4\",\"status\":0,\"value\":{\"acceptSslCerts\":true,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"handlesAlerts\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"nativeEvents\":true,\"platform\":\"ANDROID\",\"rotatable\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"version\":\"37.0.2062.117\",\"webStorageEnabled\":true}}"
info: <-- GET /wd/hub/session/156419e631507860e6cce65f8bd816e4 200 8.028 ms - 476
info: --> POST /wd/hub/session/156419e631507860e6cce65f8bd816e4/timeouts/implicit_wait {"ms":3000}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/156419e631507860e6cce65f8bd816e4/timeouts/implicit_wait","method":"POST","json":{"ms":3000}}
info: [debug] Proxied response received with status 200: {"sessionId":"156419e631507860e6cce65f8bd816e4","status":0,"value":null}
info: <-- POST /wd/hub/session/156419e631507860e6cce65f8bd816e4/timeouts/implicit_wait 200 8.273 ms - 72
info: --> POST /wd/hub/session/156419e631507860e6cce65f8bd816e4/url {"url":"http://google.com/"}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/156419e631507860e6cce65f8bd816e4/url","method":"POST","json":{"url":"http://google.com/"}}
info: [debug] Proxied response received with status 200: {"sessionId":"156419e631507860e6cce65f8bd816e4","status":0,"value":null}
info: <-- POST /wd/hub/session/156419e631507860e6cce65f8bd816e4/url 200 4324.785 ms - 72
info: --> POST /wd/hub/session/156419e631507860e6cce65f8bd816e4/orientation {"orientation":"LANDSCAPE"}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/156419e631507860e6cce65f8bd816e4/orientation","method":"POST","json":{"orientation":"LANDSCAPE"}}
info: [debug] Proxied response received with status 501: "unimplemented command: session/156419e631507860e6cce65f8bd816e4/orientation"
info: <-- POST /wd/hub/session/156419e631507860e6cce65f8bd816e4/orientation 501 8.164 ms - 75
info: --> DELETE /wd/hub/session/156419e631507860e6cce65f8bd816e4 {}
info: Shutting down appium session
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection

Thanks,
Priyank Shah

**Comment by aniket-21** [comment]
Is this still an open issue

**Comment by priyankshah217** [comment]
@Jonahss , This is not issue since it works well in native context. so closing this.
