### ISSUE TITLE
v7.1.0 is not available through jitpack.io

### ISSUE THREAD

**Issue by sen4ik** [appium/java-client#1187]
## Description

Appium java-client v7.1.0 is not available as a maven dependency through jitpack.io.

Screenshot shows that only v7.0.0 does have OK status and can be used through jitpack.io.
![2019-07-17 22_21_10-Window](https://user-images.githubusercontent.com/6224852/61431112-43cb0f80-a8e1-11e9-8180-faa22deadb0c.png)

Following build log might be useful https://jitpack.io/com/github/appium/java-client/v7.1.0/build.log

Same issue with v6.1.0 and v6.0.0. The only version that works is v7.0.0.
The issue holds me from using latest version of Appium java-client.

## Ecxeption stacktraces
[ERROR] Failed to execute goal on project TestValidator: Could not resolve dependencies for project org.TestValidator:1.0-SNAPSHOT: Failure to find com.github.appium:java-client:jar:v7.1.0 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or up dates are forced -> [Help 1]

**Comment by sen4ik** [comment]
Please let me know if i should've reported above to https://github.com/jitpack/jitpack.io/issues

**Comment by sen4ik** [comment]
Since i got not replies, i have logged issue to jitpack.io here https://github.com/jitpack/jitpack.io/issues/3906

**Comment by SrinivasanTarget** [comment]
@sen4ik Its already released to maven central. Please pick it from there. I see latest commit is available in jitpack if you wanted to.

**Comment by sen4ik** [comment]
@SrinivasanTarget Thank you.
