### ISSUE TITLE
Appium Driver, throws null pointer exception in iOS 13 Beta

### ISSUE THREAD

**Issue by chethanshetty09** [appium/java-client#1195]
## Description

While initializing the Appium Driver, throws null pointer exception in iOS 13 Beta. Cannot run my test on Appium 1.13.0 with iOS 13 Beta OS.

Throws: XCApplicationQuery elementSnapshotForDebugDescription]: unrecognized selector sent to instance 0x280e62dc0 error.

## Environment

* java client: 7.0.0
* Appium server version : 1.13.0
* Desktop OS/version used to run Appium if necessary: 1.13.0
* Node.js version : 11.7.0
* Mobile platform/version under test: iOS 13 Beta 3
* Real device: iPhone 7 plus
MAC version: 10.14.5
Xcode: 11 Beta

## Code To Reproduce Issue [ Good To Have ]

```
import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.ios.IOSDriver;
import java.net.URL;

public class RunTest {

    public static final String URL = "http://0.0.0.0:4723/wd/hub";

static AppiumDriver driver;
    public static void main(String[] args) throws Exception {

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", "iPhone 7 plus");
        capabilities.setCapability("platformVersion", "13.0");
        capabilities.setCapability("udid","5df840e0a62c7adc7c0fe4759fbbbd280a");
        capabilities.setCapability("app", "com.test.demo");
        capabilities.setCapability("browserName", "");
        capabilities.setCapability("deviceOrientation", "portrait");
        capabilities.setCapability("appiumVersion", "1.13.0");

        try {
            new IOSDriver(new URL(URL), capabilities);
        }catch (Exception e){
            e.printStackTrace();
        }


        driver.quit();
    }
}
```

## Exception stacktraces

Please find the stacktraces here https://gist.github.com/chethanshetty09/3473e33c7515e7f29c0cf392ea2b960f

## Link to Appium logs
https://gist.github.com/chethanshetty09/b0f12f630dd3a8c135d8c80058401010

**Comment by mykola-mokhnach** [comment]
Beta compatibility is tracked in https://github.com/appium/appium/issues/12960

In general, one has to use Appium@beta to test beta versions of mobile platforms
