### ISSUE TITLE
Unable to install android apk using appium.

### ISSUE THREAD

**Issue by Upma-10** [appium/java-client#1207]
## Description

I am trying to install an apk, placed on my desktop, using appium. But, I got the error , Exception in thread "main" org.openqa.selenium.json.JsonException: Unable to determine type from: /. Last 41 characters read: {
  "desiredCapabilities": {
    "app": /

## Environment

* java client build version - 7.1.0
* Appium server version  - v1.13.0
* Desktop OS/version used to run Appium- MacOS ver 10.14.5 
* Node.js version - v10.16.0
* Mobile platform/version under test: Samsung J7 Nxt - Android version 8.1.0
* Real device or emulator/simulator - Real Device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

package self_heal;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.*;

import io.appium.java_client.android.*;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

public class Selfhealapp {

	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		// TODO Auto-generated method stub
		File f=new File("/Users⁩/⁨xxxxxxxxxx/⁨Desktop/xxxxxxxxxxx.apk");
		
		DesiredCapabilities cap=new DesiredCapabilities();
		cap.setCapability("automationName","UiAutomator2");
		cap.setCapability("deviceName","Samsung J7Nxt");
		cap.setCapability("platformName","Android");
		cap.setCapability("platformVersion","8.1.0");
		cap.setCapability("adbExecTimeout", "200000");
        cap.setCapability("app",f);
        cap.setCapability("appPackage","com.xxxxxx.xxxxxxxx.debug");
        cap.setCapability("appActivity","com.xxxxxx.xxxxxxxx.debug.MainActivity");
        
        URL url = new URL("http://xxx.xx.xx.xx:4723/wd/hub");
        AndroidDriver<WebElement> driver = new AndroidDriver<WebElement>(url, cap);
        Thread.sleep(10000);
        
        
        
	}

}

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by aldochristiaan** [comment]
You don't have to set the app as file, just pass the directory of the app ..
`ex: /home/user/Desktop/xxxxx.apk`

**Comment by priyankshah217** [comment]
cap.setCapability("app",f); -- It should be string (File path)

**Comment by SrinivasanTarget** [comment]
feel free to reopen if you face issue further

**Comment by JGDStein** [comment]
hi, guys, actually I'm getting the same issue, could someone help me to solve this?

I'm getting this issue:

Exception in thread "main" org.openqa.selenium.json.JsonException: Unable to determine type from: /. Last 41 characters read: {
  "desiredCapabilities": {
    "app": /
    
**Actually my envoronment is:** 

- Java client build version - 7.6.0
- Appium server version - v1.21.0
- Desktop OS/version used to run Appium- MacOS ver 11.6.7
- Node.js version - v17.8.0
- Mobile platform/version under test: Samsung Galaxy S9 - Android version 10
- Real device or emulator/simulator - Real Device

**Code to reproduce the Issue**

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.android.AndroidElement;
import org.openqa.selenium.remote.DesiredCapabilities;



import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

public class base {


     public static AndroidDriver capabilities()  throws MalformedURLException {
        //TODO: Auto generate

         File appDirectory = new File("src");
         File app = new File(appDirectory, "ApiDemos-debug.apk");
         DesiredCapabilities cap = new DesiredCapabilities();

         cap.setCapability(MobileCapabilityType.DEVICE_NAME,"3652495741573398");
         cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
         cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10");
         cap.setCapability(MobileCapabilityType.APP, app.getAbsoluteFile());
         cap.setCapability("adbExecTimeouts", "20000");

         //UI Automator -> Android
         cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");

         cap.setCapability("appPackage","io.appium.android.apis");
         cap.setCapability("appActivity", "io.appium.android.apis.ApiDemos");

         URL url = new URL("http://localhost:4723/wd/hub");
         AndroidDriver<AndroidElement> driver = new AndroidDriver<>(url, cap);

         return driver;
    }
}

=======================================================================
=======================================================================

public class basics extends base {

    public static void main(String[] args) throws MalformedURLException {
        //TODO Auto generate method stub

        AndroidDriver<AndroidElement> driver = capabilities();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

**Comment by valfirst** [comment]
@JGDStein could you please provide the full error?
