### ISSUE TITLE
AppiumDriverLocalService doesn't start service on specified port by  .usingPort(appiumPort)

### ISSUE THREAD

**Issue by Mynziak** [appium/java-client#1211]
## Description

Hello!
I'm trying to run appium android test in parallel with starting appium-server programmatically for every thread by using AppiumServiceBuilder:

 `AppiumServiceBuilder appiumServiceBuilder = new AppiumServiceBuilder();

        AppiumDriverLocalService service = AppiumDriverLocalService.buildService(appiumServiceBuilder);
    
    if (!isDesktopAppium) {
            appiumServiceBuilder.withAppiumJS(new File(getAppiumPath()));
        }
        appiumServiceBuilder
                .usingPort(appiumPort)
                .withIPAddress(APPIUM_IP)
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                .withLogFile(new File(System.getProperty("user.dir") + "/target/resources/appium_server_logs" + Thread.currentThread().getId()));
        service.start();

        Assert.assertTrue(service.isRunning(), "Appium service is not running! ");
  `
For every thread code generates appiumPort  starts from 4723.
So for two-threads I want to run Appium service on 4723 and 4724 ports appropriately.

But method  service.getUrl() returns  [http://0.0.0.0:4723/wd/hub](url) for any appiumPort value specified in .usingPort(appiumPort) method.
And when I run test in parallel - sometimes method service.isRunning() returns false, and 
Appium logs says:

> [Appium] Welcome to Appium v1.14.1
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
Fatal Error: listen EADDRINUSE: address already in use 0.0.0.0:4723
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at doListen (net.js:1451:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)

It reproduces  about 4 times from 10. 
I tried  .usingAnyFreePort() , .usingPort(appiumPort) and  .withArgument(() -> "--port", String.valueOf(appiumPort)) . but it gives the same results.

How to run Appium service in different ports when parallel test execution? 

## Environment

* java client build version:  1.8
* Appium server version: 1.14.1
* Node.js version  v10.15.3
* Mobile platform/version under test: 8.1.0
* Real device or emulator/simulator: real device

**Comment by SrinivasanTarget** [comment]
> The requested port may already be in use. 

check what is running in those ports and free those.

**Comment by Mynziak** [comment]
Thanks for the answer, @SrinivasanTarget , but how to start AppiumDriverLocalService in custom port? If I specify  .usingPort(4724) and .withIPAddress("127.0.0.1")  anyway - service.getUrl() returns "http://0.0.0.0:4723/wd/hub". Is it normal? I'm expecting to get appium url "http://127.0.0.1:4724/wd/hub"

**Comment by Mynziak** [comment]
It was bug in code.
