### ISSUE TITLE
Add "idb" support

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#1227]
## Description

Please add new facebook iOS automation support (https://github.com/appium/appium-idb) with example of test code.

**Comment by mykola-mokhnach** [comment]
idb is used by XCUITest driver internally. I have no idea about what java client has to do with it and which test code example is expected to be added

**Comment by amedvedjev** [comment]
@mykola-mokhnach  ahhhhh. i misunderstood. i see project: https://github.com/facebookarchive/WebDriverAgent NOT active any more. and i was thinking about migration to https://github.com/facebook/idb/
