### ISSUE TITLE
Setting Chrome options

### ISSUE THREAD

**Issue by sasanapu** [appium/java-client#1232]
## The problem

I have problem setting chrome options while running Android Web TestNG Java tests. I have to disable the save password popup, that comes after login. I am trying to disable it by setting chrome preferences but Appium is not recognising the chrome options. 

## Environment
Appium version used: 1.7.1
Chrome version: 65
Android version: 9

## Link to Appium logs
https://gist.github.com/sasanapu/b48c92940218720cbefc909e172368f9

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, config.getPlatformName());
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, config.getPlatformVersion());
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, config.getBrowser());
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, NEW_COMMAND_TIMEOUT);
        capabilities.setCapability(AndroidMobileCapabilityType.NATIVE_WEB_SCREENSHOT, true);
        capabilities.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
        capabilities.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);

        // Setting chrome options to disable save your password popup
        if(config.getBrowser().equalsIgnoreCase("Chrome")) {
            Logger.log("Disabling save password");
            ChromeOptions cOptions = new ChromeOptions();
            Map<String, Object> prefs = new HashMap<>();
            prefs.put("credentials_enable_service", false);
            prefs.put("profile.password_manager_enabled", false);
            cOptions.setExperimentalOption("prefs", prefs);

            capabilities.setCapability(ChromeOptions.CAPABILITY, cOptions);
        }
        
        AppiumDriver<MobileElement> driver = new AppiumDriver<MobileElement> (new URL(config.getAppiumEndpoint()), capabilities);
        return driver;
    }

**Comment by mykola-mokhnach** [comment]
> from unknown error: unrecognized chrome option: prefs

It's the error from chromedriver. Probably, older version of it don't understand such option

**Comment by sasanapu** [comment]
I did try with "AndroidMobileCapabilityType.CHROME_OPTIONS" but got the same error.

**Comment by sasanapu** [comment]
> > from unknown error: unrecognized chrome option: prefs
> 
> It's the error from chromedriver. Probably, older version of it don't understand such option

May be I am not sure, https://chromedriver.chromium.org/downloads has nothing about chromeOptions. How ever the service I use, uses chromeDriver 2.38

**Comment by sasanapu** [comment]
> Yes you should

I did try with "AndroidMobileCapabilityType.CHROME_OPTIONS" but got the same error.

**Comment by KazuCocoa** [comment]
`prefs` works only desktop chrome. They do not address which options are available for android in https://chromedriver.chromium.org/capabilities, but https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/capabilities.cc#544 has the logic.

**Comment by sasanapu** [comment]
Thanks for the update. Yes indeed it wouldnt work with Android Chrome.

**Comment by jyotijaggasaxena** [comment]
@sasanapu : so how did you manage to update chrome options for Android? I also need to update chrome preferences for android and figuring out how to do it.

**Comment by singh-swati28** [comment]
@KazuCocoa , any suggestion how can I pass below chromeOptions in Android:
var args = new ChromeOptions();
            {
                args.AddArguments("--use-fake-ui-for-media-stream");
                args.AddArguments("--use-fake-device-for-media-stream");
                args.AddArguments("--use-file-for-fake-video-capture=E:\\sample.y4m");
            };

These are working in desktop web but getting error while doing same for mobile web app

[debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[debug] [Chromedriver] InvalidArgumentError: invalid argument: cannot parse capability: goog:chromeOptions
[debug] [Chromedriver] from invalid argument: unrecognized chrome option: AcceptInsecureCertificates
[debug] [Chromedriver]     at errorFromW3CJsonCode (C:\Users\swati.singh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
[debug] [Chromedriver]     at ProxyRequestError.getActualError (C:\Users\swati.singh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
[debug] [Chromedriver]     at JWProxy.command (C:\Users\swati.singh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:272:19)
[debug] [Chromedriver]     at runMicrotasks (<anonymous>)
[debug] [Chromedriver]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] invalid argument: cannot parse capability: goog:chromeOptions
[Chromedriver] from invalid argument: unrecognized chrome option: AcceptInsecureCertificates

Any help would be appreciated

**Comment by KazuCocoa** [comment]
Could you attach the full appium log, please?

I guess you passed the below option, but it did not work on chromedriver for Android. (Btw, the error seems by chromedriver. Nothing can do in Appium side)

> [debug] [Chromedriver] from invalid argument: unrecognized chrome option: AcceptInsecureCertificates
