### ISSUE TITLE
WindowsDriver find returns RemoteWebElement instead of WindowsElement

### ISSUE THREAD

**Issue by adrianhara** [appium/java-client#1247]
## Description

I'm new to Appium and I have the problem described in this issue https://github.com/appium/java-client/issues/1194 (which was closed without any explanation). Basically I'm creating a `WindowsDriver<WindowsElement>` to automate a WPF app, when finding elements (by accesibility id) it says `foundBy io.appium.java_client.windows.WindowsDriver` however the returned element type is `RemoteWebElement`. I would expect the type to be `WindowsElement`. What's more, calling find by accessibility id on the returned element sometimes fails with a not supported exception.

## Environment

* java client build version or git revision if you use some shapshot: 7.2.0
* Appium server version or git revision if you use some shapshot: 1.13.0
* Desktop OS/version used to run Appium if necessary: Windows 10 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Windows/WPF
* Real device or emulator/simulator: -

## Details

Happy to provide, please let me know what you need.

**Comment by guilim** [comment]
Hey! I have the exact same issue: WindowsDriver returning RemoteWebElement, thus leading to cast errors if trying to store them in WindowsElement variables.
Looks like the same issue as https://github.com/appium/java-client/issues/774.
