### ISSUE TITLE
how to save record in a custom path for startRecordingScreen(), Its always under "/sdcard/" but i have "/storage/emulated/0/"

### ISSUE THREAD

**Issue by shofin-islam** [appium/java-client#1254]
## Description
Some of the cases device having a different path like "/storage/emulated/0/"  OR any other path base on the device.

But startRecordingScreen() always storing data into the "/sdcard/"  [Find in the appium log]
How do i set a custom path?
Any solution??

## Environment
* java client build version 7.2
* Appium server version 1.15.1
* Windows 10
* Real device 

## Link to Appium logs
 Running 'C:\Users\Safiul Islam-516\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s UCPVFIM7NVLV497D pull /sdcard/1571283148556.mp4 C\:\\Users\\SAFIUL~1\\AppData\\Local\\Temp\\2019917-12708-ww38ap.7q3tq\\1571283148556.mp4'

Responding to client with driver.stopRecordingScreen() result: ""

**Comment by saikrishna321** [comment]
@shofin-islam ⬇️ 

```
        ((AndroidDriver)driver).startRecordingScreen();
        //something
        String s = ((AndroidDriver) driver).stopRecordingScreen();
        byte[] decode = Base64.getDecoder().decode(s);
        FileUtils.writeByteArrayToFile(new File(System.getProperty("user.dir")+"/sample.mp4"),
                decode);
```

Please ask for questions at discuss.appium.io

**Comment by shofin-islam** [comment]
@saikrishna321 
Your code not working. As I am using only the internal storage how it will pull from SD card, don't understand. however, I will raise this question in discuss.appium.io. 

thank you for your feedback.
