### ISSUE TITLE
[Question] How to use flag allow-insecure on AppiumServiceBuilder?

### ISSUE THREAD

**Issue by nacfe** [appium/java-client#1278]
I'm trying to disable animations on an Android device, using these commands from an article at appium.pro (https://appiumpro.com/editions/25):
```
driver.executeScript("mobile: shell", ImmutableMap.of(
	"command","settings put global window_animation_scale 0",
	"command","settings put global transition_animation_scale 0",
	"command","settings put global animator_duration_scale 0"
));
```

In order to use them I need to do something like this in my test code:
```
builder = new AppiumServiceBuilder();
(...)
builder.withArgument(GeneralServerFlag.RELAXED_SECURITY);
```

My problem is that I want to use the flag
`--allow-insecure=adb_shell`
instead of the flag relaxed-security, but I don't know how to do it, since I can't find a GeneralServerFlag for that. Can you please help me?

* Java client build version or git revision if you use some snapshot: 7.2.0
* Appium server version or git revision if you use some snapshot: 1.15.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both

**Comment by saikrishna321** [comment]
Can you try this

`
builder.withArgument('--allow-insecure');
`

**Comment by nacfe** [comment]
@saikrishna321 unfortunately the method AppiumServiceBuilder.withArgument()  only accepts an io.appium.java_client.service.local.flags.ServerArgument as input, not a String. There is another method but also requires a ServerArgument: withArgument(ServerArgument argument, String value)

**Comment by pr4bh4sh** [comment]
@nacfe just in case if you haven't solved it already, check https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java#L129

**Comment by nacfe** [comment]
Thanks @pr4bh4sh , I made that code change but then I forgot to close this thread.

**Comment by hardik1111** [comment]
I am still getting the error : AppiumServiceBuilder
.withArgument(GeneralServerFlag.ALLOW_INSECURE,"adb_shell");

Failed to reset font size to default: An unknown server-side error occurred while processing the command. Original error: Potentially insecure feature 'adb_shell' has not been enabled. If you want to enable this feature and accept the security ramifications, please do so by following the documented instructions at http://appium.io/docs/en/2.0/guides/security/
Build info: version: '4.19.1', revision: 'abe0ee07dc'
