### ISSUE TITLE
How to use network shared folder with appium?

### ISSUE THREAD

**Issue by qaschevychelov** [appium/java-client#1284]
Hi everyone!

I've opened shared access to a folder in another domain.
The folder is \\\another-domain-ip\rtd-apk

In order to launch android tests i need to specify a path to an ".apk" file with my application.
I set it -Dappium.app=\\\another-domain-ip\rtd-apk\app-debug.apk

Appium log
`[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"\\\\\another-domain-ip\\rtd-apk\\app-debug.apk","appActivity":"com.mvideo.rtd_android.features.auth.AuthActivity","appPackage":"com.mvideo.rtd_android","noReset":"true","newCommandTimeout":"30000","pla
tformVersion":"8.1","automationName":"UiAutomator2","platformName":"Android","udid":"52003d9bbcca5559","deviceName":"device","fullReset":"false"},null,{"alwaysMatch":{"appium:app":"\\\\\another-domain-ip\\rtd-apk\\app-debug.apk","appium:appActivity":"com.mvideo.rtd_androi
d.features.auth.AuthActivity","appium:appPackage":"com.mvideo.rtd_android","appium:automationName":"UiAutomator2","appium:deviceName":"device","appium:fullReset":"false","appium:newCommandTimeout":"30000","appium:noReset":"true","platformName":"android","appium:pla
tformVersion":"8.1","appium:udid":"52003d9bbcca5559"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1577090873955 (11:47:53 GMT+0300 (RTZ 2 (зима)))
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[Appium] Could not parse W3C capabilities: 'newCommandTimeout' must be of type number
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["app","appActivity","appPackage","automationName","deviceName","fullReset","newCommandTimeout","noReset","platformVersion","udid"] are not standard capabilities and should have an extension prefix
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[Appium] Could not parse fixed W3C capabilities: 'newCommandTimeout' must be of type number. Falling back to JSONWP protocol
[Appium] Creating new AndroidUiautomator2Driver (v1.16.0) session
[Appium] Capabilities:
[Appium]   app: \\\another-domain-ip\rtd-apk\app-debug.apk
[Appium]   appActivity: com.mvideo.rtd_android.features.auth.AuthActivity
[Appium]   appPackage: com.mvideo.rtd_android
[Appium]   noReset: true
[Appium]   newCommandTimeout: 30000
[Appium]   platformVersion: 8.1
[Appium]   automationName: UiAutomator2
[Appium]   platformName: Android
[Appium]   udid: 52003d9bbcca5559
[Appium]   deviceName: device
[Appium]   fullReset: false
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"\\\\\another-domain-ip\\rt...
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('30000') to integer (30000). This may cause unexpected behavior
[BaseDriver] Session created with session id: 649656e7-4e46-40c6-9dfd-821257232b16
[BaseDriver] **Downloading the application '\\\another-domain-ip\rtd-apk\app-debug.apk' from SMB share...**
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1577090874064 (11:47:54 GMT+0300 (RTZ 2 (зима)))
[MJSONWP] Encountered internal error running command: Error: **The application at '\\\another-domain-ip\rtd-apk\app-debug.apk' does not exist or is not accessible for download**
[MJSONWP]     at Object.configureApp$ (C:\Users\schevychelov\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\helpers.js:65:13)
[MJSONWP]     at tryCatch (C:\Users\schevychelov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\schevychelov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\schevychelov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\schevychelov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at <anonymous>
`
I use login/password for access to another domain.
Is there any appium flags for credentials for domain shared files?

**Comment by mykola-mokhnach** [comment]
Connect the network share as network drive, and provide the path to the target app in appium capabilities using "classic" Windows path format (e.g. "Z:\file.apk")

**Comment by qaschevychelov** [comment]
ok, thanks!
