### ISSUE TITLE
Not able to call 'setSetting' API

### ISSUE THREAD

**Issue by jineshqa** [appium/java-client#1310]
https://github.com/facebookarchive/WebDriverAgent/issues/1074

## The problem

Appium fails to fetch snapshot. I think it might be related to above issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mojave 10.14.6 
* Node.js version (unless using Appium.app|exe): Using .app
* Npm or Yarn package manager: 
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: .app

## Details

Appium fails to take snapshot with error 
2020-03-03 15:49:52.959309-0800 WebDriverAgentRunner-Runner[13001:2373474] Cannot take the snapshot of Window after 15 seconds
2020-03-03 15:49:52.959665-0800 WebDriverAgentRunner-Runner[13001:2373474] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Error kAXErrorIPCTimeout getting snapshot for element <AXUIElementRef 0x7fdc83546d80> {pid=12189} {uid=[ID:9999 hash:0xe948db3f07000000]}" UserInfo={NSLocalizedDescription=Error kAXErrorIPCTimeout getting snapshot for element <AXUIElementRef 0x7fdc83546d80> {pid=12189} {uid=[ID:9999 hash:0xe948db3f07000000]}}
2020-03-03 15:49:52.961785-0800 WebDriverAgentRunner-Runner[13001:2373474] Skipping source dump for 'Window' because its snapshot cannot be resolved

## Link to Appium logs

https://gist.github.com/jineshqa/de4aa49bd17008ed397dc5fb3821079c

## Code To Reproduce Issue [ Good To Have ]

Not reproducible with sample app.

**Comment by jineshqa** [comment]
@KazuCocoa Even if that works it will set for entire session and I do not want that as test execution time will increase exponentially.

This is not XCTest issue, this works fine with XCUITest from Xcode. This issue is because WDA is slow on pages with 400+ links, which can be worked around using the settings mentioned but java_client is not letting me use setSetting method. So this is java_client issue. If java_client works and WDA does not respond to it them it becomes WDA issue.

**Comment by KazuCocoa** [comment]
Okay, so this issue is cannot call `setSetting` API. Renaming,

hm, Java client seems to have the API
https://github.com/appium/java-client/search?q=setSetting&unscoped_q=setSetting

By _Settings API was improved to accept string names. #1240_, the key accepts String.

**Comment by jineshqa** [comment]
Thanks @KazuCocoa

**Comment by jineshqa** [comment]
@mykola-mokhnach I'm seeing an issue with webdriveragent. What is the best way to log the same?

**Comment by jineshqa** [comment]
@KazuCocoa @mykola-mokhnach Could any java_client dev guide me?

**Comment by KazuCocoa** [comment]
https://github.com/appium/java-client/wiki is for devs

**Comment by jineshqa** [comment]
I meant any committers to the java_client project look into this.

**Comment by KazuCocoa** [comment]
Perhaps @SrinivasanTarget can help if he has a chance.

This issue is about `snapshotTimeout` in https://appium.io/docs/en/advanced-concepts/settings/
But `setSetting` did not work on your env. https://github.com/appium/java-client/issues/1310#issuecomment-594272853
https://github.com/appium/java-client/search?q=setSetting&unscoped_q=setSetting

**Comment by SrinivasanTarget** [comment]
Sure will have a look at this soon.

**Comment by jineshqa** [comment]
Thank you Srini @SrinivasanTarget

**Comment by jineshqa** [comment]
@SrinivasanTarget did u get a chance to take a look amid all that is happening around us.

**Comment by shibupanda** [comment]
> I tried latest one as well (7.3.0), I am still getting the error setSetting not found.

@jineshqa I guess setSetting method is available in "AndroidDriver" and "IOSDriver". I mean if we are using AppiumDriver driver = new IOSDriver() then setSetting method is not visible. Hope this comment can help you some extend.

**Comment by jineshqa** [comment]
@shibupanda you are right...it requires OS specific driver to work.
