### ISSUE TITLE
imageMatchThreshold doesn't seem to be set...

### ISSUE THREAD

**Issue by jsa34** [appium/java-client#1317]
## Description

Trying to set value of imageMatchThreshold for image matching, but it never seems to be updated, according to appium logs.

I have tried:
            capabilities.setCapability("imageMatchThreshold", "0.9");
 and
            capabilities.setCapability("imageMatchThreshold", 0.9);

But both still log:
[BaseDriver] Finding image element with match threshold 0.4
## Environment

* Java client build version or git revision if you use some snapshot: 7.3.0
* Appium server version or git revision if you use some snapshot: 1.7.0-beta
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 
* Mobile platform/version under test:
* Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please attach the full log

**Comment by mykola-mokhnach** [comment]
also, make are you sure it is a capability, not a setting?

**Comment by jsa34** [comment]
You are absolutely right!  Sorry...
The solution was to use:
        CommandExecutionHelper.execute(driver, new AbstractMap.SimpleEntry<>("setSettings", prepareArguments("settings", prepareArguments("imageMatchThreshold", 0.9))));

It would be helpful to have a sort of "driver.setSetting" method, which I could see in the comments of:
https://github.com/appium/appium/issues/11854
But I couldn't see this in methods available for WindowsDriver

**Comment by mykola-mokhnach** [comment]
> It would be helpful to have a sort of "driver.setSetting" method, which I could see in the comments of:

yes this might be an improvement. There is also a possibility to provide initial setting values as capabilities, for example `caps.setCapability("settings[imageMatchThreshold]", 0.9)`
