### ISSUE TITLE
suggestion of altering mobileElement.getCenter() using getRect command

### ISSUE THREAD

**Issue by cheffey** [appium/java-client#1320]
io.appium.java_client.MobileElement.java

   public Point getCenter() {
        Point upperLeft = this.getLocation();      //one request
        Dimension dimensions = this.getSize(); //another request
        return new Point(upperLeft.getX() + dimensions.getWidth() / 2,
            upperLeft.getY() + dimensions.getHeight() / 2);
    }

this command make two request([left, top], []) and calculate the center.

I'm wondering if we could replace with :
 execute(DriverCommand.GET_ELEMENT_RECT, ImmutableMap.of("id", id));
to fetch the result with one request.

In my scenario, this would optimize the command speed especially for IOS.

**Comment by mykola-mokhnach** [comment]
GET_ELEMENT_RECT is a W3C endpoint. Changing this call might render failures in existing client scripts if they use JSONWP protocol

**Comment by cheffey** [comment]
> GET_ELEMENT_RECT is a W3C endpoint. Changing this call might render failures in existing client scripts if they use JSONWP protocol

I see. Thank you Mykola.

**Comment by cheffey** [comment]
@mykola-mokhnach 
I found that the rect command in the appium is still a combination of getLocation and getSize, so changing it won't do much good.

Also I didn't know jsonwp before, now I learned some thing new. https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol
