### ISSUE TITLE
ClassCastException on getAllSessionDetails()

### ISSUE THREAD

**Issue by mrk-han** [appium/java-client#1328]
## Description

Error when trying to call getAllSessionDetails.

I'm setting an ENV variable on Jenkins, so when we execute on Jenkins if we Build with Parameters and set that param `PRINT_SESSION_DETAILS` to "true" then we will execute the code below. This code also executes 100% of the time when running locally.

However, when run on Jenkins we're seeing this Exception thrown.

## Environment

* Java client build version or git revision if you use some snapshot: 7.3.0 
* Appium server version or git revision if you use some snapshot: 1.16.0
* Desktop OS/version used to run Appium if necessary: Linux

## Details

ClassCastException when calling `getAllSessionDetails()`
`sessionDetails = getAppiumDriver().getAllSessionDetails();`

## Code To Reproduce Issue [ Good To Have ]

```
        if (nodeName == null || "true".equals(System.getenv("PRINT_SESSION_DETAILS"))) {
            List<Map<String, Object>> sessionDetails = null;
            if (getAppiumDriver() != null) {
                sessionDetails = getAppiumDriver().getAllSessionDetails();
                for (Map<String, Object> sessionDetail : sessionDetails) {
                    System.out.println(sessionDetail + "\n");
                }
            }
        }
```

## Exception Stacktraces

```
java.lang.ClassCastException: Cannot cast com.google.common.collect.Maps$TransformedEntriesMap to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at io.appium.java_client.HasSessionDetails.getAllSessionDetails(HasSessionDetails.java:101)
```

## Link To Appium Logs

n/a

**Comment by cheffey** [comment]
seems you import the wrong Map

**Comment by mrk-han** [comment]
Ahhh, thank you! I didn’t think of that. Much appreciated.
