### ISSUE TITLE
Appium stuck at tapping an coordinate or taking screenshot from time to time

### ISSUE THREAD

**Issue by seanLiu716** [appium/java-client#1338]
## Description

My Java code with Appium worked ok with a Moto G6 (Android 9). Recently I switched to 
a OnePlus 6T with Android 9. 
Appium stuck from time to time, mostly at tap to an coordinate or take screenshot. 
The weird thing is that the first loop typically is ok. 2nd loop of the same code likely run into issue.
Appium stuck, I can manually tap the phone. It is responsive.

See server log below.

## Environment

* Java client build version V7.3.0
* Appium server version Appium V1.17 beta or Appium Desktop V.15 - issue duplicateable in both version
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Oneplus 6T

## Details

Please provide more details, if necessary.

Please see server log link below, stuck at line 339

## Code To Reproduce Issue [ Good To Have ]

Please remember: it's easier to reproduce and fix the bug with sample code.
You can git clone https://github.com/appium/appium/tree/master/sample-code or https://github.com/appium/appium/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs
https://gist.github.com/seanLiu716/74eb944c9fe9320614c4eb682a78b080

stuck at line 339
[debug] [35m[W3C (17f803a4)][39m Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":275,"y":865}}],"17f803a4-e0a9-4461-9fdc-7bd1eb25e2a4"]
[debug] [35m[WD Proxy][39m Proxying [POST /appium/tap] to [POST http://localhost:8200/wd/hub/session/ab496a33-9ef6-4cf2-a447-177d4a58df00/appium/tap] with body: {"x":275,"y":865}[info]

another run: tap at coordinate works fine, but appium stuck at taking screenshot
https://gist.github.com/seanLiu716/74bc8bf5ece70a99e70eb755f395f782
Stuck at line: 310
[debug] [35m[W3C (7fdcd840)][39m Calling AppiumDriver.getScreenshot() with args: ["7fdcd840-cfa5-429f-869a-e7fd14ee9119"]
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/e1560ee1-ea63-4de1-8558-0b3a4cc8d095/screenshot] with no body[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/7fdcd840-cfa5-429f-869a-e7fd14ee9119/screenshot [39m[32m-[39m [90m- ms - -[39m
[info] [35m[HTTP][39m [90m[39m

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by mykola-mokhnach** [comment]
Your issue looks similar to https://github.com/appium/appium-uiautomator2-server/issues/310

**Comment by seanLiu716** [comment]
Thanks mykola. 

I modified setting in Battery to avoid UiAutomator2 session being killed in background. 
Now I can run 10 loops, about 10 minutes with Appium not crashing. 

Can you take a look at the server log, let me know if there is any solution?
I typically run the code for hours with MotoG6.

https://gist.github.com/seanLiu716/4eaa512d54b05d2ca7925bd5f3ff1c85

crash occurred at line 1975
[debug] [35m[W3C (0cc7780d)][39m Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"x":460,"duration":300,"y":315}},{"action":"release","options":{}}],"0cc7780d-858e-43a2-ace7-7927613d9374"]
[debug] [35m[WD Proxy][39m Matched '/touch/longclick' to command name 'touchLongClick'
[debug] [35m[WD Proxy][39m Proxying [POST /touch/longclick] to [POST http://localhost:8200/wd/hub/session/5db5ec61-4d97-4e58-a3b7-72ef19362f01/touch/longclick] with body: {"params":{"x":460,"y":315,"duration":300}}[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0
[info] [35m[WD Proxy][39m Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [35m[W3C (0cc7780d)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

**Comment by mykola-mokhnach** [comment]
You won't see nothing in Appium log. Consider checking the logcat one

**Comment by seanLiu716** [comment]
Please see the logcat file attached. 
The last Appium action before crash is at line # 84108
04-30 19:47:01.308 27061 27552 I appium  : channel read invoked!
04-30 19:47:01.309 27061 27552 I appium  : channel read: POST /wd/hub/session/4858a152-9047-4e62-a269-85546bae5625/appium/tap
04-30 19:47:01.313 27061 27552 I appium  : tap command
04-30 19:47:01.320 27099 27313 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-30 19:47:01.336 27061 27552 D InteractionController: clickNoSync (540, 1287)
04-30 19:47:01.351 27099 27313 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-30 19:47:01.385 27099 27313 I chatty  : uid=10120(com.nianticlabs.pokemongo) Thread-283 identical 1 line
04-30 19:47:01.419 27099 27313 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-30 19:47:01.449 27061 27552 I appium  : Waiting up to 10000ms for device to be idle
04-30 19:47:01.451 27061 27552 I appium  : AppiumResponse: {"sessionId":"4858a152-9047-4e62-a269-85546bae5625","value":null}
[logcat.txt](https://github.com/appium/java-client/files/4561943/logcat.txt)

**Comment by seanLiu716** [comment]
This issue is due to Appium process got killed by OnePlus at background.
