### ISSUE TITLE
Cannot get the latest master-SNAPSHOT from jitpack.io by following the steps in the ReadMe.md

### ISSUE THREAD

**Issue by MohabMohie** [appium/java-client#1351]
## Description

Cannot get the latest master-SNAPSHOT from jitpack.io by following the steps in the ReadMe.md

## Environment

* Java/Maven

## Details

![image](https://user-images.githubusercontent.com/19201898/82760899-e48a3580-9df6-11ea-8d55-d3f037a171da.png)

![image](https://user-images.githubusercontent.com/19201898/82760927-126f7a00-9df7-11ea-919f-ee7d74178536.png)

![image](https://user-images.githubusercontent.com/19201898/82760922-0683b800-9df7-11ea-9c7d-6f7dcef6821f.png)

**Comment by sandeep-looker** [comment]
Same here, using Gradle:

Could not resolve com.github.appium:java-client:158f183526

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by SrinivasanTarget** [comment]
Fixed [here](c8cee6ec6fca2872757c1c79ddb0fd65c34ad6ce)
