### ISSUE TITLE
Shutting Down Android Emulator

### ISSUE THREAD

**Issue by wulfihm** [appium/java-client#1379]
How would I go about shutting down the android emulator after my tests? 
My expectation was that `driver.quit()` would also close the emulator used, but it doesn't.

I wrote myself a small function which sends a reboot command to appium but it does not work. If I use it before the quit() command the quit() command throws obviously an error, if I use it after the quit() command it throws an error as well because the driver doesn't haven a session id anymore.

```
    public void shutdownEmulator(){
        Map<String, String> cmd = ImmutableMap.of(
                "command", "reboot",
                "args", "-p"
        );
        String answer = (String) this.executeScript("mobile: shell", cmd);
        System.out.println(answer);
    }
```

Ideally I would like to also shutdown the emulator. I know I can do this via adb but how can I do this programmatically via appium?

Could also be that this is not possible at all, than this would be an appium issue.

## Environment

* Java client build version or git revision if you use some snapshot: 7.3.0
* Appium server version or git revision if you use some snapshot: 1.17.0
* Mobile platform/version under test: Android

**Comment by mykola-mokhnach** [comment]
> If I use it before the quit() command the quit() command throws obviously an error

I would say this is an expected behaviour. You could simply ignore the exception in `quit` call on the client side.

**Comment by wulfihm** [comment]
So with my first experiences it seems like the emulator does not really like the reboot command. The emulator dissapears and the process keeps on running in the background and I have to close it forcefully.

Is there any way to make direct adb calls to appium? I found this https://github.com/appium/appium-adb
But not sure at all how I would go about to use it in the java client.

**Comment by mykola-mokhnach** [comment]
You could try to send the shutdown command directly to the emulator terminal. See for example https://appiumpro.com/editions/120-setting-accelerometer-data-for-the-android-emulator

**Comment by wulfihm** [comment]
So works but it fails because I am not root.
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute the 'stop' shell command. Original error: Command 'C:\\Users\\myrocast\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5556 shell stop -p' exited with code 1. StdOut: . StdErr: stop: must be root`

**Comment by mykola-mokhnach** [comment]
try to add `su root` prefix to your shell command ;)

**Comment by wulfihm** [comment]
Okay this will not work, since that command does not work even normally when I try it directly with adb.

```
PS C:\Users\Me> adb -P 5037 -s emulator-5554 shell
generic_x86_arm:/ $ su root
generic_x86_arm:/ # stop
generic_x86_arm:/ #
```
It just does nothing. I mean I can see something in the appium logs that the instrumentation stopped but the emulator is still running, weird behaviour.

However, what works is this:
`adb -s emulator-5554 emu kill`

But I failed to find out how to do this via appium.

**Comment by mykola-mokhnach** [comment]
I really don't like to provide final solutions, because I prefer people to figure them out on their own. Although I see you are trying hard:

Option 1:
`driver.executeScript("mobile: execEmuConsoleCommand", ImmutableMap.of("command","kill"));` (exists since Appium 1.18.0)

Option 2:
`driver.executeScript("mobile: shell", ImmutableMap.of("command", "su root stop -p"))`

**Comment by wulfihm** [comment]
Ah okay, I were using Appium 1.17.0. and updated to 1.18.0.

Option 2 did not work: Seems to be because of adb itself as I said above.
Emulator is still running after executing the command.

However, Option 1 did work.
It successfully kills the emulator.
Unfortunately there are other issues I run into.

1. As already mentioned driver.quit() will throw an exception if the emulator is killed.
2. I can catch that exception and simply ignore that. Then it will time out. https://gist.github.com/wulfihm/2c5c362c3a8f78d3032135f1da4caab4
3. It seems appium has some issues if the session is not properly closed or if these errors from aboce occur. I am not able to begin another session until I do "CRTL + C" in the appium server console. If I do that it creates another session but is not able to connect to the emulator. https://gist.github.com/wulfihm/e1429861777d1022577dd95e223dc20a

**Comment by wulfihm** [comment]
>     3. It seems appium has some issues if the session is not properly closed or if these errors from above occur. I am not able to begin another session until I do "CRTL + C" in the appium server console. If I do that it creates another session but is not able to connect to the emulator. https://gist.github.com/wulfihm/e1429861777d1022577dd95e223dc20a

The issue that appium is not able to find the device is because of the emulator/ADB. After killing the device it is listed as offline when it starts again.
```
PS C:\Users\MyUser> adb devices
List of devices attached
emulator-5554   offline
```

So far the only solution I found that fixes it is wiping the device via the AVD manager of android studio.
Fortunately it is possible to define that in appium-
`cap.setCapability(AndroidMobileCapabilityType.AVD_ARGS, "-wipe-data -no-snapshot -gpu on -accel on");`

I also added the "-no-snapshot" arg, so that the device state is not saved at after a test run.
https://developer.android.com/studio/run/emulator-commandline

With that the device always cold boots and takes about a minute to start up.

**Comment by mykola-mokhnach** [comment]
> In summary, killing/shutting down the android emulator via appium is not feasiable at all. Doing it yourself externally without appium is better.

I agree to that. Appium is created with "maximum survivability" principle in mind (adb as well), which means it does retries and everything else needed to keep session alive. Changing this behaviour could require serious architectural changes in the server code, which are also not really needed for the majority of the users.
