### ISSUE TITLE
Getting "org.openqa.selenium.UnsupportedCommandException: actions" at line driver.perform()

### ISSUE THREAD

**Issue by sudhanshuprakash** [appium/java-client#1383]
## The problem

I am trying to copy paste a text using point options. But I am getting an error at the line driver.perform().

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10
* Node.js version (unless using Appium.app|exe):v12.14.0
* Npm or Yarn package manager:
* Mobile platform/version under test:7.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/sudhanshuprakash/b1a843f6ee50b27f1976b878a9b28ffb

## Code To Reproduce Issue [ Good To Have ]

TouchAction t1=new TouchAction(driver).longPress(PointOption.point(w,x)).perform();
        TouchAction t2=new TouchAction(driver).longPress(PointOption.point(w,x)).perform().waitAction().moveTo(PointOption.point(y,z)).release().perform();

        KeyInput keyboard = new KeyInput("keyboard");
        Sequence sendKeys = new Sequence(keyboard, 0);

        sendKeys.addAction(keyboard.createKeyDown(Keys.CONTROL.getCodePoint()));
        sendKeys.addAction(keyboard.createKeyDown("c".codePointAt(0)));
        sendKeys.addAction(keyboard.createKeyUp("c".codePointAt(0)));
        sendKeys.addAction(keyboard.createKeyUp(Keys.CONTROL.getCodePoint()));
        driver.perform(Arrays.asList(sendKeys));
        Thread.sleep(5000);
        driver.getClipboard(ClipboardContentType.PLAINTEXT);

**Comment by sudhanshuprakash** [comment]
Okay. So what exactly should I search to resolve this issue?

**Comment by sudhanshuprakash** [comment]
@mykola-mokhnach is there any way to launch my appium test on dialect W3C instead of dialect OSS. Because I am getting this error when the app is launching on dialect OSS.

**Comment by sudhanshuprakash** [comment]
Hi @mykola-mokhnach . Any suggestions on how to launch my appium application on dialect w3c?

**Comment by bijitbiswas1994** [comment]
Hi @sudhanshuprakash 
Did you able to find a solution for this issue ? I am still facing the same problem while trying to do
`driver.perform(asList(sequence, sequence2))`
