### ISSUE TITLE
zoom in and zoom out not working on dialect OSS.

### ISSUE THREAD

**Issue by sudhanshuprakash** [appium/java-client#1395]
## Description

I am trying to implement zoom in and zoom out in my application. Now when I try to do it in my unit test it is working as expected. But when I try it in my integration test it gives an error. The only difference I can find in the two is that when the app is being launched in unit test it works on dialect W3C and when I am working on integration test it works on dialect OSS.

## Environment

Appium version (or git revision) that exhibits the issue: 1.18.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium:10
Node.js version (unless using Appium.app|exe):v12.14.0
Npm or Yarn package manager:
Mobile platform/version under test:7.1.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium.exe
* Real device or emulator/simulator:

## Code To Reproduce Issue [ Good To Have ]

https://appiumpro.com/editions/67-generating-touch-gestures-to-zoom-in-and-out-on-google-maps

## Exception Stacktraces

https://gist.github.com/sudhanshuprakash/f38c2da3bb1b75aa39e5bac0050a5b66

## Link To Appium Logs

https://gist.github.com/sudhanshuprakash/816c27075b31d5b4d7e3d64c6d986cac

**Comment by mykola-mokhnach** [comment]
This is expected. Actions API is only defined in W3C

**Comment by sudhanshuprakash** [comment]
Can you please tell me any alternates for zoom in if actions is not defined in dialect OSS. Or is there any way on which I can only launch my app only on dialect W3C by setting the desired capabilities?

**Comment by sudhanshuprakash** [comment]
Hey @mykola-mokhnach . Can you please tell me a workaround so that I can implement zoom ina and zoom out in my code while I am working on dialect OSS. Will like to close this issue.

**Comment by mykola-mokhnach** [comment]
I don't know if there is a workaround

**Comment by sudhanshuprakash** [comment]
Ok, @mykola-mokhnach . Can you tell me is there any way in which I can make sure that the app that I am launching in appium is getting launched always in dialect W3C. Or if someone else knows whom you can assign this to?

**Comment by sudhanshuprakash** [comment]
@mykola-mokhnach .This is the final test on which I am stuck. Would truly appreciate if can get help on this.

**Comment by mykola-mokhnach** [comment]
Try to ask at [Appium forum](discuss.appium.io)

**Comment by sudhanshuprakash** [comment]
This is expected behavior as actions class is only defined for dialect W3C and for zoom we have to find a different way on dialect OSS.
