### ISSUE TITLE
['java-client', version: '7.4.0'] error: package org.openqa.selenium.support.ui does not exist import org.openqa.selenium.support.ui.WebDriverWait;

### ISSUE THREAD

**Issue by yavgel** [appium/java-client#1415]
- just updated my 'java-client' version, to version: '7.4.0' (Gradle)
- build

having the next error:

![image](https://user-images.githubusercontent.com/8123409/99693228-6c41bb80-2a8b-11eb-8f48-3316cf213e45.png)

with version: '7.3.0' - all is OK

**Comment by headsvk** [comment]
Yes I'm also experiencing this issue with many classes. There must be something wrong with the latest jar package.

**Comment by andres-choco** [comment]
And not only those, several libraries failed to import when updating to java-client 7.4.0 , also including `org.openqa.selenium.remote.DesiredCapabilities`

**Comment by SrinivasanTarget** [comment]
@andres-choco @headsvk @yavgel thanks for the report. Will definitely look at it today.

**Comment by SrinivasanTarget** [comment]
@headsvk @yavgel @andres-choco please add the below dependency explicitly as a temporary solution to solve this problem till we release a patch version. I'm checking on this and will add more details here soon.

```
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.141.59</version>
        </dependency>
```

**Comment by yavgel** [comment]
@SrinivasanTarget  - related issues mentioned in this bug still exists in `v7.4.0` and `v7.4.1` - when your fixes will be accessible in public? thanks

**Comment by yavgel** [comment]
> @headsvk @yavgel @andres-choco please add the below dependency explicitly as a temporary solution to solve this problem till we release a patch version. I'm checking on this and will add more details here soon.
> 
> ```
>         <dependency>
>             <groupId>org.seleniumhq.selenium</groupId>
>             <artifactId>selenium-remote-driver</artifactId>
>             <version>3.141.59</version>
>         </dependency>
> ```

@SrinivasanTarget  - it does not help for `v7.4.0` and for `v7.4.1`
issue is still relevant

**Comment by valfirst** [comment]
@yavgel could you please provide more details?
