### ISSUE TITLE
It's not possible to extend from MobileElement

### ISSUE THREAD

**Issue by lartemyev** [appium/java-client#1433]
## Description

When I try to extend from the MobileElement class, got a compilation error like reported here: https://discuss.appium.io/t/how-to-extend-mobileelement/21693
Do we have any way to extend from MobileElement?

## Environment

* Java client build version: **1.8.0_271**
* Appium server version: **java-client (v7.4.1), Appium v1.20.0**
* Desktop OS/version: **Windows 10 x64**
* Node.js version: **v15.5.0**
* Android **Galaxy Nexus API 30**
* Emulator

**Comment by valfirst** [comment]
`MobileElement` was [removed](https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#mobileelement) in Appium Java Client 8.x.
