### ISSUE TITLE
Appium IOS tests running when server started manually but not when server is started via AppiumDriverLocalService

### ISSUE THREAD

**Issue by fida10** [appium/java-client#1444]
## The problem

Attempting to run Appium automation scripts on iOS (simulator) on a Mac Mini (M1 chip, if that's relevant). When I run the tests, they work just fine when the Appium server is started manually (typing "appium" into the terminal and starting it that way). However, when I attempt to start the appium server programmatically, the application under test fails to launch, with the following error:

2021-02-17 03:41:27:256 [W3C]       WebDriverAgentRunner-Runner.app (19077) encountered an error (Failed to load the test bundle. If you believe this error represents a bug, please attach the result bundle at /Users/sagolGoru20/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkbkvswlszzhhbevpokpwtrjdxxq/Logs/Test/Test-WebDriverAgentRunner-2021.02.16_22-41-22--0500.xcresult. (Underlying Error: **The bundle “WebDriverAgentRunner” couldn’t be loaded because it doesn’t contain a version for the current architecture. The bundle doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.** dlopen_preflight(/Users/sagolGoru20/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkbkvswlszzhhbevpokpwtrjdxxq/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
2021-02-17 03:41:27:256 [W3C]   /Users/sagolGoru20/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkbkvswlszzhhbevpokpwtrjdxxq/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture))

## Environment

* Appium version (or git revision) that exhibits the issue: 7.4.1
* Desktop OS/version used to run Appium: Mac OS 11.1 (Big Sur)
* Node.js version (unless using Appium.app|exe): Node.js v15.8.0
* Npm or Yarn package manager: npm 7.5.0
* Mobile platform/version under test: iOS Simulator (iPhone SE 2nd Generation 14.4)
* Real device or emulator/simulator: Simulator

## Details

I originally thought that this was an issue with xcode or WDA, but if that were the case, the tests would fail no matter how Appium was started, and as mentioned previously, the tests pass perfectly fine when Appium is started manually (via terminal), so it might be an issue with the PATH or environment variables upon execution from Java, not sure though.

## Link to Appium logs

Here's the full appium log: https://gist.githubusercontent.com/fida10/44344b223874310cf296d38a95d4268f/raw/316855b619129680eeaa6519a446a436d0699cd6/failedLog.txt

## Code To Reproduce Issue [ Good To Have ]

Here is the code I am using to start the server programmatically:

        HashMap<String, String> environment = new HashMap();
        environment.put("PATH", "/usr/local/bin:" + System.getenv("PATH"));

        AppiumDriverLocalService server = AppiumDriverLocalService
                .buildService(new AppiumServiceBuilder()
                        .withEnvironment(environment)
                        .usingDriverExecutable(new File("//opt/homebrew/Cellar/node/15.8.0/bin/node"))
                        .withAppiumJS(new File("//Users/sagolGoru20/.npm-packages/lib/node_modules/appium/build/lib/main.js"))
                        .usingAnyFreePort()
                        .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                        .withLogFile(new File("//Users/sagolGoru20/Programming/JavaProjects/MavenProjects/MobileAutomationProjects/firstAppiumProject/appiumLog.txt"))
                );
        server.start();
As the appium log shows, the server seems to be started fine but then throws the above error, so I think the issue may be with how I'm building the AppiumDriverLocalService object.

I followed this tutorial in building AppiumDriverLocalService: https://appiumpro.com/editions/71-starting-an-appium-server-programmatically-using-appiumservicebuilder

Any help would be greatly appreciated.

**Comment by mykola-mokhnach** [comment]
This is how service builder locates the main script path: https://github.com/appium/java-client/blob/ff10d910eae1706d4e0b4888979b9e4ffc91e35d/src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java#L141

Make sure it returns a correct path on your env

**Comment by fida10** [comment]
I was able to solve the issue. The fix:

Went to: ~/.npm-packages/lib/node_modules/appium/node_modules/appium-webdriveragent and opened "WebDriverAgent.xcodeproj" in Xcode (12.4), then went into "Build Settings" and changed all the "Build Active Architecture Only" settings to "no", like so: 

![Screen Shot 2021-02-18 at 12 50 51 AM](https://user-images.githubusercontent.com/3886263/108311698-71de9880-7183-11eb-922d-292d67c36559.png)

Closed Xcode and ran the appium test again, now works as intended. 

Thanks again mykola for your help. I am still not sure why it was working with manual appium server and not with AppiumDriverLocalService. There does now appear to be three .xctestrun files in ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkbkvswlszzhhbevpokpwtrjdxxq/Build/Products:

![Screen Shot 2021-02-18 at 12 56 55 AM](https://user-images.githubusercontent.com/3886263/108312140-37c1c680-7184-11eb-9145-a039bf2d98cf.png)

The WebDriverAgentRunner_iphonesimulator14.4-arm64-x86_64.xctestrun is the new file. 

The issue appears to have been the M1 chip in the end.

**Comment by iamhaseebiqbal** [comment]
For ARM based MACs, make sure you are using aarch64 based JAVA and not x86_64 based. Use following to list down your JAVAs.

```
> /usr/libexec/java_home -V
```
