### ISSUE TITLE
java-client release with Mac2Driver

### ISSUE THREAD

**Issue by mythsunwind** [appium/java-client#1448]
## Description

I need a java-client version with the new Mac2Driver support. I can currently build it myself, but i was not able to get it via jitpack.io (see details below). There was no release since November last year. Will there be a new release soon?

## Issue with jitpack.io

I added the following to my pom.xml as described in the README:

```
<repositories>
                <repository>
                    <id>jitpack.io</id>
                    <url>https://jitpack.io</url>
                </repository>
</repositories>

<dependencies>
           <dependency>
                    <groupId>io.appium</groupId>
                    <artifactId>java-client</artifactId>
                    <version>c14054ed9e95b7499c90a09a098b675529c86237</version>
           </dependency>
<dependencies>
```

But this results in:

```
The POM for io.appium:java-client:jar:c14054ed9e95b7499c90a09a098b675529c86237 is missing, no dependency information available
```

**Comment by SrinivasanTarget** [comment]
@mythsunwind I forget to release it last weekend. Will definitely do it before this Friday and update here.

**Comment by SrinivasanTarget** [comment]
@mythsunwind Java Client `7.5.0` is now released with Appium `Mac2Driver`

**Comment by mythsunwind** [comment]
Thank you @SrinivasanTarget
