### ISSUE TITLE
Rename org.openqa.selenium package due to split package issue

### ISSUE THREAD

**Issue by naveenchandra91** [appium/java-client#1455]
## Description

We are having split package issue due to the package org.openqa.selenium package. Please rename the package or provide a good way to get rid of the split package issue.

## Environment

* Java client 7.5.0

![image](https://user-images.githubusercontent.com/20183760/112253210-4835f700-8c84-11eb-826f-7781a3bc9ddd.png)

**Comment by dnicholas2001** [comment]
This is a blocker for any Java project using modules!

**Comment by ajschwieterman** [comment]
Any update on this issue?

**Comment by ajschwieterman** [comment]
I think this might be related to the issue I recently created.  #1465

**Comment by dnicholas2001** [comment]
There might be a solution using `maven-shade` plugin to combine *both* appium and selenium-api into a single JAR. Have been successful in clearing the compile and runtime errors, especially for `ModuleResolutionException`. However, haven't figured out a way to publish the maven shade JAR file.

Pulling in the standalone maven project will also pull in the dependencies, but, we don't want the dependencies, rather, we want the maven shade JAR.

So, not sure on the best solution here.

Hope this helps.

**Comment by naveenchandra91** [comment]
@dnicholas2001 : Just combining the Jars wont help. I did think about that. However when I went through the source I got to know that even though they are the same package the contents of the classes are modified to suit Appium needs. hence combining Jars might just overwrite selenium compiled classes with Appium or other way round. Hard to predict that. 

The proper solution would be to use different package naming and different class naming for Appium modifications needed for selenium source. Also if source code of selenium is needed for reusability with modifications they should use design patterns like Decorator to decorate the selenium sources with the changes Appium needs.

But this requires some amount of work. If someone is thinking to contribute to PR I am happy to help

**Comment by dnicholas2001** [comment]
@naveenchandra91 Good point, thanks for sharing, hadn't considered that.

I wonder if Selenium 4 will solve this issue?

**Comment by valfirst** [comment]
Please try `8.0.0-beta` (it's based on Selenium 4)

**Comment by valfirst** [comment]
Fixed by #1555
