### ISSUE TITLE
element.getAttribute("value") returns different value than it being inspected by accessibility inspector / Appium inspector

### ISSUE THREAD

**Issue by igalep** [appium/java-client#148]
Hi , 
I'm trying to get a value from "UIAStaticText" control. 
While I'm trying to inspect it by IOS accessibility inspector or while I'm launching the Appium's one , I'm getting correct value ...  

{"UIAStaticText":{"@":{"name":"spread","label":"spread","value":"0.9","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/41","x":146,"y":168,"width":35,"height":21},">":[]}}

But while I'm trying to get the value by programmatically : 

MobileElement element = MobileElementsOperations.getElementByName(conn.getDriver(), "spread");
String val = element.getAttribute("value");

The val equals to "spread"
Also if I'm trying to inspect the control by Appium inspector , the value is different from the printed in log.

name: spread
type: UIAStaticText
value: spread
label: spread
enabled: true
visible: false
valid: true
location: {-174, 168}
size: {35, 21}
xpath: //UIAApplication[1]/UIAWindow[1]/UIAStaticText[7]

Any Idea ?

**Comment by Jonahss** [comment]
I think @bootstraponline can provide more detail. This would be a general Appium behavior, and not related to the java-client

**Comment by bootstraponline** [comment]
If `"value":"0.9"` shows up in the xml dump and we can't access it as an attribute then it seems like a bug to me. If there's some way to reproduce the issue using a sample app, that'd help a lot.

**Comment by igalep** [comment]
Got the answer , 
The problem was that there are several controls with the same name (bad developmnet ... )
And by uisng getElement I got the first one , while the control with value = 0.9 is actually third one on the list ...


Pls close this issue

**Comment by Jonahss** [comment]
That explains it :)
