### ISSUE TITLE
Not possible to double click on element

### ISSUE THREAD

**Issue by pabloleal1** [appium/java-client#1491]
After trying to set the appium method for double click:
     Actions action = new Actions(driver);
            action.moveTo(element);
            action.doubleClick();
            action.perform();
I'm getting the next error 
<img width="281" alt="Sin título" src="https://user-images.githubusercontent.com/25209957/124149281-b9115a00-da90-11eb-936f-f0d998223ff6.png">

For our project, we are using maven with the following dependency (Wich I'm not sure if it can impact on the above error)
    <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.4.1</version>
        </dependency>

If it didn't, wich dependency we need to include in our pom?

On the other hand, If anyone know other methods to double click, please could you help to solve this?
Thanks you ever so much.

**Comment by jlipps** [comment]
I don't think this class is the current w3c standard actions class. @SrinivasanTarget can you provide guidance here?

**Comment by SrinivasanTarget** [comment]
@pabloleal1 you can refer to double click or any gesture example here https://www.github.com/saikrishna321/VodQaAdvancedAppium/tree/master/src%2Ftest%2Fjava%2Fcom%2Fappium%2Fgesture%2FGestureTest.java

**Comment by pabloleal1** [comment]
Hi all, 

We are still getting the same error.

Any help would be appreciated!

**Comment by saikrishna321** [comment]
@pabloleal1 What error are u getting?

**Comment by pabloleal1** [comment]
Hi @saikrishna321,

We were getting the same error as shown above however we solved using the methods for appium 1.21.0

Thanks!
