### ISSUE TITLE
Java client should have a scrollTo(xpath) similar to scrollTo(text) method

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/java-client#151]
If text for an element is not available than scrollTo(xpath) method might be useful.

**Comment by sahajamit** [comment]
Actually in iOS, ScrollTo method is defined to scroll over a TableView which has multiple cells. It is always recommended to use it over the UIATableView and it scroll to the respective cell of this table depending the search text is present in the cell name.

If we have cells with duplicate names then there is no way to scroll to each of these cells. So I have added a new method called "scrollTobyCellIndex" in the IOSElement class where you can pass the index of the cell and it will scroll to that specific cell.

You can find my updated code here:  https://github.com/sahajamit/java-client

I have sent a pull request to this project owners and hope they will incorporate my code.

If you need my project jar then please let me know.

**Comment by Jonahss** [comment]
@sahajamit are you sure you sent a pull request? I don't see it on the java-client repo. Happy to take a look and merge it :)

**Comment by sahajamit** [comment]
@Jonahss, Sorry I think I missed to send the pull request. Here is the one

https://github.com/appium/java-client/pull/190

**Comment by SrinivasanTarget** [comment]
scrollTo is deprecated and here we go: https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSScrollingSearchingTest.java#L80
