### ISSUE TITLE
How to disable/supress the following logs: AppiumCommandExecutor and Detected dialect: W3C 

### ISSUE THREAD

**Issue by SpencerMelo** [appium/java-client#1525]
## Description
First, it's not a bug.

Currently, due to the amount of tests I run in parallel (20+) there is one log that keep spamming and I have no idea on how to disable it, I tried different things as we do in Selenium, but I had no success in Appium.

Throwing things into dev/null, changing log level and etc, but not a single success.

I don't know if it's already possible, but can we disable this logs below?
```java
Oct 06, 2021 3:16:52 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
```

What this kind of log causes to our CD environment:
![image](https://user-images.githubusercontent.com/13931163/136152040-e6d4b89d-b603-498d-9ee0-b7f3bb07ef61.png)

This spam is never ending, and this information was actually never useful (more than a year running and never had to rely in this information).

**Comment by mykola-mokhnach** [comment]
This log has been removed since the beta version of the client as it only supports W3C

**Comment by SpencerMelo** [comment]
A bit late to the party, and thanks for the information @mykola-mokhnach, on that time (years ago) what I had to do to solve:
```java
Logger.getLogger("org.openqa.selenium").setLevel(Level.OFF);
```
I will close this.
