### ISSUE TITLE
[Enhancement] [Android] [swipe function] Do not shutdown Appium server when there is an error with swipe()

### ISSUE THREAD

**Issue by vietnq254** [appium/java-client#154]
Hello,

I am using ``` Java client 2.1.0 ```.
``` 
private AndroidDriver dr;

public void test()
{
    List<WebElement> lst = ...;
    WebElement element = lst.get(lst.size() - 1); // sure that the size > 1
    dr.swipe(0, element.getLocation().y, 0, 0, 800);
}
``` 
The function ```swipe()``` sometimes run failed and the Appium server will shutdown immediately although I can see the movement. 

It is better if Appium logs the warnings and ignore this error and Appium can continue to work.

**Comment by Jonahss** [comment]
I agree. can you post the appium server logs, and the code you used to the [appium](github.com/appium/appium) project?
