### ISSUE TITLE
Unable to launch Gmail Android App.

### ISSUE THREAD

**Issue by clmathuriya** [appium/java-client#156]
Hi,
I am using Appium server 1.3.5 &  java client 2.1.0 with emulator API level 19.

I am unable to launch gmail android application.
Below is my java code:

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

public class YoutubeTest {

	public static void main(String[] args) {

		DesiredCapabilities capabilities = new DesiredCapabilities();
		File app = new File("/home/chhagan/AppsTest/com.google.android.gm.apk");

		capabilities.setCapability(MobileCapabilityType.APP,
				app.getAbsolutePath());
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,
				"emulator-5554");
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,
				1800);

		try {
			AndroidDriver driver = new AndroidDriver(new URL(
					"http://127.0.0.1:4723/wd/hub"), capabilities);
			System.out.println(driver.currentActivity());
		} catch (MalformedURLException e) {

			e.printStackTrace();
		}

	}

}

while running this i am getting below error:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 99.60 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'chhagan-HP-EliteBook-8440p', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-45-generic', java.version: '1.7.0_75'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:39)
	at YoutubeTest.main(YoutubeTest.java:31)

Appium Logs are : 

info: Welcome to Appium v1.3.5 (REV a124a15677e26b33db16e81c4b3b34d9c6b8cac9)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":1800,"app":"/home/chhagan/AppsTest/com.google.android.gm.apk","platformName":"Android","deviceName":"emulator-5554"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/chhagan/AppsTest/com.google.android.gm.apk
info: [debug] Creating new appium session 856658e6-33fc-4093-ba6d-a56dfa19ab6c
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.7.0_75
info: [debug] Checking whether adb is present
info: [debug] Using adb from /home/chhagan/android/adt/sdk/platform-tools/adb
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device emulator-5554
info: [debug] Setting device id to emulator-5554
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 wait-for-device
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /home/chhagan/android/adt/sdk/build-tools/android-4.4W/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/build-tools/android-4.4W/aapt dump badging /home/chhagan/AppsTest/com.google.android.gm.apk
info: [debug] badging package: com.google.android.gm
info: [debug] badging act: null
info: [debug] Parsed package and activity are: com.google.android.gm/ConversationListActivityGoogleMail

info: [debug] Getting device API level
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: Device API level is: 19
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language: en
info: [debug] java -jar "/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/home/chhagan/AppsTest/com.google.android.gm.apk" "/tmp/com.google.android.gm" en
info: [debug] No strings.xml for language 'en', getting default strings.xml
info: [debug] java -jar "/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/home/chhagan/AppsTest/com.google.android.gm.apk" "/tmp/com.google.android.gm"
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 push "/tmp/com.google.android.gm/strings.json" /data/local/tmp
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /home/chhagan/android/adt/sdk/build-tools/android-4.4W/aapt
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/build-tools/android-4.4W/aapt dump xmltree /home/chhagan/AppsTest/com.google.android.gm.apk AndroidManifest.xml
info: [debug] Set app process to: com.google.android.gm
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for /home/chhagan/AppsTest/com.google.android.gm.apk.
info: [debug] executing cmd: java -jar /home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/jars/verify.jar /home/chhagan/AppsTest/com.google.android.gm.apk
info: [debug] App already signed.
info: [debug] Zip-aligning /home/chhagan/AppsTest/com.google.android.gm.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /home/chhagan/android/adt/sdk/build-tools/android-4.4W/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/build-tools/android-4.4W/zipalign -f 4 /home/chhagan/AppsTest/com.google.android.gm.apk /tmp/115117-23457-1mtc52t/appium.tmp
info: [debug] MD5 for app is a08029665438aa9327453206ec1f65e3
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "ls /data/local/tmp/a08029665438aa9327453206ec1f65e3.apk"
info: [debug] Getting install status for com.google.android.gm
info: [debug] Getting device API level
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages -3 com.google.android.gm"
info: [debug] App is installed
info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "am force-stop com.google.android.gm"
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "pm clear com.google.android.gm"
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 push "/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 install "/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 install "/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
info: [debug] dataDir set to: /data
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] Getting device API level
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.google.android.gm/ConversationListActivityGoogleMail
"
info: [debug] We tried to start an activity that doesn't exist, retrying with . prepended to activity
info: [debug] Getting device API level
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.google.android.gm/.ConversationListActivityGoogleMail
"
error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 12.702
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
info: [debug] Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    at null.<anonymous> (/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:1130:21)
    at null.<anonymous> (/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)","origValue":"Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity"},"sessionId":null}
info: <-- POST /wd/hub/session 500 37591.701 ms - 346

**Comment by Jonahss** [comment]
Try running the adb command that appium used to try and start the app:
` /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.google.android.gm/.ConversationListActivityGoogleMail"`

**Comment by clmathuriya** [comment]
@Jonahss : 
I think appium is not able to identify launchable activity from apk properly.
Is anybody able to launch gmail android app using Appium ?

I tried below:
/home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5556 shell am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.google.android.gm/.ConversationListActivityGoogleMail
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
Stopping: com.google.android.gm
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.gm/.ConversationListActivityGoogleMail }
Error type 3
Error: Activity class {com.google.android.gm/com.google.android.gm.ConversationListActivityGoogleMail} does not exist.

**Comment by Jonahss** [comment]
Hmm. If you can figure out what the proper launchable activity is, you can specify it directly through appium.

**Comment by clmathuriya** [comment]
@Jonahss  Any idea why appium is not able to get launchable activity details from apk in this case?

**Comment by Jonahss** [comment]
I'm not sure. The fact that it is the Gmail app might mean that they use
all sorts of trickery beyond the standard setup. Perhaps @bootstraponline
might know details.

**Comment by Fanch-** [comment]
```java
getDriver().startActivity("com.google.android.gm", "ConversationListActivityGmail");
```
It works for me.

**Comment by clmathuriya** [comment]
Thank you @Fanch- It helped.

**Comment by ChristianFontalvo** [comment]
Thank you @Fanch- It works for me too
