### ISSUE TITLE
Unable to use gestures on android browser, java-client:2.1.0

### ISSUE THREAD

**Issue by md29** [appium/java-client#157]
i have tried to using below 2 methods but i get error:
org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11 milliseconds

1)
MobileElement e = (MobileElement) driver.findElement(By.cssSelector(".image-wrap img"))		
e.tap(1, 1000)
e.zoom()
e.swipe(SwipeElementDirection.LEFT,1000)

2)
JavascriptExecutor js = (JavascriptExecutor) driver
HashMap<String, Double> swipeObject = new HashMap<String, Double>()
swipeObject.put("startX", 0.95)
swipeObject.put("startY", 0.5)
swipeObject.put("endX", 0.05)
swipeObject.put("endY", 0.5)
swipeObject.put("duration", 1.8)
js.executeScript("mobile: swipe", swipeObject)

**Comment by Jonahss** [comment]
You shouldn't be finding elements by CSSSelector, that shouldn't work on appium (unless, are you inside of a webview, or a browser?)

There might currently be issues with TouchActions on webviews in android. I think this is related: https://github.com/appium/appium/issues/4075
