### ISSUE TITLE
[Question] Is there a roadmap/release plan for Appium 8?

### ISSUE THREAD

**Issue by Trigtrig** [appium/java-client#1586]
Hello everyone,

Is there a roadmap regarding Appium 8? Or possible release candidates like with Selenium 4 this year? I am very interested in some changes I just saw in Appium 8 beta. Especially the changes in the WebDriver inheritance (no MobileDriver anymore).

Best regards
Trig

**Comment by SrinivasanTarget** [comment]
@Trigtrig we are looking for feedbacks on the beta version to tune the stable version better. Feel free to try out beta and let us know. You can expect few more beta version before the final one.

**Comment by Trigtrig** [comment]
ok, thank you :)
