### ISSUE TITLE
scrollTo(), swipe (SwipeElementDirection (...) )

### ISSUE THREAD

**Issue by Fanch-** [appium/java-client#159]
Well, still with **java-client version 2.1.0 and appium 1.3.5**.

I'm currently trying to optimize stories/scenarios (Android at the moment).
When I perform scrollTo(), scrollToExact(), the problem is : it looks for the whole window/listView before stopping the scroll, even if it finds an occurence of element on the way. (It makes even slower the scenarios).
(Must be appium issue)

I would like to just specify the scroll direction, the element and optionally the number of the occurence where the scroll should stop (by defaut first one). I would like to know if the actual behaviour is the one wanted or if some improvements are provided.

That's why I'm currently using loop+ swipe() function to scroll without serious time wasting.

About the swipe (SwipeElementDirection (...) ) function : there is an issue with listView. Without offset it won't scroll the element. 
```java
    public static void swipeDownLikeSwipeElementDirection(MobileElement element, int duration){
        int offset = 1;
        Point p = element.getCenter();
        Point location = element.getLocation();
        Dimension size = element.getSize();
        getDriver().swipe(p.getX(), location.getY() + size.getHeight() - offset, p.getX(), location.getY() , duration);
    }
```
And about the duration parameter, it seems if we try | duration < 1.5s| the swipe has trouble to stop and it scrolls more elements than expected. No problem for | duration > 1.5s |

**Comment by Jonahss** [comment]
Your solution looks good. What would you like us to do?
Appium is still looking for a good way to do scrollTo commands that work in both Android and iOS

**Comment by Fanch-** [comment]
Well, I use swipe() function to *'scroll'*.
From my point of view : scroll() function (which is using scrollIntoView() ) isn't really optimized *for Android* at the moment.

Meanwhile, I would like to have a workaround somewhat more malleable and less time wasting.

For example : 
First, a modification to consider **enum SwipeElementDirection** compatible with **listView** (down/up) : 

```Java
    public enum SwipeElementDirection {
        UP {
            void swipe(AppiumDriver driver, MobileElement element, int duration) {
                int offset = 1;
                Point p = element.getCenter();
                Point location = element.getLocation();
                Dimension size = element.getSize();
                driver.swipe(p.getX(), location.getY() + size.getHeight() + offset, p.getX(), location.getY(), duration);
            }
        },
        DOWN {
            void swipe(AppiumDriver driver, MobileElement element, int duration) {
                int offset = 1;
                Point p = element.getCenter();
                Point location = element.getLocation();
                Dimension size = element.getSize();
                driver.swipe(p.getX(), location.getY(), p.getX() - offset, location.getY() + size.getHeight(), duration);
            }
        },
```
Then something like this to swipe() until the desired element (still with up/down) : 

```Java
    /**
     * (scroll) Swipe an element to find another
     */
    public static void swipeElementUntilStopperElement(String direction, MobileElement swipedElement, MobileElement stopperElement) {
        SwipeElementDirection dir;

        if (direction.toUpperCase() == "DOWN") { dir = SwipeElementDirection.DOWN; }
        else { dir = SwipeElementDirection.UP;}


        boolean searchElement = true;
        String lastTxtElement = null;
        String previousTxtElement;
        List<WebElement> elements;

        while(searchElement)
        {
            previousTxtElement = (lastTxtElement != null) ? lastTxtElement : "unset";

            //get text of last element ( detect scrollView or listView)
            elements = (getDriver().findElementByAndroidUIAutomator("new UiSelector().className(\"android.widget.ListView\")").isDisplayed()) ?
                    getDriver().findElementsByAndroidUIAutomator("new UiSelector().className(\"android.widget.ListView\")") :
                    getDriver().findElementsByAndroidUIAutomator("new UiSelector().className(\"android.widget.ScrollView\")");
            lastTxtElement = elements.get(elements.size() - 1).getText();

            //compare element's text between last index of previous swipe and last index of current swipe to detect end of scrolling
            if (lastTxtElement.equals(previousTxtElement)){
                throw new NoSuchElementException("stopperElement not found");
            }

            try
            {
                //stop when desired element is displayed
                stopperElement.isDisplayed();
                searchElement = false;
            }
            catch (Exception e)
            {
                //swipe up|down when desired element is not displayed
                swipedElement.swipe(dir, 1700);
            }
        }
    }
```
I do one more swipe to detect end of element and then throw an error, do you have a solution to avoid this additional swipe ? (Without timeout/loop over a fixed number)

**Comment by TikhomirovSergey** [comment]
Hi guys!
I'm really not sure that above is a thing that can be included at java-client build. We provide BASIC things. The code that above will work against Android. I'm not sure that it will be compatible with each-Android project. And it is not compatible with iOS at all.

But the swiping with offset is a really good point. :) ... And it can be implemented without serious efforts.

@Jonahss probation at my new job will finished soon. So I am going to enhance it.

**Comment by Fanch-** [comment]
You're right, the API provides BASIC things. I hope we'll get a robust scroll function() soon !
+1 for offset.

**Comment by Jonahss** [comment]
I'll create a new issue to add the scroll offset. You can submit a pull request if you like :)

---
That's good news @TikhomirovSergey , I look forward to it :)

**Comment by Jonahss** [comment]
A robust scroll function is something we all look forward to. It will require us all deciding on a good way of doing it in Appium for both iOS and Android. I will make sure it gets addressed after we take care of outstanding bugs and issues.

**Comment by Divyashreep** [comment]
@Fanch- Thanks, I have used your logic  scroll down until we find target element , it worked fine for me.

**Comment by rompic** [comment]
thanks as well. I adapted it to scroll to an element without knowing any string value (helpful if you try to automate in different languages)

            boolean searchElement=true;
            while(searchElement){
                    try
                    {
                        //stop when desired element is displayed
                        searchElement=!item.isDisplayed();
                    }
                    catch (Exception e)
                    {
                        //swipe up when desired element is not displayed (menu is found by java annotations)
                        menu.swipe(SwipeElementDirection.UP, 1, 1, 1700);
                    }
            }
there's no break condition yet.

i'm thinking about
- limiting the swipe retries
- getting the texts from the elements as Fanch does
- somehow check if I arrived at the end of the screen yet (if possible)

**Comment by RajeevReghuvaranNair** [comment]
For guys who are using python with appium; i have used the swipe function to perform the scroll as it works well:

APK used: APIDemo.apk

def test_swipe(self):
        x = []
        sleep(1)
        self.driver.find_element_by_name("Views").click() 
        sleep(1)
        while x == []:    #Perform scroll till i get the desired item i am looking for, here its "ImageView" which is in the second page
            x = self.driver.find_elements_by_name("ImageView")
            size = self.driver.get_window_size()        
            starty = int(size["height"] * 0.80)
            endy = int(size["height"]*0.20)        
            startx = int(size["width"]/2)
            sleep(2)
            self.driver.swipe(startx, starty, startx, endy, 3000) #Swipe from bottom to top
            sleep(2)

**Comment by bloomzCode** [comment]
@Fanch- 

In recent update appium "mobile : scroll"/"mobile : scrollTO " deprecated, following code will work and video will help you to implement.
 
Scroll to text : 

    MobileElement radioGroup = (MobileElement) wd
    
    .findElementByAndroidUIAutomator("new UiScrollable(new UiSelector()"
    
    ".resourceId(\"+<listview_id>+\")).scrollIntoView("
    
    "new UiSelector().text(\"+<your_text>+\"));");
    
    radioGroup.click();

This link will help you : https://www.youtube.com/watch?v=bT3tqaLNn-Y

**Comment by sharonandrades** [comment]
For ScrollTo() function the below method worked very well,

`driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector()).scrollIntoView("+ "new UiSelector().text(\"_input your text name here_\"));").click();`

Please try using the above method & this should solve your problem with regards to scrollTo() function, thanks.

**Comment by joshidipakkumar** [comment]
Hi There,

I am using appium 1.6.1 and java client java-client-6.0.0-BETA5.jar.
I am not able to scroll using below code:

MobileElement element = (MobileElement) driver.findElements(MobileBy.AndroidUIAutomator(
		            "new UIScrollable(new UiSelector().className(\"android.widget.TextView\").clickable(true).index(10)).scrollIntoView("+ "new UiSelector().text(\"Update\"))"));
		
		element.click();

and also i cant find driver.scrollTo or swipe() in this version. I am stuck :(



it gives below error:

org.openqa.selenium.WebDriverException: Returned value cannot be converted to List<WebElement>: {error=unknown command, message=The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource., stacktrace=UnknownCommandError: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
    at errorFromMJSONWPStatusCode (C:\Users\deepak.msp\AppData\Local\appium-desktop\app-1.6.1\resources\app\node_modules\appium-base-driver\lib\protocol\errors.js:769:12)
    at Socket.<anonymous> (C:\Users\deepak.msp\AppData\Local\appium-desktop\app-1.6.1\resources\app\node_modules\appium-android-bootstrap\lib\bootstrap.js:129:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)}
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'MSPSYS927', ip: '192.168.0.108', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AppiumDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:354)
	at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:54)
	at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:152)
	at io.appium.java_client.FindsByAndroidUIAutomator.findElementsByAndroidUIAutomator(FindsByAndroidUIAutomator.java:51)
	at io.appium.java_client.MobileBy$ByAndroidUIAutomator.findElements(MobileBy.java:211)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:305)
	at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:50)
	at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:148)
	at sanitySuite.ProfileUpdate.ProfUpdate(ProfileUpdate.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:352)
	... 33 more

**Comment by joshidipakkumar** [comment]
@sharonandrades ,

Thanks mate your below code solves my scrolling issue, I was trying since 3 days :). thanks a lot man

cheers!!

driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector()).scrollIntoView("+ "new UiSelector().text(\"_input your text name here_\"));").click();
