### ISSUE TITLE
Failed to Create Session[Unable to authenticate request] using Appium Java Client 8.0.0-beta in Pefecto Cloud

### ISSUE THREAD

**Issue by anoopsimon** [appium/java-client#1597]
## Description

Failed to Create Session using Appium **Java Client 8.0.0-beta** in Pefecto Cloud.
Exception : **_SessionNotCreatedException : Could not Start a new session. Response Code 401 : Unable to authenticate request_.**

## Environment

* Java client build version : **8.0.0-beta**
* Cloud Vendor / Infrastructure: **Perfecto Cloud**
* Mobile platform/version : **Samsung S 21**
* Real device or emulator/simulator: **Real Device**

## Details
Session created successfully when I used _RemoteWebDriver_ instead of _AppiumDriver/AndroidDriver_ to instantiate android session in perfecto.

When lookedup selenium 4 documentation specific to [ugrade to Selenium 4.0.0](https://www.selenium.dev/documentation/getting_started/how_to_upgrade_to_selenium_4/)  , I found that there is a '**_cloud vendor specific capability_**' that need to be passed as a separate map to the DesiredCapabilities Object while creating session remotely.

So I suspect there is something to do with AppiumDriver/AndroidDriver translating new capability object in Appium Version 8.0.0-beta

I am a regular user of Appium Java Client with Perfecto. Code snippet(screenshot) provided below works just fine with Appium Version <= 7.6.1

This issue is a blocker for me to upgrade Appium to V 8.*.* beta.

## Code To Reproduce Issue

![image](https://user-images.githubusercontent.com/63703161/143006594-627daaad-8acf-415d-8e42-a03ab4a27028.png)

## Exception Stacktraces

![image](https://user-images.githubusercontent.com/63703161/143008583-c2eff917-d935-46aa-af5b-6fbed0e922cc.png)

**Comment by mykola-mokhnach** [comment]
- Please attach the server log
- Have you tried to contact cloud provider's customer support?

**Comment by TFGAccount** [comment]
We are also getting same error message, any solutions for this?

**Comment by anoopsimon** [comment]
This issue has been fixed in Java Client version 8.0.0 .Hence closing the bug
