### ISSUE TITLE
Unable to switch to webview context in appium 7.6

### ISSUE THREAD

**Issue by mikepeceros** [appium/java-client#1604]
## The problem

I'm not able to switch to webview context in an Android device since the chrome driver version is outdated.

## Environment

Appium 7.6.0
I do not have selenium dependency since I know appium already contains selenium 3.141.59

## Details

I'm currently working against Gigafox devices but this looks beyond the platform since the message is clear (the chrome version). I've tried one month earlier and my scripts were passing at that time. I did not change the capabilities. I'm just initializing the appium driver and adding the capabilities before trying the switch.

```
in a BaseActions class
protected DesiredCapabilities cap = new DesiredCapabilities();
protected AppiumDriver<MobileElement> driver = null;

public class WebViewTests extends BaseActions 
@Test
    public void testCaseAndroid() {
        url = new URL("https://xxxxxxxxxx.gigafox.io/Appium");
        cap.setCapability("gigafox:username", "xxxxxx.xxxxx@xxxxxxxx.com");
        cap.setCapability("gigafox:apikey", "xxxxxxxxxxxxxxxxxxxxx");
        cap.setCapability("newCommandTimeout", "100000");
        cap.setCapability("gigafox:skipInstall", "false");
        cap.setCapability("autoGrantPermissions", "true");
        cap.setCapability("noReset", "false");
        cap.setCapability("fullReset", "false");
        cap.setCapability("automationName", "Appium");
        cap.setCapability("platformName", "Android");
        cap.setCapability("gigafox:device", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        cap.setCapability("gigafox:application", "xxxxxxxxxxxxxxxxxxxxxxx");
        cap.setCapability("gigafox:sessionName", "xxxxxxxxxxxxxxxxxxxxx");
        driver = new AndroidDriver(url, cap);
        driver.context("WEBVIEW_chrome");
}
```

## Code To Reproduce Issue [ Good To Have ]

After verifying I have two available contexts

`driver.getContextHandles()`
0 = "NATIVE_APP"
1 = "WEBVIEW_chrome"

`driver.context("WEBVIEW_chrome")`

## Exception Stacktraces

`An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 96.0.4664.45 with package name com.android.chrome (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-U0MKK7L', ip: '192.168.0.105', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_292'
Driver info: io.appium.java_client.android.AndroidDriver`

## Link To Appium Logs

https://gist.github.com/mikepeceros/f8282968e3d02d7d0f61263621780087

**Comment by mykola-mokhnach** [comment]
I don't see any issues there. Is there something that prevents you from updating Chromedriver?

**Comment by mikepeceros** [comment]
This issue lies on the Gigafox platform that my team is working with since its chrome drive is outdated.
