### ISSUE TITLE
Cannot resolve symbol 'MobileElement', 'AndroidElement', and 'IOSElement' in 8.0.0Beta

### ISSUE THREAD

**Issue by deena-p** [appium/java-client#1612]
## Description

What happened to all the MobileElement type - AndroidElement, IOSElement in 8.0.0Beta

## Environment

* Java client build version  - 8.0.0 Beta

## Details

MobileElement, AndroidElement, and IOSElement are not available in 8.0.0Beta

## Code To Reproduce Issue [ Good To Have ]

Migrate appium from 7.x.x to 8.0.0 Beta.
MobileElement, AndroidElement, and IOSElement are not available

**Comment by valfirst** [comment]
@deena-p please check https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#mobileelement

**Comment by deena-p** [comment]
Thanks @valfirst. It works.
