### ISSUE TITLE
Make findElement return MobileElement

### ISSUE THREAD

**Issue by alexec** [appium/java-client#162]
I noticed in a presentation yesterday that they almost always casted to MobileElement. As MobileElement appears to be a sub-class of WebElement, you can modified the return type of findElement* to return MobileElement.

This would be backwards compatible. 

If we want to get technical, we are dealing with covarient return types:

http://c2.com/cgi/wiki?CovariantReturnTypes

**Comment by Jonahss** [comment]
I *totally* agree!
For some reason when I tried to override the method originally I ran into compilation errors, but looking at it now it seems fine.

Care to submit a Pull Request?

**Comment by TikhomirovSergey** [comment]
I think the better way is to propose PR to Selenium project. I've got the great idea how to implement this. If this PR will be rejected then it is easy to override __find__ methods here.

So I think we should work on two these directions (I'm sorry for my English).

**Comment by TikhomirovSergey** [comment]
PR proposed to Selenium: https://github.com/SeleniumHQ/selenium/pull/327
If you consider that it is good please vote for this.

**Comment by Jonahss** [comment]
Great!
I've found that mentioning your pull request on the #selenium irc can get it merged quicker ^.^

**Comment by TikhomirovSergey** [comment]
I thick this ticket should be closed
