### ISSUE TITLE
[8.0.0-beta2] OPTIONAL_INTENT_ARGUMENTS are only sent as lowercase 

### ISSUE THREAD

**Issue by bpaAtCardlay** [appium/java-client#1626]
## Description
My team is currently upgrade our usage the appium java client to the new 8.0.0-beta2 version, but in the process of upgrading we are experiencing an issue in regards to sending OPTIONAL_INTENT_ARGUMENTS to the device-under-test.
Prior to the upgrade we didn't have any issue sending "--ez TESTING true" to the android device, however after upgrading to 8.0.0-beta2 this is no longer passed through correctly. We are instead seeing "--ez testing true" being sent to the device.

Furthermore it seems that the entire payload has been changed such that `desiredCapabilities` are no longer sent, but rather `capabilities` are sent.

I am suspecting that we might simply be doing something wrong, in regards to using the new client and setting up capabilities, but I am unsure whether thats the case or if this is a bug - or an issue with Browserstack.

## Environment
- Client: "io.appium:java-client:8.0.0-beta2"
- Appium servier: 1.21.0 (also tested with: 1.19.1)
- We are running tests through Browserstack, using Appium
- Android Google Pixel 3, Pixel 4, Pixel 5
- Real device

## Details

Our current approach at setting up capabilities for the Driver is based on `DesiredCapabilities` and passing those to the `AndroidDriver(url, desiredCapabilities)`

The following snippet is directly from the appium logs when the test is being executed:
`[HTTP] --> POST /wd/hub/session`
`[HTTP]{"capabilities":{"firstMatch":[{"newCommandTimeout":0,"appium:appActivity":"com.company.app.MainActivity","appium:appPackage":"com.company.app.alpha","appium:autoGrantPermissions":true,"appium:automationName":"uiautomator2","appium:browserstack.appiumLogs":true,"appium:browserstack.appium_version":"1.21.0","appium:browserstack.debug":true,"appium:browserstack.deviceLogs":true,"appium:browserstack.networkLogs":true,"appium:browserstack.timezone":"copenhagen","appium:browserstack.video":true,"appium:buildName":"company app - 10000105 - google pixel 3 - android - 9.0 - 2022-01-07t13:21:56","appium:deviceName":"google pixel 3","appium:name":"company-app","appium:optionalIntentArguments":"--ez testing true" appium:resetKeyboard":true,"appium:unicodeKeyboard":true,"appium:skipServerInstallation":"true","platformName":"Android","appium:udid":"8ARX0XT0N","appium:newCommandTimeout":0,"appium:nativeWebScreenshot":true,"a..`

The appium log when the app is tarted and the launch arguments are provided:
`[debug] [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s 8ARX0XT0N shell am start -W -n com.company.app.alpha/com.company.app.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 --ez testing true`

Running the same setup, but without upgrading to 8.0.0-beta2 we get the following, which has the correct casing on our launch arguments:
`[HTTP] --> POST /wd/hub/session`
`[HTTP] {"desiredCapabilities":{"appPackage":"com.company.app.alpha","buildName":"COMPANY APP - 10000105 - Google Pixel 3 - ANDROID - 9.0 - 2022-01-07T13:42:33","deviceName":"Android","appActivity":"com.company.app.MainActivity","automationName":"UiAutomator2","autoGrantPermissions":true,"unicodeKeyboard":true,"platformName":"Android","optionalIntentArguments":"--ez TESTING true","resetKeyboard":true,"browserstack.is_hub_canary":"false","acceptSslCert":false,"detected_language":"selenium/3.141.59 (java mac)","new_bucketing":true,"device":"google pixel 3","sessionName":"COMPANY-APP","platform":"ANDROID","os_version":"9.0","chromeOptions":{"w3c":false},"browserstack.minOSVersion":"7.0","bundleID":"com.company.app.alpha","bundleId":"com.company.app.alpha","nativeWebScreenshot":true,"version":"","mobile":{"browser":"mobile","version":"Google Pixel 3-9.0"},"orig_os":"android","64bit":false,"udid":"8CBX1LTC1","a...`

And the command launching the app:
`[debug] [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s 8ARX0XW2D shell am start -W -n com.company.app.alpha/com.company.app.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 --ez TESTING true`

**Comment by mykola-mokhnach** [comment]
the log above looks suspicious to me. v8 only supports w3c sessions, so sending desiredCapabilities should not be happening. Also, the migration [guide](https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#strict-w3c-specification-compatibility) explicitly states that Options descendants should be used instead of the obsolete DesiredCapabilities class

**Comment by bpaAtCardlay** [comment]
In regards to the desiredCapabilities, this is only used when not upgrading to 8.0.0-beta2, when we upgrade to 8.0.0-beta2 we are only seeing capabilities being passed through.

We have tried with using the UiAutomator2Options() instead of using capabilities, but are seeing the same results:
`2022-01-07 14:31:59:725 - [HTTP] {"capabilities":{"firstMatch":[{"newCommandTimeout":0,"appium:appActivity":"com.company.app.MainActivity","appium:appPackage":"com.company.app.alpha","appium:autoGrantPermissions":true,"appium:automationName":"uiautomator2","appium:browserstack.appiumLogs":true,"appium:browserstack.appium_version":"1.21.0","appium:browserstack.debug":true,"appium:browserstack.deviceLogs":true,"appium:browserstack.networkLogs":true,"appium:browserstack.timezone":"copenhagen","appium:browserstack.video":true,"appium:buildName":"company app - 10000105 - google pixel 3 - android - 9.0 - 2022-01-07t15:31:25","appium:deviceName":"google pixel 3","appium:name":"company-app","appium:optionalIntentArguments":"--ez testing true","appium:resetKeyboard":true,"appium:unicodeKeyboard":true,"appium:skipServerInstallation":"true","platformName":"Android","appium:udid":"88PX01XAN","appium:newCommandTimeout":0,"appium:nativeWebScreenshot":true,"a...`

Our current approach with options for android:
```
val options = UiAutomator2Options()
options.setDeviceName(driverConfig.device.deviceName)
options.setPlatformVersion(driverConfig.device.version)
options.setLanguage(driverConfig.language)
options.setLocale(driverConfig.locale)
options.setPlatformName("Android")
options.setAppPackage(driverConfig.app.androidPackage)
options.setAppActivity(driverConfig.app.androidActivity)
options.setAutoGrantPermissions(true)
options.setAutomationName("UiAutomator2")
options.setOptionalIntentArguments(driverConfig.launchArguments)

val driver = AndroidDriver(url, options)
```

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot reproduce the issue locally.

This is what I get after executing a local test with the following options

```java
      service = new AppiumServiceBuilder()
                .withIPAddress("127.0.0.1")
                .usingPort(PORT)
                .build();
        service.start();

        UiAutomator2Options options = new UiAutomator2Options()
                .setDeviceName("Android Emulator")
                .setApp(apiDemosApk().toAbsolutePath().toString())
                .setOptionalIntentArguments("-YOLO")
                .eventTimings();
        driver = new AndroidDriver(service.getUrl(), options);
```

```
[HTTP] --> POST /session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:app":"/Users/elf/code/java-client/build/resources/test/apps/ApiDemos-debug.apk","appium:automationName":"UIAutomator2","appium:deviceName":"Android Emulator","appium:eventTimings":true,"appium:optionalIntentArguments":"-YOLO","platformName":"android"}}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"appium:app":"/Users/elf/code/java-client/build/resources/test/apps/ApiDemos-debug.apk","appium:automationName":"UIAutomator2","appium:deviceName":"Android Emulator","appium:eventTimings":true,"appium:optionalIntentArguments":"-YOLO","platformName":"android"}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1641627364836 (08:36:04 GMT+0100 (Central European Standard Time))
[Appium] Attempting to find matching driver for automationName 'UIAutomator2' and platformName 'android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at /Users/elf/.appium/appium-uiautomator2-driver/node_modules/appium-uiautomator2-driver
[Appium] Appium v2.0.0-beta.23 creating new AndroidUiautomator2Driver (v1.73.0) session
[Appium] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[Appium] Appium's BaseDriver version is 8.2.2
[Appium] Could not determine AndroidUiautomator2Driver's BaseDriver version
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:app": "/Users/elf/code/java-client/build/resources/test/apps/ApiDemos-debug.apk",
[debug] [BaseDriver]     "appium:automationName": "UIAutomator2",
[debug] [BaseDriver]     "appium:deviceName": "Android Emulator",
[debug] [BaseDriver]     "appium:eventTimings": true,
[debug] [BaseDriver]     "appium:optionalIntentArguments": "-YOLO"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
```

Maybe try to debug your client code to figure out where exactly the argument case is changed?

**Comment by bpaAtCardlay** [comment]
I am not seeing any conversion on the client side, but in the response of the following call they are changed to lowercase:
AppiumDriver.java - line 225
```java
Response response = execute(new AppiumNewSessionCommandPayload(capabilities));
```
Which calls into the RemoteWebDriver:
```java
protected Response execute(CommandPayload payload) {
    Command command = new Command(sessionId, payload);
    Response response;

    long start = System.currentTimeMillis();
    String currentName = Thread.currentThread().getName();
    Thread.currentThread().setName(
      String.format("Forwarding %s on session %s to remote", command.getName(), sessionId));
    try {
      log(sessionId, command.getName(), command, When.BEFORE);
      response = executor.execute(command);
      log(sessionId, command.getName(), response, When.AFTER);

      if (response == null) {
        return null;
      }
```
Where the response from the executed command also has the lowercase values.


When inspecting the values returned in the response the value of optionalIntentArguments are lowercase but values for f.x. platformName or appActivity remains with starting capital letters (as they were passed to the constructor of the UiAutomator2Options) as far as I can see the values returned from the command they match up with what is being logged in the appium logs:
```
[debug] [BaseDriver] Creating session with W3C capabilities: {
2022-01-10 09:06:13:471 - [debug] [BaseDriver]   "alwaysMatch": {
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "appium:newCommandTimeout": 0,
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "platformName": "Android",
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "appium:deviceName": "google pixel 3",
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "appium:unicodeKeyboard": true,
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "appium:resetKeyboard": true,
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "goog:chromeOptions": {},
2022-01-10 09:06:13:471 - [debug] [BaseDriver]     "appium:chromedriverPorts": [
2022-01-10 09:06:13:471 - [debug] [BaseDriver]       [
2022-01-10 09:06:13:471 - [debug] [BaseDriver]         18111,
2022-01-10 09:06:13:471 - [debug] [BaseDriver]         18121
2022-01-10 09:06:13:471 - [debug] [BaseDriver]       ]
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     ],
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:systemPort": 8201,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:appActivity": "com.company.app.MainActivity",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:appPackage": "com.company.app.alpha",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:autoGrantPermissions": true,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:automationName": "uiautomator2",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.appiumLogs": true,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.appium_version": "1.21.0",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.debug": true,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.deviceLogs": true,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.networkLogs": true,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.timezone": "copenhagen",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:browserstack.video": true,
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:buildName": "company app - 10000106 - google pixel 3 - android - 9.0 - 2022-01-10t10:05:18",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:name": "company-app",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:optionalIntentArguments": "--ez testing true",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:skipServerInstallation": "true",
2022-01-10 09:06:13:472 - [debug] [BaseDriver]     "appium:udid": "8ABX0PKKJ",
2022-01-10 09:06:13:473 - [debug] [BaseDriver]     "appium:nativeWebScreenshot": true,
2022-01-10 09:06:13:473 - [debug] [BaseDriver]     "appium:platformVersion": "9.0"
2022-01-10 09:06:13:473 - [debug] [BaseDriver]   },
2022-01-10 09:06:13:473 - [debug] [BaseDriver]   "firstMatch": [
2022-01-10 09:06:13:473 - [debug] [BaseDriver]     {}
2022-01-10 09:06:13:473 - [debug] [BaseDriver]   ]
2022-01-10 09:06:13:473 - [debug] [BaseDriver] }
```

Furthermore, I can see that running against a local setup (e.g. not through Browserstack) I can see that both in the appium logs as well as the response from the above mentioned, is not being converted to lowercase.

**Comment by mykola-mokhnach** [comment]
> Furthermore, I can see that running against a local setup (e.g. not through Browserstack) I can see that both in the appium logs as well as the response from the above mentioned, is not being converted to lowercase.

Then it must be obviously a BS bug. Consider contacting their support
