### ISSUE TITLE
setLocation method is not supported by Appium java client 8.0.0-beta2

### ISSUE THREAD

**Issue by hamidmunir** [appium/java-client#1641]
## Description

Hi ,
I am trying to update geolocation with setLocation() in Appium and its  giving me syntax error.
 driver.setLocation(new Location(49, 123, 10));
Although It works fine with Appium java client 7.6.0 and gives no syntax error.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/16507620/152781415-be2cbf04-2fb4-4a9f-9164-c2abcf97eeba.png">

## Environment

* Java client : 8.0.0-beta2

**Comment by mykola-mokhnach** [comment]
This is expected. Make sure that the actual driver instance implements `io.appium.java_client.remote.SupportsLocation` interface

**Comment by hamidmunir** [comment]
> Make sure that t

Thanks it worked by creating AndroidDriver instead of AppiumDriver
