### ISSUE TITLE
cannot import io.appium.java_client.MobileElement

### ISSUE THREAD

**Issue by ChristianErdtmann** [appium/java-client#1659]
Hello, i trying to use appium for Android Studio.

I have downloaded the java-client-8.0.0.0
from https://appium.io/downloads.html
added it to my lib folder in my project and added it as libary.

I can import other things over the import tag like "io.appium.java_client.MobileCommand"
but if i write "io.appium.java_client." i missing the "MobileElement"

So i dont think that i have done something wrong by the import because i can import other classes form the java_client.
So why i cant import MobileElement.

Can you tell me what i have to do.
Did i miss something or is the MobileElement no longer named like this?

... But the Appium Inspector have generated Code with MobileElement.... so i think this class should be still available.

**Comment by mykola-mokhnach** [comment]
FYI @KazuCocoa @jlipps: the code generator in Appium Inspector should be updated for compatibility with Java Client v8

**Comment by KazuCocoa** [comment]
Yes, the code is not for Java 8 yet.
We had an issue: https://github.com/appium/appium-desktop/issues/1581

**Comment by saikrishna321** [comment]
Kazu, the issue which you pointed is different to what Mykola is asking. We need the inspector the generate Java test code as per Java-client version 8.0.0 changes.

**Comment by KazuCocoa** [comment]
ah, i see. I only saw "java 8" word.

We need to update https://github.com/appium/appium-inspector/blob/main/app/renderer/lib/client-frameworks/java.js properly. I've only updated python and ruby, which I knew necessary changes.

**Comment by SrinivasanTarget** [comment]
> @saikrishna321 or @SrinivasanTarget do you think one of you could do the inspector changes? i don't know what's different in appium java client 8

Sure will check over weekend

**Comment by mykola-mokhnach** [comment]
> @saikrishna321 or @SrinivasanTarget do you think one of you could do the inspector changes? i don't know what's different in appium java client 8

Should be nothing too complicated. Simply replace occurrences of MobileElement with WebElement. https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md contains more detailed changeless, but I assume only this one really affects the code generator

**Comment by Arifa105** [comment]
Hi ! i'm making test case in appium java and i'm facing this issue **Cannot resolve symbol 'MobileElement'**

**Comment by SrinivasanTarget** [comment]
> Hi ! i'm making test case in appium java and i'm facing this issue **Cannot resolve symbol 'MobileElement'** 

Mobile Element is removed from recent versions of Java client. Please check migration guide in Readme.

**Comment by darsh1197** [comment]
> > Hi ! i'm making test case in appium java and i'm facing this issue **Cannot resolve symbol 'MobileElement'**
> 
> Mobile Element is removed from recent versions of Java client. Please check migration guide in Readme.

Then how do i now initiate my Android driver?
