### ISSUE TITLE
URGENT! There is vulnerability in Spring Framework dependency. Need to update spring framework version

### ISSUE THREAD

**Issue by antonparyshev** [appium/java-client#1671]
Need to update dependency Spring Framework to version 5.3.18 ASAP, because existing version has vulnerability.

Regards,
Anton

**Comment by antonparyshev** [comment]
Could you clarify when new release will be available on mvn repo?

**Comment by valfirst** [comment]
@antonparyshev you can use JitPack builds: https://github.com/appium/java-client#how-to-install-latest-java-client-betasnapshots

**Comment by StephanB75** [comment]
@valfirst  has the pull request failed ?
![image](https://user-images.githubusercontent.com/90029825/161497769-dca8a722-4ec5-4b81-8142-e725d6eaae56.png)

**Comment by valfirst** [comment]
@StephanB75 some flaky tests are failed, but still you can use JitPack to get the latest build

**Comment by StephanB75** [comment]
@valfirst but the aspectjweaver 1.9.9.1 dependency is not in the latest master. Or is it not necessary ?

**Comment by valfirst** [comment]
I've just merged AspectJ dependency, but I don't see much correlation between Spring vulnerability and AspectJ dependency.

**Comment by azetor** [comment]
When this update will be released?
