### ISSUE TITLE
Can't find MobileDriver implementation with latest appium java client version

### ISSUE THREAD

**Issue by vivu034** [appium/java-client#1681]
## Description

Previously I was using legacy java client driver v4.1.0 and have used MobileDriver interface for instantiating both Android and iOS drivers.
Eg - MobileDriver mobileDriver = new AndroidDriver<AndroidElement>(AppiumServiceProvider.start().getUrl(),
                            capabilities);
mobileDriver = new IOSDriver<>(AppiumServiceProvider.start().getUrl(), capabilities);

And then I could use mobiledriver object to call methods like hideKeyboard, pressKeyCode etc.

But after using the latest version I no longer could use MobileDriver to create generic objects. It seems like we have to create separate objects for both Android and iOS.

## Environment

Appium version (or git revision) that exhibits the issue: v2.0.0-beta.27
Last Appium version that did not exhibit the issue (if applicable): v1.22.2
Desktop OS/version used to run Appium: Mac OS BigSur
Node.js version (unless using Appium.app|exe):v14.18.1
Mobile platform/version under test: Android 11.0
Real device or emulator/simulator: Emulator

## Details
Is there any alternate implementation for MobileDriver in latest java client with Appium 2.x version. Do we have to create separate objects for Android and iOS driver from now on?

**Comment by valfirst** [comment]
@vivu034 please find details in the migration guide: https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#appiumdriver
