### ISSUE TITLE
Unable To Locate Elements In Remote WindowsDriver Using ClassName

### ISSUE THREAD

**Issue by nocomply78** [appium/java-client#1683]
## Description
When trying to locate elements in a Windows app on a remote machine using AppiumBy.className, it appears as though className is not supported by RemoteWebDriver, causing StackOverflowError

Steps To Reproduce:
1. Install Appium v2 on a remote machine, e.g. npm install -g appium@2.0.0-beta.27
2. Install the windows driver for Appium, e.g. appium driver install windows
3. Set up a Selenium Grid:
3a. Create a new folder on the remote machine (e.g. C:\Grid), place the batch, toml & json files inside
3b. Create a lib folder inside the Grid folder, and place a copy of selenium-server-4.1.1.jar inside
3c. Run grid4-hub.bat, then grid4-appium-server.bat, then grid4-appium2-node-relay.bat
4. Launch a WindowsDriver session to open notepad.exe in the grid
5. Search for the text editor element by class name using AppiumBy, e.g. driver.findElement(AppiumBy.className("Edit"))

Result:
A StackOverflowError occurs in Selenium RemoteWebDriver code
Debugging shows it to be caused by the following response being received in org.openqa.selenium.remote.RemoteWebDriver#execute(org.openqa.selenium.remote.CommandPayload):
> org.openqa.selenium.InvalidArgumentException: Unable to determine element locating strategy for class name

## Environment

* Java client build version or git revision if you use some snapshot: 8.0.0
* Appium server version or git revision if you use some snapshot: 2.0.0-beta27
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 14.17.0
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* WindowsApplicationDriver version: 1.2.1

## Details

Recent attempts to reproduce this from scratch on fresh machines have ended with the WinAppDriver acting as though it's not listening on port 4723 - the error reported in Appium logs in this case is as follows:
> Encountered internal error running command: Error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually

To avoid this, I have had to install the WindowsApplicationDriver myself (v1.2.1), and use the APPIUM_WAD_PATH system variable to point to the executable.
N.B. I see the same "WinAppDriver server is not listening [...]" error when trying to point directly to v1.2.99 of WinAppDriver, so perhaps the appium driver install command is getting that version?
Either way, I now only seem to get to the point of locating elements when manually installing & specifying v1.2.1 of WinAppDriver.

## Code To Reproduce Issue [ Good To Have ]

[Code & files needed to reproduce](https://gist.github.com/nocomply78/79deb4c4bfebcd7a16d7a90350c0d226)

## Exception Stacktraces

[Java Stacktrace](https://gist.github.com/nocomply78/377ae1f5ea5b4e8a738b4df536d8b857)

## Link To Appium Logs
[Appium Logs](https://gist.github.com/nocomply78/8adb7f251d9398365ae0520f680af0c2)

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/16550

Basically grid 4 limits all non-w3c locator types. Consider reporting this issue to the Grid's issues tracker

**Comment by mykola-mokhnach** [comment]
> I see the same "WinAppDriver server is not listening [...]" error when trying to point directly to v1.2.99 of WinAppDriver, so perhaps the appium driver install command is getting that version

This is a pre-release build and it seems to be quite unstable. Unfortunately Microsoft does not maintain any updates/fixes to it since 2020

**Comment by nocomply78** [comment]
> > I see the same "WinAppDriver server is not listening [...]" error when trying to point directly to v1.2.99 of WinAppDriver, so perhaps the appium driver install command is getting that version
> 
> This is a pre-release build and it seems to be quite unstable. Unfortunately Microsoft does not maintain any updates/fixes to it since 2020 neither makes it open source, so people could fix the server on their own.

I did notice that 1.2.99 is still not considered stable, and added that info just to help anyone running into that error to find this trail of tickets in the future. It does seem strange that I see the same error after doing a standard install of Appium Server & appium-windows-driver, but it's all just anecdotal anyway :-)

> Duplicate of [appium/appium#16550](https://github.com/appium/appium/issues/16550)
> 
> Basically grid 4 limits all non-w3c locator types. Consider reporting this issue to the Grid's issues tracker

Looking at [appium/appium#16550](https://github.com/appium/appium/issues/16550) (and it's associated issues) it seems there's been a bit of back & forth between Selenium & Appium devs, and from what I understand we're either waiting for a W3C spec change or changes to endpoints in the Appium server.
I'll subscribe to that issue and see what happens I guess. :-)
And close this given that it's a dupe - apologies for adding a new issue unnecessarily - you'd think I'd be better at searching before submitting given that testing is my day job...

Thanks :-)
