### ISSUE TITLE
v2: Failed to start the session if SupportsOrientationOption is set 

### ISSUE THREAD

**Issue by alei01** [appium/java-client#1685]
## The problem
Failed to start the session if SupportsOrientationOption is set.

Exception:
`2022-04-13 09:12:21:016 - [Appium] Could not parse W3C capabilities: 'orientation' landscape is not included in the list`

## Environment

* Appium version (or git revision) that exhibits the issue: beta-30
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: MacOS 12.2.1 (21D62)
* Node.js version (unless using Appium.app|exe): v17.8.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS/Android
* Real device or emulator/simulator: real/simulator
* Appium CLI or Appium.app|exe: cli
* java-client verstion: 8.0.0

## Details
Setting the SupportsOrientationOption causes session creation fail. 
Options example:
```
    private XCUITestOptions withOptions() {
        new XCUITestOptions()
                .setApp("app")
                .setOrientation(ScreenOrientation.LANDSCAPE)
...
````

## Link to Appium logs
[log](https://gist.github.com/alei01/2842e4020b009572d30e8650babeecb6)

**Comment by alei01** [comment]
@mykola-mokhnach tried the next:
```
        XCUITestOptions xcuiTestOptions = new XCUITestOptions()
                .setApp("app")
                .amend(ORIENTATION_OPTION, ScreenOrientation.PORTRAIT.name())
```

and got the next exception:
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: 'orientation' PORTRAIT is not included in the list
```

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach tried the next:
> 
> ```
>         XCUITestOptions xcuiTestOptions = new XCUITestOptions()
>                 .setApp("app")
>                 .amend(ORIENTATION_OPTION, ScreenOrientation.PORTRAIT.name())
> ```
> 
> and got the next exception:
> 
> ```
> org.openqa.selenium.SessionNotCreatedException: Could not start a new session.
>  Response code 400. Message: 'orientation' PORTRAIT is not included in the list
> ```

Weird, it works for me locally. Could you please provide the full log?

**Comment by alei01** [comment]
Here you go [Appium server log](https://gist.github.com/alei01/d4219b90e909334a4f35490dc462a9f8)

**Comment by mykola-mokhnach** [comment]
I really don't have any idea why it does not work for you. `orientation` is defined to [strictly](https://github.com/appium/appium/blob/ee9584829cdcc1e94ba5e2d675ae78ddb23296a4/packages/base-driver/lib/basedriver/desired-caps.js#L29) equal one of ['LANDSCAPE', 'PORTRAIT']

@jlipps @boneskull maybe you know more?

**Comment by jlipps** [comment]
I can't repro using the same appium and xcuitest driver versions. the only thing I can think is maybe the string "PORTRAIT" being used here isn't in the ASCII character set? either that or some kind of interaction effect with the other capabilities. @alei01 can you reproduce with a totally basic set of capabilities?

**Comment by alei01** [comment]
I've cleared all project caches and the issue is not reproducing now. 
The bug could be closed as fixed.
