### ISSUE TITLE
session not created on sauce labs for iOS using Selenium 4

### ISSUE THREAD

**Issue by sonali9293** [appium/java-client#1690]
## The problem

When using the below config, the session is not getting created and is throwing Null Pointer exception 'because the return value of "java.lang.ThreadLocal.get()" is null'

## Environment
Appium version: 1.17.1
Appium (java-client): 8.0.0
Selenium 4.1.1

## Details
N/A

## Link to Appium logs
Attached Doc of log

## Code To Reproduce Issue [ Good To Have ]
Here is the code for reference.

- Capabilities

'MutableCapabilities caps = new MutableCapabilities();
			caps.setCapability("platformName", os);
			caps.setCapability("deviceOrientation", "portrait");
			caps.setCapability("browserName", browser);
			caps.setCapability("browserVersion", version);
			caps.setCapability("appium:deviceName", devicename);
			caps.setCapability("appium:platformVersion", platformversion);
			MutableCapabilities sauceOptions = new MutableCapabilities();
			sauceOptions.setCapability("name", methodName);
			sauceOptions.setCapability("appiumVersion", "1.17.1");
			if (buildTag != null) {
				caps.setCapability("build", buildTag);
			}
			caps.setCapability("sauce:options", sauceOptions);

			if (browser.toLowerCase().contains("chrome")) {
				ChromeOptions options = new ChromeOptions();
				options.addArguments("disable-translate");
				options.addArguments("disable-translate-new-ux");
				caps.setCapability(ChromeOptions.CAPABILITY, options);
			}

			// Launch remote browser and set it as the current thread
			webDriver.set(new RemoteWebDriver(
					new URL("https://" + username + ":" + accesskey + "@ondemand.saucelabs.com:443/wd/hub"),
					caps));
			`
Apparently, this same is working all fine for android but only for ioS there is this issue. What am i missing ?

##Error occured:
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.JavascriptExecutor.executeScript(String, Object[])" because the return value of "java.lang.ThreadLocal.get()" is null
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: 
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'W105482ZY2', ip: '192.168.29.171', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: RemoteWebDriver

[log (1).txt](https://github.com/appium/appium/files/8541438/log.1.txt)

**Comment by mykola-mokhnach** [comment]
This looks like an issue with the local automation script.

**Comment by sonali9293** [comment]
Could you tell me what changes would be needed? @mykola-mokhnach

**Comment by titusfortner** [comment]
@sonali9293 do you have a link to the test on Sauce that is failing?

We had a bug in beta version of Selenium 4 that would cause a problem like this when Sauce sent a redirect command (how it keeps the session open while it takes a while for a session to start), but that would be fixed for 4.1 for sure.

**Comment by sonali9293** [comment]
I am not sure if you would be able to access it as it is under a group [().](https://app.saucelabs.com/tests/3183feefa0024ca3ab02d283b81b419c) but I have attached the logs for reference. I have attached the video too. 

https://user-images.githubusercontent.com/83301919/164755528-ebb4cf05-b4a1-45cc-b353-888616cfba40.mp4

**Comment by titusfortner** [comment]
ok, @diemol just informed me that we only partially fixed it in the beta and we fully fixed it in 4.1.2, so upgrade your local Selenium and it should work.

**Comment by sonali9293** [comment]
This helped. It is not initializing the driver for iOS correctly. But, seems like none of the latest selenium added features such as NewWindow, getScreenshotAs, or even relative locator is compatible wit IOS. 
As we earlier discussed @titusfortner on this same, we have raised an issue for this and guess it is still in progress ( [https://github.com/appium/appium/issues/16749](url) ). How long do you guys think will it take to be added ? @mykola-mokhnach

**Comment by titusfortner** [comment]
Relative locator should work, it's just Javascript execution underneath. The others are new endpoints and the various drivers need to add them as well, from what I understand.

**Comment by titusfortner** [comment]
Ah here: https://github.com/appium/appium/issues/16749#issuecomment-1107437686

This might be chrome only, though.
