### ISSUE TITLE
re-open an installed app on an Android device

### ISSUE THREAD

**Issue by PriyaSilverback** [appium/java-client#170]
Any suggestions on how to open an app on an Android device without re-installing . This app is not a system app. A brief description of the app that i'm testing : Im enrolling an Android device into a server. During this process, the system re-directs me to playstore to install the app and enroll the device into server. I was able to automate this successfully. But then when I want to open this app for a different test scenario, I signed the app with my debug keys and gave as the target to re-open in a different test. When I run the test, the app appears to be re-installing as it un-enrolls my device. Any suggestions on how to open it as is?

**Comment by Jonahss** [comment]
Did you try the `--no-reset` [server flag](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md)? 

If still having an issue can you post to the github.com/appium/appium project? Not related to the java-client
