### ISSUE TITLE
Appium 8.0.0 can not access selenium support package

### ISSUE THREAD

**Issue by Jakwado** [appium/java-client#1700]
## Environment

Java: 15
Appium java-client version: 8.0.0

## Details

![image](https://user-images.githubusercontent.com/30602016/171148079-b947d9e4-300f-4cd0-9d95-a6ef913981f1.png)

I cannot use selenium classes when I pull appium java-client dependency v8.0.0. On the other hand when I pull selenium support as a separate dependency in pom here's what I get:

> .NoClassDefFoundError: org/openqa/
selenium/remote/AcceptedW3CCapabilityKeys

https://github.com/appium/java-client/issues/1108

Please provide any solution. Problem has been reported before:
https://github.com/appium/java-client/issues/1415

## Code To Reproduce Issue [ Good To Have ]
    

>     <parent>
>         <artifactId>XXXXX</artifactId>
>         <groupId>com.xxx</groupId>
>         <version>1.0-SNAPSHOT</version>
>     </parent>
>     <modelVersion>4.0.0</modelVersion>
> 
>     <artifactId>XXX</artifactId>
> 
>     <properties>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <maven.compiler.version>3.8.0</maven.compiler.version>
>         <spring.version>5.3.12</spring.version>
>         <appium.version>8.0.0</appium.version>
>         <junit.version>5.8.1</junit.version>
>         <lombok.version>1.18.22</lombok.version>
>         <assertj.version>3.21.0</assertj.version>
>         <awaitility.version>4.1.1</awaitility.version>
>         <reportportal.logger.version>5.1.1</reportportal.logger.version>
>         <reportportal.agent.version>5.1.1</reportportal.agent.version>
>         <feign.version>11.8</feign.version>
>     </properties>
> 
>     <dependencies>
>         
>         <dependency>
>             <groupId>io.appium</groupId>
>             <artifactId>java-client</artifactId>
>             <version>${appium.version}</version>
>         </dependency>
> 

## Exception Stacktraces

> package org.openqa.selenium.support.ui does not exist

**Comment by valfirst** [comment]
@Jakwado you need to add explicitly selenium-support dependency: `org.seleniumhq.selenium:selenium-support`

**Comment by valfirst** [comment]
@Jakwado make sure the version of `selenium-support` dependency is aligned with version of Selenium supported by Appium Java client

**Comment by Jakwado** [comment]
This is the dependency I added explicitly:
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>4.2.0</version>
        </dependency>

It aligns with java-client:8.0.0 dependencies.

**Comment by Jakwado** [comment]
What's selenium compatible version then? I tried 4.0.0, 4.12 and even notation you guys you in pom - "[4.0, 5.0)" - none of these work. Any tips?

> Factory method 'webDriver' threw exception; nested exception is java.lang.NoClassDefFoundError: org/openqa/selenium/remote/AcceptedW3CCapabilityKeys

**Comment by Jakwado** [comment]
Okay I went through the topic you sent in your latest message. Upgrading Appium to 8.1 helped. Thanks a lot for your help. Any ETA regarding it's presence on mvnrepository?

**Comment by valfirst** [comment]
It's already available: https://github.com/appium/java-client/issues/1695#issuecomment-1141834902
