### ISSUE TITLE
java.lang.ClassCastException: class org.openqa.selenium.Platform$23 cannot be cast to class java.lang.String (org.openqa.selenium.Platform$23 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by n00bstr** [appium/java-client#1701]
## Description

Unable to create both IOSDriver and AndroidDriver after upgrading Selenium to 4.2.0 and Appium to 8.1.0. Error message displayed below:

Where creating iOSDriver:

```
java.lang.ClassCastException: class org.openqa.selenium.Platform$23 cannot be cast to class java.lang.String (org.openqa.selenium.Platform$23 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

	at io.appium.java_client.AppiumDriver.ensurePlatformName(AppiumDriver.java:136)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:105)
```

When creating AndroidDriver:
```
java.lang.ClassCastException: class org.openqa.selenium.Platform$22 cannot be cast to class java.lang.String (org.openqa.selenium.Platform$22 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

	at io.appium.java_client.AppiumDriver.ensurePlatformName(AppiumDriver.java:136)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:116)
```

## Notes
- iOSDriver created with Xcuitestoptions
- AndroidDriver created with both DesiredCapabilities and UiAutomator2Options
- Both methods results in the same cannot cast error message above

## Environment

* Java client build version or git revision if you use some snapshot: 8.1.0
* Appium server version or git revision if you use some snapshot: 2.0.0-beta.24
* Desktop OS/version used to run Appium if necessary: MacOS Monterey
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS/Android
* Real device or emulator/simulator: emulator/simulator

**Comment by mykola-mokhnach** [comment]
Could you please provide an example of the client code?

**Comment by n00bstr** [comment]
@mykola-mokhnach Please see below for iOS:

```
            driver = new IOSDriver(
                    new URL(appiumServerURL),
                    new IOSDriverTestOptions().getIOSTestOptions(deviceUnderTest, driverOptions));
```

```
public XCUITestOptions getIOSTestOptions(Device deviceUnderTest, DriverOptions driverOptions) {
        XCUITestOptions testOptions = new XCUITestOptions();
        String iOSAppPath = deviceUnderTest.getAppPackageToInstall();

        testOptions.setFullContextList(false);
        testOptions.setPlatformVersion(deviceUnderTest.getOsVersion());
        testOptions.setDeviceName(deviceUnderTest.getDeviceName());
        testOptions.setClearSystemFiles(true);
        testOptions.setApp(iOSAppPath);
        testOptions.setAutomationName("XCUITest");
        testOptions.setUseJSONSource(true);
        testOptions.setNoReset(true);
        testOptions.setSkipLogCapture(true);

        // Driver Timeout Settings
        testOptions.setNewCommandTimeout(Duration.ofSeconds(180));
        testOptions.setWdaConnectionTimeout(Duration.ofSeconds(180));
        testOptions.setWdaLaunchTimeout(Duration.ofSeconds(180));
        testOptions.setSimulatorStartupTimeout(Duration.ofSeconds(180));

        String derivedDataPath = getIOSDerivedDataDirectory();
        if (!Objects.equals(derivedDataPath, "")) {
            testOptions.setDerivedDataPath(derivedDataPath);
            testOptions.setUsePrebuiltWda(true);
        } else {
            testOptions.setUseNewWDA(true);
        }

        if (deviceUnderTest.getDeviceUDID().equals(""))  {
            testOptions.setEnforceFreshSimulatorCreation(true);
        } else {
            testOptions.setUdid(deviceUnderTest.getDeviceUDID());
        }

        testOptions.setShowIosLog(driverOptions.getShowIOSLogs());

        testOptions.setShowXcodeLog(driverOptions.getShowIOSLogs());

        testOptions.setMaxTypingFrequency(180);

        MiscTools miscTools = new MiscTools();
        int wdaPort = miscTools.randomAvailablePortGenerator(8101,8200);
        testOptions.setWdaLocalPort(wdaPort);

        int mjpegServerPort = miscTools.randomAvailablePortGenerator(9101,9200);
        testOptions.setMjpegServerPort(mjpegServerPort);

        return testOptions;
    }
```

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot reproduce this issue. Maybe try to reset maven/gradle caches?

**Comment by nir-tal-talkspace** [comment]
it happened to me also 
I think it's related to the new selenium version 4.2.1

**Comment by n00bstr** [comment]
@mykola-mokhnach Here are things I've tried so far:
- downgrading the Selenium version and also the Appium java-client version, did not help. Keeps referring to Selenium 4.2.0 libraries. 
- invalidating caches and restarting the IDE, did not help
- deleting the "target" folder on my Maven project and rebuilding, did not help

Appiumdriver works but cannot use driver-specific methods. Suspect AppiumDriver is doing something where AndroidDriver/IOSDriver is not or vice versa.

**Comment by Jakwado** [comment]
> try to set `platformName` capability explicitly as a workaround

I tried and it still did not help.

**Comment by smdelacruz** [comment]
Having the same issue

**Comment by rehansulehria** [comment]
> try to set `platformName` capability explicitly as a workaround

did try to set it using below code but did not work
`        XCUITestOptions xcuiTestOptions = new XCUITestOptions();
xcuiTestOptions.setCapability("platformName", "ios");
`

**Comment by SrinivasanTarget** [comment]
@Dan-Maor I will release a patch version tonight or tomorrow surely. Meanwhile, you can try jitpack for your verification using the instructions [here](https://jitpack.io/#appium/java-client/c68d503ff9)

**Comment by n00bstr** [comment]
Great tip, @SrinivasanTarget , tried that and have some progress. Please see below:

- Android with DesiredCapabilities works
- Android with UiAutomator2Options, unable to start a new session as there's no vendor prefix (assuming it is the appium: prefix here)
- iOS with XCUITestOptions, unable to start a new session as there's no vendor prefix
- iOS with Desired Capabilities works

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: platformVersion
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'Kevins-MacBook-Pro.local', ip: 'fe80:0:0:0:4aa:42ca:3c89:5114%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.3.1', java.version: '18'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [null, newSession {capabilities=[{appium:mjpegServerPort=9125, appium:showXcodeLog=false, appium:newCommandTimeout=180, appium:clearSystemFiles=true, appium:simulatorStartupTimeout=180000, appium:derivedDataPath=/Users/kevinlau/Library/Developer/Xcode/DerivedData/WebDriverAgent-coqvzuhnrltezneljbguogqmzerx, appium:automationName=XCUITest, appium:useJSONSource=true, appium:wdaConnectionTimeout=180000, appium:noReset=true, appium:showIOSLog=false, appium:wdaLaunchTimeout=180000, appium:wdaLocalPort=8128, appium:enforceFreshSimulatorCreation=true, platformVersion=14.5, appium:skipLogCapture=true, appium:deviceName=iPhone 11 Pro Max, appium:maxTypingFrequency=180, platformName=IOS, appium:fullContextList=false, appium:app=/Users/kevinlau/IdeaProjects/PostMoney.Test.Automation/src/main/resources/appPackages/iOS/iOS_PostMoney_Release_005.app, appium:usePrebuiltWDA=true}], desiredCapabilities=Capabilities {appium:app: /Users/kevinlau/IdeaProject..., appium:automationName: XCUITest, appium:clearSystemFiles: true, appium:derivedDataPath: /Users/kevinlau/Library/Dev..., appium:deviceName: iPhone 11 Pro Max, appium:enforceFreshSimulatorCreation: true, appium:fullContextList: false, appium:maxTypingFrequency: 180, appium:mjpegServerPort: 9125, appium:newCommandTimeout: 180, appium:noReset: true, appium:showIOSLog: false, appium:showXcodeLog: false, appium:simulatorStartupTimeout: 180000, appium:skipLogCapture: true, appium:useJSONSource: true, appium:usePrebuiltWDA: true, appium:wdaConnectionTimeout: 180000, appium:wdaLaunchTimeout: 180000, appium:wdaLocalPort: 8128, platformName: IOS, platformVersion: 14.5}}]
Capabilities {}
```

@mykola-mokhnach Can you please see the above? 

I guess the workaround here is to use DesiredCapabilities instead of the driver-specific XCUITestOptions and UiAutomator2Options for now.

**Comment by mykola-mokhnach** [comment]
Thanks for the update @n00bstr 
I've created another patch to fix the issue related to platformVersion capability. It turns out Selenium lib tries to add workarounds to browser issues, which badly hits our client: https://github.com/SeleniumHQ/selenium/blob/b0057b54cff7991add4299d58de53245f9d9ecf9/java/src/org/openqa/selenium/AcceptedW3CCapabilityKeys.java#L45

**Comment by lilkimo** [comment]
> @Dan-Maor I will release a patch version tonight or tomorrow surely. Meanwhile, you can try jitpack for your verification using the instructions [here](https://jitpack.io/#appium/java-client/c68d503ff9)

didnt work for me, same error message

**Comment by nirtal85** [comment]
> Thanks for the update @n00bstr I've created another patch to fix the issue related to platformVersion capability. It turns out Selenium lib tries to add workarounds to browser issues, which badly hits our client: https://github.com/SeleniumHQ/selenium/blob/b0057b54cff7991add4299d58de53245f9d9ecf9/java/src/org/openqa/selenium/AcceptedW3CCapabilityKeys.java#L45

@titusfortner @diemol

**Comment by cyberjaime45** [comment]
I was getting this issue on my Linux machine but not on my local Mac machine. We used Jenkins with Linux slaves pointing to Saucelabs.

The work around was  to change from: 
caps.setCapability("platformName", platform);
to:
caps.setCapability("appium:platformName", platform); 


It works with no issues so far.

**Comment by abhaybharti** [comment]
Any workaround for this issue?

**Comment by AYUSH-17** [comment]
Thanks @mykola-mokhnach ,
Platform issue has been resolved now.

I have updated java-client to 8.1.1 version , selenium-java to 4.2.1 and uiautomator2 to 2.2.0

**Comment by diemol** [comment]
Apologies for the trouble. `platform` has been deprecated for a long time, however it still brings issues everywhere. 

Adding `platformVersion` to the W3C valid caps as an exception was my mistake, since we are moving towards removing JWP from Java Selenium. However, this has been reverted and 4.2.2 won't have it. Will this affect you, @mykola-mokhnach?

**Comment by mykola-mokhnach** [comment]
@diemol I've decided to maintain a separate list of allowed W3C capability names in our client, so any changes in the Selenium's one should not affect the functionality much.

**Comment by diemol** [comment]
That makes sense. Do you know how I can find all "implicit" dependencies between those two code bases? We'd like to be aware of how changes upstream affect this client.

**Comment by mykola-mokhnach** [comment]
The first thing that comes into my mind is to create a new PR and trigger unit and end-to-end tests on it. It probably also makes sense to put alpha/beta branch containing recent changes of selenium lib into Gradle dependencies (not sure if Selenium has such), because it is already too late if the corresponding version is live.

**Comment by diemol** [comment]
I will find to see how we can publish nightly or weekly builds, and then we can work on using them to check potential issues with the Appium client.

**Comment by nir-tal-talkspace** [comment]
> I will see how we can publish nightly or weekly builds, and then we can work on using them to check potential issues with the Appium client.

thanks!!!
