### ISSUE TITLE
Error: java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.(Lorg/openqa/selenium/remote/ErrorCodes;Z)V

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#171]
I am getting following error with below code I am using java client version 1.5 selenium server standalone jar 2.42 and also tried with 2.44,2.45 (latest version)

gson jar version is 2.2.4

if (browser.equals("*browser")) {`
File appDir = new File("C:\\Users\\Desktop\\ipa\\apk\\ABC_04032015.apk");
DesiredCapabilities capabilities = new DesiredCapabilities();   
capabilities.setCapability(CapabilityType.BROWSER_NAME,"");
capabilities.setCapability("deviceName","ZX1B32HNBD");
capabilities.setCapability("platformVersion","4.4.4");
capabilities.setCapability("platformName","Android");
capabilities.setCapability("app", appDir.getAbsolutePath());
capabilities.setCapability("appPackage","com.example");
capabilities.setCapability("platformName","com.example.android");
System.out.println("Before calling appium");
driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
System.out.println("After calling appium");
}

**Comment by TikhomirovSergey** [comment]
Here is the conflict of two or more Selenium versions. 

Why do you use one more Selenium dependency when Appium java-client already depends on Selenium?

Ok. 

This dependency is enough
```xml
<dependency>
  <groupId>io.appium</groupId>
  <artifactId>java-client</artifactId>
  <version>versionYouNeed</version>
</dependency>
```

If you want to use it with another Selenium version then the example below should be correct

```xml
                <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>SeleniumVersionYouNeed</version>
		</dependency>```

		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>AppiumVersionYouNeed</version>

			<exclusions>
				<exclusion>
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>selenium-java</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
Also I recomend you to use new java-client versions - 2.1.0 or 2.2.0

**Comment by TikhomirovSergey** [comment]
@Jonahss 
What if the example below will be included in README.MD

```xml
         <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>SeleniumVersionYouNeed</version>
		</dependency>```

		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>AppiumVersionYouNeed</version>

			<exclusions>
				<exclusion>
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>selenium-java</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
?
There a lot of issues where descrided the same problem of Selenium version conflict.

**Comment by Jonahss** [comment]
Good idea @TikhomirovSergey
