### ISSUE TITLE
getSystemBars returns wrong height and width

### ISSUE THREAD

**Issue by kamal-kaur04** [appium/java-client#1719]
## Description

When calling getSystemBars() on Android 12, it returns `{statusBar={visible=true, x=0, y=0, width=null, height=1}, navigationBar={visible=true, x=0, y=0, width=null, height=1}}`

## Environment

* Java client build version or git revision if you use some snapshot:
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember: it's easier to reproduce and fix the bug with sample code.
You can git clone https://github.com/appium/appium/tree/master/sample-code or https://github.com/appium/appium/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by kamal-kaur04** [comment]
Thanks @mykola-mokhnach, Could you please let me know when are you planning to release a method getSystemBars() for C# as well?

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot answer this question as I don't participate in this client development. Try asking at their issues tracker
