### ISSUE TITLE
Code Styles not in sync

### ISSUE THREAD

**Issue by RameshBabuPrudhvi** [appium/java-client#1722]
## Description

Throughout the project Code Formatter is not in sync

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

The below class uses static imports in first place
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java

However in the below class ,static imports are used in last place
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/ExecuteCDPCommand.java

## Exception Stacktraces
N/A

## Link To Appium Logs
N/A

**Comment by bipin-k** [comment]
@mykola-mokhnach @SrinivasanTarget Shall we use [Google Java StyleGuide](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) for this?
