### ISSUE TITLE
8.1.1 - Could not start a new session

### ISSUE THREAD

**Issue by StephanB75** [appium/java-client#1723]
## Description

i have updated from 8.1.0 to 8.1.1 and i get the error "Could not start a new session"
Switched back to 8.1.0 and it works again.
Has something changed regarding the appiumServiceBuilder ?

## Environment

* Java client build version or git revision if you use some snapshot: 8.1.1
* Appium server version or git revision if you use some snapshot: 2.0beta40
* Desktop OS/version used to run Appium if necessary: MacOS Monterey
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 16
* Mobile platform/version under test: iOS / Android
* Real device or emulator/simulator: Emulator

## Code To Reproduce Issue [ Good To Have ]

**capabilities setup:**
XCUITestOptions options = new XCUITestOptions();
options.setDeviceName("iPhone 8 Plus");
options.setPlatformName("iOS");
options.setPlatformVersion(getPlatformVersion());
options.setApp(getAppPath());
options.setForceAppLaunch(false);
options.setAutomationName("XCUITest");
options.setNewCommandTimeout(Duration.ofSeconds(120));
options.setKeepKeyChains(false);
options.setUdid(getUdid());
options.setLanguage("de");
options.setLocale("de_DE");
options.setUseNewWDA(false);
options.setConnectHardwareKeyboard(false);
options.setProcessArguments(argsValue);
options.setWdaLaunchTimeout(Duration.ofSeconds(60));
options.setWdaLocalPort(getWdaLocalPort());
options.setWaitForIdleTimeout(Duration.ofSeconds(1));
options.setBundleId(getAppId());

**creating a server with the serviceBuilder**
builder = new AppiumServiceBuilder().withLogFile(new File("appium_.log")).withArgument(() -> "--allow-insecure", "adb_shell").withArgument(() -> "--use-plugins", "images");
        builder.withIPAddress("127.0.0.1");
		builder.usingPort(4726);
		builder.withCapabilities(options);

**creating driver with :**
driver = new IOSDriver(new URL("http://127.0.0.1:4726)), options);

## Link To Appium Logs
error snippet :
https://gist.github.com/StephanB75/f9992b599b91029d748c6d2462357720

Full log:
https://gist.github.com/StephanB75/0ef668d56e21118b3868e5158867235c

**Comment by Higgens75** [comment]
hmm 20 days and no one had an idea why its not working anymore ?

**Comment by StephanB75** [comment]
problem solved. had to update selenium bindings from 4.1.2 to 4.4.0 (latest)
Haven't seen this information in the release notes of java client 8.1.1
