### ISSUE TITLE
please move sendKeyEvent() back to AppiumDriver

### ISSUE THREAD

**Issue by luonglne** [appium/java-client#173]
First issue:  In your release note, https://discuss.appium.io/t/java-client-2-2-0-released/3359, you mentioned that "sendKeyEvent() moved from AppiumDriver to IOSDriver"; yet in your implementation, you moved it to AndroidDriver instead, based on this commit, https://github.com/appium/java-client/commit/54af0cc1739380d3822ee2f48095702078ce9930.

Second issue: I've been using sendKeyEvent() for my iOS devices and it is working fine.  May I request you to put it back to AppiumDriver?  Please help putting it back as soon as you can.  Thanks!

**Comment by Jonahss** [comment]
Okay, I've corrected the first issue, fixed the README.

**Comment by Jonahss** [comment]
And I don't see how sendKeyEvent() works on iOS, unless you're using an old version of appium.
https://github.com/appium/appium/blob/545372b782e1b580bc8d0ea5f04be8c1600f9f00/lib/devices/ios/ios-controller.js#L847-L849

**Comment by luonglne** [comment]
It was working on Appium1.3.4.  If it is removed, is there a different way to press "Enter" on the keyboard for iOS device?

**Comment by luonglne** [comment]
I found a workaround that works, but it is not a clean as calling sendKeyEvent().  If you know of other better way, please let me know.
---------      
public static final String KEYBOARD_SEARCH = "UIATarget.localTarget().frontMostApp().keyboard().buttons()['Search'].tap();";
JavascriptExecutor jse = (JavascriptExecutor) device();
jse.executeScript(KEYBOARD_SEARCH);
---------

**Comment by Jonahss** [comment]
Ooh interesting. Maybe we can add iOS keyboard search to the java-client.
