### ISSUE TITLE
Is io.appium.java_client.internal.ElementMap.getElementClass support removed from appium 8.1.1?

### ISSUE THREAD

**Issue by gargpriya01** [appium/java-client#1732]
### Discussed in https://github.com/appium/java-client/discussions/1731

<sup>Originally posted by **gargpriya01** August  3, 2022</sup>
I am unable to use ElementMap after upgrading to appium java client 8.1.1. 

Does anyone know why this is so or an alternate solution to this?</div>

**Comment by valfirst** [comment]
please check "Migration Guide": https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#mobileelement

**Comment by gargpriya01** [comment]
i am using below code with ElementMap import. But i am not able to understand how should I modify it in v8 migration ?
private WebElement proxyForAnElement(ElementLocator locator) {
    ElementInterceptor elementInterceptor = new ElementInterceptor(locator, webDriver);
    return getEnhancedProxy(getElementClass(platform, automation), elementInterceptor);
}

@valfirst  Can you help me understand this

**Comment by valfirst** [comment]
the provided code doesn't have any [`ElementMap`](https://github.com/appium/java-client/pull/1555/files#diff-381699abe8b08025b7f0daa63e8aa188320a04d51372060f1a914827198177c5) references

**Comment by sanoj-s** [comment]
@gargpriya01 you can use, 
private WebElement proxyForAnElement(ElementLocator locator) {
        ElementInterceptor elementInterceptor = new ElementInterceptor(locator, webDriver);
        return getEnhancedProxy(**RemoteWebElement**.class, elementInterceptor);
    }

**Comment by valfirst** [comment]
@gargpriya01 is the issue solved?
