### ISSUE TITLE
Type 'io.appium.java_client.AppiumDriver' does not have type parameters

### ISSUE THREAD

**Issue by gargpriya01** [appium/java-client#1733]
I am getting following error Type 'io.appium.java_client.AppiumDriver' does not have type parameters while upgrading from v7 to v8.

## Environment

* Java client build version or git revision if you use some snapshot: 8.1.1
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary: 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember: it's easier to reproduce and fix the bug with sample code.

private final List<AppiumDriver<WebElement>> pool = new CopyOnWriteArrayList<>();   //getting above listed error in this line
@Override
    public void releaseAppiumDriver() {
        if (MobileDriverStorage.getInstance() != null) {
            AppiumDriver<WebElement> driver = MobileDriverStorage.getInstance().getDriver();   //getting above listed error in this line
            String deviceId = getDriverUdid(driver);
            if (isSessionEnding(deviceId)) {
                log.info("Device's {} session came to end", deviceId);
                mobileCloudService.stopDevice(deviceId);
                driverSessionStartTime.remove(deviceId);
                takenDevices.remove(deviceId);
            } else pool.add(driver);
            logPoolContent();
            MobileDriverStorage.getInstance().clearStorage();
        }
    }

## Exception Stacktraces

Type 'io.appium.java_client.AppiumDriver' does not have type parameters

**Comment by valfirst** [comment]
That's expected, please check "Migration Guide": https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#appiumdriver

**Comment by valfirst** [comment]
@gargpriya01 is the issue solved?
