### ISSUE TITLE
Issue with App management methods in v8

### ISSUE THREAD

**Issue by gargpriya01** [appium/java-client#1734]
Getting below errors in each of the method shared below in Code section. I understand resetApp, launchApp and closeApp have been deprecated. But removeApp and ActivateApp are newly added and still i am getting error. Also, what i can use in place of launchApp and resetApp . What about isAppInstalled?
1. Cannot resolve method 'launchApp' in 'AppiumDriver'
2. Cannot resolve method 'isAppInstalled' in 'AppiumDriver'
3. Cannot resolve method 'removeApp' in 'AppiumDriver'
4. Cannot resolve method 'activateApp' in 'AppiumDriver'
5. Cannot resolve method 'resetApp' in 'AppiumDriver'

## Environment

* Java client build version or git revision if you use some snapshot:
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Migration of Appium Java client from v7 to v8

## Code To Reproduce Issue [ Good To Have ]
@Override
    public void getAppiumDriver() {
        AppiumDriver driver = null;
        synchronized (this) {
            if (!pool.isEmpty()) {
                driver = pool.get(0);
                pool.remove(driver);
                log.info("Take device {} from pool", getDriverUdid(driver));
            }
        }
        if (driver != null) {
            resetApp(driver);
        } else {
            driver = (AppiumDriver) driverService.createWebDriver(takeDevice());
            installApp(driver);
        }
        driver.launchApp();
        MobileDriverStorage.getInstance().setWebDriver(driver);
    }

private void installApp(AppiumDriver driver) {
        String bundleId = appiumCapabilitiesService.getBundleId();
        if (driver.isAppInstalled(bundleId)) {
            driver.removeApp(bundleId);
        }
        mobileCloudService.installArtifact(getDriverUdid(driver), artifact.getId());
        if (driverService.isIos()) {
            driver.activateApp(bundleId);
        }
    }

    private void resetApp(AppiumDriver driver) {
        if (driverService.isIos()) {
            installApp(driver);
        } else if (driverService.isAndroid()) {
            driver.resetApp();
        }
    }
}

## Exception Stacktraces

1. Cannot resolve method 'launchApp' in 'AppiumDriver'
2. Cannot resolve method 'isAppInstalled' in 'AppiumDriver'
3. Cannot resolve method 'removeApp' in 'AppiumDriver'
4. Cannot resolve method 'activateApp' in 'AppiumDriver'
5. Cannot resolve method 'resetApp' in 'AppiumDriver'

**Comment by valfirst** [comment]
Please, use `io.appium.java_client.ios.IOSDriver` or `io.appium.java_client.android.AndroidDriver` which implement `io.appium.java_client.InteractsWithApps` and `io.appium.java_client.SupportsLegacyAppManagement`

**Comment by valfirst** [comment]
@gargpriya01 is the issue solved?
