### ISSUE TITLE
Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null

### ISSUE THREAD

**Issue by Pewliedie** [appium/java-client#1742]
Trying to integrate spring boot with appium and getting this strange behavior:
Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null

[pom.xml
](https://gist.github.com/Pewliedie/1cda5bcb8f2e7467f243ca05e737282c)

initialization of tests and appium [driver](https://gist.github.com/Pewliedie/dfda4a0e93ffd90ac9fcfaee6085474e)

![Screen Shot 2022-08-16 at 15 59 03](https://user-images.githubusercontent.com/56083057/184873812-061318e5-006b-4025-8574-31fb84faf34f.png)

Driver is created but if try to interact with selenium WebElement this exception **java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null** is thrown 

## Exception Stacktraces

[stacktrace](https://gist.github.com/Pewliedie/3ac2f0a37cf384f0de83dbcdbc564f75)

**Comment by valfirst** [comment]
Could you please provide [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/)?

**Comment by Rafayal383** [comment]
if it is resolved help me also please

**Comment by Shrutip2898** [comment]
I am facing same issue
