### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by avukovicnapoleongames** [appium/java-client#1769]
This is what I have istalled:
node version 10.16.1
appium 1.20.2
npm 6.14.11
maven 3.8.5 
I have isnstalled opnecv
npm i -g opencv-build
npm i -g opencv4nodejs
cucumber 7.0.0
java 17.0.2

What I want actually is to run image recognition, but I can't run this project with command mvn clean test I have an error

java.lang.IllegalStateException: The driver executable is a directory: /opt/homebrew/bin/node

Thank you in advance

**Comment by jlipps** [comment]
for what it's worth we only support image recognition through  the appium 2 images plugin, which no longer uses opencv4nodejs. not sure if that is related to your particular error, but just to say that you will want to upgrade to appium 2 and the images plugin anyway.

**Comment by teovuk** [comment]
> for what it's worth we only support image recognition through the appium 2 images plugin, which no longer uses opencv4nodejs. not sure if that is related to your particular error, but just to say that you will want to upgrade to appium 2 and the images plugin anyway.

Can you tell me which libraries and image plugin to use? Or, even better to give me the link of instruction of installation?

**Comment by StephanB75** [comment]
I think Jlipps ment to use appium 2 instead appium 1.x.
https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md

Than the image recognition can be simply used by installing the appium plugin "images" (appium plugin install images) without fiddeling around with opencv installation/compiling

**Comment by jlipps** [comment]
yep, and the image plugin itself has a readme: https://github.com/appium/appium/tree/master/packages/images-plugin
