### ISSUE TITLE
UnknownCommandException When run the mobile test

### ISSUE THREAD

**Issue by drrodriguez-ASD** [appium/java-client#1778]
## Description

Hello everyvody, I´m running my test on android device emulator from android studio, the connect to device and open the app but before the interact with the first botom the app close and get the next error in he appium console, i hope can yoy help me

## Environment

* Java client build version or git revision if you use some snapshot: Java 1.8
* Appium server version or git revision if you use some snapshot: Latest
* Desktop OS/version used to run Appium if necessary: Windows 10
* Mobile platform/version under test: Android 13

## Details

Hello everyvody, I´m running my test on android device emulator from android studio, the connect to device and open the app but before the interact with the first botom the app close and get the next error in he appium console, i hope can yoy help me

## Link To Appium Logs

![image](https://user-images.githubusercontent.com/113544106/196756179-f7fc0aa6-cd73-47fe-919d-3426fc920a83.png)
![image](https://user-images.githubusercontent.com/113544106/196756220-3c055282-4af9-427f-88c0-7286a502385e.png)

**Comment by KazuCocoa** [comment]
Could you share the full appium log as GitHub GIST?

**Comment by drrodriguez-ASD** [comment]
Of Course
[https://gist.github.com/drrodriguez-ASD/d46218c1046409c14405f82b8e0f0f57](url)

**Comment by KazuCocoa** [comment]
Thanks. The getting window handler works only for WebView since no switching windows in the native app context. Did your test code call the endpoint?
