### ISSUE TITLE
Reseaching & Enhancement: The returning of the list which contains something that extends WebElement/Generic AppiumDriver

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#178]
Hi!
It seems that I have found the solution of the problem that hasn't been resolsed at #167
The draft looks like that 

![](https://cloud.githubusercontent.com/assets/4927589/6834432/3266315a-d345-11e4-9a55-634a6acdfe39.png)

I have mage up the FireFoxDriver generic subclass and some more (still secret ;) ). 
So there are things that need for the reseaching:
- backward compatibility
- usability

@Jonahss @bootstraponline 
What do you think about generic AppiumDriver?

**Comment by TikhomirovSergey** [comment]
#162

**Comment by Jonahss** [comment]
Don't understand how you're doing it, but looks fine by me ^.^ Awesome.

What are the drawbacks?

**Comment by TikhomirovSergey** [comment]
>What are the drawbacks?

I am seeing only one for now... It is possible that warnings (rawtypes for example) can appear. But code should work anyway. And this issue is easy to fix. It is about backward compatibility.
