### ISSUE TITLE
What methods can I call the ime now？

### ISSUE THREAD

**Issue by wat4me** [appium/java-client#1781]
I upgraded java-client to 8.1.1
manage().ime().activateEngine(defaultIme) disappeared
I found this answer
https://github.com/appium/appium/issues/16939
my English is poor,i can't understand which endpoint in Java client?
so,how can i get this method in java-client?
thanks

**Comment by mykola-mokhnach** [comment]
You could use https://github.com/appium/appium-uiautomator2-driver#mobile-shell for this purpose: https://android.stackexchange.com/questions/47948/how-to-change-input-method-with-ime-command
