### ISSUE TITLE
 Encountered internal error running command: Error: Cannot verify the signature of 'C:\\\\\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v5.7.0.apk'. Original error: java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by joylan2105** [appium/java-client#1786]
## Description

Environment
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
Appium version: 2.0.0-beta.35

Below are the appium logs:

Microsoft Windows [Version 10.0.22000.1098]
(c) Microsoft Corporation. All rights reserved.

C:\Users\mesin>appium -p 4724
[Appium] Welcome to Appium v2.0.0-beta.35
[Appium] Non-default server args:
[Appium] {
[Appium]   port: 4724
[Appium] }
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at C:\Users\mesin\.appium\node_modules\appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4724
[Appium] Available drivers:
[Appium]   - xcuitest@4.12.1 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.9.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"11","appium:deviceName":"Joylan","appium:app":"C:\\Users\\mesin\\Desktop\\Mobile Automation\\sampleTraining\\app\\android\\ApiDemos-debug.apk","appium:automationName":"UIAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"11","appium:deviceName":"Joylan","appium:app":"C:\\Users\\mesin\\Desktop\\Mobile Automation\\sampleTraining\\app\\android\\ApiDemos-debug.apk","appium:automationName":"UIAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[debug] [AppiumDriver@3dc6] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"11","appium:deviceName":"Joylan","appium:app":"C:\\Users\\mesin\\Desktop\\Mobile Automation\\sampleTraining\\app\\android\\ApiDemos-debug.apk","appium:automationName":"UIAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"11","appium:deviceName":"Joylan","appium:app":"C:\\Users\\mesin\\Desktop\\Mobile Automation\\sampleTraining\\app\\android\\ApiDemos-debug.apk","appium:automationName":"UIAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [AppiumDriver@3dc6] Event 'newSessionRequested' logged at 1666945857180 (16:30:57 GMT+0800 (Philippine Standard Time))
[Appium] Attempting to find matching driver for automationName 'UIAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver
[debug] [Appium] Requiring driver at C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver
[AppiumDriver@3dc6] Appium v2.0.0-beta.35 creating new AndroidUiautomator2Driver (v2.9.0) session
[AppiumDriver@3dc6] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@3dc6] Appium's BaseDriver version is 8.7.3
[AppiumDriver@3dc6] AndroidUiautomator2Driver's BaseDriver version is 8.7.3
[debug] [AndroidUiautomator2Driver@0ca7] Creating session with W3C capabilities: {
[debug] [AndroidUiautomator2Driver@0ca7]   "alwaysMatch": {
[debug] [AndroidUiautomator2Driver@0ca7]     "platformName": "Android",
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:platformVersion": "11",
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:deviceName": "Joylan",
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:app": "C:\\Users\\mesin\\Desktop\\Mobile Automation\\sampleTraining\\app\\android\\ApiDemos-debug.apk",
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:automationName": "UIAutomator2",
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:ensureWebviewsHavePages": true,
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:nativeWebScreenshot": true,
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:newCommandTimeout": 3600,
[debug] [AndroidUiautomator2Driver@0ca7]     "appium:connectHardwareKeyboard": true
[debug] [AndroidUiautomator2Driver@0ca7]   },
[debug] [AndroidUiautomator2Driver@0ca7]   "firstMatch": [
[debug] [AndroidUiautomator2Driver@0ca7]     {}
[debug] [AndroidUiautomator2Driver@0ca7]   ]
[debug] [AndroidUiautomator2Driver@0ca7] }
[AndroidUiautomator2Driver@0ca7] The following capabilities were provided, but are not recognized by Appium:
[AndroidUiautomator2Driver@0ca7]   connectHardwareKeyboard
[AndroidUiautomator2Driver@0ca7 (397afa5f)] Session created with session id: 397afa5f-0799-48f1-bc4d-1a093b30e7b9
[BaseDriver] Using local app 'C:\Users\mesin\Desktop\Mobile Automation\sampleTraining\app\android\ApiDemos-debug.apk'
[debug] [AndroidUiautomator2Driver@0ca7 (397afa5f)] Checking whether app is actually present
[ADB] Found 2 'build-tools' folders under 'C:\Users\mesin\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/mesin/AppData/Local/Android/Sdk/build-tools/33.0.0
[ADB]     C:/Users/mesin/AppData/Local/Android/Sdk/build-tools/30.0.2
[ADB] Using 'adb.exe' from 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Looking for a device with Android '11.0.0'
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 11
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 30
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 11
[debug] [ADB] Device API level: 30
[AndroidUiautomator2Driver@0ca7 (397afa5f)] Relaxing hidden api policy
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Package name: 'io.appium.android.apis'
[ADB] Main activity name: 'io.appium.android.apis.ApiDemos'
[debug] [AndroidDriver] Parsed package and activity are: io.appium.android.apis/io.appium.android.apis.ApiDemos
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('4.2.1' >= '4.2.1')
[debug] [ADB] There is no need to install/upgrade 'C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [Logcat] Starting logs capture with command: C:\\Users\\mesin\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 logcat -v threadtime
[debug] [AndroidUiautomator2Driver@0ca7 (397afa5f)] Forwarding UiAutomator2 Server port 6790 to local port 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp:8200 tcp:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The installed 'io.appium.uiautomator2.server' package is older than 'C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v5.7.0.apk' (84 < 110 or '2.0.0' < '5.7.0')'
[debug] [AndroidUiautomator2Driver@0ca7 (397afa5f)] io.appium.uiautomator2.server installation state: olderVersionInstalled
[debug] [ADB] Checking app cert for C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v5.7.0.apk
[ADB] Using 'apksigner.jar' from 'C:\Users\mesin\AppData\Local\Android\Sdk\build-tools\33.0.0\lib\apksigner.jar'
[debug] [ADB] Starting apksigner: 'C:\\Program Files (x86)\\Java\\jdk1.7.0_60\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\mesin\\AppData\\Local\\Android\\Sdk\\build-tools\\33.0.0\\lib\\apksigner.jar verify --print-certs C:\\Users\\mesin\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v5.7.0.apk
[debug] [AndroidUiautomator2Driver@0ca7 (397afa5f)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@0ca7 (397afa5f)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@0ca7 (397afa5f)] Matched '/' to command name 'deleteSession'
[AndroidUiautomator2Driver@0ca7 (397afa5f)] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.android.apis'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:8200'
[AndroidUiautomator2Driver@0ca7 (397afa5f)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running 'C:\Users\mesin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [AppiumDriver@3dc6] Event 'newSessionStarted' logged at 1666945858666 (16:30:58 GMT+0800 (Philippine Standard Time))
[debug] [AppiumDriver@3dc6] Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v5.7.0.apk'. Original error: java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool : Unsupported major.minor version 52.0
[debug] [AppiumDriver@3dc6]     at java.lang.ClassLoader.defineClass1(Native Method)
[debug] [AppiumDriver@3dc6]     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[debug] [AppiumDriver@3dc6]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[debug] [AppiumDriver@3dc6]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[debug] [AppiumDriver@3dc6]     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[debug] [AppiumDriver@3dc6]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[debug] [AppiumDriver@3dc6]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[debug] [AppiumDriver@3dc6]     at java.security.AccessController.doPrivileged(Native Method)
[debug] [AppiumDriver@3dc6]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[debug] [AppiumDriver@3dc6]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[debug] [AppiumDriver@3dc6]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[debug] [AppiumDriver@3dc6]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[debug] [AppiumDriver@3dc6]     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[debug] [AppiumDriver@3dc6] Exception in thread "main"
[debug] [AppiumDriver@3dc6]     at ADB.checkApkCert (C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\apk-signing.js:305:11)
[debug] [AppiumDriver@3dc6]     at UiAutomator2Server.installServerApk (C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:119:13)
[debug] [AppiumDriver@3dc6]     at AndroidUiautomator2Driver.initUiAutomator2Server (C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:505:7)
[debug] [AppiumDriver@3dc6]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:400:5)
[debug] [AppiumDriver@3dc6]     at AndroidUiautomator2Driver.createSession (C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:239:7)
[debug] [AppiumDriver@3dc6]     at AppiumDriver.createSession (C:\Users\mesin\AppData\Roaming\npm\node_modules\appium\lib\appium.js:298:35)
[HTTP] <-- POST /session 500 1542 ms - 3009
[HTTP]

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Starting apksigner: 'C:\Program Files (x86)\Java\jdk1.7.0_60\bin\java.exe' -Xmx1024M -Xss1m -jar C:\Users\mesin\AppData\Local\Android\Sdk\build-tools\33.0.0\lib\apksigner.jar verify --print-certs C:\Users\mesin\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v5.7.0.apk

It looks like a very old java still sits somewhere in PATH

**Comment by joylan2105** [comment]
Yes @mykola-mokhnach you are right. I was able to solve the issue by deleting the old java.
