### ISSUE TITLE
bug: iOSXCUITestFindBy is not working properly for xpath or iosClassChain

### ISSUE THREAD

**Issue by aarahmanqa** [appium/java-client#1799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to find the Search Box in the iOS Settings app. This is my locator:
` @iOSXCUITFindBy(iOSClassChain = "**/XCUIElementTypeSearchField[$name ==[C] 'Search'$]")`
`private WebElement weSearchText;`

The same is working fine with AppiumBy variable.

This is my appium instantiation from log:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/6194278/201655600-98a34886-4a90-44c5-bf8c-ab1b8e416499.png">

When I execute that line, I got this in log:
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/6194278/201655485-9c6206ed-a2c6-4bcc-915f-e28ff48a4718.png">

As you can see, it seems that the logs are sending my element name as iosClassChain instead of my locator:
`{"using":"class chain","value":"**/*[`name == \"weSearchTextBox\"`]"}`

What am I doing wrong here?

I tried @FindBy similarly for Xpath and that worked fine.

### Expected Behavior

The element should ideally get identified properly.

### Minimal Reproducible Example

<pre>
package com.tekioncloud.core.main.mobile.pages;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.pagefactory.iOSXCUITFindBy;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.PageFactory;

import java.net.MalformedURLException;
import java.net.URL;

public class MobileSettingsAppTest {

    @iOSXCUITFindBy(iOSClassChain = "**/XCUIElementTypeCell[`label ==[C] 'General'`]")
    private WebElement weGeneral;

    private By byGeneral = AppiumBy.iOSClassChain("**/XCUIElementTypeCell[`label ==[C] 'General'`]");

    public static void main(String[] args) {
        try {
            DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
            desiredCapabilities.setCapability("platformName", "iOS");
            desiredCapabilities.setCapability("appium:automationName", "XCUITest");
            desiredCapabilities.setCapability("appium:bundleId", "com.apple.Preferences");
            desiredCapabilities.setCapability("appium:deviceName", "iPhone XR");
            desiredCapabilities.setCapability("appium:newCommandTimeout", "0");
            desiredCapabilities.setCapability("appium:platformVersion", "12.1");
            desiredCapabilities.setCapability("appium:udid", "00008020-001B044C0193802E");
            desiredCapabilities.setCapability("appium:waitForQuiescence", false);
            desiredCapabilities.setCapability("appium:wdaLocalPort", "8100");

            IOSDriver iDriver = new IOSDriver(new URL("http://0.0.0.0:4723"), desiredCapabilities);
            iDriver.setSetting("useFirstMatch", true);

            MobileSettingsAppTest mobileSettingsAppTest = new MobileSettingsAppTest();
            PageFactory.initElements(iDriver,mobileSettingsAppTest);
            mobileSettingsAppTest.weGeneral.click();
//            iDriver.findElement(mobileSettingsAppTest.byGeneral).click();
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }
}

</pre>

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.44
  - Node.js version (output of `node --version`): v18.7.0
  - `npm` version (output of `npm --version`): 8.18.0
  - Last `appium` version which did _not_ exhibit the problem: Didn't try this previously
- If running Appium Desktop, its version: NA
- Appium driver(s) and their version(s): xcuitest@4.11.1
- Appium plugin(s) and their version(s): NA
- Platform and version under test: iOS 16.1.1
- Real device or emulator/simulator: iPhone XR real device

**Comment by mykola-mokhnach** [comment]
It looks like java client lib unexpectedly changes the locator to CSS type? Are you sure the most recent version of it is used?

**Comment by mykola-mokhnach** [comment]
also please provide the full server log as gist

**Comment by aarahmanqa** [comment]
@mykola-mokhnach , Please see this link for [Gist](https://gist.github.com/aarahmanqa/99b4e1e738bf2e0b4121296a64052fcd) of Appium Logs.

**Comment by mykola-mokhnach** [comment]
Unfortunately the java client version is not stated above.

**Comment by aarahmanqa** [comment]
@mykola-mokhnach 
Please look at my gradle libraries:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/6194278/201693305-b59305cb-27a3-44a7-a810-96fe39442f88.png">
Any other better way to confirm it?

**Comment by mykola-mokhnach** [comment]
In the log I don't observe any issues:

```
[HTTP] --> POST /session/23f096da-cabb-449d-93d8-e22764332a9b/element
[HTTP] {"using":"-ios class chain","value":"**/XCUIElementTypeCell[`label ==[C] 'General'`]"}
[debug] [XCUITestDriver@5844 (23f096da)] Calling AppiumDriver.findElement() with args: ["-ios class chain","**/XCUIElementTypeCell[`label ==[C] 'General'`]","23f096da-cabb-449d-93d8-e22764332a9b"]
[debug] [XCUITestDriver@5844 (23f096da)] Executing command 'findElement'
[debug] [XCUITestDriver@5844 (23f096da)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [XCUITestDriver@5844 (23f096da)] Waiting up to 0 ms for condition
[debug] [XCUITestDriver@5844 (23f096da)] Matched '/element' to command name 'findElement'
[debug] [XCUITestDriver@5844 (23f096da)] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/4AB22159-4EBC-49B8-A208-30F76A759CA2/element] with body: {"using":"class chain","value":"**/XCUIElementTypeCell[`label ==[C] 'General'`]"}
[debug] [XCUITestDriver@5844 (23f096da)] Got response with status 200: {"value":{"ELEMENT":"1B000000-0000-0000-4B12-000000000000","element-6066-11e4-a52e-4f735466cecf":"1B000000-0000-0000-4B12-000000000000"},"sessionId":"4AB22159-4EBC-49B8-A208-30F76A759CA2"}
[debug] [XCUITestDriver@5844 (23f096da)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"1B000000-0000-0000-4B12-000000000000","ELEMENT":"1B000000-0000-0000-4B12-000000000000"}
[HTTP] <-- POST /session/23f096da-cabb-449d-93d8-e22764332a9b/element 200 971 ms - 137
```

Could you please mention where exactly the issue happens (the log line number)?

**Comment by mykola-mokhnach** [comment]
An important details is missing:

in

```
PageFactory.initElements(iDriver,mobileSettingsAppTest);
```

the first argument must be decorated like below:

```
PageFactory.initElements(new AppiumFieldDecorator(iDriver), mobileSettingsAppTest);
```

**Comment by aarahmanqa** [comment]
Yeah, its working now.
Thanks @mykola-mokhnach.
