### ISSUE TITLE
Is this flag still working with Appium 2

### ISSUE THREAD

**Issue by bb-cn-himanshu** [appium/java-client#1821]
While doing Appium migration, I started getting error while trying to start **Appium Service**

```
AppiumServiceBuilder builder =
                    new AppiumServiceBuilder()
                            .withArgument(GeneralServerFlag.LOG_LEVEL, "error")
                            .withTimeout(Duration.ofSeconds(10))
                            .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER,
                                    Integer.toString(availablePorts[0]))
                            .withArgument(GeneralServerFlag.RELAXED_SECURITY)
                            .withIPAddress(serverIP)
                            .withLogFile(logFile)
                            .withArgument(AndroidServerFlag.SUPPRESS_ADB_KILL_SERVER)
                            .withArgument(GeneralServerFlag.ALLOW_INSECURE, "chromedriver_autodownload")
                            .usingPort(availablePorts[1]);
service = builder.build();
service.start();
```

but getting error saying: Unrecognized arguments: --bootstrap-port 50358 --suppress-adb-kill-server

Below is the log for local execution 
```
appium --port 50359 --address 127.0.0.1 --allow-insecure chromedriver_autodownload --bootstrap-port 50358 --suppress-adb-kill-server --relaxed-security --log-level debug

[ERROR] Unrecognized arguments: --bootstrap-port 50358 --suppress-adb-kill-server
```
My Appium version is: `Appium v2.0.0-beta.47 (REV 001bacee18c512657e1535dff757c8cfdaefc116)`

Is the mentioned flag still useful? if not what is it replaced with?
https://github.com/appium/java-client/blob/318aa4025b2da700bb3c640200bf81be45428577/src/main/java/io/appium/java_client/service/local/flags/AndroidServerFlag.java#L32

**Comment by bb-cn-himanshu** [comment]
Here is reference comment from [jlipps](https://github.com/jlipps) related to above flag
https://github.com/appium/appium/pull/15211#issuecomment-807165368

**Comment by valfirst** [comment]
The details are available in the comment: https://github.com/appium/appium/pull/15211#issuecomment-1352401898
