### ISSUE TITLE
Issue to migration v8

### ISSUE THREAD

**Issue by pjcau** [appium/java-client#1836]
## Description

Hi Guys, 
I'm migrating the our app from v7 to v8:
So I need to use the 
  ` val sessionDetails = driver?.sessionDetails`

to retrieve the "viewportRect", "deviceName" and "deviceScreenSize". 

So I can use to retrieve this data?

## Environment

* Java client build version or git revision if you use some snapshot: 11.0
* Appium server version or git revision if you use some snapshot: 8.3.0
* Desktop OS/version used to run Appium if necessary: ios 16
* Node.js version : 19.2.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator

**Comment by valfirst** [comment]
@pjcau please see https://github.com/appium/java-client/issues/1689#issuecomment-1105825847
