### ISSUE TITLE
how to cast MobileElement to IOSElement

### ISSUE THREAD

**Issue by aznime** [appium/java-client#185]
Recently updated to latest 2.2.0 but this piece of code fails due to setValue() being moved to IOSElement.
```
        if (driver instanceof IOSDriver) {
            element.setValue(value)   // element is of MobileElement
        } else if (driver instanceof AndroidDriver) {
            element.sendKeys(value)
        }
```
Any ideas on how I can get it to work with the latest java-client? 

Thanks in advance.

**Comment by TikhomirovSergey** [comment]
Hi @aznime !

```java
       if (driver instanceof IOSDriver) {
          //(!!!)-->//  ((IOSElement) element).setValue(value)   // element is of MobileElement
        } else if (driver instanceof AndroidDriver) {
            element.sendKeys(value)
        }
```

Also I can advice you this combination of actions:

```java
       element.clear();
       element.sendKeys(value)
```
It should work against both Android and iOS.

**Comment by aznime** [comment]
Thanks. I tried to cast it like that but got an exception. Would be nice to use setValue() for IOS as it is much faster than sendKeys() though

**Comment by Jonahss** [comment]
What is the exception you got?

**Comment by aznime** [comment]
Below is the exception:

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[[IOSDriver: iOS on MAC (f8d4539c-2845-4aa8-b4c1-d02f474e399c)] -> accessibility id: Register:FormField:Email:TextField]' with class 'io.appium.java_client.MobileElement$$EnhancerByCGLIB$$f164cb9c' to class 'io.appium.java_client.ios.IOSElement'

**Comment by TikhomirovSergey** [comment]
Now it is clear. You are using PageFactory and it is a proxy of an element.
I can consider it as a bug and I know how to fix it.

**Comment by aznime** [comment]
Thank you!

**Comment by TikhomirovSergey** [comment]
@aznime Hi. It has been fixed. Please look above. Thanks for the bug report :) It is suposed to be included in the next release.
