### ISSUE TITLE
Cannot determine Simulator UDID to record the video

### ISSUE THREAD

**Issue by jacksonwen001** [appium/java-client#1887]
## Description
Below is my code. I wanna use appium to automate the safari in Mac pro. But I got the error: 
```
An unknown server-side error occurred while processing the command. Original error: Cannot determine Simulator UDID to record the video from. Double check your session capabilities
```

Do I miss any configurations?  By the way the documents for appium shows 404 not found now
![image](https://user-images.githubusercontent.com/95412295/232681800-12b49a20-cbce-40dc-bb59-63511dcc0b69.png)
 

Here is my code: 
```
@Test void test3() throws MalformedURLException {
        SafariOptions options = new SafariOptions();
        options.setCapability("platformName", "Mac");
        options.setCapability("automationName", "Safari");
        options.setCapability("browserName", "Safari");
        options.setCapability("deviceName", "Mac");
        options.setCapability(SupportsUdidOption.UDID_OPTION, "auto");
        options.setCapability(CapabilityType.BROWSER_VERSION, "16.0");

        SafariDriver driver = new SafariDriver(
                // The default URL in Appium 1 is http://127.0.0.1:4723/wd/hub
                new URL("http://127.0.0.1:4723"), options
        );

        driver.execute(START_RECORDING_SCREEN);
        try {
            driver.get("https://www.google.com");
            driver.getPageSource();
        } finally {
            driver.quit();
        }
    }
```

## Environment

* Java client build version or git revision if you use some snapshot:
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember: it's easier to reproduce and fix the bug with sample code.
You can git clone https://github.com/appium/appium/tree/master/sample-code or https://github.com/appium/appium/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by mykola-mokhnach** [comment]
>         options.setCapability(SupportsUdidOption.UDID_OPTION, "auto");

Where it is documented that such udid is supported by safari driver?
