### ISSUE TITLE
Cannot find an element using id starting with _

### ISSUE THREAD

**Issue by wazzeps** [appium/java-client#1899]
## Description

Cannot find an element using id starting with _.

## Environment

* Java client 8.3.0
* Appium server 2.0.0-beta.65
* Driver uiautomator2@2.22.1
* Inspector 2023.4.2
* Ubuntu 20.04
* Emulator

## Details

android.view.View
resource-id = __next

The element cannot be found using id locator
@AndroidFindBy(id = "__next")

but found successfully using xPath
@AndroidFindBy(xpath = "//android.view.View[@resource-id='__next']")

## Link To Appium Logs

[HTTP] --> POST /session/578aa3ae-117c-4d4a-9598-f67b15bfb592/elements
[HTTP] {"using":"id","value":"__next"}
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Calling AppiumDriver.findElements() with args: ["id","__next","578aa3ae-117c-4d4a-9598-f67b15bfb592"]
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Waiting up to 0 ms for condition
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Matched '/elements' to command name 'findElements'
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Proxying [POST /elements] to [POST http://127.0.0.1:8200/session/cf333c96-f0ce-495f-b4c6-2e841db67b69/elements] with body: {"strategy":"id","selector":"__next","context":"","multiple":true}
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Got response with status 200: {"sessionId":"cf333c96-f0ce-495f-b4c6-2e841db67b69","value":[]}
[debug] [AndroidUiautomator2Driver@d7d3 (578aa3ae)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /session/578aa3ae-117c-4d4a-9598-f67b15bfb592/elements 200 44 ms - 12

**Comment by mykola-mokhnach** [comment]
Try to enable `disableIdLocatorAutocompletion` [setting](https://github.com/appium/appium-uiautomator2-driver#settings-api)

**Comment by wazzeps** [comment]
That works.

So appium adds the prefix even to elements that are part of the webview.

    <android.webkit.WebView>
        <android.webkit.WebView>
            <android.view.View>
                <android.view.View resource-id="__next">

**Comment by mykola-mokhnach** [comment]
The prefix is always added. This behaviour was there from the very beginning.
