### ISSUE TITLE
IOS hideKeyboard()

### ISSUE THREAD

**Issue by nijakanthan** [appium/java-client#191]
In IOS simulator driver.hideKeyboard() method is not working.

**Comment by nijakanthan** [comment]
Appium Error message

info: --> POST /wd/hub/session/8db90672-457b-4981-94d7-4a88d4479a6b/appium/device/hide_keyboard {}

info: [debug] Pushing command to appium work queue: "au.hideKeyboard('default')"
info: [debug] Sending command to instruments: au.hideKeyboard('default')

info: [debug] [INST] 2015-04-28 16:48:23 +0000 Debug: Got new command 21 from instruments: au.hideKeyboard('default')
info: [debug] [INST] 2015-04-28 16:48:23 +0000 Debug: evaluating au.hideKeyboard('default')

info: [debug] [INST] 2015-04-28 16:48:23 +0000 Debug: target.frontMostApp().mainWindow().tapWithOptions({})

info: [debug] Socket data received (50 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Failed to hide keyboard."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Failed to hide keyboard."},"sessionId":"8db90672-457b-4981-94d7-4a88d4479a6b"}
info: <-- POST /wd/hub/session/8db90672-457b-4981-94d7-4a88d4479a6b/appium/device/hide_keyboard 500 17601.297 ms - 185

**Comment by imurchie** [comment]
Have you tried the non-default hide keyboard strategy?

https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/DeviceActionShortcuts.java
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/remote/HideKeyboardStrategy.java

**Comment by nijakanthan** [comment]
You mean driver.hideKeyboard(HideKeyboardStrategy, keyName) this method.

How can we specify the HideKeyboardStrategy isn't specific for different applications.
How to get the HideKeyboardStrategy of the appliction.

**Comment by SrinivasanTarget** [comment]
Latest Gist: https://gist.github.com/SrinivasanTarget/f3c5e7118e0dbcaa355808f41bc359f4

**Comment by SrinivasanTarget** [comment]
Alternatives suggested above by @imurchie works fine.
