### ISSUE TITLE
tried to access method org.openqa.selenium.remote.http.ClientConfig.<init>(Ljava/net/URI;Ljava/time/Duration;Ljava/time/Duration;Lorg/openqa/selenium/remote/http/Filter;Ljava/net/Proxy;Lorg/openqa/selenium/Credentials;)V from class io.appium.java_client.AppiumClientConfig

### ISSUE THREAD

**Issue by jynine** [appium/java-client#1914]
## Description

tried to access method org.openqa.selenium.remote.http.ClientConfig.<init>(Ljava/net/URI;Ljava/time/Duration;Ljava/time/Duration;Lorg/openqa/selenium/remote/http/Filter;Ljava/net/Proxy;Lorg/openqa/selenium/Credentials;)V from class io.appium.java_client.AppiumClientConfig

## Environment
pom:
 `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.6</version>
        <relativePath/> 
    </parent>
    <groupId>com.jynine</groupId>
    <artifactId>appSpider</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>1.8</java.version>
        <logback.version>1.2.7</logback.version>
        <commons-lang3.version>3.12.0</commons-lang3.version>
        <fastjson2.version>2.0.26</fastjson2.version>
        <java-client.version>8.3.0</java-client.version>
        <lombok.version>1.18.26</lombok.version>
    </properties>
    <dependencies>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-access</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>${fastjson2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>${java-client.version}</version>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                
                <directory>src/main/resources</directory> 
                
                <includes>
                    <include>**/*.xml</include>
                </includes>
            </resource>
            <resource>
                
                <directory>src/main/resources</directory> 
                
                <filtering>true</filtering>
                <includes>
                    <include>application.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                
                <configuration>
                    <layout>ZIP</layout>
                    <includes>
                        <include>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                        </include>
                    </includes>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.2</version>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>

            
            
        </plugins>
    </build>
</project>`

java:
`package com.jynine;

import io.appium.java_client.android.AndroidDriver;
import lombok.extern.slf4j.Slf4j;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

/**
 * @author 32825
 */
@Slf4j
public class CalculatorTest {
    public static void main(String[] args) throws MalformedURLException, InterruptedException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "NAB0220804052056");
        capabilities.setCapability("automationName", "Appium");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "12");
        capabilities.setCapability("appPackage", "com.ss.android.ugc.aweme");
        capabilities.setCapability("appActivity", "com.ss.android.ugc.aweme.splash.SplashActivity");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability("skipServerInstallation",true);
        capabilities.setCapability("unicodeKeyboard", true);
        capabilities.setCapability("resetKeyboard", true);
        capabilities.setCapability("waitForIdleTimeout",100); 
        capabilities.setCapability("waitForSelectorTimeout",100); 
        capabilities.setCapability("disableAndroidWatchers", true);
        AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        Thread.sleep(3000); 
        List webElements = driver.findElements(By.id("com.ss.android.ugc.aweme:id/szh"));
        ((WebElement)webElements.get(3)).click();
        Thread.sleep(2000);
        String ne6 = driver.findElement(By.id("com.ss.android.ugc.aweme:id/ne6")).getText();

        driver.findElement(By.id("com.ss.android.ugc.aweme:id/wlr")).click();
        Thread.sleep(1000); 
       driver.quit();
    }
 
}`
## Details
 `"C:\Program Files\Java\jdk1.8.0_251\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.2\lib\idea_rt.jar=54511:C:\Program Files\JetBrains\IntelliJ IDEA 2019.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_251\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\swxajce.jar;C:\Program Files\Java\jdk1.8.0_251\jre\lib\ext\swxacrypt.jar;D:\studio\testdemoworkspace\appSpider2\target\classes;D:\maven\repository\ch\qos\logback\logback-access\1.2.7\logback-access-1.2.7.jar;D:\maven\repository\ch\qos\logback\logback-core\1.2.7\logback-core-1.2.7.jar;D:\maven\repository\ch\qos\logback\logback-classic\1.2.7\logback-classic-1.2.7.jar;D:\maven\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\maven\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;D:\maven\repository\com\alibaba\fastjson2\fastjson2\2.0.26\fastjson2-2.0.26.jar;D:\maven\repository\org\projectlombok\lombok\1.18.26\lombok-1.18.26.jar;D:\maven\repository\io\appium\java-client\8.3.0\java-client-8.3.0.jar;D:\maven\repository\org\seleniumhq\selenium\selenium-api\4.1.4\selenium-api-4.1.4.jar;D:\maven\repository\org\seleniumhq\selenium\selenium-remote-driver\4.1.4\selenium-remote-driver-4.1.4.jar;D:\maven\repository\com\beust\jcommander\1.82\jcommander-1.82.jar;D:\maven\repository\com\google\auto\service\auto-service-annotations\1.0.1\auto-service-annotations-1.0.1.jar;D:\maven\repository\com\google\auto\service\auto-service\1.0.1\auto-service-1.0.1.jar;D:\maven\repository\com\google\auto\auto-common\1.2\auto-common-1.2.jar;D:\maven\repository\com\google\guava\guava\31.1-jre\guava-31.1-jre.jar;D:\maven\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;D:\maven\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;D:\maven\repository\org\checkerframework\checker-qual\3.12.0\checker-qual-3.12.0.jar;D:\maven\repository\com\google\errorprone\error_prone_annotations\2.11.0\error_prone_annotations-2.11.0.jar;D:\maven\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;D:\maven\repository\io\netty\netty-buffer\4.1.85.Final\netty-buffer-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-codec-http\4.1.85.Final\netty-codec-http-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-codec\4.1.85.Final\netty-codec-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-handler\4.1.85.Final\netty-handler-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-common\4.1.85.Final\netty-common-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport-classes-epoll\4.1.85.Final\netty-transport-classes-epoll-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport-classes-kqueue\4.1.85.Final\netty-transport-classes-kqueue-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport-native-epoll\4.1.85.Final\netty-transport-native-epoll-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport-native-kqueue\4.1.85.Final\netty-transport-native-kqueue-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport-native-unix-common\4.1.85.Final\netty-transport-native-unix-common-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport\4.1.85.Final\netty-transport-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-resolver\4.1.85.Final\netty-resolver-4.1.85.Final.jar;D:\maven\repository\io\opentelemetry\opentelemetry-api\1.13.0\opentelemetry-api-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-context\1.13.0\opentelemetry-context-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-exporter-logging\1.13.0\opentelemetry-exporter-logging-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk-metrics\1.13.0-alpha\opentelemetry-sdk-metrics-1.13.0-alpha.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk-logs\1.13.0-alpha\opentelemetry-sdk-logs-1.13.0-alpha.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk-common\1.13.0\opentelemetry-sdk-common-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure-spi\1.13.0\opentelemetry-sdk-extension-autoconfigure-spi-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure\1.13.0-alpha\opentelemetry-sdk-extension-autoconfigure-1.13.0-alpha.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk-trace\1.13.0\opentelemetry-sdk-trace-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-sdk\1.13.0\opentelemetry-sdk-1.13.0.jar;D:\maven\repository\io\opentelemetry\opentelemetry-semconv\1.13.0-alpha\opentelemetry-semconv-1.13.0-alpha.jar;D:\maven\repository\io\ous\jtoml\2.0.0\jtoml-2.0.0.jar;D:\maven\repository\net\bytebuddy\byte-buddy\1.12.19\byte-buddy-1.12.19.jar;D:\maven\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;D:\maven\repository\org\asynchttpclient\async-http-client\2.12.3\async-http-client-2.12.3.jar;D:\maven\repository\org\asynchttpclient\async-http-client-netty-utils\2.12.3\async-http-client-netty-utils-2.12.3.jar;D:\maven\repository\io\netty\netty-codec-socks\4.1.85.Final\netty-codec-socks-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-handler-proxy\4.1.85.Final\netty-handler-proxy-4.1.85.Final.jar;D:\maven\repository\io\netty\netty-transport-native-epoll\4.1.85.Final\netty-transport-native-epoll-4.1.85.Final-linux-x86_64.jar;D:\maven\repository\io\netty\netty-transport-native-kqueue\4.1.85.Final\netty-transport-native-kqueue-4.1.85.Final-osx-x86_64.jar;D:\maven\repository\org\reactivestreams\reactive-streams\1.0.4\reactive-streams-1.0.4.jar;D:\maven\repository\com\typesafe\netty\netty-reactive-streams\2.0.4\netty-reactive-streams-2.0.4.jar;D:\maven\repository\com\sun\activation\jakarta.activation\1.2.2\jakarta.activation-1.2.2.jar;D:\maven\repository\org\seleniumhq\selenium\selenium-http\4.1.4\selenium-http-4.1.4.jar;D:\maven\repository\dev\failsafe\failsafe\3.2.3\failsafe-3.2.3.jar;D:\maven\repository\org\seleniumhq\selenium\selenium-json\4.1.4\selenium-json-4.1.4.jar;D:\maven\repository\org\seleniumhq\selenium\selenium-support\4.1.4\selenium-support-4.1.4.jar;D:\maven\repository\com\google\code\gson\gson\2.9.1\gson-2.9.1.jar;D:\maven\repository\cglib\cglib\3.3.0\cglib-3.3.0.jar;D:\maven\repository\org\ow2\asm\asm\7.1\asm-7.1.jar;D:\maven\repository\commons-validator\commons-validator\1.7\commons-validator-1.7.jar;D:\maven\repository\commons-beanutils\commons-beanutils\1.9.4\commons-beanutils-1.9.4.jar;D:\maven\repository\commons-digester\commons-digester\2.1\commons-digester-2.1.jar;D:\maven\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\maven\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;D:\maven\repository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar" com.jynine.CalculatorTest
Exception in thread "main" java.lang.IllegalAccessError: tried to access method org.openqa.selenium.remote.http.ClientConfig.<init>(Ljava/net/URI;Ljava/time/Duration;Ljava/time/Duration;Lorg/openqa/selenium/remote/http/Filter;Ljava/net/Proxy;Lorg/openqa/selenium/Credentials;)V from class io.appium.java_client.AppiumClientConfig
	at io.appium.java_client.AppiumClientConfig.<init>(AppiumClientConfig.java:62)
	at io.appium.java_client.AppiumClientConfig.defaultConfig(AppiumClientConfig.java:79)
	at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:109)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:117)
	at com.jynine.CalculatorTest.main(CalculatorTest.java:64)

Process finished with exit code 1
`

**Comment by saikrishna321** [comment]
Please try with version ` <java-client.version>8.5.0</java-client.version>`

**Comment by jynine** [comment]
![1683775139565](https://github.com/appium/java-client/assets/6419646/e2395d1a-d194-44ce-a0a9-13290a97f155)

maven repository not have 8.5.0

**Comment by jynine** [comment]
> Please try with version ` <java-client.version>8.5.0</java-client.version>`

Maven repository not have 8.5.0

**Comment by valfirst** [comment]
@jynine Appium Java client `8.3.0` is compatible with Selenium client `4.7.0` - `4.8.1`, but you are trying to use it with Selenium `4.1.4`:

> ;D:\maven\repository\org\seleniumhq\selenium\selenium-api\4.1.4\selenium-api-4.1.4.jar;D:\maven\repository\org\seleniumhq\selenium\selenium-remote-driver\4.1.4\selenium-remote-driver-4.1.4.jar;

**Comment by valfirst** [comment]
Please check [Compatibility Matrix](https://github.com/appium/java-client/#compatibility-matrix) to find details on versions compatibility.
