### ISSUE TITLE
[🐛 Bug]: The setAutoWebview(boolean) method isn't working as expected

### ISSUE THREAD

**Issue by jgfmachado** [appium/java-client#1916]
## Description

`UiAutomator2Options().setAutoWebview(boolean);` isn't working as expected, as it doesn't change the focus to the Webview on app startup when set to `true`. We have to use `UiAutomator2Options().setCapability("autoWebview", boolean);` instead.

## Environment

Using Appium Java Client version 8.4.0

## Details

After launching the app, my script attempts to change the URL. Once it reaches that point I get a WebDriverException exception,

## Code To Reproduce Issue

```
UiAutomator2Options capabilities = new UiAutomator2Options();
capabilities.setAutoWebview(true);
```

## Exception Stacktraces

https://gist.github.com/jgfmachado/12ed0d38a5da221981117dbee80624f3

## Link To Appium Logs

https://gist.github.com/jgfmachado/a026d7728c826634dcd5df7a8ea0547e

**Comment by mykola-mokhnach** [comment]
There is a typo in the constant value. Should be fixed by https://github.com/appium/java-client/pull/1917

**Comment by mykola-mokhnach** [comment]
The fix is in master.
