### ISSUE TITLE
Unable to enter text into a textfield on ios 8.3 iphone 6 simulator

### ISSUE THREAD

**Issue by ramgokul** [appium/java-client#192]
Hi,

iOS version : 8.3
Appium Version : 2.2.0
Appium Client : 1.3.7
Selenium Version: 2.43.1 
Xcode version: 6.3.1
OSX version: 10.10.3

What I am trying to do:
1. Launch iphone 6 simulator
2. Launch UICatalog app
3. Click on the 'left' button
4. Scroll to 'Text Fields'. Tap on it
5. Enter text 'a' in all of the displayed text fields.

Code:
File file = new File("/Users/apple/Desktop/UICatalog/UICatalog.app");

		cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "iPhone 6");
		cap.setCapability("platformName", "iOS");
		cap.setCapability("platformVersion", "8.3");
		cap.setCapability("app", file.getAbsolutePath());

		IOSDriver dr2 = (IOSDriver)driver;
		dr2 = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"),cap);
		dr2.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		dr2.findElementByIosUIAutomation("UIATarget.localTarget().frontMostApp().navigationBar().leftButton()").click();
		dr2.findElementByIosUIAutomation("UIATarget.localTarget().frontMostApp().mainWindow().tableViews()[0].cells()[\"Text Fields\"]").click();
		List<WebElement> list = dr2.findElementsByXPath("//UIATextField");

		System.out.println(list.size());

		for(WebElement element : list){
			if(element.isDisplayed()){
				System.out.println("Element displayed");
				System.out.println(element.getText());
				element.clear();
				element.sendKeys("a");
				Thread.sleep(5000);
				dr2.quit();
			}
		}	

	}

Appium log messages:

info: [debug] [INST] 2015-05-01 07:05:29 +0000 Error: Error during eval: typeString@[native code]

       sendKeysToActiveElement@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/9BF8C044-6DA3-4BDA-BB93-449873FA0C77/bootstrap-931e8d7703a594e3.js:1281:32

setValueByType@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/9BF8C044-6DA3-4BDA-BB93-449873FA0C77/bootstrap-931e8d7703a594e3.js:1986:38

eval code

eval@[native code]

startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/9BF8C044-6DA3-4BDA-BB93-449873FA0C77/bootstrap-931e8d7703a594e3.js:2693:30

bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/9BF8C044-6DA3-4BDA-BB93-449873FA0C77/bootstrap-931e8d7703a594e3.js:2761:31

global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/9BF8C044-6DA3-4BDA-BB93-449873FA0C77/bootstrap-931e8d7703a594e3.js:2770:10

info: [debug] [INST] 2015-05-01 07:05:29 +0000 Debug: responding with:

info: [debug] [INST] 2015-05-01 07:05:29 +0000 Debug: Running system command #15: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"target.frontMostApp().keyboard() failed to tap 'a'"}...

info: [debug] [INST] 2015-05-01 08:11:38 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected EOF on line 2597 of bootstrap-931e8d7703a594e3.js

info: [debug] [INST] 2015-05-01 08:14:52 +0000 Error: Error during eval: typeString@[native code]
       sendKeysToActiveElement@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/E061154A-FA4C-452A-A4E6-D72AB337A064/bootstrap-931e8d7703a594e3.js:1281:32
setValueByType@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/E061154A-FA4C-452A-A4E6-D72AB337A064/bootstrap-931e8d7703a594e3.js:1986:38
eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/E061154A-FA4C-452A-A4E6-D72AB337A064/bootstrap-931e8d7703a594e3.js:2693:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/E061154A-FA4C-452A-A4E6-D72AB337A064/bootstrap-931e8d7703a594e3.js:2761:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/E061154A-FA4C-452A-A4E6-D72AB337A064/bootstrap-931e8d7703a594e3.js:2770:10

info: [debug] [INST] 2015-05-01 08:14:52 +0000 Debug: responding with:

info: [debug] [INST] 2015-05-01 08:14:52 +0000 Debug: Running system command #15: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"target.frontMostApp().keyboard() failed to tap 'a'"}...

**Comment by Jonahss** [comment]
This doesn't look like a problem with the java-client, but a problem with Appium. Could you repost the issue there?

Is it possible that one of the elements you are trying to sendKeys() to isn't a proper textField? Does your script succeed on any text field or fail on the first one?

(don't reply here, you can repost to github.com/appium/appium and continue the conversation there)
