### ISSUE TITLE
NPE on method `InteractsWithApps.terminateApp`

### ISSUE THREAD

**Issue by asolntsev** [appium/java-client#1921]
## Description

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at io.appium.java_client.InteractsWithApps.terminateApp(InteractsWithApps.java:297)
	at io.appium.java_client.InteractsWithApps.terminateApp(InteractsWithApps.java:266)
```

## Environment

* Java client build version or git revision if you use some snapshot: 8.4.0, 8.5.0
* Appium server version or git revision if you use some snapshot: 2.0.66
* Desktop OS/version used to run Appium if necessary: MacOS 13.3.1
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 20.1.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 12

## Details

NPE happens in this line in `InteractsWithApps.java:297`:

```java
            return checkNotNull(
                    (Boolean) CommandExecutionHelper.execute(
                            markExtensionAbsence(extName), new AbstractMap.SimpleEntry<>(TERMINATE_APP, args)
                    )
            );
```

Command `CommandExecutionHelper.execute` returns `null`.

## Code To Reproduce Issue

```java
  IOSDriver driver = new IOSDriver();
  driver.terminateApp(appId);
```

**Comment by mykola-mokhnach** [comment]
Make sure xcuitest driver is up to date. There was a bugfix recently regarding this endpoint

**Comment by mykola-mokhnach** [comment]
it is also possible to workaround it by calling `mobile: terminateApp` extension explicitly

**Comment by asolntsev** [comment]
@mykola-mokhnach Sure, here is Appium log: https://gist.github.com/asolntsev/d5ee172f070e1d21fcbc02efc4cb3a4e

I guess the important part is here:
```
Calling AppiumDriver.terminateApp() with args: ["com.saucelabs.mydemoapp.rn",null,null,null,"18d8da88-8101-4f7a-a893-471a07807d7a"]
Executing command 'terminateApp'
Proxying [POST /wda/apps/terminate] to [POST http://127.0.0.1:8100/session/85E0A436-20D6-4B5E-AF2C-57BAE0F67002/wda/apps/terminate] with body: {"bundleId":"com.saucelabs.mydemoapp.rn"}

Got response with status 200: {"value":true,"sessionId":"85E0A436-20D6-4B5E-AF2C-57BAE0F67002"}
Responding to client with driver.terminateApp() result: null
```

**Comment by mykola-mokhnach** [comment]
Seems like I've fixed it once, but then my changes were lost during some other rebase👿 
Try to update xcuitest driver to version 4.29.1

**Comment by asolntsev** [comment]
@mykola-mokhnach Wow. What a blazingly fast update!
Yes, it helped. NPE has dissolved. :)
