### ISSUE TITLE
Inability to start the Appium server programmatically failing in random fashion with the message: io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started.

### ISSUE THREAD

**Issue by vnuta9** [appium/java-client#1927]
## Description

Related to the topic "https://github.com/appium/java-client/blob/master/docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md" applicable to Appium versions 1.xx, I am getting random failure(roughly 1 in every 3 times) of starting the Appium server programmatically.

## Environment

* Java client build version or git revision if you use some snapshot: **8.5.0**
* JDK: **1.15.02**
* Appium server version or git revision if you use some snapshot:**2.0.0-beta66**
* Desktop OS/version used to run Appium if necessary:**Mac OS Ventura 13.3.1.a**
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:**node v18.15.0**
* Mobile platform/version under test:iPhone XS(iOS v13)
* Real device or emulator/simulator:Real.

## Details

Irrespective of using any mobile device, Android or iOS, I am getting failure with error message to start the Appium server programmatically. It is not the case when I start the Appium server on the terminal, but only during running the test in the IDE.

## Code To Reproduce Issue [ Good To Have ]
        AppiumDriverLocalService server = GetAppiumService();
...
...
```
   public AppiumDriverLocalService GetAppiumService() {
        GlobalParams params = new GlobalParams();
        return AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                .usingAnyFreePort()
                .withArgument(() -> "--base-path", "/wd/hub")
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                .withLogFile(new File(params.getPlatformName() + "_"
                        + params.getDeviceName() + File.separator + "Server.log")));
    }
```

## Exception Stacktraces

`io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: /usr/local/bin/node Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 44637, --address, 0.0.0.0, --log, /Users/venkatanutalapati/dev/IntelliJWorkspace/zimperiumzips/iOS_iPhone/Server.log, --base-path, /wd/hub/, --session-override] `

**Comment by mykola-mokhnach** [comment]
Perhaps the server needs to more time to start on your local machine. Try to increase the default timeout.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/8ebb5c320a1b98fbc14ac2f2c9cec1447db76c34/src/test/java/io/appium/java_client/ios/BaseIOSTest.java#L47 could be used as an example

**Comment by vnuta9** [comment]
@mykola-mokhnach 
Great !! It is working now with out throwing an error, so far.

BTW, I installed the following drivers, for my test automation of a **Flutter app** on both **Android and iOS platforms**
✔ Listing available drivers
- xcuitest@4.26.0 [installed (npm)]
- uiautomator2@2.24.0 [installed (npm)]
- flutter@1.14.3 [installed (npm)]
- safari@3.3.3 [installed (npm)]
- gecko@1.1.9 [installed (npm)]
- mac2@1.5.3 [installed (npm)]
- espresso [not installed]
- chromium [not installed]

I observed that every time, I start the Server, these drivers are being loaded, out of which I believe only some are required, the rest could be uninstalled **to save time**. I believe, I can **_uninstall_** '**safari', 'gecko', 'mac2' and even '_flutter_'**. 
Would you agree ?

**Comment by mykola-mokhnach** [comment]
it is completely up to you what drivers to select. I assume if you only need to automate flutter apps then only the "flutter" driver must be present
