### ISSUE TITLE
Install or update appium-gestures-plugin required for W3c Actions/Gestures implementation when using Appium 2.0

### ISSUE THREAD

**Issue by vnuta9** [appium/java-client#1930]
## Description

I am using **Appium2.0.0-beta66 version**. Since **TouchAction** class used for the gesture/actions is being deprecated, I am supposed to install **appium-gestures-plugin** ([[from](https://github.com/AppiumTestDistribution/appium-gestures-plugin)]) ) and use it.
## Environment

* Java client build version or git revision if you use some snapshot:**8.5**
* Appium server version or git revision if you use some snapshot:**2.0.0.-beta66**
* Desktop OS/version used to run Appium if necessary: **v18.15.0**
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:Android v13, iOS v13
* Real device or emulator/simulator:Real Device

## Details

When I try to run the command

`$appium plugin install --source=npm appium-gestures-plugin`
as was suggested, I am getting the message
✔ Installing 'appium-gestures-plugin'
Error: ✖ A plugin named "gestures" is already installed. Did you mean to update?
I tried to check the installed plugins

`$appium plugin list --installed`
✔ Listing installed plugins

- relaxed-caps@1.0.0-beta.13 [installed (npm)]
- images@1.3.7 [installed (npm)]
- execute-driver@2.0.6 [installed (npm)]
- gestures@1.0.0-beta.4 [installed (npm)]

Then ran this command:
`$appium plugin update  appium-gestures-plugin
`
I got back this message:
**Error: ✖ The plugin "appium-gestures-plugin" was not installed, so can't be updated**
**How to update the existing 'gestures@1.0.0-beta.4' to gestures@2.0.0 ?**
## Code To Reproduce Issue [ Good To Have ]

Please remember: it's easier to reproduce and fix the bug with sample code.
You can git clone https://github.com/appium/appium/tree/master/sample-code or https://github.com/appium/appium/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by saikrishna321** [comment]
@vnuta9 Closing this ticket as you have started a discussion here https://github.com/AppiumTestDistribution/appium-gestures-plugin/issues/74#issuecomment-1571232393
