### ISSUE TITLE
Invalid sendSMS phoneNumber param

### ISSUE THREAD

**Issue by wazzeps** [appium/java-client#1939]
## Description

Android sendSMS method doesn't take plain text although it works in the emulator extended controls.

## Environment

* Java client 8.5.1
* Appium server 2.0.0-beta.71
* Driver: uiautomator2@2.25.3
* Ubuntu 20.04
* Android
* Emulator

## Details

`driver.sendSMS("Sender", "111111");` throws an exception
An unknown server-side error occurred while processing the command. Original error: Invalid sendSMS phoneNumber param Sender

while the emulator extended controls allow to send such an SMS

![image](https://github.com/appium/java-client/assets/120301053/166dabd3-7317-42bc-9a68-20b2532a2e96)

## Exception Stacktraces

[SMS Java stacktrace](https://gist.github.com/wazzeps/238f90cca062fbef6a98d36e48302635)

## Link To Appium Logs

[SMS Appium logs](https://gist.github.com/wazzeps/a02b1796ce4740dc50b5f606015a5bd1)

**Comment by mykola-mokhnach** [comment]
Are you sure the method arguments not swapped?

**Comment by wazzeps** [comment]
Method signature: default void sendSMS(String phoneNumber, String message)

If I swap the arguments I get an SMS from "111111" with "Sender" text.

**Comment by mykola-mokhnach** [comment]
> If I swap the arguments I get an SMS from "111111" with "Sender" text.

So what is the problem?

**Comment by wazzeps** [comment]
How to pass "Sender" as phoneNumber?

**Comment by wazzeps** [comment]
uiautomator2@2.26.2

It's working now.

Thanks for the fix.
