### ISSUE TITLE
java_client | appium method to access app cache

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#194]
Sorry, If I am posting it here wrongly, but I want to know If there is any method in java client that can provide me information related to my app's cache like it's status,size etc

In selenium we have 

@Test
public void testAppCacheStatus(){
AppCacheStatus status = (ApplicationCache)
driver).getStatus();
assertEqual(status AppCacheStatus.UNCACHED);
}
}

LocalStorage storageDriver = (LocalStorage) driver;
storageDriver.size(); // returns 0 if there is nothing stored n browser

**Comment by Jonahss** [comment]
There are no functions like that currently, but you could submit an issue to the main Appium repo as a feature request.
