### ISSUE TITLE
How to deal with the Maps.TransformedEntriesMap type result returned from getContextHandles method?

### ISSUE THREAD

**Issue by shinobi01** [appium/java-client#1957]
## Description

I'm creating test cases on iOS hybrid application, we have multiple web views when I trying to switch context, so I used .fullContextList() capability to show more informations to identifying which web view is going to be switch. but I got Maps.TransformedEntriesMap type results from getContextHandles method, how could I got the information from it?

## Environment

* Java client build version or git revision if you use some snapshot: java client 8.3
* Appium server version or git revision if you use some snapshot: v2.0.0-beta.67
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS 16
* Real device or emulator/simulator: Real device

## Details

![image](https://github.com/appium/java-client/assets/19482522/dad66d02-8434-46bd-9f30-c3e5d42062f3)

## Code To Reproduce Issue [ Good To Have ]

Capabilities:
return new XCUITestOptions()
				.setUdid(UDID)
				.setPlatformVersion(prop.getProperty("platformVersion"))
				.setDeviceName(prop.getProperty("deviceName"))
				.setApp(appLocation)
				.setAutomationName(prop.getProperty("automationName"))
				.fullReset()
				.setUseNewWDA(false)
				.fullContextList()
				.clearSystemFiles()
				.setNewCommandTimeout(Duration.ofSeconds(300))
				.showXcodeLog();
Code Snippet:
// AppiumDriver driver
Set<String> contextNames = ((SupportsContextSwitching)world.driver).getContextHandles();

**Comment by mykola-mokhnach** [comment]
https://github.com/google/guava/blob/a9c2970e1cdff1e71a27a75866b083f3ae60d6f2/guava/src/com/google/common/collect/Maps.java#L2172

It implements the Map interface and thus could be interacted as any other normal map

**Comment by shinobi01** [comment]
@mykola-mokhnach, thank you for your response.
yes, we could get the info in follow actions, just post here in case anyone needed.
String id = (String) ((Map<?, ?>) contextName).get("id");
