### ISSUE TITLE
AndroidDriver#scrollToExact

### ISSUE THREAD

**Issue by ahansen1** [appium/java-client#196]
The AndroidDriver#scrollToExact javadoc says that it will match on "description **or** name".  However, the selector being created appears to be matching on description **and** name.  I attempted to fork and create a failing unit test.  But, the APK used by AndroidDriverTest appears to have the same name and description for all the menu items that I could find.

> Scroll forward to the element which has a description or name which exactly matches the input text.

**Comment by ahansen1** [comment]
More accurately, it looks like it is behaving like an "and" because if the first selector fails it is throwing an UiObjectNotFoundException and returning a failure early.

```
info: --> POST /wd/hub/session/0c5db892-7b0c-4f6f-8a37-34be4861ee17/element {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"Java\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"Java\").instance(0));"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"Java\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"Java\").instance(0));","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"Java\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"Java\").instance(0));","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("Java").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("Java").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("Java").instance(0))
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().description("Java").instance(0),
info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().description("Java").instance(0)
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "Java"
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@186efe68
info: [debug] [BOOTSTRAP] [error] com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[INSTANCE=0, SCROLLABLE=true]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: problem using reflection to call this method"}
info: [debug] Condition unmet after 11539ms. Timing out.
info: [debug] Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","origValue":"Could not parse UiSelector argument: problem using reflection to call this method"},"sessionId":"0c5db892-7b0c-4f6f-8a37-34be4861ee17"}
```

**Comment by aniket-21** [comment]
which version of Java-client are you using? Can you use the latest one and check if the issue persists? If yes, please re-post the server trace

**Comment by aniket-21** [comment]
I checked this issue and can confirm that scrollTo or scrollToExact checks for both Description and Text and not just either of them. First it tries to find with description, if not it will try to find with Text.
I don't think this is a bug

**Comment by anders-g-hansen** [comment]
I can also confirm that this is not an issue on the current code.  Knowing more now about bootstrap and looking back on my original log, it looks like it was likely the issue was in that code vs. java-client.  I'm now running 1.4.8 and I just tested it and see it making both calls now.

### Test
	@Test
	public void scrollToExactNotThere() {
	  driver.scrollToExact("DoesNotExist").click();
	}

### Output

	info: --> POST /wd/hub/session/366d60e0-ee67-4f53-93cd-e625077a2213/element {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"DoesNotExist\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).sc
	info: [debug] Waiting up to 0ms for condition
	info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"DoesNotExist\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoVi
	info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"DoesNotExist\").instance(0));new UiScrollable(new UiSelector().scrol
	info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
	info: [debug] [BOOTSTRAP] [debug] Got command action: find
	info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("DoesNotExist").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("DoesNotExist").instance(0)); using ANDROI
	info: [debug] [UIAUTOMATOR STDOUT] [APPIUM-UIAUTO] [debug] Parsing scrollable: new UiScro
	info: [debug] [UIAUTOMATOR STDOUT] llable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("DoesNotExist").instance(0))[/APPIUM-UIAUTO]
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().description("DoesNotExist").instance(0),
	info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().description("DoesNotExist").instance(0)
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "DoesNotExist"
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@12099331
	info: [debug] [BOOTSTRAP] [debug] Invoke complete.
	info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("DoesNotExist").instance(0))
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().text("DoesNotExist").instance(0),
	info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().text("DoesNotExist").instance(0)
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "DoesNotExist"
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@21d2ca16
	info: [debug] [BOOTSTRAP] [debug] Invoke complete.
	info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=DoesNotExist, INSTANCE=0]
	info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=DoesNotExist, INSTANCE=0]
	info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
	info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("DoesNotExist").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("DoesNotExist").instance(0)); using ANDROI
	info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("DoesNotExist").instance(0))
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().description("DoesNotExist").instance(0),
	info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().description("DoesNotExist").instance(0)
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "DoesNotExist"
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [UIAUTOMATOR STDOUT] [APPIUM-UIAUTO] [debug]
	info: [debug] [UIAUTOMATOR STDOUT] Method name: scrollIntoView[/APPIUM-UIAUTO]
	info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@356ef97
	info: [debug] [BOOTSTRAP] [debug] Invoke complete.
	info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("DoesNotExist").instance(0))
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().text("DoesNotExist").instance(0),
	info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().text("DoesNotExist").instance(0)
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "DoesNotExist"
	info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
	info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
	info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@ece3584
	info: [debug] [BOOTSTRAP] [debug] Invoke complete.
	info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=DoesNotExist, INSTANCE=0]
	info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=DoesNotExist, INSTANCE=0]
	info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"No element found"}
	info: [debug] Condition unmet after 12264ms. Timing out.
	info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"No element found"},"sessionId":"366d60e0-ee67-4f53-93cd-e625077a2213"}
	info: <-- POST /wd/hub/session/366d60e0-ee67-4f53-93cd-e625077a2213/element 500 12269.427 ms - 195

**Comment by aniket-21** [comment]
Cool!
