### ISSUE TITLE
Session creation fails when xcuitest.setProcessArguments() is used

### ISSUE THREAD

**Issue by prasadshirwadkar96** [appium/java-client#1963]
## Description

**Steps to reproduce:**

1. Add process arguments in XCUITestOptions like below:
```
List<String> processArgs = new ArrayList<>(List.of(""));
Map<String, Object> processEnv = new HashMap<>();
processEnv.put("key", "value");
options.setProcessArguments(new ProcessArguments(processArgs, processEnv));
```
2. Create a new IOSDriver by using the options from above.

## Environment

* Java client build version or git revision if you use some snapshot: v8.5.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device (BrowserStack)

## Details

Exception:
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
...
Caused by: org.openqa.selenium.WebDriverException: processArguments must be a json format or an object with format {args : [], env : {a:b, c:d}}
```
In case we provide the capability in the following way, it works fine (the capability value is formatted to JSON string)
```
List<String> processArgs = new ArrayList<>(Arrays.asList(""));
JSONObject argsValue = new JSONObject();
argsValue.put("args", processArgs);
Map<String, String> processEnv = new HashMap<>();
processEnv.put("key", "value");
argsValue.put("env", processEnv);
options.setCapability("appium:processArguments", argsValue.toString());
```

## Code To Reproduce Issue [ Good To Have ]

Added Above

## Exception Stacktraces
https://gist.github.com/prasadshirwadkar96/0f3e6c7b3fcb45d3dbc13eddae75758a

**Comment by mykola-mokhnach** [comment]
- Please attach the actual server log
- The `ProcessArguments` class has dedicated constructors for cases when only env or only args should be provided but not both. If you still want to use the default constructor then try to set null to the corresponding value instead of an empty object.
