### ISSUE TITLE
[Feature] Add option to have video filters for Android screen recording

### ISSUE THREAD

**Issue by kle97** [appium/java-client#1964]
## Description
Can we have option to have video filters for Android screen recording?

## Environment

* Java client build version or git revision if you use some snapshot: 8.5.1
* Appium server version or git revision if you use some snapshot: 2.0.0-beta.57
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v18.11.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Details

AndroidStartScreenRecordingOptions class doesn't have video filter option like IOSStartScreenRecordingOptions. It'll be nice if we can have ffmpeg video filter for Android screen recording too.

## Code To Reproduce Issue [ Good To Have ]

N/A

## Exception Stacktraces

N/A

## Link To Appium Logs

N/A

**Comment by mykola-mokhnach** [comment]
I don't think it would be possible. Android screen recorder uses an internal system toot while the iOS one uses ffmpeg to encode the incoming MJPEG stream from the device. And video filters are only available for the latter. The screenrecorder tool in Android though has pretty limited set of possible options.

**Comment by kle97** [comment]
@mykola-mokhnach I see. Adb screenrecord tool indeed has only a few options.
I'm just curious, is it possible to say using ffmpeg to further process the video that is returned from Appium and add a timestamp overlay on that video?
I'm looking at a ffmpeg wrapper in Java like this one
https://github.com/bramp/ffmpeg-cli-wrapper

**Comment by mykola-mokhnach** [comment]
This is definitely possible. Locally, you could do any necessary video postprocessing, although this won't be a part of the Appium API

**Comment by kle97** [comment]
@mykola-mokhnach 
Thanks for all of your information. That's really good to know.
