### ISSUE TITLE
iOS - scrollTo and scrollToExact should parameterise the class name

### ISSUE THREAD

**Issue by email2vimalraj** [appium/java-client#197]
Currently, the `scrollTo` and `scrollToExact` method has the `UIATableView` hardcoded in the method under the `IOSDriver` class. The `UIATableView` is specific to a particular type of application.

The application which I test has implemented the `UIAScrollView` instead of `UIATableView`. Hence I would recommend to parameterise the value of the view class name like as follows:

```java
public MobileElement scrollTo(String className, String text) {
     return ((IOSElement) findElementByClassName(className)).scrollTo(text);
}
```

Same for `scrollToExact`. Please refer [UIAScrollView Documentation](https://developer.apple.com/library/prerelease/ios/documentation/ToolsLanguages/Reference/UIAScrollViewClassReference/index.html).

**Comment by Jonahss** [comment]
:+1:

**Comment by TikhomirovSergey** [comment]
I'm closing it according to #385
