### ISSUE TITLE
[Feat]:

### ISSUE THREAD

**Issue by venkatprassu** [appium/java-client#1976]
How search records in android automation testing without using mobile keyboard?
i am using this scripts 
public void clickOnSearchOption(){
        wait.until(ExpectedConditions.visibilityOf(jsalocators.searchDescription));
        jsalocators.searchDescription.click();
        jsalocators.searchDescription.sendKeys("Description");
        DriverClass.getDriver().pressKey(new KeyEvent(AndroidKey.SEARCH));

    }
  But it is not working fine it running fine but display all records along with search name(Description),  I think search is not working or enter button is not click.
how to avoid this problem? please suggest?

**Comment by ashwithpoojary98** [comment]
@venkatprassu try to find any locator available for the search button. If nor then jsalocators.searchDescription.sendKeys("Description"+Keys.Enter);
try this

**Comment by valfirst** [comment]
@venkatprassu please use [Discussions](https://github.com/appium/java-client/discussions) to ask questions
