### ISSUE TITLE
I want use Appium 2.0 with java client 6.1.0

### ISSUE THREAD

**Issue by JYOTIPRAKASH225** [appium/java-client#1992]
### Do I have the most recent component updates?

- [x] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want use Appium 2.0 with java client 6.1.0.
While using AppiumDriverLocalService : I am getting **URL_MASK = "http://%s:%d/wd/hub";**, this doen't work with Appium 2.0
So I need a solution where I will be able to use AppiumDriverLocalService in Appium 2.0 with java client 6.1.0

### Expected Behavior

So I need a solution where I will be able to use AppiumDriverLocalService in Appium 2.0 with java client 6.1.0

### Minimal Reproducible Example

While using AppiumDriverLocalService : I am getting **URL_MASK = "http://%s:%d/wd/hub";**, this doen't work with Appium 2.0

### Environment

- Appium server version : 2.1.3

**Comment by jlipps** [comment]
Why can't you upgrade the java client version?

**Comment by ashwithpoojary98** [comment]
@JYOTIPRAKASH225  please try below code
    new AppiumServiceBuilder()
                .usingAnyFreePort()
                .usingDriverExecutable(new File("/usr/local/bin/node"))
                .withLogFile(new File(System.getProperty("user.dir")+"appium.log"))
                .withArgument(GeneralServerFlag.BASEPATH, "/wd/hub")
                .withArgument(GeneralServerFlag.RELAXED_SECURITY)
                .build()
                .start();
