### ISSUE TITLE
bug: AppiumFluentWait -> Cannot access org.openqa.selenium.support.ui.FluentWait

### ISSUE THREAD

**Issue by AlessandroMiccoli** [appium/java-client#2012]
## Description

I am trying to use AppiumFluentWait. Previously, with the version 7.6.0, I was able to do 

```
new AppiumFluentWait<AppiumDriver<?>>(appiumDriver)
                .withTimeout(Duration.ofMillis(maxWait))
                .pollingEvery(Duration.ofMillis(interval))
                .ignoring(NoSuchElementException.class)
                .ignoring(TimeoutException.class)
                .until(ExpectedConditions.visibilityOfElementLocated(by));
```

With version 8.5.1, I got: `Cannot access org.openqa.selenium.support.ui.FluentWait` when I try to use AppiumFluentWait. 

Is it a bug or I am missing something for this implementation?

**Comment by mykola-mokhnach** [comment]
Most likely something has been changed in selenium so the reflection access is broken now and needs to be updated.
So yeah, lets assume it is a bug

**Comment by mykola-mokhnach** [comment]
Please provide the full stacktrace as well

**Comment by AlessandroMiccoli** [comment]
Sorry for my late reply. This is a screenshot that summarises the problem. 

![Screenshot 2023-09-15 at 16 20 22](https://github.com/appium/java-client/assets/57630383/439eb3d3-e6ea-499b-a429-cc20c10296bd)

**Temporary fix**

Add the dependency to your project -> implementation 'org.seleniumhq.selenium:selenium-support:4.8.3'

**Fix to appium**

Add this to the build.gradle

    api ('org.seleniumhq.selenium:selenium-support') {
        version {
            strictly "[${seleniumVersion}, 5.0)"
            prefer "${seleniumVersion}"
        }
    }

Let me know if it makes sense for you, so I will create a PR.

**Comment by mykola-mokhnach** [comment]
@valfirst @SrinivasanTarget Are you able to reproduce the above issue?

**Comment by ashwithpoojary98** [comment]
@AlessandroMiccoli it's working fine 
 new AppiumFluentWait<>(appiumDriver)
                .withTimeout(Duration.ofMillis(maxWait))
                .pollingEvery(Duration.ofMillis(interval))
                .ignoring(NoSuchElementException.class)
                .ignoring(TimeoutException.class)
                .until(ExpectedConditions.visibilityOfElementLocated(by));

**Comment by saikrishna321** [comment]
@mykola-mokhnach I'm unable to reproduce this problem. Using the latest java-client

**Comment by AlessandroMiccoli** [comment]
@ashwithpoojary98 are you using `io.appium:java-client:8.5.1` without implementing separately `org.seleniumhq.selenium:selenium-support:4.8.3`? If yes, on my IntelliJ I don't see selenium-support in the compile classpath:

![Screenshot 2023-09-19 at 13 30 31](https://github.com/appium/java-client/assets/57630383/67266c9e-be35-450d-ba9c-437a36a5d190)

Could you provide me with the whole implementation with the import, etc...

**Comment by ashwithpoojary98** [comment]
@AlessandroMiccoli I'm using Appium client 8.5.1

**Comment by AlessandroMiccoli** [comment]
> @AlessandroMiccoli I'm using Appium client 8.5.1

@ashwithpoojary98 I am using the same.

Do you import `org.seleniumhq.selenium:selenium-support:4.8.3` separately in your project? Do you manipulate the import of `io.appium:java-client:8.5.1` in some ways?

Please, could you share your code on git?
