### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.openqa.selenium.remote.http.ClientConfig.<init>(java.net.URI, java.time.Duration, java.time.Duration, org.openqa.selenium.remote.http.Filter, java.net.Proxy, org.openqa.selenium.Credentials)'

### ISSUE THREAD

**Issue by dipakkumar1225** [appium/java-client#2044]
## Description
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.openqa.selenium.remote.http.ClientConfig.<init>(java.net.URI, java.time.Duration, java.time.Duration, org.openqa.selenium.remote.http.Filter, java.net.Proxy, org.openqa.selenium.Credentials)'

## Environment

* Java client build version or git revision if you use some snapshot: 8.5.1
* Appium server version or git revision if you use some snapshot:2.1.3
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 18.18.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both emulator and Real Device
Java Version 15
## Details
By lowering the selenium version to 4.13.0, it works, but not with 4.14.0 or 4.14.1.
```
<dependencies>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>8.5.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-remote-driver</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-support</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-api</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-http</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-json</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-manager</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-os</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.13.0</version>
        </dependency>
    </dependencies>
```

## Code To Reproduce Issue [ Good To Have ]
```
public static void main(String[] args) {
        AppiumDriverLocalService appiumDriverLocalService = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                .withIPAddress("127.0.0.1")
                .usingPort(4723)
                .withArgument(GeneralServerFlag.BASEPATH, "/wd/hub/")
                .withArgument(GeneralServerFlag.LOG_LEVEL, "info:debug")
                .withTimeout(Duration.ofSeconds(180))
                .withLogFile(new File("Logs" + File.separator + "Server.log")));
        appiumDriverLocalService.start();

        UiAutomator2Options uiAutomator2Options = new UiAutomator2Options()
                .setAutomationName(AutomationName.ANDROID_UIAUTOMATOR2)
                .setApp(System.getProperty("user.dir" + File.separator + "app" + File.separator + "android" + File.separator + "Android-MyDemoAppRN.1.3.0.build-244.apk"))
                .setFullReset(false)
                .setNoReset(true)
                .setPlatformName("android")
                .setPlatformVersion("13")
                .setUdid("emulator-5554")
                .setAppPackage("com.saucelabs.mydemoapp.rn")
                .setAppActivity("com.saucelabs.mydemoapp.rn.MainActivity");

        System.out.println("URL " + appiumDriverLocalService.getUrl());
        AppiumDriver appiumDriver = new AndroidDriver(appiumDriverLocalService.getUrl(), uiAutomator2Options);
        System.out.println("SessionID" + appiumDriver.getSessionId());
        appiumDriverLocalService.stop();
    }
```

## Exception Stacktraces

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.openqa.selenium.remote.http.ClientConfig.<init>(java.net.URI, java.time.Duration, java.time.Duration, org.openqa.selenium.remote.http.Filter, java.net.Proxy, org.openqa.selenium.Credentials)'
	at io.appium.java_client.AppiumClientConfig.<init>(AppiumClientConfig.java:62)
	at io.appium.java_client.AppiumClientConfig.defaultConfig(AppiumClientConfig.java:79)
	at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:109)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:113)
	at com.automation.Demo.main(Demo.java:40)
```

## Link To Appium Logs
```
Tried to attach logging to file 'D:\Trial\Logs\Server.log' but an error occurred: EBUSY: resource busy or locked, unlink 'D:\Trial\Logs\Server.log'
[Appium] Welcome to Appium v2.1.3
[Appium] Non-default server args:
[Appium] { address: '127.0.0.1', basePath: '/wd/hub/', loglevel: 'info:debug' }
[Appium] Attempting to load driver uiautomator2...
[Appium] Attempting to load driver espresso...
[Appium] Appium REST http interface listener started on http://127.0.0.1:4723/wd/hub
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.9 (automationName 'UiAutomator2')
[Appium]   - espresso@2.25.7 (automationName 'Espresso')
[Appium] Available plugins:
[Appium]   - images@2.1.4
[Appium]   - element-wait@2.0.3
[Appium]   - gestures@3.0.0
[Appium]   - appium-dashboard@v2.0.2
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[HTTP] <-- GET /wd/hub/status 200 5 ms - 110
[HTTP] 
```

**Comment by ashwithpoojary98** [comment]
@dipakkumar1225  can please check "D:\Trial\Logs" Logs folder exist??

**Comment by valfirst** [comment]
> By lowering the selenium version to 4.13.0, it works, but not with 4.14.0 or 4.14.1.

Please check the [compatibility matrix](https://github.com/appium/java-client#compatibility-matrix)

**Comment by Mahendra-Adda** [comment]
i faced the same issue 
tried By lowering the selenium version to 4.13.0 and other versions 
still facing the issue.

**Comment by JuscaMolaiwa** [comment]
I am facing the same issue, did you guys get any solution for this?

**Comment by shyam6363** [comment]
Hi All,

The issue got resolved by updating the appium java client dependency.


  <dependency>
     <groupId>io.appium</groupId>
     <artifactId>java-client</artifactId>
     <version>9.2.2</version>
  </dependency>
  
  
  **Here's the my pom xml.**
  
  <dependencies>
  
  
  
  <dependency>
     <groupId>org.seleniumhq.selenium</groupId>
     <artifactId>selenium-java</artifactId>
     <version>4.23.0</version>
  </dependency>  
    
  
  
  <dependency>
     <groupId>io.appium</groupId>
     <artifactId>java-client</artifactId>
     <version>9.2.2</version>
  </dependency>
   
 
  
  <dependency>
     <groupId>org.slf4j</groupId>
     <artifactId>slf4j-api</artifactId>
     <version>2.0.13</version>
  </dependency>
    
    
  
   <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.13</version>
      <scope>test</scope>
    </dependency>

  </dependencies>

**Comment by Mahendra-Adda** [comment]
Hi All ,
used  

            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>8.6.0</version>
      now it's working fine

**Comment by mdahooks** [comment]
at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[38;5;156m[6941fef7][0m[38;5;86m[HTTP][0m [37m<-- POST /session [39m[31m500[39m [90m732 ms - 10542[39m [90m[39m
FAILED: ayamApp.TestCase1.openTheApp
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Check https://github.com/appium/appium/issues/13802 for throubleshooting. Error executing adbExec. Original error: 'Command 'C:\\Users\\Dahooks\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s v49hwk8tnnxsr4ob shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: 
Exception occurred while executing 'delete':

**Comment by krishnaprasanth26** [comment]
The issue got resolved by updating the appium java client dependency.

io.appium java-client 9.2.2. Thanks to Shyam.
