### ISSUE TITLE
No Chrome browser web context after browser termination and relaunch

### ISSUE THREAD

**Issue by wazzeps** [appium/java-client#2062]
## Description

After calling the terminateApp(String bundleId) method to close Chrome browser it has no web context after subsequent launch.

## Environment

* Java-client 8.5.0
* Appium 2.1.3
* uiautomator2@2.31.4
* Android emulator

## Details

We navigate from the application to the Chrome browser using a link, after which we clear the state of the browser, closing all tabs and destroying the browser. When we try to navigate from the application to the browser again, the driver does not find web context.

## Code To Reproduce Issue [ Good To Have ]

Test 1

```
// tap a link in the app
// wait for the browser to open

((SupportsContextSwitching) driver).context("WEBVIEW_chrome");
driver.getWindowHandles().forEach(windowHandle -> driver.switchTo().window(windowHandle).close());
((InteractsWithApps) driver).terminateApp("com.android.chrome");
```

Test 2

```
// tap a link in the app
// wait for the browser to open

System.out.println(((SupportsContextSwitching) driver).getContextHandles());

Output: [NATIVE_APP]
```

## Link To Appium Logs

[Appium logs](https://gist.github.com/wazzeps/b37454f9f7a85859c23398726e5be4c5)

**Comment by wazzeps** [comment]
Setting ensureWebviewsHavePages capability to false allows the driver to see the context but not switch to it.

**Comment by wazzeps** [comment]
@mykola-mokhnach could you please look into?

**Comment by mykola-mokhnach** [comment]
Maybe the context is really not connectable. Are you able to connect to it with Chrome remote debugger in such state?

**Comment by wazzeps** [comment]
Yes I can connect and open tabs with remote dubugger.

![image](https://github.com/appium/java-client/assets/120301053/b1eb8e8d-a508-46bd-9a69-14ac9ddc64d0)

**Comment by wazzeps** [comment]
Sometimes I can see both contexts, but switching is not completed within the allotted time.

[Appium logs](https://gist.github.com/wazzeps/c76e8dbfb29786b4d65236fb50bfabbd)

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't know how we can help there. Maybe try to report the issue to chromedriver.

**Comment by KazuCocoa** [comment]
`appium:showChromedriverLog` may show more information. Although it looks like Chrome or chromedriver side's something.

Not for the version, but chrome v115+ has similar issue https://bugs.chromium.org/p/chromedriver/issues/detail?id=4595
