### ISSUE TITLE
Add non-compliant endpoints from Selenium

### ISSUE THREAD

**Issue by titusfortner** [appium/java-client#2090]
## Description

Selenium currently defines these endpoints and makes them available to Appium:
* GET_SCREEN_ORIENTATION
* SET_SCREEN_ORIENTATION
* GET_SCREEN_ROTATION
* SET_SCREEN_ROTATION
* SWITCH_TO_CONTEXT
* GET_CURRENT_CONTEXT_HANDLE
* GET_CONTEXT_HANDLES

We're looking at removing everything that isn't w3c compliant — https://github.com/SeleniumHQ/selenium/pull/13372

So, here I am, not removing things in Selenium before making sure things are good in Appium. 😂 

Thanks.

**Comment by mykola-mokhnach** [comment]
I would say most of the above commands only make sense in the Appium context, so it is a good idea to remove them from Selenium. Just let us know which version won't have them anymore before it is released

**Comment by titusfortner** [comment]
I'm removing for 4.17. Hope to release it between 1/17 & 1/23 (trying to go off of https://chromiumdash.appspot.com/schedule)

**Comment by mykola-mokhnach** [comment]
cc @valfirst ^
