### ISSUE TITLE
@parameters anonation through exception"BeforeSuite on method initializeAndroidDriver but has not been marked @Optional or defined"

### ISSUE THREAD

**Issue by asmayonis1** [appium/java-client#2100]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 @BeforeSuite
    @Parameters({"platformVersion", "platformName", "deviceName", "automationName"})
    public void initializeAndroidDriver(
    		 String platformVersion,
             String platformName,
             String deviceName,
             String automationName) throws MalformedURLException { {

        URL url = new URL("http://127.0.0.1:4723");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("appium:platformVersion", platformVersion);
        capabilities.setCapability("appium:platformName", platformName);
        capabilities.setCapability("appium:deviceName", deviceName);
        capabilities.setCapability("appium:automationName", automationName );
        capabilities.setCapability("appPackage", "com.talabat");
        capabilities.setCapability("appActivity", "com.talabat.LandingScreen");
        capabilities.setCapability("appium:locationServicesAuthorized", false);
        capabilities.setCapability("appium:locationServicesEnabled", false);
        capabilities.setCapability("appium:autoDismissAlerts", true);
        capabilities.setCapability("appium:autoAcceptAlerts", false);

        androidDriver = new AndroidDriver(url, capabilities);
        wait = new WebDriverWait(androidDriver, Duration.ofSeconds(50));
    }
    }
    
    and run testng xml file 
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">
	<test name="Test-OnePlus5">
		<parameter name="platformVersion" value="13.0"></parameter>
		<parameter name="platformName" value="android"></parameter>
		<parameter name="deviceName" value="RF8NA0W2YFM"></parameter>
		<parameter name="automationName" value="UiAutomator2" />

		<classes>
			<class name="test.TestBase" />
			<class name="test.androidLogin" />
		</classes>
	</test>
</suite>
through exception 
org.testng.TestNGException: 
Parameter 'platformVersion' is required by BeforeSuite on method initializeAndroidDriver but has not been marked @Optional or defined
in /private/var/folders/b5/936632353fj08k51cf78vm9jcn4crr/T/testng-eclipse-1114858715/testng-customsuite.xml

### Expected Behavior

Android parameters should read from XML and run correctly 

### Minimal Reproducible Example

code has been attached 

### Environment

- Operating system:
- Appium server version (output of `appium --version`): v2.3.0
- Appium driver(s) and their version(s): uiautomator2@2.34.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Not sure this exception has to do anything with this client

**Comment by amedvedjev** [comment]
eeee. 
1 you should move start Appium driver to @beforeMethod
2 this is not an appium bug. ask questions -> https://discuss.appium.io/
3 error tells: you did not provide `platformVersion`
you can add logs to see it:
```
    public void initializeAndroidDriver(
            String platformVersion,
            String platformName,
            String deviceName,
            String automationName) throws MalformedURLException {
        System.out.println("initializeAndroidDriver(): platformVersion: '" + platformVersion + "', platformName: '" + platformName + "', deviceName: '" + deviceName + "', automationName: '" + automationName + "'");
```

**Comment by asmayonis1** [comment]
@amedvedjev 
platform provided in XML as 
<test name="Test-OnePlus5">
		<parameter name="platformVersion" value="13.0"></parameter>
		<parameter name="platformName" value="android"></parameter>
		<parameter name="deviceName" value="RF8NA0W2YFM"></parameter>
		<parameter name="automationName" value="UiAutomator2" />
		<parameter name="latitude" value="25.1872"/>
		<parameter name="longitude" value="55.2741"/>
		
but I figured the issue is we need to import 
import org.testng.ITestContext;
