### ISSUE TITLE
iOSFindBy & AndroidFindBy annotations are ignored

### ISSUE THREAD

**Issue by justintilson** [appium/java-client#211]
I've been trying for a couple of days to get iOSFindBy & AndroidFindBy annotations working with page objects and the PageFactory. I've tried versions 2.2.0 and 3.0.0 of the java-client and tests for Android and iOS, all with the same result - which is the same as not including any annotations.

Here is a truncated version of one of my page objects

```java
public class HomePhonePage extends BaseHomePage {

    public HomePhonePage(AppiumDriver driver) {
        super(driver);

        PageFactory.initElements(new AppiumFieldDecorator(driver,
                        IMPLICIT_WAIT,
                        TimeUnit.SECONDS),
                this
        );
    }

    @iOSFindBy(accessibility = "home_landing_my_favorites_count_label")
    private WebElement myFavoritesCountLabel;

    public String getMyFavoritesCountLabel() {
        return myFavoritesCountLabel.getText();
    }
}
```

My test code:
```java
    @Test
    public void testHomeIsValid() {

        homePhonePage = new HomePhonePage(driver);
        globalNavPage = new GlobalNavigationPage(driver);

        homePhonePage.clickHamburgerMenu(); //FAILS HERE because element was not found
        globalNavPage.clickHome();

    }
```
When I debug into PageFactory.initElements, I see [unknown locator] for each property that is a WebElement. Then the PageFactory defaults to looking for each page object's property name as the id or name of the WebElement and fails to find anything.

![unknown-locator2](https://cloud.githubusercontent.com/assets/1480031/8463051/deb8064c-2005-11e5-8d10-ad79755218ab.png)

I suspect "I'm doing it wrong" but I can't figure out where. It is behaving as if the annotations are not even there.

**Comment by Simon-Kaz** [comment]
Hey, could you post your capabilities as well? I've been using page factory extensively and haven't encountered this issue.

**Comment by justintilson** [comment]
```java
System.out.println(driver.getCapabilities().toString());
```
outputs:

Capabilities [{networkConnectionEnabled=true, desired={}, platformVersion=4.4.4, warnings={}, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, databaseEnabled=false, deviceName=192.168.56.101:5555, platform=LINUX}]

I also dug a bit deeper into the debugger for the particular field as it's being decorated by the PageFactory and it shows no annotations (I'm not sure if it should):

![no-annotations](https://cloud.githubusercontent.com/assets/1480031/8465076/1440a576-2015-11e5-8f34-ffcbfb9557a0.png)

**Comment by TikhomirovSergey** [comment]
@justintilson Hi!
Is it native app? Maybe hybrid. Maybe you are trying to run test with mobile browser?

**Comment by TikhomirovSergey** [comment]
>Capabilities [{networkConnectionEnabled=true, desired={}, platformVersion=4.4.4, warnings={}, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, databaseEnabled=false, deviceName=192.168.56.101:5555, platform=LINUX}]

Are you tryng to use iOSFindBy for Android
>@iOSFindBy(accessibility = "home_landing_my_favorites_count_label")
?

Please improve your page object as follows 

```java
@iOSFindBy(accessibility = "home_landing_my_favorites_count_label")
@AndroidFindBy(your locator for android)
    private WebElement myFavoritesCountLabel;
```

What the result?

**Comment by justintilson** [comment]
@TikhomirovSergey - I have separate tests and page objects for Android and iOS and use the appropriate @FindBy in each.

**Comment by justintilson** [comment]
Here are the desired capabilities that are passed into the Android driver:

![dcs-passed-to-android-driver](https://cloud.githubusercontent.com/assets/1480031/8465425/22185ca4-2018-11e5-9de8-fc9f3359ea58.png)

and for the iOS

![dcs-passed-to-ios-driver](https://cloud.githubusercontent.com/assets/1480031/8465441/37d15c6c-2018-11e5-831f-1088f33d1192.png)

**Comment by justintilson** [comment]
And if it helps:

![appium-android-settings](https://cloud.githubusercontent.com/assets/1480031/8465507/da3047fc-2018-11e5-8a44-17a7c856fba3.png)

![appium-ios-settings](https://cloud.githubusercontent.com/assets/1480031/8465508/da309a04-2018-11e5-8d4e-39278dd1d1a3.png)

**Comment by TikhomirovSergey** [comment]
Ok. If I clearly understand you

Appuim features allow to implement one page object for Android/iOS/browser testing. Please look at this  

```java
@iOSFindBy(locator_for_ios) //this locater is used when here is iOS native content
@AndroidFindBy(locator_for_android)//this locator is used when here is Android native content
@FindBy(locator_for_HTML)//this locator is used when here mobile or desktop browser or webview //content
 private WebElement myFavoritesCountLabel;
```

Ok. Is this used with Android 

```java
public class HomePhonePage extends BaseHomePage {

    public HomePhonePage(AppiumDriver driver) {
        super(driver);

        PageFactory.initElements(new AppiumFieldDecorator(driver,
                        IMPLICIT_WAIT,
                        TimeUnit.SECONDS),
                this
        );
    }

    @iOSFindBy(accessibility = "home_landing_my_favorites_count_label")
    private WebElement myFavoritesCountLabel;

    public String getMyFavoritesCountLabel() {
        return myFavoritesCountLabel.getText();
    }
}
```
?

**Comment by TikhomirovSergey** [comment]
...I am just trying to understand your problem and usecase :)

**Comment by justintilson** [comment]
@TikhomirovSergey - I understand that I *can* use a single page object to test both but platforms but I've found in this particular instance it didn't work out well because the implementations are somewhat different and evolving at different rates.

Here is the Android page object:

```java
public class HomePhonePage extends BaseHomePage {

    public HomePhonePage(AppiumDriver driver) {
        super(driver);

        PageFactory.initElements(new AppiumFieldDecorator(driver,
                        IMPLICIT_WAIT,
                        TimeUnit.SECONDS),
                this
        );
    }

    @AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"com.wholefoods.wholefoodsmarket:id/tvFavOrangeBubble\")")
    private MobileElement myFavoritesCountLabel;

    public String getMyFavoritesLabel() {
        return myFavoritesLabel.getText();
    }

    public String getMyFavoritesCountLabel() {
        return myFavoritesCountLabel.getText();
    }
}
```

**Comment by TikhomirovSergey** [comment]
ok. Now it is clear. Is your app hybrid? Appium-specific annotations were designed for native contents. What does return .getContext() method before your test is failed?

**Comment by justintilson** [comment]
System.out.println(driver.getContext()); 

prints: **NATIVE_APP**

**Comment by TikhomirovSergey** [comment]
Ok. Is it possible that your project still depending on java_client 2.2.0 or lower? Please look at your dependencies hierarchy.

**Comment by justintilson** [comment]
I thought that might have had something to do with it so I upgraded yesterday. Here is my build.gradle file:
```
dependencies {
    testCompile 'org.testng:testng:6.8.21'
    testCompile 'org.seleniumhq.selenium:selenium-java:2.46.0'
    testCompile 'io.appium:java-client:3.0.0'
    testCompile 'com.google.code.gson:gson:2.3.1'
    testCompile 'org.json:json:20140107'
    testCompile 'org.apache.httpcomponents:httpclient:4.3.6'
    testCompile 'net.sf.opencsv:opencsv:2.3'
}
```

and the gradle cache:

![gradle-cache](https://cloud.githubusercontent.com/assets/1480031/8466282/e6ae33ee-201e-11e5-8a96-f532416440be.png)

**Comment by TikhomirovSergey** [comment]
Ok. It seems I've found the cause of problem

> Capabilities [{networkConnectionEnabled=true, desired={}, platformVersion=4.4.4, warnings={}, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, databaseEnabled=false, deviceName=192.168.56.101:5555, platform=LINUX}]

Why platform is Linux? Is it passed via capabilities 

```java
new AndroidDriver(URL, capabilities)
```
?

Can you change it to Android/IOS?

**Comment by TikhomirovSergey** [comment]
![androidcaps](https://cloud.githubusercontent.com/assets/4927589/8466438/643dfb0a-205b-11e5-9ece-4609fb071cfd.png)

And when you are running

>System.out.println(driver.getCapabilities().toString());

it prints 

> Capabilities [{networkConnectionEnabled=true, desired={}, platformVersion=4.4.4, warnings={}, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, databaseEnabled=false, deviceName=192.168.56.101:5555, platform=LINUX}]

Am I right?

**Comment by TikhomirovSergey** [comment]
Ok. I have two things to say.
The first is it is my fault that I forgot to improve this:
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java#L74
It is autdated thing from times when there weren't AndroidDriver/IOSFriver (there was only AppiumDriver). I can change it and propese PR soon.

The second. If I am right then there is the strange difference between given and printed capabilities. The absence of "platform" parameter causes your problem.

**Comment by justintilson** [comment]
I've messing around. I changed the 'platformName' desired capability to 'platform' with no difference. 

Here are the desired capabilities passed into the AndroidDriver:

![dcs-passed-to-android-driver2](https://cloud.githubusercontent.com/assets/1480031/8466941/2e591716-2026-11e5-81a1-568d2d51d6b0.png)

and this is how they read after the driver has been instantiated:

![dcs-read-from-driver-after-instantiation](https://cloud.githubusercontent.com/assets/1480031/8466944/3d4dbcb8-2026-11e5-95c8-99f5d3b810b0.png)

I'm not sure where LINUX is coming from but it's not something I seem to be able to control.

**Comment by TikhomirovSergey** [comment]
Ok. The outdated code will be improved today (I'm going to propose a PR). 

Also it seems that there is another problem. I can't figure out how Appium desktop transforms capabilities.  Appium java_client sets the required platform in capabilities when itstantiates desired driver... It seems that you are facing this problem: https://github.com/appium/appium/issues/4091

Actually don't use Appium desctop app. I usually use server that is installed via npm. For now I can suggest you to do the same.

**Comment by justintilson** [comment]
I tried switching to node server (instead of Appium.app) and got the same results. It's still trying to use the property name of the page object to find elements instead of using the values provided in the annotations.

**Comment by TikhomirovSergey** [comment]
@justintilson The PR is proposed and now it is waiting for the merging.

**Comment by justintilson** [comment]
@TikhomirovSergey - thanks for the update and your speedy fix. How long is typical for a merge? Our tiny team of two is somewhat blocked by this issue.

**Comment by TikhomirovSergey** [comment]
It is depending on @Jonahss

**Comment by Jonahss** [comment]
@justintilson merged!
Are you ok compiling on your own from this repo? Or would you prefer we do a full release to the Maven Central Repository?

**Comment by justintilson** [comment]
@Jonahss - our current gradle build script pulls from the Maven repo. I could probably tweak it to download the source and compile it if you weren't planning to do a release for a while. If it's relatively effortless to do a release, that would accelerate things on my side.

**Comment by Jonahss** [comment]
@justintilson Yeah I can do a release :)
It's relatively effortless compared to gardening in my backyard. But is an incredible amount of effort compared to using npm :P

I'll start running the test suite now.

**Comment by Jonahss** [comment]
@justintilson Ok, released version 3.1.0

**Comment by justintilson** [comment]
It works! I tested on both Android and iOS. @TikhomirovSergey, @Jonahss Thanks so much for moving this issue through so quickly!

**Comment by Jonahss** [comment]
Yay!

**Comment by TikhomirovSergey** [comment]
I'm happy :)

**Comment by umaralikhan** [comment]
one question. Do I need to change the context of the driver before I try to locate webview elements (hybrid app - like FB login) by using Page Objects/Factory as mentioned above?

FindBy(locator_for_HTML)//this locator is used when here mobile 
//or desktop browser or webview
 private WebElement myFavoritesCountLabel;
