### ISSUE TITLE
Unable to execute javascript with Appium 1.3.4 & javaclient 2.2.0 for Android native context

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#212]
Hi,

I am not able to execute javascript on native android elements....

public static void highlightElement(WebElement element, AppiumDriver driver2) { 
			for (int i = 0; i <2; i++) { 
				JavascriptExecutor js = (JavascriptExecutor) driver2; 
				js.executeScript("arguments[0].setAttribute('style', arguments[1]);", element, "border: 4px solid Red;"); 
				js.executeScript("arguments[0].setAttribute('style', arguments[1]);", element, ""); 
			} 
	}

highlightElement(driver.findElementById("in.amazon.mShop.android.shopping:id/web_home_shop_by_department_label"),driver);

Appium error logs
> info: [debug] [BOOTSTRAP] [debug] Finding in.amazon.mShop.android.shopping:id/web_home_shop_by_department_label using ID with the contextId: multiple: false 
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=in.amazon.mShop.android.shopping:id/web_home_shop_by_department_label]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0} 
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"d0253515-b3c8-49e6-a4f1-0fc7eb3ca111"} 
> info: <-- POST /wd/hub/session/d0253515-b3c8-49e6-a4f1-0fc7eb3ca111/element 200 1284.329 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"d0253515-b3c8-49e6-a4f1-0fc7eb3ca111"} 
> info: --> POST /wd/hub/session/d0253515-b3c8-49e6-a4f1-0fc7eb3ca111/execute {"script":"arguments[0].setAttribute('style', arguments[1]);","args":[{"ELEMENT":"1"},"border: 4px solid Red;"]} 
> info: [debug] Responding to client that a method is not implemented

**Comment by Jonahss** [comment]
Yeah, you can't execute javascript on native android elements. Android uses Java afterall, so building a javascript interpreter and building an api to interact with native elements isn't really in the scope of the appium project.
Plus there's no way to set attributes of native elements in android UIAutomator.

**Comment by amitjaincoer191** [comment]
Sorry for raising this invalid issue. Thanks for quick reply. Really appreciated your help

**Comment by Jonahss** [comment]
It's ok :) An easy misunderstanding if you don't know how appium works internally, which of course we can't expect everybody to understand right away ;)

**Comment by Xebia-Sumit-Soman** [comment]
Hi Jonahss,

Can we setAttribute for a UIStaticText by using javascript executor in an IOS native app.
I tried running same command used in Webdriver to setAttribute but it doesnt work on IOS native app.

Reply will be highly appreciated.!!

**Comment by thamizhkumarana** [comment]
Hi Jonahss,
Is there any way to set the new attribute to an element in webview (android/ios).

thanks,
Thamizh

**Comment by jenniferhuang** [comment]
The same requirement:
Can we setAttribute for a UIStaticText for ios app
