### ISSUE TITLE
The import io.appium.java_client.android.AndroidElement cannot be resolved

### ISSUE THREAD

**Issue by ak270296** [appium/java-client#2126]
getting above error while importing manually for AndroidElemnet. 
AndroidElement element = (AndroidElement) wait.until(ExpectedConditions.elementToBeClickable(driver.findElement(By.id("idtext"))));

Specification of project:
project: cucumber
java: 11
selenium-java: 4.11.0
java-client: 8.3.0

**Comment by valfirst** [comment]
https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#mobileelement
