### ISSUE TITLE
How to start an Activity using mobile: startActivity with OptionalIntentArguments? 

### ISSUE THREAD

**Issue by cmccarthyIrl** [appium/java-client#2127]
## Description

After updating my Appium dependency to version 9.1.0, I am no longer able to use ((AndroidDriver) driver).startActivty(activity)

## Environment

* Java client build version: 9.1.0
* Appium server version: 2.4.1
* Desktop OS/version used to run Appium if necessary: Mac Ventura 13.5.2
* Mobile platform/version under test: Android 12
* Real device or emulator/simulator: Real device

## Details

With Appium version 8.5.1, I was able to start my Android Activity using the following approach: 

  Activity activity = new Activity("com.android.settings", ".applications.InstalledAppDetails")
      .setOptionalIntentArguments("package:com.android.chrome");
  ((AndroidDriver) DriverManager.getDriver()).startActivity(activity);

How can I launch the `package:com.android.chrome activity` using `mobile: startActivity` ?

**Comment by valfirst** [comment]
@cmccarthyIrl please check https://github.com/appium/java-client/blob/master/docs/v8-to-v9-migration-guide.md#removed-previously-deprecated-items

**Comment by mmajcherczyk** [comment]
in kotlin 
```
        fun startActivity() {
            androidDriver!!.executeScript(
                "mobile: startActivity",
                mapOf(
                    "intent" to APP_PACKAGE + "/" + APP_ACTIVITY,
                    "stop" to "true"
                )
            )
        }
```

**Comment by eglitise** [comment]
You can also find example usage for any mobile extension command for UiAutomator2 [in its readme here](https://github.com/appium/appium-uiautomator2-driver#platform-specific-extensions).

**Comment by cmccarthyIrl** [comment]
Thanks @valfirst , @eglitise  - I'm following those examples but I'm not able to open the Chrome package in Settings. I can get the Settings app to open on the device but not the `Settings > Apps > Chrome` package as expected 

**Approach 1** 
` 
String[][] arrayOfArrays = {
   {"s", "package", "com.android.chrome"}
};
      
driver.executeScript("mobile: startActivity", ImmutableMap.of("intent", "com.android.settings/.applications.InstalledAppDetails", "wait", true, "extras",arrayOfArrays));
`

**Approach 2** 
`
driver.executeScript("mobile: startActivity", ImmutableMap.of("intent", "com.android.settings/.applications.InstalledAppDetails", "wait", true,"package", "com.android.chrome"));
`

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/18589910/android-launch-app-info-dialog-via-adb-shell-am

**Comment by cmccarthyIrl** [comment]
Thanks @mykola-mokhnach, I got it working with the following

```java
driver.executeScript("mobile: startActivity",
          ImmutableMap.of( "action", "android.settings.APPLICATION_DETAILS_SETTINGS", "uri",
              "package:com.android.chrome"));
```

**Comment by cmccarthyIrl** [comment]
Thanks @mykola-mokhnach, I got it working with the following

```java
driver.executeScript("mobile: startActivity",
          ImmutableMap.of( "action", "android.settings.APPLICATION_DETAILS_SETTINGS", "uri",
              "package:com.android.chrome"));
```
