### ISSUE TITLE
Use Gradle to build instead of Maven

### ISSUE THREAD

**Issue by Jonahss** [appium/java-client#214]
suggested by @bootstraponline to align with other Android and Appium projects. Maven is unsupported by Google.

**Comment by bootstraponline** [comment]
> Important: Support for the Android Developer Tools (ADT) in Eclipse is ending, per our announcement. You should migrate your app development projects to Android Studio as soon as possible. For more information on transitioning to Android Studio, see Migrating to Android Studio.
>
> https://developer.android.com/tools/help/adt.html

**Comment by Jonahss** [comment]
I use intellij. That all right?

**Comment by bootstraponline** [comment]
Android Studio is built on Intellij so Intellij has excellent gradle support.

**Comment by Jonahss** [comment]
:+1:

**Comment by aniket-21** [comment]
I am using intellij, I can look into this one

**Comment by aniket-21** [comment]
Was trying to get my fork running with Gradle and having a hard time compiling this List<RequiredElementType> 

I get the below error
javaclient\java-client\src\main\java\io\appium\java_client\AppiumDriver.java:84: error: findElements(By) in AppiumDriver cannot implement findElements(By) in WebDriver
	public List<RequiredElementType> findElements(By by){
	                                 ^
  return type List<RequiredElementType> is not compatible with List<WebElement>
  where RequiredElementType is a type-variable:
    RequiredElementType extends WebElement declared in class AppiumDriver

I tried typecasting return value to List<RequiredElementType> with no luck

**Comment by aniket-21** [comment]
javaclient\java-client\src\main\java\io\appium\java_client\AppiumDriver.java:84: error: findElements(By) in AppiumDriver cannot implement findElements(By) in WebDriver
	public List< RequiredElementType > findElements(By by){
	                                 ^
  return type List< RequiredElementType > is not compatible with List< WebElement >
  where RequiredElementType is a type-variable:
    RequiredElementType extends WebElement declared in class AppiumDriver

**Comment by aniket-21** [comment]
@Jonahss @TikhomirovSergey , Gradle uses javac and it seems it is pretty stringent than eclipse or intellij compilers when it comes to Generics. I am not sure if there can be a workaround to overcome this w/o make code changes around handling generics

Per error even if RequiredElementType extends WebElement, it doesn't translate into List<RequiredElementType > extends List<WebElement >
and hence the declaration of overridden method is invalid as per the compiler

**Comment by TikhomirovSergey** [comment]
@aniket-21 Sorry for my late responce Too busy.
The fix is here:
https://github.com/SeleniumHQ/selenium/pull/863
We need the Selenium version with these changes. Also I'll try to find a way to avoid this problem with Gradle.

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/issues/220

**Comment by aniket-21** [comment]
Thanks @TikhomirovSergey , It would be good to have the implementation changes at Selenium end rather than forcing the compilers to accept current one with warnings :)

**Comment by TikhomirovSergey** [comment]
Was implemented at #442 #465. @aniket-21 Please wait for v5.0.0
