### ISSUE TITLE
add /status, /sessionId and /sessions methods

### ISSUE THREAD

**Issue by Jonahss** [appium/java-client#215]
These methods are super useful, but the selenium project doesn't think they belong in a driver client and are only for selenium grid.

I'm fine with adding them to this client though :)

**Comment by saikrishna321** [comment]
i have picked this, will send a PR soon with /sessions and /status.

**Comment by SrinivasanTarget** [comment]
Cool

**Comment by Jonahss** [comment]
Oh super cool.
