### ISSUE TITLE
Not able to switch on webview.

### ISSUE THREAD

**Issue by iabhay** [appium/java-client#216]
Android or iOS: Android 4.4.2
Platform version: Windows
Real device or emulator/simulator: Real device
Scenario:
1.User open the App.
2.Click on Bus on product listing.
3.Enter required information.
4..Click on search bus.
5.Result page is display that is webview.

On this page i am getting only Native View not web view.

I have attached the code.You can run the code just right click on sanitytest_testng.xml and run as test ng.
App is under APK folder.

code location :
https://drive.google.com/file/d/0B0QUsT7aTHwCcm5TQVdUTWhNNkE/view?usp=sharing

**Comment by Fanch-** [comment]
Same for gmail app, I see webviews when I try to read a mail; in page source, but with getcontexthandles() I detect only Native View. I haven't upgrade to appium 1.4.7/java-client 3.1.0 though, so I will post again after upgrading to give a feedback.

There is something funny about that : sometimes using native selectors in gmail webviews, it works. And sometimes I just can't access to these elements in webviews, but the webviews aren't also reachable in this case (still only Native View). It might be a google specificity, I don't know : what about "//android.webkit.WebView/android.view.View[@index='1']" ? Am I right to think that must be a webview?

**Comment by Jonahss** [comment]
Ok, looking forward to what you find after upgrading.

It's possible that complex apps like gmail are doing things that we haven't tested before, so we might have to experiment.

Remember that appium's designed use-case is for testing _your own_ apps .....

**Comment by amitjaincoer191** [comment]
@ abhay,

I checked by installing your app and you are right that page is under webview ...
For webview to be detected by appium below are prerequisites
 - apk with setWebContentsDebuggingEnabled flag set to true,
 - API level of device >=19
Are you sure your android developer had set this flag to true, kindly confirm ?
Also ask your developer to once build the app for android version 4.4.4 or above

**Comment by Fanch-** [comment]
I have upgraded, and the funny thing is at my first launching I detected every webviews (gmail). But after it; it went in the previous state, where only Native Context was detected.

I thing yeah the webview detection is more robust, but it seems apps like gmail, facebook have some intern modification.

For gmail it might transform webviews in native elements, but this behavior doesn't seem consistent, sometimes we just don't have access to DOM in webviews. Google check to slow crawler? 

>  "Remember that appium's designed use-case is for testing your own apps ....."

Well, for now use mail app is the only way to open links which permit to open the app. For validation account and redirection on app, etc .... There are some scenarii which need to pass by email step.

**Comment by amitjaincoer191** [comment]
@Fanch- 
But issue raised by abhay is related to Android app and not iOS app. In Android app webview gets detected if mentioned property is on and we can also inspect webview using chrome remote debugger

In case of iOS webview might be handled different way ....

**Comment by Fanch-** [comment]
Well he said iOS or Android.

From doc (hybrid apps) : 
>There is a bit of technical complexity required so that Appium knows whether you want to automate the native aspects of the app or the web views (...)

@amitjaincoer191 You said : 
>In Android app webview gets detected if mentioned property

Does that mean we can automate webviews in native context and **also** from webview context (switching on it or the capability with auto-switch) using chrome remote debugger? I thought we had to switch to webview context to automate it, that's why I'm asking. The doc isn't really clear about it.

jlipps said : 
>I think that the only solution here is to provide a capability that turns searching through webviews natively back on. It will make people's tests slower but it will allow them to have native access to certain webview elements.

He also said that UiAutomation (iOS) does give native access to some webview elements. So I was wondering if it was the case for UiAutomator (Android) too. Because from what I see on gmail app, it seems to be the case, nevertheless the DOM in gmail webviews isn't available sometimes.

from jlipps again : 
>But because UIAutomation gives access to these elements, sometimes there are so many (say in the case of a big webpage), that we rule them out from search to make searches take a reasonable amount of time.

I thought it could have be that there were sometimes too many mails on activity, so too many webviews/web pages. Or google intern modification, because the webviews were detected only at the first launching. I don't know, need other feedbacks.

**Comment by jlipps** [comment]
All of my comments were about iOS so I don't think they apply here

**Comment by Fanch-** [comment]
Then I guess by default gmail app doesn't allow WebContentsDebugging.

**Comment by Fanch-** [comment]
One more comment : it seems it detects the webView (still speaking about gmail) everytime on LG_G3, but never with for example Samsung_Galaxy_S5 or Samsung_Galaxy_Note3.

**Comment by saikrishna321** [comment]
@TikhomirovSergey inactive defect, can this be closed?
