### ISSUE TITLE
IOSFindBy  & AndroidFindBy with parametrs

### ISSUE THREAD

**Issue by rutin31** [appium/java-client#2168]
How to set selector with parameters
on appium C# client

for example:

[AndroidFindBy(XPath="android.widget.Text[contains(@text("user Name+xxx"))]")
[IOSFindBy(AccessibilityId="userName+xxx")]
private MobileElement userNameSelector;

where xxx - parameter  that can change
how to call to this selector from test?

**Comment by eglitise** [comment]
Please use [Appium forum](https://discuss.appium.io/) to ask questions.
