### ISSUE TITLE
File pushed to mobile device using pushFile method cannot be viewed in device/windows BUT these file get's listed using adb

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#218]
I pushed a image and a text file using pushFile method of java client on my sdcard location
/storage/sdcard1/User

But I cannot see the pushed files 
  >>>  When I open the above directory into my mobile using fileExplorer app
  >>>> When I connect my mobile to windows machine and I navigate to above directory

>>> I cannot only view the listing of my file using adb shell cd /storage/sdcard1/User

shell@condor_umtsds:/storage/sdcard1/User $ ll
-rwxrwx--- root     sdcard_r    54960 2015-07-17 18:53 img1.jpg
-rwxrwx--- root     sdcard_r   334126 2015-04-18 16:45 ticket.png

My Code :
                 @Test
		  public void pushImageFileFromMobileTest() throws IOException {
			  File fi = new File("C:\\eclipse\\img1.jpg");
			  byte[] fileContent = Files.readAllBytes(fi.toPath());
            _driver.pushFile("/storage/sdcard1/User/img1.jpg", fileContent);          
		  }

Similarly happens with text file ....

I am not sure but what I feel issue may be is that files are not decoded to Base64 before copying to device....

**Comment by amitjaincoer191** [comment]
Appium Logs

> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV install "C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "dumpsys window"
> info: Unlocking screen
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "dumpsys window"
> info: [debug] Screen is unlocked, continuing
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.android.apis/ApiDemos"
> info: [debug] We tried to start an activity that doesn't exist, retrying with . prepended to activity
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.android.apis/.ApiDemos"
> info: [debug] Waiting for pkg "io.appium.android.apis" and activity "ApiDemos" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "dumpsys window windows"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 4e356329-c07b-4c0d-a976-8d3c2af9c48c
> info: <-- POST /wd/hub/session 303 12586.253 ms - 9 
> info: --> GET /wd/hub/session/4e356329-c07b-4c0d-a976-8d3c2af9c48c {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformVersion":"4.4.2","platformName":"Android","deviceName":"emulator-5554","browserName":"","appActivity":"ApiDemos","appPackage":"io.appium.android.apis"},"platformName":"Android","deviceName":"emulator-5554","appActivity":"ApiDemos","appPackage":"io.appium.android.apis"},"sessionId":"4e356329-c07b-4c0d-a976-8d3c2af9c48c"}
> info: <-- GET /wd/hub/session/4e356329-c07b-4c0d-a976-8d3c2af9c48c 200 2.072 ms - 599 {"status":0,"value":{"platform":"LINUX","browserName":"","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformVersion":"4.4.2","platformName":"Android","deviceName":"emulator-5554","browserName":"","appActivity":"ApiDemos","appPackage":"io.appium.android.apis"},"platformName":"Android","deviceName":"emulator-5554","appActivity":"ApiDemos","appPackage":"io.appium.android.apis"},"sessionId":"4e356329-c07b-4c0d-a976-8d3c2af9c48c"}
> info: --> POST /wd/hub/session/4e356329-c07b-4c0d-a976-8d3c2af9c48c/appium/device/push_file {"path":"/storage/sdcard1/User/img1.jpg","data":[-1,-40,-1,-32,0,16,74,70,73,70,0,1,2,0,0,100,0,100,0,0,-1,-20,0,17,68,117,99,107,121,0,1,0,4,0,0,0,80,0,0,-1,-30,12,88,73,67,67,95,80,82,79,70,73,76,69,0,1,1,0,0,12,72,76,105,110,111,2,16,0,0,109,110,116,114,82,71,66,32,88,89,90,32,7,-50,0,2,0,9,0,6,0,49,0,0,97,99,115,112,77,83,70,84,0,0,0,0,73,69,67,32,115,82,71,66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-10,-42,0,1,0,0,0,0,-45,45,72,80,32,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,99,112,114,116,0,0,1,80,0,0,0,51,100,101,115,99,0,0,1,-124,0,0,0,108,119,116,112,116,0,0,1,-16,0,0,0,20,98,107,112,116,0,0,2,4,0,0,0,20,114,88,89,90,0,0,2,24,0,0,0,20,103,88,89,90,0,0,2,44,0,0,0,20,98,88,89,90,0,0,2,64,0,0,0,20,100,109,110,100,0,0,2,84,0,0,0,112,100,109,100,100,0,0,2,-60,0,0,0,-120,118,117,101,100,0,0,3,76,0,0,0,-122,118,105,101,119,0,0,3,-44,0,0,0,36,108,117,109,105,0,0,3,-8,0,0,0,20,109,101,97,115,0,0,4,12,0,0,0,36,116,101,99,104,0,0,4
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV push "C:\\Users\\amit.ja\\AppData\\Local\\Temp\\appium115617-8964-5djnno.tmp" /storage/sdcard1/user/img1.jpg
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"4e356329-c07b-4c0d-a976-8d3c2af9c48c"}
> info: <-- POST /wd/hub/session/4e356329-c07b-4c0d-a976-8d3c2af9c48c/appium/device/push_file 200 504.049 ms - 74 {"status":0,"value":"","sessionId":"4e356329-c07b-4c0d-a976-8d3c2af9c48c"}
> info: --> DELETE /wd/hub/session/4e356329-c07b-4c0d-a976-8d3c2af9c48c {}
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s BX1136HGHV shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 8.139
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"4e356329-c07b-4c0d-a976-8d3c2af9c48c"}
> info: <-- DELETE /wd/hub/session/4e356329-c07b-4c0d-a976-8d3c2af9c48c 200 1201.758 ms - 76 {"status":0,"value":null,"sessionId":"4e356329-c07b-4c0d-a976-8d3c2af9c48c"}

**Comment by amitjaincoer191** [comment]
I am using java-client 3.1

**Comment by amitjaincoer191** [comment]
Actual logs of all push and pull method

> info: --> POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/pull_file {"path":"/storage/sdcard1/User/IMG_20140828_072840.jpg"}
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s aadB32374D pull /storage/sdcard1/User/IMG_20140828_072840.jpg "C:\\Users\\amit.ja\\AppData\\Local\\Temp\\appium115617-8684-1ltzbry.tmp"
> info: [debug] Responding to client with success: {"status":0,"value":"/9j/4QBURXhpZgAATU0AKgAAAAgAAwESAAMAAAABAAEAAIdpAAQAAAABAAAARgEyAAIAAAAUAAAAMgAAAAAyMDE0OjA4OjI4IDA3OjI4OjQyAAAAAAAAAP/gABBKRklGAAEBAAABAAEAAP/bAEMAAwICAwICAwMDAwQDAwQFCAUFBAQFCgcHBggMCgwMCwoLCw0OEhANDhEOCwsQFhARExQVFRUMDxcYFhQYEhQVFP/bAEMBAwQEBQQFCQUFCRQNCw0UFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFP/AABEIBcsEYQMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APyqooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoooo...","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: <-- POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/pull_file 200 691.461 ms - 690970 {"status":0,"value":"/9j/4QBURXhpZgAATU0AKgAAAAgAAwESAAMAAAABAAEAAIdpAAQAAAABAAAARgEyAAIAAAAUAAAAMgAAAAAyMDE0OjA4OjI4IDA3OjI4OjQyAAAAAAAAAP/gABBKRklGAAEBAAABAAEAAP/bAEMAAwICAwICAwMDAwQDAwQFCAUFBAQFCgcHBggMCgwMCwoLCw0OEhANDhEOCwsQFhARExQVFRUMDxcYFhQYEhQVFP/bAEMBAwQEBQQFCQUFCRQNCw0UFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFP/AABEIBcsEYQMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APyqooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoooo...","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: --> POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/pull_file {"path":"/storage/sdcard1/mili_log.txt"}
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s aadB32374D pull /storage/sdcard1/mili_log.txt "C:\\Users\\amit.ja\\AppData\\Local\\Temp\\appium115617-8684-1pyjbri.tmp"
> info: [debug] Responding to client with success: {"status":0,"value":"MjAxNS0wNi0xOSAxMDo0ODozMS44NDcgIEJyYWNlbGV0QXBwICBub3QgbG9naW4gdWlkOi0xCjIwMTUtMDYtMTkgMTA6NDg6MzEuODUwICBCcmFjZWxldEFwcCAgdWlkOi0xLEJhc2ljU2VydmVyRGVmLlVTRV9IT1NUX09WRVJTRUFTOmZhbHNlCjIwMTUtMDYtMTkgMTA6NDg6MzIuMDU5ICBEYXRhTWFuYWdlciAgaW4gaW5pdERheXMKMjAxNS0wNi0xOSAxMDo0ODozMi4wNjIgIERhdGFNYW5hZ2VyICBvdXQgaW5pdERheXMKMjAxNS0wNi0xOSAxMDo0ODozMy4yODYgIFV0aWxzICAKZGV2aWNlSWQ6IDM1OTI5OTA1NjIwMDY3MwpzZXJpYWxOdW06IDg5OTExMTAwMTgyMDI5NTkzODQyCmFuZHJvaWRJZDogNDBlOGRkMDhkYWU2OTlmNAptYWNBZGRyZXNzOiAwODowMDowMDo0Nzo0RDozNQp1dWlkOmZmZmZmZmZmLWZmNmQtZGI3Ny1mZmZmLWZmZmZmZmI2ZmY5ZQoyMDE1LTA2LTE5IDEwOjQ4OjMzLjQwNyAgU2Vuc29ySHViQ29udHJvbGxlciAgU2Vuc29ySHViSW5mbzoKdHlwZTotMQp1c2VUaW1lc3RhbXA6LTEoVGh1IEphbiAwMSAwNToyOTo1OSBJU1QgMTk3MCkKc3luY1RpbWVzdGFtcDotMShUaHUgSmFuIDAxIDA1OjI5OjU5IElTVCAxOTcwKQpiYXNlU3RlcDotMQoyMDE1LTA2LTE5IDEwOjQ4OjMzLjQyNCAgTWl1aUFQSSAgaW5pdAoyMDE1LTA2LTE5IDEwOjQ4OjMzLjY0NSAgTWl1aUFQSSAgTWlCbGVEZXZpY2VNYW5hZ2VyIG9uRGVzdHJveSEKMjAxNS0wNi0xOSAxMToxNDoyMS4yODggIEJMRVNlcnZpY2UgIHRvcEFj...","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: <-- POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/pull_file 200 245.414 ms - 1158 {"status":0,"value":"MjAxNS0wNi0xOSAxMDo0ODozMS44NDcgIEJyYWNlbGV0QXBwICBub3QgbG9naW4gdWlkOi0xCjIwMTUtMDYtMTkgMTA6NDg6MzEuODUwICBCcmFjZWxldEFwcCAgdWlkOi0xLEJhc2ljU2VydmVyRGVmLlVTRV9IT1NUX09WRVJTRUFTOmZhbHNlCjIwMTUtMDYtMTkgMTA6NDg6MzIuMDU5ICBEYXRhTWFuYWdlciAgaW4gaW5pdERheXMKMjAxNS0wNi0xOSAxMDo0ODozMi4wNjIgIERhdGFNYW5hZ2VyICBvdXQgaW5pdERheXMKMjAxNS0wNi0xOSAxMDo0ODozMy4yODYgIFV0aWxzICAKZGV2aWNlSWQ6IDM1OTI5OTA1NjIwMDY3MwpzZXJpYWxOdW06IDg5OTExMTAwMTgyMDI5NTkzODQyCmFuZHJvaWRJZDogNDBlOGRkMDhkYWU2OTlmNAptYWNBZGRyZXNzOiAwODowMDowMDo0Nzo0RDozNQp1dWlkOmZmZmZmZmZmLWZmNmQtZGI3Ny1mZmZmLWZmZmZmZmI2ZmY5ZQoyMDE1LTA2LTE5IDEwOjQ4OjMzLjQwNyAgU2Vuc29ySHViQ29udHJvbGxlciAgU2Vuc29ySHViSW5mbzoKdHlwZTotMQp1c2VUaW1lc3RhbXA6LTEoVGh1IEphbiAwMSAwNToyOTo1OSBJU1QgMTk3MCkKc3luY1RpbWVzdGFtcDotMShUaHUgSmFuIDAxIDA1OjI5OjU5IElTVCAxOTcwKQpiYXNlU3RlcDotMQoyMDE1LTA2LTE5IDEwOjQ4OjMzLjQyNCAgTWl1aUFQSSAgaW5pdAoyMDE1LTA2LTE5IDEwOjQ4OjMzLjY0NSAgTWl1aUFQSSAgTWlCbGVEZXZpY2VNYW5hZ2VyIG9uRGVzdHJveSEKMjAxNS0wNi0xOSAxMToxNDoyMS4yODggIEJMRVNlcnZpY2UgIHRvcEFj...","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: --> POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/push_file {"path":"/storage/sdcard1/User/img1.jpg","data":[-1,-40,-1,-32,0,16,74,70,73,70,0,1,2,0,0,100,0,100,0,0,-1,-20,0,17,68,117,99,107,121,0,1,0,4,0,0,0,80,0,0,-1,-30,12,88,73,67,67,95,80,82,79,70,73,76,69,0,1,1,0,0,12,72,76,105,110,111,2,16,0,0,109,110,116,114,82,71,66,32,88,89,90,32,7,-50,0,2,0,9,0,6,0,49,0,0,97,99,115,112,77,83,70,84,0,0,0,0,73,69,67,32,115,82,71,66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-10,-42,0,1,0,0,0,0,-45,45,72,80,32,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,99,112,114,116,0,0,1,80,0,0,0,51,100,101,115,99,0,0,1,-124,0,0,0,108,119,116,112,116,0,0,1,-16,0,0,0,20,98,107,112,116,0,0,2,4,0,0,0,20,114,88,89,90,0,0,2,24,0,0,0,20,103,88,89,90,0,0,2,44,0,0,0,20,98,88,89,90,0,0,2,64,0,0,0,20,100,109,110,100,0,0,2,84,0,0,0,112,100,109,100,100,0,0,2,-60,0,0,0,-120,118,117,101,100,0,0,3,76,0,0,0,-122,118,105,101,119,0,0,3,-44,0,0,0,36,108,117,109,105,0,0,3,-8,0,0,0,20,109,101,97,115,0,0,4,12,0,0,0,36,116,101,99,104,0,0,4
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s aadB32374D push "C:\\Users\\amit.ja\\AppData\\Local\\Temp\\appium115617-8684-gl03cv.tmp" /storage/sdcard1/User/img1.jpg
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: <-- POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/push_file 200 240.337 ms - 74 {"status":0,"value":"","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: --> POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/push_file {"path":"/storage/sdcard1/User/appium.txt","data":[82,83,52,103,86,121,52,103,82,71,108,113,97,51,78,48,99,109,69,61]}
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s aadB32374D push "C:\\Users\\amit.ja\\AppData\\Local\\Temp\\appium115617-8684-t8prsh.tmp" /storage/sdcard1/User/appium.txt
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: <-- POST /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12/appium/device/push_file 200 285.512 ms - 74 {"status":0,"value":"","sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: --> DELETE /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12 {}
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s aadB32374D shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 8.306
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}
> info: <-- DELETE /wd/hub/session/2838237c-f517-489e-9e26-3fc1bddc5a12 200 1179.797 ms - 76 {"status":0,"value":null,"sessionId":"2838237c-f517-489e-9e26-3fc1bddc5a12"}

**Comment by Jonahss** [comment]
I think that might just be an android permissions thing. The onboard file browser is pretty limited in what it will display. If adb says it's there, it's there.

**Comment by amitjaincoer191** [comment]
But I have a question when I push a file to a device then, appium copy file in Base64encoded format
E.g. I pushed a text file to a device then appium pushes it, but when I print the file using adb it displays me a base64 encoded string inside file, if I decode it from base64 using any online service , then it displays the text inside file which I really pushed to device.

when I push file manually using below command it works fine
adb push <localPath> <remotePath>

**Comment by amitjaincoer191** [comment]
Hi All,

Any updates on this. I can give example also that in API Demo's apk the unit test case which is written is creating is sending a text string to a mobile device. Now one that text is pushed to appium it is getting stored in a tmp file , if I print that text file it does not print what we sent . Please look into this.

 @Test
  public void pushFileTest() {
    byte[] data = Base64.encodeBase64("The eventual code is no more than the deposit of your understanding. ~E. W. Dijkstra".getBytes());
    driver.pushFile("/data/local/tmp/remote.txt", data);
    byte[] returnData = driver.pullFile("/data/local/tmp/remote.txt");
    String returnDataDecoded = new String(Base64.decodeBase64(returnData));
    assertEquals("The eventual code is no more than the deposit of your understanding. ~E. W. Dijkstra", returnDataDecoded);
  }


Thanks
Amit

**Comment by Jonahss** [comment]
So uh, the test is encoding the text as Base64. The `pushFile()` method takes any byte array `byte[]` and saves it to the device. If you want to save a string in standard utf-8 encoding to the device, you can do it like this:

```
@Test
  public void pushFileTest() {
    String str = "The eventual code is no more than the deposit of your understanding. ~E. W. Dijkstra";
    byte[] data = str.getBytes(Charset.forName("UTF-8"));
    driver.pushFile("/data/local/tmp/remote.txt", data);
    byte[] returnData = driver.pullFile("/data/local/tmp/remote.txt");
    String returnDataDecoded = new String(returnData, StandardCharsets.UTF_8);
    assertEquals("The eventual code is no more than the deposit of your understanding. ~E. W. Dijkstra", returnDataDecoded);
  }
```

If you are having trouble with pushing the file you read, try just saving it to your local computer and see if it is working there, then try appium.
