### ISSUE TITLE
Long Press KeyCode on java client ?

### ISSUE THREAD

**Issue by jalexis** [appium/java-client#219]
I need to perform a long press on KEYCODE_SOFT_LEFT on android. This feature is supported on python client through long_press_keycode(), but I can't find any way to do it in java. I can only perform a long press on an element through TouchAction#longPress(), or a simple press on key using sendKeyEvent().

**Comment by Jonahss** [comment]
Oh cool. Yeah that sounds like a feature we should support.

**Comment by TikhomirovSergey** [comment]
Is already included
