### ISSUE TITLE
How to continue execution even after the step failed in cucumber 7.18.0

### ISSUE THREAD

**Issue by ak270296** [appium/java-client#2194]
I am using cucumber 7.18.0 with selenium java here if the step fails in the test case the execution of the next steps does not continue. So I want to mark the failed step as failed and continue the execution. This logic exists in my old project where I use info.cukes dependencies.

dependencies used in pom.xml:
junit-jupiter-engine = 5.10.2
junit-jupiter-api = 5.10.3
junit-platform-suite = 1.10.2
junit-platform-suite-api = 1.10.2
cucumber-junit-platform-engine = 7.18.0
cucumber-java = 7.18.0
cucumber-core = 7.18.0
selenium-java = 4.11.0

**Comment by itkhanz** [comment]
I don't see how Appium is related to this from your problem description and dependencies, hence I conclude that this issue is not relevant to Appium. Please open the issue in relevant project.
