### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.findElement(org.openqa.selenium.By)" because "this.driver" is null

### ISSUE THREAD

**Issue by bejaoui13** [appium/java-client#2224]
base.java

package appTest;

import org.testng.annotations.BeforeClass;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeClass;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import io.appium.java_client.pagefactory.AppiumFieldDecorator;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import io.appium.java_client.service.local.AppiumServiceBuilder;

public class Base {

 	public AppiumDriverLocalService service;
	
	
	  public AndroidDriver  driver;

	  
	 
	  
	  
	@BeforeClass
	public void configureAppium() throws MalformedURLException,InterruptedException {

		Map<String, String> env = new HashMap<String, String>(System.getenv());
		env.put("ANDROID_HOME", "C:\\Users\\user\\AppData\\Local\\Android\\Sdk");
		env.put("JAVA_HOME", "C:\\Program Files\\Java\\jdk-17");

		service = new AppiumServiceBuilder()
				.withAppiumJS(
						new File("C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js"))
				.withIPAddress("127.0.0.1").usingPort(4723).withEnvironment(env).withTimeout(Duration.ofSeconds(30)).build();
		service.start();

		UiAutomator2Options options = new UiAutomator2Options();
		options.setDeviceName("smart6px");
		options.setApp(System.getProperty("user.dir") + "\\ressource\\android.wdio.native.app.apk");
		AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/"), options);
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(300));

	}
	
	
 
	   @AfterClass
	     public void tearDown() {
	    		
	 		driver.quit();
	 		service.stop();
	   }
}

devicetest 
package appTest;

import org.testng.Assert;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.android.AndroidDriver;

public class DeviceTest extends Base {
	
 

	
	@Test
	public void lancerDevice () throws InterruptedException
	
	
	{
 		 System.out.println("Clicked Successfully");

		 driver.findElement(AppiumBy.accessibilityId("Login")).click();
			driver.findElement(AppiumBy.xpath("//android.widget.TextView[@text='Sign up']")).click();
			driver.findElement(AppiumBy.accessibilityId("input-email")).sendKeys("test@yopmail.com");
			driver.findElement(AppiumBy.accessibilityId("input-password")).sendKeys("87654321");
	 		driver.findElement(AppiumBy.accessibilityId("input-repeat-password")).sendKeys("87654321");
			driver.findElement(AppiumBy.accessibilityId("button-SIGN UP")).click();
			String msgrecu = driver.findElement(AppiumBy.id("android:id/message")).getText();
			System.out.println(msgrecu);
			driver.findElement(AppiumBy.id("android:id/button1")).click();
	 		Assert.assertEquals(msgrecu, "You successfully signed up!");
	}

}

**Comment by bejaoui13** [comment]
whene the script in the same page it is working good but when i but them in 2 pages i have error

**Comment by valfirst** [comment]
It is not Appium java client issue

**Comment by itkhanz** [comment]
> whene the script in the same page it is working good but when i but them in 2 pages i have error

As mentioned, problem is not with Appium but how you are using driver variable in your child class. 
Here’s what’s happening:

1. In the Base class, you are initializing the driver inside the configureAppium method. However, you are using a local variable `AndroidDriver driver `instead of assigning it to the class-level driver variable.

2. Because the driver in the Base class is not being assigned correctly, the driver in the DeviceTest class remains null, leading to the NullPointerException.

To fix this, ensure that the driver in the Base class is assigned to the class-level variable instead of creating a new local variable. Here’s how you can fix the Base class `configureAppium()` method:

```
// Assign the driver to the class-level variable
 driver = new AndroidDriver(new URL("http://127.0.0.1:4723/"), options);
```

**Comment by amedvedjev** [comment]
@valfirst it is expected with your code try something like:
```
    @BeforeSuite() // happens ONLY one time before starting first test
    public void startAppiumServer() {
        System.out.println("startAppiumServer"); // add logs to see when it happens
        Map<String, String> env = new HashMap<String, String>(System.getenv());
        env.put("ANDROID_HOME", "C:\\Users\\user\\AppData\\Local\\Android\\Sdk");
        env.put("JAVA_HOME", "C:\\Program Files\\Java\\jdk-17");

        service = new AppiumServiceBuilder()
                .withAppiumJS(
                        new File("C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js"))
                .withIPAddress("127.0.0.1").usingPort(4723).withEnvironment(env).withTimeout(Duration.ofSeconds(30)).build();
        service.start();
    }

    @BeforeMethod() // happens before EACH test start
    public void startAppiumDriver() {
        System.out.println("startAppiumDriver"); // add logs to see when it happens
        UiAutomator2Options options = new UiAutomator2Options();
        options.setDeviceName("smart6px");
        options.setApp(System.getProperty("user.dir") + "\\ressource\\android.wdio.native.app.apk");
        AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/"), options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(300));

    }

    @AfterMethod() // happens before EACH test start
    public void quitDriver() {
        System.out.println("quitDriver"); // add logs to see when it happens
        driver.quit();
    }

    @AfterSuite() // happens ONLY one time after finishing last test
    public void stopAppiumServer() {
        System.out.println("stopAppiumServer"); // add logs to see when it happens
        service.stop();
    }
```
