### ISSUE TITLE
TouchAction.perform not working in appium 2 java client 9.2.2 (Unhandled endpoint ... touch/perform)

### ISSUE THREAD

**Issue by MuhammadAli00145** [appium/java-client#2232]
I'm encountering an issue when trying to perform a tap action using TouchAction in my iOS automation script. Below is the code snippet I'm using:

TouchAction touchAction = new TouchAction((PerformsTouchActions) driver);
touchAction.tap(PointOption.point(x, y)).release().perform();

However, this results in the following error:

org.openqa.selenium.UnsupportedCommandException: Unhandled endpoint: /session/BF7BBE79-B209-4C70-AD7E-CC979C420E0B/touch/perform -- http://127.0.0.1:8100/ with parameters {
    wildcards =     (
        "session/BF7BBE79-B209-4C70-AD7E-CC979C420E0B/touch/perform"
    );
}

Steps to Reproduce:

Initialize the driver with the required capabilities for an iOS device.
Attempt to perform a tap action using the TouchAction API.
Expected Behavior: The tap action should be performed without throwing an UnsupportedCommandException.

Actual Behavior: The exception is thrown, indicating that the endpoint is unhandled by the WebDriverAgent.

Request: Could you please advise on whether this is a known issue or if there is an alternative approach for performing tap actions on iOS using Appium? Any guidance on resolving this would be appreciated.

**Comment by valfirst** [comment]
`TouchAction` is deprecated: https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#touch-actions
