### ISSUE TITLE
AndroidDriver.currentActivity null pointer exception

### ISSUE THREAD

**Issue by nicolasavenza** [appium/java-client#224]
I'm getting some test failures due to a nullpointer exception inside the AndroidDriver when I call currentActivity(). This does not happen every time, most of the times the call works properly. I'm using the currentActivity call to verify whether the app crashed or is still running.

    java.lang.NullPointerException
	at io.appium.java_client.android.AndroidDriver.currentActivity(AndroidDriver.java:223)

Server log: 

    [36minfo[39m: [37m<-- GET /wd/hub/session/51f2fd4e-62c8-4fca-9ea3-56071b2b41ae/appium/device/current_activity [39m[32m200[39m[90m 159.526 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"51f2fd4e-62c8-4fca-9ea3-56071b2b41ae"}[39m

This issue happens with Appium 1.4.7 on OSX 10.10.4
Client library is java-client 3.0.0

**Comment by TikhomirovSergey** [comment]
It is definitely the bug of the server, not client.

**Comment by TikhomirovSergey** [comment]
@nicolasavenza 
Please reopen this ticket/open a new one if the problem is reproduced still
Please try to use this template: https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md
