### ISSUE TITLE
Javascript executor not working in android 4.3

### ISSUE THREAD

**Issue by hmungoli** [appium/java-client#225]
@Test
	public void openTC5() throws InterruptedException {

		util = new Utility(driver);
		driver.startActivity("com.admarvel.testerappV250",
				"com.admarvel.testerapp.AdMarvelTesterAppActivity");
		util.contextChange("NATIVE");
		Thread.sleep(2000);
		// Banner button
		util.byId("com.admarvel.testerappV250:id/btnLoadBanner").click();
		Thread.sleep(2000);
		util.contextChange("WEBVIEW");
		Thread.sleep(2000);
		((JavascriptExecutor) driver).executeScript("openSite();");
}
I am using java client 3.0.0 ; appium server 1.4.0.0 when trying to execute javascript commands in android 4.3 getting error as org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds

NOTE: The same script is working fine in Android 5.0

**Comment by TikhomirovSergey** [comment]
Hi @hmungoli 
Could you provide a gist with server output? It is probably server-side problem. Did it worked with sever 1.3.x

**Comment by Jonahss** [comment]
You should be using `driver.getContext()` and `driver.context('WEBVIEW')`.

**Comment by hmungoli** [comment]
Hi Johnass .,
I have used the same command......I defined a function that will use the same command

**Comment by hmungoli** [comment]
Hi Johnass .,
I have used the same command......I defined a function that will use the same command

**Comment by hmungoli** [comment]
Hi Johnass .,
I have used the same command......I defined a function in my own created class utility that will use the same command
public void contextChange(String context) {

		Set<String> contextNames = driver.getContextHandles();
		for (String contextName : contextNames) {
			if (contextName.contains(context)) {
				driver.context(contextName);
			}
		}
	}
	so if u can check my code in the 1st post i am calling the same function by calling the function with the object of the above class which i have created separately for all the utility functions util.contextChange("WEBVIEW");

And what i mentioned was the main problem while executing in android 4.3 is while executing the javascript command ( ((JavascriptExecutor) driver).executeScript("openSite();");)after changing the context to webview is saying that the (org.openqa.selenium.WebDriverException: Not yet implemented) while the same script is working fine in android 5.0

Can you please tell me whether appium supports javascript execution in android 4.3?

**Comment by Jonahss** [comment]
Yes it should support it inside webviews.
Try using capabilities: {automationName: "selendroid" }

**Comment by aniket-21** [comment]
This is the reason 
androidController.execute = function (script, args, cb) {
  cb(new NotYetImplementedError(), null);
};

Also it seems you are trying to execute a javascript function called openSite(); present inside HTML source. I don't think UIAutomator has a capability to do that.
As Jonahss suggested, you should use Selendroid

**Comment by TikhomirovSergey** [comment]
@hmungoli 
Is the problem resolved? Please reopen this issue or open a new one using this template: https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md
