### ISSUE TITLE
Since Oracle JDK charges a fee, I need to switch to another JDK. Do you have a recommended JDK that is more suitable for java_client? 

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/java-client#2253]
## Description

Since Oracle JDK charges a fee, I need to switch to another JDK. Do you have a recommended JDK that is more suitable for java_client? 

## Environment

* appiumVersion: 1.22.2
* Node.jsVersion: 22.10.0
* AndroidDeviceVersion:10
* Real device or emulator/simulator: Real device

**Comment by valfirst** [comment]
Appium Java client supports all Java distributions.

**Comment by eglitise** [comment]
Personally I've used [Adoptium's Temurin JDK](https://adoptium.net/en-GB/temurin/releases/) as an alternative.
For future questions please use [the Appium forum](https://discuss.appium.io/).
Also just to add, Appium 1 is no longer supported since 2022. We recommend upgrading to Appium 2.
