### ISSUE TITLE
UiScrollable Within A Context - Scrolling First Element

### ISSUE THREAD

**Issue by anders-g-hansen** [appium/java-client#226]
Sending a UiScrollable command to a page that contains multiple scrollable elements always appears to act upon the first scrollable element even when a context is provided.

Here is an example using test I plugged into the java-client AndroidUIAutomatorTest class to demonstrate the issue.  Note, the test navigates to a page in the test app which has multiple scrollables.  When it attempts to scroll to find an element it scrolls the wrong scrollable (first on the page) rather than the element in the provided context.

	  @Test
	  public void scrollBars() {
		driver.scrollToExact("Views").click();
		driver.scrollToExact("ScrollBars").click();
		driver.scrollToExact("3. Style").click();

		// find the middle ScrollView (second one since we're 0 based index)
		AndroidElement element = driver.findElementByAndroidUIAutomator("new UiSelector().className(android.widget.ScrollView).index(1)");
		assertTrue(element.isDisplayed());

		AndroidElement found;

		// use a UiScrollable selector with something we know will be found within the context of the middle scrollview and print the text to ensure it works
		found = element.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView))");
		assertTrue(found.isDisplayed());
		System.out.println("text: " + found.getText());

		// use a UiScrollable selector with something ew know will NOT be found to see if it will properly scroll to find it, note it is scrolling the first Scrollable on the page
		// not the one with the "element" context
		found = element.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId(\"notFoundId\"))");
		assertTrue(found.isDisplayed());
		System.out.println("text: " + found.getText());

	  }

Here are the appium logs for the above test run.

The first log provided is from the first find within the context (4 from the log).  This call works as expected.

		info: --> POST /wd/hub/session/84c164f6-fc7c-433f-ac46-7cae26739c05/element/4/element {"id":"4","using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView))"}
		info: [debug] Waiting up to 0ms for condition
		info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView))","context":"4","multiple":false}]
		info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView))","context":"4","multiple":false}}
		info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
		info: [debug] [BOOTSTRAP] [debug] Got command action: find
		info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView)) using ANDROID_UIAUTOMATOR with the contextId: 4 multiple: false
		info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView))
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
		info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: className(android.widget.TextView),
		info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: className(android.widget.TextView)
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: java.lang.Class<T> arg: android.widget.TextView
		info: [debug] [UIAUTOMATOR STDOUT] referenceTable GDEF length=778 1
		info: [debug] [UIAUTOMATOR STDOUT] referenceTable GSUB length=6388 1
		info: [debug] [UIAUTOMATOR STDOUT] referenceTable GPOS length=66796 1
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: android.widget.TextView
		info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
		info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
		info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.TextView]
		info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"5"}}
		info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"5"},"sessionId":"84c164f6-fc7c-433f-ac46-7cae26739c05"}
		info: <-- POST /wd/hub/session/84c164f6-fc7c-433f-ac46-7cae26739c05/element/4/element 200 109.181 ms - 87 {"status":0,"value":{"ELEMENT":"5"},"sessionId":"84c164f6-fc7c-433f-ac46-7cae26739c05"}

This log is from the call which results in scrolling the wrong scrollable.  Though the context of "4" was provided, it ends up scrolling the first scrollable on the page NOT the one within the provided context.

		info: --> POST /wd/hub/session/f709bb83-1ef2-41c9-a874-bbb6eeb9b471/element/4/element {"id":"4","using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId(\"notFoundId\"))"}
		info: [debug] Waiting up to 0ms for condition
		info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId(\"notFoundId\"))","context":"4","multiple":false}]
		info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId(\"notFoundId\"))","context":"4","multiple":false}}
		info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
		info: [debug] [BOOTSTRAP] [debug] Got command action: find
		info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId("notFoundId")) using ANDROID_UIAUTOMATOR with the contextId: 4 multiple: false
		info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId("notFoundId"))
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
		info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: resourceId("notFoundId"),
		info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: resourceId("notFoundId")
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "notFoundId"
		info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
		info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
		info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@f374fae
		info: [debug] [BOOTSTRAP] [debug] Invoke complete.
		info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=notFoundId]
		info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
		info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId("notFoundId")) using ANDROID_UIAUTOMATOR with the contextId: 4 multiple: false
		info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId("notFoundId"))
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
		info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: resourceId("notFoundId"),
		info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: resourceId("notFoundId")
		info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "notFoundId"
		info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
		info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
		info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@2368214f
		info: [debug] [BOOTSTRAP] [debug] Invoke complete.
		info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=notFoundId]
		info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"No element found"}
		info: [debug] Condition unmet after 15967ms. Timing out.
		info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"No element found"},"sessionId":"f709bb83-1ef2-41c9-a874-bbb6eeb9b471"}
		info: <-- POST /wd/hub/session/f709bb83-1ef2-41c9-a874-bbb6eeb9b471/element/4/element 500 15971.919 ms - 195
		info: --> DELETE /wd/hub/session/f709bb83-1ef2-41c9-a874-bbb6eeb9b471 {}

I suspect it is losing the context when it fails to find the element and we see this line in the log:

> info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.

**Comment by Jonahss** [comment]
Whoah great writeup. Looks like a bug. This will have to get corrected in our Java code.

**Comment by aniket-21** [comment]
I could replicate the issue but its really weird cos I could see context Id being retained and its the same parent element on which getChild method being called. Parent object is persistent in Element hash. Still wondering what is causing it to search in 1st scrollable instead of 2nd.
Will try to look into again sometime later today

**Comment by aniket-21** [comment]
I am not sure if you are really doing this right. I observed few things

1) Your parent element is a ScrollView, which is a scrollable. There are no more scrollable objects _inside_ scroll view, but your UISelector is trying to find one :
new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId(\"notFoundId\"))"

2) Although the above code seem to work (ideally it should not per me when its called over an element and not the driver) it fetches the 1st scrollable and acts on the same

3) If I execute your code, during search of 1st element (textview), it scrolls the 2nd scroll view, not sure why it needs to scroll , cos the textview is right there inside the scrollview, it doesn't need to scroll to find it.

I tried your code with a small change. I applied index 1 on scrollable that you are searching and both the times, appium searched 2nd scroll view with expected results

1st time it didnt scroll atall cos text view was right there and it got the text
2nd time it did scroll (the 2nd scroll view) but was unable to find an element with resource id "notFound"

4) With all these observations, I feel the "find" handler of bootstrap behaves weirdly when it comes to scrollable and scroll in view. I feel scrollToView should not be a part of UIObject selector string. In UIAutomator scrollToView returns a boolean and you cannot expect an element from it when passed as selector string

**Comment by ahansen1** [comment]
It is entirely possible that I'm not doing it correctly.  Essentially what I'm trying to accomplish is to scroll for an element within the context of the previously found element.  I plugged in index(1) as you suggested, and did see it work.  However, this is modifying the selector based on the root or driver context not the context of the element we're within.

When the context goes down into appium how is it being used?  Maybe if I understood this at a high level it would be easier to understand how I might be able structure the selector to work correctly?

This is an example raw selector that will work.  It takes the selector used to find "element" (our context) and appends it inside a fromParent.  However, we don't want the "fromParent" to have to be specified.  The fromParent should be implied from the context it's working within.

    found = element.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).fromParent(new UiSelector().className(android.widget.ScrollView).index(1))).scrollIntoView(resourceId(\"notFoundId\"))");

Hopefully this makes sense.  I'm in a bit over my head on terminology here.

**Comment by anders-g-hansen** [comment]
It is entirely possible that I'm not doing it correctly.  Essentially what I'm trying to accomplish is to scroll for an element within the context of the previously found element.  I plugged in index(1) as you suggested, and did see it work.  However, this is modifying the selector based on the root or driver context not the context of the element we're within.

When the context goes down into appium how is it being used?  Maybe if I understood this at a high level it would be easier to understand how I might be able structure the selector to work correctly?

This is an example raw selector that will work.  It takes the selector used to find "element" (our context) and appends it inside a fromParent.  However, we don't want the "fromParent" to have to be specified.  The fromParent should be implied from the context it's working within.

    found = element.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).fromParent(new UiSelector().className(android.widget.ScrollView).index(1))).scrollIntoView(resourceId(\"notFoundId\"))");

Hopefully this makes sense.  I'm in a bit over my head on terminology here.

**Comment by aniket-21** [comment]
I understand your concern and agree that it doesn't seem to work in context of parent element
This can be further drilled down by checking how it works directly with UIautomator. If it works as expected then we need to get appium handler corrected.

Considering the case it was working fine..I would expect both your statements to fail rather than succeeding , reason being if you are trying to find a scrollable inside scrollview it should not return you an element which is currently not the case.

I will see how it works directly using UIautomator

**Comment by aniket-21** [comment]
I also think that may be scrollable is not a good example to test parent context.
You can probably try fetching a linearview as parent and then search for child scrollviews

**Comment by anders-g-hansen** [comment]
How does appium use the context or parent element?  Is it modifying the UiSelector that is sent?  Maybe similar to what I had above?  How would one go about testing the equivalent of parent context within UiAutomator directly?  What I had given above with the fromParent is what I imagined would be equivalent.

The example I used is a bit contrived.  It is all I could find to demonstrate within the sample app and I wanted to use what was out of the box in the repository.  

We do have examples though where there are multiple scrollable views and we would like to search for elements within them.  In this case the scrollable we would like scrolled is actually the root element.  What we are really after is the selector in the scrollIntoView, e.g. className(android.widget.TextView) or resourceId("notFoundId"). 

I'm not so sure it doesn't make sense that the first one is found.  It just depends on what appium is doing with context.  In the last example I used with fromParent, the scrollable is kind of like the parent context and it finds the scrollable.  If the root element itself is considered in the search, then it makes sense that the scrollable would find the root when it was run, even if it didn't contain any.

Hopefully this makes sense?

**Comment by anders-g-hansen** [comment]
I did a bit more digging into the bootstrap code and have a much better idea about what is going on.  Though admittedly I am still just scratching the surface.  Here is raw UiAutomator code along with comments indicating what I think is going on.  It is based within the context of my original example.  I included in the comments the mappings to the original statements.

	// AndroidElement element = (AndroidElement)driver.findElementByAndroidUIAutomator("new UiSelector().className(android.widget.ScrollView).index(1)");
	// Grab the green (middle) scrollable as our context.
	UiObject contextElement = device.findObject(new UiSelector().className("android.widget.ScrollView").index(1));

	// new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(className(android.widget.TextView))
	// The getChild is what happens when we pass the context.  This case works because when the element already exists
	// and the UiScrollableParser doesn't have to do a scrollIntoView b/c it does an exists check before scrolling.
	UiObject elementThatExists = contextElement.getChild(new UiSelector().className("android.widget.TextView"));
	assertTrue(elementThatExists.exists());

	// new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId("notFoundId"))
	// This is the case that wasn't working as expected.  The UiScrollableParser actually constructs
	// the UiScrollable and executes the scrollIntoView.  It then returns the UiSelector contained
	// within the scrollIntoView method which will be run by the Find command (and ultimately the AndroidElementsHash)
	// in the correct context.  The trouble is that the UiScrollable didn't scroll the correct element
	// based on the context.
	UiSelector scrollIntoViewSelector = new UiSelector().resourceId("notFoundId");

	// This is essentially what the UiScrollableParser runs which is why it is getting executed outside the context.
	new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(scrollIntoViewSelector);

	// This is what I would expect if the context was maintained.  However, as you've noted this wouldn't
	// exactly solve what I'm trying to accomplish.
	UiSelector scrollableSelector = contextElement.getChild(new UiSelector().scrollable(true)).getSelector();
	new UiScrollable(scrollableSelector).scrollIntoView(scrollIntoViewSelector);

	// In order to solve what I'm after I would also need a special keyword available to the UiScrollableParser
	// that indicated that the scrollable should be created from the context itself, e.g. 
	// new UiScrollable(CONTEXT).scrollIntoView(resourceId("notFoundId"))
	new UiScrollable(contextElement.getSelector()).scrollIntoView(scrollIntoViewSelector);

	// When the returned selector is run, it runs it in the correct context.
	UiObject elementThatDoesNotExist = contextElement.getChild(scrollIntoViewSelector);
	assertFalse(elementThatDoesNotExist.exists());

**Comment by TikhomirovSergey** [comment]
I'm closing it according to #385
