### ISSUE TITLE
Enhancement: what if there was some page/screen object extension/small framework 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#228]
Problems :

- 1

Appium tools as well as similar Selenium facilities provide the following usecase:

```java
public class MyScreen{

  @iOSFindBy
  @AndroidFindBy
  MobileElement textField;

  @iOSFindBy
  @AndroidFindBy
  MobileElement button;

  public void setText(String text) {
      textField.sendKeys(text);
  }

  public void confirm() {
      button.click();
   }
}
```

It looks ok. But it is possible that behavior for each plathorm can be different. If it is so then the code can look not so pretty

```java
public class MyScreen{

  @iOSFindBy
  @AndroidFindBy
  MobileElement textField;

  @iOSFindBy
  @AndroidFindBy
  MobileElement button;

  public void setText(String text) {
      if (android) {
         textField.clear();
         textField.sendKeys(text);
      }
      if (ios){
         //does something else
         textField.setValue(text)
      }
  }

  public void confirm() {
      if (android) {
          button.click();
       }
       if (ios){
         //does something else
         textField.tap(5000);
      }
   }
}
```
No one complains. But it is probably they think that it is usual.

 - 2

Appium tools as well as similar Selenium facilities by default allows to use only WebElement or subclasses. So if there is no decomposition on widgets or repeatable groups of elements then there are probably many declared elements and methods. If there is decompasition then end user can face the problem __1__.

What could be a solution:

I think that it would be cool if appium java_client supported the following use case as well as default:

```java
public class MyBigScreen{

  @iOSFindBy
  @AndroidFindBy
  Widget1 widget1; //it is a page/screen object
  //that describes some widget

  @iOSFindBy
  @AndroidFindBy
  Widget2 widget2; //it is a page/screen object
  //that describes some widget

  @iOSFindBy
  @AndroidFindBy
  List<Widget1> widgets1;

  @iOSFindBy
  @AndroidFindBy
  List<Widget2> widgets2;

  public void doSomething() {
     widget1.doSomeAction1();
     widget1.doSomeAction2();
  }

  public void doSomethingElse() {
     widget2.doSomeAction1();
     widget2.doSomeAction2();
  }

  //and so on  
}
```

Each __Widget1__ and __Widget2__ are abstractions/certain classes that descride behavior of some widget or repeatable group of elements. If there are abstrations then their extensions for each certain platform are supposed to be used. These extensions would encapsulate peculiar behavior properties. 

Honestly I found this idea when I was looking at this framework: [Yandex Html Elements framework](https://github.com/yandex-qatools/htmlelements). I think there is no need to develop the large lib of elements/widgets like that. We could provide only 2-3 abscract classes that would allow end user to model their app/screens similar way.

**Comment by Simon-Kaz** [comment]
:+1:

**Comment by Jonahss** [comment]
Cool :+1:

**Comment by saikrishna321** [comment]
:+1:  

@TikhomirovSergey Wordpress app should b a good example to test this feature

(Android)
* Enter username and password and click on Signin Button

(IOS)
* Enter username , password.
* Enter the Site URL and then click on Singin Button

As this feature clearly is useful for identical apps on page object pattern with slight change in the flow.

https://github.com/wordpress-mobile/WordPress-iOS

https://github.com/wordpress-mobile/WordPress-Android

**Comment by saikrishna321** [comment]
@TikhomirovSergey  is this gonna b available in the next java-client release ?

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
>is this gonna b available in the next java-client release ?
Yes! :)

**Comment by saikrishna321** [comment]
@TikhomirovSergey  How is it going ? Any Updates ?

**Comment by TikhomirovSergey** [comment]
@saikrishna321 yep!
It is coming out soon...

**Comment by saikrishna321** [comment]
:+1:

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
Now I have a problem with StaleElementReferenceException in Selendroid mode. It is defenitely a bug that I should fix. After I'm going to add fully cross platform test. Then work will be finished.

**Comment by saikrishna321** [comment]
@TikhomirovSergey Awesome.. looking for it...

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
If it is interesting please look at my las commit:

https://github.com/TikhomirovSergey/java-client/commit/8f69b8ca7f63e47905b2fa1b999368ef8028ecb7
