### ISSUE TITLE
Redirect webflow to IOS app in appium

### ISSUE THREAD

**Issue by addepalliamareswar** [appium/java-client#231]
Hi ,,

I am new to appium automation .

I am automating ios hybrid app using appium. Below are the steps doing to automate.

1. Open the safari browser and pass the url 

2.Click on the button(VPN)  in image 3

3. It will redirect to App which is already installed on mobile.

First two steps are automated. But in third step not getting the control on that app and stuck there. Even page source also not giving in appium inspector.

![image 3](https://cloud.githubusercontent.com/assets/13344549/9513613/972af704-4caf-11e5-9669-00239f5ec536.jpg)
![image 4](https://cloud.githubusercontent.com/assets/13344549/9513617/a24688ce-4caf-11e5-8883-b1f3a6f6a79e.jpg)

**Comment by addepalliamareswar** [comment]
Blocked with this issue . Not able to move forward ...

Please help me with some workarounds to fix it..

**Comment by Jonahss** [comment]
In Appium on iOS, you can only automate the app that Instruments first launches. So if you want to automate your app, you have to start with your app. This is a limitation of Apple UIAutomation framework.
