### ISSUE TITLE
Unable to click/tap multiple items in a list, only the first item

### ISSUE THREAD

**Issue by justintilson** [appium/java-client#232]
Appium: 1.4.1, Java Client: 3.1.0, iPhone 6, Platform 8.3

I have a test that is attempting to click/tap multiple UIACollectionCells in a list. I have no trouble retrieving the MobileElements but I'm only able to click the first one. Any subsequent attempts to click/tap any others, either in order or randomly fail. The elements are visible on the screen and show up in the Appium Inspector when 'Show Disabled' and 'Show Invisible' are unchecked.

What I know: I've tried using the Appium Inspector's 'TAP' functionality on the same elements and it works correctly.

If I check the .isDisplayed() method when iterating over all the UIACollectionCells, all except the first one return false.

I tried dumping some details (id, size, location) to see what is going on:

Displayed ID: 18
Displayed Size: (345, 50)
Displayed Location: (30, 182)
~~
Not Displayed ID: 19
Not Displayed Size: (0, 0) 
Not Displayed Location: (0, 0)
~~
Not Displayed ID: 20
Not Displayed Size: (0, 0)
Not Displayed Location: (0, 0)
...

All elements beyond the first one that was clicked have 0 size and 0 location.

If I dump the XML for the same elements, all the elements are there with correct x,y coordinates.

```xml
<UIACollectionCell name="recipes_sort_filter_by_african" label="" value="0" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/37/0" x="30" y="182" width="345" height="50">
    <UIAStaticText name="African" label="African" value="African" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/37/0/0" x="87" y="196.5" width="268" height="21">
    </UIAStaticText>
</UIACollectionCell>
<UIACollectionCell name="recipes_sort_filter_by_asian" label="" value="0" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/37/1" x="30" y="232" width="345" height="50">
    <UIAStaticText name="Asian" label="Asian" value="Asian" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/37/1/0" x="87" y="246.5" width="268" height="21">
    </UIAStaticText>
</UIACollectionCell>
<UIACollectionCell name="recipes_sort_filter_by_central_south_american" label="" value="0" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/37/2" x="30" y="282" width="345" height="50">
    <UIAStaticText name="Central/South American" label="Central/South American" value="Central/South American" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/37/2/0" x="87" y="296.5" width="268" height="21">
    </UIAStaticText>
</UIACollectionCell>
```

What all the above leads me to think is that Appium is returning the correct XML but the Java Client is not interpreting it correctly (maybe?).

**Comment by aniket-21** [comment]
can you paste your code?

**Comment by justintilson** [comment]
page object that loads the screen elements:

```java
public class SortFilterChooseFiltersPhonePage extends IOSPage {
    public SortFilterChooseFiltersPhonePage(final AppiumDriver driver) {
        super(driver);
    }

    @iOSFindBy(accessibility = "recipes_sort_filter_container")
    private MobileElement filterContainer;

    public final List<MobileElement> getFilters() {
        return filterContainer.findElementsByClassName("UIACollectionCell");
    }
}
```

code that iterates over the filters:

```java
List<MobileElement> recipeFilters = sortFilterChooseFiltersPhonePage.getFilters();

for (MobileElement element : recipeFilters) {
    if (element.isDisplayed()) {
        System.out.println("Displayed ID: " + element.getId());
        System.out.println("Displayed Size: " + element.getSize());
        System.out.println("Displayed Location: " + element.getLocation().toString());

        element.click();
    } else {
        System.out.println("Not Displayed ID: " + element.getId());
        System.out.println("Not Displayed Size: " + element.getSize());
        System.out.println("Not Displayed Location: " + element.getLocation().toString());
    }
}
```

**Comment by TikhomirovSergey** [comment]
Hi @justintilson 
Can you paste a code sample of how it performs the tapping on a collection?
Also it is interesting to see server outpur. Could you provide a gist?

**Comment by justintilson** [comment]
@TikhomirovSergey, I provided the code that clicks on each element in the collection above, with the line:

   element.click();

Or more succinctly:
```java
for (MobileElement element : recipeFilters) {
    if (element.isDisplayed()) {
         element.click();
    }
}
```

Server logs in a gist here: https://gist.github.com/justintilson/76ea98cb31368c2110a7

**Comment by TikhomirovSergey** [comment]
Sorry @justintilson sometimes I'm so distrait :)
I think there is the reported server-side issue. Please look at this https://github.com/appium/appium/issues/4916

Your problem is that instruments return "false" when they calculate visibility. Right?

**Comment by justintilson** [comment]
@TikhomirovSergey - this might be the same issue as https://github.com/appium/appium/issues/4916

I assumed it was Java Client related because the XML (above) generated by the Appium Inspector looks correct to me. All UIACollectionCell have positive (non-zero) coordinates and are flagged as enabled, valid and visible, yet, .isDisplayed() returns false and .getSize() returns (0, 0).

I'll follow up on the other thread and see if someone else can replicate my problem.

**Comment by justintilson** [comment]
I wrote the same test for Android and it is working as expected/intended (all items in the list of clickable). That seems to verify that this is an iOS/instruments issue.

**Comment by aniket-21** [comment]
I wonder how does it work from inspector then

**Comment by TikhomirovSergey** [comment]
@justintilson 
Please reopen this issue/onen a new one if the problem is still reproduced.
Please try to use this template https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md

**Comment by erpardeepjain** [comment]
@justintilson have you get your issue sorted out yet? any solution so far?
