### ISSUE TITLE
The user informing: some methods of AppiumDriver/MobileElements should be marked @Deprecated with the definition of the reason 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#234]
Majority (I think) of end user community uses java_client for the native app testing. Some methods which work against web/HTML UI won't work at this case:

- Methods related with the finding by css values/link tests doesn't work at all or at all most all cases.

- I'm suspecting that methods of Selenium Mouse/Keyboard interfaces don't work too. If it is impossible to reimplement them then they should be declared as deprecated.

So I think an end user has to be informed about these things.

**Comment by Simon-Kaz** [comment]
It should definitely be noted somewhere, though the CSS/link selectors work on mobile web, which a large % of users use Appium for.

**Comment by Fanch-** [comment]
In web context of hybrid apps too.

**Comment by Jonahss** [comment]
:+1:

**Comment by TikhomirovSergey** [comment]
I'm thinking about the adding of information to JavaDoc only...
