### ISSUE TITLE
SendKeys with accent and others characters is not working.

### ISSUE THREAD

**Issue by Vanilton18** [appium/java-client#239]
Hello,

I am sending texts in Portuguese in which they have accents like: á, ão, ª, º, ° , à, ¨, soon identified problems sending the SendKeys method words or text containing the values already mentioned.

Example:

Input:
String word = "ão";
for(int i=0; i<word.length(); i++){
driver.findElementById("foo").sendKeys("letter"+word.charAt(i));
}

Output

""

No exception is thrown, only the text is not sent.

Appium java-client Version: 3.1.0
Device tested: Samsung_SM-T210 
Android Version: 4.4.2

**Comment by Fanch-** [comment]
Did you try with 
```java
capabilities.setCapability("unicodeKeyboard", true); 
```
?
Care it modifies your keyboard settings.

**Comment by Vanilton18** [comment]
Thank you! I did not know this capability, she could be in MobileCapabilityType interface. Apparently solved the problem. Another problem identifying return here.

**Comment by TikhomirovSergey** [comment]
@Vanilton18 I can add this to MobileCapabilityType soon.

**Comment by Fanch-** [comment]
@Vanilton18 I got issue with this capability though, like filling phone number fields. Otherwise it was fine. To retrieve previous state : 
```java
capabilities.setCapability("resetKeyboard", true);
```

**Comment by Vanilton18** [comment]
Ok @Fanch- I will perform the test battery that I have to check but there were problems.

@TikhomirovSergey Thanks for disposal.

Thank you for your help.
