### ISSUE TITLE
Unable to scroll using coordinates in iOS Simulator e.g. in UIACatalog app

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#241]
I am using appium 1.3.4
javaclient 3.1
iOS O/S version - OS X Yosemite version 10.10.3
iOS Simulator - 8.1

I am unable to scroll using coordinates in iOS Simulator in UIACatalog app
I tried different ways but it didn't scroll If i use coordinates If I use WebElement directly it scrolls

// This doesnt work
startx = driver.findElementByAccessibilityID("Alert Controller").getLocation.getX();
starty = driver.findElementByAccessibilityID("Alert Controller").getLocation.getY();
endx = driver.findElementByAccessibilityID("Sliders").getLocation.getX();
endy = driver.findElementByAccessibilityID("Sliders").getLocation.getY();
driver.swipe(startx,starty,endx,endy,2000);

// This works
TouchAction act = new TouchAction(driver);
WebElement To_elem = driver.findElementByAccessibilityID("Alert Controller");
WebElement from_elem = driver.findElementByAccessibilityID("Sliders");
act.press(from_elem ).moveTo(To_elem).release().perform();

In above web elements are same in both code but coordinates code does not work ? It simply taps 
I want to know the reason please help me with this ??

**Comment by TikhomirovSergey** [comment]
Hi @amitjaincoer191! 

What an exception does it throw? Can you create a gist with server output and attach the link to this ticket?

**Comment by amitjaincoer191** [comment]
Code does not throw any exception just the scroll does not happen. Below is the complete appium 
server logs for code 

startx = driver.findElementByAccessibilityID("Date Picker").getLocation.getX();
starty = driver.findElementByAccessibilityID("DatePicker").getLocation.getY();
endx = driver.findElementByAccessibilityID("Sliders").getLocation.getX();
endy = driver.findElementByAccessibilityID("Sliders").getLocation.getY();
driver.swipe(endx ,endy ,startx,starty,2000);


Server logs url : http://pastebin.ca/3157703
UICatalog Image : http://ibin.co/2FAqzdJjlQpk

**Comment by amitjaincoer191** [comment]
Any updates on this ???

**Comment by TikhomirovSergey** [comment]
I've no idea what is wrong on the client-side. Especially the "swipe" source looks like your code that works:

```java
@Override
	public void swipe(int startx, int starty, int endx, int endy, int duration) {
		TouchAction touchAction = new TouchAction(this);

		// appium converts press-wait-moveto-release to a swipe action
		touchAction.press(startx, starty).waitAction(duration)
				.moveTo(endx, endy).release();

		touchAction.perform();
	}
```

How can "wait" affect this? I don't know. Maybe it is one more server-side problem. Maybe @Jonahss or @bootstraponline have got more information.

**Comment by amitjaincoer191** [comment]
@TikhomirovSergey  
Appium Server logs are pasted here http://pastebin.ca/3157703

**Comment by amitjaincoer191** [comment]
Hello Sir,
Any updates on this issue ? Any input required from my end for answering. Please let me know.

Regards
Amit Jain

**Comment by aniket-21** [comment]
I would recommend you to try out one thing. Instead of using exact X and Y coordinates, Try to get the center coordinates of both the objects i.e X = x + width/2 and Y = y + height/2
Let me know if that works for you

**Comment by amitjaincoer191** [comment]
Sorry, I was not able to reply from last few days. I tried with object center coordinates also but it is not working ...

§Here is code
        
          int heightX = driver.findElementByAccessibilityId("Picker View").getSize().getHeight();
          int widthX = driver.findElementByAccessibilityId("Picker View").getSize().getWidth();
          int x1 = driver.findElementByAccessibilityId("Picker View").getLocation().getX();
          x1=x1+widthX/2;
          int y1 = driver.findElementByAccessibilityId("Picker View").getLocation().getY();
          y1=y1+heightX/2;
          int heightY = driver.findElementByAccessibilityId("Sliders").getSize().getHeight();
          int widthY = driver.findElementByAccessibilityId("Sliders").getSize().getWidth();
          int x2 = driver.findElementByAccessibilityId("Sliders").getLocation().getX();
          int y2 = driver.findElementByAccessibilityId("Sliders").getLocation().getY();
          x2=x2+widthY/2;
          y2=y2+heightY/2;
          System.out.println("x1,y1 " + x1 + "," + y1 + " x2,y2 " + x2 + "," + y2);
          TouchAction act = new TouchAction(driver);
          driver.swipe(x2,y2,x1,y1,2000);
          Thread.sleep(1000);
Output 
[TestNG] Running:
  /private/var/folders/4g/935x8_cn0dd2_cvhl6j4yqk4jx4cqn/T/testng-eclipse-1748952268/testng-customsuite.xml

x1,y1 187,410 x2,y2 187,564
PASSED: setUp

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

**Comment by amitjaincoer191** [comment]
Here are appium server logs for above executed code ..
http://pastebin.com/eWaP4CcT

**Comment by amitjaincoer191** [comment]
@aniket-21
Any updates ?

**Comment by TikhomirovSergey** [comment]
I think this issue is not in actual state. If you can reproduce it with the latest server/client version please open a new one issue
