### ISSUE TITLE
[Enhancement] Spring configuration, beans and aspects vs EventFiringWebdriver 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#242]
The Selenium project has an interesting solution,
EventFiringWebDriver:
- http://www.seleniummonster.com/eventfiringwebdriver-and-event-listeners-in-selenium/
- http://www.abodeqa.com/2014/06/08/event-listeners-in-selenium-webdriver/
- and lots of staff that Google can find

## Everything is cool but I think there are disadvantages for Appium users:

- this implementation restricts the using of mobile-specific functions till 

```java
AppiumDriver d = (AppiumDriver) eventFiringWebDriver.getWrappedDriver();
```

The same is true for elements

```java
MobileElement e = (MobileElement) ((WrapsElement) element).getWrappedDriver();
```

- almost all interfaces which are nested in WebDriver has protected/private implementations here. So an end user has to duplicate the present code when there is need to extend it

## What is supposed to be designed:

- it is supposed that the WebDriverEventListener interface will be reused. Also it would be cool if there were interfaces whose implementations allow to listen to (optionally) events of alerts, windows, contexts and so on.

-  To design a solution which has linear architecture. It would be cool to use Spring & AspectJ here.
http://www.mkyong.com/spring3/spring-aop-aspectj-annotation-example/

**Comment by GiannisPapadakis** [comment]
Isn't it very strict to depend on Spring and AspectJ for proxifying objects for logging and other features?

**Comment by TikhomirovSergey** [comment]
@GiannisPapadakis 
Why not? :)

It would be good to have same AndroidDriver/IOSDriver or MobileElement with subclasses that also provide an ability to log events implicitly. Spring and AspectJ 
provide ability to create proxies of whole classes (not only interfaces). 

There probably another suitable tools...

**Comment by GiannisPapadakis** [comment]
It is ok with this solution of course. There are a lot of possibilities for Spring AOP to cover. You need of course to have a bean lifecycle. I  could try some examples and review together if you want.

**Comment by TikhomirovSergey** [comment]
@GiannisPapadakis 
So do you consider that Spring could be more widely used in java_client? You are right definitely. The logging is just the most obvious capability :)

**Comment by GiannisPapadakis** [comment]
Of course it would be great to have Spring features into java_client. But careful design should be approached in order to expose ApplicationContext and referenced beans correctly.

**Comment by TikhomirovSergey** [comment]
Ok. I've got and this will be kept in mind.
Now this feature is being thought about. Also there is some dependency on few PR's to Selenium...
