### ISSUE TITLE
sendKeyEvent does not work and "pressKeyCode" method is not available in javaclient

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#244]
Suddenly sendKetEvent method stopped working and as per logs "pressKeyCode" method is not available in "java-client 3.1". Please fix this issue. Thanks....

Appium server logs :
{"platformVersion":"4.4.4","platformName":"Android","deviceName":"","appActivity":"SplashScreenActivity","autoLaunch":false,"appPackage":"com.cloverstudio.spika"},"platformName":"Android","deviceName":"","appActivity":"SplashScreenActivity","autoLaunch":false,"appPackage":"com.cloverstudio.spika"},"sessionId":"cb5fc214-7e5a-4994-b632-9180865e9cfc"}
> info: --> POST /wd/hub/session/cb5fc214-7e5a-4994-b632-9180865e9cfc/appium/device/start_activity {"appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","appWaitPackage":"","appWaitActivity":""}
> info: [debug] Getting device API level
> info: [debug] executing cmd: adb shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: adb shell "am start -S -n com.android.settings/com.android.settings.Settings"
> info: [debug] Responding to client with success: {"status":0,"value":"Successfully launched the app.","sessionId":"cb5fc214-7e5a-4994-b632-9180865e9cfc"}
> info: <-- POST /wd/hub/session/cb5fc214-7e5a-4994-b632-9180865e9cfc/appium/device/start_activity 200 1535.112 ms - 104 {"status":0,"value":"Successfully launched the app.","sessionId":"cb5fc214-7e5a-4994-b632-9180865e9cfc"}
> info: --> POST /wd/hub/session/cb5fc214-7e5a-4994-b632-9180865e9cfc/appium/device/keyevent {"keycode":3}
> warn: [DEPRECATED] The keyevent function has been deprecated and will be removed.  Please use the pressKeyCode function instead.
> info: [debug] Pushing command to appium work queue: ["pressKeyCode",{"keycode":3,"metastate":null}]
> error: Unhandled error: TypeError: Cannot call method 'sendAction' of null
>     at null.<anonymous> (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android.js:481:24)
>     at Object.q.process [as _onImmediate] (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:809:21)
>     at processImmediate [as _immediateCallback] (timers.js:330:15) context: [POST /wd/hub/session/cb5fc214-7e5a-4994-b632-9180865e9cfc/appium/device/keyevent {"keycode":3,"metastate":null}]

**Comment by amitjaincoer191** [comment]
Similar issue was raised in appium repo and it was closed without fix ....
https://github.com/appium/appium/issues/5285

**Comment by aniket-21** [comment]
I have created a pull request for it https://github.com/appium/java-client/pull/233
waiting for it to be merged

**Comment by Jonahss** [comment]
fixed by @aniket-21 in #233. Now merged and will be published shortly.
