### ISSUE TITLE
[Licensing]: A header of each source file should contain the reference to the Apache 2.0 licence 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#245]
Read this:
http://www.apache.org/licenses/LICENSE-2.0

**Comment by bootstraponline** [comment]
java-client should follow the apache 2.0 license just as the selenium hq upstream project does. That includes:

- [having a license file in the repo](https://github.com/SeleniumHQ/selenium/blob/master/LICENSE)
- [a notice file with contributors](https://github.com/SeleniumHQ/selenium/blob/master/NOTICE)
- [an appropriate header file on each source file](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/Proxy.java)

There are tons of resources online that explain in detail the trivial requirements to properly implementing the license. [ASF](http://www.apache.org/legal/src-headers.html) in particular is helpful.
