### ISSUE TITLE
iOS - Cannot get text from UIAElement

### ISSUE THREAD

**Issue by mkataokaelementum** [appium/java-client#256]
I am unable to get text by getText() method. Here is the title element I am trying to get the text from.

UIAElement name="cardTitleLabel" label="cardTitleLabel" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/2/1/1" x="28.125" y="356.9375" width="199.8046875" height="45.703125"

I tried the following.

title.getText();
title.getAttribute("name");
title.getAttribute("text")
title.getAttribute("label")
title.getAttribute("value")

**Comment by TikhomirovSergey** [comment]
@mkataokaelementum 
Please provide more details about your problems.
What does it return instead of expected text?
Maybe there is a thrown exception?
Please provide a stacktrace of exception and server output as attached gists.

**Comment by TikhomirovSergey** [comment]
@mkataokaelementum which server version do you use? Have you tried to use the latest version?

**Comment by namannigam** [comment]
facing similar issue with Android for the list of objects,trying to access them using index
element.get(i).getText()

**Comment by TikhomirovSergey** [comment]
@mkataokaelementum @namannigam 
Please attach gists with setrver output and stacktraces if there is some thrown exception.

**Comment by namannigam** [comment]
Returns "cannot resolve the method getText()"
Though the following redressed the error ::
List <WebElement> elementList = driver.findElements(By.id("element"));
elementList.get(i).getText()

**Comment by TikhomirovSergey** [comment]
@namannigam 
Can you add three gists to this ticket? One contains detailed sample of your client code. One more contains server console output. And last one contains error stacktraces. There is not enough information to find the root cause of your problem.

Also
Which versions of java client and appium server do you use?

**Comment by TikhomirovSergey** [comment]
@namannigam 
Please provide information and then reaopen this issue/open a new one. 
Please follow this template:  https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md
