### ISSUE TITLE
Android - pressKeyCode not working

### ISSUE THREAD

**Issue by aohrem** [appium/java-client#257]
The pressKeyCode() method of the AndroidDriver is not working for me and apparently a lot of other users from different help desks at the web as well. Example: https://discuss.appium.io/t/unable-to-tap-search-button-on-android-softkeyboard/1598

Appium java-client version 3.2

**Comment by TikhomirovSergey** [comment]
Hi @aohrem 
It is definitely the server-side problem, I think. 

There are too many concerns and opinions in mentioned topic. Let's talk about your problem. What does happen? Is some exception thrown? 

Please provede stacktrace and server output as attached gists.

Is this issue suitable for your case? 
https://github.com/appium/appium/issues/5162

**Comment by aohrem** [comment]
So, I also try to press the search button of the soft keyboard to start a location search in a native Android app. I tried the following things to achieve that:

mDriver is of the type AndroidDriver.

* mDriver.pressKeyCode(66);
* mDriver.pressKeyCode(84);
* mDriver.pressKeyCode(AndroidKeyCode.ENTER); // should be 66
* mDriver.pressKeyCode(AndroidKeyCode.KEYCODE_SEARCH); // should be 84
* mDriver.pressKeyCode(AndroidKeyCode.KEYCODE_ENTER); // should be 66

Also, I tried some work-arounds:

* clicking the search button coordinates with mDriver.tap() (screen width - X, screen height - X)
* sending a "\n" to the search field and the end of the search string with the sendKeys() method of my search field WebElement
* The mDriver.sendKeyEvent() method does not exist.

None of the above-mentioned solutions worked, but I also got no Exception or error message. The test just continues without the search button beeing pressed, so I assumed there has to be a bug in the Appium code.

The issue from your link (#5162) seems very related, but as far as I can see, I tried all solutions mentioned in that thread and none of those worked.

**Comment by TikhomirovSergey** [comment]
@aohrem 
Ok. Now it is clear 
I think you'll face this issue the root cause https://github.com/appium/appium/issues/5162 is found.  It is most likely on the the server side and it is probably won't be fixed by the java_client code changing.

Right now I can't mention one more workaround. Maybe @Jonahss or @bootstraponline know more. 

It woild be great if you attached two gists to this issue. A one with your java code sample and another with server output.

**Comment by aohrem** [comment]
Thank you, this really helped. :) I actually used an older Appium server version (1.4.0.0) and now updated to 1.4.13.1. Now this command works: mDriver.pressKeyCode(AndroidKeyCode.KEYCODE_ENTER);

**Comment by TikhomirovSergey** [comment]
Ok @aohrem . I'm happy :)

**Comment by xiaominghou** [comment]
hi I have use： 
            capabilities.setCapability("unicodeKeyboard", "True");
            capabilities.setCapability("resetKeyboard", "True");
To let me input Chinese word , and the keyboard is disappeared. So ,i cannot get the coodi for the search button, how can I to click the search button?

**Comment by abvijay** [comment]
I dont see SendKeyEvent or pressKeyCode in appiumdriver instance. Using AppiumForWindows 1_4_13_1.
 I need to delete Default value in the Email Field(Textbox) and Enter new value.

**Comment by RanjithHS** [comment]
pressKeyCode is not working for me even after using java client 5.0
please let me know if someone has implemented the same.

**Comment by gitterchris** [comment]
Do you have any workaround for this? Keycode 66 works but not 84.

**Comment by jarod-legault** [comment]
This solution in JavaScript worked for me:

`return driver.waitForElementById(<elementId>).type(<text to type>).click().execute( "mobile: performEditorAction", { "action": "search" } );`

This allowed me to find a text field, input some text, and submit a search command (same as clicking the search icon in the keyboard). Of course, you have to replace `<elementId>` and `<text to type>` with the proper values. See http://appium.io/docs/en/commands/mobile-command/ for details on "mobile: performEditorAction".
