### ISSUE TITLE
push apk from system to mobile (android) using pushfile function not working

### ISSUE THREAD

**Issue by bibekSahoo** [appium/java-client#258]
File apk = new File("D:\\");
		 File app = new File(apk, "some.apk");
                 byte[] fileContent = app.getAbsolutePath().getBytes()			
		 dr.pushFile("/mnt/sdcard/",fileContent);

//this is creating a tmp file , but unable to push the apk to device, but when adb push from command prompt working fine

**Comment by Jonahss** [comment]
Can you post the appium logs?

**Comment by bibekSahoo** [comment]
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.mediatek.filemanager","appActivity":"com.mediatek.filemanager.FileManagerOperationActivity","platformName":"Android","deviceName":"0123456789ABCDEF","newCommandTimeout":700}}
> info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_60)
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session b3cec698-02ed-4f71-9406-6755f21f501f
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_60
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 0123456789ABCDEF
> info: [debug] Setting device id to 0123456789ABCDEF
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF wait-for-device
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF push "C:\\Program Files\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF install "C:\Program Files\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF install "C:\Program Files\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.mediatek.filemanager -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [UIAUTOMATOR STDOUT] tcp port:4724
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.mediatek.filemanager/com.mediatek.filemanager.FileManagerOperationActivity"
> info: [debug] Waiting for pkg "com.mediatek.filemanager" and activity "com.mediatek.filemanager.FileManagerOperationActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 4.4.2
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to 700 secs
> info: [debug] Appium session started with sessionId b3cec698-02ed-4f71-9406-6755f21f501f
> info: <-- POST /wd/hub/session 303 11384.292 ms - 74 
> info: --> GET /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.mediatek.filemanager","appActivity":"com.mediatek.filemanager.FileManagerOperationActivity","platformName":"Android","deviceName":"0123456789ABCDEF","newCommandTimeout":700},"appPackage":"com.mediatek.filemanager","appActivity":"com.mediatek.filemanager.FileManagerOperationActivity","platformName":"Android","deviceName":"0123456789ABCDEF","newCommandTimeout":700},"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- GET /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f 200 4.741 ms - 711 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.mediatek.filemanager","appActivity":"com.mediatek.filemanager.FileManagerOperationActivity","platformName":"Android","deviceName":"0123456789ABCDEF","newCommandTimeout":700},"appPackage":"com.mediatek.filemanager","appActivity":"com.mediatek.filemanager.FileManagerOperationActivity","platformName":"Android","deviceName":"0123456789ABCDEF","newCommandTimeout":700},"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: --> POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/timeouts {"type":"implicit","ms":5000}
> info: [debug] Set Android implicit wait to 5000ms
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/timeouts 200 6.056 ms - 76 {"status":0,"value":null,"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: --> POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/element {"using":"id","value":"com.mediatek.filemanager:id/edit_adapter_name"}
> info: [debug] Waiting up to 5000ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.mediatek.filemanager:id/edit_adapter_name","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.mediatek.filemanager:id/edit_adapter_name","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding com.mediatek.filemanager:id/edit_adapter_name using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.mediatek.filemanager:id/edit_adapter_name]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/element 200 30.860 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: --> POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/element/1/click {"id":"1"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/element/1/click 200 280.730 ms - 76 {"status":0,"value":true,"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: --> POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/appium/device/push_file {"path":"/mnt/sdcard/","data":[68,58,92,115,101,46,110,101,110,97,46,110,101,110,97,109,97,114,107,50,46,97,112,107]}
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF push "C:\\Users\\bibek\\AppData\\Local\\Temp\\appium115917-7460-ercmvo.tmp" /mnt/sdcard/
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/appium/device/push_file 200 68.257 ms - 74 {"status":0,"value":"","sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: --> POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/element {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"se.nena.nenamark2.apk\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"se.nena.nenamark2.apk\").instance(0));"}
> info: [debug] Waiting up to 5000ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"se.nena.nenamark2.apk\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"se.nena.nenamark2.apk\").instance(0));","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"se.nena.nenamark2.apk\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"se.nena.nenamark2.apk\").instance(0));","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("se.nena.nenamark2.apk").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("se.nena.nenamark2.apk").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("se.nena.nenamark2.apk").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().description("se.nena.nenamark2.apk").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().description("se.nena.nenamark2.apk").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "se.nena.nenamark2.apk"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@41b02c88
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("se.nena.nenamark2.apk").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().text("se.nena.nenamark2.apk").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().text("se.nena.nenamark2.apk").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "se.nena.nenamark2.apk"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@41a08698
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=se.nena.nenamark2.apk, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=se.nena.nenamark2.apk, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
> info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("se.nena.nenamark2.apk").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("se.nena.nenamark2.apk").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("se.nena.nenamark2.apk").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().description("se.nena.nenamark2.apk").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().description("se.nena.nenamark2.apk").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "se.nena.nenamark2.apk"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@41acb158
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("se.nena.nenamark2.apk").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().text("se.nena.nenamark2.apk").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().text("se.nena.nenamark2.apk").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "se.nena.nenamark2.apk"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@41b9dd30
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=se.nena.nenamark2.apk, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=se.nena.nenamark2.apk, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"No element found","status":7}
> info: [debug] Condition unmet after 25114ms. Timing out.
> info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"No element found"},"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- POST /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f/element 500 25120.032 ms - 195 
> info: --> DELETE /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f {}
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Users\bibek\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [UIAUTOMATOR STDOUT] [CDS]close[4724]
> info: [debug] [UIAUTOMATOR STDOUT] close [socket][/0.0.0.0:4724]
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 30.919
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}
> info: <-- DELETE /wd/hub/session/b3cec698-02ed-4f71-9406-6755f21f501f 200 1334.180 ms - 76 {"status":0,"value":null,"sessionId":"b3cec698-02ed-4f71-9406-6755f21f501f"}

**Comment by Jonahss** [comment]
So what error do you encounter when you try to push the file? The logs look ok.

**Comment by bibekSahoo** [comment]
I am trying to push apk, in sdcard
![screenshot_2015-10-19-22-54-58](https://cloud.githubusercontent.com/assets/9712774/10585355/8814d68e-76b4-11e5-9f79-91687a4e5138.png)
 but a tmp file is pushed which is of some bytes.

**Comment by Jonahss** [comment]
Oh I see, it's pushing a 24 byte file with a weird name, instead of your
app. Hmm.

Ok, can you post this as an issue to the main Appium repo? I'm not sure
it's related to the java client.
You can link this issue in the new issue.

**Comment by bibekSahoo** [comment]
posted the issue in the mainm appium repo below is the link for reference

https://github.com/appium/appium/issues/5741

**Comment by Jonahss** [comment]
Thanks.
We'll keep this issue open until the main issue gets classified as an
appium vs client issue.

**Comment by aniket-21** [comment]
Please see my comment @ appium/appium#5741

**Comment by imurchie** [comment]
This is a matter of the wrong arguments being send. The remote path should be a file, not a directory. Given no file name, appium makes a temporary name and uses that. In terms of the data, it should be the contents of the file, encoded in base64. Not the path. The reason the file is 24 bytes long is that it is just the path given from `app.getAbsolutePath()`.

Closing.
