### ISSUE TITLE
ScrollTo and ScrollToExact methods are not working for android.

### ISSUE THREAD

**Issue by deepakG-optimus** [appium/java-client#260]
I am using 
driver.findElement(MobileBy.AndroidUIAutomator(KeyText));
driver.scrollTo(KeyText);

in keytext i am passing text value on which I want to scroll.

Please provide the exact code in java.

**Comment by saikrishna321** [comment]
@deepakG-optimus 



	public void scrollToExactElement(String str) {
		((AndroidDriver<MobileElement>) driver).findElementByAndroidUIAutomator(
				"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\""
						+ str + "\").instance(0))");
	}

     public void scrollToElement(String str) {
		((AndroidDriver<MobileElement>) driver).findElementByAndroidUIAutomator(
				"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new     UiSelector().textContains(\""
						+ str + "\").instance(0))");
	}


Use of the code:::

           public void scrollToExact() {
		           scrollToExactElement("About phone");
	       }

**Comment by TikhomirovSergey** [comment]
@deepakG-optimus 
Is the problem resolved. Please reopen this issue or open a new one using this template: https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md
