### ISSUE TITLE
Fails to install unlock_apk-debug.apk

### ISSUE THREAD

**Issue by gregorywringle** [appium/java-client#262]
Appiums dies on:

    adb install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

After which capabilities get sent again and cause everything to be clobbered.

Log Snipit

    22:46:22 �[36minfo�[39m: [debug] App is installed
    22:46:22 �[36minfo�[39m: App is already installed, resetting app
    22:46:22 �[36minfo�[39m: [debug] Running fast reset (stop and clear)
    22:46:22 �[36minfo�[39m: [debug] executing cmd: adb shell "am force-stop com.test.test"
    22:46:23 �[36minfo�[39m: [debug] executing cmd: adb shell "pm clear com.test.test"
    22:46:24 �[36minfo�[39m: [debug] Forwarding system:2252 to device:4724
    22:46:24 �[36minfo�[39m: [debug] executing cmd: adb  forward tcp:2252 tcp:4724
    22:46:24 �[36minfo�[39m: [debug] Pushing appium bootstrap to device...
    22:46:24 �[36minfo�[39m: [debug] executing cmd: adb  push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
    22:46:24 �[36minfo�[39m: [debug] Pushing settings apk to device...
    22:46:24 �[36minfo�[39m: [debug] executing cmd: adb  install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
    22:46:24 �[36minfo�[39m: [debug] Pushing unlock helper app to device...
    22:46:24 �[36minfo�[39m: [debug] executing cmd: adb  install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
    22:56:15 �[36minfo�[39m: �[37m<-- POST /wd/hub/session �[39m�[32m-�[39m�[90m - ms - -�[39m �[90m�[39m
    22:56:17 �[36minfo�[39m: �[37m-->�[39m �[37mPOST�[39m �[37m/wd/hub/session�[39m �[90m{"desiredCapabilities":{"app":"test.apk","platformVersion":"5.1.0","udid":"WQJ321JI","platformName":"Android","deviceName":"Nexus 5"}}�[39m
    22:56:17 �[36minfo�[39m: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
    22:56:17 �[36minfo�[39m: Found an existing session to clobber, shutting it down first...
    22:56:17 �[36minfo�[39m: Shutting down appium session
    22:56:17 �[36minfo�[39m: [debug] Pressing the HOME button
    22:56:17 �[36minfo�[39m: [debug] executing cmd: adb  shell "input keyevent 3"
    22:56:18 �[36minfo�[39m: [debug] Stopping logcat capture
    22:56:18 �[36minfo�[39m: [debug] Logcat terminated with code null, signal SIGTERM
    22:56:18 �[36minfo�[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
    22:56:20 undefined
    23:06:17 �[36minfo�[39m: �[37m<-- POST /wd/hub/session �[39m�[32m-�[39m�[90m - ms - -�[39m �[90m�[39m

Appium Command

    /Applications/Appium.app/Contents/Resources/node/bin/node lib/server/main.js --command-timeout 7200 --session-override

Note: Every time I've seen this occur there are about 10 minutes between unlocking and the capabilities being resent.

**Comment by Jonahss** [comment]
Huh.
This looks like an appium issue, not java-client. could you repost the issue there please?
Thanks :)
