### ISSUE TITLE
AppiumLocalService needs to have OutputStream parameter for logging

### ISSUE THREAD

**Issue by smartinovic** [appium/java-client#264]
Currently AppiumLocalService logs to System.err and it is not changeable. It would be better if there is OutputStream parameter for streaming the logs.

**Comment by TikhomirovSergey** [comment]
@smartinovic 
Do you want to save logs to file? Do I clearly understand your problem?

**Comment by smartinovic** [comment]
@TikhomirovSergey 
I don't have problem saving logs to file, for this I use existing method withLogFile().
Problem is that I don't have freedom to set output stream for appium server logs, now they are always logging to error stream and cluttering output of my application.
If that is parametrised, I would be able to choose to write logs into System.err, System.out, log4j or choose any other way that I want to handle these logs.

**Comment by TikhomirovSergey** [comment]
Ok. I'll add the requiled abilty soon.
Do you want this method

> servise.setOutputStream(OutputStream stream)

?

**Comment by smartinovic** [comment]
That looks right. Thanks
