### ISSUE TITLE
Continuos builds/deployment and PR workflow validation improvement

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#269]
In 2014 java_client was the very small library. Since that time it has grown to framework (I think) and it is still growing. Number of contributors increases. 
- 1. We need to automate the building and deployment.
- 2. We need to enhance PR state workflow.

The first we could do with Jenkins CI or [Travis CI](https://travis-ci.org/) (like the Selenium project does).

The second should include:
- the PR checking with CI (it is connected to point 1)
- (optionally) the code style checking

**Comment by bootstraponline** [comment]
- https://github.com/google/google-java-format
- https://github.com/appium/java-client/pull/267#issuecomment-156311112

**Comment by Jonahss** [comment]
parallel testing on Sauce Labs please!
