### ISSUE TITLE
AppiumDriver becomes "stuck" when executing the "getOrientation" command inside webview

### ISSUE THREAD

**Issue by danielputerman** [appium/java-client#271]
Although an error appears in the Appium logs , no exception is thrown from the AppiumDriver instance. Instead, it's keeps on waiting for a response.

Tested using Appium java bindings ver 3.2.0, on Android emulator.  

Logs are available in the following gist: https://gist.github.com/danielputerman/c2321d365d010aee0174

**Comment by TikhomirovSergey** [comment]
Do you perform a test in mobile chrome?

**Comment by danielputerman** [comment]
Yes, sorry, I thought I mentioned it in the description.

**Comment by Jonahss** [comment]
Could you post the issue to the main appium repo? Sounds like an issue with
the server.

**Comment by saikrishna321** [comment]
@danielputerman can you please try with the latest appium and java_client.

**Comment by danielputerman** [comment]
Will do, thanks!

**Comment by SrinivasanTarget** [comment]
@danielputerman This works fine in latest server and client.Here you go https://gist.github.com/SrinivasanTarget/3a8232f3a7a97f0920a581defa97997d#file-webview-orientation-test-L251.

Closing this now.Please feel free to log a new issue with logs in form of gist incase if you hit the same.
