### ISSUE TITLE
NoSign flag + uiautomator

### ISSUE THREAD

**Issue by stonesong** [appium/java-client#275]
Hi, I am using java-client with @AndroidFindBy(uiAutomator = etc.) And it works great, but still appium desired capabilities capabilities.setCapability("noSign", true); is no effective. My map won't appear due to resigning of the apk from appium. I run this on android 4.3. Still the appium doc says "will work only with UiAutomator and not with selendroid". Am I missing anything ? I can't find code samples about this.
Pierre

**Comment by TikhomirovSergey** [comment]
@stonesong Hi
I have some questions
How is __@AndroidFindBy(uiAutomator = etc.)__ connected with  __capabilities.setCapability("noSign", true)__?
Do you get the desired result using
```java
MobileElement e = driver.findElement(MobileBy.androidUIAutomator("your locator"));
//your actions are below
...
```
?

Maybe @Jonahss knows the solution. I think it is the server-side problem.

**Comment by stonesong** [comment]
@TikhomirovSergey It worked !! You were right, I was using WebElement instead of MobileElement and somehow now appium is okay with not resigning my apk ! That's great.

At least it work on my local Appium, then I am also trying with testObject and it does not look like having much effect on their appium server. 

thanks a lot !

**Comment by TikhomirovSergey** [comment]
You also can 

```java
@AndroidFindBy(uiAutomator = etc.)
MobileElement e;
//your actions are below
...
```

That should work too.
So. Can I close this ticket? You are free to close it on your own :)

**Comment by stonesong** [comment]
Sure that's how I did it actually, thanks again for you quick help !
