### ISSUE TITLE
Issue with PageFactory set up in Appium

### ISSUE THREAD

**Issue by niranjanparija** [appium/java-client#277]
I have a Framework Set up with Silk Mobile but we want to migrate the entire set up to Appium.I am stuck with the PageFactory set up for Android and iOS as it is not at possible to reuse the same Pagefactory with Appium. Need yours quick help and suggestions on this.

**Comment by TikhomirovSergey** [comment]
@niranjanparija Please provide more details. I can't figure out what happens.

Please attach to this ticket samples of your client code (with comments if it is possible), server output, error stacktraces as gists. 

https://help.github.com/articles/creating-gists/

**Comment by TikhomirovSergey** [comment]
Also please provide info about your client and server versions

**Comment by niranjanparija** [comment]
Please find the URL for the gists: 
https://gist.github.com/niranjanparija/2a8fe8b78960015d1bcf
and suggest

**Comment by TikhomirovSergey** [comment]
@niranjanparija 
These samples don't show how do you use Selenium PageFactory class. Do you use it at all?
[Oficial document with description] (https://code.google.com/p/selenium/wiki/PageFactory)

[API](https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/PageFactory.html)

[API full package](https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/)

[Appium common description](https://github.com/appium/java-client/pull/68)

[Appium samples](https://github.com/appium/sample-code/tree/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object)

[A new feature that is coming out](https://github.com/appium/java-client/pull/267)

**Comment by niranjanparija** [comment]
I just updated the code snippets which I want to run by referring the PageObjects and PageElements mentioned earlier with Appium.Please check this once if at all it can help you to understand the issue.
https://gist.github.com/niranjanparija/3b706105004065236878

**Comment by TikhomirovSergey** [comment]
I think that it is totally not connected with Appium or Selenium Webdriver. 
Here is the exception text:
https://gist.github.com/niranjanparija/3b706105004065236878#file-gistfile1-txt-L113

It means that Reflection API can't find the convinient constructor. Available constructors:

https://gist.github.com/niranjanparija/3b706105004065236878#file-issue-with-pagefactory-set-up-in-appium-277-L343

https://gist.github.com/niranjanparija/3b706105004065236878#file-issue-with-pagefactory-set-up-in-appium-277-L363

>and PageElements mentioned earlier with Appium

I'm really not sure that it works. AndroidDriver and IOSDriver fetch implementations of org.selenium.WebElement.

**Comment by TikhomirovSergey** [comment]
@niranjanparija Please reopen this issue/open a new one if you'll find some details which directly connected to Appium.
