### ISSUE TITLE
Can someone help with how to use Enterprise signed ipa profile to test on Appium Successfully.

### ISSUE THREAD

**Issue by niranjanparija** [appium/java-client#282]
I have an .ipa file from developer with an Enterprise Distribution profile signed.But running this in Appium I got an error that "the App must be signed with a developement Identitiy".So,could not continue with the test.
Can someone help with how to use Enterprise signed ipa profile to test on Appium Successfully.

**Comment by Jonahss** [comment]
Apple only allows testing to be done using Development signed .app files. Sorry.

**Comment by niranjanparija** [comment]
Thanks John for the information.But can you please provide us any information on difference between Enterprise Distribution Profile and Development Signed App and the reason for being it is not possible to run the app with an Enterprise distribution profile signed with Appium.

**Comment by Jonahss** [comment]
I suggest you read up on iOS app code signing. Once you are familiar with
the premise and details involved, hopefully the limitations with Appium
will make more sense to you :)
http://seventhsoulmountain.blogspot.com/2013/09/ios-code-sign-in-complete-walkthrough.html
https://gigaom.com/2015/02/07/how-ios-developers-use-code-signing-to-get-their-apps-on-iphones/

Appium uses Apple's device-testing frameworks to automate iOS devices.
Apple has built-in checks, and the programs which allow us to automate iOS
will not run if an app is not signed with a Developer certificate.
