### ISSUE TITLE
java-client-3.3.0  - Cannot not start a new session using service.start().   $ANDROID_HOME ?

### ISSUE THREAD

**Issue by mkataokaelementum** [appium/java-client#286]
java-client-3.3.0 

I could not start a new session using service.start().  service.start() works locally on my laptop, but does not work on the Jenkins machine.  The error message is "The ANDROID_HOME environment variable is not set to the Android SDK root directory path", even though I have $ANDROID_HOME set properly as below.  

*** Question 
Is the error happening because Android_home is not under /Users/<username>/Library/Android/sdk ? 

*** Jenkins machine: 

el-mbp15-mv-server-111-C02KP4FNDV33-00111:~ jenkins$ echo $ANDROID_HOME
/usr/local/opt/android-sdk
el-mbp15-mv-server-111-C02KP4FNDV33-00111:~ jenkins$ cat ~/.bash_profile
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/bin:$PATH"
export ANDROID_HOME=/usr/local/opt/android-sdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/

*** Error from Jenkins

[36minfo[39m: [debug] Creating new appium session fc064d02-0807-4a25-b5a4-556ba951b7df
[36minfo[39m: Starting android appium
[36minfo[39m: [debug] Getting Java version
[36minfo[39m: Java version is: 1.8.0_65
[36minfo[39m: [debug] Checking whether adb is present
[33mwarn[39m: The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[36minfo[39m: [debug] executing cmd: which adb
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
[36minfo[39m: [debug] Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:126:12)
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at maybeClose (internal/child_process.js:819:16)
    at Socket.<anonymous> (internal/child_process.js:320:11)
    at emitOne (events.js:78:13)
    at Socket.emit (events.js:170:7)
    at Pipe._onclose (net.js:470:12)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.)","origValue":"Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path."},"sessionId":null}

**Comment by mkataokaelementum** [comment]
Provided additional info just in case..  Please let me know if I was doing something wrong below. 

public class NewCreateIssueTest extends TestUnitBase {

    AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
....

    @BeforeTest
    public void beforeTest() throws Exception {
        service.start();
...
   }

    @AfterTest
    public void afterTest() throws IOException {
        doAfterMethod();
        doTeardown();
        service.stop();
    }
...
}

**Comment by mkataokaelementum** [comment]
Additional info from my Jenkins shell script.. 

#!/bin/bash -x
export PATH=$PATH:/usr/local/bin

# Kill all running appium and genymotion processes
ps -ef | grep Geny | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep appium | grep -v grep | awk '{print $2}' | xargs kill -9
sleep 10

export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH=$PATH:/usr/local/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools/
adb devices
echo $PATH
echo $ANDROID_HOME

**Comment by TikhomirovSergey** [comment]
@mkataokaelementum 
I'm going to reproduce this issue.. Thanks for the detailed report.

**Comment by mkataokaelementum** [comment]
Thanks for your comment.  Hmmm...Do I need to reinstall Android SDK?

**Comment by TikhomirovSergey** [comment]
@mkataokaelementum 
Ok. Thanks a lot for the answer.
It was expected that it is not the problem of Appium. So I'm closing this issue.
