### ISSUE TITLE
isAppInstalled return always true 

### ISSUE THREAD

**Issue by RoyGeagea** [appium/java-client#287]
Hello,
i'm using driver.isAppInstalled(bundleid), but this function return always true in case the app is installed the ios device or not

**Comment by SrinivasanTarget** [comment]
@RoyGeagea @TikhomirovSergey It works fine as expected. @RoyGeagea Can you update gist logs url  here? Also provide us more info like appium server and client version

**Comment by TikhomirovSergey** [comment]
@RoyGeagea 
Is the problem still here? Please reopen this issue or open a new one using this template: https://github.com/appium/java-client/blob/master/ISSUE_TEMPLATE.md
