### ISSUE TITLE
zoom gestures are not working

### ISSUE THREAD

**Issue by kkhaidukov** [appium/java-client#288]
I'm trying to use AppiumDriver's `zoom` methods and they seem broken:
1. `zoom(WebElement el)` does nothing (i.e. the expected zoom gesture is not performed)
2. `zoom(int x, int y)` causes an exception, probably due to an incorrect usage of moveTo call

**Comment by kkhaidukov** [comment]
I've created a pull request for this -- https://github.com/appium/java-client/pull/289

**Comment by Jonahss** [comment]
Merged :)
Will publish in next version.

**Comment by kkhaidukov** [comment]
thanks!
