### ISSUE TITLE
Did not return correct element

### ISSUE THREAD

**Issue by medy75** [appium/java-client#292]
In forum:
Comment:
> Some comment in forum, but its too... (See more)

If I try 
> def comments: List[AndroidElement] = drvr.findElementsById(COMMENT_TEXT).toList
> comments(0).getText

I get "Some comment in forum, but its too...". Its OK.
But If I click on See more button, comment text is now complete ->

> Some comment in forum, but its too long to see it in its entire form.

And try

> def comments: List[AndroidElement] = drvr.findElementsById(COMMENT_TEXT).toList
> comments(0).getText

I get same response as before "Some comment in forum, but its too..." but its not true.

Is there some cahce to be cleared before?

**Comment by medy75** [comment]
Tested on java-client 3.3.0 with Appium 1.4.16.1 on Windows and with Appium 1.4.13 (Draco) on Mac.

**Comment by TikhomirovSergey** [comment]
Hi @medy75 
Can you provide more details? Client code samples, server output (it is cool to make gists).

**Comment by Jonahss** [comment]
Yeah I don't think this would be a java-client bug. It sounds more like an issue with how iOS or Android works (is it iOS or Android)?

After clicking the "see more" link, run `driver.getSource()` and take a look at the xml source of the page. What is the text of the comment there?

This would be a bug with appium, not the java-client, so please create an issue on the main Appium repo and include the details here.
