### ISSUE TITLE
Not able to build project locally

### ISSUE THREAD

**Issue by saikrishna321** [appium/java-client#294]
@TikhomirovSergey i was unable to build the project locally. I cloned the java_client and ran the the command 

```
mvn clean install -Dmaven.test.skip=true
```
 Please check the gist for errors.

https://gist.github.com/saikrishna321/03f85f7bfce8d2199f7d

More Info:
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T17:27:37+05:30)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"

```

**Comment by TikhomirovSergey** [comment]
I'm not sure that it is the bug. Some changes of Java 8 break javadoc generation

http://stackoverflow.com/questions/26049329/javadoc-in-jdk-8-invalid-self-closing-element-not-allowed
https://bugs.openjdk.java.net/browse/JDK-8020619

However, I think this thing should be fixed. Especially if the new java_client build will be migrated to JDK8.
