### ISSUE TITLE
How to detect facebook login window?

### ISSUE THREAD

**Issue by drapostolos** [appium/java-client#295]
I'm testing an app (on Android) which connects/login to facebook. I'm testing the scenario where the Facebook app is NOT installed on device. When I click on the "connect to facebook" button in my app, the "facebook login" appears (using the web interface. See image below). But for some reason appium can not detect it. 

Is there anything special I need to do to detect it? This prevents me from providing the login credentials and log in :(

![image](https://cloud.githubusercontent.com/assets/2085564/12447956/3c7b95c0-bf73-11e5-9a60-de414a26f56a.png)

Calling AdroidDriver.getPageSource(), gives me this (which I guess is the page source for my app, not the facebook login popup. My app uses OpenGL so no elements should be available):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<hierarchy rotation="0">
	<android.widget.FrameLayout index="0" text=""
		class="android.widget.FrameLayout" package="com.***"
		content-desc="" checkable="false" checked="false" clickable="false"
		enabled="true" focusable="false" focused="false" scrollable="false"
		long-clickable="false" password="false" selected="false" bounds="[0,0][480,800]"
		resource-id="" instance="0">
		<android.widget.LinearLayout index="0"
			text="" class="android.widget.LinearLayout" package="com.********"
			content-desc="" checkable="false" checked="false" clickable="false"
			enabled="true" focusable="false" focused="false" scrollable="false"
			long-clickable="false" password="false" selected="false" bounds="[0,0][480,800]"
			resource-id="" instance="0">
			<android.widget.FrameLayout index="0"
				text="" class="android.widget.FrameLayout" package="com.********"
				content-desc="" checkable="false" checked="false" clickable="false"
				enabled="true" focusable="false" focused="false" scrollable="false"
				long-clickable="false" password="false" selected="false" bounds="[0,38][480,800]"
				resource-id="android:id/content" instance="1">
				<android.widget.FrameLayout index="0"
					text="" class="android.widget.FrameLayout" package="com.********"
					content-desc="" checkable="false" checked="false" clickable="false"
					enabled="true" focusable="false" focused="false" scrollable="false"
					long-clickable="false" password="false" selected="false" bounds="[0,38][480,800]"
					resource-id="" instance="2">
					<android.widget.LinearLayout index="0"
						text="" class="android.widget.LinearLayout" package="com.********"
						content-desc="" checkable="false" checked="false" clickable="false"
						enabled="true" focusable="false" focused="false" scrollable="false"
						long-clickable="false" password="false" selected="false" bounds="[0,38][480,800]"
						resource-id="" instance="1" />
					<android.widget.ImageView NAF="true"
						index="1" text="" class="android.widget.ImageView" package="com.********"
						content-desc="" checkable="false" checked="false" clickable="true"
						enabled="true" focusable="false" focused="false" scrollable="false"
						long-clickable="false" password="false" selected="false" bounds="[0,38][44,82]"
						resource-id="" instance="0" />
				</android.widget.FrameLayout>
			</android.widget.FrameLayout>
		</android.widget.LinearLayout>
	</android.widget.FrameLayout>
</hierarchy>
```

I use java_client 3.1.0 and appium (server) 1.4.16 (on windows)

**Comment by pr4bh4sh** [comment]
Refer this https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by drapostolos** [comment]
Thx, I'll have a look at it. 
But I don't see how that will help me use appium to click on the facebook login popup? Why can't appium click on the facebook login popup? Are there any settings I need to do first? like setting. Any hints?

**Comment by amitjaincoer191** [comment]
@drapostolos
If popup opens as a webview inside your android app you can handle it using Appium. 
You need to get app build and ask devteam to set this "setWebContentsDebuggingEnabled" property and rebuild app. Then u will see webview context and switching context to webview you can handle fb pop up.
https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by drapostolos** [comment]
aha! thx! I will look into that!

**Comment by ErikMedina** [comment]
I have the same problem like you, drapostolos. Did you fix it? I'd appreciate some help with this problem. Thanks!

**Comment by drapostolos** [comment]
Not yet. Still waiting for developers to set the "setWebContentsDebuggingEnabled" property (they need to bump the android API version first to set this property). I hope this will solve the problem.

**Comment by drapostolos** [comment]
I will post back as soon as I have been able to try the "setWebContentsDebuggingEnabled" property solution.

**Comment by drapostolos** [comment]
Setting the  `setWebViewDebugEnabled` to true solved my problem.
