### ISSUE TITLE
Is it possible to switch wifi networks

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/java-client#298]
Hi @jlipps , @Jonahss , @TikhomirovSergey 

While executing my test suite I have to switch between two networks. Is it possible through Appium?
In the middle of the execution I have to change my wifi connection from Network_1 to Network_2 and after completing a specific test case I have to change the wifi back to Network_1 from Network_2. 
Please let me know if it possible through Appium or from iDevice Settings .

**Comment by TikhomirovSergey** [comment]
@shivakrishnach31 sorry for the late response.
Is this method not convinient
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L230
?

Also we have these things
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/NetworkConnectionSetting.java#L53

Do you need to do it on iOS?

**Comment by shivakrishnach31** [comment]
Thanks for the response @TikhomirovSergey , 

Yes, I need to do it on iOS? The links you provided may not works with iOS I believe. Could you please suggest me a way to achieve my scenario.

Thanks in Advance.

**Comment by TikhomirovSergey** [comment]
@shivakrishnach31 sorry for the late response.
We can to try to implement this feature. Now this issue is the feature/enhancement request.

**Comment by shivakrishnach31** [comment]
Thanks for the response @TikhomirovSergey .
Could you make it available ASAP many people are asking for this feature in many forums.

**Comment by TikhomirovSergey** [comment]
Ok. I will start to do it on this week.

**Comment by shivakrishnach31** [comment]
@TikhomirovSergey, Have you started implementing it. 70% of my tests are on hold due to this limitation. If you implement it, it would be really really great thing. And I can continue my test development. Please...

**Comment by TikhomirovSergey** [comment]
I had started to work on it. But I needed to publish build 3.4.0. But it seems that it is not so easy to resolve this problem because it requires a bit redesign current API. 

Anyway it is high-priority task now and fix will be published at 3.4.1

**Comment by TikhomirovSergey** [comment]
@shivakrishnach31 
I have news. One is bad and one is good.

- The bad one: 
No one of these commands works with iOS. They are not implemented by Appium iOS-tools

```
rest.post('/wd/hub/session/:sessionId?/appium/device/toggle_airplane_mode', controller.toggleFlightMode);
rest.post('/wd/hub/session/:sessionId?/appium/device/toggle_data', controller.toggleData);
rest.post('/wd/hub/session/:sessionId?/appium/device/toggle_wifi', controller.toggleWiFi);
rest.post('/wd/hub/session/:sessionId?/appium/device/toggle_location_services', controller.toggleLocationServices);
...
rest.get('/wd/hub/session/:sessionId?/network_connection', controller.getNetworkConnection);
rest.post('/wd/hub/session/:sessionId?/network_connection', controller.setNetworkConnection);
```

I've asked a question to people that develop server as well I've tried them on my own. 

So this is available for Adroid for now.

- The good one:

@shivakrishnach31 
Have you tried the **Network Link Conditioner** 

http://stackoverflow.com/questions/1614802/simulate-airplane-mode-in-iphone-simulator

http://nshipster.com/network-link-conditioner/

http://useyourloaf.com/blog/network-link-conditioner/

@imurchie What do you think about the using of this tool on server side. At this case it would be possible to play with simulator connections I think.

**Comment by email2vimalraj** [comment]
I like the idea about using Network Link Conditioner tool.

Thanks
Vimal

**Comment by SrinivasanTarget** [comment]
:+1:

**Comment by pavanbachu0604** [comment]
@TikhomirovSergey : Is there any fix on this issue ?

**Comment by SrinivasanTarget** [comment]
@pavanbachu0604 Unfortunately no but may be WDA might have some solution for this.We need to way for it.

**Comment by anand853** [comment]
is this impletemened? how to switch between networks in the app ? (for Android)?

**Comment by anand853** [comment]
@saikrishna321 , did you get any update on this thread ?
looks like the feature is not available for Android

**Comment by SrinivasanTarget** [comment]
Nothing we could do about it unless it is natively supported. PR's are welcome at server end.

**Comment by raghavbajoria** [comment]
@SrinivasanTarget Hi, were you able to solve the above problem? I am stuck in this situation and could not find any possible solution..

**Comment by adityabhargav** [comment]
Hi @raghavbajoria ,

use -> https://github.com/steinwurf/adb-join-wifi
