### ISSUE TITLE
getting java.lang.NoClassDefFoundError when using AppiumDriver constructor 

### ISSUE THREAD

**Issue by MariaSoluto** [appium/java-client#30]
This is the error stack I get:

FAILED: AndroidApp_ReturnUserLogsIn_ValidateMainPage
java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClients
    at io.appium.java_client.ComplexFind.<clinit>(ComplexFind.java:15)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:46)

At this line:
        driver = new AppiumDriver(url , capabilities);

I just upgraded to Appium 1.0, Selenium 2.41. The version of the java-client of Appium is 1.2.0.

**Comment by jyothiptw** [comment]
please any one help ,I an getting following
 java.lang.ClassNotFoundException error when i have remove some jar on lib folder.which jar has to add to avoid this exception

**Comment by staplesj** [comment]
I am getting this same error, using java-client : 6.0.0-BETA2

**Comment by vikramvi** [comment]
@staplesj it will be nice to create new issue; instead of commenting on closed issue, as majority of times it gets ignored

**Comment by staplesj** [comment]
@vikramvi - I am sure it would be lovely!!
