### ISSUE TITLE
Android emulator doesn't get launched automatically like iOS simulator

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#300]
Hi,
I am trying simple script mentioned in https://github.com/appium/sample-code

Below code launches XCode simulator and continue with test case execution

        capabilities.setCapability("platformVersion", "9.2");
        capabilities.setCapability("deviceName", "iPhone 5");
        capabilities.setCapability("app", app.getAbsolutePath());
        driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

but similarly it doesn't launch Android emulator automatically with below code

        capabilities.setCapability("platformVersion", "6.0");
        capabilities.setCapability("deviceName","Android Emulator");
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("appPackage", "com.example.android.contactmanager");
        capabilities.setCapability("appActivity", ".ContactManager");
        driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

Instead ut keeps on looking for connected emulator / device and times out?

Is this a bug ? or am I missing something.

Please look into this and clarify

Thanks,
Vikram

**Comment by Jonahss** [comment]
Appium has never started Android Emulators automatically.
You could add this as a feature request to appium by creating an issue on the main appium github repo.

For now, appium just detects emulators already running, and devices which are connected via usb.

**Comment by vikramvi** [comment]
@Jonahss any historical reasons for not starting given android simulator like it does in case of iOS simulator ?

I had started server externally with command appium without any flags

thanks in advance.

**Comment by Jonahss** [comment]
The historic reason would be that we never intended to start any emulators/simulators, but iOS UIAutomation Instruments automatically launches the sim for us. So appium didn't add logic for that (and didn't really have a choice).

I personally like it that way, and think it's a good idea to add this as a feature to the Android Driver.

**Comment by amitjaincoer191** [comment]
I also agree in iOS its underlying instruments framework that automatically invoke Simulator.
Incase of Android UIAutomator does not do so.. 

You can also use below code to start it using java program
@Test
	public void launchAVD() throws InterruptedException, IOException {
		ProcessBuilder pbEmulator = new ProcessBuilder("emulator", "-avd", "EmulatorName");
		Process pcEmulator = pbEmulator.start();
		pcEmulator.waitFor();
		
		ProcessBuilder pbADB = new ProcessBuilder("adb", "devices");
		Process pcADB = pbADB.start();
		pcADB.waitFor();
		
		InputStream is = pcADB.getInputStream();
		InputStreamReader isr = new InputStreamReader(is);
		BufferedReader br = new BufferedReader(isr);
		String line;
		String adb = new String();
		
		while ((line = br.readLine()) != null) {
		    if (line.length()>0)
			line += br.readLine();
		    System.out.println(line);
		}
	
		if (adb.contains("emulator-5554") && (!adb.contains("offline"))) {
			System.out.println("Device is connected");	
		}
	}

**Comment by vikramvi** [comment]
Thanks  @amitjaincoer191 for detailed answer & clarification.

Regards,
Vikram
