### ISSUE TITLE
Non-Latin and special symbols support

### ISSUE THREAD

**Issue by VizanArkonin** [appium/java-client#303]
Greetings, folks.

I have a question - is there a way to correctly process/decode the special or Non-Latin symbols using the Java client?

I work with the app that supports Spanish language, and in most cases both navigation (by name or XPath, that will contain the Espanol symbols) and contents comparison doesn't seem to go along fine.
I used the Python client before, which didn't had any of those issues, and i'm not a Java-expertise, so i'm not sure if it's something to do with the client or it's something language-related.

Thanks in advance!

**Comment by TikhomirovSergey** [comment]
Hi @VizanArkonin 
You just neen to pass these capability through constructor I think

- "unicodeKeyboard"

I'm going to add this to MobileCapabilityType. The same is going to be done for C# client.
https://github.com/appium/appium-dotnet-driver/issues/131

**Comment by VizanArkonin** [comment]
Hi Sergey,
Yeah, i tried that option. Even though i keep all project filed UTF-8 encoded, it doesn't seem to help much.
For instance - that's how one of XPath's coded:
 - //android.view.View[contains(@content-desc,'¿No es un miembro registrado?')]
And that's how Appium server shows it in console:
 - //android.view.View[contains(@content-desc,'Ã‚Â¿No es un miembro registrado?')]
Same happens with both espanol letters but with special symbols like ™, © and such.

I'd be happy to use some more versatile navigation (by ID, for instance), but that's pretty poor-processed hybrid app, so that's the only option.

Cheers!

**Comment by TikhomirovSergey** [comment]
@imurchie
Can you advice something?

**Comment by imurchie** [comment]
Within selectors? I don't think there is a way to do that. UI Automator strips the characters out.

**Comment by VizanArkonin** [comment]
Oh, got it. Thanks!

Just one more question, then - if i pull the contents of some object, which contains that Espanol text (for instance, getAttribute("name") on the WebElement), will it preserve those symbols or they're going to be stripped too? Or it only applies to the selectors?

**Comment by imurchie** [comment]
I'm not exactly sure. If you try it, would you let me know? Thanks!

**Comment by VizanArkonin** [comment]
That one is weird.
I made a quick-test, that will pull the text contents of the element and print it (1), then print the probe (for comparison) (2) and then perform a simple boolean 1 == 2.
Here's the result:
- Términos
- Términos
- false

So it seems to preserve those symbols, but it can't be used for comparison tests (my guess - something to do with encoding). Changing the project files encoding doesn't help either.

**Comment by imurchie** [comment]
Ah!

Yes, it has to do with normalization of the encoding. See https://docs.oracle.com/javase/tutorial/i18n/text/normalizerapi.html

**Comment by VizanArkonin** [comment]
Thanks for the link!
That wasn't the issue, but that pointed my thoughts in the right direction :)
I solved most parts of navigation and string comparison by forcing the UTF-8 encoding to every single file in project (for IDEA - Settings -> Editor -> File Encodings), as well as setting the IDE and Project encoding to UTF-8.
The only navigation issue remaining only covers some letters, that failed to convert, like:
 - //android.widget.Button[@content-desc='Men�']

Other XPaths' seem to work just fine - Appium console still shows those weird symbols ('Ã‚Â), but successfully finds the element.

Thank you for the input, friends! I think for me, this case is closed :)

**Comment by TikhomirovSergey** [comment]
Ok!
Please reopen this ticket if you find some related problems.
