### ISSUE TITLE
AppiumServiceBuilder throws InvalidServerInstanceException with Appium node 1.5.0.x

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#305]
AppiumServiceBuilder throws InvalidServerInstanceException because the location of the file appium.js is changed with the new major version. 

[This pattern](https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java#L45) should be more fluent and compatible with higher and lower appium-node versions.

**Comment by TikhomirovSergey** [comment]
#302

**Comment by rompic** [comment]
@TikhomirovSergey when will this be released?
