### ISSUE TITLE
DatePicker Issue with Appium for Android Driver

### ISSUE THREAD

**Issue by niranjanparija** [appium/java-client#312]
Hi,I am facing issues to select date from the datepicker with Appium for Android Driver.Please check the attached screenshots of the Calender I am looking for.

I have already tried with element.clear() followed by element.sendkeys("text"),but its not working.

Also I tried to work with Scroll to followed by TouchAction ,where its working till selecting the Year ,but after that its failed to select the date and month which should be selected from the screenshot named as DatePicker2.

Can anyone please suggest me any workout .
![daypicker1](https://cloud.githubusercontent.com/assets/16086474/12818424/ca115e9c-cb4e-11e5-80fe-9549fe8fed32.PNG)
![daypicker2](https://cloud.githubusercontent.com/assets/16086474/12818434/d02ac8fe-cb4e-11e5-9c04-276ed3f4d56f.PNG)
![daypicker3](https://cloud.githubusercontent.com/assets/16086474/12818445/d3850f8c-cb4e-11e5-9ad6-2a30078fe244.PNG)

**Comment by niranjanparija** [comment]
@TikhomirovSergey - can you please guide on this issue

**Comment by TikhomirovSergey** [comment]
@niranjanparija 
Sorry for the late response.
Honestly, I think it is not the problem of appium java client or server.

Similar problems could be resolved using jQuery (browser automation). I think that UI automation/android command line/javascript could help you.

http://stackoverflow.com/questions/24679937/selectvalue-on-date-picker-does-not-work
http://developer.android.com/reference/android/app/DatePickerDialog.html
http://stackoverflow.com/questions/29982202/how-to-deal-with-datepicker-in-appium-android

**Comment by niranjanparija** [comment]
@TikhomirovSergey - Unfortunately tries with all these,and nothing works.Please let me know if any other solution can be tried of for this.

**Comment by SwamiShekhar** [comment]
@TikhomirovSergey  @niranjanparija  I am also facing similar issue. http://stackoverflow.com/questions/34527606/how-to-interact-with-time-picker-which-is-in-linearlayout
Let me know if i can solve this issue

**Comment by Dharmendrapawar** [comment]
Hi Niranjanparija and SwamiShekar,

Even i am stuck with this problem, i need to handle data picker in my application. How to do it ? If you guys have found any solution, please help me.

**Comment by saikrishna321** [comment]
I have similar date picker in ma app and I was able to select the date, haven't tried with year.will try n get back.

can you post the code which helped you scroll n select the year and which didn't work on selecting the date

**Comment by mondalasim19** [comment]
Facing the same problem
Able to performing scrolling but not able to select the item.
Can anyone help please?

**Comment by kbalakumar99** [comment]
@saikrishna321  @mondalasim19 @Dharmendrapawar @SwamiShekhar @niranjanparija 

I have found the solution for this. Sharing the code snippets here.

`
	public void setDate_android(String day, String month, String year)
	{
		tap("Id", "android:id/date_picker_header_year");
		findElementInList("Id","android:id/date_picker_year_picker","Text",year,"10","down");
//		Date today = Calendar.getInstance().getTime();
		int diff = Integer.parseInt(month) - Calendar.MONTH;
		if(diff<0)
		{
			tapNTimes("Id", "android:id/prev", String.valueOf(Math.abs(diff)));
		}else
		{
			tapNTimes("Id", "android:id/next", String.valueOf(diff));
		}
		tap("Text", day);
		tap("Text", "Set")
	}

	public void findElementInList(String listType, String listId, String elementType, String elementId, String noOfScrolls, String direction)
	{
		MobileElement element = null;
		for (int i = 0; i <= Integer.parseInt(noOfScrolls); i++) 
		{
			try {
				element = findElement(elementType, elementId);
			} catch (NoSuchElementException e) {
				if(i<Integer.parseInt(noOfScrolls))
				{
					switch (direction) 
					{
					case "down":
						swipe_BottomToTop(listType, listId);
						break;
					case "up":
						swipe_TopToBottom(listType, listId);
						break;
					case "left":
						swipe_LeftToRight(listType, listId);
						break;
					case "right":
						swipe_RightToLeft(listType, listId);
						break;
					default:
						swipe_BottomToTop(listType, listId);
						break;
					}
					continue;
				}else
				{
					throw new NoSuchElementException("Element could not be found in the list");
				}
			}
			element = findElement(elementType, elementId);
			element.tap(1, 1);
			break;
		}
	}

	public void tap(String type, String id)
	{		
//		action.tap(findElement(type, id));
		findElement(type, id).tap(1, 1);
	}

	public void tapNTimes(String type, String id, String noOfTimes)
	{
		MobileElement el = findElement(type, id);
		for (int i = 0; i < Integer.parseInt(noOfTimes); i++) 
		{
			el.tap(1, 1);
		}
	}`

**Comment by kbalakumar99** [comment]
It would be better if the sendKeys work for this calendar view. @TikhomirovSergey  Think of it

**Comment by kbalakumar99** [comment]
But, I am facing a different problem here. After setting the date, I could not find any elements in the page. I can get the elements in the page only after tapping/swiping a location in the screen using location attributes. Anyone facing the similar issue??

**Comment by Dharmendrapawar** [comment]
kbalakumar99 , Thank you so much. The code snippet which you have posted above, do i need to put those methods in a separate class and call "setDate_ android" method whenever it is required to select date from date picker ???

please answer

**Comment by kbalakumar99** [comment]
@Dharmendrapawar  Yes. You can use those methods. I just gave it as reference to the actual method 'setDate_android'

**Comment by Dharmendrapawar** [comment]
BalaKumar,

Can you please tell me, why have you used String type and String Id as parameters in tap, tapNTimes and swipe_BottomToTop methods. and also there are so many parameters in findElementInList method.

Could you please explain? I am confused.

many thanks in advance

**Comment by kbalakumar99** [comment]
It is used as string for my convenience. You can modify it as per your requirement

**Comment by Dharmendrapawar** [comment]
Hi BalaKumar,

I still have some doubts, Could you please share me your email Id, so that i could communicate with you via email privately.

Many thanks in advance,

**Comment by Dharmendrapawar** [comment]
Hi BalaKumar,

I will share the UI Automator dump and Screen shot of the calendar, can you please modify the above code accordingly ?

please do the needful,

**Comment by hemano** [comment]
This works for me all the time.

```
    scrollKeys(new String[]{date, mon, year});

    // Generic scroll using send keys
    // Pass in values to be selected as a String array to the list parameter
    // Method will loop through looking for scroll wheels based on the number of
    // values you supply
    // For instance Month, Day, Year for a birthday would have this loop 3 times
    // dynamically selecting each scroll wheel
    // Code here shouldn't be modified
    public void scrollKeys(String[] list) {

        By meX = By.xpath("//android.widget.EditText[@resource-id='android:id/numberpicker_input']");

        int i = list.length - 1;
        for (; i >= 0; i--) {

            waitForElement(driver.findElement(meX));
            MobileElement me = (MobileElement) driver.findElements(meX).get(i);

            TouchAction touchAction6 = new TouchAction(driver);
            touchAction6.longPress(me, 1000).release();
            (driver).performTouchAction(touchAction6);

            if(driver.getSessionDetails().get("platformVersion").equals("6.0.1")){
                (driver).getKeyboard().pressKey(list[i] + "");
            }else {
                driver.getKeyboard().sendKeys(list[i]);
                driver.getKeyboard().sendKeys(list[i]);
            }
        }

        //Extra action to make sure the desired option is selected
        MobileElement me = (MobileElement) driver.findElements(meX).get(i + 1);
        me.click();
    }
```
