### ISSUE TITLE
Create WIKI

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#321]
- There are many questions which could not be asked if there was WIKI.
- It is not convenient to search for issue/PR. Information should be aggregated.
- It is convenient to add here links to related projects and useful articles.

**Comment by TikhomirovSergey** [comment]
#274

**Comment by TikhomirovSergey** [comment]
#337

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/issues/351

**Comment by namannigam** [comment]
#355

**Comment by TikhomirovSergey** [comment]
WIKI was finally completed. Now we need to actualize it when it is needed.
