### ISSUE TITLE
Android 6.x Webview undefined when switching context

### ISSUE THREAD

**Issue by elpipso** [appium/java-client#324]
Hi,

I've got sometimes "WEBVIEW_undefined" on AndroidDriver.getContextHandles().

Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            if (contextName.contains("WEBVIEW")){
                driver.context(contextName);
            }
        }

The issue is resolved in javascript project "appium-android-driver" => https://github.com/appium/appium-android-driver/commit/0c0dbe989ab29ce1e8fb3c48151232c8beedfa7d

I'm using :
- appium/java-client commit e0958c7 (latest)
- Cordova application
- Android device version 6.0.1
- Android device model Nexus 6
- Appium server 1.5 in docker container

I hope you have enough details !

Thanks in advance.

**Comment by dmlemeshko** [comment]
Hi @elpipso, I observe the same issue (appears randomly on my Nexus 5) and I guess it will be faced until this [6007](https://github.com/appium/appium/pull/6007) is merged.

**Comment by dhirenmudgil** [comment]
I am also facing the same on android 6.x

**Comment by MrAppium** [comment]
I've been experiencing the same issue only on Android 6.*

**Comment by nikhil-dabhade** [comment]
+1 for this issue on Android 6.x

**Comment by r0850n** [comment]
+1 Android 6.x  I can switch to webView but after call driver.getPageSource i get error

**Comment by prichopra** [comment]
Hi All,

Is there any update on this issue?

**Comment by TikhomirovSergey** [comment]
I suppose that this issue has been fixed. Please reopen is not everything is ok.
