### ISSUE TITLE
can we identify that the script is running on device or simulator

### ISSUE THREAD

**Issue by Sreeshail** [appium/java-client#330]

**Comment by TikhomirovSergey** [comment]
@Sreeshail 
What do you mean?
Please provide some details.

**Comment by Sreeshail** [comment]
can we find whether the code we are running/executing is on the device or simulator

**Comment by TikhomirovSergey** [comment]
I think it is imposible to detect is it a simulator or device by default. You can define a device name or id, but I think you can't get from a  driver what is this (device or similator)?

However, @imurchie 
has server an ability to extract a device name where an app is run?

**Comment by Sreeshail** [comment]
Are you telling about the UDID of the device to be checked

**Comment by TikhomirovSergey** [comment]
> Are you telling about the UDID of the device to be checked
Yep

**Comment by imurchie** [comment]
There is no mechanism of querying that info from the server, no. The test requested the environment, so it should know anyway.

**Comment by TikhomirovSergey** [comment]
So I'm closing this ticket...
