### ISSUE TITLE
Invoking methods inside Activity

### ISSUE THREAD

**Issue by vbhojaraja** [appium/java-client#331]
## Description

How to invoke the methods inside a particular Activity for Native Apps.

**Comment by TikhomirovSergey** [comment]
Hi @vbhojaraja 
What do you mean? Could you add a sample of code which java_client should support? Are you talking about intends?

**Comment by TikhomirovSergey** [comment]
@vbhojaraja 
Please formulate your question correctly and then reopen this ticket/open a new one.
