### ISSUE TITLE
[Appium 1.5] removeApp doesn't remove app from iOS device

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/java-client#332]
## Description
removeApp doesn't remove app from iOS device

## Environment

* java client build version or git revision if you use some shapshot: 3.4.0
* Appium server version or git revision you is use some shapshot: 1.5 source
* Desktop OS/version used to run Appium if necessary: OS X El capitan
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 5.7.0
* Mobile platform/version under test: iOS 8.4
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/SrinivasanTarget/f724dd986701f029bdf4

@romainlouvet @TikhomirovSergey @imurchie

**Comment by SrinivasanTarget** [comment]
#302

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
Was some exception thrown? 

It is most likely the server-side error.

**Comment by SrinivasanTarget** [comment]
@imurchie Please advice. @TikhomirovSergey Appium logs shows 501. Will post the exact exception ASAP.

**Comment by imurchie** [comment]
The method is not implemented. I've added it to the simulator and added a method to the ios driver. I'm just not sure how to test it because I have no idea when it would be used.

https://github.com/appium/appium-ios-driver/pull/109

**Comment by SrinivasanTarget** [comment]
Its good to have @imurchie , can be utilised when we would like to clear our app cache memory and fresh install after that.

Accept we have resetApp() functionality, just tested and this method didn't reset the application state even after executing resetApp() method.

https://gist.github.com/SrinivasanTarget/73c881423b82045373ec

Will create a new issue if needed.

**Comment by imurchie** [comment]
Yes. Can you create one on the iOS driver repo, with as much detail as possible? And then close this.

**Comment by SrinivasanTarget** [comment]
closing this one
