### ISSUE TITLE
removeApp not implemented

### ISSUE THREAD

**Issue by romainlouvet** [appium/java-client#333]
## Description

When i try to execute command : driver.removeApp("fr.****");
[HTTP] --> POST /wd/hub/session/a939f1f2-742c-4217-b106-0c529966e23c/appium/device/remove_app [MJSONWP] Calling AppiumDriver.removeApp() with args: ["fr.leboncoin.Leboncoin","a939f1f2-742c-4217-b106-0c529966e23c"] [debug] [iOS] Executing iOS command 'removeApp' [HTTP] <-- POST /wd/hub/session/a939f1f2-742c-4217-b106-0c529966e23c/appium/device/remove_app 501 3

org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)

## Environment

Appium version : 1.5.0
Java-client version : 3.4.0

**Comment by SrinivasanTarget** [comment]
Both of us have created an issue.
