### ISSUE TITLE
setNetworkConnection() does not work if > 1 Android device connected

### ISSUE THREAD

**Issue by savishy** [appium/java-client#336]
### Background
I have written a framework that executes Appium TestNG tests in parallel on multiple connected Android devices.
The App under Test has several operations directly related to the current network state. So modifying and monitoring network connection is critical.

### Problem

`driver.setNetworkConnection()` and `driver.getNetworkConnection()` seem to be using the *single-device version of adb command* i.e `adb shell` as opposed to `adb -s device_id shell`.

When I execute this on a *single device*, the command fails with the error:

```
   [testng] org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (Original error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\vish\adt-bundle\sdk\platform-tools\adb.exe shell "settings get global airplane_mode_on""
   [testng] error: more than one device/emulator

```

## Environment

* Java Client 3.3.0
* Appium version 1.4.13.1
* Windows 7
* Node 0.12.7
* Android 5.1, MotoE and Android 5.0, Micromax A107.
* Both real devices.

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

	//assumes driver is initialized and 2 devices connected.
	//to switch to 3G. 
	NetworkConnectionSetting n = new NetworkConnectionSetting(false, false, true;
	driver.setNetworkConnection(n);

## Exception stacktraces

https://gist.github.com/savishy/524ad08dfa423c9e0497

## Link to Appium logs

https://gist.github.com/savishy/4faa2bf0b8c671d2f8cd

**Comment by imurchie** [comment]
Can you try this with Appium 1.5? The logic for interacting with `adb` has changed quite a bit.

**Comment by TikhomirovSergey** [comment]
@savishy
Do you face this issue using the node server 1.5.0?

If you are still seing it then please reopen this issue and add more detailed code sample.
