### ISSUE TITLE
Receiving Connection Refused when attempting instantiate the selenium webdriver 

### ISSUE THREAD

**Issue by nuggit32** [appium/java-client#338]
## Description

I'm receiving org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused running trying start the webdriver to appium.  

Appium appears to be started on 127.0.0.0:4723 but when I call driver = new AndroidDriver<MobileElement>(service.getUrl(), cap) I receive connection refused.

## Environment

* java client build version or git revision if you use some shapshot: 3.4.0
* Appium server version or git revision you is use some shapshot: 1.5.0
* Desktop OS/version used to run Appium if necessary:  OSX El Capitan 10.11.3
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v5.5.0
* Mobile platform/version under test: API 21
* Real device or emulator/simulator: Real Device Samsung S6

## Details

I'm not sure what I'm missing that is causing the connection refused.  
This works fine on Appium 1.4.16 and Java 3.4.0,  but I use appium.js to start appium and call driver as follows:
driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/nuggit32/c99d56cc3f6fc55f1982

## Ecxeption stacktraces

Appium Debug Log
https://gist.github.com/nuggit32/f66ad15818bd16397499

## Link to Appium logs

Appium Debug Log
https://gist.github.com/nuggit32/f66ad15818bd16397499

**Comment by nuggit32** [comment]
I don't think this is a client side issue now.  I started appium from the command line and the server starts.    I'm not seeing the server start on the port when programmatically running.  I will continue to investigate.

**Comment by nuggit32** [comment]
Appears the problem is that if I supply the argument .withIPAddress("127.0.0.1") to the server side it does not start up the server.  I sniffed out the address and ports with lsof -n -i4TCP:4723 | grep LISTEN and do not see it, thus I would get a connection refused.  No idea why that would not work.

When I don't supply it, I can see a port up and listening.

node      5474 herbertscruggs   11u  IPv4 0x9e218116b3598ffb      0t0  TCP *:4723 (LISTEN)

But I still get a connection refused.

org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:4723 [/0.0.0.0] failed: Connection refused

**Comment by TikhomirovSergey** [comment]
@nuggit32 
Im trying to reproduce the problem...

**Comment by TikhomirovSergey** [comment]
@nuggit32 
Does it work then you use emulator instead of the device?

**Comment by nuggit32** [comment]
I had a coding error in my finally statement that was shutting down my service :(

**Comment by TikhomirovSergey** [comment]
@nuggit32 
Ok. Be careful.

**Comment by DanBilzerian** [comment]
Facing the same. Can u pls help me out its urgent

This is the code i am using to start appium server
public class AppiumServer {

    /**
     * @param args the command line arguments
     * @throws InterruptedException 
     */
    public void startAppiumServer() {
        /**
         * Starting the Appium server assuming that Appium file are located in
         * the following directory: "C:/Appium". Change the next three variables
         * to match your Appium binary location and server configurations.
         */
        String AppiumNodeFilePath = "C:/Program Files (x86)/Appium/node.exe";
        String AppiumJavaScriptServerFile = "C:/Program Files (x86)/Appium/node_modules/appium/bin/Appium.js";
        String AppiumServerConfigurations = "--port 4723 --platform-name Android "
        + "--platform-version 22 --automation-name Appium --log-no-color";
        executeCommand("\"" + AppiumNodeFilePath + "\" \"" + AppiumJavaScriptServerFile + "\" " + AppiumServerConfigurations);
        System.out.println("Appium Server started");
    }
    
    public void stopAppiumServer() {
        	
    	String AppiumServerPortNumber = "4723";
    	executeCommand("cmd /c echo off & FOR /F \"usebackq tokens=5\" %a in" 
    	+ " (`netstat -nao ^| findstr /R /C:\"" + AppiumServerPortNumber + "\"`) do (FOR /F \"usebackq\" %b in" 
    	+ " (`TASKLIST /FI \"PID eq %a\" ^| findstr /I node.exe`) do taskkill /F /PID %a)");
    	System.out.println("Appium Server stopped");
    }

    /**
     * Executes a command line command using Java's Process class.
     *
     * @param command A String representation of the command line to execute.
     * @throws InterruptedException 
     */
    private static void executeCommand(String command) {
        //String s = null;

        try {
            Process p = Runtime.getRuntime().exec(command);
            /*BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
            BufferedReader stdError = new BufferedReader(new InputStreamReader(p.getErrorStream()));

            // read the output from the command
            System.out.println("Standard output of the command:\n");
            while ((s = stdInput.readLine()) != null) {
                System.out.println(s);
            }

            // read any errors from the attempted command
            System.out.println("Standard error of the command (if any):\n");
            while ((s = stdError.readLine()) != null) {
                System.out.println(s);
            }*/
        } catch (IOException e) {
            System.out.println("exception happened: ");
            e.printStackTrace();
        }
    }
}
