### ISSUE TITLE
IOSDriver cannot be created from AppiumDriverLocalService, because of Problem getting session data for driver type IosDriver

### ISSUE THREAD

**Issue by truebit** [appium/java-client#339]
## Description
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Problem getting session data for driver type IosDriver; does it implement 'get driverData'? (WARNING: The server did not provide any stacktrace information)

## Environment

* java client build version or git revision if you use some shapshot: 3.4.0
* Appium server version or git revision you is use some shapshot:1.5.0
* Desktop OS/version used to run Appium if necessary:Mac OS X 10.11
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 5.6.0
* Mobile platform/version under test: 8.1.1
* Real device or emulator/simulator: iphone 5s 

## Details
I run my test in testng
I created AppiumDriverLocalService and `started()` it in `@BeforeSuite`
then in `@BeforeTest` I created IOSDriver as follow:
```java
IOSDriver<MobileElement> iosDriver = new IOSDriver<>(getLocalService().getUrl(), desiredCapabilities);
```
But this statement got stacks
```
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Problem getting session data for driver type IosDriver; does it implement 'get driverData'? (WARNING: The server did not provide any stacktrace information)
```
detailed full logs, please see https://gist.github.com/truebit/f017d57fc887ec0e3be6
## Code To Reproduce Issue [ Good To Have ]
None

## Ecxeption stacktraces
https://gist.github.com/truebit/f017d57fc887ec0e3be6

## Link to Appium logs

https://gist.github.com/truebit/f017d57fc887ec0e3be6

**Comment by TikhomirovSergey** [comment]
It seems that something is wrong on the server side. This exception was thrown here: https://github.com/appium/appium/blob/5d324178c8246c0122f5dbc6302fcf24c0322d6a/lib/appium.js#L137

I have no device ti reproduce this problem. @imurchie Any idea?

**Comment by TikhomirovSergey** [comment]
@truebit 
Which capabilities have been provided here (I need Java code)?

```java
IOSDriver<MobileElement> iosDriver = new IOSDriver<>(getLocalService().getUrl(), desiredCapabilities);
```

**Comment by imurchie** [comment]
This looks like two sessions happening at once? There is a second session starting here: https://gist.github.com/truebit/f017d57fc887ec0e3be6#file-gistfile1-txt-L139

The error is... odd.

**Comment by truebit** [comment]
@imurchie yes, It seems that the AppiumDriverLocalService have already created an session. and then IOSDriver tried to create another and failed.

@TikhomirovSergey I wrote a class to read desiredCapabilities from a properties file. The desiredCapabilities could be seen in the log gist actually.

**Comment by TikhomirovSergey** [comment]
@truebit @imurchie 
As I know appium doesn't support the multisession mode, am I right?

@truebit 
Do these sessions use the same port?

**Comment by imurchie** [comment]
The infrastructure is there for multisession mode, but it hasn't been ironed out. Also, for iOS it is unlikely to happen until we support something other than Instruments.

**Comment by TikhomirovSergey** [comment]
@truebit I think the it could work out your problem:

it is possible to create two instance of AppiumDriverLocalServices which can use same binaries and work on different ports. 

```java
 new AppiumServiceBuilder().
                    usingAnyFreePort().build().start();
```

@imurchie @truebit What do you think about this?

**Comment by truebit** [comment]
@TikhomirovSergey I have tried to use `usingAnyFreePort`. Now it would init port other than 4723, but still the same error.

So is it normal that IOSDriver would create new session after AppiumDriverLocalService already started?
Why two session? I did not intent to create two sessions

**Comment by truebit** [comment]
Sorry, I have found the root cause. 
The server was only launched once, but I created IOSDriver twice. It failed when trying to create another IOSDriver instance

**Comment by among29** [comment]
appium 1.5.2 

使用  appium --session-override 启动。

第一个session启动正常，在第二个session请求后，并没有覆盖第一个session，直接报错了。
错误信息：
{
	"status": 33,
	"value": {
		"message": "A new session could not be created. Details: Problem getting session data for driver type IosDriver; does it implement 'get driverData'?"
	},
	"sessionId": null
}

**Comment by juhlila** [comment]
I just restarted appium and it worked for me

**Comment by babusurendra** [comment]
hi @imurchie , could you help me how to update Automaion name from "UIAutomation" to "XCUITest" ?

bellow are the appium logs 

![image](https://cloud.githubusercontent.com/assets/8430311/20713592/e212f58a-b66e-11e6-989b-f76079ce6792.png)

**Comment by ochubey** [comment]
have you tried to define it in Capabilities 
for Java client it's something like `capabilities.setCapability("automationName", "XCUITest");`

**Comment by babusurendra** [comment]
Hi @ochubey , I have scripts in ruby and tried the same :automationName => config['XCUITest']  still i am seeing the same

**Comment by babusurendra** [comment]
can any one help me on this?

**Comment by babusurendra** [comment]
I have updated the script as :automationName => 'XCUITest' , since dont have the value in config file and now it is working fine
thanks @ochubey  !

**Comment by ochubey** [comment]
@babusurendra U welcome ;)

**Comment by babusurendra** [comment]
Hi @ochubey , i have xpath like //UIAApplication[1]/UIAWindow/UIAAlert[contains(@label,'Notifications')] but this is not working in 1.6 appium when i use //*[contains(@label,'Notifications')] it is working fine do we have any solution for this?

**Comment by babusurendra** [comment]
also working with  "//XCUIElementTypeApplication[1]/XCUIElementTypeWindow/XCUIElementTypeAlert[contains(@label,'Notifications')]

**Comment by shahulprofile** [comment]
Run Appium. 
It will create new session, Find the port number. (always it will be like - address "127.0.0.1" --robot-
 port 4)
Port number should match with the capability.

Example: If my port number is 4, then 

		AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4/wd/hub"),cap);
Thanks,
Shameed.
