### ISSUE TITLE
ScrollToExact inconsistent in it's behavior

### ISSUE THREAD

**Issue by nuggit32** [appium/java-client#341]
## Description

I'm not sure this is the expected behavior of ScrollToExact, but I would expect it to stop at the text once it is present on the screen.

I've seen ScrollToExact work correctly sometimes and incorrectly sometimes.

Incorrectly:
1. Scrolls the whole page to the bottom (passes by the text)
2. Then all the way back to the top (passes by the text)
3. Then back to the middle where it needed to stop. (now it stop on the text)

## Environment

* java client build version or git revision if you use some shapshot: 3.4.0
* Appium server version or git revision you is use some shapshot: 1.4.16 and Source 1.5
* Desktop OS/version used to run Appium if necessary:  MAC OSX El Capitan 10.11.3
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 5.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: API 21 Android 5.1.1

## Details

I would expect the scrolling to stop mid way down where the text is present, but I see it scan the whole page, then back to the top then back down to the text field. It passes by the text field 2 times.

## Code To Reproduce Issue [ Good To Have ]

   ((AndroidDriver<?>) driver).scrollToExact("7-31 Day CD");

## Exception stacktraces

There is no stacktrace to provide as eventually it finds the text.

## Link to Appium logs

https://gist.github.com/nuggit32/b959e7dd241ae3546614

**Comment by TikhomirovSergey** [comment]
I'm closing it according to #385
