### ISSUE TITLE
Execution is taking forever once context switched from native to web view to perform any web event.

### ISSUE THREAD

**Issue by VinitSandesara** [appium/java-client#347]
Hi @TikhomirovSergey, This is regarding the solution you have provided in closed issue "https://github.com/appium/java-client/issues/343" , assigning any port with iOS webkit proxy server using the solution you have provided in given above closed issue doesn't work at all, after switching context from native to webview, next line of web doesn't perform any web event (If it is click, it doesn't click on web element). Execution takes forever until it manually killed. 

![screen shot 2016-03-27 at 7 46 43 pm](https://cloud.githubusercontent.com/assets/12589206/14069135/5d86ccd6-f45b-11e5-852e-8e058da3457a.png)

Thanks
Vinit

**Comment by TikhomirovSergey** [comment]
@VinitSandesara 
Hi
This issue can't be fixed on the client side. 

The switching to the WEB_VIEW works well without ios-webkit-proxy.
So I have two ideas:

- there is the problem on the side of Appium server. You have reported the issue https://github.com/appium/appium/issues/6334

- the problem of the proxy server.

**Comment by VinitSandesara** [comment]
Hi @TikhomirovSergey , The thing is that if i manually start webkit proxy server using command on terminal like this "ios_webkit_debug_proxy -c 1fb95ac900359617add8ffbb41dfdba33668e2a9:56215" i am able to switch the context from native to webview and able to perform all web actions after that (click, sendKeys etc). 

Thanks
Vinit

**Comment by SrinivasanTarget** [comment]
Seems you have got the solution.will close this.

**Comment by SrinivasanTarget** [comment]
@triager please close
