### ISSUE TITLE
Should BootStrap Server flag be moved to GeneralServerFlag ?

### ISSUE THREAD

**Issue by saikrishna321** [appium/java-client#348]
@TikhomirovSergey 

To iOS test in parallel, we need to specific bootstrap port else it fails to run parallely. From the below code u can see i have called BOOTSTRAP PORT from AndroidServerFlag 

Can we have this moved at the java_client end or should this take place first at the server side ?

Thoughts ??

```
AppiumServiceBuilder builder = new AppiumServiceBuilder()
                .withAppiumJS(new File(prop.getProperty("APPIUM_JS_PATH")))
                .withArgument(GeneralServerFlag.LOG_LEVEL, "info")
                .withLogFile(new File(
                        System.getProperty("user.dir") + "/target/appiumlogs/" + deviceID.replaceAll("\\W", "_") + "__" + methodName + ".txt"))
                .withArgument(GeneralServerFlag.UIID, deviceID).withArgument(IOSServerFlag.USE_NATIVE_INSTRUMENTS)
                .withArgument(webKitProxy,webKitPort)
                .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, Integer.toString(bootstrapPort))
                .withArgument(GeneralServerFlag.TEMP_DIRECTORY,
                        new File(String.valueOf(classPathRoot)).getAbsolutePath() + "/target/" + "tmp_" + port)
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE).usingPort(port);
		/* and so on */
        ;
        appiumDriverLocalService = builder.build();
        appiumDriverLocalService.start();
        System.out.println(appiumDriverLocalService.isRunning());
        System.out.println(builder);
```

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
There is the document: 
http://appium.io/slate/en/master/?ruby#appium-server-arguments
And _--bootstrap-port_ is _Android-only_ here. 

What if several instances of _AppiumDriverLocalService _ would be created?

**Comment by saikrishna321** [comment]
@TikhomirovSergey nothing goes wrong when creating multiple _AppiumDriverLocalService_ on different ports, it's just to run test in parallel for sure the bootstrap is must for iOS and right now i see BootStrap in android server flag as you pointed out.... 

Was thinking if we could have it moved to GeneralFlag as we are using it for both android and iOS server session for parallel run 

Thoughts ??

**Comment by TikhomirovSergey** [comment]
Ok. 
Is it possible to start an IOSDriver instance the way below

```
AppiumServiceBuilder builder = new AppiumServiceBuilder()
...
                .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, Integer.toString(bootstrapPort))
..
        ;
        appiumDriverLocalService = builder.build();
        appiumDriverLocalService.start();
       ....
       new IOSDriver(service.getUrl(), capabilities)
```
?

What does servel log show? If this starting is ok is bootstrap port number ignored?

If everything is ok then there are questions why is it documented as Android-only

**Comment by saikrishna321** [comment]
@TikhomirovSergey 

Yes, i can start the IOSDriver the way specified .

It starts IOSDriver when bootstrap is ignored, but definitely fails when running parallely tests on IOS. 

When giving BOOTSTRAP port in IOS parallel run tests execute on multiple devices without any issue.

**Comment by TikhomirovSergey** [comment]
Ok. I will ask the question to server developer team.

**Comment by imurchie** [comment]
Can you provide the server logs for this, @saikrishna321 ? I can't find any way that it would do anything in iOS, but something weird might have happened.

**Comment by saikrishna321** [comment]
@imurchie when i tried to execute on 1.5.0 and 1.5.1 without giving boot strap port it works fine for IOS parallel, in the previous version it was not stable(1.4.16) without bot strap and was very stable with bot strap. 

It would be really helpful, if you could give us some info on how boot strap port helps running tests in parallel ?

Refer old thread : https://github.com/appium/appium/issues/273 where everyone has always given -bp for running in parallel

**Comment by imurchie** [comment]
I don't see everyone always using `-bp` in the thread mentioned. As far as I can see in the 1.5 codebase there is no way that the bootstrap port could have any effect on iOS tests.

This is why I wanted to see the logs, to see if it is getting in there somehow.

**Comment by saikrishna321** [comment]
Not able to reproduce with lates v 1.5.1.Closing the ticket

**Comment by Raj1071** [comment]
is it necessary to define AndroidDriver class and URL value as http://127.0.0.1:port/wd/hub if we define AppiumDriverLocalService class and provide IP address and Port also
