### ISSUE TITLE
Exception throws for Gesture on Android with release operation

### ISSUE THREAD

**Issue by TurlyYang** [appium/java-client#358]
## Description
Running the following code exception throws, which means when doing gesture from bottom to top or from right to left, exception would throw on release action, please help to resolve it, thanks

Here is the code:
TouchAction gesture1 = new TouchAction(baseDriver.getAppiumDriver()).press(849, 748)
.moveTo(-309,311)
.moveTo(-314,311)
.moveTo(314,0)
.moveTo(314,0)
.moveTo(0,-311)
.moveTo(-309,-311)
.moveTo(-314,0)
.moveTo(0,311).release();
gesture1.perform();

Here is appium server debug info:
{"x":849,"y":748}},
{"action":"moveTo","options":{"x":-309,"y":311}},
{"action":"moveTo","options":{"x":-314,"y":311}},
{"action":"moveTo","options":{"x":314,"y":0}},
{"action":"moveTo","options":{"x":309,"y":-311}},
{"action":"moveTo","options":{"x":-309,"y":-311}},
{"action":"moveTo","options":{"x":-314,"y":0}},
{"action":"moveTo","options":{"x":0,"y":311}},
{"action":"release","options":{}}]}

> info: [debug] Pushing command to appium work queue: ["element:touchDown",{"x":849,"y":748}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":849,"y":748}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? false x: 849, y: 748
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":540,"y":1059}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":540,"y":1059}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 540, y: 1059
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":226,"y":1370}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":226,"y":1370}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 226, y: 1370
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":540,"y":1370}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":540,"y":1370}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 540, y: 1370
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":849,"y":1059}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":849,"y":1059}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 849, y: 1059
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":540,"y":748}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":540,"y":748}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 540, y: 748
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":226,"y":748}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":226,"y":748}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 226, y: 748
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":226,"y":1059}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":226,"y":1059}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 226, y: 1059
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":-309,"y":-311}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":-309,"y":-311}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Coordinate [x=-309.0, y=-311.0] is outside of element rect: [0,0][1080,1920]","status":29}
> info: [debug] Responding to client with error: {"status":29,"value":{"message":"The coordinates provided to an interactions operation are invalid."...

## Environment

* Appium java_client 3.3, Appium server 1.4.13 for windows ,  android device

**Comment by TikhomirovSergey** [comment]
@TurlyYang 
Sorry for the late responce. I was too busy.
It is not the problem of the _release_ operation. It is the problem of the _moveTo_. Given coorditanes are invalid. They should be positive and absolute for Android.

**Comment by TikhomirovSergey** [comment]
@TurlyYang Please reopen if you'll find some new details.
