### ISSUE TITLE
iOS Native apps, appium version v1.5.1, Element doesn’t click once scroll performed on an element.

### ISSUE THREAD

**Issue by VinitSandesara** [appium/java-client#360]
Hi, We have 15 items listed on search result page and we want to click on 3rd item listed on page for which we use scroll to the 3rd element before clicking on it where scroll is happening but it doesn't click on 3rd element once scroll performed. PFB gist log

Note : Here we want 3rd element to be click on it, not that but all items after 1st 2 items it doesn't click on any element (3,4,5,6,7 etc).

https://gist.github.com/VinitSandesara/1f852265e1e7aa2cc2b105e7d67b88c3

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Any update on this ?

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Can someone please help on this issue, we have many elements on page to perform action on we first need to scroll before performing an action on it but due to an issue we are blocked and can't move further, if anyone out there who has solution please help.

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi @TikhomirovSergey , Can you please give your thought on this ? it's been 9 days i am waiting for the solution. As i have mentioned above in my comment we have many pages to perform an action on an element we have to scroll on page.

Thanks
Vinit

**Comment by TikhomirovSergey** [comment]
No idea. It seems that somethong is on the server side
https://github.com/appium/appium/search?o=desc&q=+elementId+2+could+not+be+tapped&s=created&type=Issues&utf8=%E2%9C%93

Sorry.
