### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V 	at io.appium.java_client.AppiumDriver.

### ISSUE THREAD

**Issue by michellell** [appium/java-client#363]
i am getting following error: Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V
	at io.appium.java_client.AppiumDriver.

I checked all the jar file version and i don't see any problem.  here is screenshot of the jar files and versions.  Can someone help if there is conflict on this, if yes, what versions do i need?

![config](https://cloud.githubusercontent.com/assets/18407538/14692665/95d7e3b2-070d-11e6-9dbc-81a05f5446bb.png)

**Comment by TikhomirovSergey** [comment]
@michellell 
It is not the problem of the Appium Java client. It is the dependency conflict.

Which java_client versions have you used?
Take a look at this page
http://mvnrepository.com/artifact/io.appium/java-client/3.4.1 the section **Compile Dependencies**. 
And then take a look at http://mvnrepository.com/artifact/org.uiautomation/ios-server/0.6.5. It seems it is the root cause of dependency conflicts.

**Comment by michellell** [comment]
i've updated jar files that appear to be in conflict and still getting the same error.  could it be within the code that's causing the problem?

**Comment by TikhomirovSergey** [comment]
@michellell 
No. I've searched and found this commit 
https://github.com/SeleniumHQ/selenium/commit/1208bbcfe2804336994036f8702f7cedb244ff5e

It seems it is much newer than Selenium 2.35.

I don't know what does the ios-server artefact do in your project, but I'm seeing two solutions:

- to remove it from your dependencies.

- to add some exclusions
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html
So you have to exclude Selenium 2.35. http://mvnrepository.com/artifact/org.uiautomation/ios-server/0.6.5. This thing depends on it.

**Comment by TikhomirovSergey** [comment]
@michellell 
Please reopen if you'll find something new about this issue

**Comment by michellell** [comment]
why do i need to add exclusions? i am not using maven.

**Comment by moshosseini** [comment]
this problem is related to Appium java client. I had this problem with 6.1.0 version. I have this problem with 6.0.0 too but it solved by using 5.0.4.
I am using:
selenium 3.14v
Appium java client 5.0.4
