### ISSUE TITLE
 List<MyWidget>  all items initialise by first page element

### ISSUE THREAD

**Issue by IZaiarnyi** [appium/java-client#364]
## Description
Wrong data comes to widget that contains another widget during  initialising.
This issue is reproduced only for tablet Android emulators.

I have such elements 
http://screencast.com/t/gWjsyUTp3

 Code for covering this widget
```java
@AndroidFindBy(xpath = "//*[contains(@resource-id,'lv_users')]/android.widget.LinearLayout")
public class DroidInviteShareContact2 extends Widget {
    protected DroidInviteShareContact2(WebElement element) {  super(element); }

    @AndroidFindBy(id = "cb_checked")
    private MobileElement checkbox;
    @AndroidFindBy(id = "tv_name")
    private MobileElement name;
    @AndroidFindBy(id = "tv_subtitle")
    private MobileElement email;

    public Contact getContact(){
        return new Contact(
                name.getText(),
                email.getText(),
                checkbox.getAttribute("checked").equals("true"));
    }
}
```
```java
@AndroidFindBy(xpath = "//*[contains(@resource-id,'lv_users')]")
public class DroidInviteShareContacts2 extends Widget {
    @WithTimeout(time = 5, unit = SECONDS)
    private List<DroidInviteShareContact2> contacts;

    protected DroidInviteShareContacts2(WebElement element) { super(element); }
    public int getContactsCount(){
        return  contacts.size();
    }
    public Contact getContact(int index){
        return  contacts.get(index).getContact();
    }
}
```
```java
public class InviteShare{
    private AndroidDriver<MobileElement> driver;
    private DroidInviteShareContacts2 contacts2;
    private List<DroidInviteShareContact2> listContacts;

   public InviteShare(AndroidDriver<MobileElement> driver) {
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver, 0, TimeUnit.SECONDS), this);
    }
  public DroidInviteShareContacts2 getContacts() {
        return contacts2;
    }
  public List<DroidInviteShareContact2> getListContacts() {
        return listContacts;
    }
}
```
```java
   new InviteShare(driver).getContacts().getContact(4).name; 
   //Inviteshare Test0
   // Wrong Behaviour because all items was initialised by first page element 
   new InviteShare(driver).getContacts().getContactsCount();
   // 6
   new InviteShare(driver).getListContacts().get(4).getContact().name
   // Inviteshare Test4
   // Correct behaviour all items was initialised by corresponding elements 
   new InviteShare(driver).getListContacts().size();
   // 6 
```
**Expected result: listContacts and contacts2 have the same data.**
**What is cause such behaviour or maybe I do something wrong?**
## Environment

* java-client 3.4.1
* Appium v1.5.1
* Mac OS X 10.10.5
* Node.js v5.1.0
* Mobile platform Android 5.1.0 
* emulator Nexus9

**Comment by TikhomirovSergey** [comment]
@IZaiarnyi 
Good report. Thank. The searching for root cause has been started :)

**Comment by TikhomirovSergey** [comment]
@IZaiarnyi 
I have got some questions

Why do you instantiate the _DroidInviteShareContact2_ twice?

Here:
```java
@AndroidFindBy(xpath = "//*[contains(@resource-id,'lv_users')]")
public class DroidInviteShareContacts2 extends Widget {
    @WithTimeout(time = 5, unit = SECONDS)
    private List<DroidInviteShareContact2> contacts; ///<====!!!

    protected DroidInviteShareContacts2(WebElement element) { super(element); }
    public int getContactsCount(){
        return  contacts.size();
    }
    public Contact getContact(int index){
        return  contacts.get(index).getContact();
    }
}
```

and here

```java
public class InviteShare{
    private AndroidDriver<MobileElement> driver;
    private DroidInviteShareContacts2 contacts2;
    private List<DroidInviteShareContact2> listContacts; ///<====!!!!

   public InviteShare(AndroidDriver<MobileElement> driver) {
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver, 0, TimeUnit.SECONDS), this);
    }
  public DroidInviteShareContacts2 getContacts() {
        return contacts2;
    }
  public List<DroidInviteShareContact2> getListContacts() {
        return listContacts;
    }
}
```

???

Should the _DroidInviteShareContact2_ be used as a sub-widget of _DroidInviteShareContacts2_?
Why do you do it?

**Comment by IZaiarnyi** [comment]
> Should the DroidInviteShareContact2 be used as a sub-widget of DroidInviteShareContacts2?

Yes, I do this in such way because I want to have abstract class that would have common methods for `List<InviteShareContact2>` for Android, IOS, HTML base pages.
Like we have in appium samples 
[github example](https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/widgets/RottenTomatoes.java)
```java 
    @OverrideWidget(html = HTMLInviteShareContacts2.class, selendroid = SelendroidInviteShareContacts2.class.class,
            androidUIAutomator = DroidInviteShareContacts2.class, iOSUIAutomation = IOSInviteShareContacts2.class)
   private InviteShareContacts2 contacts2;
```

> Why do you instantiate the DroidInviteShareContact2 twice?

I did this for showing the difference.
`List<DroidInviteShareContact2>` works as expected and `DroidInviteShareContacts2 contacts2` have unexpected behaviour.
In my code I use only  `DroidInviteShareContacts2 contacts2` that works unexpectedly.

**Comment by TikhomirovSergey** [comment]
@IZaiarnyi 
Sorry for the late responce 

Can you show me _uiautomatorviewer_? 
>This issue is reproduced only for tablet Android emulators.
Please take it from tablet emulator.

How to do it:
1. Open a tablet emulator and install the target app there. Please launch it.

2. Go to _{$AndroidSDKfolder}/tools/uiautomatorviewer.bat_ (or _uiautomatorviewer_, it depends on OS).

3.  Click _Device Screenshot._

4. ![](https://cloud.githubusercontent.com/assets/4927589/14811167/73c6bd20-0b9f-11e6-979a-d101ef382bed.png)

**Comment by TikhomirovSergey** [comment]
@IZaiarnyi 
Also please make focus on target elements. You can post a few screenshots. 

PS: Can you send me an email message with the app build in attaches If it is possible?

**Comment by sergeyzenchenko** [comment]
hey @TikhomirovSergey we can create a slack chat for this discussion to share all required details in it.

**Comment by IZaiarnyi** [comment]
@TikhomirovSergey all requested information was sent to your email tichomirovsergey@gmail.com

**Comment by TikhomirovSergey** [comment]
It is most likely something is going wrong on the server side. Please reopen if you'll find something else related to this issie and there will be some concerns about client consistency.
