### ISSUE TITLE
[question] Do we need to have Dependency Check

### ISSUE THREAD

**Issue by saikrishna321** [appium/java-client#367]
@TikhomirovSergey @SrinivasanTarget 

Do you think we need to have dependency check within the java_client library?

![screen shot 2016-04-25 at 11 16 08 am](https://cloud.githubusercontent.com/assets/4045041/14774785/6665a3bc-0ad7-11e6-8d51-6aa46a620d08.png)

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey @saikrishna321 I have similar stuff implemented on server side. Server team are running npm-check before publishing on npm registry. We can have this on client side.

**Comment by TikhomirovSergey** [comment]
I think it is good idea.

**Comment by saikrishna321** [comment]
@TikhomirovSergey @SrinivasanTarget 
will send a PR soon...

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/pull/369

**Comment by TikhomirovSergey** [comment]
Merged
