### ISSUE TITLE
Child `Widget` extends another non-abstract parent `Widget` would throw NoSuchMethodException if child using parent method

### ISSUE THREAD

**Issue by truebit** [appium/java-client#395]
## Description

Child `Widget` extends another non-abstract parent `Widget` would throw NoSuchMethodException if child using parent method

## Details
For example:
I only tried in `OverrideWidget` scenario. Below example could reproduce the issue:

There is an abstract Widget named `AbstractWidget`, I implemented two widgets `AndroidParentWidget` and `IOSParentWidget` to extends `AbstractWidget`.

Then I implemented another widget named `AndroidChildWidget` extends `AndroidParentWidget`. in `AndroidChildWidget`, I only added one more method. Other existing methods such like `parentMethod()` in `AndroidChildWidget`  just being extended directly without override.

When invoking `AndroidChildWidget.parentMethod()` in test code, it would throw `NoSuchMethodException`.

I found a workaround: override `parentMethod` in `AndroidChildWidget` explicitly with `super.parentMethod()`. it would work

**Comment by truebit** [comment]
Sometimes I would got NoSuchMethodException in `OverrideWidget` with plain standard usage.
After applying https://github.com/appium/java-client/issues/418#issuecomment-226715514,
the exception chagned to `java.lang.IllegalArgumentException: Constructor not found`:

> 	at com.changba.mobile.uitest.widgets.HottestPageTopListCell$$EnhancerByCGLIB$$33a838b0.newInstance(<generated>)
> 	at net.sf.cglib.proxy.Enhancer.createUsingFactory(Enhancer.java:777)
> 	at net.sf.cglib.proxy.Enhancer.nextInstance(Enhancer.java:650)
> 	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:282)
> 	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:433)
> 	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:324)
> 	at io.appium.java_client.pagefactory.utils.ProxyFactory.getEnhancedProxy(ProxyFactory.java:56)
> 	at io.appium.java_client.pagefactory.WidgetListInterceptor.getObject(WidgetListInterceptor.java:66)
> 	at io.appium.java_client.pagefactory.interceptors.InterceptorOfAListOfElements.intercept(InterceptorOfAListOfElements.java:51)
> 	at $java.util.ArrayList$$EnhancerByCGLIB$$c0a2d785.get(<generated>)

**Comment by TikhomirovSergey** [comment]
@truebit 
If there had been any problem then it seems it was fixed there #392. I can't find a way to reproduce it. Please provide the code sample as a gist and reapen this one.
