### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by Manmit83** [appium/java-client#396]
## Description

Getting No Such Method Error 

## Environment

* java Client = java-client-3.4.1.jar
* Appium Version = 1.5.2 (Ara)
* OS = Mac OSX El Captian (v 10.11)
* Node Version = v4.4.5
* Mobile platform/version = iOS 8.1, iPhone5
* Real device or emulator/simulator: Xcode 7.3.1, Command_Line_Tools_OS_X_10.11_for_Xcode_7.3.1.dmg

## Details

Other Lib
* Selenium 2.53
* Junit 4.12
* ios-server-0.6.5-jar-with-dependencies.jar

## Code To Reproduce Issue [ Good To Have ]

import java.net.URL;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.ios.IOSDriver;

public class AppiumiOSDemo {
	
	WebDriver driver;
	
	@Before
	public void setCapabilites() throws Exception {
		DesiredCapabilities capablilites = new DesiredCapabilities();
		capablilites.setCapability("deviceName", "iPhone 5");
		capablilites.setCapability("platformName", "iOS");
		capablilites.setCapability("platformVersion", "8.1");
		capablilites.setCapability(CapabilityType.BROWSER_NAME,"Safari");
		
		driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capablilites);
	}
	
	@Test
	public void testgoogleSearch() {
		
		driver.get("http://www.google.co.in");
		
	}

}

## Ecxeption stacktraces

java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V
	at io.appium.java_client.AppiumDriver.<clinit>(AppiumDriver.java:57)
	at AppiumiOSDemo.setCapabilites(AppiumiOSDemo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by TikhomirovSergey** [comment]
@Manmit83 
This is the same as 
https://github.com/appium/java-client/issues/363

This is not the issue of java_client.
