### ISSUE TITLE
The splitting of AndroidDriver and IOSDriver

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#398]
## Description

_AndroidDriver_ should be separated into _AndroidUIAutomatorDriver_ and _SelendroidDriver_.
IOSDriver should be splitted into IOSAutomationDriver and IOSXCUITDriver.

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/issues/143

**Comment by saikrishna321** [comment]
@TikhomirovSergey should this be still open ?

**Comment by SrinivasanTarget** [comment]
As we deprecated legacy drivers officially at server end, we can close this.
