### ISSUE TITLE
Migrate to Java 8 (9?)

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#399]
## Description

Migrate this project to jdk 8. Maybe to jdk 9 if it would be released.

**Comment by SrinivasanTarget** [comment]
Awesome

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/3279

**Comment by SrinivasanTarget** [comment]
Selenium heading to Java 8: https://github.com/SeleniumHQ/selenium/blob/master/maven/pom.xml#L242

**Comment by SrinivasanTarget** [comment]
Selenium moved to Java 8: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG
