### ISSUE TITLE
Where is the IOSKeyCode class?

### ISSUE THREAD

**Issue by abourdon** [appium/java-client#402]
Hi,

I'm trying to update to the 4.0.0 version and I can see that the IOSKeyCode class is now missing. Is there an other class to use? Or a new way to follow in order to press a key to IOS devices?

Regards,
Aurélien

**Comment by TikhomirovSergey** [comment]
The sending of key event was removed from the IOSDriver long time ago. And IOSKeyCode became useless.

@imurchie @bootstraponline I can't find how does server-side iOS perform the sending of key event. Will it support that action further?

**Comment by abourdon** [comment]
Thanks for you reply. Class is still available in 3.4.1 version and missing in 4.0.0. Let me know if I have to follow a new way to press a key to IOS devices.

Regards

**Comment by SrinivasanTarget** [comment]
@abourdon Interface IOSKeyCode was available on previous versions of java-client code but unfortunately keycodes are not for iOS and so not implemented on both server and client for iOS. 
```
public interface IOSKeyCode {

    int BACKSPACE = 8;
    int ENTER = 13;
    int RETURN = 13;
    int SPACE = 32;

}
```
We had the above code and it doesn't make sense to have this without any support.Hence we removed this from our latest release.

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/4479

**Comment by SrinivasanTarget** [comment]
@abourdon Please refer this: https://github.com/appium/appium/issues/4277 & https://github.com/appium/appium-uiauto/issues/65

**Comment by abourdon** [comment]
Thanks for your reply.

Regards,
Aurélien
