### ISSUE TITLE
symbol not found error for MobileCapabilityType.UNICODE_KEYBOARD and MobileCapabilityType.APP_WAIT_ACTIVITY,

### ISSUE THREAD

**Issue by rompic** [appium/java-client#406]
## Description
using 
- capabilities.setCapability(MobileCapabilityType.UNICODE_KEYBOARD,true); or
- capabilities.setCapability(MobileCapabilityType.APP_WAIT_ACTIVITY, "<ActivityName>")
leads to a symbol not found error when compiling.

using the string equivalents works:
capabilities.setCapability("unicodeKeyboard",true)

## Environment

* java client build version or git revision if you use some shapshot: 4.0
* Appium server version or git revision if you use some shapshot: 1.5.2
* Desktop OS/version used to run Appium if necessary: Mac OSX 10.11.5
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 
* Mobile platform/version under test:
* Real device or emulator/simulator: Emulator

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by saikrishna321** [comment]
@rompic its been moved
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java#L176

https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java#L42

**Comment by rompic** [comment]
thx. IntelliJ doesn't find it but it seems to work.

**Comment by rompic** [comment]
worked after cleaning and restarting.
