### ISSUE TITLE
setlocation on android emulator doesn't work

### ISSUE THREAD

**Issue by rompic** [appium/java-client#407]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.

i cannot get setlocation on the android emulator to work. i.e. location is not used within my app under test

## Environment

* java client build version or git revision if you use some shapshot: 4.0.0
* Appium server version or git revision if you use some shapshot: 1.5.2
* Desktop OS/version used to run Appium if necessary: Mac OSX 10.11.5
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android Nexus_5_API_21_x86
* Real device or emulator/simulator: Emulator

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
driver.setLocation(new Location(lat,long,alt));

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/11db1be9-98b7-4a35-a00d-645865622e78/location {"location":{"altitude":0,"latitude":58.210033,"hCode":565277442,"class":"org.openqa.selenium.html5.Location","longitude":26.363449}}
    [MJSONWP] Calling AppiumDriver.setGeoLocation() with args: [{"altitude":0,"latitude":58.210033,"hCode":565277442,"class":"org.openqa.selenium.html5.Location","longitude":26.363449},"11db1be9-98b7-4a35-a00d-...
    

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by TikhomirovSergey** [comment]
@rompic This issue is already fixed by @SrinivasanTarget. Please wait for a new server release. Also you can get latest Android-specific artefacts and put them to the server location.

**Comment by rompic** [comment]
thanks for the fast response. can you point to the issue / pull request that fixed this or tell me when the next server release can be expected? thx.

**Comment by rompic** [comment]
is this included in https://discuss.appium.io/t/appium-1-5-3-released/10606 ?

**Comment by SrinivasanTarget** [comment]
Hey @rompic Sorry for the confusion. I think @TikhomirovSergey thought this as setNetworkConnection API and told here.GeoLocation is not been fixed in server yet.

@TikhomirovSergey Let me have a look and try my best to fix this on server:)

**Comment by rompic** [comment]
thanks for the update

**Comment by TikhomirovSergey** [comment]
Yes. There was misunderstanding.

**Comment by rompic** [comment]
it works now after uninstalling the appium settings apk / activating allow mock locations in settings. see the referenced issue for more info

**Comment by SrinivasanTarget** [comment]
Thanks for letting us know.Glad it worked for you @rompic :)
