### ISSUE TITLE
What about adding a startIntent() method ?

### ISSUE THREAD

**Issue by Fanch-** [appium/java-client#408]
## Description

What about adding a

>     startIntent(String intentAction,String intentCategory,
>     String intentFlags,String intentOptionalArgs)

method in java-client ?

Because startActivity is fine but it requires appActivity and appPackage, which sometimes are not necessary.

This method could be useful for example to open DeepLink : 

```shell```
adb -s $1 shell "am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d '$url'"
```

From 

```java```
getDriver().startActivity("android", "com.android.internal.app.ResolverActivity", "", "", "android.intent.action.VIEW", "android.intent.category.BROWSABLE", "", "-d + url");
```

To

```java```
getDriver().startIntent("android.intent.action.VIEW", "android.intent.category.BROWSABLE", "", "-d + url");
```

**Comment by saikrishna321** [comment]
@Fanch- this be been in 4.0.0 https://github.com/appium/java-client/pull/381

**Comment by Fanch-** [comment]
@saikrishna321 Without requiring appActivity and appPackage ? I found only the startActivity method.

**Comment by SrinivasanTarget** [comment]
@Fanch- Yes ```appPackage``` and ```appActivity``` are required params for ```start_activity``` API. This need to be adapted on server side.I see you had already raised a related issue on server side. You can probably ask the same here again: https://github.com/appium/appium/issues/5209. I think either deep linking or app indexing should probably be an enhancement on server side.

Closing this.
