### ISSUE TITLE
Swipe - Reduced capabilities on Appium Driver (Java Client)

### ISSUE THREAD

**Issue by Markm21** [appium/java-client#41]
On WebRemoteDriver it is possible to swipe using percentages (values between 0 and 1) and on AppiumDriver it is not.

I'm using different Mobile devices and i cannot use the same coordinates for all of them.
What's my best solution here? 

/**
- Convenience method for swiping across the screen
- @param startx starting x coordinate
- @param starty starting y coordinate
- @param endx ending x coordinate
- @param endy ending y coordinate
- @param duration amount of time in milliseconds for the entire swipe action to take
  */
  public void swipe(int startx, int starty, int endx, int endy, int duration) {
    TouchAction touchAction = new TouchAction(this);
  
    //appium converts press-wait-moveto-release to a swipe action
    touchAction.press(startx, starty).waitAction(duration).moveTo(endx, endy).release();
  
    touchAction.perform();
  }

**Comment by namannigam** [comment]
Any updates on swiping using the element location?

**Comment by TikhomirovSergey** [comment]
I'm closing this issue because defined gesture methods are considered deprecated.
