### ISSUE TITLE
Network Connection for iOS

### ISSUE THREAD

**Issue by email2vimalraj** [appium/java-client#412]
## Description

With the latest release v4.0.0, I see the **NetworkConnectionSetting** had been deprecated which was common for both **Android** and **iOS**. Whereas, now **io.appium.java_client.android.Connection** is implemented only for Android. How do we manipulate the network settings for iOS?

## Environment

* java client build version or git revision if you use some shapshot: v4.0.0
* Appium server version or git revision if you use some shapshot: v1.5.3
* Desktop OS/version used to run Appium if necessary: MacOSX El Captain
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v6.0.0
* Mobile platform/version under test: Android L / iOS 9
* Real device or emulator/simulator: Real Device

**Comment by TikhomirovSergey** [comment]
@email2vimalraj 
Was it possible to change network connection on iOS?

Please show your working code sample.

**Comment by email2vimalraj** [comment]
@TikhomirovSergey : Sorry I don't have any working code. I was assuming the NetworkConnectionSetting worked for iOS too. However, now after my investigation, this won't be possible. Apologise for raising this issue.

BTW, do we have anything on roadmap to support for iOS too.

**Comment by Mikulasi** [comment]
Same issue for Android, there is no implementation for switching wifi on/off besides enum Connection. Are you going to fix this issue?
