### ISSUE TITLE
Could not find adb Please set the ANDROID_HOME environment variable even though it's set properly

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#416]
## Description

1. Appium java client version 4.0.0
2. while running test case checkTheAbilityToStartADriverWithTheDefaultServerAndNotDefaultNode getting error "Could not find adb Please set the ANDROID_HOME environment variable"
3. path.to.custom.node.macos=/usr/local/lib/node_modules/appium/build/lib/main.js set in custom_node_path.properties
   ( Mac OS + Eclipse ) 
4. from command line 

Vikrams-MacBook-Pro:~ vikram-anna$ echo $ANDROID_HOME
/Users/vikram-anna/Library/Android/sdk

## Environment

* java client build version or git revision if you use some shapshot: 1.8.0
* Appium server version or git revision if you use some shapshot: 1.5.0.
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 5.7.0

## Details

NA

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

https://gist.github.com/vikramvi/a761dab97f97374f8941d0166b10766f

## Link to Appium logs

NA

**Comment by saikrishna321** [comment]
@vikramvi if you running your test from eclipse you need to set ANDROID_HOME under run configuration

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/issues/252

**Comment by TikhomirovSergey** [comment]
@vikramvi @saikrishna321 
It is not related to #252. It seems a sever instance was started but the server could not read ANDROID_HOME.

**Comment by TikhomirovSergey** [comment]
It is related to #286. Maybe it makes sense to add ANDROID_HOME to Eclipse environment (#252).

**Comment by vikramvi** [comment]
Closing as this is Eclipse bug and not related to appium java-client. 
Thanks @saikrishna321  and @TikhomirovSergey  for responses.

I've added this in my demo projects fixing branch.

**Comment by toastsgithub** [comment]
I met the same problem, 
I don't know why, I've checked the ANDROID_HOME manually,
and the 'appium-doctor' shows all the test case are passed,
but when I launch my test script with eclipse, the server throw this Error.

and finally this wired problem solved by set the `android sdk path` in `Android Settings --
 Advanced` of Appium

----

OS: MacOS 10.12
Appium: 1.5.3

hope this will help you guys

**Comment by olyv** [comment]
I doubt if this issue is caused by Eclipse, I am having the same problem in Intellij Idea.

**Comment by Pranavindia2007** [comment]
SET ANDROID_HOME variable in your home project if you are running appium from your java code.

o run the tests from eclipse, u need to set the ANDROID_HOME in environment of eclipse. Right Click in Runner.java --> Run Configuration --> Set ANDROID_HOME under environment .
