### ISSUE TITLE
Query:  checkTheAbilityToStartADriverWithTheDefaultServerAndNode TC under DriverServiceSample

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#417]
## Description

1. While running checkTheAbilityToStartADriverWithTheDefaultServerAndNode under https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/driver_service/DriverServiceSample.java

getting error as InvalidServerInstanceException

2. I have set value of 

path.to.custom.node.macos=/usr/local/lib/node_modules/appium/build/lib/main.js

in custom_node_path.properties

Query:

1. Is this bug or I'm doing something wrong here ?

2. What is exact purpose of this TC ? Didn't understand it fully.

## Environment

* java client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

https://gist.github.com/vikramvi/a4245a2c32b1cfdd0cf70cf1224f3598

## Link to Appium logs

NA

**Comment by TikhomirovSergey** [comment]
@vikramvi 
It is not the bug. It is hardcoded value. It is most likely the path to the instantalled Appium App. I was usng Appium 1.4.x at that time.

**Comment by TikhomirovSergey** [comment]
This is not related to java clint. But I agrre that samples are not in actual state and it should be improved.
