### ISSUE TITLE
scrollTo and scrollToExact - their replacement

### ISSUE THREAD

**Issue by igalep** [appium/java-client#421]
in java client 4.0 , these two are marked as deprecated , I was wondering if there is going to be a replacement for them ?

**Comment by TikhomirovSergey** [comment]
@igalep 
Hi!
You can use methods that perform the searching

Android:
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidSearchingTest.java#L58
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidElementTest.java#L68

iOS:. https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSScrollingSearchingTest.java

Deprecated methods were using the same approach. But locators were hardcoded and a lot of users had having problems. We could not find the generic solution.

**Comment by smaspe** [comment]
@TikhomirovSergey The second method presented for android seems weird: the `UiSelector` passed to the `UiScrollable` has no selection element, and I don't see how the context of the webelement on which the `find` is called could help. (Also I did some tests with the python client and could not get that kind of selector to work.)

I could really use having the possibility to find the list view using something that is not a `UiSelector`, so if you have any clue?

**Comment by alexilyenko** [comment]
@TikhomirovSergey Sergey, are there any updates on scrollTo methods for XCUIT elements?
