### ISSUE TITLE
Appium driver returns portrait orientation for tablets which have default orientation landscape.

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/java-client#422]
## Description

I use Samsung Galaxy Note 10.1.
Landscape orientation is default for this device and when I check  driver.getOrientation() it returns Portrait.
## Environment

Java client:  4.0
appium server: 1.5.3
desktop OS/version: Mac OS Capitan
mobile platform/version under test: Android 5.1
real device or emulator/simulator: Samsung Galaxy Note 10.1.
## Link to Appium logs

MJSONWP] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/bf42f231-4e1f-4b78-a5ce-34ae8395be70/element/1/displayed 200 31 ms - 76 
[HTTP] --> GET /wd/hub/session/bf42f231-4e1f-4b78-a5ce-34ae8395be70/orientation {}
[MJSONWP] Calling AppiumDriver.getOrientation() with args: ["bf42f231-4e1f-4b78-a5ce-3...
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"orientation","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"orientation","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: orientation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Current rotation: ROTATION_0
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"PORTRAIT"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getOrientation() result: "PORTRAIT"

**Comment by TikhomirovSergey** [comment]
Hi @shynkevich-alex 
This is not the bug of the java_client,
The root cause: 
https://github.com/appium/appium/issues/6348

The fix (still opened): 
https://github.com/appium/appium-android-bootstrap/pull/21

**Comment by shynkevich-alex** [comment]
@TikhomirovSergey  thanks.
