### ISSUE TITLE
pinch doesn't work as expected

### ISSUE THREAD

**Issue by rompic** [appium/java-client#424]
## Description

I'm trying to pinch a mapview on IOS 9.3 and it seems to tap outside of the element
## Environment
- java client build version or git revision if you use some shapshot: 4.0.0
- Appium server version or git revision if you use some shapshot: 1.5.3
- Desktop OS/version used to run Appium if necessary: Mac OSX 10.11.5
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 6.2.1
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: simulator
## Details

The map view is located on
location: {10, 64}
and has a size of
size: {355, 355}

However appiums seems to click on y 482 which is far outside of the element.

   also see discussion concerning zoom in https://discuss.appium.io/t/zoom-and-pinch-have-no-impact-though-there-is-no-error/3746/7
## Code To Reproduce Issue [ Good To Have ]

map.getSize()
map.pinch();
## Ecxeption stacktraces

none
## Link to Appium logs

 [debug] [Instruments] [INST] 2016-06-22 18:36:15 +0000 Debug: Got new command 47 from instruments: au.getElement('25').rect()
    [debug] [Instruments] [INST] 2016-06-22 18:36:15 +0000 Debug: evaluating au.getElement('25').rect()
    [debug] [Instruments] [INST] 2016-06-22 18:36:15 +0000 Debug: evaluation finished
    [debug] [Instruments] [INST] 2016-06-22 18:36:15 +0000 Debug: responding with:
    [debug] [Instruments] [INST] 2016-06-22 18:36:15 +0000 Debug: Running system command #48: /usr/local/Cellar/node/6.2.1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/kp/1dwvz50n44ldz0xlxw7xw4280000gp/T/instruments_sock 2,{"status":0,"value":{"origin":{"x":10,"y":64},"size":{"width":3...
    [debug] [UIAuto] Socket data received (83 bytes)
    [debug] [UIAuto] Got result from instruments: {"status":0,"value":{"origin":{"x":10,"y":64},"size":{"width":**355**,"height":**355**}}}
    [debug] [UIAuto] Sending command to instruments: target.touch([{"time":0.2,"touch":[{"x":197,"y":128},{"x":197,"y":482}]},{"time":0.4,"touch":[{"x":187.5,"y":241.5},{"x":187.5,"y":241.5}]}])
    [debug] [Instruments] [INST] 2016-06-22 18:36:16 +0000 Debug: Got new command 48 from instruments: target.touch([{"time":0.2,"touch":[{"x":197,"y":128},{"x":197,"y":482}]},{"time":0.4,"touch":[{"x":187.5,"y":241.5},{"x":187.5,"y":241.5}]}])
    [debug] [Instruments] [INST] 2016-06-22 18:36:16 +0000 Debug: evaluating target.touch([{"time":0.2,"touch":[{"x":197,"y":128},{"x":197,"y":**482**}]},{"time":0.4,"touch":[{"x":187.5,"y":241.5},{"x":187.5,"y":241.5}]}])
    [debug] [Instruments] [INST] 2016-06-22 18:36:16 +0000 Debug: target.touch(__NSCFArray)
    [debug] [Instruments] [INST] 2016-06-22 18:36:16 +0000 Debug: evaluation finished
    [debug] [Instruments] [INST] 2016-06-22 18:36:16 +0000 Debug: responding with:
    [debug] [Instruments] [INST] 2016-06-22 18:36:16 +0000 Debug: Running system command #49: /usr/local/Cellar/node/6.2.1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/kp/1dwvz50n44ldz0xlxw7xw4280000gp/T/instruments_sock 2,{"status":0,"value":""}...
    [debug] [UIAuto] Socket data received (25 bytes)
    [debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
    [MJSONWP] Responding to client with driver.performMultiAction() result: null

**Comment by rompic** [comment]
on android (emulator API 22) it just seems to swipe in some way. But again y coordinates seem to be way out of scope.

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"38"}}
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getSize
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"width":1080,"height":1530}}
    [debug] [AndroidBootstrap] Received command result from bootstrap
    [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"performMultiPointerGesture","params":{"actions":[[{"action":"press","time":0.005,"touch":{"element":"38","x":540,"y":486}},{"action":"moveTo","time":0.01,"touch":{"element":"38","x":540,"y":1008}}],[{"action":"press","time":0.005,"touch":{"element":"38","x":540,"y":**2016**}},{"action":"moveTo","time":0.01,"touch":{"element":"38","x":540,"y":1008}}]]}}
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"performMultiPointerGesture","params":{"actions":[[{"action":"press","time":0.005,"touch":{"element":"38","x":540,"y":486}},{"action":"moveTo","time":0.01,"touch":{"element":"38","x":540,"y":1008}}],[{"action":"press","time":0.005,"touch":{"element":"38","x":540,"y":2016}},{"action":"moveTo","time":0.01,"touch":{"element":"38","x":540,"y":1008}}]]}}
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: performMultiPointerGesture
    [debug] [AndroidBootstrap] Received command result from bootstrap
    [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK"}
    [MJSONWP] Responding to client with driver.performMultiAction() result: "OK"
    [HTTP]

**Comment by TikhomirovSergey** [comment]
@rompic 
Yes. I and @SrinivasanTarget know about that bug. We want completely redesign both _pinch_ and _zoom_ methods.

**Comment by TikhomirovSergey** [comment]
We are going to make `pinch`/`zoom` methods deprecated. Probably they won't be supported anymore
