### ISSUE TITLE
Swipe Action Performs press action while swiping over link

### ISSUE THREAD

**Issue by gowriremo** [appium/java-client#425]
## Description

I'm Trying to Swipe over a UIALink Element in ios8.4 simulator using Appium. While Swiping it works fine but at the End it performs the Press action too. 

touchAction.press(startx, starty).waitAction(duration).moveTo(endx, endy).release();

How swipe over the link without pressing the link.

**Comment by SrinivasanTarget** [comment]
@imurchie Any suggestions?

**Comment by TikhomirovSergey** [comment]
@gowriremo We are going to make the `swipe` method deprecated. Probably it won't be supported anymore.
