### ISSUE TITLE
IOS removeApp call issues target application appears to have died

### ISSUE THREAD

**Issue by go2guy** [appium/java-client#426]
## Description

Sometimes when calling removeApp() I get an error that it appears the target application has died.  Sometimes the code works fine then other times it does not.
## Environment
- java client build version or git revision if you use some shapshot: 4.0.0
- Appium server version or git revision if you use some shapshot: 1.5.3
- Desktop OS/version used to run Appium if necessary: OSX 10
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 5.5.0
- Mobile platform/version under test: 
- Real device or emulator/simulator: iPhone 6 Version 9.3.2
## Details

I'm trying to uninstall the latest app and install the latest app everynight from a nightly build.   I do this by creating a driver instance and calling removeApp() then close the driver.  Then I start another driver instance.  Since the app is not installed that driver instance will install the app.

What I see is that this only works about 50% of the time.  It is hit and miss.  The app gets uninstalled but it never makes it to the new driver to reinstall the new app as it issues an Abnormal Instruments termination.  

Maybe I'm doing this wrong as well and there is a better way to uninstall and reinstall the latest app.
## Code To Reproduce Issue [ Good To Have ]

```
    app = new File(context.getCurrentXmlTest().getParameter("ipafile"));
            cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
            cap.setCapability(MobileCapabilityType.DEVICE_NAME,
                context.getCurrentXmlTest().getParameter("virtualDevice"));
            cap.setCapability(MobileCapabilityType.UDID, context.getCurrentXmlTest().getParameter("udid"));
            cap.setCapability(MobileCapabilityType.PLATFORM_NAME, context.getCurrentXmlTest().getParameter("platformName"));
            cap.setCapability(IOSMobileCapabilityType.BUNDLE_ID, context.getCurrentXmlTest().getParameter("bundleID"));

            driver = new IOSDriver<MobileElement>(AppiumService.getUrl(), cap);

           //Remove the App
            ((AppiumDriver<MobileElement>) driver).removeApp(context.getCurrentXmlTest().getParameter("bundleID"));
            ((AppiumDriver<MobileElement>) driver).quit();

            driver = null;
           //Let the new driver install the new app
            driver = new IOSDriver<MobileElement>(AppiumService.getUrl(), cap);
```
## Ecxeption stacktraces

https://gist.github.com/nuggit32/78faf895149949954d50299ddddd82a1
## Link to Appium logs

https://gist.github.com/nuggit32/78faf895149949954d50299ddddd82a1

**Comment by nuggit32** [comment]
Can I get some feedback on how to proceed using removeApp on IOS?  Is this a known issue?

**Comment by SrinivasanTarget** [comment]
@nuggit32 Yes this seems like an issue with server.

@imurchie FY, Your thoughts on this please.
Latest gist: https://gist.github.com/SrinivasanTarget/34718615bbd880ee17a9cc91cd350bcf

**Comment by nuggit32** [comment]
@SrinivasanTarget do I need to open the issue on the server side?

**Comment by SrinivasanTarget** [comment]
@nuggit32 Yes please and then tag it here

**Comment by nuggit32** [comment]
#https://github.com/appium/appium/issues/6669

**Comment by saikrishna321** [comment]
Closing as issue on server-side is closed.
