### ISSUE TITLE
Appium blocks screen while using long press

### ISSUE THREAD

**Issue by shay777** [appium/java-client#428]
## Description

I have a message that I should long press on it.
When the code for the long press is starting to performed, appium basically blocks the screeen in a way that I cannot even manually press on that message. After a few seconds appium releases the screen so I can manually tap anywhere (without performing the long press).

## Environment

* java client build version or git revision if you use some shapshot: 3.2.0 / 4.0.0
* Appium server version or git revision if you use some shapshot: 1.4.8/1.4.16/1.5.2
* Desktop OS/version used to run Appium if necessary:mac os
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:ios
* Real device or emulator/simulator:real device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

       TouchAction action = new TouchAction(driver);
        action.longPress(getElement(by),millisecond).perform();

## Ecxeption stacktraces
[ios_logs.txt](https://github.com/appium/java-client/files/339379/ios_logs.txt)

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

**Comment by SrinivasanTarget** [comment]
@shay777 Why do you want to do long press manually or do any actions on screen when appium is already acting on it?

**Comment by shay777** [comment]
I don't want to manually press on the screen.
I wrote a code that will perform it.
What I mean is that the script runs, reaches the ling for the long press, and not performing it.
The thing is that the long press part never performs and also appium blocks the screen. I saw it because I cannot even press manually on the message while appium tries to run the code for the long press.

**Comment by SrinivasanTarget** [comment]
@shay777 Ok Thanks for the info.Will look into this in sometime.Going forward please share your logs in form of gist.

**Comment by shay777** [comment]
sure
thanks

**Comment by SrinivasanTarget** [comment]
@shay777 I don't see any issues with ```longPress``` on iOS.It works fine for me and also in the logs attached here.I can see the status is success for ```longPress``` in logs attached.

**Comment by shay777** [comment]
@SrinivasanTarget  Thanks for your assistance

**Comment by shay777** [comment]
The long press is actually performed as you said. 
We changed our ios code so now with a long press I can see the default options on the tooltip (cut,copy,paste) but not the customized options.
Manually I can see all the options.
Should I open a new query regarding this or it can be answered here?
Thanks

**Comment by SrinivasanTarget** [comment]
@shay777 I think that it's an expected behaviour with TouchActions.I think your question needs to be raised in our forum https://discuss.appium.io/

**Comment by SrinivasanTarget** [comment]
@shay777 I'm closing this.
