### ISSUE TITLE
Swipe always change to long press

### ISSUE THREAD

**Issue by 18516329677** [appium/java-client#436]
## Description

After i upgrade appium to 1.5.3 and use java client 4.0 , swipe does not work for IOS in my project.
i want to use swipe to refresh order list in my app , but it always perform long press action , then the app will change to multiple select page , swipe can not be finished.
From the appium log i can see that when call swipe method , the start point will be pressed for 0.2s by default.

## Environment

java client 4.0
appium: 1.5.3
node version:v6.2.0
test machine：iPhone 5
test platform: IOS 9.2.1

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

      int width = driver.manage().window().getSize().width;
      int height = driver.manage().window().getSize().height;
      driver.swipe(width / 2, height * 2 / 5, width / 2, height * 4 / 5, 500);

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/869464ed-57f7-47b2-bcc8-93d528bbd7ea/touch/perform {"actions":[{"action":"press","options":{"x":160,"y":227}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":227}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [iOS] Executing iOS command 'performTouch'
[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":160,"y":227}],"time":0.2},{"touch":[{"x":160,"y":227}],"time":0.7},{"touch":[{"x":160,"y":454}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-07-11 07:15:33 +0000 Debug: Got new command 11 from instruments: target.touch([{"touch":[{"x":160,"y":227}],"time":0.2},{"touch":[{"x":160,"y":227}],"time":0.7},{"touch":[{"x":160,"y":454}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-07-11 07:15:33 +0000 Debug: evaluating target.touch([{"touch":[{"x":160,"y":227}],"time":0.2},{"touch":[{"x":160,"y":227}],"time":0.7},{"touch":[{"x":160,"y":454}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-07-11 07:15:33 +0000 Debug: target.touch(__NSCFArray)
[debug] [Instruments] [INST] 2016-07-11 07:15:34 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-07-11 07:15:34 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-07-11 07:15:34 +0000 Debug: Running system command #12: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/p9/9bdgbcp94dz0h2mhwl9z3s7r0000gn/T/instruments_sock 2,{"status":0,"v...
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/869464ed-57f7-47b2-bcc8-93d528bbd7ea/touch/perform 200 1912 ms - 76 
 INFO [main] (MCommand.java:190) - Swipe down
 INFO [main] (SmartStepExecutor.java:93) -

**Comment by 18516329677** [comment]
@Srinivasan Sekar

**Comment by SrinivasanTarget** [comment]
@18516329677 Please take a look at this https://github.com/appium/java-client/issues/350

**Comment by SrinivasanTarget** [comment]
@18516329677 If you still face issues please paste the entire logs here inform of gist:https://gist.github.com/

**Comment by 18516329677** [comment]
@SrinivasanTarget 
This seems to be a sever bug , when i try to run the same script with appium 1.5.3 , it works......so i need to wait server update?

**Comment by 18516329677** [comment]
@SrinivasanTarget  here is the full logs<script src="https://gist.github.com/18516329677/be1c73c81a38abd091f4f2277c247b3a.js"></script>

**Comment by SrinivasanTarget** [comment]
```This seems to be a sever bug , when i try to run the same script with appium 1.5.3 , it works``` What does it mean? Why do you need to wait for server update?

**Comment by 18516329677** [comment]
@SrinivasanTarget sorry ,  i mean i run the same script with Appium 1.4.13 , it works...

**Comment by TikhomirovSergey** [comment]
Guys, do not argue. :)
There is the interesting string
https://gist.github.com/18516329677/be1c73c81a38abd091f4f2277c247b3a#file-gistfile1-txt-L314

Why x turned into 0? When x stays the same when the offset should be 0. At this case the offset equals  the original x (!!!). Where is logic? I'm looking at the current implementation of the swiping at the client side. Everything should be ok. https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/ios/IOSDriver.java#L171

**Comment by TikhomirovSergey** [comment]
@18516329677 
Could you try this code with the endX which differs from the startX?

>  int width = driver.manage().window().getSize().width;
> int height = driver.manage().window().getSize().height;
> driver.swipe(width / 2, height * 2 / 5, width / 2, height * 4 / 5, 500);

**Comment by TikhomirovSergey** [comment]
https://medium.com/@scottdixon/appium-touch-examples-w-nodejs-ios-wd-ee2b9956aab1#.y1xqx7dzm

**Comment by TikhomirovSergey** [comment]
@18516329677 
The current implementation of the swiping on iOS: https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/ios/IOSDriver.java#L171

**Comment by TikhomirovSergey** [comment]
@18516329677 Sorry for the removed reply. I was not run into the problem completely.

**Comment by 18516329677** [comment]
@TikhomirovSergey  so i really have to wait the server side update ? or there is another way can solve this issue?Thanks for your replies!

**Comment by TikhomirovSergey** [comment]
@scottdixon @imurchie 
Any ideas?

**Comment by 18516329677** [comment]
finally , i got the answer .
when i use 
new TouchAction(driver).longPress(width / 2, height * 2 / 5).moveTo(0, height * 2 / 5).release().perform();
swipe works .
i suppose this issue may be caused by the duration time.

**Comment by TikhomirovSergey** [comment]
@18516329677 This is interesting. But anyway you can use very low time out as a workaround. What will happen if you will set zero timeout?

**Comment by toejough** [comment]
same as https://github.com/appium/appium-ios-driver/issues/150?

**Comment by 18516329677** [comment]
@TikhomirovSergey i have tried , when the duration is zero , swipe will not perform.

**Comment by 18516329677** [comment]
@toejough i think it's the same issue.

**Comment by SrinivasanTarget** [comment]
@18516329677 This has been fixed in server.If your running from ```appium``` source please take a pull and try.It should be working now.

**Comment by SrinivasanTarget** [comment]
@18516329677 I'm closing this.
