### ISSUE TITLE
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session

### ISSUE THREAD

**Issue by SergioLeone** [appium/java-client#443]
## Description

Trying to use PageFactory with appium and get the following exception
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session

## Environment

* java client build version or git revision if you use some shapshot: 4.0.0
* Appium server version or git revision if you use some shapshot: 1.5.3
* Desktop OS/version used to run Appium if necessary: MacOS X 10.10.5
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: NA
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: Device

## Details
Just started learning appium. Have some knowledge of selenium. Want to implement PageFactory functionality, but get exception. I have found solutions, actually taken a complete code with minor modifications from my side that was said to be working from here https://github.com/appium/java-client/issues/73, but still can not figure out what is wrong.

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/SergioLeone/eef8b4c350f5521b89837bbfb880bbeb

## Ecxeption stacktraces

NA

## Link to Appium logs

https://gist.github.com/SergioLeone/53bd921a2535ab4162f47262fce559ab

**Comment by TikhomirovSergey** [comment]
Hi @SergioLeone
It is not the problem of the Java cliend. And it is not the propblem of the server.

https://github.com/appium/appium/releases/tag/v1.5.0
>Remove long-deprecated name locator strategy
