### ISSUE TITLE
java -client4.1  "EventFiringWebDriverFactory.getEventFiringWebDriver"capabilities turn to null

### ISSUE THREAD

**Issue by tutunang** [appium/java-client#450]
## Description

use java-client 4.1 found :+1: 

capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, browser_Name); 
	        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, platform_Name);  
	        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,device_Name);  
	        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, platform_Version);  

	  driver = new AndroidDriver(new URL(hubURL),capabilities);
      driver2= EventFiringWebDriverFactory.getEventFiringWebDriver(driver, new AlertListener(), new ElementListener());

the driver2 is null!!!!!

when i debug found when the code run into "EventFiringWebDriverFactory.getEventFiringWebDriver(driver, new AlertListener(), new ElementListener());"

the capabilities turn to null;

## Environment
jdk 1,7
java -client 4.1
selenium 2.53

**Comment by TikhomirovSergey** [comment]
@tutunang 
The fix is there #451

**Comment by tutunang** [comment]
excuse me！when could we hava new version 4.1.1？

**Comment by SrinivasanTarget** [comment]
@tutunang It's available in Maven Central Repo already. http://search.maven.org/#artifactdetails%7Cio.appium%7Cjava-client%7C4.1.1%7C

**Comment by tutunang** [comment]
@SrinivasanTarget  ok! 4.1.1 has been useda moment ago！ there is no problem！
