### ISSUE TITLE
Unable to perform a precise swipe [iOS]

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/java-client#453]
## Description

I've been using driver.swipe() with the swipe duration of at least 1 second to make sure that the swipe is slow and will not cause a fling instead.

With 1.5, I had to change to TouchAction as the swipe changed from absolute to relative.

My current "scroll up" code looks like this.

```

            touchAction
                    .press(centerX, startY)
                    .moveTo(0, endY)
                    .waitAction(1000)
                    .release()
                    .perform(); 

```

The problem with TouchAction is that it doesn't provide an option to slow down the swipe.I was trying to work around it with .waitAction, but it doesn't slow down the swipe. What happens, is that the move is very fast, then there's a delay (waitAction) and then the release. It looks like a slowed down fling.
## Environment
- java client build version: 4.0.0
- Appium server version: 1.5.3
- Desktop OS: OSX El Capitan 10.11.4
- Node.js version 5.10.1
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: real device
## Link to Appium logs

https://gist.github.com/Simon-Kaz/2fc17177c818197def4749d2ab5f18b6

**Comment by TikhomirovSergey** [comment]
@Simon-Kaz We are going to make the `swipe` method deprecated. Probably it won't be supported anymore.
