### ISSUE TITLE
locating elements: PageFactory with uiAutomator throws exception

### ISSUE THREAD

**Issue by SergioLeone** [appium/java-client#457]
## Description

I'm using PageFactory and trying to locate elements with uiAutomator like this:

```
@AndroidFindBy 
(uiAutomator = "new UiSelector().className(\"android.widget.TextView\").text(\"Home\")")
public MobileElement testElement;
```

but after running the code it throws:
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

## Environment

* java client build version or git revision if you use some shapshot: 4.0.0
* Appium server version or git revision if you use some shapshot: 1.5.3
* Desktop OS/version used to run Appium if necessary: MacOS 10.11
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: Device (Samsung S4)

## Details

NA

## Code To Reproduce Issue [ Good To Have ]

```
@AndroidFindBy 
(uiAutomator = "new UiSelector().className(\"android.widget.TextView\").text(\"Home\")")
public MobileElement testElement;

testElement.click()
```

## Ecxeption stacktraces

NA

## Link to Appium logs

https://gist.github.com/SergioLeone/fa5fc5bcbdc33b94ef6f7a38b8bc3543

**Comment by vikramvi** [comment]
@SergioLeone  can you please comment why is this issue closed and what was your solution ?

**Comment by Harlber** [comment]
Just import [commons-lang3](https://mvnrepository.com/artifact/org.apache.commons/commons-lang3/3.10) in your project，it works for me. @vikramvi
