### ISSUE TITLE
In-app Browser view: Unable to click WebElement

### ISSUE THREAD

**Issue by jmehtaebates** [appium/java-client#466]
## Description

My app has an in-app browser which opens up when user clicks 'Shop' button. At this point user is in the browser but still within the app. I am able to successfully switch context to this webview but when i try to click on any element or perform any other action it fails. I have provided the code I am using as well as the link to the logs below
## Environment

I am using Appium Version 1.5.3 (Ara)
Running tests on iOS 6S Plus simulator
## Code To Reproduce Issue [ Good To Have ]

```
@BeforeMethod
public void setUp() throws MalformedURLException {
    DesiredCapabilities caps = new DesiredCapabilities();
    caps.setCapability("platformName", "iOS");
    caps.setCapability("platformVersion", "9.3"); 
    caps.setCapability("deviceName", "iPhone 6s Plus"); 
    caps.setCapability("app", "path to my app"); 
    caps.setCapability("nativeWebTap", true);

    driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
}

    driver.findElementByAccessibilityId("Shop Now").click();

    driver.context(driver.getContextHandles().toArray()[1].toString());

    driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[1]")).click()
```
## Details about the views:

Views: NATIVE_APP
Views: WEBVIEW_79548.1
context after switching is WEBVIEW_79548.1
## Link to Appium logs

You can find logs here: https://gist.github.com/jmehtaebates/2c369a1d430f7d8a113c8594be16e8fd

**Comment by jmehtaebates** [comment]
@TikhomirovSergey can you please take a look ?

**Comment by saikrishna321** [comment]
@jmehtaebates closing as inactive. Please raise if issue exists
