### ISSUE TITLE
There is no setconnection method for iOS 

### ISSUE THREAD

**Issue by NahidSiddiqui** [appium/java-client#472]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.
## Environment
- java client build version or git revision if you use some shapshot:
- Appium server version or git revision if you use some shapshot:
- Desktop OS/version used to run Appium if necessary:
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
- Mobile platform/version under test:
- Real device or emulator/simulator:
## Details

Please provide more details, if necessary.
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)
## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.
## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by NahidSiddiqui** [comment]
Although there was I believe a method for android to access the wifi controls in Appium, there isn't and never was any method to access the wifi controls on an iOS device. On top of this there doesn't seem to be any work around for this either.

**Comment by TikhomirovSergey** [comment]
@NahidSiddiqui It should be supported by server. It seems that iOS UI automation mode still doesn't support the network switching.
