### ISSUE TITLE
Compile-time issues when upgrading to 4.1.2

### ISSUE THREAD

**Issue by ssynix** [appium/java-client#474]
## Description

I'm trying to upgrade java-client 3.4.1 to 4.1.2.

## Details

Our framework is built on top of Selenium and Appium's java-client. With the recent update, a simplified version of our interfaces below is failing to compile. I've tried multiple modifications to our code with no result, especially since I don't understand why the error is happening.

## Code To Reproduce Issue

I've managed to narrow down the problem to this set of interfaces [on Ideone](https://ideone.com/Q6booi). I believe [this change](https://github.com/appium/java-client/compare/3.4.1...4.1.2#diff-347229f21cec91dcb24eb35f3ba0f348R42) is what is causing the issue for us.

* For some reason, if we continue to `extend MobileDriver` without a generic parameter, the compiler is not able to override `execute`. This completely baffles me...

* If I `extend MobileDriver<WebElement>` or change all our interfaces to generic (`IFrameworkMobileDriver<T extends WebElement> extends MobileDriver<T>`), the Java compiler pulls two versions of `FindsByXPath` into the our class with what it thinks are non-covariant return types (`List<T>` and `List<WebElement>` are not covariant?).

Any idea what I'm missing here?

**Comment by TikhomirovSergey** [comment]
Hi @ssynix 
It is known issue. There are many details provided here https://github.com/appium/java-client/pull/413
Also there are many details how to resolve it. You need to use eclipse compiler. 
If you use maven then https://github.com/appium/java-client/blob/master/archive/pom.xml#L217
if you use gradle then https://github.com/appium/java-client/blob/master/build.gradle#L31
I'm waiting for your response.

**Comment by ssynix** [comment]
It seems I haven't been as thorough in my searching! Unfortunately, the current set up at our company gets in the way of using a different compiler.

I read most of the issues that you linked, and I see there have been a lot of development going on into refactoring these interfaces, but I still fail to understand why this issue is happening. Are we facing a bug in the java compiler?

I managed to fix the problem by changing our override from
    `public void execute(String driverCommand, Map<String, ?> parameters) {}`
to
    `public void execute(String driverCommand, Map parameters) {}`

I still have no idea why making `MobileDriver` generic would suddenly necessitate removing the type parameters from our overridden methods.

I have given up on trying to understand this issue for now and will probably resort to the fix/workaround above.

Thanks for the additional details!

**Comment by TikhomirovSergey** [comment]
@ssynix Yes. It is probably javac issue. But I'm not sure.
