### ISSUE TITLE
Is it possible that MobileElement/AndroidElement/IOSElement support element description?

### ISSUE THREAD

**Issue by ansonliao** [appium/java-client#478]
## Description

Hi,
For more details to track the test operation/flow in test report (for example, ReportNG, ExtentsReport), is it possible that add a public `String` field to `MobileElement`/`AndroidElement`/`IOSElement` for storing the element's description?

for example:

``` java
public class HomePageObjects {

    @iOSFindBy(id = "submit", description = "Home page - [Submit] button")
    public IOSElement submitButton;

    ...
}

public class ProfilePageObjects {

    @iOSFindBy(id = "submit", description = "Profile page - [Submit] button")
    public MobileElement submitButton;
}
```

so that in calling reporter's log method in personal Appium test project:

``` java
public void click(MobileElement e) {
    e.click();
    // reportNG
    reporter.log("Click: " + e.getDescription());
}

public void clearText(MobileElement e) {
    e.clear();
    //reportNG
    reporter.log("Clear Text: " + e.getDescription());
}

public void enterText(MobileElement e, String s) {
    e.sendKeys(s);
    //reportNG
    reporter.log("Type Text: " + e.getDescription());
}

public void swipDown(MobileElement e) {
    //add code here
}
```

so that the test report will be more detail as mobile description supported:

Snipshot of ReportNG:

``` text
Type: ......
Swipe Down: ....
Clear Text: ...
...
Click: Home page - [Submit] button
...
Click: Profile page - [Submit] button
Test fail

Error: MobileElemet: by.id = "submit" still displayed.
```

tracking test report test operation flow, it is more easier to locate the it was fail after click profile page submit button, not home page submit button.

please advise.

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.
## Environment
- java client build version or git revision if you use some shapshot:
- Appium server version or git revision if you use some shapshot:
- Desktop OS/version used to run Appium if necessary:
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
- Mobile platform/version under test:
- Real device or emulator/simulator:
## Details

Please provide more details, if necessary.
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)
## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.
## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by rromanik** [comment]
Hi all,

I like the idea to have some additional info returned about an element when its 'toString()' method is invoked.

Maybe, to inject such description into @FindBy annotation is not reasonable, but to add, e.g., @Name annotation (in a manner similar to Yandex HtmlElements framework, see [here](https://github.com/yandex-qatools/htmlelements)  and [here](https://oss.sonatype.org/service/local/repositories/releases/archive/ru/yandex/qatools/htmlelements/htmlelements/1.8/htmlelements-1.8-javadoc.jar/!/index.html) ) would be great!

And this enhancement may well be in accord with 'Widget' feature of Appium framework, see [here](https://github.com/appium/java-client/pull/267).

The example code:
```
public class APage {
    @Name("'Login' Button")
    @FindBy(id = "loginButton")
    private Button loginButton;

    public void clickLoginButton() {
        System.out.println("Clicks " + loginButton);
        loginButton.click();
    }
}
```

and invoking 'clickLoginButton()' method from APage would print 
"Clicks 'Login' Button"

And last comment: It does not sound like an issue, but rather as an enhancement proposal. Where should I put it then?

Thanks,
Roman Romanik

**Comment by ansonliao** [comment]
@rromanik 

Good to know Yandex HtmlElements framework, and look good that anntation `@Name`, dont know how to implement it in MobileElement.

any idea?

**Comment by HlebHalkouski** [comment]
@TikhomirovSergey how you look at idea add `Name` annotation like Yandex HtmlElements framework? 

We need to change AppiumField decorator: update `defaultElementFieldDecorator` and `decorateWidget` method.
Add to interceptors constructors parameter `String name` and  in intercept `toString` replace `locator.toString` to `name`:
And add ElementUtil class with logic around `Name` annotation.

I can try to implement this.

**Comment by aldonin** [comment]
@HlebHalkouski hi, any progress? If you need, I have working example, but for 1.4 fork. We use it for our project

**Comment by ansonliao** [comment]
thanks all, I also use `Yandex HtmlElements framework` in my Selenium test, for Appium, I tried to extend MobileElement and finally found that many classes are private in `Java-Client`, it is hard to extend from `Java-Client`.

@HlebHalkouski @aldonin hope can hear the good news from you soon.

**Comment by HlebHalkouski** [comment]
@ansonliao @aldonin  I found good solution. This [merge](https://github.com/appium/java-client/pull/630) make locator factory classes public and I use annotation from java-client with my custom decorator. My decorator is hybrid of `Yandex HtmlElements` decorator with locator factory from java-client.

`
        elementLocatorFactory = new AppiumElementLocatorFactory(context, timeOutDuration, originalDriver,
                new DefaultElementByBuilder(platform, automation));
        blockLocatorFactory = new AppiumElementLocatorFactory(context, timeOutDuration, originalDriver,
                new WidgetByBuilder(platform, automation));`

**Comment by aldonin** [comment]
@HlebHalkouski Do you plan any pull request to java-client? It would be great. Thanks in advance

**Comment by HlebHalkouski** [comment]
@aldonin no, no pull request. Because I created [issue](https://github.com/appium/java-client/issues/625) and Mykola explained me why appium java-client don't need updates. 
You can contact me by Skype and I will show you me inmplementation.

**Comment by saikrishna321** [comment]
Closing w.r.t https://github.com/appium/java-client/issues/625

**Comment by ansonliao** [comment]
@HlebHalkouski 
could you share your code that those classes implemetation?
Contact you via Skyep but no response.

`elementLocatorFactory = new AppiumElementLocatorFactory(context, timeOutDuration, originalDriver, new DefaultElementByBuilder(platform, automation));' ' blockLocatorFactory = new AppiumElementLocatorFactory(context, timeOutDuration, originalDriver, new WidgetByBuilder(platform, automation));
`

**Comment by UltroEdward** [comment]
Any custom Decorator & extended mobile elements implementation?
