### ISSUE TITLE
bugs in errorcodes parsing with lateset selenium3 beta 4

### ISSUE THREAD

**Issue by wangxf1030** [appium/java-client#488]
## Description

NO_SUCH_ELEMENT can't be parsed.
NPE. Please see the attachment at the end for stacktrace.
## Environment

java8
Appium1.5.2
MAC
Android
## Details

With the latest selenium(selenium3 beta 4) and appium1.5.2:
When "NO_SUCH_ELEMENT" error is parsed,
 ErrorCodesMobile.getExceptionType(int) is supposed to call  ErrorCodes.getExceptionType(int) , and within that method it should call ErrorCodes.getExceptionType(string). However, ErrorCodes.getExceptionType(string) is overrided by ErrorCodesMobile, but it doesn't call ErrorCodes.getExceptionType(string), instead it thorws NPE.
## Code To Reproduce Issue [ Good To Have ]

call findElement when the element is not displayed
## Ecxeption stacktraces

please see attachment.
<img width="1122" alt="screen shot 2016-10-03 at 10 43 01 am" src="https://cloud.githubusercontent.com/assets/3776782/19295909/8cb16db8-8fec-11e6-8344-14a904322281.png">

**Comment by TikhomirovSergey** [comment]
The migration to Selenium 3 is planned. But we have not started it yet.

**Comment by SrinivasanTarget** [comment]
I'm not able to reproduce this.Can you paste the entire logs inform of gist. It throws NSE exception perfectly for me in Selenium 3.0 with Java-Client #489

**Comment by SrinivasanTarget** [comment]
Also let us know what you are exactly trying to do.
