### ISSUE TITLE
Swipe is not working as expected in Android

### ISSUE THREAD

**Issue by dinkar19121991** [appium/java-client#491]
## Description

If i write something like this driver.swipe(0, 100, 0, 900, 100); , it should swipe the screen from 100 to 900 means we should see the element above in our list or scrollable area as it work for IOS
## Environment
- java client build version or git revision if you use some shapshot: 4.1.2
- Appium server version or git revision if you use some shapshot: 1.5.3
- Desktop OS/version used to run Appium if necessary: MAC 10.12 (16A323)
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
- Mobile platform/version under test: 4.4.2 and 5.1
- Real device or emulator/simulator: Real device(4.4.2) and genymotion simulator (5.1)
## Details

If i write something like this driver.swipe(0, 100, 0, 900, 100); , it should swipe the screen from 100 to 900 means we should see the element above in our list or scrollable area as it work for IOS
## Code To Reproduce Issue [ Good To Have ]

driver.swipe(0, 100, 0, 900, 100);
## Ecxeption stacktraces

no exception but swipe did't happen
## Link to Appium logs

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 28 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> POST /wd/hub/session/a5702278-eed7-497e-890f-b57d7fb9d2c2/touch/perform {"actions":[{"action":"press","options":{"x":0,"y":100}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":0,"y":900}},{"action":"release","options":{}}]}

[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"swipe","params":{"startX":0,"startY":100,"endX":0,"endY":900,"steps":3}}

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":0,"startY":100,"endX":0,"endY":900,"steps":3}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: swipe
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1920]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1920]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Swiping from [x=540.0, y=100.0] to [x=540.0, y=900.0] with steps: 3

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":true,"status":0}

[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.performTouch() result: true
[HTTP] <-- POST /wd/hub/session/a5702278-eed7-497e-890f-b57d7fb9d2c2/touch/perform 200 56 ms - 76 

[HTTP] --> DELETE /wd/hub/session/a5702278-eed7-497e-890f-b57d7fb9d2c2 {}

[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["a5702278-eed7-497e-890f-b...
[debug] [AndroidDriver] Shutting down Android driver

**Comment by TikhomirovSergey** [comment]
It is deorecated now.
