### ISSUE TITLE
pushFile corrputs transfered file

### ISSUE THREAD

**Issue by isbjorn** [appium/java-client#493]
## The problem

`driver.pushFile` corrputs file when called with instance of `java.io.File`
### Not works

```
File file = ...
driver.pushFile(devicePath, file); // corrupts file, looks like it base64 encoded twice
```
### Works

```
import org.apache.commons.io.FileUtils;
...
byte[] content = FileUtils.readFileToByteArray(file); // file -> stream -> byte array
driver.pushFile(devicePath, content); // works
```
## Environment
- Appium 1.5.3
- Node.js  v6.3.1
- Android emulator with 5.1.1
- Appium java-client 4.1.2
## Details

Push one file into virtual device, the first time with `java.io.File`, the second time with `byte[]`
Grab both files from deviced with `adb pull ...`
The first file will be broken

**Comment by TikhomirovSergey** [comment]
Ok.

**Comment by bgizdov** [comment]
I reproduced this issue when I tried to push json file to device with the pushFIle(String path, File file) method.

I solved it this way:
```
String json = // read from file or other;
byte[] data = Base64.encodeBase64(json.getBytes());
driver.pushFile(path, data);
```

**Comment by mykola-mokhnach** [comment]
This is fixed in the version 6+

**Comment by Kpamnani1** [comment]
String json = // read from file or other;
byte[] data = Base64.encodeBase64(json.getBytes());
driver.pushFile(path, data);
This is not working with 6.0.0-BETA5
