### ISSUE TITLE
sendkeys() for AndroidDriver doesn't fill text correctly for all fields event setValue() doesn't work

### ISSUE THREAD

**Issue by fatmafareed** [appium/java-client#505]
## Description

I have a login form, sendKeys() fill username field but not for password field

## Environment

* java client build version or git revision if you use some shapshot: 4.2.1
* Appium server version or git revision if you use some shapshot: 1.4.16.1
* Desktop OS/version used to run Appium if necessary: Windows 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android - marshmallow 
* Real device or emulator/simulator: real device 

## Code To Reproduce Issue [ Good To Have ]
MobileElement u= (MobileElement) helper.appiumDriver.findElementByXPath("//android.view.View[contains(@index,'1')]/android.widget.EditText[contains(@index,'0')]");
		u.sendKeys("e2etesting");
		MobileElement p= (MobileElement) helper.appiumDriver.findElementByXPath("//android.view.View[contains(@index,'3')]/android.view.View[contains(@index,'3')]/android.widget.EditText[contains(@index,'0')]");
	    p.sendKeys("password");

**Comment by saikrishna321** [comment]
closing as inactive.
