### ISSUE TITLE
SessionNotCreatedException when Chrome browser version 54 in real Android device

### ISSUE THREAD

**Issue by JMVM** [appium/java-client#510]
## Description

When trying to automate using Chrome browser in real Android device, getting an exception when trying to create driver instance.

## Environment

* java-client 4.0.0 (checked with 4.1.2 with same issue)
* Chrome driver 2.18.343
* Chrome browser 54.0.2840.68
* Operative system: Android 5.1.1
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Appium 1.4.16.1 for Windows
* Mobile platform/version under test: Samsung Galaxy Note 4
* Real device or emulator/simulator: Real device

## Details

Note that the same issue in Chrome Desktop version related to last Chrome browser version 54 with an old Chrome driver. 

## Ecxeption stacktraces

https://gist.github.com/JMVM/8ca91fad8ad01364867359f4a5096786

## Link to Appium logs

https://gist.github.com/JMVM/30daf6ae54d51105cfc79e70d201c35a

**Comment by mykola-mokhnach** [comment]
Please try it with Appium 1.6

**Comment by SrinivasanTarget** [comment]
Update your Chrome driver version to 2.25 to work with Chrome latest
version that you already have.It should work properly after the update.

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach Please reopen it of the advice above doesn't help.
