### ISSUE TITLE
How to scroll elements in Hamburger menu of Web App on Andoid mobile browser using appium

### ISSUE THREAD

**Issue by Reddypramodh** [appium/java-client#511]
![capture](https://cloud.githubusercontent.com/assets/20171131/20176681/eaf81536-a76e-11e6-9426-7cf0a772d824.JPG)
I am doing automation for a Web App, where I am facing issue with scrolling elements.
Once if I click on hamburger menu it will display 4 elements in one screen and if I swipe left horizontally it will display next set of 4.
The element that I am trying to click is 25 in that list. How can I achieve this

Attached the screen shot of how the elements look in hamburger menu

**Comment by Ser-Gius** [comment]
Get the x,y coordinates of two points where you want to swipe (first point will be where you want to start your swipe, second where you want it to end).

Then use the swipe method like this: swipe(xStart, yStart, xEnd, yEnd, 1000);
or TouchAction like this: action().press(xStart, yStart).waitAction(1000).moveTo(xEnd, yEnd).release().perform();

**Comment by TikhomirovSergey** [comment]
@jedi-tester Is the issue actual yet? If it is true please reopen then.
