### ISSUE TITLE
driver.lockDevice(5) is not working

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/java-client#512]
@TikhomirovSergey 

## Description
unable to lock device using lockDevice(5) method. Getting below error 
org.openqa.selenium.WebDriverException: Method has not yet been implemented 

## Environment

* java client build version: v4.1.2-2
* Appium server version: 1.6.0
* Desktop OS/version used to run Appium if necessary: Mac ElCapiton 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:v6.8.1
* Mobile platform/version under test: iPhone 6 plus and iPad/9.3.2
* Real device or emulator/simulator: real device

## Details

I used IOSDriver<mobileElement>

## Code To Reproduce Issue [ Good To Have ]
`driver.lockDevice(5);`

## Ecxeption stacktraces

> org.openqa.selenium.WebDriverException: Method has not yet been implemented 

## Link to Appium logs
> [HTTP] <-- POST /wd/hub/session/f3139f7b-ecd9-4b1a-bf03-cb4f30bd80a3/element/AF35F06B-97C5-41CF-9846-E93FE93A1453/click 200 4003 ms - 74 
> [HTTP] --> POST /wd/hub/session/f3139f7b-ecd9-4b1a-bf03-cb4f30bd80a3/appium/device/lock {"seconds":5}
> [MJSONWP] Calling AppiumDriver.lock() with args: [5,"f3139f7b-ecd9-4b1a-bf03...
> [debug] [XCUITest] Executing command 'lock'
> [HTTP] <-- POST /wd/hub/session/f3139f7b-ecd9-4b1a-bf03-cb4f30bd80a3/appium/device/lock 501 3 ms - 122 
> [debug] [iProxy] recv failed: Resource temporarily unavailable
> [debug] [iProxy] recv failed: Operation not 

> permitted

**Comment by saikrishna321** [comment]
@shivakrishnach31 this is server issue. Can you pls raise it on server side.

**Comment by shivakrishnach31** [comment]
@saikrishna321 . sure. Thank you.
