### ISSUE TITLE
APK - not found

### ISSUE THREAD

**Issue by ydonev** [appium/java-client#515]
Trying to run an android test on OS X (10.11.6) or Linux (Debian 8.6) I always get an error:  "Could not find app apk at" 

## Details
I am using Google's Keep APK [file](http://www.apkmirror.com/apk/google-inc/keep/). I've tried with other APK files - the same error.
The APK file can be installed successfully via ADB.
isFile returns 'True' - so file path is correct.

## Environment

* java client build version - latest (4.1.2)
* Appium server version - latest (1.6.0)
* OS X (10.11.6) or Debian 8.6
* Node.js version - 6.5
* Mobile platform/version under test: Android 4.4.4 ; 5.1.1; 6.0.1
* Real device
* JDK 1.7.0_71
* Appium doctor says that everything is OK (JAVA_HOME and ANDROID_HOME)

## Code To Reproduce Issue
http://pastebin.com/nTdm9aCA

## Ecxeption stacktraces
http://pastebin.com/qba6wWuK

## Link to Appium logs
No Appium server log.

**Comment by mykola-mokhnach** [comment]
Can it be, that appium/node process does not have read permissions to this file?

**Comment by ydonev** [comment]
Yavors-Mac-mini:res yavordonev$ ls -l com.google.android.keep.apk 
-rwxrwxrwx@ 1 777  staff  12860948 Nov 17 11:50 com.google.android.keep.apk

**Comment by mykola-mokhnach** [comment]
Is Appium service running from the same user account?

**Comment by ydonev** [comment]
Yes, it is running from the same user account.

**Comment by ydonev** [comment]
After restart ... somehow it is fix.

Now I have same problem but when I tried to run the test on remote server (IP address is 192.168.168.x). The error is the same.

**Comment by saikrishna321** [comment]
@SrinivasanTarget can we close this as inactive?

**Comment by SrinivasanTarget** [comment]
@ydonev please try latest version of client and server and log a new defect if you still face this.
