### ISSUE TITLE
Add @FindBy annotations for appium's extra locator strategies

### ISSUE THREAD

**Issue by Jonahss** [appium/java-client#52]
As mentioned in #22

**Comment by umaralikhan** [comment]
fot Page tests and page factory if @FindBy is used to locate some element on hybrid app (web view - FB login page) then should testers need to explicitly change the context of the AppoumDriver?

**Comment by suganeby** [comment]
@iOSFindBy(name = "XXXX") not working in the java-client version > 4.1.0. Getting below error,

'name'is not part of the annotation io.appium.java_client.pagefactory.iOSFindBy

**Comment by Henkoglobin** [comment]
@suganeby the 'name' locator strategy has been removed a year ago: https://github.com/appium/java-client/commit/75433564033cb55bde74595beb3dcf08a9fb9c24

I can't, however, find any rationale for this. It'd be nice to know why the strategy has been removed.

**Comment by suganeby** [comment]
@Henkoglobin
I am still using java client version 3.4.1. I am mostly using name locator in my testcases. Class names are not unique. Elements in the table cells are not accessible even with the accessibility id. name locator was very helpful.

**Comment by VenkateshPS** [comment]
what strategy to use if have same locator id for iOS and Android ?

**Comment by umaralikhan** [comment]
@FindBy
