### ISSUE TITLE
Not able to install appium on my mac

### ISSUE THREAD

**Issue by shay777** [appium/java-client#533]
## Description

I had appium installed and I deleted it. I also deleted node.js and npm.
I re-installed node.js and npm and I am not able to install appium now using the command:
npm install -g appium

not sure what is happening here. any help please?

thanks

https://gist.github.com/shay777/3d4887b23301e55edcbffdedabe2e850

**Comment by vikramvi** [comment]
@shay777 please file this under parent project https://github.com/appium/appium

@triager please close this

**Comment by SrinivasanTarget** [comment]
Its not an issue in appium client/server end. Seems like an npm issue. Downgrade your npm and try installing appium
