### ISSUE TITLE
IOSDriver freezing when connecting to saucelabs (Not Localhost)

### ISSUE THREAD

**Issue by williamrussellajb** [appium/java-client#534]
## Description
Everything works for Desktop while connecting to SauceLabs, just not IOS Driver.

## Environment

* java client build version 1.6.1
* SauceLabs
* MAC Sierra
* SauceLabs Simulator

## Details

I've debugged it down to RemoteWebDriver

## Code To Reproduce Issue [ Good To Have ]

What am I missing?
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session
 
 
 
Code example:
```@Test
public void pleaseLaunchThisDriver() {
 
DesiredCapabilities caps = org.openqa.selenium.remote.DesiredCapabilities.iphone();
caps.setCapability("appiumVersion", "1.6.1");
caps.setCapability("deviceName","iPhone 6s Simulator");
caps.setCapability("deviceOrientation", "portrait");
caps.setCapability("platformVersion","9.3");
caps.setCapability("platformName", "iOS");
caps.setCapability("browserName", "Safari");
 
driver = new IOSDriver<MobileElement>(new URL(“https://MyUserName:MySecretKey@ondemand.saucelabs.com:443/wd/hub“) , caps)
Note: I’ve also changed the port of 443 to port 80.
}
```
 
I have debugged the code, and found that is is hanging within the Appium Java Client, and then inside of Selenium.
 
Inside of RemoteWebDriver.java
Line 601:
`response = executor.execute(command);`
 
It’s trying to execute this:
```
[null, newSession {desiredCapabilities=Capabilities [{appiumVersion=1.6.1, platformVersion=9.3, browserName=Safari, deviceOrientation=portrait, platformName=iOS, version=, deviceName=iPhone 6s Simulator, platform=MAC}]}]
```
 
This ends up hanging for a very long time, eventually timing out.
 
 
As said before, if I directly use the RemoteWebDriver for Desktop, everything is fine. If I use IOSDriver, its freezing, this is preventing me from testing mobile.

**Comment by SrinivasanTarget** [comment]
Closing this as inactive
