### ISSUE TITLE
MultiTouchAction not working as expected on Android

### ISSUE THREAD

**Issue by jedi-tester** [appium/java-client#541]
## Description

I'm trying to create a zoom method using multi-touch action to zoom in/out a map view
I've enabled "show touches" and "pointer location" in debug mode to see how the action is performed.
When the actions are performed separately, then the pointer is moving in correct direction (action0 starts a little lower and to the left of center and moving to the lower left corner, and action1 starts a little upper and to the right of center and moving to the upper right conrer).
When I combine two actions in a multi-touch, then both are moving in a wrong direction. 

## Environment

* java client build version or git revision if you use some shapshot: 4.1.2
* Appium server version or git revision if you use some shapshot: 1.6.1
* Desktop OS/version used to run Appium if necessary: MacOS X
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 7.0.0
* Mobile platform/version under test: Android, 5.1.1. Native app
* Real device or emulator/simulator: Real device

## Details

NA

## Code To Reproduce Issue [ Good To Have ]

```
protected void zoomIn(MobileElement windowElement) {
        int leftX = windowElement.getLocation().getX();
        int rightX = windowElement.getSize().getWidth() + leftX;
        int midX = (leftX + rightX) / 2;

        int upperY = windowElement.getLocation().getY();
        int lowerY = windowElement.getSize().getHeight() + upperY;
        int midY = (upperY + lowerY) / 2;

        int aX = (int) (midX * 0.3);
        int aY = (int) (midY * 1.7);
        int bX = (int) (midX * 0.8);
        int bY = (int) (midY * 1.2);

        int cX = (int) (midX * 1.7);
        int cY = (int) (midY * 0.3);
        int dX = (int) (midX * 1.2);
        int dY = (int) (midY * 0.8);

        TouchAction action0 = new TouchAction(driver);
        TouchAction action1 = new TouchAction(driver);

        action0.press(bX, bY).waitAction(1000).moveTo(aX, aY).release();
        action1.press(dX, dY).waitAction(1000).moveTo(cX, cY).release();

        MultiTouchAction mAction = new MultiTouchAction(driver);

        mAction.add(action0).add(action1).perform();

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

## Ecxeption stacktraces

NA

## Link to Appium logs

NA

**Comment by Ser-Gius** [comment]
I've inspected the logs and it seems that on multi touch action the moveTo() method takes offset coordinates.

So the moveTo coordinates become as follows: (aX+bX, aY+bY) and (cX+dX, cY+dY)

Is this intended?

**Comment by TikhomirovSergey** [comment]
@Ser-Gius 

>I've inspected the logs and it seems that on multi touch action the moveTo() method takes offset coordinates.

Yes. `moveTo()` should take relative values. But there are some issues on Android side. There is one of them 
https://github.com/appium/appium/issues/7486

I would like to advice you to use `moveTo` with `WebElement` and offset coordinates (if necessary) as parameters.

**Comment by Ser-Gius** [comment]
@TikhomirovSergey 
Thanks for the response Sergey.

I thought it a bit strange that single touch action would take absolute coordinates for moveTo() and when the same method is used in multi-touch then it takes relative values.

Could you please explain how does moveTo(WebElement, x, y) perform? Does it take x,y offset from the center of WebElement?

**Comment by Ser-Gius** [comment]
To answer my own question and if anyone else will have the same question. 
I've done some more testing of this functionality and `press(WebElement, x, y) ` and `moveTo(WebElement, x1, y1)` will press on x,y offset of top left corner of WebElement and then move to x1,y1 offset of top left corner of WebElement.

But again, if we are using this in MultiTouch, then it becomes a bit hectic. For example I want a pinch method on an element:
```
TouchAction action1 = new TouchAction(driver).press(mapLayout, 100, -100).waitAction(1000).moveTo(mapLayout, 500, -500).release();
        TouchAction action2 = new TouchAction(driver).press(mapLayout, -100, 100).waitAction(1000).moveTo(mapLayout, -500, 500).release();

MultiTouchAction mAction = new MultiTouchAction(driver).add(action1).add(action2);
        mAction.perform();
```

Now in here `moveTo()` will give very hectic movement.

Is it possible to implement `moveTo()` to perform in the same way in MultiTouchAction as in TouchAction?
