### ISSUE TITLE
GeneralServerFlag.UIID doesn't work

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#544]
## Description

I've requirement to register appium node with selenium HUB. From command line I execute
appium --nodeconfig EMULATOR_Nexus_4_2.json -p 4823 -bp 4824 -U emulator-5554

Trying to achieve similar behaviour through programme but it doesn't work

AppiumDriverLocalService driverLocalService = AppiumDriverLocalService
        			.buildService(new AppiumServiceBuilder()
        					.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
        					.usingDriverExecutable(new File("/usr/local/bin/node"))
        					.usingPort(4445)
        					.withArgument(GeneralServerFlag.UIID, "emulator-5554")			
        					.withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER,"4824")
        					.withArgument(GeneralServerFlag.SESSION_OVERRIDE)
        					.withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
        					.withArgument(GeneralServerFlag.CONFIGURATION_FILE, nodeConfigFilePath));

## Environment

* java client build version or git revision if you use some shapshot: latest
* Appium server version or git revision if you use some shapshot: 1.6.3
* Desktop OS/version used to run Appium if necessary: MAC 10.11.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: NA
* Real device or emulator/simulator:   Android Emulator

## Details

NA

## Code To Reproduce Issue [ Good To Have ]

Mentioned in description

## Ecxeption stacktraces

NA

## Link to Appium logs

NA

**Comment by TikhomirovSergey** [comment]
Hi @vikramvi 
It seems there is not enough information. 

This flag is deprecated and it was removed on 12 Apr 2016. Please take a look at this commit. 
https://github.com/appium/java-client/commit/7eb5911ed79f2e93ad0527372e6fa8e613796967#diff-7ffa4c71ce252408a910625b7ab34f4eL46

So I'm not sure that the version is the latest. Also please take a look at this doc
https://github.com/appium/appium/blob/9441a89f7e368f0c621db3a0cf9ab074c045ac3a/docs/en/writing-running-appium/server-args.md

Even there is no info about UIID flag. 

It is possible to define that by capabilities

```java
AppiumDriverLocalService driverLocalService = AppiumDriverLocalService
                .buildService(new AppiumServiceBuilder()
                        .usingPort(4445)
                        .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER,"4824")
                        .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                        .withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
                        .withArgument(GeneralServerFlag.CONFIGURATION_FILE, new File("sone.json").getAbsolutePath())
                .withCapabilities(new DesiredCapabilities(ImmutableMap.of(MobileCapabilityType.UDID, "emulator-5554"))));
        driverLocalService.start();
```

The result
```
[Appium] Non-default server args:
[Appium]   port: 4445
[Appium]   bootstrapPort: 4824
[Appium]   sessionOverride: true
[Appium]   nodeconfig: 'C:\\appium\\java-client\\sone.json'
[Appium]   defaultCapabilities: { udid: 'emulator-5554' }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: 'emulator-5554'
```

**Comment by vikramvi** [comment]
@TikhomirovSergey Thanks a ton for detailed clarifications. 

I have put UDID into json file and got it working.

**Comment by vikramvi** [comment]
@TikhomirovSergey I was wrong in earlier comment, please ignore.

In order to run test cases in parallel mode with Appium & Grid setup in case of Android devices; passing UDID is must.

Thanks for your solution in your comment, it helped me to unblock.

Best Regards,
Vikram
