### ISSUE TITLE
Gradle build issue

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#550]
## Description

There is a problem with the gradle building/publishing. Take a look at [this file](https://github.com/TikhomirovSergey/java-client/blob/master/gradle.properties). It requires hardcoded parameters. This information is sensitive. And it could be commited eventually.

## Environment

Doesn't matter. It needs for gradle v > 2.14

## Details

Could we add something like this
```
tasks.withType(signing) {
   //trying to extract credentials and other secret information from the gradle.properties
   //if there is no data
  //  it tries to get it from System.properties 
}
```

That way we could configure CI.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey We can configure it as environment variables in TravisCI. What do you say?
