### ISSUE TITLE
action.longPress(element).moveTo(y_coordinate, height).release().perform() not working

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#563]
## Description

I'm trying to achieve pull down refresh.
For this I need to press and hold a element, pull to a nominal distance and release.

The action is failing with exception.

## Environment

* java client build version or git revision if you use some shapshot: 4.0.0
* Appium server version or git revision if you use some shapshot: 1.6.3
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

WebElement element = iOSDriver().findElement(By.xpath("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]//XCUIElementTypeTable[1]/XCUIElementTypeOther[1]"));
	Integer x_coordinate = element.getLocation().x;
	Integer y_coordinate = element.getLocation().y;
	Integer height = element.getSize().height;
	Integer width  = element.getSize().width;
	
	int bottomY = y_coordinate + height;
	int centerX  = x_coordinate + width/2;
		
	//iOSDriver().swipe(centerX, bottomY, centerX,y_coordinate , 2000 );
	
	TouchAction action = new TouchAction(iOSDriver());
	action.longPress(element).moveTo(y_coordinate, height).release().perform();

## Ecxeption stacktraces

https://gist.github.com/vikramvi/c4a8152f83567ee43f640285c849048f

## Link to Appium logs

NA

**Comment by SrinivasanTarget** [comment]
@vikramvi What was the client version?

**Comment by vikramvi** [comment]
@SrinivasanTarget sorry missed to mention, updated the bug description 

4.0.0

**Comment by SrinivasanTarget** [comment]
@vikramvi We aren't supporting version lesser than 5.0 Beta for Server 1.6.3. Follow our wiki and upgrade the client version and raise a new issue if you hit any issues.

**Comment by vikramvi** [comment]
Thanks @SrinivasanTarget for clarification
