### ISSUE TITLE
Android driver can't be initialized successfully when i added capability "AutomationName.ANDROID_UIAUTOMATOR2"

### ISSUE THREAD

**Issue by tlllly** [appium/java-client#570]
## Description
I would like to test Toast message, so i updated appium to 1.6.3. And then i added "capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);" to the method which used to init Android Driver.
But the Android Driver can't be initialized successfully, it can be initialized successfully if i delete the capability.

## Environment

* java client build version or git revision if you use some shapshot:  jave-client-5.0.0-BETA2
* Appium server version or git revision if you use some shapshot: Appium 1.6.3
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v6.9.1
* Mobile platform/version under test: Android 6.0 Samsung Galaxy S7 edge
* Real device or emulator/simulator: Real device 

## Details
Appium start command: appium -a 127.0.0.1 -p 4723 --session-override
error message in appium:
C\:\\Users\\tangleilei\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\.0.2.9\@appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-v0.1.1.apk' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:70:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

error message in Eclipse IDE:
二月 14, 2017 1:27:03 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
二月 14, 2017 1:27:14 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Falling back to original OSS JSON Wire Protocol.
二月 14, 2017 1:27:24 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Falling back to straight W3C remote end connection
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{appPackage=xxxxxxxxx.android, appActivity=xxxxxxxxxxxx.MainActivity, noReset=true, newCommandTimeout=500, automationName=UIAutomator2, browserName=, unicodeKeyboard=True, platformName=Android, version=6.0, deviceName=3e2c3500}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'

## Link to Appium logs
[appiumlogs.txt](https://github.com/appium/java-client/files/773237/appiumlogs.txt)

**Comment by tlllly** [comment]
I have solved this issue. The reason is "appium-uiautomator2-server-v0.1.1.apk" not exist.

**Comment by Cindy1235** [comment]
I have the same problem with you. Did you reinstalled the appium server or add the appium-uiautomator2-server-v0.1.1.apk? If I add the apk, where I can find it? Thank you!
