### ISSUE TITLE
The element which isn't in current page also be retured when i used Uiautomator2

### ISSUE THREAD

**Issue by tlllly** [appium/java-client#571]
## Description
1. In current page, there is only one element which text=="discuss"
2. I used "xpath: //android.widget.TextView[@text="discuss"]" to get the element. But i get two elements.
    [[[AndroidDriver:  on LINUX (0e36ff64-47a9-4580-b6e8-ea3ffbb8c993)] -> xpath: //android.widget.TextView[@text="discuss"]], [[AndroidDriver:  on LINUX (0e36ff64-47a9-4580-b6e8-ea3ffbb8c993)] -> xpath: //android.widget.TextView[@text="discuss"]]].
3. The other one is belongs to not visiable page.

if i dont used Uiautomator2, i get one taget element.

Could help to solve this issue?

Enviroment：
    java client build version or git revision if you use some shapshot: jave-client-5.0.0-BETA2
    Appium server version or git revision if you use some shapshot: Appium 1.6.3
    Desktop OS/version used to run Appium if necessary: Windows 10
    Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v6.9.1
    Mobile platform/version under test: Android 6.0 Samsung Galaxy S7 edge
    Real device or emulator/simulator: Real device

**Comment by saikrishna321** [comment]
@sravanmedarapu  ping

**Comment by sravanmedarapu** [comment]
@tlllly, Can you please share the page source(`getPageSource`) of the view ?
btw what do you mean by ````3. The other one is belongs to not visiable page.````, does it mean you have another element with same property when you scroll down or up ?

**Comment by tlllly** [comment]
Hi @sravanmedarapu , let me explain the issue, my app language is chinese, please let me know if you have any questions.
1. There are two views in app. 
![view2](https://cloud.githubusercontent.com/assets/10986129/23008743/bc6f24a4-f44c-11e6-93fb-fef934e57c0d.jpg)
![view1](https://cloud.githubusercontent.com/assets/10986129/23008744/bc95992c-f44c-11e6-8db8-c577a3ffcb07.jpg)
2. pageSource：
[View1_pageSource.txt](https://github.com/appium/java-client/files/779162/View1_pageSource.txt)
[View2_pageSource.txt](https://github.com/appium/java-client/files/779163/View2_pageSource.txt)

3.My target element is "xpath: //android.widget.TextView[@text="发现"]"
4.The target element in the pagesource that i have got are correct, there is one can be found on view1, and there are two elements can be found on view2.
4.But when i use findElements(By.xpath,"xpath: //android.widget.TextView[@text="发现"]) on View1, i can get two elements. I don't know why.
![elements](https://cloud.githubusercontent.com/assets/10986129/23009261/dcab5942-f44f-11e6-8356-2efa91058068.jpg)
5. You can download my test app from: https://www.douyu.com/client?platform=2, select Android app.

Thank you and looking forward to your reply

**Comment by TikhomirovSergey** [comment]
Ok. So this is the server side bug.

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver@v0.2.10 should fix this issue.

**Comment by saikrishna321** [comment]
closing its fixed in appium-uiautomator2-driver@v0.2.10
