### ISSUE TITLE
default implicit wait set for pageobject is not working

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#572]
## Description

I've set implicit wait for a page as below

```
protected WebDriver driver;

public AUTLandingPage(WebDriver driver) {
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver, 10, TimeUnit.SECONDS), this);
    }
```
I also checked with AppiumDriver but same issue

In this pageobject class, I check for availability of element with method isEnabled()

`particularElement.isEnabled()`

But instead of waiting for 10 sec, driver just continues execution after 0 sec

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA2
* Appium server version or git revision if you use some shapshot:  1.6.3
* Desktop OS/version used to run Appium if necessary: 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v7.2.1
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator

## Details

1. This happens when I login and goto next screen.
2. Then this issue happens https://github.com/appium/appium/issues/7034
3. After this I've observed appium doesn't wait for default implicit time mentioned in constructor

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

NA

## Link to Appium logs

NA

**Comment by vikramvi** [comment]
Please refer to sample code

https://github.com/awslabs/aws-device-farm-appium-tests-for-sample-app/blob/63a8b6f799d034fba39425b9a1f1fbe26eab6b91/src/test/java/Pages/BasePage.java

Tried initially with AppiumDriver and later with WebDriver but found issue in both cases.

**Comment by saikrishna321** [comment]
@vikramvi can you pls provide logs ?

**Comment by vikramvi** [comment]
@saikrishna321 please refer to https://gist.github.com/vikramvi/9814a6b6281634a64bb97f2d04ba6101

Here you are see that [debug] [BaseDriver] Set implicit wait is changing to 0 during execution

**Comment by saikrishna321** [comment]
@vikramvi i see this working as expected, please take a look at the updated logs from appium server version 1.6.4.beta and java-client 5.0.0Beta2

https://gist.github.com/saikrishna321/a1b9232c21d3aa903e5230b5f72113f0#file-detailed-logs-L813

There is nothing that we do on the client end and its completly from the selenium end.
 
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java#L81

>[debug] [BaseDriver] Set implicit wait is changing to 0 during execution

implicit wait is applied only for findElements
