### ISSUE TITLE
Inquiry: Sample iOS and Android apps to cover all the major scenarios

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#573]
## Description

@TikhomirovSergey  @SrinivasanTarget @saikrishna321

I was thinking to maintain test suite covering all the scenarios on Android and iOS clients as part of main code base itself.

This should be run before each release to make sure there is no regression.

I will be happy to contribute for this test suite.

Please let me know your views on this.

**Comment by saikrishna321** [comment]
@vikramvi we already have this and before every release the tests are triggered and once it goes green only we publish. But there are some edge cases which might have not been covered. More than happy to see contributions.

https://github.com/appium/java-client/tree/master/src/test

**Comment by vikramvi** [comment]
@saikrishna321 Thanks 👍  will check it out and start contributing
