### ISSUE TITLE
org.openqa.selenium.remote.ProtocolHandshake createSession

### ISSUE THREAD

**Issue by Cindy1235** [appium/java-client#576]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.

## Environment

* java client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by TikhomirovSergey** [comment]
@Cindy1235 Could you describe the issue?

**Comment by Cindy1235** [comment]
### Description
Recently I have this problem of my appium testing in all code.Here is a set of examples.
### code
`public class AppTest {
	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		AndroidDriver driver;
		DesiredCapabilities cap=new DesiredCapabilities();
		cap.setCapability("deviceName","192.168.130.101:5555");//设备名
		cap.setCapability("platformVersion", "7.0");//平台版本
		cap.setCapability("automationName", "Appium");//使用测试的引擎
		cap.setCapability("platformName", "Android");//平台名
		cap.setCapability("app", "D:\\Testing\\mukewang.apk");//app 绝对地址
		cap.setCapability("appPackage", "'cn.com.open.mooc");//app 的包名
		cap.setCapability("appActivity", "cn.com.open.mooc.index.splash.MCSplashActivity");
		cap.setCapability("devicereadyTimeout", 30);
		cap.setCapability("unicodeKeyboard", true);
		cap.setCapability("resetKeyboard", true);
		driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		Thread.sleep(5000);
		driver.quit();
	}
}
`
### Eclipse console
`org.openqa.selenium.remote.ProtocolHandshake createSession
 Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Command failed: D:\Testing\Android\android-sdk_r23.0.2-windows\android-sdk-windows\platform-tools\adb.exe -s 192.168.130.101:5555 shell "pm install -r /data/local/tmp/b4dbaa27bad4718d724a211aab254363.apk"
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
) (WARNING: The server did not provide any stacktrace information)
`
### Appium log
`info: Client User-Agent string: Apache-HttpClient/4.5.2 (Java/1.8.0_111)
info: [debug] The following desired capabilities were provided, but not recogni
ed by appium. They will be passed on to any other services running on this serv
r. : devicereadyTimeout`
`error: Failed to start an Appium session, err was: Error: Command failed:`
### Environment
    jdk:1.8.0_111"
    Appium server version :1.4.16
    Windows verision: win7+64bit
    Node.js version :v6.9.5

**Comment by TikhomirovSergey** [comment]
@Cindy1235 Have you tried server 1.6.x?

**Comment by Cindy1235** [comment]
Did you say the appium server version? Its latest version is AppiumForWindows_1_4_16_1，my version is 1.4.16. Thank your help！

**Comment by SrinivasanTarget** [comment]
@Cindy1235 sorry for the late response. Please install latest version of appium using ```npm install -g appium@beta``` will install latest version which is 1.6.6 beta now. Please do raise issue if you hit the same again.
