### ISSUE TITLE
Partial swipe left is not working

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#580]
## Description

1. I've an element in form of row ( XCUIElementTypeTable[1]/XCUIElementTypeCell[1] ) on which I need to swipe partial left
2. This will unhide button on right side of the row ( XCUIElementTypeTable[1]/XCUIElementTypeCell[1]/XCUIElementTypeButton[1] )
3. I have tried all options possible but couldn't get this working
4. It always results in normal swipe and next screen gets loaded

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA3
* Appium server version or git revision if you use some shapshot:  1.6.4. beta
* Desktop OS/version used to run Appium if necessary:  Mac 10.11.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v7.2.1
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: iOS Simulator

## Details

have provided in description

## Code To Reproduce Issue [ Good To Have ]

I tried below ways to achieve swipe left in partially

`TouchAction action1 = new TouchAction(driver).press(250 , 147).waitAction(-200).moveTo(147, 200).release();
        	        action1.perform(); 
        	    
                	/*WebElement rowToSlide = AppiumController.instance.driver.findElement(By.xpath("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]//XCUIElementTypeTable[1]/XCUIElementTypeCell[1]"));
                	               
                	TouchAction swipe = new TouchAction(driver).press(rowToSlide, 250 , 147)
   	                     .waitAction(-200).moveTo(rowToSlide, 200, 147).release();
          
                         swipe.perform();*/
          
        	    
                	/*Dimension size = rowToSlide.getSize();
                	
                	TouchAction swipe = new TouchAction(driver).press(rowToSlide, size.width / 2 + 100 , size.height / 2).waitAction(2000)
                	            .moveTo(rowToSlide, 100, size.height / 2).release().perform();
                	        //swipe.perform();
*/                	        
                      // Point location =  rowToSlide.getLocation();
                       //Point center    =  ((MobileElement) rowToSlide).getCenter();
                       
                       
                       
                	/*WebElement element = AppiumController.instance.driver.findElement(By.xpath("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]//XCUIElementTypeTable[1]/XCUIElementTypeCell[1]"));
                	Integer x_coordinate = element.getLocation().x;
                	Integer y_coordinate = element.getLocation().y;
                	Integer height = element.getSize().height;
                	Integer width  = element.getSize().width;
                	
                	TouchAction action = new TouchAction(driver);
                	action.press(element).waitAction(1000).moveTo(250, 0).release().perform();`

https://gist.github.com/vikramvi/220ba19708a8f1ec0bbc8d906072f209

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by SrinivasanTarget** [comment]
@vikramvi Why is ```waitAction``` negative?

**Comment by SrinivasanTarget** [comment]
@vikramvi How do you got the values as 250 etc etc hotcoded there?

**Comment by vikramvi** [comment]
@SrinivasanTarget I tried by giving positive value, removing it altogether and later negative. This was one of the options suggested on appium forum. 

But none of them working in this case

**Comment by SrinivasanTarget** [comment]
AFIK @vikramvi waitAction should be always positive.

**Comment by vikramvi** [comment]
> @vikramvi How do you got the values as 250 etc etc hotcoded there?

First I calculated size of the row which is {0,120} {0,174} { 320,120} {320,174}. To get it work at least, I tried hard coding the values.

**Comment by vikramvi** [comment]
> AFIK @vikramvi waitAction should be always positive.

I tried but didn't work in that case as well

**Comment by vikramvi** [comment]
One more solution mentioned https://discuss.appium.io/t/partial-swipe-left-on-ios-simulator-10-x-not-working/14948/2 , didn't work as well

**Comment by SrinivasanTarget** [comment]
>I tried but didn't work in that case as well

I believe it should be the issue with the co.ord's given.

**Comment by vikramvi** [comment]
@SrinivasanTarget can you please suggest what co-ordinates should I try, I spent 2 days and come to conclusion that this could be a bug.

Please refer to attached 2 screen shots for confirmation about correct co-ordinates. 

![screen shot 2017-02-22 at 12 13 15 pm](https://cloud.githubusercontent.com/assets/308490/23209169/5dca5684-f8f8-11e6-95f4-985e227a1a6a.png)
![screen shot 2017-02-22 at 12 13 24 pm](https://cloud.githubusercontent.com/assets/308490/23209168/5dc5a83c-f8f8-11e6-9c4e-903386f175ed.png)

**Comment by SrinivasanTarget** [comment]
@vikramvi I don't suggest getting Co.ords using Appium/any Inspector. Something that we need to calculate through the dimensions of element. Should be something like this, https://github.com/saikrishna321/VodQaAdvancedAppium/blob/master/src/test/java/com/appium/gesture/GestureTest.java#L25.

**Comment by vikramvi** [comment]
yes I tried it already, just used appium client to cross check co-ordinates. Earlier posted co-ordinates have got from code and not appium client.

**Comment by saikrishna321** [comment]
@vikramvi can you post this on appium.discuss forum with your sample app. That would help to reproduce.

@triager please close 😉

**Comment by vikramvi** [comment]
@saikrishna321 @SrinivasanTarget @TikhomirovSergey  I still feel this is a valid bug. I played with the app for 30 mins.

The behaviour is similar to Mail app in iOS.

I think chaining of events are happening properly in this case.
Instead of waiting for next chain event Press -> MoveTo -> Release -> Perform

It's doing Press which is resulting in next screen to open; similar to Mail app.

Let me search for some open source project with similar behaviour to reproduce issue

**Comment by RockChild** [comment]
Are you sure that you need to swipe? I mean what is the purpose for swipe?

**Comment by TikhomirovSergey** [comment]
@vikramvi It is not the client bug.

**Comment by vikramvi** [comment]
@RockChild  yes, I need to do swipe to get button enabled on right side of row; similar to Mail app email row.

@TikhomirovSergey shall I close this and open new issue in appium repo ?

**Comment by TikhomirovSergey** [comment]
Please open a new issue here
https://github.com/appium/appium/issues. This issue is related to this repo: https://github.com/appium/appium-xcuitest-driver.

The new one issue please link to this one. User should know where is the problem :)

**Comment by vikramvi** [comment]
@TikhomirovSergey thanks for confirming it's bug on server side. I've opened new issue https://github.com/appium/appium/issues/7914

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey I think this one can be closed as java-driver unrelated issue

**Comment by vikramvi** [comment]
@triager  please close
