### ISSUE TITLE
Swipe, tap, TouchAction don't work on double-panel iOS application

### ISSUE THREAD

**Issue by RockChild** [appium/java-client#581]
## Description
AppiumDriver.swipe() and swipe through TouchAction method is not working properly on the application with 2-panels app(divided vertically) like this:
<img width="601" alt="screen shot 2017-02-22 at 17 52 52" src="https://cloud.githubusercontent.com/assets/7795004/23222574/a3fb9bf6-f928-11e6-9800-c75770ccc990.png">

## Environment

* java client build version: 5.0.0-BETA1/3, 4.1.2
* Appium server version or git revision if you use some snapshot: 1.6.3, 1.6.4-beta
* Desktop OS/version used to run Appium if necessary: Mac OS X(10.12.3)
* Node.js version: v6.9.5
* Mobile platform/version under test:iOS 10.2.1
* Real device or emulator/simulator: simulator/real iPad Mini 2

## Details

The problem appears when trying to swipe() using both x/y axes or existing element on the 2-panel application(looks like iOS Settings screen on iPad Mini), although it works on another screen(login page in my case), which is 1-panel. 
Appium server is getting stuck for like 5 minutes when running these methods. The issue is resolving if:
1.  you make swipe manually before or during waiting of method execution
2. before method execution, click on some link and then navigate back without page reloading (doesn't work when clicking on 'inactive' element:  I tried to make a click on 'XCUIElementTypeStaticText' element, which is not opening anything, just static text without link action and it didn't help)

The same issue is happening while trying to tap on an element, which is displayed below on the screen, but not visible: 
-          new TouchAction(driver).press(firstService).waitAction(350).release().perform();
As the element is not displayed on the visible area of the page, driver indirectly is trying to swipe page until element would be in the area. But again, if to click on visible element(element.click();) what will open another pane, navigate back, press on 'hidden' element is performing without any issue(actually, it's current workaround in my framework)

## Code To Reproduce Issue [ Good To Have ]

-         new TouchAction(driver).press(400, 200).moveTo(0, -200).release().perform();
-     //element - existing element, which is enabled and displayed on the page 
       new TouchAction(driver).press(element).moveTo(0, -200).release().perform();
-         driver.swipe(400, 200, 0, -200, 350);
-          new TouchAction(driver).press(firstService).waitAction(350).release().perform();
-     JavascriptExecutor js = driver;
      HashMap<String, String> scrollObject = new HashMap<String, String>();
      scrollObject.put("direction", "down");
      scrollObject.put("element", element.getId());
      js.executeScript("mobile: swipe", scrollObject);

Every option was successfully performed on 1-panel screen.

## Exception stacktraces

No Exceptions at all, it just continue working after 5+ minutes delay

## Link to Appium logs

[In logs](https://gist.github.com/RockChild/f3c280da9bab06e9a7ed12485904d109), there is a successful response(200) after 6 minutes, but actually, it is not swiped

**Comment by wenshi11019** [comment]
I have the same question,too

**Comment by vikramvi** [comment]
@RockChild @wenshi11019 this is appium server side issue, please open ticket there

**Comment by MaheshReddyAkuleti** [comment]
Even I am facing the same issue..

**Comment by TikhomirovSergey** [comment]
We don't support the swipe method anymore, so this issue is closed.
