### ISSUE TITLE
iOS: Feature Request: Add support to tap home key

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#587]
## Description

webdriveragent supports convenient way go to home screen with
```
curl -X POST $JSON_HEADER -d "" $DEVICE_URL/wda/homescreen
```

it will be nice to support it.

**Comment by SrinivasanTarget** [comment]
@amedvedjev I don't see a server endpoint here: https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js So please raise it under server.
