### ISSUE TITLE
ESOCKETTIMEDOUT Error

### ISSUE THREAD

**Issue by rajanbharti** [appium/java-client#600]
## Description

After 30-40 requests of driver.getPageSource(). I get **ESOCKETTIMEDOUT** error in console and testing stops after that point
Tried both Appium version 4.1.2 and 5.0.0- Beta 5

## Environment

* Appium: java client 4.1.2
* Mac OS X
* Mobile platform/version under test: 10.1.1
* Real device or emulator/simulator: iPhone 5S

### Error

```
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 240.06 seconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'Apples-Mac-mini.local', ip: '192.168.2.157', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
```

**Comment by SrinivasanTarget** [comment]
Please use 5.0.0- Beta 4 for time being. Beta 5 is broken and we have fix in place [here](https://github.com/appium/java-client/pull/597). Same will be released soon.

**Comment by rajanbharti** [comment]
https://github.com/facebook/WebDriverAgent/issues/507
So, is this resolved at aapium end? because, i am getting same problem, even after using beta 4

**Comment by SrinivasanTarget** [comment]
@rajanbharti Which version of appium server are you trying out?

**Comment by rajanbharti** [comment]
@SrinivasanTarget , I am using 1.6.3 version of appium server

**Comment by SrinivasanTarget** [comment]
@rajanbharti Can you try latest server version, ```npm install -g appium@beta --no-shrinkwrap```

**Comment by rajanbharti** [comment]
@SrinivasanTarget , It is working now, Thanks

**Comment by SrinivasanTarget** [comment]
cool @rajanbharti
