### ISSUE TITLE
Bad parameters

### ISSUE THREAD

**Issue by MordaBoy** [appium/java-client#602]
## Description
2 days ago it worked perfectly. I changed nothing. But now In Appium 1.6.4-beta, getting the error: 
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]

In Intellij, getting the error : 
Caused by: 18:21:01.079 [DEBUG] [TestEventLogger]         org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{browserName=Browser, platformName=Android, deviceName=192.168.56.101:5555, version=4.4.4}], required capabilities = Capabilities [{}]
18:21:01.079 [DEBUG] [TestEventLogger]  

## Environment

Appium v1.6.4-beta
java version "1.8.0_111" (build 1.8.0_111-b14)
node v7.0.0
Mac 10.12
Emulator Samsung Galaxy S5 Android 4.4.4 - API 19
Intellij idea

## Code To Reproduce Issue [ Good To Have ]

 'galaxy-s5-4.4.4' {
        driver = {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "192.168.56.101:5555");
            capabilities.setCapability(MobileCapabilityType.PLATFORM, "ANDROID");
            capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Browser");
            capabilities.setCapability(MobileCapabilityType.APP, (String) null);
            capabilities.setCapability(MobileCapabilityType.VERSION, "4.4.4");
            URL url= new URL("http://localhost:4723/wd/hub/");
            WebDriver driver =  new AndroidDriver<>(url, capabilities);
        }
    }

**Comment by SrinivasanTarget** [comment]
We are aware of it and it is been tracked [here](https://github.com/appium/java-client/issues/594). Please use 5.0.0-Beta 4 instead. Fix is in [here](https://github.com/appium/java-client/pull/597).
