### ISSUE TITLE
org.openqa.selenium.remote.ProtocolHandshake createSession messages logging as errors

### ISSUE THREAD

**Issue by Brian-Watson** [appium/java-client#603]
## Description

After just recently upgrading to java-client 5.0.0-BETA4, my Appium jenkins jobs are now ending as failure even though all tests pass.

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA4
* Appium server version or git revision if you use some shapshot: 1.6.4-beta
* Desktop OS/version used to run Appium if necessary: Windows and OSX
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS and Android
* Real device or emulator/simulator: emu and sim

## Details

Each time I create a new IOSDriver or AndroidDriver, I see the following in my jenkins job console output...

`com.company.dtr.brokeragent.TransactionRoomsDetailsTestSuite_BA > addTransactionContactDetailsFromNetwork STANDARD_ERROR
    Mar 15, 2017 5:13:23 PM org.openqa.selenium.remote.ProtocolHandshake createSession
    INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
    Mar 15, 2017 5:13:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
    INFO: Detected dialect: OSS
`
My jenkins job will then end as FAILURE even though all my tests pass.  I then noticed that these new output messages seem to be going to STANDARD_ERROR for some reason.  When using the older java-client v4.1.2, I never had this problem.

**Comment by saikrishna321** [comment]
@Brian-Watson there is conflict in dependencies . Can you pls share the logs n pom.xml as gist

**Comment by Brian-Watson** [comment]
@saikrishna321 Sure.  I am currently using gradle for my dependencies, so my gradle file just includes...
`repositories {
    jcenter()
}

dependencies {
    compile 'junit:junit:4.12'
    compile 'io.appium:java-client:5.0.0-BETA4'
    compile 'log4j:log4j:1.2.17'
    compile 'joda-time:joda-time:2.3'
    compile 'com.saucelabs:sauce_junit:2.1.21'
    compile 'com.saucelabs:saucerest:1.0.35'
    compile 'io.rest-assured:rest-assured:3.0.0'
    compile 'com.relevantcodes:extentreports:2.41.2'
    compile 'com.google.guava:guava:21.0'

    compile 'com.fasterxml.jackson.core:jackson-core:2.8.1'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.8.1'
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-joda:2.8.1'

    testCompile group: 'junit', name: 'junit', version: '4.12'
}
`
Which logs would you be interested in?

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/issues/588

**Comment by saikrishna321** [comment]
@Brian-Watson can you try with 
```
<dependency>
		<groupId>io.appium</groupId>
		<artifactId>java-client</artifactId>
		<version>5.0.0-BETA5</version>
	</dependency>

```

**Comment by TikhomirovSergey** [comment]
@Brian-Watson 
I think it is related to #594. The fix is here #597. It is waiting for the aproval

**Comment by TikhomirovSergey** [comment]
@Brian-Watson I am closing this issue. 5.0.0-BETA6 was published. Please try it. If not everything is ok then please re-open this issue.

**Comment by Brian-Watson** [comment]
@saikrishna321 @TikhomirovSergey Just wanted to update you guys to say I installed the latest BETA6 and it indeed fixed my issue.  Thank you guys so much for your work!!!!
