### ISSUE TITLE
In Appium 1.6.3, getting the error 'Bad parameters

### ISSUE THREAD

**Issue by SwiftPlayer** [appium/java-client#604]
## Description

In Appium 1.6.3, getting the error 'Bad parameters: BadParametersError: Parameters were incorrect.

## Environment

*Appium version 1.6.3
*Mac 10.12.2
*Real device iphone 6s plus
*Intellij idea
*java-client-4.1.2.jar
*selenium-server-standalone-3.3.1

## Details

In Appium 1.6.3, getting the error 'Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id"]} and you sent ["capabilities"]'

In Intellij, getting the error 'Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=/Users/admin/Desktop/IntegrationApp.app, appiumVersion=1.6.3, platformVersion=10.2, platformName=iOS, udid=86997a848f41407ce0419720a3e630458bd4473d, deviceName=Stephania's iPhone, launchTimeout=500000}], required capabilities = Capabilities [{}],

## Code To Reproduce Issue [ Good To Have ]

```
public class First_Appium_Run {
   private static IOSDriver<MobileElement> wd;

   public static void main(String[] args) throws MalformedURLException, InterruptedException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.3");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Stephania's iPhone");
        capabilities.setCapability(MobileCapabilityType.UDID, "86997a848f41407ce0419720a3e630458bd4473d");
        capabilities.setCapability(MobileCapabilityType.APP, "/Users/admin/Desktop/IntegrationApp.app");
        //capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "IOS_XCUI_TEST");
        //capabilities.setCapability("bundleId", "com.MysamPhone.Integration");
        //driver = new IOSDriver(new URL(""), capabilities);
        capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
        wd = new IOSDriver (new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
        wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
        wd.findElement(By.name("Alerts"));
    }
}

```

**Comment by SrinivasanTarget** [comment]
If you wanted to run in real device specify UDID and ipa (not app). app is only for simulators.
