### ISSUE TITLE
I am facing issue while I try to run my code on real iOS device using Appium. I am getting below error message while I run my script.    [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]

### ISSUE THREAD

**Issue by ravi31186** [appium/java-client#608]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium Java client so please describe necessity of this feature and the way that it should work.

## Environment

* java client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by SrinivasanTarget** [comment]
@ravi31186 Please fill the template properly along with logs inform of gist to investigate the issues. Use the latest beta version of java client and server, you will not face this issue.

**Comment by ravi31186** [comment]
Hello Sri,

Thanks for your response really appreciated. 

I have used the  java-client-5.0.0-BETA5.jar
Selenium-server-standalone-3.2.1.jar

Dependencies but still I am getting same error... would you please specify which latest beta version of java client and server I can use to resolve this issue?

Below is the log info....


ravindras-MacBook-Air:~ ravindrapatil$ appium -U 1965fe18a1cb5c71085ca83a90a159a8c990a03c --app com.facebook.IntegrationApp
[Appium] Welcome to Appium v1.6.3
[Appium] Non-default server args:
[Appium]   app: 'com.facebook.IntegrationApp'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium] Deprecated server args:
[Appium]   --app => --default-capabilities '{"app":"com.facebook.IntegrationApp"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: 'com.facebook.IntegrationApp'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/WebDriverAgentRunner-Runner.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/WebDriverAgentRunner-Runner.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"requiredCapabilities":{}},"alwaysMatch":{"app":"/Users/ravindrapatil/Desktop/WebDriverAgentRunner-Runner.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"firstMatch":[]}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]
[HTTP] <-- POST /wd/hub/session 400 11 ms - 243 
^C[Appium] Received SIGINT - shutting down
ravindras-MacBook-Air:~ ravindrapatil$ 
ravindras-MacBook-Air:~ ravindrapatil$ appium -U 1965fe18a1cb5c71085ca83a90a159a8c990a03c --app com.facebook.IntegrationApp
[Appium] Welcome to Appium v1.6.3
[Appium] Non-default server args:
[Appium]   app: 'com.facebook.IntegrationApp'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium] Deprecated server args:
[Appium]   --app => --default-capabilities '{"app":"com.facebook.IntegrationApp"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: 'com.facebook.IntegrationApp'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/WebDriverAgentRunner-Runner.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/WebDriverAgentRunner-Runner.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"requiredCapabilities":{}},"alwaysMatch":{"app":"/Users/ravindrapatil/Desktop/WebDriverAgentRunner-Runner.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"firstMatch":[]}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]
[HTTP] <-- POST /wd/hub/session 400 5 ms - 243

**Comment by SrinivasanTarget** [comment]
Hi @ravi31186 

Beta 5 had this issue we have recently resolved it.so please use 5.0.0-BETA6.

**Comment by ravi31186** [comment]
Hello Sri,

Thanks for you response your suggestion solved my problem but I am having another issue I am not able to launch WebDriverAgent app on my device.

Please see below log for more details....

ravindras-MacBook-Air:~ ravindrapatil$ appium -U 1965fe18a1cb5c71085ca83a90a159a8c990a03c --app com.facebook.IntegrationApp
[Appium] Welcome to Appium v1.6.3
[Appium] Non-default server args:
[Appium]   app: 'com.facebook.IntegrationApp'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium] Deprecated server args:
[Appium]   --app => --default-capabilities '{"app":"com.facebook.IntegrationApp"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: 'com.facebook.IntegrationApp'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},{},[{"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"}},{"requiredCapabilities":{}}],null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/ravindrapatil/Desktop/IntegrationApp.app'
[Appium]   appiumVersion: '1.6.3'
[Appium]   platformVersion: '10.2.1'
[Appium]   bundleId: 'com.facebook.IntegrationApp'
[Appium]   platformName: 'iOS'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium]   deviceName: 'ravi'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.
[BaseDriver] Session created with session id: db354f22-6a66-4b76-a667-b26f61404c9e
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: 1965fe18a1cb5c71085ca83a90a159a8c990a03c
[debug] [XCUITest] Creating iDevice object with udid 1965fe18a1cb5c71085ca83a90a159a8c990a03c
[XCUITest] Determining device to run tests on: udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c', real device: true
[BaseDriver] Using local app '/Users/ravindrapatil/Desktop/IntegrationApp.app'
[debug] [XCUITest] Checking whether app '/Users/ravindrapatil/Desktop/IntegrationApp.app' is actually present
[debug] [XCUITest] App is present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1965fe18a1cb5c71085ca83a90a159a8c990a03c -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 1965fe18a1cb5c71085ca83a90a159a8c990a03c' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 1965fe18a1cb5c71085ca83a90a159a8c990a03c' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 1009 ms - 262 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"},{},null,null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/ravindrapatil/Desktop/IntegrationApp.app'
[Appium]   appiumVersion: '1.6.3'
[Appium]   platformVersion: '10.2.1'
[Appium]   bundleId: 'com.facebook.IntegrationApp'
[Appium]   platformName: 'iOS'
[Appium]   udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c'
[Appium]   deviceName: 'ravi'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.
[BaseDriver] Session created with session id: a96f70fc-76ed-4018-ad2d-70b22e84b09f
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: 1965fe18a1cb5c71085ca83a90a159a8c990a03c
[debug] [XCUITest] Creating iDevice object with udid 1965fe18a1cb5c71085ca83a90a159a8c990a03c
[XCUITest] Determining device to run tests on: udid: '1965fe18a1cb5c71085ca83a90a159a8c990a03c', real device: true
[BaseDriver] Using local app '/Users/ravindrapatil/Desktop/IntegrationApp.app'
[debug] [XCUITest] Checking whether app '/Users/ravindrapatil/Desktop/IntegrationApp.app' is actually present
[debug] [XCUITest] App is present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1965fe18a1cb5c71085ca83a90a159a8c990a03c -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 1965fe18a1cb5c71085ca83a90a159a8c990a03c' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 1965fe18a1cb5c71085ca83a90a159a8c990a03c' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 578 ms - 262 
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/ravindrapatil/Desktop/IntegrationApp.app","appiumVersion":"1.6.3","platformVersion":"10.2.1","bundleId":"com.facebook.IntegrationApp","platformName":"iOS","udid":"1965fe18a1cb5c71085ca83a90a159a8c990a03c","deviceName":"ravi"}},{"requiredCapabilities":{}}]}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id","sessionId","id","sessionId","id"]} and you sent ["capabilities"]
[HTTP] <-- POST /wd/hub/session 400 1 ms - 205
