### ISSUE TITLE
Driver gets exit on other threads while changing the connection settings

### ISSUE THREAD

**Issue by neetesh000** [appium/java-client#609]
## Description

If the Appium script; that is running on multiple devices in parallel mode; encounters driver.setConnection(Connection.<<connectionType>>) instruction on one thread, the drivers on other threads gets stopped.

## Environment

* java client build version: 4.1.2
* Appium server version: 1.6.3
* Node.js version: v7.2.1
* Mobile platform/version under test: Nexus 5 (Android v: 6.0.1), LETV LeEco Le 2 (6.0.1)
* Real device or emulator/simulator: Real Devices/ Emulator

## Details

If a Appium unit test/ script contains driver.setConnection(Connection.<<connectionType>>) instruction which is being executed in parallel on multiple devices with Appium-Grid configuration then when the script encounters the 'setConnection()' method on one thread the driver on other threads gets stopped while on the first thread it continue to run properly.

I tested the script on 3 devices, so when the script encounters the 'setConnection()' method on one device the drivers corresponding to other 2 devices gets stopped and the tests/ script gets failed on other devices.

The error starts with following logs on the thread which is being interrupted. 

[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session b7c5ec65-23ac-4b8a-911b-31ab4bbeb6cd from our master session list

##Project Link
 
Following is the sample project in which the issue occurs.
https://github.com/neetesh000/Appium_Grid

## Ecxeption stacktraces

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: UiAUtomator shut down unexpectedly (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 155 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'apples-MacBook-Air.local', ip: '192.168.0.11', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_112'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=/Users/apple/Documents/workspace/Appium-Grid-For-Android-master/src/example/AndroidCalculator.apk, appPackage=com.android2.calculator3, networkConnectionEnabled=true, warnings={}, appWaitPackage=com.android2.calculator3, appWaitActivity=com.android2.calculator3.Calculator, databaseEnabled=false, version=6.0.1, deviceName=1fc4a4fa, platform=ANDROID, deviceUDID=1fc4a4fa, appActivity=com.android2.calculator3.Calculator, desired={app=/Users/apple/Documents/workspace/Appium-Grid-For-Android-master/src/example/AndroidCalculator.apk, browserName=android, platformName=Android, udid=1fc4a4fa, version=6.0.1, deviceName=Letv LeX526, platform=ANDROID}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=android, javascriptEnabled=true, platformName=Android, udid=1fc4a4fa}]
Session ID: b7c5ec65-23ac-4b8a-911b-31ab4bbeb6cd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:33)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at example.CalcExample.performOperations(CalcExample.java:27)
	at example.CalcExample.run(CalcExample.java:46)
	at java.lang.Thread.run(Thread.java:745)
`

## Link to Appium logs 

Uninterrupted Driver Logs: 
https://gist.github.com/neetesh000/10b467fc3cc8d12af20968f0afa718c6

Interrupted Driver Logs: 
https://gist.github.com/neetesh000/a3d61601372f12f5dde800ef77b5a9fe

**Comment by hareeshnkp** [comment]
Getting the error when tying to do parallel execution.

[info] [HTTP] <-- POST /wd/hub/session/a6c52050-119d-4b0b-bdb7-5a1bf89ebb32/appium/device/hide_keyboard 500 584 ms - 218 
[error] [UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[warn] [Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[info] [Appium] Removing session a6c52050-119d-4b0b-bdb7-5a1bf89ebb32 from our master session list

**Comment by saikrishna321** [comment]
closing as inactive.
