### ISSUE TITLE
 ./gradlew build and too many test are failed

### ISSUE THREAD

**Issue by yuzhidi** [appium/java-client#615]
I'm a new one to java-client.
I clone repo and ./gradlew build

for compile pass I delete
- artifacts {
-    archives javadocJar, sourcesJar
-}
-
-signing {
-    sign configurations.archives
-}

-uploadArchives {
.....
-}

141 tests completed, 77 failed
:test FAILED

too many test are fail.
No build guide in this repo. Can any one give me some advice? Thanks.

**Comment by TikhomirovSergey** [comment]
#325
#269
