### ISSUE TITLE
Android Chrome browser @AndroidFindBy(xpath="//a[contains(text(),'Continue using')]") not working

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#616]
![screen shot 2017-04-06 at 2 42 26 pm](https://cloud.githubusercontent.com/assets/308490/24756069/c20416de-1adc-11e7-8b8a-6b2faa032d26.png)
## Description

I've below locator

```
    @AndroidFindBy(xpath="//a[contains(text(),'Continue using')]")
    private WebElement gotoMobileWebsiteLink;
```

but from appium log, I could see finding by xpath call is not being made but instead

```
[HTTP] --> POST /wd/hub/session/3648600a-1ed2-4a41-9af7-f66fd58d5114/element {"using":"id","value":"gotoMobileWebsiteLink"}

[HTTP] --> POST /wd/hub/session/3648600a-1ed2-4a41-9af7-f66fd58d5114/element {"using":"name","value":"gotoMobileWebsiteLink"}
```

## Environment

* java client build version or git revision if you use some shapshot:  5.0.0-BETA6
* Appium server version or git revision if you use some shapshot:  1.6.4-beta
* Desktop OS/version used to run Appium if necessary: Mac  10.11.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:  v7.6.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real Device 

## Details

1. Android device's Chrome browser needs to open a website and do some action
2. I'm trying to click on a link on outlook default home page, but finding with xpath is not working

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

NA

## Link to Appium logs
https://gist.github.com/vikramvi/4ab168d0fab0fecc08033cd0df351e3d

**Comment by mykola-mokhnach** [comment]
Change xpath to 

```
//a[contains(.,'Continue using')]
```

**Comment by vikramvi** [comment]
@mykola-mokhnach  this xpath does work with `arc`.
 I could find the element and click on it. 

Only with java client it's not working. If you see appium logs, there is no xpath usage at all. 
I'm not sure why `name` and `id` are used and no `xpath`

**Comment by mykola-mokhnach** [comment]
this is expected if the current context is a webview or you want to say that the locator for webview is also applied to native context?

**Comment by vikramvi** [comment]
My bad for Browser automation, I should use @FindBy and not @AndroidFindBy 

Found my mistake through https://github.com/appium/java-client/issues/52#issuecomment-49777944 and https://github.com/appium/java-client/blob/master/docs/Page-objects.md

@triager  please close
