### ISSUE TITLE
@WithTimeout wait for WebElement seems to be broken in with current version

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#617]
## Description

I've generic method for explicit wait as below

```
    @WithTimeout(time = 5, unit = TimeUnit.SECONDS)
    @FindBy(xpath="//input[@name='passwd']")
    private WebElement OLPassword;

public boolean isElementPresent(WebElement elementName, int timeout){
	try{
	        WebDriverWait wait = new WebDriverWait(getDriver(), timeout);
	        wait.until(ExpectedConditions.visibilityOf(elementName));
	        return true;
	}catch(Exception e){
	    return false;
	}
    }

  public OutlookPage(AppiumDriver driver){
	this.driver = driver;
	PageFactory.initElements(new AppiumFieldDecorator(driver, 1, TimeUnit.SECONDS), this);
    }

```

- If you refer to attached appium log, when outlook login screen changes pages, explicit wait is not working. 
- I've tried setting WithTimeout for this element but it doesn't wait for 5 sec either.
- It's always waiting for 1 sec only, which is implicit wait and ignores both explicit wait and WithTimeout

@TikhomirovSergey can you please check 

## Environment

- java client build version or git revision if you use some shapshot: 5.0.0-BETA6
- Appium server version or git revision if you use some shapshot: 1.6.4-beta
- Desktop OS/version used to run Appium if necessary: Mac 10.11.6
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v7.6.0
- Mobile platform/version under test: Android 6.0.1
- Real device or emulator/simulator: Real Device

## Details

Expected wait time is 10 sec but script waits less than 1 sec

## Code To Reproduce Issue [ Good To Have ]

```
 public boolean outlookLogin(String email, String password){
	if(isElementPresent(OLEmail,5)){
	    OLEmail.sendKeys(email);
	    NextButton.click();
	       if(isElementPresent(OLPassword,10)){  	 // FAILS HERE, DOESN'T WAIT FOR 10 SEC       
	            OLPassword.sendKeys(password);
	            OLSignButton.click();
	            return true;
	       }else{
		   return false;
	       }
	}else{
	    return false;
	}	
    }
```

- I think explicit and implicit wait is Selenium issue but per my understanding @WithTimeout against each of the WebElement should be used as final value to wait for that element

## Ecxeption stacktraces

NA

## Link to Appium logs

https://gist.github.com/vikramvi/7ce1f09d5f8edf458760be400b26a77d#file-gistfile1-txt-L296

**Comment by SrinivasanTarget** [comment]
@vikramvi I believe this is fixed in recent fixes made by Thikomo [here](https://github.com/appium/java-client/pull/863/files)

**Comment by narendra-chandratre** [comment]
Any working solution?
