### ISSUE TITLE
Can I change capability dynamically?

### ISSUE THREAD

**Issue by crazyk2** [appium/java-client#621]
I want to test toast message in my native app.
There is an info  In release notes.

> 1.6.3
>  Android - Uiautomator2
> Add ability to verify TOAST messages (these can't be interacted with, only
> text retrieval allowed)

I see [example](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/UIAutomator2Test.java#L86)  how I should test toast

But when I set 
`       capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
`
I broke my test. (Can't find some elements and type text).

So I set `AUTOMATION_NAME` by default
`       capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.APPIUM);
`
My question:
Can I change capability dynamically, namely `automationName`?

I tried to do it in my test like 
`        getDriver().executeScript("env.automationName = 'UIAutomator2'");`

```
        composerPage.setToAddress("test");
        composerPage.sendButton.click();

        getDriver().executeScript("env.automationName = 'UIAutomator2'");

        final WebDriverWait wait = new WebDriverWait(getDriver(), 10);
        WebElement ac = wait.until(ExpectedConditions.presenceOfElementLocated(
                By.xpath("//*[contains(@text, 'Invalid')]")));
```
(from [here](https://github.com/appium/java-client/issues/217#issuecomment-122095883))
 but catch Error 
[gist Java logs](https://gist.github.com/crazyk2/87ad5408db2e28525d22fd0a604c2dc8url) 
[gist Appium server logs](https://gist.github.com/crazyk2/5b8a56ce838ba3746adf5462674b0326#file-gistfile1-txt-L366)

## Environment

* java client 5.0.0-BETA7
* Appium server version: 1.6.4
* Node.js version: 7.5.0
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: HTC Desire 820G dual sim

**Comment by saikrishna321** [comment]
@crazyk2 no you cant change the capability

**Comment by crazyk2** [comment]
Ok.
How should i test toast?
Do not suggest OCR ))

**Comment by SrinivasanTarget** [comment]
@crazyk2 If you wanna test toast messages, you have to use UIAutomator2 as automationName.It is not possible to test the same feature in legacy driver. If running your tests on UiAutomator2 breaks your tests there is no other go you have to fix it one day or other since legacy drivers will be deprecated sooner or later.
