### ISSUE TITLE
Groovy PageFactory

### ISSUE THREAD

**Issue by vVv-AA** [appium/java-client#623]
I know that Groovy exactly isn't supported by Appium by since it also runs on JVM I guess this might be solvable.
## Description

PageFactory.initElements causes problems with when used in groovy except for 2 cases:

public static void initElements(WebDriver driver, Object page)
public static <T> T initElements(WebDriver driver, Class<T> pageClassToProxy)

that too only if you use @FindBy annotation and WebElement as the datatype. Any other combination of annotation and datatype results in java.lang.IllegalArgumentException. 

eg.  java.lang.IllegalArgumentException Can not set io.appium.java_client.MobileElement field com.mobileapp.pageobjects.SplashScreenPageObjects.logInButton to com.sun.proxy.$Proxy7
`
Other PageFactory.initElements do not work and result in https://gist.github.com/vVv-AA/db0279e604d1492dd29aa574c2f82313

## Environment

* java client build version: 5.0.0-BETA4.
* Appium server version: 1.6.4 BETA

## Exception stacktraces

https://gist.github.com/vVv-AA/db0279e604d1492dd29aa574c2f82313

## Link to Appium logs

https://gist.github.com/vVv-AA/e752bc6b2477a0c1ca9e04f93512994c

**Comment by TikhomirovSergey** [comment]
@vVv-AA Sorry for the delaying. I am was very busy.
Could you provide the code sample to reproduce?

**Comment by vVv-AA** [comment]
Its working now. Please close.
