### ISSUE TITLE
Add possibility to check condition of widget and widget elements if widget not present on screen. 

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/java-client#625]
## Description

In the current implementation when we invoke any method of widget or widget elements, if widget not present on screen, throws NoSuchElementsException. 

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA7

## Details

Example: we have class: 

```
public class MobileBlock extends Widget {
    
@AndroidFindBy(id = "main")
public MobileElement element;

    protected MobileBlock(WebElement element) {
        super(element);
    }

    public boolean isDisplayed() {
        return getWrappedElement().isDisplayed();
    }
}
```

If we try invoke method `isDisplayed` in `MobileBlock` class when widget is not present we have `NoSuchElementException`.
Or try to check visibility of widget element we also have `NoSuchElementException`.

**Comment by mykola-mokhnach** [comment]
The [similar](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/1880) issue has already been closed as By Design in original Selenium project. Why should Appium change this behaviour?

**Comment by HlebHalkouski** [comment]
@mykola-mokhnach Thank you for information. I agree with you.
