### ISSUE TITLE
Open API for some pagefactory classes

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/java-client#628]
## Description

Made some classes public: 
- `WidgetByBuilder.class`, 
- `DefaultElementByBuilder.class`, 
- `AppiumElementLocatorFactory.class`.

If this classes made public, we adding opportunity to use `AppiumElementLocatorFactory` with custom decorators. 

As a result, in order to accelerate develop and make UI testing more stable.

**Comment by mykola-mokhnach** [comment]
You could create a PR instead ;)
