### ISSUE TITLE
java.lang.NoSuchMethodError thrown when creating a new AppiumDriver

### ISSUE THREAD

**Issue by YoniH** [appium/java-client#63]
After upgrading java-client from version 1.1 to any higher version (last one I tried is 1.5), I can't create an AppiumDriver. I get the following error:

java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V  at io.appium.java_client.AppiumDriver.<clinit>(AppiumDriver.java:37)

The Selenium version I am using is 2.42.2.

**Comment by PavithraRavichandranR** [comment]
I'm using the jars which @stsatlantis  have mentioned. Still I'm facing the above errorFAILED CONFIGURATION: @BeforeMethod setupAppium
java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V
	at io.appium.java_client.AppiumDriver.<clinit>(AppiumDriver.java:46

I'm using the version of jars which @stsatlantis  have mentioned. Could you please help me out to solve the problem ? Thanks!

**Comment by PavithraRavichandran** [comment]
Hi Everyone, 
I'm using the jars which @stsatlantis  have mentioned. Still I'm facing the above errorFAILED CONFIGURATION: @BeforeMethod setupAppium
java.lang.NoSuchMethodError: org.openqa.selenium.remote.ErrorHandler.<init>(Lorg/openqa/selenium/remote/ErrorCodes;Z)V
	at io.appium.java_client.AppiumDriver.<clinit>(AppiumDriver.java:46

I'm using the version of jars which @stsatlantis  have mentioned. Could you please help me out to solve the problem ? Thanks!

**Comment by TikhomirovSergey** [comment]
Hi @PavithraRavichandran 
It looks like there is a conflict of dependencies on Selenium java. The current version of java-client uses 2.43.1. I think that your project depends on one more version which is probably lower than 2.43.1. Is it true? So you have to remove the outdated dependency. 

PS. The @stsatlantis 's message was posted Jul 18 2014. So many things have been change since that day :)

**Comment by PavithraRavichandran** [comment]
Hi @TikhomirovSergey 
      Thanks much, I'm using java client 2.1.0, now it's working fine :-)

**Comment by Suryatoy** [comment]
Hi all I am using java client 2.1.0 and selenium java 2.43.1 jars..But still I am facing the same issue.Could   
someone help me out? Thanks!
