### ISSUE TITLE
Windows Phone Automation

### ISSUE THREAD

**Issue by prudhvialahari** [appium/java-client#637]
Hi, 
I'm trying to automate windows phone using Appium. I'm using WindowsDriver from java_client.
Appium  V1.6.4
Java V1.8
Selenium V2.53.1 
Java-client V5.0.0 B8

Can you please provide a sample test case which would initialize the WindowsDriver and install an app(.xap) onto the windows phone device.

**Comment by TikhomirovSergey** [comment]
@prudhvialahari Sorry for the delaying. Why do you use Selenium V2.53.1

**Comment by prudhvialahari** [comment]
So, do I need to use other version of selenium or should not selenium at all...?

**Comment by SrinivasanTarget** [comment]
You don't need to use Selenium language bindings coz Java client internally
comes with latest Selenium language bindings.

**Comment by prudhvialahari** [comment]
Ohh.., okay. Can you please show how to initialize the driver for windows phone...

**Comment by SrinivasanTarget** [comment]
@prudhvialahari Hey sorry i missed this thread. I actually don't remember windows-driver supports windows phone. @jlipps or @jonstoneman please confirm.

**Comment by jlipps** [comment]
it does not

**Comment by SrinivasanTarget** [comment]
@prudhvialahari Please raise a feature request [here](https://github.com/jonstoneman/appium-windows-driver/issues)
