### ISSUE TITLE
deviceScreenSize=null with Android device 4.1.2

### ISSUE THREAD

**Issue by appiumnovice** [appium/java-client#638]
## Description

When a test is run, Appium installs android app with success and fails immediately after.
Client side error: java.lang.NullPointerException: null value in entry: deviceScreenSize=null
Only (for the moment) with a device Samsung Google with Android 4.1.2.

## Environment

* java client build version : 5.0.0-BETA8
* Appium server version : 1.6.5-beta / Appium CLI
* Desktop OS/version used to run Appium : Mac OSX El Capitan 10.12.4
* Mobile platform/version under test: Android 4.1.2
* Real device or emulator/simulator: Device Samsung Google (screen size : 720x1280)

## Code To Reproduce Issue [ Good To Have ]

Just run test.

## Exception stacktraces

Java client side error :
https://gist.github.com/appiumnovice/83e5140cd3850aa42b40d60a9a92493d#file-java-client-error

## Link to Appium logs

https://gist.github.com/appiumnovice/83e5140cd3850aa42b40d60a9a92493d#file-appium-log

**Comment by SrinivasanTarget** [comment]
I wonder do we really have any such capability called ```deviceScreenSize``` ?
https://gist.github.com/appiumnovice/83e5140cd3850aa42b40d60a9a92493d#file-appium-log-L26

**Comment by appiumnovice** [comment]
You're probably right.
It was a try. With or without this fake capability, result is identical.

**Comment by SrinivasanTarget** [comment]
Can you give a try with UIAutomator2 as automationName?

**Comment by pr4bh4sh** [comment]
As per this http://appium.io/getting-started.html android 4.1.2(is < API 17) should not work with appium unless you try with Selendroid mode.

@SrinivasanTarget 
I'm not sure, does UIAutomator2 support 4.1.2?

**Comment by mykola-mokhnach** [comment]
Unfortunately UIA2 only supports 5.0+

**Comment by SrinivasanTarget** [comment]
@appiumnovice Can you share your pom.xml?

**Comment by appiumnovice** [comment]
Yes, here is the pom.xml file:
https://gist.github.com/appiumnovice/83e5140cd3850aa42b40d60a9a92493d#file-pom-xml

**Comment by SrinivasanTarget** [comment]
Ah xml looks good.

**Comment by saikrishna321** [comment]
@appiumnovice do you get this when u get the sessionDetails ?

**Comment by SrinivasanTarget** [comment]
Looks like server throws this when we are trying to get the session details to determine the platform

**Comment by jcordero-git** [comment]
Hi everyone, I have the same issue using android 4.2.2, appium 1.6.4, do have anyone idea how to fix it. ;)?

**Comment by appiumnovice** [comment]
OK, I tried to change to "UIAutomator2" and this corrected this problem of deviceScreenSize.
Now, I have another problem with the installation of UIAutomator2 on device.

Appium log:
[debug] [ADB] Running '/Users/tester/Library/android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","34337C97D19100EC","install","-r","/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-debug-androidTest.apk"]
[UiAutomator2] Installed UiAutomator2 server apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/tester/Library/android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","34337C97D19100EC","shell","am","force-stop","io.appium.uiautomator2.server"]
[UiAutomator2] Starting uiautomator2 server v0.1.4 with cmd: am,instrument,-w,io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner
[UiAutomator2] running command...
 adb -s 34337C97D19100EC shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner... 
[UiAutomator2] Waiting for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body

When I try to install UIAutomator2 manually, I obtains the error "INSTALL_FAILED_OLDER_SDK".
It seems to confirm the fact that UIAutomator doesn't support Android 4.x.

**Comment by SrinivasanTarget** [comment]
Yes as said above in comments UIAutomator2 wont work with lower versions.

**Comment by appiumnovice** [comment]
So, there is no possibilities to run a test on Android 4.x devices with Appium ?

**Comment by SrinivasanTarget** [comment]
@sravanmedarapu ping

Don't have any real device to test it. Will test it from my side soon.

**Comment by appiumnovice** [comment]
However, I tried with a Samsung Galaxy 4 mini device (Android 4.2.2) and the app was installed with success.
This is selective.

**Comment by SrinivasanTarget** [comment]
Even i couldn't be able to reproduce it :(

**Comment by appiumnovice** [comment]
OK. Thanks for your help, the problem of "deviceScreenSize" is resolved for me.
I think you can close this issue.
I'll open a new issue if necessary to process the error "INSTALL_FAILED_OLDER_SDK".

**Comment by bennid** [comment]
I'm in need of running tests against older apis, and have seen this while running on a stock android emulator.  Should I open a new bug for this, or can this be re-opened?

**Comment by Moshik177** [comment]
i have the same problem , i am using server 1.6.5 and device version 4.2.2 ,  i got the error .null value in entry: deviceScreenSize=null ,i using Samsung galaxy s4 ,did you have any solution?

**Comment by olyv** [comment]
@appiumnovice Hi, you say the issue is resolved for but can you pleas elaborate on how you fixed the issue? I am having troubles with my Sony L (android 4.2.2) and wonder how I can fix it

**Comment by Jasonzming** [comment]
I have the same problem,I am using server v1.8.0 and device version 4.4.2.  I wonder how I can fix it.
