### ISSUE TITLE
AUTO_GRANT_PERMISSIONS not working

### ISSUE THREAD

**Issue by eliasnogueira** [appium/java-client#639]
## Description

Test script is not able to auto grant android permission when I click in a button that request runtime access to any Android resources.

## Environment

* java client version: 5.0.0-BETA8
* Appium server version: 1.6.5-beta
* Desktop OS/version: MacOSX 10.12.4
* Node.js version: 6.10.2
* Mobile platform/version under test: Android 6.0 and 7.0
* Real device or emulator/simulator: Moto G4 Plus (7.0) and Android Emulator - Genymotion (6.0)

## Details

The app that I using shows a permission alert when I click in a button.
All the time that script run I got a NoSuchElementException (because the next command is click in a button). The test is on the _Code To Reproduce Issue_

Otherwise in another app, that shows the permission alert when an app is shown by the first time, Appium is capable to auto grant the runtime permission.
You can see this code, that works, on https://github.com/eliasnogueira/appium-tips/blob/master/src/test/java/appium/tips/language/LanguageTesting.java

## Code To Reproduce Issue [ Good To Have ]

```java
@Test
public void autoGrantPermissionTest() throws MalformedURLException {
   /*
   * I got this project from following github repository
   * https://github.com/googlesamples/android-RuntimePermissions
   */
   File app = new File("apps/android-RuntimePermissions.apk");

   DesiredCapabilities dc = new DesiredCapabilities();
   dc.setCapability(MobileCapabilityType.APP,app.getAbsolutePath());
   dc.setCapability(MobileCapabilityType.PLATFORM_NAME,MobilePlatform.ANDROID);
   dc.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");

   // this Android capability will auto grant any android runtime permission
   dc.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);

   AndroidDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://localhost:4723/wd/hub"), dc);

   /*
   * In these two commands bellow you won't see the permission to camera and contacts prompt
   * because we se the AUTO_GRANT_PERMISSIONS to true
   */ 
 driver.findElement(By.id("com.example.android.system.runtimepermissions:id/button_contacts")).click();
 driver.findElement(By.id("com.example.android.system.runtimepermissions:id/button_camera")).click();


   String dummyContact = driver.findElement(By.id("com.example.android.system.runtimepermissions:id/contact_message")).getText();
   assertTrue("Text dummy contact not found", dummyContact.contains("DUMMY CONTACT"));
   
   driver.quit();
}
```

## Ecxeption stacktraces

Exception in Appium java-client (NoSuchElementException)
https://gist.github.com/eliasnogueira/df9ad2ba29a6b560c3630f481dcc30a3

## Link to Appium logs
https://gist.github.com/eliasnogueira/f976e708e8d720cdf05129ad3473c1ca

**Comment by eliasnogueira** [comment]
Guys, I have a clue in how to solve this...

I've searched for any item that I could see in the repository to change and test, but I failed...
I found a method in **appium-android-driver** called `grantAllPermissions`, but I don't know where it's located.

To solve the problem manually I did:

- get the list of permissions on the app
`adb shell dumpsys package package_name | grep permission`
- grant each permission 
`adb shell pm grant package_name android_permission`

One thing here is to know if the user is executing the grant permission on a emulator or real device, that needs an argument -d on grant command
`adb shell -d pm grant package_name android_permission`

After run these commands I'm able to click on the buttons and don't see the permission prompt.

If you guys guide me, I can try to apply this.

Regards!

**Comment by SrinivasanTarget** [comment]
@sravanmedarapu ping

**Comment by SrinivasanTarget** [comment]
@eliasnogueira Please try UIAutomator2 mode

**Comment by eliasnogueira** [comment]
Hello @SrinivasanTarget 
I got the same error.
Follow the appium server log: https://gist.github.com/eliasnogueira/b93f3bfacb711423bf680efb8e9a9b3e

**Comment by sravanmedarapu** [comment]
@eliasnogueira, Can you please share the result of below command
`adb shell pm dump com.example.android.system.runtimepermissions`

**Comment by eliasnogueira** [comment]
Here: https://gist.github.com/eliasnogueira/c158dcf4cc8fbf7b6d912d873d63e2e8

There're three permissions request (CAMERA, READ_CONTACTS and WRITE_CONTACTS)

**Comment by Shchepkin** [comment]
the same issue
`"autoGrantPermissions": True`

Appium-Python-Client: 0.26
Appium server version: 1.7.2
Desktop OS/version: Linux Mint 18.3 Sylvia
Node.js version: 9.5.0
Mobile platform/version under test: Android 6.0.1

[2018-02-16_155104549591_appium.log](https://github.com/appium/java-client/files/1731683/2018-02-16_155104549591_appium.log)

**Comment by mykola-mokhnach** [comment]
@Shchepkin You must set ANDROID_HOME environment variable.
