### ISSUE TITLE
setValue() does not clear value

### ISSUE THREAD

**Issue by dr12782** [appium/java-client#643]
## Description

I need to clear a text field that might contain some text. Prior to Appium 1.6.4, I remember setValue used to clear the text and paste the new text. However, now, it appends the new value to the existing value. As a workaround, I am explicitly calling clear() before calling setValue().

## Environment

* Appium java client build version: 5.0.0-beta8
* Appium server version: 1.6.4
* Desktop OS/version used to run Appium if necessary: Sierra (10.12.4)
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 1.6.4 and Appium Desktop 1.0.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real device

**Comment by saikrishna321** [comment]
Closing as server-side issue
