### ISSUE TITLE
Impossible to run test on Android 7.x device

### ISSUE THREAD

**Issue by appiumnovice** [appium/java-client#650]
## Description

When I try to install app on device, the ADB error "must be root" appears.
According to Appium support (https://github.com/appium/appium/issues/8327), "Real devices above API level 23 do not allow adbd to be run as root".
To bypass that error, I just have not to set these two capabilities : 'locale' and 'language'.

Without these capabilities, I can installed app correctly.
But, at this instant, the error "java.lang.NullPointerException: null value in entry: language=null" appears.
If I set this capability, an error for "local=null" appears.
If I set these two capabilities, I encountered the ADB error "must be root".

So, can you remove the obligation to set these capabilities (at least for Android 7.x on device) ?

## Environment

* java client build version : 5.0.0-BETA8
* Appium server version : 1.6.5
* Desktop OS/version used to run Appium : MacOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe) : CLI
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: device Google/LG Nexus 5x

**Comment by SrinivasanTarget** [comment]
Can you share the logs in form of gist for further investigation? AFIK, we didn't restrict anything from client. Will test in real device tomorrow. Btw update the logs here in form of gist.

**Comment by appiumnovice** [comment]
I can reproduce this behavior with Android Studio Emulator 7.0 (x86) + Play:

**1. I run test without capabilites language and locale**

The app is correctly installed
Immediately after this installation, the test stops with a client side error "java.lang.NullPointerException: null value in entry: language=null" 

**Server log**
https://gist.github.com/appiumnovice/88b635a791c65787eb42e82599fffcd3#file-1a-server-log-without-capabilities

**Client log**
https://gist.github.com/appiumnovice/88b635a791c65787eb42e82599fffcd3#file-2a-server-log-with-language-capability


**1. I run test with capabilites language and locale**

The app is not installed, and the test stops on server side error "adb : must be root"

**Server log**
https://gist.github.com/appiumnovice/88b635a791c65787eb42e82599fffcd3#file-2a-server-log-with-language-capability

**Client log**
https://gist.github.com/appiumnovice/88b635a791c65787eb42e82599fffcd3#file-2b-client-log-with-language-capability

Is it possible to test a java client version where capabilities language and locale are not mandatory?

**Comment by SrinivasanTarget** [comment]
Ok i see Appium Server doesn't return the ```platformName``` or doesn't hold ```platformName``` in session so client was not able to determine the platform. Just before you got the error can you debug and check the session details.
>Is it possible to test a java client version where capabilities language and locale are not mandatory?

Client doesn't set any capability as mandatory or optional.

**Comment by appiumnovice** [comment]
OK. How to watch session details ?

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/7730

**Comment by appiumnovice** [comment]
Calling AppiumDriver.getSession() with args: ["ace26b64-a7f1-48f9-bb51-5586b66182a5"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platform":"ANDROID","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.sncf.fusion","app":"/apk/app-integration-release-7.87.apk","clearSystemFiles":true,"keystorePassword":"sncfandroid","keyAlias":"SNCF","language":null,"locale":null,"deviceName":"emulator-5631","fullReset":true,"platform":"ANDROID","keystorePath":"/ta/Keystore/SNCF.keystore","appActivity":"com.sncf.fusion.ui.activity.DashBoardActivity","newCommandTimeout":3000,"keyPassword":"sncfandroid","platformVersion":"7.0","automationName":"UIAutomator2","browserName":"BROWSER","platformName":"Android","useKeystore":true,"udid":"emulator-5631"},"appPackage":"com.sncf.fusion","app":"/apk/app-integration-release-7.87.apk","clearSystemFiles":true,"keystorePassword":"sncfandroid","keyAlias":"SNCF","language":null,"locale":null,"deviceName":"emulator-5631","fullReset":true,"keystorePath":"/ta/Keystore/...

**Comment by appiumnovice** [comment]
I can't have a result for getSessionDetails() because the test crash just during installation of app.

**Comment by SrinivasanTarget** [comment]
I see ```platformName``` caps is available above. Will debug and update you.

**Comment by appiumnovice** [comment]
Thx :)

**Comment by SrinivasanTarget** [comment]
@appiumnovice Dude, why do you set language and locale as null? https://gist.github.com/appiumnovice/88b635a791c65787eb42e82599fffcd3#file-1a-server-log-without-capabilities-L31-L32

Remove those and give a try, it will work.

**Comment by appiumnovice** [comment]
Haaaaaaarrrggg!
You're right! It works perfectly now!
I pass capabilities as external arguments to my test.
When I don't want to use them, I just remove them, but there are effectively set to null inside the test !!!
With a previous version of Appium, this behavior didn't matter. And it doesn't matter with the Android 7 Emulator and Appium 1.6.5.
But with the new Android 7 emulator containing Play Store and with my device Nexus 5x, to set these capabilities to "null" blocks the test run.
I'm sorry I did not check my test settings correctly and disturb you!
Thank you for your help.
