### ISSUE TITLE
AndroidDriver cannot be resolved as a type

### ISSUE THREAD

**Issue by gitissuepost** [appium/java-client#653]
## Description

While instantiate WebDriver object using AndroidDriver, it is saying, "_AndroidDriver cannot be resolved as a type_". I am using a maven project to execute the scripts with Appium 5.0.0-BETA 8. However this si working fine with 4.1.2

## Environment
java client build version : **5.0.0-BETA-8**
Appium server version : **1.6.4**
Desktop OS/version : **Win 10**
Mobile platform/version : **Android/4.4.4**
Real device or emulator/simulator: **Emulator (Genymotion)**

## Code To Reproduce Issue
JavaClass : https://gist.github.com/gitissuepost/796e364df45faa270199491f9d720f4f
POM : https://gist.github.com/gitissuepost/c52f23fa07f2ce6959f85ecc6d93f79c

**Comment by SrinivasanTarget** [comment]
@gitissuepost please raise generic issues in discuss forum.

**Comment by gitissuepost** [comment]
@SrinivasanTarget Can you help me with the link to discuss forum

**Comment by SrinivasanTarget** [comment]
discuss.appium.io but yours is not an appium related issue to discuss there though.
