### ISSUE TITLE
Unable to find node.exe and main.js file to start appium hence unable to start appium programatically

### ISSUE THREAD

**Issue by surikiran** [appium/java-client#654]
I am trying to start appium programatically I installed appium through npm using the below command
npm install -g appium 
before this I installed nodejs too. Previously when I used to install appium it gets installed in C drive of my machine but now surprisingly it's taking C:/User/UserName/AppData/Roaming/npm/appium.... where I am not able to find node.exe as it used to come within the Appium folder only but unable to find it. I wrote a Java program to start appium programatically as below:-

return service = AppiumDriverLocalService.buildService ( new AppiumServiceBuilder ( )
 .usingDriverExecutable ( new File (
"C:\\Program Files\\nodejs\\node.exe" ) )
 .withAppiumJS ( new File (
 "C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js") )
 .usingPort ( port )
		.withArgument ( GeneralServerFlag.LOG_LEVEL ,
		     "debug" ) ) ;
service.start();

surprisingly the appium is not starting and not even a single error shown to identify the exact issue (which is really breaking my head). I tried to start manually with the same path for node and appium which I provided above which got started successfully but not happening when trying programatically. I can proceed by starting it manually but not interested to do so hence thought of doing it programatically which I am unable achieve hence please provide some solution as I am really panic to solve this since 1 week

Environment:-
Appium 1.6.5
Node v6.10.3
Java (JRE) 1.8.0_131
OS : Windows 10
gson-2.8.0
java-client-5.0.0-BETA8

Strange thing is appium itself not happening hence request for a help. This worked well in previous versions of Java but in latest version getting failed

**Comment by surikiran** [comment]
Small change in my above statement "Strange thing is appium itself not happening hence request for a help. This worked well in previous versions of Java but in latest version getting failed" is modified as......Strange thing is appium itself not opening when trying in this way hence request for a help. This worked well in previous versions of Appium both in Windows and Mac OS machines for both Android and iOS devices but in latest version getting failed. Initially tried for Android only with latest version of Appium

**Comment by TikhomirovSergey** [comment]
@surikiran Hi. Sorry for the late response. I am busy now. Is the problem solved? Could you update Node js to 7.x and try again?

**Comment by surikiran** [comment]
No not yet as you are the only person to respond to me as of now.......

On Tue, Jun 13, 2017 at 9:33 PM, Sergey Tikhomirov <notifications@github.com

**Comment by SrinivasanTarget** [comment]
@surikiran Any success? Apologies for late response. Let us know if you hit the same issue again.

**Comment by SrinivasanTarget** [comment]
Closing this as inactive. Feel free to raise a new issue if you hit the same again.
