### ISSUE TITLE
New current_package endpoint on server

### ISSUE THREAD

**Issue by imurchie** [appium/java-client#656]
## Description

Appium 1.6.6 beta has a new endpoint for getting the currently running package during an Android test. This needs to be supported in the Java Client.

See https://github.com/appium/appium-base-driver/commit/190a896d9ce8a877f95392f3ab3d5726f2b2c10a

Re: https://github.com/appium/appium/issues/8674

**Comment by saikrishna321** [comment]
@imurchie will get this on client as well..

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/pull/657
