### ISSUE TITLE
How do I open Web Browsers on windows through AppiumDriver instead of WebDriver ?

### ISSUE THREAD

**Issue by samnit** [appium/java-client#662]
How can I use appium driver to run web browsers on windows as when I try to initialise my Appium Driver with RemoteWebDriver or FirefoxDriver they give an error.
When I Use :
AppiumDriver driver=(AppiumDriver) new RemoteWebDriver(sUrl,caps);

It opens the browser but after that throws the error cannot convert from RemoteWebDriver to Appium Driver
and When I use this :
AppiumDriver driver=new FirefoxDriver();

It gives the compilation error that cannot convert from FirefoxDriver to AppiumDriver.

How can I Use AppiumDriver for web browsers ??

**Comment by SrinivasanTarget** [comment]
By windows do you mean windows mobile? @samnit

**Comment by samnit** [comment]
@SrinivasanTarget No, I meant windows for desktop. I want to run firefox through Appium driver on my PC.

**Comment by SrinivasanTarget** [comment]
@samnit Check this out https://www.youtube.com/watch?v=MgBRvQOZhec
