### ISSUE TITLE
Appium - Android tests takes very long time to run and finally throws  org.apache.http.NoHttpResponseException

### ISSUE THREAD

**Issue by Brad19** [appium/java-client#664]
## Description

I was trying to run the appium tests for Android. And it is taking very very long time to run and slowly my first test is failing with
`org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: 0.0.0.0:4723 failed to respond`

And there is no error from server. This in continuation of the following issue raised a day back.
https://github.com/appium/java-client/issues/661.

I really got struck with this issue for the past 2 days to kick off basic set of tests to check the compatibility for Android and IOS. Can someone please help me if you know the answer

## Environment
Jdk: Jdk- 1.8.0_121
Env variables :
export ANDROID_HOME=/Users/xxxx/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
Appium server: 1.6.6beta
capability settings:
                  capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"emulator-5554");
                  capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"android");
                  capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"7.1.1");
                  capabilities.setCapability(MobileCapabilityType.APP, appForAndroid.getAbsolutePath());
                   capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 120);
OS: macOs sierra 10.12.5
XCode: 8.3.3
node version: v8.1.2
Android emulator: API 25 and Android 7.1.1
Project type: Maven
Pom.xml:
`<dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
            <scope>Test</scope>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.10</version>
            <scope>Test</scope>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.0-BETA9</version>
        </dependency>
    </dependencies>`
## Code To Reproduce Issue [ Good To Have ]
just a sample code to test

public class Appium {
   AndroidDriver driver;
    DesiredCapabilities capabilities = new DesiredCapabilities();

    public WebDriver setUp(String platform) throws Exception {
        int platformVal;
        if (platform == "ios") {
            platformVal = 1;
        } else {
            platformVal = 2;
        }
        switch (platformVal) {
            case 1: File app = new File("/Users/xxxxxx/Desktop/xxxx.app");
                        capabilities.setCapability("deviceName", "iPhone 7");
                        capabilities.setCapability("platformName", "iOS" );
                        capabilities.setCapability("platformVersion", "10.3");
                        capabilities.setCapability("app", app.getAbsolutePath());
                        capabilities.setCapability("appPackage", "xx.xx.xxx.iphone");
                        capabilities.setCapability("appActivity","");
                        break;
            case 2: File appForAndroid = new File("/Users/xxxxx/Desktop/xxxxx-debug.apk");
                        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"emulator-5554");
                        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"android");
                        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"7.1.1");
                    capabilities.setCapability(MobileCapabilityType.APP, appForAndroid.getAbsolutePath());
                        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 120);
                        break;

            default: throw new IllegalArgumentException("Platform chosen was wrong");
        }
            driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities) {
                @Override
                public void swipe(int i, int i1, int i2, int i3, int i4) {}
                @Override
                public void rotate(DeviceRotation deviceRotation) {}
                @Override
                public DeviceRotation rotation() {
                    return null;
                }
            };
            driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
            return driver;   
    }
}

**Comment by SrinivasanTarget** [comment]
@Brad19 Java Client comes along with latest selenium client so you don't need to specify the selenium dependency in pom.xml. please remove that and invalidate the cache in your IDE and give a try. Also FYI there could be issues with Appium on Android 7.1.1.

**Comment by saikrishna321** [comment]
@Brad19 make sure your capabilities are correct, i see you have added appPackage and appActivity for ios 
```
                    capabilities.setCapability("appPackage", "xx.xx.xxx.iphone");
                    capabilities.setCapability("appActivity","");
```

**Comment by Brad19** [comment]
Thanks @SrinivasanTarget  @saikrishna321 . The issue was i was trying to find the elements for Android driver with xpath which i initially found for IOS thinking it'll be same.

**Comment by saikrishna321** [comment]
@Brad19 so is your issue fixed, if so can you pls close this issue
