### ISSUE TITLE
'ESOCKETTIMEDOUT' exception shows in AWS

### ISSUE THREAD

**Issue by Logakarti** [appium/java-client#665]
I get the "ESOCKETTIMEDOUT" exception in AWS while automating the particular cases in Android. Appium log says "Error: Process didn't end after 20000ms at Timeout._onTimeout". How to resolve this issue. I stuck this issue for more than a day.  I can execute that particular cases in my real devices as well without issue.

## Environment
* Appium Version: 1.6.3
* Device : Motorola Moto G (AT&T) 
* Android Version: 4.4.4

## Code To Reproduce Issue [ Good To Have ]
final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
URL url = new URL ( URL_STRING );
DesiredCapabilities capabilities = new DesiredCapabilities ( );
driver = new AndroidDriver<MobileElement> ( url, capabilities );
capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
capabilities.setCapability("newCommandTimeout", "50000");
capabilities.setCapability("recreateChromeDriverSessions", true );
driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS );

## Exception stacktraces
An exception was taken from AWS:
An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: Error: ESOCKETTIMEDOUT

## Link to Appium logs
 https://gist.github.com/Logakarti/f04a226eca77619a3bac7b59b15a2e83

@jlipps 
@mykola-mokhnach

**Comment by Logakarti** [comment]
@mykola-mokhnach

**Comment by Logakarti** [comment]
Have any solution for this issue?

**Comment by SrinivasanTarget** [comment]
There is nothing we could do about it here @Logakarti Please raise it in discuss forum.
