### ISSUE TITLE
Appium IOS driver could not identify subview elements from ListView

### ISSUE THREAD

**Issue by Brad19** [appium/java-client#666]
## Description
Context - React-Native App

I'm trying to identify the elements inside the ListView using appium IOS driver, but it looks like it can't identify the sub view element at all for IOS. Whereas in android it works good. It looks like XCUITEST might have some issue or some settings to be changed. Not sure why this is not working. The Appium inspector or macaca inspector doesn't identify the elements inside subview.

Is this something to do with Appium which doesn't support this or XCTest framework issue. If anyone has any work around, Please provide me and it'll be much helpful.

## Environment
Jdk: Jdk- 1.8.0_121
Appium server: 1.6.6beta
capability settings:
    capabilities.setCapability("deviceName", "iPhone 7");
   capabilities.setCapability("platformName", "iOS" );
   capabilities.setCapability("platformVersion", "10.3");
   capabilities.setCapability("app", app.getAbsolutePath());
   capabilities.setCapability("appPackage", "au.com.forex.iphone");
   capabilities.setCapability("appActivity","");

and using the following code IOS driver
 iosDriver = new IOSDriver<>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
XCode: 8.3.3
node version: v8.1.2
IOS emulator: 10.3 - Iphone 7
Project type: Maven
Pom.xml:
`<dependencies> <dependency> <groupId>org.seleniumhq.selenium</groupId> <artifactId>selenium-java</artifactId> <version>3.3.1</version> <scope>Test</scope> </dependency> <dependency> <groupId>org.testng</groupId> <artifactId>testng</artifactId> <version>6.10</version> <scope>Test</scope> </dependency> <dependency> <groupId>io.appium</groupId> <artifactId>java-client</artifactId> <version>5.0.0-BETA9</version> </dependency> </dependencies>`

## Details

Please find the attachment for both IOS and Android.

## Code To Reproduce Issue [ Good To Have ]

I used the following path shown from screenshots below.

//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]

The above points the list item and no there is no element recognised under the path below

## Exception stacktraces

NA

## Link to Appium logs

NA
Android
![android](https://user-images.githubusercontent.com/10935246/27851207-a084f5d0-619c-11e7-9d26-b366b1b9b261.png)

IOS
![ios](https://user-images.githubusercontent.com/10935246/27851208-a088fafe-619c-11e7-9554-356800636202.png)

**Comment by mykola-mokhnach** [comment]
This could be a programming issue. Check https://github.com/appium/appium/issues/6517

**Comment by Brad19** [comment]
Thanks for the updates. I'm trying now with accessibility ID and will let you know if it works.

**Comment by Brad19** [comment]
I read through and noticed that accessibility label is required to be added. And it looks like parent view should be accessible to bring its child elements, whereas the above 6517 is bit different. But anyway I tried different possibility and still find that it is not working. Here is the code of the list view where I have made View as accessible and trying to find the child elements inside the view. If someone knows pls advise

`renderRow(rowData, sectionID, rowID) {
    return (
      <TouchableHighlight style={ {flex: 1} } underlayColor={"rgb(210,210,210)"} onPress={() => this.pressRow(rowData)}>
       <View style={styles.listViewRow} accessible={true}>
            <Image source={{ uri: rowData.image}} style={ styles.listViewRowIcon } accessibilityLabel="uia-listView-image"/>
            <View style={styles.updateContentColumn} accessible={true}>
              <Text style={[styles.rowSubTitle, styles.textSizeSmall, styles.textColorSecondary]}>{rowData.date}</Text>
              <Text style={[styles.rowTitle, styles.textSizeMedium, styles.textColorNormal, styles.updateRowTitle]} ellipsizeMode={ 'tail' } numberOfLines={ 2 } >{rowData.title}</Text>
            </View>
        </View>
      </TouchableHighlight>
);
`
return (
      <View style={styles.container}>
        <StatusBar barStyle="light-content" />
        <Animated.View style={ [styles.header, { height: headerHeight }]}>
          <Image source={{ uri: this.state.headerArticle.image }} style={ styles.updateHeaderImage }>
            <LinearGradient colors={['rgba(70,69,71,0.9)', 'rgba(54,53,55,0.6)','rgba(54,53,55,0.9)']} style={ styles.updateHeaderImage } />
          </Image>
          <Animated.View style={ styles.updateHeaderText }>
            <TouchableOpacity onPress={ ()=>{ this.pressRow( this.state.headerArticle ) }}>
              <Text style={ styles.updateHeaderTitle }>{this.state.headerArticle.title}</Text>
              <Text style={[styles.updateHeaderDateTime]}>{this.state.headerArticle.date}</Text>
            </TouchableOpacity>
          </Animated.View>
        </Animated.View>
        <ListView
          style={styles.listView}
          dataSource={this.state.dataSource}
          renderRow={this.renderRow.bind(this)}
          scrollEventThrottle={ 16 } 
          onScroll={ (e) => { 
            this.state.scrollY.setValue(e.nativeEvent.contentOffset.y);
          }}
          />
      </View>

**Comment by Brad19** [comment]
Found the solution.  To make it visible, here it is required to set the parent component with accessible={false}. In this case we need to make <TouchableHighlight accessible = {false}>. Thanks for your support.

**Comment by lanzelot1989** [comment]
Hey @Brad19, could you expand a bit on your solution, we are facing the same problem and are struggling to get this right.

**Comment by lanzelot1989** [comment]
Hi, @hemangi-patel!

What worked for us was to follow what was described here (religiously): https://github.com/appium/appium/issues/6517#issuecomment-298037046

In short, setting only the "leaf nodes" of the hierarchy to be accessible (all other elements need to be unaccessible). Let me know if this works for you.

**Comment by simonDominos** [comment]
I found setting accessible={false} meant we couldn't scroll in android

**Comment by deasartech** [comment]
After searching for a long time, this solution allows me to locate deeply nested elements by testID on iOS (react-native app) that were previously unreachable due to limits on the XML tree that is created, child elements were being grouped into the parent element:

Add to capabilities
settings[snapshotMaxDepth], 500
[View settings here for xcuitest v4.16](https://appium.github.io/appium-xcuitest-driver/4.16/settings/)

A normal capability would be added like this:

setting, value
Settings must be added by updating the settings object like this:

settings[setting], value
keys correspond to setting names, and values to the value of the setting.

Appium Version: 2.0.0-beta.46
XCUITEST version: 4.16.10

**Comment by Sreyung** [comment]
> After searching for a long time, this solution allows me to locate deeply nested elements by testID on iOS (react-native app) that were previously unreachable due to limits on the XML tree that is created, child elements were being grouped into the parent element:
> 
> Add to capabilities
> 
> * settings[snapshotMaxDepth], 500
> 
> [View settings here for xcuitest v4.16](https://appium.github.io/appium-xcuitest-driver/4.16/settings/)
> 
> A normal capability would be added like this:
> 
> setting, value Settings must be added by updating the settings object like this:
> 
> settings[setting], value keys correspond to setting names, and values to the value of the setting.
> 
> Appium Version: 2.0.0-beta.46 XCUITEST version: 4.16.10

Thanks for this solution, it worked.

**Comment by deasartech** [comment]
FWIW [this thread](https://github.com/appium/appium/issues/14825#issuecomment-1557437915) might be helpful
