### ISSUE TITLE
Unable to resolve findElementByAndroidUIAutomator with java client :5.0.0-BETA9 version

### ISSUE THREAD

**Issue by skmvali** [appium/java-client#668]
The problem

Unable to resolve the method findElementByAndroidUIAutomator with andriod driver object. Instead working fine with "MobileBy.AndroidUIAutomator("")". is "findElementByAndroidUIAutomator " deprecated with latest version?

Environment

Appium Java Client version : 5.0.0-BETA9
Code To Reproduce Issue

Working Code

DesiredCapabilities cap=new DesiredCapabilities();
cap.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "");
AppiumDriver driver=new AndroidDriver(new URL(""), cap);

driver.findElement(MobileBy.AndroidUIAutomator("")).click();

Unresolved code

driver.findElementByAndroidUIAutomator(").click()

**Comment by TikhomirovSergey** [comment]
@skmvali 

Sorry for the delaying. I am busy.
What do you expect?
Yes. AppiumDriver  has NO findElementByAndroidUIAutomator. It is not implemented by the AppiumDriver class but it is implemented by the AndroidDriver. So the there are two correct ways: 

```java
driver.findElement(MobileBy.AndroidUIAutomator("")).click();
```
as you has described

```java
AndroidDriver driver=new AndroidDriver(new URL(""), cap);
```

**Comment by skmvali** [comment]
Thanks for the reply @TikhomirovSergey

**Comment by SrinivasanTarget** [comment]
I think it is reopened by mistake. Feel free to reopen if you still hit any issues.

**Comment by WalterSihlali** [comment]
Hi Guys
According to my understanding of polymophisim and inheritence principles

AppiumDriver driver = new AndroidDriver(capabilities,"")

driver.findElementByAndroidUIAutomator("") should call the AndroidDriver method andnot the AppiumDriver one but this is not the case

**Comment by vignesh1810** [comment]
I am facing the same issue. Below is my code

File f = new File("src/test/java");
File fs = new File(f,"ApiDemos-debug.apk");
		
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus 6 API 28");
cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
URL url = new URL("http://127.0.0.1:4723/wd/hub");
AndroidDriver<AndroidElement> driver = new AndroidDriver<AndroidElement>(url,cap);
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
// driver.findElementByAndroidUIAutomator ==>findElementByAndroidUIAutomator cannot be resolved or is not a field

selenium-java - 3.141.59
java-client - 7.3.0
<img width="1440" alt="Screenshot 2020-04-21 at 6 56 58 PM" src="https://user-images.githubusercontent.com/40608099/79871619-3d366f00-8402-11ea-9d10-2cfff7450ab1.png">

**Comment by madhusmitanishu** [comment]
I am also facing the same issue, any resolution for this?

**Comment by vignesh1810** [comment]
@madhusmitanishu No resolution. You have to type the entire method name. Then it does not throw the error

**Comment by amodmahajan2016** [comment]
Because findElementByAndroidUIAutomator is a default method which is supported by Java 8 onward. You are using Java 1.5 in project. Change it to 1.8 +.

**Comment by mani19297** [comment]
@amodmahajan2016  thankyou , i changed JAVA SE 1.7 TO JAVA SE 1.8 .Now driver.findElementsByAndroidUIAutomator showing 
![Screenshot (187)](https://user-images.githubusercontent.com/71871071/100556601-73f23300-32c9-11eb-9468-e9420d934ae0.png)

**Comment by joyjagan11** [comment]
![image](https://user-images.githubusercontent.com/69839515/168759069-76028e5b-9e7c-4eb1-91b7-a710aa972c46.png)


am also facing here

**Comment by sweeneyapps** [comment]
@joyjagan11 

MobileBy is deprecated but you can use this:

`driver.findElement(new AppiumBy.ByAndroidUIAutomator("text(\"Views\")")).click();`
