### ISSUE TITLE
NoSuchElementException - sendKeys() & setValue()

### ISSUE THREAD

**Issue by krantos** [appium/java-client#670]
When I try to set values on a _XCUIElementTypeTextField_ 
with _sendKeys() & setValue()_ 
I get this error _org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters._

## Environment
java version: 1.8.0_101
Appium: 1.6.5 server & (Latest on the project pom.xml file)
iOS: Sierra 10.12.3
npm: 4.1.2
ios_platform_version = 10.3
ios_device_name = iPhone 6 (also tried with iPhone 7)
Xcode: 8.3.3

## Details
The element exists, I can make click on it, also get _true_ from _isDisplayed()_ and print it on log like _XCUIElementTypeTextField_
I've tried changing the locator from name to xpath, and nothing.
The most awkward thing is with every change I did, a previous screen which use this code works fine. Also compare the code, and is the same structure of creation and use of this code. 

## Capabilities 
[
      {
           rotatable = true, 
          networkConnectionEnabled = false, 
          noReset = false, 
          databaseEnabled = false, 
          deviceName = iPhone 7, 
          fullReset = false, 
          platform = MAC, 
          platformVersion = 10.3, 
          webStorageEnabled = false, 
          locationContextEnabled = false, 
          automationName = XCUITest, 
          useNewWDA = true, 
          takesScreenshot = true, 
          javascriptEnabled = true, 
          platformName = iOS, 
     }
]

## Code: 
```
try {
       LOGGER.info(mobileElement.getTagName());
       mobileElement.clear();
       mobileElement.click();
       
       if(mobileElement.isDisplayed())
       {
           LOGGER.info("TRUE IS DISPLAYED");
        }
        
       mobileElement.setValue(data);
     }
   catch (Error e)
     {
          LOGGER.error(e.getMessage());
      }
```

also tried with 
mobileElement.setValue(data);
&
mobileElement.sendKeys(data)

## Server Log
```
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/E64A6C32-4AA9-44F8-BC06-E666B4408145/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[@name = 'QuantityTextField']"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"7069C7A3-C35A-44C7-83EB-1195CA06B206","type":"XCUIElementTypeTextField","label":""},"sessionId":"E64A6C32-4AA9-44F8-BC06-E666B4408145","status":0}
```

**Comment by SrinivasanTarget** [comment]
@krantos Can you post complete logs in form of [gist](https://gist.github.com/) here?

**Comment by krantos** [comment]
I've replaced sensible info with xxxxx

https://gist.github.com/krantos/ce308136c88f66fe6b5b1879728b8af4

**Comment by krantos** [comment]
I've made a workaround for this.
