### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 33 milliseconds

### ISSUE THREAD

**Issue by didi112113** [appium/java-client#672]
Hi,

Appium v1.65
Operating System: Windows 7
node v6.11.0
npm 3.10.10

I am new to Appium and I am getting this weird Error: org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement ‘get driverData’? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds

I am running a parallel testing using two Android devices, two instances of Appium and two drivers. I also used one driver before but still I am getting the same error.

my capabilities set using the following method:
public DesiredCapabilities getCaps(String udid, String platformVersion,String deviceName) {
streamCaps.setCapability(“deviceName”, deviceName);
streamCaps.setCapability(“udid”, udid);
streamCaps.setCapability(“platformVersion”, platformVersion);
streamCaps.setCapability(“platformName”, “Android”);
streamCaps.setCapability(“appPackage”, “com.motorolasolutions.videostream”);
streamCaps.setCapability(“appActivity”, “com.motorolasolutions.videostream.VideoStreamActivity”);
streamCaps.setCapability(“autoGrantPermissions”, true);

return streamCaps;

}

Your help is really appreciated. I need a response quickly. I 've been trying for the last 3 days with no luck of getting rid of the error.

Below is the link to the log:
https://gist.github.com/didi112113/8433c43559f1307d5bb7369993797ceb

Thank you

**Comment by SrinivasanTarget** [comment]
@didi112113 I dont see any issues with Appium running parallel using https://github.com/saikrishna321/AppiumTestDistribution. Please check there how was the appium sessions being started parallely for more info raise your questions in appium discuss forum.
