### ISSUE TITLE
[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class pages.HomePage ({})

### ISSUE THREAD

**Issue by livastar** [appium/java-client#673]
## Description
After n times to upgrade the java-client I realized this.
Now I'm using java-client: 5.0.0-BETA8; appium: v1.6.6-beta.3; and serenity-version: 1.4.0
When I'm trying to increase the java client to 5.0.0-BETA9 it gives me the error "[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class pages.HomePage ({})
java.lang.IllegalArgumentException: @$Proxy25: There is an unknown strategy priority"
When I'm trying to increase serenity version to 1.5.3 (the latest one) and java-client 5.0.0-BETA8; the same thing.

## Environment

* java client build version: 5.0.0-BETA8
* Appium server version: v1.6.6-beta.3
* Serenity version: 1.4.0
* Node.js version: v8.1.3
* Mobile platform: iOS
* Real device or emulator/simulator: doesn't metter

## Ecxeption stacktraces
https://gist.github.com/livastar/4f9b7d2c03cb0861f3f259befdb64d06

##Test
https://gist.github.com/livastar/630afddd0aae146c6f4f0fef0283128d

**Comment by TikhomirovSergey** [comment]
@livastar Hi. It is the issue of thucydides/serenity. We added the new parameter to locator annotions at 5.0.0-BETA9. Serenity has code that looks like it was pasted from older versions of java_ client. 

I think that the correct way is to make some PR and propose it to serenity. We have some public API.
