### ISSUE TITLE
Cannot access Duration 

### ISSUE THREAD

**Issue by LeePray** [appium/java-client#674]
## Description
I cannot use Duration in .waitaction 
## Environment

* Android studio 2.3.3
* Appium server version: 1.6.5
* Desktop OS/version used to run Appium if necessary:Mac os 
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real

## Code To Reproduce Issue [ Good To Have ]

````java
    public static void swipeHorizontal(AndroidDriver driver, double startPercentage, double finalPercentage, double anchorPercentage, int duration)  {
        Dimension size = (driver.manage().window().getSize());
        int anchor = (int) (size.height * anchorPercentage);
        int startPoint = (int) (size.width * startPercentage);
        int endPoint = (int) (size.width * finalPercentage);
        new TouchAction(driver).press(startPoint, anchor)
                .waitAction(duration)
                .moveTo(endPoint, anchor)
                .release()
                .perform();
    }
````

## Ecxeption stacktraces

Error:(23, 17) error: cannot access Duration
class file for java.time.Duration not found

**Comment by SrinivasanTarget** [comment]
`waitAction` method can accept only duration not integer. Also make sure you have java 8 and same is correctly configured on path. Java-client or Selenium officially supports Java 8 as min version.

**Comment by LeePray** [comment]
@SrinivasanTarget  Thanks for answer. 
But i already put the correct Java 8 version .

**Comment by SrinivasanTarget** [comment]
@LeePray You are sending integer to a method where it expects only Duration so change int to duration and please send it like below,
`waitAction(Duration.ofSeconds(3)).moveTo(endPoint, anchor).release().perform();`

**Comment by LeePray** [comment]
@SrinivasanTarget  Sorry , i didn't say this. 
When i import Duration , it is  always  maked org.openqa.~~~ . 
I cannot import java.time.Duration. 
But i already said that i put the correct path. 

/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home

**Comment by SrinivasanTarget** [comment]
Please raise your question on our discuss forum. It is something to do with your IDE or should invalidate cache and update your maven repository if not. Nothing to do with Appium or javaclient.
