### ISSUE TITLE
toggleTouchIDEnrollment not implemented?

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#677]
## Description

i see with latest java-client Beta9 we have available "performTouchID" but "toggleTouchIDEnrollment" not available. Did i miss something?

```
        ((IOSDriver) driver).toggleTouchIDEnrollment(); // this does not available
        ((IOSDriver) driver).performTouchID(true);
```

although i see this in test - https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

PS: Also is it possible implement to get current state of TouchIDEnrollment?

**Comment by SrinivasanTarget** [comment]
Test is available [here](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java#L53) and it is implemented only in XCUIT mode

**Comment by amedvedjev** [comment]
@SrinivasanTarget where does toggleTouchIDEnrollment() pointing to? 
e.g. performTouchID -> interface PerformsTouchID

as workaround i am starting driver with "ALLOW_TOUCHID_ENROLL" true.
