### ISSUE TITLE
Replacement for Deprecated Swipe Functions in 5.0.0-BETA2?

### ISSUE THREAD

**Issue by mojojojo94** [appium/java-client#678]
Pretty much the title. Label as question.

Saw that AppiumDriver swipe and MobileElement swipe functions were marked deprecated, is there a replacement for it? Or a better alternative?

Thank you for your time.

**Comment by mykola-mokhnach** [comment]
Use TouchAction methods for swipe purposes.

**Comment by mojojojo94** [comment]
Thank you @mykola-mokhnach, could you provide documentation for those. Thanks again.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/TouchAction.java

All methods there are nicely documented

**Comment by mojojojo94** [comment]
Thank you so much @mykola-mokhnach!!
