### ISSUE TITLE
Showing the eclipse console error "Unable to create new remote session" on mac

### ISSUE THREAD

**Issue by Vismi1** [appium/java-client#679]
## Description
I have installed below listed versions in my mac machine. While running the code in eclipse showing the console error "Unable to create new remote session"
I have attached eclipse code, console error ,appium code. please see in the attachemnt

[untitled folder.zip](https://github.com/appium/java-client/files/1179153/untitled.folder.zip)

## Environment

1.Java - 1.8.0_131
2.xcode - 8.3.3
3.Appium -Version 1.5.3
4.Selenium- 3.4.0
5.Eclipse- 4.7.0

**Comment by SrinivasanTarget** [comment]
@Vismi1 Which version of java client are you using? Also did you invalidate your IDE cache and restarted it? Can you share your logs inform of [gist](https://gist.github.com/)? Share your pom.xml as well if possible.

**Comment by Vismi1** [comment]
Java Client version: 2.1.0
I had cleared cache and restarted , still showing same error
Where i can find pom.xml file??

**Comment by SrinivasanTarget** [comment]
@Vismi1 Please try in a latest version of java client.

**Comment by Vismi1** [comment]
kk..Let me check it

**Comment by Vismi1** [comment]
Installed latest java version....


showing the error.....

org.openqa.selenium.WebDriverException:Unable to parse remote response: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities"]

**Comment by SrinivasanTarget** [comment]
Dude not java JDK, please use latest version of appium's [java-client](https://github.com/appium/java-client/)

**Comment by Vismi1** [comment]
Sorry my mistake....
Installed latest java client version...
