### ISSUE TITLE
Swipe action performs invalid tap on element since navigating on false UI.

### ISSUE THREAD

**Issue by ajit-jadhav** [appium/java-client#684]
## Description
Swipe action from AndroidDriver class performs invalid tap on element since navigating on false UI.

## Environment

* java client build version - 3.4.1
* Appium server version - 1.6.3
* Desktop OS/version used to run Appium if necessary: Windows-8
* Mobile platform/version under test: Android 6.0 
* Real device or emulator/simulator:Samsung On 7

## Details
 1. While performing swipe method call from AndroidDriver class it is tapping on scroll view which is leading to false navigation.
 2. Need an alternate solution which can swipe more fluently like manual scroll/swipe.

**Comment by TikhomirovSergey** [comment]
This method is going to be removed at 5.0.0. It is deprecated method. Please use touch actions instead.
