### ISSUE TITLE
java.lang.IllegalArgumentException: If you use a '@$Proxy14' annotation, you must not also use a '@$Proxy15' annotation 

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/java-client#687]
## Description

Observing the above error message in Page Factory Model. I have referred [Link](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/pagefactory_tests/IOSPageFactoryTest.java)
for writing the xpath

## Environment

* java client build version or git revision if you use some shapshot: 4.1.2
* Appium server version or git revision if you use some shapshot: 1.6.5
* Desktop OS/version used to run Appium if necessary: MacOS
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real Device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

[Code to reproduce ](https://gist.github.com/pavanbachu0604/41a0786cc60dc35c730cb14b86aa4dd2)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs
[Appium Logs](https://gist.github.com/pavanbachu0604/dd8c036bc5ac5bd005a5f7eddf76fca0)

**Comment by TikhomirovSergey** [comment]
@pavanbachu0604 
>java client build version or git revision if you use some shapshot: 4.1.2

The actual version is 5.0.0-BETA9. The error that you caught is the normal behaviour for the 4.1.2.
