### ISSUE TITLE
Why can't I find this file

### ISSUE THREAD

**Issue by GospelHW** [appium/java-client#689]
![image](https://user-images.githubusercontent.com/24928406/29018302-313e5102-7b8d-11e7-8ca3-468afeb15f75.png)

GET_PATH_TO_DEFAULT_NODE_UNIX("get_path_to_default_node.sh"),
 GET_NODE_JS_EXECUTABLE("getExe.js");
    private static final String RESOURCE_FOLDER = "/scripts/";
    private final String script;

    Scripts(String script) {
        this.script = script;
    }

    public File getScriptFile() {

        InputStream inputStream = getClass().getResourceAsStream(RESOURCE_FOLDER + this.script);

java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:721)
	at io.appium.java_client.service.local.Scripts.getScriptFile(Scripts.java:42)

**Comment by saikrishna321** [comment]
@GospelHW pls raise any java-client related issue. This is more java concept. 

@SrinivasanTarget pls close

**Comment by GospelHW** [comment]
why?
Isn't that a problem?I want to be helped because this is the problem I had when I was using the Appium java-client.thank you

**Comment by SrinivasanTarget** [comment]
@GospelHW Whats the problem? I didn't get why do you use these scripts under resources. Are you trying to start appium server programmatically then here you go with [example](https://github.com/appium/java-client/blob/master/docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md).

**Comment by TikhomirovSergey** [comment]
Can't reproduce.
