### ISSUE TITLE
Appium driver quits with 'unknown server error' on disabled button click for iOS.

### ISSUE THREAD

**Issue by deepa782** [appium/java-client#69]
For iOS we have found that sometime Appium driver stops abruptly and got the root cause that it crashes whenever it clicks on a disabled 'Back button'.

Expected:  it should not crash on clicking on a button if its in disabled state. It should fail with an exception.

 
Appium exception and logs are given below:

 
Exception :

 
java.lang.AssertionError: Element Back key not found. Original Error: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 1.60 seconds Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32' System info: host: 'NAG1-DMAC-26709', ip: '172.17.10.238', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.6.0_65' Session ID: e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff Driver info: io.appium.java_client.AppiumDriver Capabilities [{platform=MAC, app=/Users/Glnagpur/Desktop/Appium_Checkout/FiOS-SanityTestAutomation/TestApp/VZFiOSMobile_New.app, javascriptEnabled=true, browserName=Mac, rotatable=true, udid=4afbda0275e921a0c327e6df5715d2081cc4e1f9, desired={newCommandTimeout=600, platformVersion=7.0, app=/Users/Glnagpur/Desktop/Appium_Checkout/FiOS-SanityTestAutomation/TestApp/VZFiOSMobile_New.app, platformName=iOS, deviceName=iPhone, browserName=Mac, device=iPad, rotatable=true, udid=4afbda0275e921a0c327e6df5715d2081cc4e1f9}, locationContextEnabled=false, newCommandTimeout=600, platformVersion=7.0, databaseEnabled=false, deviceName=iPhone, platformName=iOS, webStorageEnabled=false, device=iPad, warnings={}, takesScreenshot=true}] expected [true] but found [false] at reusableComponets.AppiumMethods.click_On_Element(AppiumMethods.java:108) at iOSTests.IphoneTests.test10_DRM_Player_Verification_MyLibraryScreen(IphoneTests.java:455) ... Removed 27 stack frames

Appium logs :
 
debug: Request received with params: {"using":"name","value":"TopBarBackButton"}

debug: Pushing command to appium work queue: "au.getElementByName('TopBarBackButton')"

debug: Sending command to instruments: au.getElementByName('TopBarBackButton')

debug: Sending command to instruments: au.getElementByName('TopBarBackButton')

debug: [INST] 2014-07-21 11:49:35 +0000 Debug: Got new command 49 from instruments: au.getElementByName('TopBarBackButton')

       

debug: [INST] 2014-07-21 11:49:35 +0000 Debug: evaluating au.getElementByName('TopBarBackButton')

       

debug: [INST] 2014-07-21 11:49:35 +0000 Debug: Lookup returned [object UIAButton] with the name "TopBarBackButton" (id: 16).

       

debug: [INST] 2014-07-21 11:49:35 +0000 Debug: evaluation finished

       

debug: [INST] 2014-07-21 11:49:35 +0000 Debug: Running system command #50: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"16"}}...

       

debug: Socket data received (39 bytes)

debug: Socket data being routed.

debug: Got result from instruments: {"status":0,"value":{"ELEMENT":"16"}}

debug: Responding to client with success: {"status":0,"value":{"ELEMENT":"16"},"sessionId":"e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff"}

info: <-- POST /wd/hub/session/e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff/element 200 1196.124 ms - 88 {"status":0,"value":{"ELEMENT":"16"},"sessionId":"e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff"}

debug: Appium request initiated at /wd/hub/session/e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff/element/16/click

info: --> POST /wd/hub/session/e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff/element/16/click {"id":"16"}

debug: Request received with params: {"id":"16"}

debug: Pushing command to appium work queue: "au.tapById('16')"

debug: Sending command to instruments: au.tapById('16')

debug: Sending command to instruments: au.tapById('16')

debug: [INST] 2014-07-21 11:49:36 +0000 Debug: Got new command 50 from instruments: au.tapById('16')

       

debug: [IOS_SYSLOG_ROW ] Jul 21 17:19:36 OS704 MobileGestaltHelper[76] <Error>: libMobileGestalt MobileGestalt.c:267: server_access_check denied access to question UniqueDeviceID for pid 1007

debug: [IOS_SYSLOG_ROW ] Jul 21 17:19:36 OS704 ScriptAgent[1007] <Error>: libMobileGestalt MobileGestaltSupport.m:167: pid 1007 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled

debug: [IOS_SYSLOG_ROW ] Jul 21 17:19:36 OS704 ScriptAgent[1007] <Error>: libMobileGestalt MobileGestalt.c:528: no access to UniqueDeviceID (see <rdar://problem/11744455>)

debug: [INST] 2014-07-21 11:49:36 +0000 Debug: evaluating au.tapById('16')

       

debug: [INST] 2014-07-21 11:49:36 +0000 Debug: UIAButton.tap()

       

debug: [INST] 2014-07-21 11:49:36 +0000 Debug: UIAButton could not be tapped

       

debug: [INST] 2014-07-21 11:49:36 +0000 Debug: evaluation finished

       

debug: [INST] 2014-07-21 11:49:36 +0000 Debug: Running system command #51: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":13,"value":"elementId 16 could not be tapped"}...

       

debug: Socket data received (58 bytes)

debug: Socket data being routed.

debug: Got result from instruments: {"status":13,"value":"elementId 16 could not be tapped"}

debug: Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 16 could not be tapped"},"sessionId":"e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff"}

info: <-- POST /wd/hub/session/e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff/element/16/click 500 1078.717 ms - 201 

debug: Appium request initiated at /wd/hub/status

info: --> GET /wd/hub/status {}

debug: Request received with params: {}

debug: Responding to client with success: {"status":0,"value":{"build":{"version":"1.2.0","revision":"e53f49c706a25242e66d36685c268b599cc18da5"}},"sessionId":"e4b4e1bd-e585-43ca-bbe6-0bc3168a90ff"}

**Comment by surunagaura** [comment]
in that situation if after the appium fail to get that element, if i do some action (Like touch or scroll) it start working as expected.
I was getting  same kind of issue in android real device (moto g)

**Comment by TikhomirovSergey** [comment]
This issue is not actual, I think. If you are facing the same problem with server 1.5.x please open a new one issue there: https://github.com/appium/appium
