### ISSUE TITLE
Error when Trying to click FluentWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object; Exception

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/java-client#690]
## Description

Trying to click element of Native Screen

## Environment

* java client build version or git revision if you use some snapshot: 4.1.2
* Appium server version or git revision if you use some snapshot: 1.6.5
* Desktop OS/version used to run Appium if necessary: MacOS
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS10.2.1
* Real device or emulator/simulator: Real Device
Guava Version- 22.0

## Code To Reproduce Issue [ Good To Have ]

[Code](https://gist.github.com/pavanbachu0604/3eeb5305f75471504361f168740ff4ca)

## Ecxeption stacktraces

[Failure Stack Trace](https://gist.github.com/pavanbachu0604/3eeb5305f75471504361f168740ff4ca)

## Link to Appium logs
[Appium logs](https://gist.github.com/pavanbachu0604/2222cb95fec69014893c879de0c87981)

**Comment by TikhomirovSergey** [comment]
This is not the appium issue. This is related to latest changes of Selenium
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/FluentWait.java#L204

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/FluentWait.java#L34

not google. Sorry.
