### ISSUE TITLE
.withArgument(GeneralServerFlag.LOCAL_TIMEZONE, true) throws compilation error

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#694]
## Description

wrt https://github.com/appium/appium/issues/9022#issuecomment-322275627 & https://github.com/appium/appium/issues/9022#issuecomment-322410984

`.withArgument(GeneralServerFlag.LOCAL_TIMEZONE, true)`

throws below compilation error

`The method withArgument(ServerArgument, String) in the type AppiumServiceBuilder is not applicable for the arguments (GeneralServerFlag, boolean)`

- this works `.withArgument(GeneralServerFlag.LOCAL_TIMEZONE)` but as per https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md, default value is false and user needs to pass true flag for this 

Expected Result:
1. It will be nice to give control to user to pass true / false value for this flag

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA9
* Appium server version or git revision if you use some shapshot: 1.6.6-beta.3
* Desktop OS/version used to run Appium if necessary:Mac 10.12.5
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v7.9.0
* Mobile platform/version under test:
* Real device or emulator/simulator: 

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by TikhomirovSergey** [comment]
@vikramvi Please re-open this issue if not everything is ok and provide more details.

**Comment by vikramvi** [comment]
@TikhomirovSergey I think this is not invalid issue.

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md, if I want to set value as **true** how to do that ?

Can you please re-open this issue as I don't have permission to do it

**Comment by TikhomirovSergey** [comment]
>I want to set value as true how to do that ?

```
builder.withArgument(LOCAL_TIMEZONE)
```
