### ISSUE TITLE
"com.google.common.collect.Multimaps.transformValues" error shows while running the app suite in AWS

### ISSUE THREAD

**Issue by Logakarti** [appium/java-client#702]
## Description
"com.google.common.collect.Multimaps.transformValues(Lcom/google/common/collect/ListMultimap;Lcom/google/common/base/Function;)Lcom/google/common/collect/ListMultimap" error shows while automating the app suite in AWS for Android.

I have no idea to predict the exact issue and where it.
## Environment
Appium version (or git revision) that exhibits the issue: 1.6.5
Mobile platform/version under test: Android
Real device or emulator/simulator: Samsung Galaxy Tab S2 8.0" (WiFi)

## Link to Appium logs

https://gist.github.com/Logakarti/6bb23a42091bebf4670f42b6fc290a22

**Comment by TikhomirovSergey** [comment]
@Logakarti could you show java stacktrace?

**Comment by Logakarti** [comment]
I resolved this issue after adding the below dependency in the pom.xml

<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>

Thanks for lookup...

**Comment by SrinivasanTarget** [comment]
@Logakarti We have released a latest java-client so please give a try there as well.

```
<dependency>
  <groupId>io.appium</groupId>
  <artifactId>java-client</artifactId>
  <version>5.0.0</version>
  <scope>test</scope>
</dependency>
```

**Comment by Logakarti** [comment]
Thanks @SrinivasanTarget 

Sure, I will try it and let you know if any difficulties.

**Comment by SrinivasanTarget** [comment]
Sure @Logakarti
