### ISSUE TITLE
"Encountered internal error running command: Error: Process didn't end after 10000ms" error shows while running the app suite in AWS for Android tablet devices.

### ISSUE THREAD

**Issue by Logakarti** [appium/java-client#703]
## Description
"Encountered internal error running command: Error: Process didn't end after 10000ms" error shows while running the app suite in AWS for Android tablet devices.

I could run successfully without any error in my Android tablet devices and emulators. 

## Environment
* Appium -java-client : 4.1.2
* Appium server version or git revision if you use some shapshot: 1.6.3
* Desktop OS/version used to run Appium if necessary: MAC
* Mobile platform/version under test: 5.1
* Real device : Dell Venue 8 7840(Real device)

## Code To Reproduce Issue [ Good To Have ]
final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL ( URL_STRING );
        DesiredCapabilities capabilities = new DesiredCapabilities ( );
        driver = new AndroidDriver<MobileElement> ( url, capabilities );
        capabilities.setCapability( CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("newCommandTimeout", "50000");
        capabilities.setCapability("recreateChromeDriverSessions", true );
        //Use a higher value if your mobile elements take time to show up
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS );
        try {
            Thread.sleep ( 10000 );
        } catch (InterruptedException e) {
            e.printStackTrace ( );
        }
    }

## Ecxeption stacktraces

https://gist.github.com/Logakarti/38d236797be4af93161ba84c92d206f1

Please help me to resolve above the issue.

**Comment by Logakarti** [comment]
@SrinivasanTarget

**Comment by Logakarti** [comment]
Anyone help me to resolve this issue.

**Comment by SrinivasanTarget** [comment]
@Logakarti Update your chromeversion and give a try. Also would be good if you use latest appium version too which is in beta now. please install via `npm install -g appium@beta`.

**Comment by Logakarti** [comment]
@SrinivasanTarget 

I couldn't update the chromedriver and latest appium , because I'm running my cases in AWS cloud machine.  I can run my cases without issue in my local physical devices and emulators.

**Comment by TikhomirovSergey** [comment]
Servere version and client versin are old. I think we could mark it invalid. I think that @Logakarti have to try it with updated Appium.

**Comment by Logakarti** [comment]
I tried it appium version(1.6.5) and client version(5.0..0) also, the issue still happens.

**Comment by TikhomirovSergey** [comment]
@Logakarti 
It looks similar to
https://github.com/appium/appium/issues/7423

**Comment by TikhomirovSergey** [comment]
Also it is possible that there is something wrong on the server side

**Comment by SrinivasanTarget** [comment]
Please try in latest appium if AWS supports it. Closing this now.
