### ISSUE TITLE
org.openqa.selenium.remote.ProtocolHandshake createSession Error

### ISSUE THREAD

**Issue by welnanick** [appium/java-client#707]
## Description

I updated to java-client v5.0.0 today and suddenly my tests would show an org.openqa.selenium.remote.ProtocolHandshake createSession error when starting the test suite, but the tests still all passed without issue.

## Environment

* java client build version or git revision if you use some shapshot: v5.0.0
* Appium server version or git revision if you use some shapshot: 1.6.6-beta4
* Desktop OS/version used to run Appium if necessary: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: nodejs v8.4.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device

## Exception stacktraces
This is all I get from gradle, even with `exceptionFormat` set to full:
```
Gradle suite > Gradle test STANDARD_ERROR
    Aug 28, 2017 2:11:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
    INFO: Detected dialect: OSS
```
Since the tests don't actually fail, I don't get any stacktrace anywhere

**Comment by SrinivasanTarget** [comment]
Can you share your build.gradle config here @welnanick

**Comment by welnanick** [comment]
[build.gradle](https://gist.github.com/welnanick/c9bd39d30f826dbee7b4db3e5953603c)

I removed a few sensitive things, but they were all just names of tests and files, not anything config wise.

I should note this also is happening on v5.0.1 and happens with iOS as well, tests still all run fine.

**Comment by TikhomirovSergey** [comment]
@welnanick 
So. It can't be reproduced now, is it true?

**Comment by welnanick** [comment]
It happens every time I run my test suite, but does not affect the actual execution. Gradle is outputting an "error" from selenium (it prints to STANDARD_ERROR), but nothing actually fails.

**Comment by welnanick** [comment]
I get the stacktrace from my original post, and then everything continues on as if nothing was wrong.

**Comment by welnanick** [comment]
According to this: https://github.com/SeleniumHQ/selenium/issues/3087, it might be intentional that it is printing out. This doesn't explain why it wasn't printing out before, but may be why it is printing out now?

**Comment by SantiCF** [comment]
I'm getting the same error here with 5.0.0 and 5.0.1:

The error is because the version of com.google.common.collect.ImmutableSet does not have the "toImmutableSet" method. (ProtocolHandshake class, streamW3CProtocolParameters method)

Maybe the Guava version is the culprit?

**Comment by SantiCF** [comment]
It also can't find the method 'throwIfUnchecked' in the AppiumCommandExecutor class

**Comment by TikhomirovSergey** [comment]
@welnanick @SantiCF is there similar problem with 5.0.2?

**Comment by welnanick** [comment]
I still get the output to STANDARD_ERROR, but no change in behavior. Everything still runs fine.

Like before, this "error" is happening but not affecting anything in my tests. Can't speak for other people however.

**Comment by SantiCF** [comment]
@TikhomirovSergey it fixed it for me. As well as excluding selenium and adding the latest manually. So 5.0.2 is good on my end even without the mentioned workaround. 👍🏻

**Comment by raghav9626** [comment]
org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS - getting this below error while exeuting suite

**Comment by testingy12345** [comment]
Please help me to resolve this issue ?
![IMG20191121233225](https://user-images.githubusercontent.com/34809401/69525790-dd40b700-0f8e-11ea-8288-dd243fdc4b2e.jpg)

**Comment by omkarnathsingh** [comment]
@testingy12345 This is not an issue
