### ISSUE TITLE
Protocol handshake error

### ISSUE THREAD

**Issue by ranjitnayak007** [appium/java-client#710]
## Description

Getting error mentioned below while running app on Appium server. It shows device connected, opens app but while selecting elements, it stops and throws error.
--------------------------
org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.

## Environment

NA

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

N/A

**Comment by ranjitnayak007** [comment]
someone help me out if there is a solution.

**Comment by mykola-mokhnach** [comment]
Closed as duplicate of https://github.com/appium/java-client/issues/707

**Comment by ranjitnayak007** [comment]
Can I get a solution please?

**Comment by ranjitnayak007** [comment]
Can i get a solution plz, all my tests are stopped.

Appium server runs correctly, App also opens. but while working on elements, it stops. shows protocolhandshake error.

**Comment by shailjadubey** [comment]
> @mykola-mokhnach Can i get a solution plz, all my tests are stopped.
> 
> Appium server runs correctly, App also opens. but while working on elements, it stops. shows protocolhandshake error. appium logs given below: https://gist.github.com/ranjitnayak007/6a28d7302f95d63a69df9c0ef1547f99

I am facing same error , please help with the solution
