### ISSUE TITLE
 wait.until()  issue  still exists  on 5.0 release 

### ISSUE THREAD

**Issue by bearxc** [appium/java-client#711]
I tried latest java client   5.00/  5.01  

testCompile 'io.appium:java-client:5.0.1'

wait.until(ExpectedConditions.elementToBeClickable(By.id("abc")));

java: method until in class org.openqa.selenium.support.ui.FluentWait<T> cannot be applied to given types;
  required: java.util.function.Function<? super org.openqa.selenium.WebDriver,V>
  found: org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
  reason: cannot infer type-variable(s) V
    (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,V>)

**Comment by TikhomirovSergey** [comment]
@bearxc 
Could you check your dependencies? It seem that you project still depends on on Selenium v < 3.5.x

**Comment by narendra-chandratre** [comment]
Yes, Selenium version is < 3.5.x still facing this issue. 
More info - 
1. Appium 1.8.1
2. Java-client 6.1.0
