### ISSUE TITLE
build issue on  latest code 

### ISSUE THREAD

**Issue by bearxc** [appium/java-client#712]
I tried to build on latest code  , get following errors when build project

Error:(162, 30) java: findElements(org.openqa.selenium.By) in io.appium.java_client.AppiumDriver cannot override findElements(org.openqa.selenium.By) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>....

If I run gradle task   "jar" , I could generate a jar file , but that jar  misses almost all classes for org.openqa.selenium ... 

so what is the correct way to build ???

**Comment by TikhomirovSergey** [comment]
@bearxc 
Could you read this [document](https://github.com/appium/java-client/blob/master/docs/Note-for-developers.md#compiler) please? 

We use Eclipse compiler.
