### ISSUE TITLE
Not able to use isDisplayed() method.

### ISSUE THREAD

**Issue by jcmorfin** [appium/java-client#715]
## Description

After moving to appium java 5.0.1 some methods became unavailable:

- "driver.findElement(By).isDispalyed()" method .
- "driver.manage().window().getSize();" method.

in this case the driver is an IOSDriver instance.

Also the "Swipe" functionality does not work but that can be replaced with TouchAction.

I m using selenium version 3.0.1.

Is there any dependency on the appium java and the selenum version?

I searched around and it looks like no one is having this issue.

## Environment

* java client build version or git revision if you use some shapshot: 5.0.1
* Appium server version or git revision if you use some shapshot: 1.6.5
* Desktop OS/version used to run Appium if necessary: macOS 10.12

**Comment by SrinivasanTarget** [comment]
@jcmorfin I'm not able to replicate it. As said Swipe can be performed only through TouchActions or mobile: methods. Share your pom.xml or Gradle file. Incase if you are overriding selenium dependencies by excluding it from java client it may not work as expected and throw errors.

**Comment by mykola-mokhnach** [comment]
Java client 5.0.1 is only compatible to selenium API 3.5.x, so the problems described here might be kind of expected.

**Comment by jcmorfin** [comment]
Hello, after reading @SrinivasanTarget  response about overriding selenium dependencies I wnt through the pom file and I found this dependency:
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-common</artifactId>
	<version>2.0b1</version>
</dependency>

After I removed the errors were cleared. 

I will also set selenium 3.5 dependency as mentiones by @mykola-mokhnach 

Thank you
