### ISSUE TITLE
Android: UIAUTOMATOR2: CHAIN strategy does not work 

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#716]
## The problem

Chain strategy does not work when finding elements. Problem does not exists when caps set to:
```
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.APPIUM);
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0-beta, java-client: 5.0.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real phone with Android 6.0

## Code To Reproduce Issue [ Good To Have ]

```
    @HowToUseLocators(androidAutomation = LocatorGroupStrategy.CHAIN)
    @AndroidFindBy(id = "sliding_dashboard")
    @AndroidFindBy(id = "handle_icon")
    private AndroidElement switchAccountIcon;
```

## Link to Appium logs

https://gist.github.com/amedvedjev/2da1468ca7aad98f9b827cd171e80118

**Comment by TikhomirovSergey** [comment]
@amedvedjev 
I am not sure that is the client problem. 
Could you try this 

```java
driver.findElementBy(id("sliding_dashboard")).findElementBy(id("handle_icon"))
```
What is happening?

Also this ids are looking suspiciously. Maybe ids should like [here](https://github.com/appium/java-client/blob/2cc72aed588fa96c02895285b33d6bbb9a07eaa1/src/test/java/io/appium/java_client/android/AndroidTouchTest.java) and actually you need for accessibilityId

**Comment by amedvedjev** [comment]
@TikhomirovSergey why suspicious? custom names i gave. not problem to find with old automator cause it is searching itself by adding package name. others will try soon...

**Comment by amedvedjev** [comment]
@SrinivasanTarget  @TikhomirovSergey no idea why but today just can't reproduce the issue. all is fine. also tried following code without any issue.
```
        List<AndroidElement> elementList = driver.findElement(By.id("sliding_dashboard")).findElements(By.id("handle_icon"));
        assertTrue("not found", !elementList.isEmpty());
````

if i fail to reproduce in few days i will close the issue
