### ISSUE TITLE
Selenium dependency boundaries not working with Maven

### ISSUE THREAD

**Issue by Hi-Fi** [appium/java-client#718]
## Description

While trying to create jar with dependencies with Selenium2library-java (https://github.com/Hi-Fi/robotframework-selenium2library-java/tree/Selenium3.5.2) with maven-assembly-plugin:3.1.0, error is thrown because of identical boundaries in Selenium version.

## Environment

* io.appium:java-client:jar:5.0.1
* Microsoft Windows [Version 10.0.15063]
* Maven version: 3.5.0
* Java version: 1.8.0_144, vendor: Oracle Corporation

## Details

Error message from Maven:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (make-assembly) on project robotframework-selenium2library-java: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: Unable to get dependency information for io.appium:java-client:jar:5.0.1: Invalid version for dependency org.seleniumhq.selenium:selenium-java:jar: Range cannot have identical boundaries: [3.5.2,3.5.2]
[ERROR]   io.appium:java-client:jar:5.0.1
```

## Way To Reproduce Issue

Can be seen by executing _mvn clean verify_ with code from https://github.com/Hi-Fi/robotframework-selenium2library-java/tree/Selenium3.5.2

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey FYI

**Comment by TikhomirovSergey** [comment]
@Hi-Fi @mykola-mokhnach Yes. I am taking this issue. As we found the rootcause of many issues (#714) I will return the version number to its normal form (3.5.3 or another higher number) in 5.0.3

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey 

This is what I have found on this topic so far:
http://gradle.1045684.n5.nabble.com/Translating-Ivy-dep-version-syntax-to-Maven-in-POM-generation-td5712755.html

Probably, we can use https://github.com/nebula-plugins/nebula-publishing-plugin, which can properly publish version ranges into Maven pom files.

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach Ok. Will try the nebula plugin. Thank you.

**Comment by realnikunj** [comment]
I am facing this same issue with java-client version 5.0.2

Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (make-assembly) on project mt-ui-utils: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: Unable to get dependency information for io.appium:java-client:jar:5.0.2: Invalid version for dependency org.seleniumhq.selenium:selenium-java:jar: Range cannot have identical boundaries: [3.5.3,3.5.3]
  io.appium:java-client:jar:5.0.2

**Comment by SrinivasanTarget** [comment]
@realnikunj We are working on fix. Will push a release sooner.

**Comment by TikhomirovSergey** [comment]
5.0.3 is coming ASAP.
