### ISSUE TITLE
Appium 1.7.0 will support pushFile for iOS Simulators

### ISSUE THREAD

**Issue by imurchie** [appium/java-client#720]
## Description

Appium 1.7.0 will support pushing individual files to iOS simulators through `simctl addmedia`. The interface is the same as Android: a filename (for iOS, this is the name of a temporary local file that will be pushed) and the base 64 data of the contents. 

It will only work for pushing photos.

The implementation on the server side: https://github.com/appium/appium-xcuitest-driver/commit/430005e7ffec00dc03223efc22575e3984356f9b

**Comment by mykola-mokhnach** [comment]
I'll take care of it
