### ISSUE TITLE
How to control the speed of touchAction

### ISSUE THREAD

**Issue by msmirzazadeh** [appium/java-client#723]
## Description

Is there any way to control the speed of touchAction method?

why swipe was removed from java client 5.0.3

**Comment by krantos** [comment]
I think you can use .waitAction(Duration.ofMillis(time)) and you set the time to control the speed of the action. Chain this into TouchAction before do perform()

**Comment by SrinivasanTarget** [comment]
AFAIK waitAction doesn't control the speed of the touch perform, it is immediate. Check if there is something in mobile: methods for the same.
