### ISSUE TITLE
@AndroidFindBys annotation is not working on appium java client 5.0.0 

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/java-client#724]
problem:
@androidfindbys annotation is not working on appium java client 5.0.0
@androidfindbys({
@androidfindby(id = "au.net.abc.kidsiview:id/action_bar"),
@androidfindby(className = "android.widget.TextView")
)
public MobileElement pageHeading;

Error:
Incompatiable types error

The same is working fine on appium java client 4.0.0.

Environment

Appium:1.6.5
Mac OS:10.11.6
appium java client: tried on both 4.0.0 and 5.0.0

**Comment by TikhomirovSergey** [comment]
Hi @vutukuriswathi 
This sample looks incorrect. The correct code should look like the sample below if you use 5.x

```java
@AndroidFindBys({
@AndroidBy(id = "au.net.abc.kidsiview:id/action_bar"),
@AndroidBy(className = "android.widget.TextView")
)
public MobileElement pageHeading;
```

Also if you need the chained searching you can just

```java
@AndroidFindBy(id = "au.net.abc.kidsiview:id/action_bar"),
@AndroidFindBy(className = "android.widget.TextView")
public MobileElement pageHeading;
```

**Comment by vutukuriswathi** [comment]
This code is working properly on appium java client 4.0.0
@androidfindbys({
@androidfindby(id = "au.net.abc.kidsiview:id/action_bar"),
@androidfindby(className = "android.widget.TextView")
)
public MobileElement pageHeading;

Is there any change in annotation in 5.0.0

**Comment by avanishf** [comment]
Its strange, @AndroidBys works fine on java-client 5.0.1 but not for iOSBys. Instead i had to use iOSFindBys. Is this  a bug in appium?

**Comment by TikhomirovSergey** [comment]
@vutukuriswathi 
Yes. It is the breaking change of the release 5.0.0. Please read my reply above

**Comment by TikhomirovSergey** [comment]
@vutukuriswathi I am closing this issue. If there are some not resolved questions, please reopen this one or open a new issue.
