### ISSUE TITLE
Date picker issue where all elements are under android.view.view

### ISSUE THREAD

**Issue by kuldeeppatil6290** [appium/java-client#731]
Hi All,

When I am using find element().click(); under for loop for date picker it is moving elements unexpectedly. some times by 2 elements some time by 1 element.

Please could you help us as we are stuck in date picker. our date picker does have text enable it is only clickable, focusable 

Please let me know if you want more details

**Comment by SrinivasanTarget** [comment]
Please raise this in appium discuss forum.
