### ISSUE TITLE
Unable to identify elements using @iOSXCUITFindBy for following-sibling, preceding-sibling and parent element.

### ISSUE THREAD

**Issue by ashrafmulla105** [appium/java-client#734]
## Description

I am trying to identify iOS elements using @iOSXCUITFindBy. But for the individual element it is working fine. For e.g. if I try to identify element whose xpath is

**Xpath:** 
@iOSFindBy(xpath = "//XCUIElementTypeActivityIndicator[@label='In progress' or @label='en cours']")
**using @iOSXCUITFindBy:**
@iOSXCUITFindBy(iOSClassChain = "**/*[`label=='In progress' OR label=='en cours'`]")

This works fine but when I try to identify element whose xpath is
**Xpath:** 
``
@iOSFindBy(xpath = "//XCUIElementTypeStaticText[contains(@label,'Email Address') or @label='Adresse courriel pour Virement Interac']/../following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText")
``
**Using @iOSXCUITFindBy:**
``
//@iOSXCUITFindBy(iOSClassChain = "**/*[`label CONTAINS[cd] 'Email Address' OR label CONTAINS[cd] 'Adresse courriel pour Virement Interac'`]/../following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText")
``
This does not identify the element.

## Environment

JAVA CLient - 5.0.0-BETA9
Appium Server - 1.6.6-beta.4
OS -MacOS Sierra 10.12.6
iOS version - 10.3.3

## Code To Reproduce Issue [ Good To Have ]

```
@iOSFindBy(xpath = "//XCUIElementTypeStaticText[contains(@label,'Email Address') or @label='Adresse courriel pour Virement Interac']/../following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText")
	@iOSXCUITFindBy(iOSClassChain = "**/*[`label CONTAINS[cd] 'Email Address' OR label CONTAINS[cd] 'Adresse courriel pour Virement Interac'`]/../following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText")
	private MobileElement emailAddressVal;
```

**Comment by mykola-mokhnach** [comment]
`../following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText` - this won't work with class chain and the syntax is considered incorrect. 
Class chain is a thin wrapper over native XCTest locators and since these don't provide any possibilities to locate sibling elements then it's impossible in class chain as well.

**Comment by ashrafmulla105** [comment]
Then how can I identify the siblings or parents using @iOSXCUITFindBy? As I don't want to use xpath which takes too much time to identify the elements.

**Comment by mykola-mokhnach** [comment]
I don't know any other way of doing this except of xpath. [This PR](https://github.com/facebook/WebDriverAgent/pull/702) should improve the performance there a bit.

As a workaround one can locate a parent element and then filter all its children, but this will require more then one lookup request, so not sure which approach is going to be faster.
