### ISSUE TITLE
[5.0.3] .sendKeys() crashes app when interacting with an editText with android:maxLength set

### ISSUE THREAD

**Issue by welnanick** [appium/java-client#736]
## Description
I have a scenario where I am testing that an editText reacts properly when I attempt to type more characters than it is allowed to hold. I was initially calling .sendKeys() with a string that was 1 longer than what the editText allowed. Today this started to crash the application. I have not changed java-client versions or Appium server versions since it was working last friday. .setValue() still works fine, so I do not know what changed.

## Environment

* java client build version or git revision if you use some shapshot: 5.0.3
* Appium server version or git revision if you use some shapshot: 1.7.0
* Desktop OS/version used to run Appium if necessary: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

```
@AndroidFindBy(id = "editText")
private MobileElement editText; //can only handle 8 characters
...

editText.sendKeys("123456789");
```

## Exception stacktraces

There are none, the app crashes but the java client just complains about not finding elements after the app crashes.

**Comment by saikrishna321** [comment]
@welnanick Nothing has been changed on sendKeys() can you pls post server logs and can you also see if this crash occurs when you try it manually ?

**Comment by welnanick** [comment]
I'll get logs here in a second, I need to modify my environment so it only runs the one test, however connecting to my appium server with appium-desktop and mimicking the test causes no crash, however the behavior of send keys eems to be different between the two. 

On appium-desktop the string looks like it is being typed in to the editText, however using the java client the string just pops into existence as if it was pasted into the editText. I tried pasting a string that was too long manually and the app did not crash. 

When I switched to using .setValue() in the java client, it started to do the "typing" of the string just like appium-desktop and stopped crashing the app, rather than "pasting" the string. .sendKeys() used to act like .setValue(), typing in the string, but at some point has seemingly changed.

Did selenium update at all? I didn't see it download any new dependencies, but maybe I missed it. The only thing I know changed was my app, and the visual behavior of .sendKeys(). I double checked the changes in my app, but the screen that is crashing has not been changed since May (both the layout xml and activity java file).

**Comment by welnanick** [comment]
So, I feel a little bit dumb. This seems to be a UiAutomator2 issue NOT a java-client issue. I forgot to set the automationName capability when testing with appium-desktop, with it set appium-desktop also causes the crash. Closing this issue and opening a new one on the main appium repo. Sorry everyone.
