### ISSUE TITLE
Android: getPageSource() does not return all elements.

### ISSUE THREAD

**Issue by amedvedjev** [appium/java-client#74]
Hi,

while trying to workaround "https://github.com/appium/appium/issues/3222" i met with same issue, but now with "driver.getPageSource()".

I can find some elements By.Id with "driver.findElements" (or with android UIAutomator tool) but can't see it in "driver.getPageSource()". 

I can  share logs externally that subsequent:
- driver.findElements(By.Id "someText") = success
- driver.getPageSource -> search for "someText" = failed
- driver.findElements(By.Id "someText") = success

Is there any workaround between these two issues?

in the mean time i am force to balance both two searches:
- search driver.findElements(By.Id "someText")
- or search inside driver.getPageSource -> get element bounds attribute -> tap element with driver.tap(1,x,y,200)

or 
- vice versa

**Comment by 0x1mason** [comment]
@amedvedjev @amirnissim @takakim  and others: I added a workaround to AppiumBootstrap.jar that resolves this behavior. https://github.com/appium/appium/issues/4200

**Comment by amirnissim** [comment]
great news! thanks @0x1mason :+1:
