### ISSUE TITLE
Desctop WindowsDriver doesn't find native controls in Chrome

### ISSUE THREAD

**Issue by iravasylyk** [appium/java-client#740]
## Description
inspect.exe parsing elements on native Chrome elements on Desctop (url field, buttons, menu, toolbar)
browser is starting, but failing with exception element wasn't found
 DesiredCapabilities capabilities = new DesiredCapabilities();
 capabilities.setCapability("app", "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");
 driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
 driver .manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
 driver .findElementByName("Reload").click();

 https://drive.google.com/open?id=0B-2ZhNxhgOzFVk82OFFZay1vQzQ screenshot from inspector.exe

## Environment

* java client build version or git revision if you use some shapshot: 1.8
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary: 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
How this issue is related to the java client? Please move it to https://github.com/appium/appium/issues
Also, attach the output of getPageSource command as well as full server log
