### ISSUE TITLE
How to make a swipe with IOS?

### ISSUE THREAD

**Issue by BlayerB** [appium/java-client#743]
## Description

Can't make a horizontal swipe.

## Environment

* java client version 5.0.3
* Appium server version 1.6.5
* IOS
* simulator

**Comment by TikhomirovSergey** [comment]
@BlayerB 
Hello. Have you tried combinations like below?
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSTouchTest.java#L40

I suppose you may need some other sequence.
