### ISSUE TITLE
WebDriverWait doesn't work

### ISSUE THREAD

**Issue by hepilt** [appium/java-client#744]
## Description

I've set implicitlyWait to:
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

and then i've used:
new WebDriverWait(driver, 1L).until(ExpectedConditions.presenceOfElementLocated(by));

but it doesn't work as expected

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA9
* Appium server version or git revision if you use some shapshot: 1.7.1
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Nexus 5

## Link to Appium logs

HTTP] --> POST /wd/hub/session/9a7a08b4-1a2d-48f9-b707-f61588cfb37b/element {"using":"id","value":"id/exit"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","id/exit","9a7a08b4-1a2d-48f9-b707-f61588cfb37b"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"id/exit","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"id/exit","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'id/exit' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=id/exit]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'id/exit' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=id/exit]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [BaseDriver] Waited for 91 ms so far

**Comment by FA-tvonmoll** [comment]
Mixing implicit and explicit waits can definitely lead to confounding outcomes. I'd recommend just sticking with your explicit wait (and ditch the `.implicitlyWait(...)` line).

**Comment by TikhomirovSergey** [comment]
@hepilt @FA-tvonmoll 
Yes. There is the conflict between implicit and explicit waitings. I would like to recomment you to only one of these waiting strategies.

**Comment by vikramvi** [comment]
@hepilt this is how I'm currently doing in my framework

public PageObjectClassName(AppiumDriver driver){
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver, 1, TimeUnit.SECONDS), this);
    }

helper method

public boolean isElementPresent(WebElement elementName, int timeout){
        try{
            int counter = 0;
            while(counter < timeout){
                Thread.sleep(1000);
                counter++;
                try{
                    if(elementName.isDisplayed()){
                        //if(ExpectedConditions.visibilityOf(elementName) !=null ){
                        return true;
                    }else{
                        continue;
                    }
                }catch(Exception e){
                    continue;
                }
            }
            System.out.println("ELEMENT NOT FOUND  -  " + elementName  + "  AFTER  " +  timeout  );
            return false;
        }catch(Exception e){
            return false;
        }
    }

this helper method can be called for each of the mobile elements with different time specified.
