### ISSUE TITLE
I don't want this method to return null if element is not found

### ISSUE THREAD

**Issue by ashrafmulla105** [appium/java-client#745]
## Description

The below method I am using to create dynamic elements in my page factory model. I am passing the IOSClassChain value as a string and then converting it into element. This works fine when the element is present on the page but this returns null when the element is not present. Below is the method:

## Environment

* java client - :5.0.0-BETA9
* Appium server version:1.6.6-BETA4
* Desktop OS/version: Windows 10
* Mobile platform/version under test: 6.0.1 - Galaxy S7

## Code To Reproduce Issue [ Good To Have ]

`public MobileElement mobileElementUsingIOSClassChain(String objElement) throws IOException {

    MobileElement objMobileElement = null;

    try {
        objMobileElement = (MobileElement) ((AppiumDriver) GetDriver()).findElement(ByIosClassChain.iOSClassChain(objElement));

    } catch (Exception e) {
        System.err.println("Element not found");
    }
    return objMobileElement;

}`

The value I am passing for objElement is:

`String elementStr = "**/XCUIElementTypeButton[`label=='Name'`]"`

Any Suggestions?

**Comment by mykola-mokhnach** [comment]
What do you expect to be returned instead? it works exactly according to your logic: findElement throws an exception if the element is not present, you silence it in the _catch_ block and get the default null value as the result.

**Comment by ashrafmulla105** [comment]
I am expecting if we can create a dummy element that can be used instead of null value. something like `objElement = somePseudoElementCreated`. Can we do that?

**Comment by mykola-mokhnach** [comment]
You can do it in your client code. WebDriver standard does not declare anything like this.
