### ISSUE TITLE
Exception java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.MobileElement

### ISSUE THREAD

**Issue by Rnij** [appium/java-client#746]
## Description

Getting exception java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.MobileElement.

## Environment

* java client build version or git revision if you use some shapshot:java-client-4.1.2.jar
* Appium server version or git revision if you use some shapshot:1.6.5
* Desktop OS/version used to run Appium if necessary:1.2.1
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:10.3.3
* Real device or emulator/simulator:Real device

## Details

I would like to use IOSDriver as I want to use TouchAction to automate the app. IF I use IOSDriver then it gives a type cast exception. How can I resolve that? 

## Code To Reproduce Issue [ Good To Have ]

AppiumDriver<MobileElement> driver;
driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"),d);

**Comment by mykola-mokhnach** [comment]
It's an expected exception. You must update java client to the most recent version to be able to use it with Selenium 3.

**Comment by Rnij** [comment]
@mykola-mokhnach Thanks, after updating I did not get the exception.

**Comment by matteocollina** [comment]
@mykola-mokhnach Thank you! I changed to 5.0.4 and it works
