### ISSUE TITLE
How do you scroll to an out of view element?

### ISSUE THREAD

**Issue by paul-nelson-baker** [appium/java-client#747]
## Description

I cannot find a reliable way to scroll an element into view so I can interact with it.

## Environment

* java client build version or git revision if you use some shapshot: 5.0.3

## Details

The change-log shows that scrollTo was removed in a previous version about three years ago, and in this [revision](https://github.com/appium/java-client/commit/88197f71a146e69ce4e6696cad3d24f190d89a36). All my researching shows people used to call this method, or execute now removed javascript to scroll to the element. Looking through some stuff, I think you're supposed to use `io.appium.java_client.MobileBy.AndroidUIAutomator(String uiautomatorText)`. The javadoc references the [http://developer.android.com/intl/ru/tools/testing-support-library/index.html#uia-apis](http://developer.android.com/intl/ru/tools/testing-support-library/index.html#uia-apis), but that in and of itself no longer references anything.

How do you scroll an element into view?

**Comment by TikhomirovSergey** [comment]
Hi @paul-nelson-baker 
Yes. There is no scroll methods. And I think you can use the searching for the scrolling.

https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidSearchingTest.java#L60
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidElementTest.java#L70

https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSScrollingSearchingTest.java

**Comment by paul-nelson-baker** [comment]
So it looks like the best reference for building a UiScrollable/UiSelector is in the manor shown by your links. It looks like the best reference is [here](https://developer.android.com/reference/android/support/test/uiautomator/UiSelector.html) and [here](https://developer.android.com/reference/android/support/test/uiautomator/UiScrollable.html), but we lose type safety and compile-time checking by building code inside a string. Is there a way to do this pragmatically without having to pass code via String?

**Comment by saikrishna321** [comment]
Closing as InActive

**Comment by paul-nelson-baker** [comment]
@saikrishna321 While I can understand why this would be closed for lack of answer, I'd still like more information on how to do this and why it was done this way instead. Type-Safety is a big part of what makes Java, Java. I've been having to teach QAs how to program, and it would be impossible to get them to write anything coherent if the compiler didn't tell them they couldn't do something right out of the gate. Why are we passing code via String?
