### ISSUE TITLE
Question: How to use iOS UIAUtomation Strategy

### ISSUE THREAD

**Issue by stephenws** [appium/java-client#749]
## Description

Hi, I am using @iOSFindBy method, in this it is showing @iOSFindBy UIAutomation
I understand how to use UIAutomation in @androidFindBy but nop idea how to use in @iosFindBy

Can you give idea how to use UIAutomator in @iosFindBy
## Environment

* java client build version or git revision if you use some shapshot: 5.0.1
* Appium server version or git revision if you use some shapshot: 1.7.0
* Desktop OS/version used to run Appium if necessary:Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by SrinivasanTarget** [comment]
@stephenws Refer this tests: https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/pagefactory_tests/IOSPageFactoryTest.java#L58
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/pagefactory_tests/XCUITModeTest.java
Wiki: https://github.com/appium/java-client/blob/master/docs/Page-objects.md
