### ISSUE TITLE
Getting exception Error converting element ID for using in WD atoms: 8350431A-D0BF-499F-9C0A-F91B0B409401

### ISSUE THREAD

**Issue by Rnij** [appium/java-client#750]
## Description

I am trying to get the font size for static text on an app and getting below error.

Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: 8350431A-D0BF-499F-9C0A-F91B0B409401 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds

## Environment

java client build version or git revision if you use some shapshot:java-client-5.0.4.jar
Appium server version or git revision if you use some shapshot:1.6.5
Desktop OS/version used to run Appium if necessary:1.2.1
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
Mobile platform/version under test:10.3.3
Real device or emulator/simulator:Real device

## Details

I have to test the font size for the iPad app and using the code below it is throwing an error.

## Code To Reproduce Issue [ Good To Have ]

AppiumDriver<IOSElement> driver;
driver = new IOSDriver<IOSElement>(new URL("http://127.0.0.1:4723/wd/hub"),d);
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

String fontsize=driver.findElementByXPath("//XCUIElementTypeStaticText[@name=\"Proof of Residence\"]").getCssValue("font-size");
System.out.println("Font Size -> "+fontsize);

**Comment by mykola-mokhnach** [comment]
Are you in a web view context while this command is executed?

**Comment by Rnij** [comment]
@mykola-mokhnach I am not sure about that. How can I find out?

**Comment by Rnij** [comment]
It is not a web application if thats what you are asking.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mykola-mokhnach** [comment]
The the described exception is expected. CSS has no sense for mobile native context.

**Comment by Rnij** [comment]
How can I get the font size and font type for mobile native app?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Rnij** [comment]
I have to test the font type and font size on a  mobile app. How can i do that?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mykola-mokhnach** [comment]
Probably using screenshot comparison with baseline. There are also specialised tools for this on the market.

But I personally would do such comparison in unit tests rather that end-to-end.
