### ISSUE TITLE
Java client library throwing UnreachableBrowserException while trying to start Appium server programmatically using AppiumServiceBuilder

### ISSUE THREAD

**Issue by manojhans** [appium/java-client#751]
## Description

I m trying to start Appium Server programmatically using java client 5.0.4 but getting an exception 
UnreachableBrowserException.

## Environment

Java Client: 5.0.4
Appium Server: 1.7.1
OS: Window 10, Mac 10.12.6
Nodejs: 8.6.0
emulator/simulator: Android/6.0, iPhone/11.0 

## Details

This issue arise when I invoke Appium server without providing node executable and let the code find the executable on the basis of environment variable. Java code is able to find the node binary path but not able to add the node executable. 

Have a look on the comments in the below code:
Under AppiumServiceBuilder class we have a function which looks for the default executable:

protected File findDefaultExecutable() {
        String nodeJSExec = System.getProperty("NODE_BINARY_PATH");

        if(StringUtils.isBlank(nodeJSExec)) {
            nodeJSExec = System.getenv("NODE_BINARY_PATH");//Successfully identify the path
        }
        if(!StringUtils.isBlank(nodeJSExec)) {
            File commandLine = new File(nodeJSExec);
            if(commandLine.exists()) {// here it is returning the File path without knowing that it is executable or not, due to this it is throwing NullPointerException as code is not able to find node executable
                return commandLine;
            }
        }
        this.setUpGetNodeJSExecutableScript();
        CommandLine commandLine1;
        try {
            if(Platform.getCurrent().is(Platform.WINDOWS)) {
                commandLine1 = new CommandLine("node.exe", new String[]{this.getNodeJSExecutable.getAbsolutePath()});
            } else {
                commandLine1 = new CommandLine("node", new String[]{this.getNodeJSExecutable.getAbsolutePath()});
            }

## Code To Reproduce Issue

AppiumServiceBuilder appiumServiceBuilder = new AppiumServiceBuilder()              .usingAnyFreePort();
driver = new AndroidDriver(appiumServiceBuilder, capabilities);

## Resolution 

We can change this condition 
if(commandLine.exists()) 
to  
if(commandLine.exists() && !commandLine.isDirectory() && commandLine.canExecute())

## Exception stacktraces

https://gist.github.com/manojhans/1c2c702bcd72e4880cc3669c5b11bc7d#file-javaclientexception-txt
## Link to Appium logs

No Need for Appium logs as this issue is related to java client

**Comment by SrinivasanTarget** [comment]
Wont be an issue if PATH variables including APPIUM_BINARY_PATH are set properly
