### ISSUE TITLE
Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

### ISSUE THREAD

**Issue by keshavwy** [appium/java-client#752]
## Description

Not able to use xcrun even though it is installed.

## Environment

1. Appium version (or git revision) that exhibits the issue: 1.7.1
2. Mobile platform/version under test: iOS (10.3.3)
3. Real device or emulator/simulator:iphone (real device)

## Details
Here is a link: https://gist.github.com/keshavwy/d7beaa9e85e156ad0f5c3cf252e74019#file-gistfile1-txt

**Comment by keshavwy** [comment]
Whenever I try to run my code using testng.Xml, I am hitting the above-mentioned error. If I run the test cases separately it works fine.

**Comment by saikrishna321** [comment]
@keshavwy make sure you have command-line tools installed

**Comment by keshavwy** [comment]
@saikrishna321 
Command line tools are installed on my machine. PFA
<img width="571" alt="screen shot 2017-10-14 at 14 47 17" src="https://user-images.githubusercontent.com/11436452/31574494-c3052660-b0ee-11e7-90fe-ee324497c665.png">

I am facing issue only if I run the code through testng suite. I mean through testng.xml file

**Comment by keshavwy** [comment]
I am on Xcode 9.0 and  using MacOSX High sierra

**Comment by keshavwy** [comment]
This issue is solved now.
