### ISSUE TITLE
IOS touch action pass wrong parameters to /wda/dragfromtoforduration

### ISSUE THREAD

**Issue by rayzhouzhj** [appium/java-client#762]
## Description

When swiping in IOS, try to swipe from right to left, wrong parameters are passed to /wda/dragfromtoforduration

## Environment

* java client build version or git revision if you use some shapshot: 5.0.4
* Appium server version or git revision if you use some shapshot: 1.7.1
* Desktop OS/version used to run Appium if necessary: MacOS 10.12.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.1.2
* Mobile platform/version under test: Iphone 7 10.3.3
* Real device or emulator/simulator: Real Device

## Details

API is receiving action  press(options={"x":337,"y":333})-moveTo(options={"x":37,"y":333})
but sending request as:
Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:58886/session/2C0C11E1-B469-45BE-BD2E-D03D27E12053/wda/dragfromtoforduration] with body: {"fromX":337,"fromY":333,"toX":374,"toY":666,"duration":0.5}

## Code To Reproduce Issue [ Good To Have ]

		// Swipe from right to left in IOS
		TouchAction action = new TouchAction(driver);

		Dimension dimension = driver.manage().window().getSize();
		action.press(dimension.getWidth() * 9 / 10, dimension.getHeight() / 2)
		.waitAction(Duration.ofMillis(500))
		.moveTo(dimension.getWidth() / 10, dimension.getHeight() / 2)
		.release().perform();

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

[debug] [MJSONWP] Responding to client with driver.getWindowSize() result: {"width":375,"height":667}
[HTTP] <-- GET /wd/hub/session/87b388b6-111f-4783-93a7-77a5bc07c6cd/window/current/size 200 388 ms - 98 
[HTTP] --> POST /wd/hub/session/87b388b6-111f-4783-93a7-77a5bc07c6cd/touch/perform {"actions":[{"action":"press","options":{"x":337,"y":333}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":37,"y":333}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":337,"y":333}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":37,"y":333}},{"action":"release","options":{}}],"87b388b6-111f-4783-93a7-77a5bc07c6cd"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":337,"y":333})-wait(options={"ms":500})-moveTo(options={"x":37,"y":333})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:58886/session/2C0C11E1-B469-45BE-BD2E-D03D27E12053/wda/dragfromtoforduration] with body: {"fromX":337,"fromY":333,"toX":374,"toY":666,"duration":0.5}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"2C0C11E1-B469-45BE-BD2E-D03D27E12053","status":0}

**Comment by mykola-mokhnach** [comment]
moveTo method expects offsets from the recent touch point rather absolute coordinates. So I expect at leats one of them to be negative in order to swipe from right to left

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey FYI

**Comment by rayzhouzhj** [comment]
Thanks for your reply @mykola-mokhnach 

But I think the function moveTo() behaviors differently between android and IOS, as in android it accepts absolute coordinates but not offsets.

When I run the same code on android device, it swipes successfully with absolute coordinates just like I run the adb command (adb shell input swipe 1296 1280 144 1280):
touch/perform {"actions":[{"action":"press","options":{"x":1296,"y":1280}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":144,"y":1280}},{"action":"release","options":{}}]}

And if I use offsets in the moveTo() function with a negative value, it will throw out an exception:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)

Do you think it would be better the function moveTo() sync the behavior between android and IOS so that we do not need to provide different codes for different devices?

**Comment by mykola-mokhnach** [comment]
@dpgraham @imurchie  Is there a spec somewhere on how moveTo method should behave in JSONWP protocol?

**Comment by dpgraham** [comment]
There's this: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchmove

Nothing super detailed though

**Comment by dpgraham** [comment]
There's also the w3c spec: https://www.w3.org/TR/webdriver/#dfn-pointermove

`pointerMove` is equivalent to `moveTo`

**Comment by mykola-mokhnach** [comment]
@rayzhouzhj It seems like the implementation on iOS side contains a bug that makes these coordinates to be calculated differently. For now, please use offsets as moveTo arguments as a workaround. We are going to address this issue in the next minor Appium version (most likely 1.7.3).

**Comment by rayzhouzhj** [comment]
Thanks @mykola-mokhnach
