### ISSUE TITLE
why server`s log  is showing in Eclipse Console, Although i have already  written the log to file?

### ISSUE THREAD

**Issue by smallsharp** [appium/java-client#767]
## Description
i use the code
```
File folder = new File("log");
folder.mkdir();
File logFile = new File(folder, UDID +System.currentTimeMillis()+ ".log");
localService = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
				.withLogFile(logFile)
```
and i found the logFile in the workspace ~/log/xxx.log

my question is ：
why the Eclipse Conlsole shows it again? like follows
```
[RemoteTestNG] detected TestNG version 6.11.0
2017-11-15 10:32:12:981 - [Appium] Welcome to Appium v1.7.1
2017-11-15 10:32:12:984 - [Appium] Non-default server args:
2017-11-15 10:32:12:984 - [Appium]   address: 127.0.0.1
2017-11-15 10:32:12:985 - [Appium]   sessionOverride: true
2017-11-15 10:32:12:985 - [Appium]   log: D:\workspace\EclipseStation\Appium\log\LE67A063101439501510741928005.log
2017-11-15 10:32:12:985 - [Appium]   logTimestamp: true
2017-11-15 10:32:12:985 - [Appium]   defaultCapabilities: {
2017-11-15 10:32:12:986 - [Appium]     udid: LE67A06310143950
2017-11-15 10:32:12:986 - [Appium]   }
2017-11-15 10:32:12:987 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2017-11-15 10:32:12:989 - [Appium]   udid: 'LE67A06310143950'
2017-11-15 10:32:13:043 - [Appium] Appium REST http interface listener started on 127.0.0.1:4723
2017-11-15 10:32:13:540 - [HTTP] --> GET /wd/hub/status {}
2017-11-15 10:32:13:543 - [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2017-11-15 10:32:13:587 - [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
[2017-11-15 18:32:13] [INFO] AppiumServer is started with 127.0.0.1 4723 LE67A06310143950
 2017-11-15 10:32:13:593 - [HTTP] <-- GET /wd/hub/status 200 49 ms - 83 
```

## Environment

* java client build version or git revision if you use some shapshot: 5.0.4
* Appium server version or git revision if you use some shapshot: 1.7.1
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 6.11.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real device

## Details

if u needs more

**Comment by TikhomirovSergey** [comment]
@smallsharp
Sorry for the late response.
It seems this is normal behaviour. Appium local server uses the console output also you may define the log file to write it. 

What the behaviour do you expect?

**Comment by abvijay** [comment]
My eclipse console looks as below..I dont want appium server log in console. I want only sysout in console. Can someone help to resolve it.

[TestNG] Running:
  C:\Users\Vijay\AppData\Local\Temp\testng-eclipse-846001565\testng-customsuite.xml

12:08:39.486 [Forwarding newSession on session null to remote] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
12:08:39.499 [Forwarding newSession on session null to remote] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
12:08:39.499 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:4723][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://localhost:4723][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {}->http://localhost:4723
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:4723
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connection established 127.0.0.1:52959<->127.0.0.1:4723
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 10800000
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request POST /wd/hub/session HTTP/1.1
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /wd/hub/session HTTP/1.1
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/json; charset=utf-8
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 106
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: localhost:4723
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_45)
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /wd/hub/session HTTP/1.1[\r][\n]"
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 106[\r][\n]"
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: localhost:4723[\r][\n]"
12:08:39.514 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
12:08:39.530 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_45)[\r][\n]"
12:08:39.530 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
12:08:39.530 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
12:08:39.530 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 >> "{"desiredCapabilities":{"platformName":"Android","deviceName":"0123456789ABCDEF","platformVersion":"6.0"}}"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Powered-By: Express[\r][\n]"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Methods: GET,POST,PUT,OPTIONS,DELETE[\r][\n]"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Headers: origin, content-type, accept[\r][\n]"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Vary: X-HTTP-Method-Override[\r][\n]"
12:09:07.956 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json; charset=utf-8[\r][\n]"
12:09:07.971 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 206[\r][\n]"
12:09:07.971 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Mon, 05 Mar 2018 06:39:07 GMT[\r][\n]"
12:09:07.971 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
12:09:07.971 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
12:09:07.971 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-0 << "{"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a connected Android device.)","origValue":"Could not find a connected Android device."},"sessionId":null}"
12:09:07.993 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 500 Internal Server Error
12:09:07.993 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << X-Powered-By: Express
12:09:07.993 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Origin: *
12:09:07.993 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Methods: GET,POST,PUT,OPTIONS,DELETE
12:09:07.993 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Headers: origin, content-type, accept
12:09:07.993 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Vary: X-HTTP-Method-Override
12:09:07.994 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/json; charset=utf-8
12:09:07.994 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 206
12:09:07.994 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Mon, 05 Mar 2018 06:39:07 GMT
12:09:07.994 [Forwarding newSession on session null to remote] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
12:09:07.998 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
12:09:08.013 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://localhost:4723] can be kept alive indefinitely
12:09:08.013 [Forwarding newSession on session null to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://localhost:4723][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]
FAILED CONFIGURATION: @BeforeClass setUp
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not find a connected Android device.) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 28.62 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: '10503-INA506PX0T-D', ip: '192.168.45.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/pull/909

**Comment by Jitu1888** [comment]
still logs are coming
2018-09-21 19:05:33 61 IOSDriverAPI [INFO] Checking visibility of type=='XCUIElementTypeButton' AND label=='View Files on iPhone' AND visible == true	 with 	  iOS PREDICATE,  drive disconnected view files on iPhone
[W3C] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C]     at XCUITestDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_module
