### ISSUE TITLE
Android Appium: org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=1}

### ISSUE THREAD

**Issue by lubshilk** [appium/java-client#768]
Hi,

My set-up is:
appium server 1.7.0
java-client 5.0.4
selenium-server-standalone-3.0.0-beta1.jar or selenium-server-standalone-3.7.1.jar (began from 3.0.0beta, received Exception, tried to use newer version - the same exception)

Getting the same exception:
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=1}

I've seen discussion here:
https://discuss.appium.io/t/org-openqa-selenium-webdriverexception-returned-value-cannot-be-converted-to-webelement/18608/30

Suggestion to downgrade jars is not welcomed in my case since I have few other projects that uses selenium driver and cannot downgrade it :(

Please, help

**Comment by ndndien** [comment]
Here is my working version:
Appium 1.7.1
Java-client 5.0.4
Selenium 3.6.0

Hope it helps.

**Comment by TikhomirovSergey** [comment]
@lubshilk 
duplicate #727
Please make sure that you project doesn't depend on some old selenium version

**Comment by lubshilk** [comment]
@TikhomirovSergey
1. I have no problem with the same setting on MacOS with IOS  (I receive the exception on Windows for Android)
2. I don't use POM

So, please, explain, how can I fix it in my case
Thanks

**Comment by lubshilk** [comment]
@ndndien 
Thanks I'll try

Selenium 3.6.0 - do you mean "selenium standalone server" or "selenium serer"?

**Comment by lubshilk** [comment]
@ndndien 
Many thanks, with your setting it works

**Comment by lubshilk** [comment]
re-run it with the newest jars:
Appium 1.7.1
Java-client 5.0.4
Selenium 3.7.1
Exception doesn't happen any more

**Comment by ksurya28995** [comment]
Hi Frnds,

I found the solution, but cant explain how it works. But it works for me as a miracle.

Just add the below line, and magic happens. I dont have any idea how that makes it work..HAHAHA..

capability.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");

**Comment by Vyankat16** [comment]
Hi ksurya,

capability.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");

This is not working for me. I am not understanding where i put this in my script.

Plz help me.

**Comment by ksurya28995** [comment]
Add it in the Desired Capabilities instance before passing the
desiredCapabilityObject to the remotedriver/androiddriver.

**Comment by Vyankat16** [comment]
Hi ksurya,

Can you share your mobile number?
If i need you then i will whatsapp you.
