### ISSUE TITLE
Slow findElements by xPath when there are many elements - IOS

### ISSUE THREAD

**Issue by lubshilk** [appium/java-client#780]
I try to retrieve records from log of an application using the following code:
_logger.info("trying to catch reports lines in log");
List<WebElement> rows = driver.findElements(By.xpath("//*[@type='XCUIElementTypeCell']"));
logger.info(rows.size() + " rows, begin to look for " + this.contactNumberToVerify);_

When there are many elements in application log it takes too long time (almost 2 minutes) to receive the data. In log of automation:
_15:51:55: trying to catch reports lines in log
15:53:50: 60 rows, begin to look for 0557055161_ 

Checked in Appium server log - it took about half-a-minute for responce: 
_15:51:55:322 - info: [HTTP] --> POST /wd/hub/session/cf3d660b-83d0-4be6-ba40-8fec3a72d376/elements {"using":"xpath","value":"//*[@type='XCUIElementTypeCell']"}
.....
15:52:23:911 - info: [debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"E312A718-039B-4E60-9FD5-506CAF8F7577","type":"XCUIElementTypeCell","label":null},{"ELEMENT":"5B81306E-546C-40F7-B73F-DEF37CE1CDCD","type":"XCUIElementTypeCell","label":null},...
2017-12-04 15:52:23:912 - info: [HTTP] <-- POST /wd/hub/session/cf3d660b-83d0-4be6-ba40-8fec3a72d376/elements 200 28589 ms - 5653_

**What takes another 1.5 minutes to pass the data to script?**

In long runs the time to retrieve data becomes longer and longer (it takes up to 8-10 minutes to retrieve about 100 rows from application log)  
[appiumServer60elements.txt](https://github.com/appium/java-client/files/1529976/appiumServer60elements.txt)

## Environment

* java client 5.0.4.
* Appium server v1.7.0
* MAC OS version 10.12.6
* Mobile under test IOS 11 
* Real device

Attached appium server log (relevant part) and picture of application log
![rowsinlog](https://user-images.githubusercontent.com/20837714/33594226-bef606e0-d99b-11e7-9899-ef401046d101.png)

**Comment by mykola-mokhnach** [comment]
It's known wda issue. Nothing we can do about it. Simply [avoid](https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance) using xpath locators.
