### ISSUE TITLE
getting error while instantiating Appium Service Builder - "The given nodeJS file doesn't exist. Given path E:\usr\local\bin\node"

### ISSUE THREAD

**Issue by prateekchawla** [appium/java-client#781]
## Description

I want to run appium on mac triggering it from my windows machine using the Appium Service Builder but i am getting an error.

## Environment

* java client build version or git revision if you use some shapshot: NA
* Appium server version or git revision if you use some shapshot: NA
* Desktop OS/version used to run Appium if necessary: Mac
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Appium CLI
* Mobile platform/version under test: NA
* Real device or emulator/simulator: Real device

## Details

The exception I am getting is "The given nodeJS file doesn't exist. Given path E:\usr\local\bin\node" which indicates that it is finding nodeJS on the windows itself as it is giving a path on E drive.

## Code To Reproduce Issue [ Good To Have ]

<script src="https://gist.github.com/prateekchawla/7c449af6e71c822129c0a976e583c243.js"></script>

## Ecxeption stacktraces

<script src="https://gist.github.com/prateekchawla/7dd3056f5edda7de7661cdd44938be50.js"></script>

## Link to Appium logs

NA

**Comment by TikhomirovSergey** [comment]
Something weird. It looks like windows file path...

**Comment by prateekchawla** [comment]
Thanks @TikhomirovSergey

**Comment by prateekchawla** [comment]
@TikhomirovSergey  How to explicitly give the chrome driver port to the Appium service builder while starting the appium service.
Currently it starts chrome driver on the port 9515 , and I need to run appium tests on parallel android devices.

**Comment by saikrishna321** [comment]
@prateekchawla please refer [doc](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md) for parallel testing.
