### ISSUE TITLE
Support for MultiApp testing XCUI 

### ISSUE THREAD

**Issue by saikrishna321** [appium/java-client#782]
With respect to PR https://github.com/appium/appium-xcuitest-driver/pull/576 we can get this support on client once its merged

**Comment by TikhomirovSergey** [comment]
I suppose it is the candidate for the next build.

**Comment by mykola-mokhnach** [comment]
do n't be so fast - these endpoints  are anyway available via executeScript "mobile" interface and they should be tested properly first before creating high-level wrappers for them

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach of cource

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/pull/824
