### ISSUE TITLE
UIAutomator2: Driver get or navigate to throw exception: Proxy error: Could not proxy command to remote server. Original error: 404 - undefined

### ISSUE THREAD

**Issue by rosolko** [appium/java-client#787]
## Description

I'm trying to navigate by deeplink using `get` or `navigate.to` mthods but got en error:  `Could not proxy command to remote server. 404 - undefined.`

## Environment

* java client build version or git revision if you use some shapshot: 5.0.4
* Appium server version or git revision if you use some shapshot: 1.7.1
* Desktop OS/version used to run Appium if necessary: Mac OS X 10.13.2
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v9.2.1
* Mobile platform/version under test: android 6.0 API 23
* Real device or emulator/simulator: emulator

## Details

Work well with `desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.APPIUM);`

## Code To Reproduce Issue [ Good To Have ]

1. Set driver creation capability `desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);`
2. Use method call in test:
`driver.get(deep://link)`
or
`driver.navigate().to(deep://link/to/some/part/of/app)`

## Link to Appium logs and Exception stacktraces
[gist](https://gist.githubusercontent.com/rosolko/570ec30968ec1aef0cee341f3c96da69/raw/c1729fa4b167441ffee44925ea46d6ca7bc0b8df/ex)

**Comment by mykola-mokhnach** [comment]
Are you in webview context?

**Comment by rosolko** [comment]
No. Android application.

**Comment by mykola-mokhnach** [comment]
This endpoint is only available in webview context

**Comment by rosolko** [comment]
@mykola-mokhnach Related to this [bug](https://github.com/appium/appium/issues/5209) it should work with `driver.get(url)` command. I don't need to work with webview to navigate by deep link in format `scheme://link`

**Comment by rosolko** [comment]
@mykola-mokhnach 
Can you please clarify:

Related to this bug: https://github.com/appium/appium/issues/5209

When I using `Appium` as automation name I don't need to work with webview to navigate by deep link in format `scheme://link` by `driver.get(url)`
And it's work as designed.

But it won't work with `UIAutomator2` as automation name.

Thanks.

**Comment by mykola-mokhnach** [comment]
@rosolko I'll check it.
