### ISSUE TITLE
OverWriteError

### ISSUE THREAD

**Issue by fhlkm** [appium/java-client#789]
## Description
Issue:
Error:(144, 30) java: findElements(org.openqa.selenium.By) in io.appium.java_client.AppiumDriver cannot override findElements(org.openqa.selenium.By) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>

Steps:
Just download the appp and When I try to Run "io.appium.java_client.appium.AndroidTest"

## Environment
java version: 1.8.0_65
Windows: Windows 7 Professionl
Node: 5.2.0
Appium: v1.7.1
Mobile: Samsung S6
Android OS: 7.0
Tools: Intellij IDE 2017.1.5

## Details

Please provide more details, if necessary.
C:\git\Appium-java-client\src\main\java\io\appium\java_client\AppiumDriver.java
Error:(144, 30) java: findElements(org.openqa.selenium.By) in io.appium.java_client.AppiumDriver cannot override findElements(org.openqa.selenium.By) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(148, 30) java: findElements(java.lang.String,java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElements(java.lang.String,java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(152, 30) java: findElementsById(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsById(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(156, 20) java: findElementsByLinkText(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByLinkText(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(160, 20) java: findElementsByPartialLinkText(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByPartialLinkText(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(164, 20) java: findElementsByTagName(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByTagName(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(168, 20) java: findElementsByName(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByName(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(172, 20) java: findElementsByClassName(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByClassName(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(176, 20) java: findElementsByCssSelector(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByCssSelector(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(180, 20) java: findElementsByXPath(java.lang.String) in io.appium.java_client.AppiumDriver cannot override findElementsByXPath(java.lang.String) in org.openqa.selenium.remote.RemoteWebDriver
  return type java.util.List<T> is not compatible with java.util.List<org.openqa.selenium.WebElement>
C:\git\Appium-java-client\src\main\java\io\appium\java_client\MobileElement.java
Error:(45, 42) java: findElements(org.openqa.selenium.By) in io.appium.java_client.MobileElement cannot override findElements(org.openqa.selenium.By) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(49, 42) java: findElements(java.lang.String,java.lang.String) in io.appium.java_client.MobileElement cannot override findElements(java.lang.String,java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(53, 42) java: findElementsById(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsById(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(57, 32) java: findElementsByLinkText(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByLinkText(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(61, 32) java: findElementsByPartialLinkText(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByPartialLinkText(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(65, 32) java: findElementsByTagName(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByTagName(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(69, 32) java: findElementsByName(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByName(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(73, 32) java: findElementsByClassName(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByClassName(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(77, 32) java: findElementsByCssSelector(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByCssSelector(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>
Error:(81, 32) java: findElementsByXPath(java.lang.String) in io.appium.java_client.MobileElement cannot override findElementsByXPath(java.lang.String) in org.openqa.selenium.remote.RemoteWebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/blob/master/docs/Note-for-developers.md#compiler
