### ISSUE TITLE
lockDevice() not working for iOS 10+ devices

### ISSUE THREAD

**Issue by sanojqa** [appium/java-client#792]
lockDevice() not working for iOS 10+ devices

I used following settings,

Appium: 1.7.1
java-client: 5.0.4
iOS version 10.0.1

Code used for execution:
===================
 ((LocksIOSDevice) driver).lockDevice(Duration.ofSeconds(20));

((IOSDriver<?>) driver).lockDevice(Duration.ofSeconds(4));

In above executions I got following errors:
===============================
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'Neethus-Mac-mini.local', ip: '172.16.0.119', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: com.rapidvalue.accurate.base.AutomationBase$1
Capabilities {automationName: XCUITest, browserName: , bundleId: com.hungama.myplay, databaseEnabled: false, deviceName: iPhone, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: , noReset: true, platform: MAC, platformName: MAC, platformVersion: 10.0.1, realDeviceLogger: /usr/local/lib/node_modules..., takesScreenshot: true, udid: c1ae954995c20ec904a00c3eafd..., webStorageEnabled: false}
Session ID: 54d8c72a-961e-4466-aad7-db2e917f4a8c

**Comment by mykola-mokhnach** [comment]
This is known and is stated in the documentation. There is a fix coming soon though.
