### ISSUE TITLE
Android: Unable to switch into WebView.

### ISSUE THREAD

**Issue by rosolko** [appium/java-client#796]
## Description

I'm tryimg to switch into webview on android activity that contains it but got an error.

## Environment

* java client build version or git revision if you use some shapshot: `5.0.4`
* Appium server version or git revision if you use some shapshot: `1.7.1`
* Desktop OS/version used to run Appium if necessary: `Mac OS X 10.13.2 `
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: `v9.3.0`
* Mobile platform/version under test: `Android 6`
* Real device or emulator/simulator: `Emulator`

## Details

I'm located in activity that contains webview because command return me right context.
Command: `final Set contextHandles = androidDriver.getContextHandles();`
Result: `[NATIVE_APP, WEBVIEW_com.client.android.stage]`

I got installed latest Chrome and Chrome WebView on emulator.

## Code To Reproduce Issue [ Good To Have ]

After I'm trying to switch into webview context by:
`androidDriver.context("WEBVIEW_com.client.android.stage");`
And got error:
```java
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Unable to automate Chrome version because it is too old for this version of Chromedriver.
[Chromedriver] Please see 'https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/chromedriver.md'
[Chromedriver] Error: session not created exception: Chrome version must be >= 58.0.3029.0
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.13.2 x86_64)
```

## Exception stacktraces and appium logs
[Gist](https://gist.github.com)

**Comment by mykola-mokhnach** [comment]
You must use an appropriate driver version as it is described in https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/chromedriver.md

Closed as not an issue.

**Comment by rosolko** [comment]
@mykola-mokhnach Link is dead. I assume that [this](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md) is a new one. I download `2.16` version and set path to it with `new AppiumServiceBuilder().withArgument(AndroidServerFlag.CHROME_DRIVER_EXECUTABLE, "/Users/arasolka/Downloads/chromedriver")`. But no luck there. I'm also tied `2.20` version and it's also don't work.

**Comment by mykola-mokhnach** [comment]
What is the webview version?

**Comment by rosolko** [comment]
WebView `60.0.3112.107`
Chrome `63.0.3239.111`

**Comment by mykola-mokhnach** [comment]
> [Chromedriver] Error: session not created exception: Chrome version must be >= 58.0.3029.0

This error says that webview version should be older. Are you sure it's `60.0.3112.107`?

**Comment by rosolko** [comment]
<img width="480" alt="screen shot 2017-12-22 at 13 56 52" src="https://user-images.githubusercontent.com/11458319/34295748-fef39f64-e71f-11e7-860e-2f120951bd8b.png">

**Comment by mykola-mokhnach** [comment]
Which error do you see in the log if the most recent chromedriver is used?

**Comment by rosolko** [comment]
```

**Comment by mykola-mokhnach** [comment]
Most likely your application under test requires lower version of the chromedriver. I'd download several chromedriver binaries and try them all until the match is found.

**Comment by rosolko** [comment]
@mykola-mokhnach 
Sorry for long update.

From `2.34` to `2.21` I've got an error related to too old chrome version.

After `2.20` and and below my tests stuck on: 
`androidDriver.context("WEBVIEW_com.client.android.stage")`
And after long time fails with:
```java
[MJSONWP] Encountered internal error running command: Error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.13.2 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:197:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.13.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'mbp.local', ip: 'fe80:0:0:0:8bd:a124:e121:a6de%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_152'
Driver info: io.appium.java_client.android.AndroidDriver
```

Command `androidDriver.getContextHandles()` returns me:
`[NATIVE_APP, WEBVIEW_com.client.android.stage]`

**Comment by mykola-mokhnach** [comment]
> Build info: version: '3.8.1'

This might also be the problem. Selenium 3.8+ API requires the proxy to fully support W3C standards, which is not the case for Appium yet. Try to downgrade Selenium.

**Comment by rosolko** [comment]
I've downgrade selenium to 3.6.0 version but it isn't help.
Got the same error:
```java
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.13.2 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:197:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.13.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'mbp.local', ip: 'fe80:0:0:0:8bd:a124:e121:a6de%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_152'
Driver info: io.appium.java_client.android.AndroidDriver
```

**Comment by mykola-mokhnach** [comment]
then I have no more suggestions. Google says it is still a problem of wrong driver version: https://stackoverflow.com/questions/21001652/chrome-driver-error-using-selenium-unable-to-discover-open-pages/38700776#38700776
