### ISSUE TITLE
Driver returns "null" when I use the java-client5.0.4

### ISSUE THREAD

**Issue by darkmanno6** [appium/java-client#801]
## Description
```java
androidDriver = new AndroidDriver<>(new URL("http://" + appiumHost + ":" + port + "/wd/hub"), capabilities);
```
Driver returns "Android: null" when I use the java-client 5.0.4,  Please see details bellow.

## Environment

* java client : v5.0.4
* selenium-java : v3.5.3
* Appium server : v1.7.1
* Desktop OS/version : Mac OSX 10.12
* Node.js version : v6.12.2
* Mobile platform/version under test: Android OS v5.1
* Real device or emulator/simulator: real device

## Details
I upgrate `java-client` from `5.0.0` to `5.0.4` today ,  and run the test locally(start appium server locally and run the test script locally). It's run all ok!
However , when I use grid mode to run the test it throws the Exception:
```log
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'Mac', ip: 'fe80:0:0:0:423:d00:9c83:6ce1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: AndroidDriver
Capabilities [{appPackage=com.aicai.axd, deviceScreenSize=1080x1920, networkConnectionEnabled=true, recreateChromeDriverSessions=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=KZZLQSPNKZGEVWK7, platform=LINUX, deviceUDID=KZZLQSPNKZGEVWK7, appActivity=com.aixuedai.axd.common.activity.SplashActivity, desired={appPackage=com.aicai.axd, appActivity=com.aixuedai.axd.common.activity.SplashActivity, recreateChromeDriverSessions=true, noReset=true, newCommandTimeout=300, platformVersion=4.4, unicodeKeyboard=true, platformName=Android, udid=KZZLQSPNKZGEVWK7, deviceName=KZZLQSPNKZGEVWK7, resetKeyboard=true}, newCommandTimeout=300, platformVersion=5.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=OPPO R7, unicodeKeyboard=true, platformName=Android, udid=KZZLQSPNKZGEVWK7, deviceManufacturer=OPPO, resetKeyboard=true}]
Session ID: 7320015b-3ff6-4a03-8e21-df34f471c205

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:662)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.getSize(RemoteWebDriver.java:905)
```
then I  created the breakpoint on the code 
```java
androidDriver = new AndroidDriver<>(new URL("http://" + appiumHost + ":" + port + "/wd/hub"), capabilities);
````
 and debug the code . I found the driver returned strangely , see the pic below :

![image](https://user-images.githubusercontent.com/8080262/34708882-cc0323c0-f54f-11e7-9039-e765d519959a.png)

the driver displayed the "Android: null" ,but the driver object is not NULL, so I think it leads to my test fail.

I retryed the java-client 5.0.0 , the driver shows 
![image](https://user-images.githubusercontent.com/8080262/34709054-82826804-f550-11e7-82eb-9411bf95dd19.png)
and it ran all ok.

**So the problem is that while running the test locally (java-client 5.0.4), the driver returns "Android:null " but could run ok, while running the test using grid (java-client 5.0.4), the driver also returns "Android:null " and it leads to the failing test.**

hope someone can solve the problem ., thx.

**Comment by saikrishna321** [comment]
Please provide server logs

**Comment by fdPoornima** [comment]
faced the same issue with 5.0.4 and moved back to 5.0.0, which works. Thanks @darkmanno6  for posting

**Comment by shizhongping** [comment]
This bug will defeat polymorphism. Stupid.
