### ISSUE TITLE
Getting BadParametersError on Mac Appium Server when trying to launch app from windows client

### ISSUE THREAD

**Issue by nehav1** [appium/java-client#813]
## Description
Not able to launch application on Mac Appium server using windows client

## Environment
Java client version: 6.0.0 Beta 2
Appium server 1.5.3
Mac OS 10.11
selenium server 3.3.1
selenium java 3.8.1

## Details
org.openqa.selenium.WebDriverException: Unable to parse remote response: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id"]} and you sent ["desiredCapabilities","capabilities"]
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'IMPETUS-NL168', ip: '192.168.221.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: IOSDriver

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs
BadParametersError

**Comment by saikrishna321** [comment]
@nehav1 can you please use the latest appium-server, that would fix this issue
