### ISSUE TITLE
java.lang.NoClassDefFoundError: io/appium/java_client/FindsByAccessibilityId

### ISSUE THREAD

**Issue by mithuns** [appium/java-client#815]
## Description

I am trying to debug a project in eclipse that uses 5.0.1 version of java-client.
But it keeps throwing this class not found exception.

## Environment

* java client build version : 5.0.1
* Appium server version : N/A
* Desktop OS/version used to run Appium if necessary: N/A
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: N/A
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: real device windows 10- eclipse (Version: Mars.2 Release (4.5.2))

## Details

I am using serenity-core , which pulls in java-client transitively, I have also tried to directly pull java-client under scope - test and runtime, but that didnt help either. 

## Code To Reproduce Issue [ Good To Have ]
This is what my AcceptanceTests looks like
https://gist.github.com/mithuns/40e163a4a2d3df92c4182f702774b2b5

## Ecxeption stacktraces

https://gist.github.com/mithuns/e86b378c934ad5611770a6ed3d497dfd

## Link to Appium logs

N/A

**Comment by mithuns** [comment]
Anyone ? Any ideas ? 
Is it possible this class is packaged with some other api, if I use IntelliJ or some other IDE ?

**Comment by TikhomirovSergey** [comment]
v5.0.1 is outdated
