### ISSUE TITLE
Appium 1.8.0-beta+Java 6.0.0-beta2: Unable to convert: Locator Strategy 'css selector' is not supported for this session

### ISSUE THREAD

**Issue by vjmaiky** [appium/java-client#818]
## Description

I switched to appium 1.8.0-beta. I changed a bit the capabilities format in order to be able to start all setup. Setup starts ok but it crashes when tries to identify any element:

```
Jan 24, 2018 12:06:01 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.id: Setup Later)
org.openqa.selenium.json.JsonException: Unable to convert: Locator Strategy 'css selector' is not supported for this session
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
```

## Environment
- Java library: 6.0.0-BETA2
- Appium version (or git revision) that exhibits the issue: 1.8.0-beta
- Last Appium version that did not exhibit the issue (if applicable): 1.7.2
- Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
- Node.js version (unless using Appium.app|exe): 8.5.0
- Mobile platform/version under test: iOS 10.3.3
- Real device or emulator/simulator: Real Device (iphone 6+)

## Details
Problem was initially posted to Appium issue tracker, but Mykola redirected me with this issue here.
Original bug:
https://github.com/appium/appium/issues/10055#issuecomment-360137043

**Comment by SrinivasanTarget** [comment]
@vjmaiky Its fixed in latest client version. Can you give a try?
