### ISSUE TITLE
java.util.HashMap cannot be cast to org.openqa.selenium.WebElement

### ISSUE THREAD

**Issue by telangn** [appium/java-client#826]
## Description
@SrinivasanTarget @mykola-mokhnach @TikhomirovSergey @jlipps
@saikrishna321 

Once appium starts up and begins to find and use element id's in the mobile app, an error is thrown:

```
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=1}
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.openqa.selenium.WebElement
```
Appium Log files: https://gist.github.com/telangn

## Environment

Ubuntu 16 OS
```
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.4.0</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.0.0-BETA2</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

```
## Details

GIST for appium log files:

https://gist.github.com/telangn

## Link to Appium logs

https://gist.github.com/telangn

**Comment by telangn** [comment]
@yefankongge is there a fix? What is the fix?

**Comment by telangn** [comment]
This issue has been fixed. Can be closed.

**Comment by fdPoornima** [comment]
@telangn  : what is the fix for this? which library should be updated?

**Comment by telangn** [comment]
This was a while ago, so I can't remember, but I think it had something to do with version compatibility between appium and selenium. Try messing with different versions of them.

**Comment by otaviolandim** [comment]
@fdPoornima can you send me how steps and which version worked for you?

**Comment by tutkuefe** [comment]
What is the solution ? @otaviolandim  @telangn @fdPoornima

**Comment by mahima-ranium** [comment]
Thanks for your answer it helped me @telangn
