### ISSUE TITLE
Issue when Swiping vertically on an Element.

### ISSUE THREAD

**Issue by WasiqB** [appium/java-client#827]
## Description

It is required to move finger from top border of element downwards. However it is not working as expected when starting position of finger is on the top border of the element. App used for testing this scenario can be found [here](https://github.com/saikrishna321/VodQaAdvancedAppium) named **VodQA.apk**.

## Environment

* java client build version or git revision if you use some shapshot: 5.0.4
* Appium server version or git revision if you use some shapshot: 1.7.2
* Desktop OS/version used to run Appium if necessary: Mac OSX 10.12
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.9.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real

## Details

Screen Size = [1080, 1920]
Element bounds = [0, 348][1080, 1920]

**Not Working as expected (Moves finger from bottom upwards):**
Start Position on Element = [540, 0]
End Position on Element = [540, 393]

**Working as expected (Moves finger from top downwards):**
Start Position on Element = **[540, 5]**
End Position on Element = [540, 393]

## Code To Reproduce Issue [ Good To Have ]

```java
    // In Vertical Swipe View.
    final MobileElement list = driver.findElementByAccessibilityId ("listview");
    new TouchAction (driver).press (list, 540, 0)
	.waitAction (Duration.ofSeconds (2))
	.moveTo (list, 540, 393)
	.release ()
	.perform ();
```

## Exception stacktraces
```terminal
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element bounds: [0,348][1080,1920]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element bounds: [0,348][1080,1920]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Swiping from [x=540.0, y=1134.0] to [x=540.0, y=741.0] with steps: 56
```

**Comment by SrinivasanTarget** [comment]
@WasiqB please check this one https://github.com/saikrishna321/VodQaAdvancedAppium/blob/master/src/test/java/com/appium/gesture/GestureTest.java#L97
