### ISSUE TITLE
Appium version 1.8.0beta - uiautomator2 does not wait for the element to be visible condition where as uiautomator running fine.

### ISSUE THREAD

**Issue by shagupta92042** [appium/java-client#830]
## Description

uiautomator2 does not wait for the element to be visible condition where as uiautomator running fine. 

## Environment

* java client build version or git revision if you use some shapshot: 5.0.0-BETA9
* Appium server version or git revision if you use some shapshot: 1.8.0 beta
* Desktop OS/version used to run Appium if necessary: Widows 7
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.9.4
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Nexus 6S

## Details

I am running my android device (8.1) test cases on an android app using selenium and appium which is currently using the uiautomator and it is running fine as i am using explicit wait(WebDriverWait ) but when i switch to uiautomator2 then it does not wait for the elements to be visible and test cases starts failing as it waits for 0ms seconds . Please find the appium logs of uiautomator and uiautomator2 execution and suggest me a solution for the same.

## Code To Reproduce Issue [ Good To Have ]

	public ElementConditions(WebDriver driver) {
		this.driver = driver;
		wait = new WebDriverWait(driver, 60);
	}

	public void elementToBeClickable(WebElement element) {
		wait.until(ExpectedConditions.elementToBeClickable(element));
	}

	public void visibilityOfElement(WebElement element) {

		wait.until(ExpectedConditions.visibilityOf(element));
	}

## Link to Appium logs

https://gist.github.com/shagupta92042/ac140ac6b81375eb838d27eebc0ff0bc

**Comment by mykola-mokhnach** [comment]
Your xpath locator does not look correct. The `index` property purpose is the internal indexing and it should not be used for lookup. Also UIA2 does not have it.

**Comment by shagupta92042** [comment]
@mykola-mokhnach but it works perfectly for uiautomator  and when i use thread.sleep for uiautomator2 then it works fine and it is able to identify the elements then . The only problem with the time as it does not wait.

**Comment by shagupta92042** [comment]
@mykola-mokhnach : Could you please help here as i am stuck ?

**Comment by kiragengis** [comment]
Hi, I am having the same problem. But with Thread.Sleep works fine.


**Environment:**
* Windows 10
* Visual Studio 2017
* C#
* NuGet packages:
*    Appium.WebDriver
*    Selenium.Support
*    Selenium.WebDriver
*    DotNetSeleniumExtras.WaitHelpers [this is optional and I used it to try the ExpectedConditions because on the last Selenium are deprecated]

`[TestMethod]
        public void TestingCostco()
        {
            //SunPass
            //

            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("appium-version", "1.0");
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("deviceName", "b4e94f8b");
            capabilities.SetCapability("platformVersion", "7.0");
            capabilities.SetCapability("appPackage", "com.costco.app.android");
            capabilities.SetCapability("appActivity", "com.costco.app.android.LaunchActivity");
            
            //---> Y tried with AndroidDriver and AppiumDriver
            driverAppium = new RemoteWebDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);

            //---> I tried this way and TimeSpan.FromSeconds(30)
            WebDriverWait wait = new WebDriverWait(driverAppium, new TimeSpan(0, 0, 30));

          //---> This way doesn't work  wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(By.XPath("//android.widget.ImageButton[@content-desc='Open navigation drawer']")));
            driverAppium.FindElement(By.XPath("//android.widget.ImageButton[@content-desc='Open navigation drawer']")).Click();
            driverAppium.FindElementByXPath("//android.widget.CheckedTextView[@text='Membership']").Click();

            //---> This way doens't wait either
            var element = wait.Until(condition =>
            {
                try
                {
                    //---> Here fails the first time.
                    var elementToBeDisplayed = driverAppium.FindElementByXPath("//android.view.View[@text='Costco Gold Star Membership Card Gold Star']");
                    return elementToBeDisplayed != null;
                }
                catch (StaleElementReferenceException)
                {
                    return false;
                }
                catch (NoSuchElementException)
                {
                    return false;
                }
            });

            
            driverAppium.FindElementByXPath("//android.view.View[@text='Costco Gold Star Membership Card Gold Star']").Click();

        }`

**Comment by SrinivasanTarget** [comment]
@shagupta92042 please raise questions in discuss forum.
