### ISSUE TITLE
6.0.0-BETA3 - PLATFORM_NAME cannot be resolved

### ISSUE THREAD

**Issue by telangn** [appium/java-client#844]
## Description
@SrinivasanTarget @mykola-mokhnach @TikhomirovSergey @jlipps
@saikrishna321

Going from BETA2 to BETA3, using the code below is giving me an issue, whereas in BETA2 it did not -

```
dc.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.ANDROID);

```
PLATFORM_NAME **cannot be resolved** is what my IDE is throwing now.

My only options are PLATFORM or PLATFORM_VERSION.
I have tried them and I get a console error that PLATFORM_NAME should be used and it couldn't start. But I cannot choose it when programming. _Which one do I choose now?_

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 63 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'ninad-Gazelle', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-36-generic', java.version: '1.8.0_151'
Driver info: driver.version: AppiumDriver
```

_Also, What is the argument I pass as the Android OS?_ (instead of Platform.ANDROID)

## Environment

io.appium - java-client - 6.0.0-BETA3
Ubuntu 16
Eclipse IDE

**Comment by saikrishna321** [comment]
Can you share your appium server logs

**Comment by TikhomirovSergey** [comment]
@telangn 
Sorry for the late respnonse. 
>Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
I am seing this string and I suspect a dependency conflict there. Two last beta versions depend on Selenium 3.9.1. Could you update your project?

Also beta3 has some breaking changes which require server >= 1.8.0-beta3? Which server version do you use?

**Comment by telangn** [comment]
Hi @TikhomirovSergey @saikrishna321 ,
below are all the Selenium and Appium dependencies I have in my pom.xml currently.
Am I missing some dependencies? 
What should I change? 
Many thanks!

**org.seleniumhq.selenium**
selenium-java
**3.4.0**

**io.appium**
java-client
**6.0.0-BETA3**

**Comment by SrinivasanTarget** [comment]
@telangn Remove Selenium dependency from your pom.xml and use the latest version of java client which is `6.0.0-BETA4` and do use the latest beta of appium server too. If you still face any issues, feel free to give us the server logs.

**Comment by telangn** [comment]
Can you give me the command line instruction to upgrade my appium server to the latest? @saikrishna321 @TikhomirovSergey

**Comment by SrinivasanTarget** [comment]
@telangn 
````
npm uninstall -g appium
npm install -g appium@beta

**Comment by telangn** [comment]
Thank you so much! Everything works now! 
This issue can be closed.
