### ISSUE TITLE
Replacement for Deprecated Press, Moveto Functions in 6.0.0-BETA2?

### ISSUE THREAD

**Issue by Addy-07** [appium/java-client#847]
## Description
I am trying to do the functionality with the - Press, and -moveto() touchaction class in the method. However, its display an error "these 2 were deprecated" and the method waitAction(WaitOptions) in the type TouchAction is not applicable for the arguments (int)

Saw that AppiumDriver press and MobileElement moveto functions were marked deprecated, is there a replacement for it? Or a better alternative?

## Environment

* java client build version - 6.0.0-BETA4 :
* Appium server version 1.7.2:
* Desktop OS/version windows 10:
* Mobile platform/version 7.1.1:
* Real device or emulator/simulator: emulator

## Code To Reproduce Issue [ Good To Have ]

Unable to use the swipe(), longPress and scrollToExact() in TouchAction class.
Anupam · 5 days ago
Hi Rahul,

I am trying to do the functionality with the - swipe() and - scrollToExact() touchaction class in the method. However, its display an error "these 2 were deprecated" and the method waitAction(WaitOptions) in the type TouchAction is not applicable for the arguments (int)

I really do not understand why it is not working (and is the lecture wrong?)

Could you please help me with this?

------------------------------------

working On:

- java-client-6.0.0-BETA4 

- selenium-3.10.0

Code:----------------------------------------------

import java.net.MalformedURLException;
import java.util.concurrent.TimeUnit;

import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;

public class swipedemo extends base{

public static void main(String[] args) throws MalformedURLException {
// TODO Auto-generated method stub
     AndroidDriver<AndroidElement> driver=capabilities();
     driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
     
     TouchAction t=new TouchAction(driver);
     driver.findElementByXPath("//android.widget.TextView[@text='Views']").click();
     driver.findElementByXPath("//android.widget.TextView[@text='Date Widgets']").click();
     driver.findElementByAndroidUIAutomator("text(\"2. Inline\")").click();
     driver.findElementByXPath("//*[@content-desc='9']").click();

              t.press(driver.findElementByXPath("//*[@content-desc='15']")).waitAction(2000).moveTo(driver.findElementByXPath("//*[@content-desc='45']")).release().perform();

}

}

**Comment by SrinivasanTarget** [comment]
@Addy-07 Refer [this](https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/TouchAction.java) and [this](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidTouchTest.java)

**Comment by anu-shreya** [comment]
AndroidTouchTest and TouchAction is deprecated in 9.0.0

**Comment by valfirst** [comment]
@anu-shreya https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#touch-actions
