### ISSUE TITLE
Android UiSelector with childSelector not returning multiple items

### ISSUE THREAD

**Issue by bennid** [appium/java-client#848]
The following bug wasn't re-opened... but hitting this with Appium 1.7.2 server.

https://github.com/appium/java-client/issues/150

Appium log for the search:

> 2018-03-19 13:00:37:438 - [HTTP] --> POST /wd/hub/session/7e1ae00e-e12d-4f58-85b7-6c4f9a13f0a7/elements {"using":"-android uiautomator","value":"new UiSelector().resourceId(\"com.tripadvisor.tripadvisor.mainline:id/poi_tours_list\").childSelector(new UiSelector().className(\"android.widg
et.LinearLayout\"))"}
2018-03-19 13:00:37:438 - [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["-android uiautomator","new UiSelector().resourceId(\"XXXX:id/TEST_ID\").childSelector(new UiSelector().className(\"android.widget.LinearLayout\"))","7e1ae00
e-e12d-4f58-85b7-6c4f9a13f0a7"]
2018-03-19 13:00:37:439 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-03-19 13:00:37:439 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-03-19 13:00:37:439 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-03-19 13:00:37:440 - [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8593/wd/hub/session/f62fe65a-ecc6-4414-b113-7b56b6848082/elements] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"XXXX:id/TEST_ID\").childSelector(new UiSelector().className(\"android.widget.LinearLayout\"))","context":"","multiple":true}
2018-03-19 13:00:38:317 - [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"f62fe65a-ecc6-4414-b113-7b56b6848082","status":0,"value":[{"ELEMENT":"2f6f8771-c261-411e-b04d-74f1f4528f89"}]}
2018-03-19 13:00:38:317 - [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"2f6f8771-c261-411e-b04d-74f1f4528f89"}]
2018-03-19 13:00:38:318 - [HTTP] <-- POST /wd/hub/session/7e1ae00e-e12d-4f58-85b7-6c4f9a13f0a7/elements 200 880 ms - 124 

My DOM actually has two of the children LinearLayouts (similar to all the complaints in issue 150)

![childselectorimage](https://user-images.githubusercontent.com/502340/37597868-fef6e0c2-2b56-11e8-8695-2d2ac4f86f48.png)

**Comment by KazuCocoa** [comment]
- Are you using `uiautomator2`?
    - It's helpful to attach some configuration related logs as well.
- Could you try the `uiautomator` request using Espresso and check the results?
    - Since I have an experience I couldn't get some element via `UiSelector()` on Espresso even it shows on the `monitor` tool.

**Comment by bennid** [comment]
Yes, using UiAutomator2.  Capabilities are as follows:

[{app=https://TEST_URL.com/assets/files/up/testapp-180326014.apk, appPackage=XXXX, clearSystemFiles=true, platformType=Phone, deviceName=ANY, platform=ANDROID, appActivity=TEST_ACTIVITY, newCommandTimeout=45, platformVersion=ANY, automationName=UIAutomator2, browserName=, unicodeKeyboard=true, platformName=Android, resetKeyboard=true}]

**Comment by SrinivasanTarget** [comment]
@bennid Can you please check in app's page source as well once? I will try reproducing this at my end.

**Comment by bennid** [comment]
Here's the DOM (removing IDs to preserve the innocent)

                              <android.support.v7.widget.RecyclerView bounds="[36,1165][1044,1752]" checkable="false" checked="false" class="android.support.v7.widget.RecyclerView" clickable="false" content-desc="CommerceView" enabled="true" focusable="true" focused="false" index="2" instance="2" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/TEST_ID" scrollable="false" selected="false" text="">
                                 <android.widget.LinearLayout bounds="[36,1201][1044,1376]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" instance="7" long-clickable="false" package="XXXX" password="false" resource-id="" scrollable="false" selected="false" text="">
                                    <android.widget.LinearLayout bounds="[36,1201][774,1376]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" instance="8" long-clickable="false" package="XXXX" password="false" resource-id="" scrollable="false" selected="false" text="">
                                       <android.widget.TextView bounds="[36,1201][774,1307]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" instance="10" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/TITLE" scrollable="false" selected="false" text="Title 1"/>
                                       <android.widget.TextView bounds="[36,1319][254,1376]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" instance="11" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/PRICE" scrollable="false" selected="false" text="from $1.00"/>
                                    </android.widget.LinearLayout>
                                    <android.widget.Button bounds="[798,1216][1044,1360]" checkable="false" checked="false" class="android.widget.Button" clickable="true" content-desc="" enabled="true" focusable="true" focused="false" index="1" instance="1" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/MORE_INFO" scrollable="false" selected="false" text="More Info"/>
                                 </android.widget.LinearLayout>
                                 <android.widget.LinearLayout bounds="[36,1451][1044,1626]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" instance="9" long-clickable="false" package="XXXX" password="false" resource-id="" scrollable="false" selected="false" text="">
                                    <android.widget.LinearLayout bounds="[36,1451][774,1626]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" instance="10" long-clickable="false" package="XXXX" password="false" resource-id="" scrollable="false" selected="false" text="">
                                       <android.widget.TextView bounds="[36,1451][774,1557]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" instance="12" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/TITLE" scrollable="false" selected="false" text="Title 2"/>
                                       <android.widget.TextView bounds="[36,1569][254,1626]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" instance="13" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/PRICE" scrollable="false" selected="false" text="from $2.00"/>
                                    </android.widget.LinearLayout>
                                    <android.widget.Button bounds="[798,1466][1044,1610]" checkable="false" checked="false" class="android.widget.Button" clickable="true" content-desc="" enabled="true" focusable="true" focused="false" index="1" instance="2" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/MORE_INFO" scrollable="false" selected="false" text="More Info"/>
                                 </android.widget.LinearLayout>
                                 <android.widget.TextView bounds="[36,1701][1044,1752]" checkable="false" checked="false" class="android.widget.TextView" clickable="true" content-desc="" enabled="true" focusable="false" focused="false" index="2" instance="14" long-clickable="false" package="XXXX" password="false" resource-id="XXXX:id/SEE_MORE" scrollable="false" selected="false" text="See More"/>
                              </android.support.v7.widget.RecyclerView>

**Comment by KazuCocoa** [comment]
@bennid 
As I wrote in the previous comment, I wonder if the behaviour is Appium side issue or UiAutomator side issue.

> Could you try the uiautomator request using Espresso and check the results?

Do you have an opportunity to conduct the uiselector operation on Espresso? Since `new UiSelector().resourceId("XXXX:id/TEST_ID").childSelector(new UiSelector().className("android.widget.LinearLayout"))` is [Android's UiSelector](https://developer.android.com/reference/android/support/test/uiautomator/UiSelector.html) and if the issues comes from it, we can't touch in Appium side.

---

#150 is too old, I guess `uiautomator1` is original, and I can see [C#](https://github.com/appium/java-client/issues/150#issuecomment-327098399) stuff as well. So, I predict this issue is uiautomator side issue though. (If so, we should report it to Google)
