### ISSUE TITLE
Swipe is not working in iOS 11 using Touch actions appium

### ISSUE THREAD

**Issue by appiumtesterios** [appium/java-client#849]
## Description

Vertical swipe in iOS 11 is not working.
Code to reproduce the issue:
 Dimension size = driver.manage().window().getSize();
 int starty = (int) (size.height * 0.80);
 int endy = (int) (size.height * 0.20);
 int startx = size.width / 2;
      
 TouchAction tAction = new TouchAction(driver);
tAction.press(startx , endy).waitAction().moveTo(startx , starty).release().perform();

## Environment

* java client build version - 5.0.3
* Appium server version :latest 
* Desktop OS/version used to run Appium if necessary: iOS 11.2
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device and simulator

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using Java and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted java code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by SrinivasanTarget** [comment]
@appiumtesterios Would recommend to fill the complete issue description to look into if there is anything specific to client. Also its recommended to perform swipe based on the element/view rather then on complete screen co.ordinates. Check [this](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSTouchTest.java#L43)

**Comment by rcuyugan** [comment]
TouchAction not working on IOS 11.4. Code works on Android without a problem. Using elements to get locations. I see in the coordinates on the Appium logs but the server throws a server side error during the perform(). I looked at the Appium logs and noticed that the two end coordinates are set to "0" see bolded  on log.

Using:
Appium 1.5.0
Server 1.7.2
Java client 6.0.0
xCode 9.4.1
iPhone 6S - real device
java


[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/element] with body: {"using":"id","value":"confirm_password"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D"},"sessionId":"040A4D88-43EA-413B-985A-AB417351EA67","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D"}
[HTTP] <-- POST /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element 200 213 ms - 122 
[HTTP] --> GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D","cd488aef-1a43-4dcb-861a-d7f7f51d59bb"]
[XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/rect] to [GET http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 344,\n    \"x\" : 35,\n    \"width\" : 305,\n    \"height\" : 43\n  },\n  \"sessionId\" : \"040A4D88-43EA-413B-985A-AB417351EA67\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":35,"y":344}
[HTTP] <-- GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/location 200 330 ms - 88 
[HTTP] --> GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D","cd488aef-1a43-4dcb-861a-d7f7f51d59bb"]
[XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/rect] to [GET http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 344,\n    \"x\" : 35,\n    \"width\" : 305,\n    \"height\" : 43\n  },\n  \"sessionId\" : \"040A4D88-43EA-413B-985A-AB417351EA67\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":35,"y":344}
[HTTP] <-- GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/8A5BA1BF-2C3C-4BE1-AEF1-3C13254FA45D/location 200 275 ms - 88 
[HTTP] --> POST /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element {"using":"id","value":"email"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","email","cd488aef-1a43-4dcb-861a-d7f7f51d59bb"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/element] with body: {"using":"id","value":"email"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"BADF3E65-D575-40A7-BD0F-0B3F0DBBB553"},"sessionId":"040A4D88-43EA-413B-985A-AB417351EA67","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"BADF3E65-D575-40A7-BD0F-0B3F0DBBB553"}
[HTTP] <-- POST /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element 200 203 ms - 122 
[HTTP] --> GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["BADF3E65-D575-40A7-BD0F-0B3F0DBBB553","cd488aef-1a43-4dcb-861a-d7f7f51d59bb"]
[XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/rect] to [GET http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 180,\n    \"x\" : 35,\n    \"width\" : 305,\n    \"height\" : 43\n  },\n  \"sessionId\" : \"040A4D88-43EA-413B-985A-AB417351EA67\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":35,"y":180}
[HTTP] <-- GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/location 200 277 ms - 88 
[HTTP] --> GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["BADF3E65-D575-40A7-BD0F-0B3F0DBBB553","cd488aef-1a43-4dcb-861a-d7f7f51d59bb"]
[XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/rect] to [GET http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 180,\n    \"x\" : 35,\n    \"width\" : 305,\n    \"height\" : 43\n  },\n  \"sessionId\" : \"040A4D88-43EA-413B-985A-AB417351EA67\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":35,"y":180}
[HTTP] <-- GET /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/element/BADF3E65-D575-40A7-BD0F-0B3F0DBBB553/location 200 271 ms - 88 
[HTTP] --> POST /wd/hub/session/cd488aef-1a43-4dcb-861a-d7f7f51d59bb/touch/perform {"actions":[{"action":"longPress","options":{"x":35,"y":344}},{"action":"moveTo","options":{"x":35,"y":180}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"x":35,"y":344}},{"action":"moveTo","options":{"x":35,"y":180}},{"action":"release","options":{}}],"cd488aef-1a43-4dcb-861a-d7f7f51d59bb"]
[XCUITest] Executing command 'performTouch'
[XCUITest] Received the following touch action: longPress(options={"x":35,"y":344})-moveTo(options={"x":35,"y":180})-release(options={})
[XCUITest] Found matching gesture: drag
[JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/040A4D88-43EA-413B-985A-AB417351EA67/wda/dragfromtoforduration] with body: **{"fromX":35,"fromY":344,"toX":0,"toY":0,"duration":null}**
[JSONWP Proxy] Got response with status 200: {"value":"-[NSNull doubleValue]: unrecognized selector sent to instance 0x1b3b42878\n\n(\n\t0   CoreFoundation                      0x0000000181936da4  + 252\n\t1   libobjc.A.dylib                     0x0000000180af05ec objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000181944098  + 0\n\t3   CoreFoundation                      0x000000018193c5c8  + 1380\n\t4   CoreFoundation                      0x000000018182241c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000104f386c4 +[FBElementCommands handleDragCoordinate:] + 600\n\t6   WebDriverAgentLib                   0x0000000104f142bc -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t7   WebDriverAgentLib                   0x0000000104f0757c __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t8   RoutingHTTPServer                   0x0000000104fd63cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t9   RoutingHTTPServer                   ...
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
@rcuyugan Please check if the issue is reproducible with the most recent server version (1.8.1 for noew or appium@beta). We don't provide patches to older versions.

**Comment by rcuyugan** [comment]
Hi. Upgrading to appium 1.6.1, Server 1.8.1 solved the swipe issue. I initially had an updated version version of appium installed but ran into "connection reset" issues after Iand reverting back to the 1.5.0  version solved that issue. I hope that this updating again doesn't introduce that same issue. Thanks!
