### ISSUE TITLE
Proper substitute for deprecated driver.swipe() method

### ISSUE THREAD

**Issue by adrianth** [appium/java-client#856]
I might be wrong here, but I think the TouchAction.moveTo() method should have an overload that allows specifying the duration of the swipe, just like the deprecated driver.swipe() method used to have. We are trying to swipe to go downwards in a page using this code:

```
(new TouchAction(driver))
                .press(PointOption.point(fromX, fromY))
                .waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000)))
                .moveTo(PointOption.point(offsetX, offsetY))
                .release()
                .perform();
```

The page has some button controls in its bottom section, and the starting point of the swipe happens to be over a button. Because of the `waitAction()` call, the button takes the delay as indication that we want to do a tap on it instead of a swipe gesture, so we are unable to swipe.

Can you please help answer these two questions:

* Is there other better API that replaces `driver.swipe()`?
* If the code above is really how you perform a swipe gesture with duration of 1 second, how do we avoid the button tap? Please note that the button position is not known up front, so we cannot solve this by adjusting the start position of the swipe.

**Comment by saikrishna321** [comment]
@adrianth sorry for delay response. 

Why not consider the fromX, fromY just above the button. You can get the position of the button and get the X and Y and -200 and then get a workaround.

**Comment by adrianth** [comment]
@saikrishna321 Thanks for your answer. Unfortunately that's not an option for us, because the position of the button is not known in advance.  In order to find a certain UI element, we are swiping multiple times in a loop, in a dynamically populated scroll view, and we have no idea what button controls might overlap with our swipe start position in our journey to the UI element we're looking for.

I am going to try a workaround, namely to split the swipe gesture in two sections: a very short section in which the swipe happens with no wait at all, then the longer section that spans the whole 1 second duration. This way I am hoping to avoid the button tap event. If that doesn't work though, I am really stuck, an I will have to revert back all the way to 4.1.2 again :-(

Can you please let me know your opinion on the proposal I formulated in my previous message? It would be nice to have a `TouchAction.moveTo(PointOption point, int duration)` method that allows specifying the duration of the swipe? Using the waitAction() method seems like an unnatural way to specify the duration of a swipe gesture, even if it did work correctly. Please let me know your stand on this proposal 
 and what do you think my options would be, if the workaround I explained above fails. Thank you.

**Comment by adrianth** [comment]
Just wanted to follow up on this issue. To summarize, when I read the following code
```
(new TouchAction(driver))
                .press(PointOption.point(fromX, fromY))
                .waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000)))
                .moveTo(PointOption.point(offsetX, offsetY))
                .release()
                .perform();
```
I conclude that it does the following: press, then wait 1 second, then move to point, then release. If I want to specify the duration of time that the move action should take, I would expect the moveTo method to be called like this:
```
moveTo(PointOption.point(offsetX, offsetY), 1000)
```
Shouldn't there exist an overload to the `moveTo` method that also accepts a duration, same as we had for the deprecated `driver.swipe()`? I am very surprised no one else is raising this issue, so maybe I am missing something? Can somebody please shed some light on this?

**Comment by Gocoollnath** [comment]
@adrianth Could you try this and see , whether it works or not?

(new TouchAction(driver))
                .press(PointOption.point(fromX, fromY))
                 .moveTo(PointOption.point(offsetX, offsetY)) 
                 .waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000)))
                .release()
                .perform();

**Comment by nimeshbhatt** [comment]
I am getting this error;
**java.lang.ClassCastException: io.appium.java_client.android.AndroidDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen**
on statement;
**TouchActions temp = new TouchActions(driver);**
So, what should be the type of parameter required to pass in TouchActions() ?

**Comment by Gocoollnath** [comment]
@nimeshbhatt Could you try my above comment and check whether it solves your issue.

**Comment by nimeshbhatt** [comment]
Hi @Gocoollnath, 
I need to pass 2 parameters for "TouchAction", please check the below line.
**TouchAction temp = new TouchAction(touchScreen, locationProvider)**
So, I am sorry but the above code is not working for me.

**Comment by nimeshbhatt** [comment]
I actually, trying to do a swipe on DATE PICKER, and for that, I started searching for swipe functionality. 
Found that driver.swipe() is now deprecated and now I am searching for the alternative of it. 
But didn't getting proper solution yet.

**Comment by Gocoollnath** [comment]
try this if it works for your date picker. It works on scrollable date pickers like the one below.

driver.findElementByLocator("Day column element").sendkeys("your day value").

![image](https://user-images.githubusercontent.com/39054531/41709844-dc611118-7561-11e8-8e27-3d269f228bc4.png)

**Comment by nimeshbhatt** [comment]
Hi, 
I have a date picker look like this, 
[https://drive.google.com/open?id=1CTMh_JgzNW-Yyd9-OJ-Mt72OXfiHI5oA](url) 
Can you please help me out where I want to select date "1" of next month every time.

**Comment by Gocoollnath** [comment]
The link throws 404 error. Could you check it again

**Comment by nimeshbhatt** [comment]
Yes, I have updated.

**Comment by nimeshbhatt** [comment]
@Gocoollnath, In shock, I am able to change the date by passing "index" value of my desired date, also able to click on "OK" button displaying on Date Picker by passing index value, but not able to click on ">" image button which allows me to change the month.

**Comment by Gocoollnath** [comment]
Step 1: Get the Month year object text and check whether its the month where the date is to be picked
If Step 1 results in the month you want to select, do nothing. Else do Step 2

Step 2: Get the element to navigate to next month and click on it until Step 1 text results the value you require

Step 3 : Get the object of Date element in the calendar and write an xpath such that it holds the date value you need to select. Store the date value as string and pass it as text attribute in the xpath you create. Eg. String date="25"; driver.findelement("//android.widget.textview[@text=\""+date+"\"]").click();


![image](https://user-images.githubusercontent.com/39054531/41711858-b7587a78-7566-11e8-8a53-ce7e4c0d8271.png)

**Comment by Gocoollnath** [comment]
@nimeshbhatt try to do a explicitwait until that '>' is clickable and then click on it

**Comment by nimeshbhatt** [comment]
@Gocoollnath, I tried by giving explicit and implicit wait too. but it is not clicking on ">" image button. 
Also, now facing an issue where I need to scroll into the app in order to click on the element which is down on the screen (visible, once you scroll). 
and this "TouchActions" is not working for scroll. giving me cast class exception.

**Comment by nimeshbhatt** [comment]
No, Scroll is different thing, sorry I mixed up.
1. ">" is not getting clicked, I applied implicit and explicit wait. Though I am able to click on "OK" button displaying on date picker.
2. After selecting date there are 3 other fields on my screen to getting filled up which will be displayed once I do scroll. So, in order to fill up details in them, I need to scroll. For that I googled which told me about "TouchActions" but it's not working too.

**Comment by Gocoollnath** [comment]
For scroll, try this
Android element screen=driver.findelement("Screen where calendar resides");
Dimension dimensions =Screen.getSize();
		Double screenHeightStart = dimensions.getHeight() * 0.5;
		int h1 = screenHeightStart.intValue();
		Double screenHeightEnd = dimensions.getHeight() * 0.2;
		int h2 = screenHeightEnd.intValue();
		for(int i=0;i<10;i++) {
		try {
		if(driver.findElementByAndroidUIAutomator("text(\"String\")").isDisplayed()) {
			driver.findElementByAndroidUIAutomator("text(\"String\")").click();
			break;
		}}
		catch(Exception e) {
			new TouchAction(driver).press(pt.point(0, h1)).moveTo(pt.point(0,-h2)).release().perform();
			continue;
		}}

**Comment by Gocoollnath** [comment]
What error  you get when you try to click on '>' button?

**Comment by nimeshbhatt** [comment]
@Gocoollnath , what you mean by the code written in "catch" block? 
- how can I write a code by defining 'new' keyword directly? "TouchAction" neither any constructor nor any class. 
- Also in "if" condition in 'try' block what is require to pass in **"driver.findElementByAndroidUIAutomator("?")"**
It's a bit confusing.

**Comment by Gocoollnath** [comment]
Sometimes creating an object for TouchAction and using it wouldn't perform necessary action, hence using a new instance directly every time you want to do a touchaction(Scroll,swipe) works.So no harm in using them.

driver.findElementByAndroidUIAutomator("") is one of the locator strategy. you can use which suits in your case. Actually syntax  is driver.findElementByAndroidUIAutomator("attribute("attributes value")"). Eg. driver.findElementByAndroidUIAutomator("text(\"Nimeshbhatt\")")

**Comment by vinitapatil1101** [comment]
Hi, i have used the below code to Swipe / Scroll and it is working perfectly.
Code to Swipe UP 
public boolean swipeFromUpToBottom() 
		{
		 try {
		  JavascriptExecutor js = (JavascriptExecutor) driver;
		  HashMap<String, String> scrollObject = new HashMap<String, String>();
		  scrollObject.put("direction", "up");
		  js.executeScript("mobile: scroll", scrollObject);
		  System.out.println("Swipe up was Successfully done.");
			}
			   catch (Exception e) 
				{
					System.out.println("swipe up was not successfull");
				}	
			return false;				
		}
Code to Swipe DOWN 
	  public boolean swipeFromBottomToUp() 
		{		
		  try  {
		  JavascriptExecutor js = (JavascriptExecutor) driver;
		  HashMap<String, String> scrollObject = new HashMap<String, String>();
		  scrollObject.put("direction", "down");
		  js.executeScript("mobile: scroll", scrollObject);
		  System.out.println("Swipe down was Successfully done");
			}
			   catch (Exception e) 
				{
					System.out.println("swipe down was not successfull");
				}	
			return false;					
		}
Code for carousel images swipe

public boolean swipeImages() 
		{		
		  try 	{
		  WebElement pageIndicator = driver.findElement(page_indicator);
		  String pageString= pageIndicator.getAttribute("value");
		  int length = pageString.length();
		  String count_string= pageString.substring(length-2, length).trim();
		  int count = Integer.parseInt(count_string);
		  System.out.println("Number of Image available to Swipe: "+count);
			   for (int i=0; i<=count; i++){			 
		  JavascriptExecutor js = (JavascriptExecutor) driver;
		  HashMap<String, String> scrollObject = new HashMap<String, String>();
		  scrollObject.put("direction", "right");
		  js.executeScript("mobile: scroll", scrollObject);		  
			   }
			   System.out.println("Swipe Successfully");
			}
			   catch (Exception e) 
				{
					System.out.println("Image swipe was not successfull");
				}	
			return false;					
		}

**Comment by BShivShankar** [comment]
@vinitapatil1101 - Thanks for the script, swipe up and down works in iphone 8 real device and appium version 1.7
one more help could you provide the script to swipe up or down to particular element and do click action like scroll up or down to particular element click.
huge thanks
