### ISSUE TITLE
Device is not recognised by Appium when is try to launch Appium server programatically.

### ISSUE THREAD

**Issue by padmakarsrinivas** [appium/java-client#857]
## Description

My device is not recognized by Appium when is try to launch Appium server programmatically. It works fine when I launch the serve from Appium Desktop.

## Environment

*Appium version (or git revision) that exhibits the issue: Appium v1.7.2
*Desktop OS/version used to run Appium: MAC 10.13.3
*Node.js version (unless using Appium.app|exe):5.6.0
*Mobile platform/version under test: iOS XCUITest
*Real device or emulator/simulator: Real device

## Details

    <dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.0.0-BETA3</version>
    </dependency>

## Code To Reproduce Issue [ Good To Have ]
    DesiredCapabilities capabilities = new DesiredCapabilities();
    File app  = new File("./src/test/resources/Ipa/XXXXX.ipa");
		capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.7.2");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2.2");
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
		capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		capabilities.setCapability("newCommandTimeout", 2000);
		capabilities.setCapability("xcodeSigningId","iPhone Developer");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, 
                AppiumBase.readPropertiesFile("IPHONE7DEVICE_NAME"));
		capabilities.setCapability(MobileCapabilityType.UDID,
               AppiumBase.readPropertiesFile("IPHONE7UDID"));
	 capabilities.setCapability("xcodeOrgId",AppiumBase.readPropertiesFile("IPHONE7xcodeOrgId"));
	capabilities.setCapability("updatedWDABundleId",AppiumBase.readPropertiesFile("IPHONE7updatedWDABundleId"));

		AppiumServiceBuilder builder = new AppiumServiceBuilder().
				withCapabilities(capabilities).withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js")).
				usingDriverExecutable(new File("/usr/local/Cellar/node/9.8.0/bin/node"))
				.withIPAddress("127.0.0.1").usingAnyFreePort();
		service = builder.build();
		service.start();
		AppiumBase.mobiledriver = new IOSDriver<>(service.getUrl(), capabilities);

## Link to Appium logs
https://gist.github.com/padmakarsrinivas/b5ba09fbc3928e89d3e30fc10b965f20

**Comment by saikrishna321** [comment]
> [XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'

Please make sure you have libimobiledevice installed and if it's installed please make sure its set in PATH

**Comment by padmakarsrinivas** [comment]
It is installed. Let me check about the path.

**Comment by padmakarsrinivas** [comment]
Okay, Even after I have set the path as mentioned below, the same problem still exists.

    export DYLD_LIBRARY_PATH=/Users/srinivasp/node_modules/libimobiledevice/:$DYLD_LIBRARY_PATH

    PATH=${PATH}:/Users/srinivasp/node_modules/libimobiledevice/

Please let me know if i am going wrong somewhere.

**Comment by padmakarsrinivas** [comment]
I have changed the path to 

   export DYLD_LIBRARY_PATH=/usr/local/Cellar/libimobiledevice/HEAD-3a37a4e_2/bin
   export PATH=/usr/local/Cellar/libimobiledevice/HEAD-3a37a4e_2/bin

still same problem.

**Comment by saikrishna321** [comment]
you should have it under /usr/local/bin pls check if you have idevice_id and other installers under this location

**Comment by saikrishna321** [comment]
Please as for question in discuss.appium.io
