### ISSUE TITLE
Sendkeys giving error on Safari browser

### ISSUE THREAD

**Issue by shridharkalagi** [appium/java-client#859]
Server logs [here](https://gist.github.com/shridharkalagi/b2199f295fced63e8ee1fab6c26e63f1) 

Appium server version - 1.8.0-beta3
Java client version - 6.0.0-BETA4
OS - MAC
Running test on iPhoneX real device

**Comment by saikrishna321** [comment]
@shridhakalagi i see from logs that ios-webkit debugger is not reachable

**Comment by shridharkalagi** [comment]
ya my bad @saikrishna321 . Actually there is no error. However, sendkeys is not working. Updated logs [here](https://gist.github.com/shridharkalagi/c2563fa01070c5fc83fd0cc5f23efc4a)

@SrinivasanTarget I tried the same with `forceMjsonwp:true` still the same behaviour

**Comment by SrinivasanTarget** [comment]
Nothing to do with client so closing this
