### ISSUE TITLE
how to start up more than one appium instance  on remote server for mulit-devices parallel test?

### ISSUE THREAD

**Issue by WenRui13** [appium/java-client#862]
from local code ,and startup  multi bootstrap-ports on remote server，how to solve it？tks!

**Comment by saikrishna321** [comment]
@WenRui13 Please refer this https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

> bootstrap-ports 

with UIAutomator2 you no more need bootstrap ports.

You don't need multiple server instances to run tests on parallel devices, single server instance can handle multiple driver request

**Comment by WenRui13** [comment]
@saikrishna321  tks ,as you say ,but it can't work.
