### ISSUE TITLE
ClassCastException in Appium java-client 6.0.0-BETA4

### ISSUE THREAD

**Issue by microlia** [appium/java-client#864]
## Description

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean

	at io.appium.java_client.InteractsWithApps.removeApp(InteractsWithApps.java:130)
	at io.appium.java_client.InteractsWithApps.removeApp(InteractsWithApps.java:114)
	

## Environment
 <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>6.0.0-BETA4</version>
 </dependency>

* Appium server version or git revision if you use some shapshot:
appium --version
1.7.2
* Desktop OS/version used to run Appium if necessary: Win 10 Pro
* Node.js version 
npm -version
5.6.0
* Mobile platform/version under test:
Real device (Android 7.0)

## Details

@AfterTest
public void removeApp() {
        if (driver().isAppInstalled(bundleId)) {
            driver.removeApp(bundleId);
        }
    }

**Comment by mykola-mokhnach** [comment]
can you also attach the Appium server log?

**Comment by mykola-mokhnach** [comment]
It might be you need to update the server to beta version as well

**Comment by microlia** [comment]
I've found the case. It is reproduced only if test is running in IntellJIdea and Appium Studio is grabbing screen via UI Automator at one time. If to close Appium Studio it is not reproduced.

**Comment by SrinivasanTarget** [comment]
Not an appium issue.
