### ISSUE TITLE
I have used .clear() and .sendKey() it does not work on Android 7.0 or above version.

### ISSUE THREAD

**Issue by abhishekgaur4feb** [appium/java-client#866]
Have a query if someone can answer:
I have used .clear() and .sendKey() it does not work on Android 7.0 or above version.

Here is my code,

driver.findElement(By.id(“com.example.appName:id/text_user_name”)).clear();
driver.findElement(By.id(“com.example.appName:id/text_user_name”)).sendKeys(“Automation”);
I’m trying to automate my android application using below configuration:

it clears the prefilled value first than when i use send keys it shows me previous value + new value.

Kindly suggest how to fix it.

Appium-Desktop 1.7.2.

selenium-java 3.8.1

selenium-server 3.8.1

java-client 5.0.2

**Comment by SrinivasanTarget** [comment]
without proper logs it is difficult to investigate @abhishekgaur4feb

**Comment by SrinivasanTarget** [comment]
Feel free to reopen with latest logs and on latest server and client. I couldnt reproduce it either.
