### ISSUE TITLE
element.isDisplayed() does not work 

### ISSUE THREAD

**Issue by WolfmosRioja** [appium/java-client#872]
# The problem
I can't use the implicit time out.
If I set 5 or 500 seconds the result is the same.

driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

# Environment

- Appium version: 1.8.0
- Windows 10
- Node.js version 9.5.0
- Samsung , AndroidVersion 7.0 (Nougat)
- Android Emulator
- Java 1.8.0
- java-client version 5.0.4

I paste the log info

org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
at AndroidUiautomator2Driver.callee$0$0$ (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:69:13)
at tryCatch (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js💯21)
at GeneratorFunctionPrototype.invoke (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
at , error=no such element, message=An element could not be located on the page using the given search parameters.}
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'DESKTOP-DCGVD8Q', ip: '172.19.48.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: AndroidDriver

**Comment by WolfmosRioja** [comment]
I have found how to reproduce this bug.
When I execute:         element.isDisplayed() and this element is not displayed, a WebDriverException is launched.

Thanks!

**Comment by TikhomirovSergey** [comment]
@WolfmosRioja You are using the older appium java client. I am going to close this issue.

**Comment by thomasEffberger** [comment]
Getting a similar issue with appium 1.8.0 Release and java-client 6.0.0beta5

https://gist.github.com/thomasEffberger/57ce3ba100dc112b29dcfa922994cbea

If i return to 1.8.0beta5 of Appium it works fine.

**Comment by thomasEffberger** [comment]
@TikhomirovSergey is this an issue with my setup or the newest java-client beta is not compatible with the appium 1.8.0 release?

**Comment by saikrishna321** [comment]
You should raise this at the server side

**Comment by thomasEffberger** [comment]
@saikrishna321 did that, but it was closed as an client issue. https://github.com/appium/appium/issues/10645

**Comment by WolfmosRioja** [comment]
I hgave the same problem https://github.com/appium/appium/issues/10583

**Comment by fyatre** [comment]
Was there a workaround or a specific version this should be fixed in? I am still seeing this on Appium 1.8.0 and Java Client 6.0.0. Works fine for iOS but not Android (uiautomator2).

**Comment by HarithaSrivathsan** [comment]
Even i am facing the same issue as @fyatre.. Any workaround ?

**Comment by mrcs64** [comment]
@HarithaSrivathsan Use older version of Appium.
