### ISSUE TITLE
Appium 1.8 - switchTo().alert() behavior change 

### ISSUE THREAD

**Issue by lubshilk** [appium/java-client#884]
switchTo.alert() doesn't work in the way it worked in appium server 1.7.1

Upgraded MAC, Xcode and Appium server to newest versions:
* java client 5.0.4
* Appium server 1.8
* MAC OS 10.13.4
* Node 6.11.3
* Mobile IOS 11.3.1
* Real device

The code:
 ```
try{ 
	Alert alert = waitForAlert(driver);
       try{
			alertText = alert.getText();
       } catch (Exception e){
				logger.info("Failed to catch alert text");
	}
	alert.accept();
} catch (Exception e) {
			logger.info("No alert");
}
```
waitForAlert() function code throws exception if alert not popped-up 
```
public static Alert waitForAlert(WebDriver driver, long wait_time)
			throws TimeoutException, NoSuchElementException {
		// configure waiting in seconds.
		wait = new WebDriverWait(driver, wait_time);
		wait.withMessage("Could not find Alert popup window , Waited " + wait_time + "s");
		// Wait for element to load
		return wait.until(new ExpectedCondition<Alert>() {
			public Alert apply(WebDriver driver) {
					return driver.switchTo().alert();
			}
		});
	}
```
With Appium server 1.7.1 MAC 10.12 and Xcode 9.2 it worked perfectly

After upgrade receiving no exception when no alert shown from wait.until() and as a result continue to alert.getText() and alert.accept() with no problems reported. But there was no alert! 
Alert text received:

>  '{stacktrace=NoSuchAlertError: [object Object] at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:769:12) at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:797:13) at asyncHandler$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:37) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37), error=no such alert, message={}}'

**Comment by mykola-mokhnach** [comment]
Update java client to version 6 along with selenium API lib

**Comment by mykola-mokhnach** [comment]
Can you try `ExpectedConditions.alertIsPresent()`. See https://github.com/appium/appium/issues/10286

**Comment by lubshilk** [comment]
I'll try later and let you know

**Comment by lubshilk** [comment]
@mykola-mokhnach Did you suggest to try ExpectedConditions.alertIsPresent() as workaround? I used another WA. If it is only suggestion for WA I would be rather not change my code

**Comment by kirillbilchenko** [comment]
@lubshilk @mykola-mokhnach for me the best way to handle alert on ios was 
`
	public static List<String> getIosAlertButtonsLabels() {
		JavascriptExecutor js = getDriver();
		Map<String, Object> params = new HashMap<>();
		params.put("action", "getButtons");
		return (List<String>) js.executeScript("mobile: alert", params);
	}`
so means if number of buttons is more then 0 mean's it's returning, you can create you own expected conditions to check this.
