### ISSUE TITLE
Unable to get Keyboard visibility in iOS Devices

### ISSUE THREAD

**Issue by kumarswamy757** [appium/java-client#885]
## Description

I'm not able to get the keyboard visibility state for iOS

## Environment

* java client build version or git revision if you use some shapshot: 6.0.0 Beta4
* Appium server version or git revision if you use some shapshot:
* Desktop OS/version used to run Appium if necessary: Windows & Linux
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: iPhone 6 Simulator 

## Details

Getting java.lang.ClassCastException: io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.android.HasDeviceDetails error in iOS.

when i check appium java docs (http://appium.github.io/java-client/io/appium/java_client/ios/IOSDriver.html) i found that "HasDeviceDetails" class extends only "AndroidDriver" but not "IOSDriver"

## Code To Reproduce Issue [ Good To Have ]

boolean isKeyboardShown = ((HasDeviceDetails)driver).isKeyboardShown();

## Ecxeption stacktraces

 java.lang.ClassCastException: io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.android.HasDeviceDetails

**Comment by thomasEffberger** [comment]
isKeyboardShown is only available for Android Driver. Afaik the android keyboard is not really visilble to appium.
On iOS though you can check on the actual elements. Try open an iOS app and start the inspector after taping on an input field.
For example you could evaluate a find by on the Search Button (asssuming you selected a search field) by
driver.findElementByAccessibilityId("Search")

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/664
