### ISSUE TITLE
Rotate gesture on map iOS 11.3

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/java-client#888]
I’m automating a map where I need to rotate the map with two fingers.
according to the XCUITEST documentation provided : https://developer.apple.com/documentation/xctest/xcuielement/1618665-rotate rotate gesture is possible. I couldn’t find any help for rotate gesture in Appium ? Can anyone help.

**Comment by SrinivasanTarget** [comment]
Please check in appium discuss forum.

**Comment by MummanaSubramanya** [comment]
Hi srinivas , i couldnt find any  discussion on this feature. This is rotation gesture with two fingers its not device rotation. I beleive this gesture is not implemnted. Request you to re confirm

**Comment by hanging-with-my-gnomies** [comment]
> I’m automating a map where I need to rotate the map with two fingers.
> according to the XCUITEST documentation provided : https://developer.apple.com/documentation/xctest/xcuielement/1618665-rotate rotate gesture is possible. I couldn’t find any help for rotate gesture in Appium ? Can anyone help.

Hello, do you found a solution?
