### ISSUE TITLE
Possible memory leak in v6.0.0-BETA5 crashing tests in surefire plugin.

### ISSUE THREAD

**Issue by ajeeshvl** [appium/java-client#891]
## Description
Using the latest v6.0.0-BETA5 throwing following error in Jenkins while running tests on iOS devices using maven surefire plugin. 
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

No issue if I change the version to **v6.0.0-BETA1**

## Environment

* java client build version or git revision if you use some shapshot: v6.0.0-BETA5
* Appium server version or git revision if you use some shapshot: 1.8
* Desktop OS/version used to run Appium if necessary: 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v9.11.1
* Mobile platform/version under test: iOS v11.3.1
* Real device or emulator/simulator: Real device
* Maven Sure Fire plugin version: 2.21.0

## Details

While investigating further I found,

If this happens on a CI environment and only after it runs for some time, there is a fair chance your test suite is leaking some kind of OS-level resource that makes things worse at every run. Regular OS-level monitoring tools may give you some indication.

http://maven.apache.org/surefire/maven-surefire-plugin/faq.html

## Exception stacktraces

https://gist.github.com/ajeeshvl/001737c154fb39b5108de524d19a152e

**Comment by SrinivasanTarget** [comment]
@ajeeshvl We have been rigorously testing using latest server and client. I don't see any issues. Feel free to raise this in discuss forum.
