### ISSUE TITLE
removeApp() causes NullPointerException because of cast to boolean

### ISSUE THREAD

**Issue by Akres** [appium/java-client#892]
## Description

I get a NullPointerException in
`at io.appium.java_client.InteractsWithApps.removeApp(InteractsWithApps.java:130)`
`at io.appium.java_client.InteractsWithApps.removeApp(InteractsWithApps.java:114)`
It is because `removeApp` command in Appium server returns `null`, but the `InteractsWithApps.removeApp` method tries to cast it to a `boolean`, which causes `NullPointerException`.

## Environment

* java client build version: 6.0.0-BETA5
* Appium server version: Appium desktop v1.6.1 with Appium server v1.8.0
* Desktop OS/version used to run Appium: macOS Sierra v10.12.6
* Mobile platform/version under test: iOS v11.2
* Real device or emulator/simulator: simulator

## Code To Reproduce Issue

`driver.removeApp(bundleId)`

**Comment by Akres** [comment]
Glad I could be of service :-) When will the change be released?

**Comment by mykola-mokhnach** [comment]
The fix has been merged to beta, will be released in 1.8.1
