### ISSUE TITLE
Find element causing issue with appium 1.8.0 it's returning response in w3c way

### ISSUE THREAD

**Issue by kirillbilchenko** [appium/java-client#895]
## Description
By introducing support of w3c specification find element response by appium server is returned in w3c standard, but appium clien still trying to handle it with JsonHttpCommandCodec JsonWireProtocol
forceMjsonwp capability doesn't affect anything 

## Environment

* 6.0.0-BETA5 but I tried different versions result the same
* 1.8.0
* System Version: macOS 10.13.4 (17E202) Kernel Version: Darwin 17.5.0
*  Node version is 9.11.1
* both android and ios
* real devices nexus on android and iphone 6 on ios

## Details
Appium 1.8.0 introduced  support of W3C WebDriver specification so responses from appium server is now returning in w3c way, if I change manually JsonHttpCommandCodec to AppiumW3CHttpCommandCodec it's passing this place successfully and handling 404 status code for find element successfully, by default initializing JsonHttpCommandCodec. So maybe you can help me how I can switch appium server to return default format of w3c?

## Ecxeption stacktraces
org.openqa.selenium.WebDriverException: 
Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:69:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>, error=no such element, message=An element could not be located on the page using the given search parameters.}
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'MacBook-Pro.local', ip: 'fe80:0:0:0:8ec:eb54:d75a:ee9e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_60'
Driver info: driver.version: AndroidDriver

[stack trace](https://gist.github.com/df4b4dda7dc8d69884e02c7e4bf6f84b.git)

## Link to Appium logs
[android](https://gist.github.com/776d5f51423d9586bef2ee62ed3aa3e3.git)
[ios](https://gist.github.com/7b6af3daaa69e84e24471636eb77bd07.git)

**Comment by SergheiRidico** [comment]
I have faced the same issue

**Comment by SrinivasanTarget** [comment]
@kirillbilchenko @SergheiRidico I was able to reproduce this. Will have a look at it soon.

**Comment by SrinivasanTarget** [comment]
Its fixed in latest release. so closing this.

**Comment by Ashishqa** [comment]
Hi Srinivasan, 
I am facing this issue with Java Client 6.0.0. and Standalone server 3.12. I am using Appium 1.6.1.
Could you suggest me in which version you have fixed this issue?
Thanks.
