### ISSUE TITLE
 getPageSource()  doesn't work for platform Android 7

### ISSUE THREAD

**Issue by Mynziak** [appium/java-client#898]
## Description

When I run Android application  -  I have Login screen and successfully signing up using my test code, but after that I'm getting another screen of application where appium doesn't work. I set brake point on this screen and try to  getPageSource() in debug mode, but nothing works. Even using uiautomator doesn't work - it shows only  loader.  If I turn application to background and run it again on foreground on current page - getPageSource() start working fine and uiautomator displays appropriate page.  

I use TestNG + Java., my code works good for another device with Android Platform 4, but doesn't work for 2 devices on Android 7 (Xiaomi Rednote4 and Samsung Galaxy J7)

Can somebody propose workaround? Please help. 

## Environment

* java client build 6.0.0-BETA5 
* Appium server version 1.6.1
* Desktop OS/version used to run Appium : 1.6.1
* Node.js version v8.11.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: real device Samsung Galaxy J7

## Details

I run Appium Server by using Desktop version 1.6.1,
Use real device Galaxy J7.
Use maven dependencies   6.0.0-BETA5 

## Code To Reproduce Issue [ Good To Have ]

My working code is here: https://github.com/Mynziak/java_appium_tests

## Ecxeption stacktraces

I get exception after timeout, because nothing receive from Appium Server

## Link to Appium logs

<script src="https://gist.github.com/Mynziak/ecb4ad94ee8ddbc80123e0651bb7ae2d.js"></script>

**Comment by kirillbilchenko** [comment]
First of all try to set MobileCapabilityType.AUTOMATION_NAME to uiautomator2, it may be a reason why it's failing for you Prerequisites: This module should support from Android 5.0 (API Level 20) and above

**Comment by Mynziak** [comment]
@kirillbilchenko Yes, It helps me! Thank you very much!
