### ISSUE TITLE
REPL for Java

### ISSUE THREAD

**Issue by mrahman53** [appium/java-client#90]
We like the way to find element from the terminal using Ruby, but it would be awesome for Java community to have that feature. Thanks

**Comment by bootstraponline** [comment]
http://www.jclarity.com/2015/04/15/java-9-repl-getting-started-guide/

**Comment by saikrishna321** [comment]
@bootstraponline  

when i trigger the groovery script from grooveysh i get the below error 

 AppiumRepl-master  ~/Downloads/groovy-2.4.5/bin/groovysh /Users/saikrisv/appium.groovy
Groovy Shell (2.4.5, JVM: 1.8.0_51)
Type ':help' or ':h' for help.
-------------------------------------------------------------------------------------------
groovy:000> :load /Users/saikrisv/appium.groovy
Invalid import definition: 'io.appium.java_client.android.AndroidDriver'; reason: startup failed:
script1444040347647458867804.groovy: 1: unable to resolve class io.appium.java_client.android.AndroidDriver
 @ line 1, column 1.
   import io.appium.java_client.android.AndroidDriver;
   ^

1 error

Invalid import definition: 'org.openqa.selenium.By'; reason: startup failed:
script14440403477731421691715.groovy: 1: unable to resolve class org.openqa.selenium.By
 @ line 1, column 1.
   import org.openqa.selenium.By;
   ^

1 error

Invalid import definition: 'org.openqa.selenium.WebElement'; reason: startup failed:
script14440403477791645566612.groovy: 1: unable to resolve class org.openqa.selenium.WebElement
 @ line 1, column 1.
   import org.openqa.selenium.WebElement;
   ^

1 error

Invalid import definition: 'org.openqa.selenium.remote.DesiredCapabilities'; reason: startup failed:
script14440403477851186576660.groovy: 1: unable to resolve class org.openqa.selenium.remote.DesiredCapabilities
 @ line 1, column 1.
   import org.openqa.selenium.remote.DesiredCapabilities;
   ^

1 error

groovysh_evaluate: 3: unable to resolve class DesiredCapabilities 
 @ line 3, column 21.
   DesiredCapabilities caps = new DesiredCapabilities();
                       ^

groovysh_evaluate: 3: unable to resolve class DesiredCapabilities 
 @ line 3, column 28.
   DesiredCapabilities caps = new DesiredCapabilities();
                              ^


I understand the imports are not happening, i have all the jars placed under .groovry/lib

**Comment by saikrishna321** [comment]
@bootstraponline  when i try to set classpath 

groovysh --classpath

it directly gets into the groovysh does not start any appium session

**Comment by saikrishna321** [comment]
@bootstraponline i was able to get the android app from groovysh, but when i make any driver calls, it gives Unknown property 

groovyconsole script ::

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.By;
import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;


        caps = new DesiredCapabilities();
        caps.setCapability("deviceName", "");
        caps.setCapability("appPackage", "com.android.contacts");
        caps.setCapability("appActivity", "com.android.contacts.activities.PeopleActivity");
        caps.setCapability("commandTimeout", "50");
        caps.setCapability("platformVersion", "5.0.2");
       AppiumDriver driver = new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
       driver.quit();

groovy:000> :load /Users/saikrisv/appium.groovy
===> org.openqa.selenium.By, io.appium.java_client.AppiumDriver, org.openqa.selenium.WebElement, org.openqa.selenium.remote.DesiredCapabilities, io.appium.java_client.android.AndroidDriver
===> io.appium.java_client.AppiumDriver, org.openqa.selenium.WebElement, org.openqa.selenium.remote.DesiredCapabilities, io.appium.java_client.android.AndroidDriver, org.openqa.selenium.By
===> org.openqa.selenium.WebElement, org.openqa.selenium.remote.DesiredCapabilities, io.appium.java_client.android.AndroidDriver, org.openqa.selenium.By, io.appium.java_client.AppiumDriver
===> org.openqa.selenium.remote.DesiredCapabilities, io.appium.java_client.android.AndroidDriver, org.openqa.selenium.By, io.appium.java_client.AppiumDriver, org.openqa.selenium.WebElement
===> io.appium.java_client.android.AndroidDriver, org.openqa.selenium.By, io.appium.java_client.AppiumDriver, org.openqa.selenium.WebElement, org.openqa.selenium.remote.DesiredCapabilities
===> Capabilities [{}]
===> null
===> null
===> null
===> null
===> null
===> AndroidDriver: Android on LINUX (319fa567-f24f-4c6c-bb9b-114eccdf1a6e)
Unknown property: driver
groovy:000>

**Comment by bootstraponline** [comment]
Use JShell instead. https://blogs.oracle.com/java/entry/jshell_and_relp_in_java

**Comment by saikrishna321** [comment]
@bootstraponline how should my appium script look like to debug with jshell ?

**Comment by bootstraponline** [comment]
There's an updated blog on jshell usage that relies on a precompiled jar from the adopt-openjdk cloudbees account.

- https://www.pgrs.net/2015/09/14/java-repl-with-jshell-and-bazel/

I haven't had a chance to test jshell with appium since I couldn't get it working on OS X. Oracle hasn't accepted jshell into the JDK 9 early access releases. I expect when that happens then it'll be easy for someone to figure out appium integration.

**Comment by saikrishna321** [comment]
@TikhomirovSergey i was able to use java-repl and get the irb for java-client 

https://github.com/saikrishna321/AppiumReplJava

**Comment by saikrishna321** [comment]
@TikhomirovSergey can we close this ?

**Comment by email2vimalraj** [comment]
@mrahman53 @saikrishna321 @bootstraponline @Jonahss : Any use-case for this Java REPL? Because almost all the Java IDEs has debugging capability which would help us any user put a break point and achieve the same on what we try to achieve through REPL.

**Comment by mygithub07** [comment]
@email2vimalraj I am trying to do the same with appium java eclipse but couldnt get it . Heres a question I asked on SO. Please let me know if you have an idea about it.

https://stackoverflow.com/questions/46918676/eclipse-java-appium-test-debug
