### ISSUE TITLE
pushFile corrputs transfered file

### ISSUE THREAD

**Issue by Kpamnani1** [appium/java-client#900]
## Description

driver.pushFile corrputs file when called with instance of java.io.File

works

File file = ...
driver.pushFile(devicePath, file); // corrupts file, looks like it base64 encoded twice

NOT Works

import org.apache.commons.io.FileUtils;
...
byte[] content = FileUtils.readFileToByteArray(file); // file -> stream -> byte array
driver.pushFile(devicePath, content); 

## Environment

    Appium 1.7.2
    Android emulator with 7.1
    Appium java-client 6.0.0-BETA5

## Details

Push one file into virtual device, the first time with java.io.File, the second time with byte[]
Grab both files from deviced with adb pull ...
Second file  will be broken

**Comment by mykola-mokhnach** [comment]
```
byte[] content = FileUtils.readFileToByteArray(file); // file -> stream -> byte array
driver.pushFile(devicePath, content);
```

the step to encode file into base64 is missing here. the client expect the array of bytes to be already encoded.

**Comment by Kpamnani1** [comment]
This is my complete code which worked fine till java-client 5.0.0.4

 Path abc=Paths.get(System.getProperty("user.dir"), "src", "main", "resources", "scripts", "update.v2c");
        StringBuilder wrContent = new StringBuilder("");
        BufferedReader reader = new BufferedReader(new FileReader(new File(abc.toString())));
        String tmp = "";
        while((tmp = reader.readLine()) != null){
            wrContent.append(tmp);
        }
driver.pushFile("sdcard/update.v2c", wrContent.toString().getBytes());

**Comment by mykola-mokhnach** [comment]
There was a bug before, which has been fixed in v6
