### ISSUE TITLE
android driver loose connection after reboot device connected by wifi

### ISSUE THREAD

**Issue by selenUser** [appium/java-client#901]
## Description

I need during my test to restart my device connected by wifi (connected like X.X.X.X:1234), and continue my flow.
because of device restart the port number changed like X.X.X.X:9876.
There is a way to update android driver / capability to look at new device UDID without restart android driver ? I need to be able to test in same android driver session

## Environment

* java client build version: 4.1.2
* Appium server version: 1.6.4
* Real device

**Comment by vikramvi** [comment]
@selenUser  you should ask this query in https://discuss.appium.io/, github is for reporting issues only
