### ISSUE TITLE
Appium returns status code 400 bad request when setting implicitlyWait timeouts

### ISSUE THREAD

**Issue by thaitrongnghi** [appium/java-client#905]
## Description
**Client script:**
AndroidDriver<WebElement> driver = new AndroidDriver<WebElement>(Configs.nativeAppiumURL(), Configs.desiredCapabilitiesLocal());
driver.manage().timeouts().implicitlyWait(90, TimeUnit.SECONDS);

**Appium logs:**
[HTTP] --> POST /wd/hub/session/c1ab703d-2ab1-4e03-a8ee-2ae8328b90be/timeouts
[HTTP] {"type":"implicit","ms":90000}
[debug] [W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":90000}

## Link to Appium logs

[Appium] Welcome to Appium v1.8.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/xxxtop/Apps/webview/SampleWebtrendsHybrid.apk","deviceName":"Nexus","platformName":"Android","realMobile":"true","sessionName":"Android app on local devices"},"capabilities":{"desiredCapabilities":{"app":"/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk","deviceName":"Nexus","platformName":"Android","realMobile":"true","sessionName":"Android app on local devices"},"firstMatch":[{"platformName":"android"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk","deviceName":"Nexus","platformName":"Android","realMobile":"true","sessionName":"Android app on local devices"},null,{"desiredCapabilities":{"app":"/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk","deviceName":"Nexus","platformName":"Android","realMobile":"true","sessionName":"Android app on local devices"},"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1526986441590 (17:54:01 GMT+0700 (+07))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["app","deviceName","platformName","realMobile","sessionName"]. Falling back to JSONWP protocol.
[Appium] Creating new AndroidDriver (v2.4.1) session
[Appium] Capabilities:
[Appium]   app: /Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk
[Appium]   deviceName: Nexus
[Appium]   platformName: Android
[Appium]   realMobile: true
[Appium]   sessionName: Android app on local devices
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/xxxtxxx..
[BaseDriver] The following capabilities were provided, but are not recognized by appium: realMobile, sessionName.
[BaseDriver] Session created with session id: c1ab703d-2ab1-4e03-a8ee-2ae8328b90be
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_151
[ADB] Checking whether adb is present
[ADB] Found 3 'build-tools' folders under '/Users/xxxtxxxary/Android/sdk' (newest first):
[ADB]     /Users/xxxtxxxary/Android/sdk/build-tools/27.0.3
[ADB]     /Users/xxxtxxxary/Android/sdk/build-tools/27.0.0
[ADB]     /Users/xxxtxxxary/Android/sdk/build-tools/26.0.2
[ADB] Using adb from /Users/xxxtxxxary/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: ZX1G22HGPV
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/xxxtxxxary/Android/sdk/platform-tools/adb
[debug] [ADB] Setting device id to ZX1G22HGPV
[BaseDriver] Using local app '/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV wait-for-device'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell pm list packages io.appium.settings'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/xxxtxxxary/Android/sdk/build-tools/27.0.3/aapt
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell ps'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 25
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell pm list packages io.appium.unlock'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell dumpsys package io.appium.unlock'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/xxxtxxxary/Android/sdk/build-tools/27.0.3/aapt
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.1.1
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell wm size'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Nexus 6
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': motorola
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Using apkanalyzer from /Users/xxxtxxxary/Android/sdk/tools/bin/apkanalyzer
[debug] [ADB] Starting '/Users/xxxtxxxary/Android/sdk/tools/bin/apkanalyzer' with args ["-h","manifest","print","/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk"]
[ADB] Package name: 'com.webtrends.WThybridAppSample'
[ADB] Main activity name: 'com.webtrends.WThybridAppSample.HybridAppSampleActivity'
[debug] [AndroidDriver] Parsed package and activity are: com.webtrends.WThybridAppSample/com.webtrends.WThybridAppSample.HybridAppSampleActivity
[debug] [ADB] Getting install status for com.webtrends.WThybridAppSample
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell pm list packages com.webtrends.WThybridAppSample'
[debug] [ADB] App is installed
[debug] [ADB] Getting install status for com.webtrends.WThybridAppSample
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell pm list packages com.webtrends.WThybridAppSample'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'com.webtrends.WThybridAppSample'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell dumpsys package com.webtrends.WThybridAppSample'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/xxxtxxxary/Android/sdk/build-tools/27.0.3/aapt
[debug] [ADB] The installed 'com.webtrends.WThybridAppSample' package does not require upgrade ('3.0.0' >= '3.0.0')
[AndroidDriver] Performing fast reset on 'com.webtrends.WThybridAppSample'
[debug] [ADB] Getting install status for com.webtrends.WThybridAppSample
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell pm list packages com.webtrends.WThybridAppSample'
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell am force-stop com.webtrends.WThybridAppSample'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell pm clear com.webtrends.WThybridAppSample'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.webtrends.WThybridAppSample' application (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell rm -rf /data/local/tmp/strings.json'
[debug] [AndroidDriver] Extracting strings from apk
[debug] [AndroidDriver] /Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk
[debug] [AndroidDriver] null
[debug] [AndroidDriver] /var/folders/y6/w_719xy922g_r5zhf_nb0xnw0000gp/T/com.webtrends.WThybridAppSample
[debug] [ADB] Extracting strings for language: default
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/xxxtxxxary/Android/sdk/build-tools/27.0.3/aapt
[ADB] Successfully extracted 18 strings from '/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk' resources for '(default)' configuration
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV push /var/folders/y6/w_719xy922g_r5zhf_nb0xnw0000gp/T/com.webtrends.WThybridAppSample/strings.json /data/local/tmp'
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV push /usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ZX1G22HGPV","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.webtrends.WThybridAppSample","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell am start -W -n com.webtrends.WThybridAppSample/com.webtrends.WThybridAppSample.HybridAppSampleActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.webtrends.WThybridAppSample' and activity: 'com.webtrends.WThybridAppSample.HybridAppSampleActivity' to be focused
[debug] [ADB] Possible activities, to be checked: 'com.webtrends.WThybridAppSample.HybridAppSampleActivity', 'com.webtrends.WThybridAppSample.com.webtrends.WThybridAppSample.HybridAppSampleActivity'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell dumpsys window windows'
[debug] [ADB] Found package: 'com.webtrends.WThybridAppSample' and fully qualified activity name : 'com.webtrends.WThybridAppSample.HybridAppSampleActivity'
[Appium] New AndroidDriver session created successfully, session c1ab703d-2ab1-4e03-a8ee-2ae8328b90be added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1526986463627 (17:54:23 GMT+0700 (+07))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk","deviceName":"Nexus","platformName":"Android","realMobile":"true","sessionName":"Android app on local devices"},"app":"/Users/xxxtxxxtop/Apps/webview/SampleWebtrendsHybrid.apk","deviceName":"ZX1G22HGPV","platformName":"Android","realMobile":"true","sessionName":"Android app on local devices","deviceUDID":"ZX1G22HGPV","platformVersion":"7.1.1","deviceScreenSize":"1440x2560","deviceModel":"Nexus 6","deviceManufacturer":"motorola","appPackage":"com.webtrends.WThybridAppSample","appWaitPackage":"com.webtrends.WThybridAppSample","appActivity":"com.webtrends.WThybridAppSample.HybridAppSampleActivity","appWaitActivity":"com.webtrends.WThybridAppSample.HybridAppSampleActivity"}
[HTTP] <-- POST /wd/hub/session 200 22046 ms - 1033
[HTTP] 
[HTTP] --> POST /wd/hub/session/c1ab703d-2ab1-4e03-a8ee-2ae8328b90be/timeouts
[HTTP] {"type":"implicit","ms":90000}
[debug] [W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":90000}
[HTTP] <-- POST /wd/hub/session/c1ab703d-2ab1-4e03-a8ee-2ae8328b90be/timeouts 400 16 ms - 4197
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/c1ab703d-2ab1-4e03-a8ee-2ae8328b90be
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["c1ab703d-2ab1-4e03-a8ee-2ae8328b90be"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1526986468756 (17:54:28 GMT+0700 (+07))
[Appium] Removing session c1ab703d-2ab1-4e03-a8ee-2ae8328b90be from our master session list
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell am force-stop com.webtrends.WThybridAppSample'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell input keyevent 3'
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xxxtxxxary/Android/sdk/platform-tools/adb -P 5037 -s ZX1G22HGPV shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1526986471994 (17:54:31 GMT+0700 (+07))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/c1ab703d-2ab1-4e03-a8ee-2ae8328b90be 200 3240 ms - 76
[HTTP]

**Comment by thaitrongnghi** [comment]
It doesn't happen on Appium 1.8.1

**Comment by thaitrongnghi** [comment]
Hi @SrinivasanTarget, this issue happens to me now. Please help double check this, thank you a lot!
- Java client: 6.0.0-BETA4
- Appium 1.8.1

**Comment by SrinivasanTarget** [comment]
@thaitrongnghi Try latest appium server 1.9.0 and java client as described [here](https://github.com/appium/java-client/#maven)

**Comment by thaitrongnghi** [comment]
Thanks @SrinivasanTarget for quick response. It worked for me on the latest appium server 1.9.0. 
Closed the ticket.
