### ISSUE TITLE
Facing issue in sending values and click in login page of my app..

### ISSUE THREAD

**Issue by knisha19** [appium/java-client#910]
## Description

I not not able to send values to userid and password and also not able to click on LogOn button.
It is not finding the element....however,I have tried with xpath,id,classname but none of them works for locating the element...everytime it is throwing the error.I am running this testcase on Emulator.
I am struggling to fix this issue from two weeks but not able to fix this issue....
Can u please help me to fix this issue...

**Here is my code:-**

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class logintest {

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		File f=new File("src");
		File fs=new File(f,"MobilePro-uat.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
	    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nisha_Emulator");
	    capabilities.setCapability("platformName", "Android");
	    capabilities.setCapability(MobileCapabilityType.APP,fs.getAbsolutePath());
	    capabilities.setCapability("appPackage","com.etrade.mobilepro.activity");
		AndroidDriver<AndroidElement> driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.findElementByAndroidUIAutomator("text(\"I AGREE\")").click();
		driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/txtUsername\")").sendKeys("abcd");
		driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/txtPassword\")").sendKeys("1234");
		driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/btnLogon\")").click();;
		}
	}
**Here is my appium logs:-**

[Appium] Welcome to Appium v1.8.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},{},{"desiredCapabilities":{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1527193658861 (13:27:38 GMT-0700 (Pacific Daylight Time))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["app","appPackage","platformName","deviceName"]. Falling back to JSONWP protocol.
[Appium] Creating new AndroidDriver (v2.4.1) session
[Appium] Capabilities:
[Appium]   app: C:\Users\Vnishal\eclipse-workspace\Etrade\src\MobilePro-uat.apk
[Appium]   appPackage: com.etrade.mobilepro.activity
[Appium]   platformName: Android
[Appium]   deviceName: Nisha_Emulator
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"C:\\Users\\Vnishal\...
[BaseDriver] Session created with session id: 4cb91d76-aed3-4d01-b5a1-2c653e43880e
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 10.0.1
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under 'C:\Users\Vnishal\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/Vnishal/AppData/Local/Android/Sdk/build-tools/27.0.3
[ADB]     C:/Users/Vnishal/AppData/Local/Android/Sdk/build-tools/26.0.2
[ADB] Using adb.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to emulator-5554
[BaseDriver] Using local app 'C:\Users\Vnishal\eclipse-workspace\Etrade\src\MobilePro-uat.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages io.appium.settings'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell ps'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 25
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages io.appium.unlock'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.unlock'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.1.1
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell wm size'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Android SDK built for x86
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': Google
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Using the alternative activity name detection method because of: Could not find apkanalyzer.bat in C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\apkanalyzer.bat,C:\Users\Vnishal\AppData\Local\Android\Sdk\emulator\apkanalyzer.bat,C:\Users\Vnishal\AppData\Local\Android\Sdk\tools\apkanalyzer.bat,C:\Users\Vnishal\AppData\Local\Android\Sdk\tools\bin\apkanalyzer.bat,C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\27.0.3\apkanalyzer.bat,C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\26.0.2\apkanalyzer.bat. Do you have the Android SDK installed at 'C:\Users\Vnishal\AppData\Local\Android\Sdk'?
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[ADB] Extracting package and launch activity from manifest
[ADB] Package name: 'com.etrade.mobilepro.activity'
[ADB] Main activity name: 'com.etrade.mobilepro.activity.MobileProMain'
[debug] [AndroidDriver] Parsed package and activity are: com.etrade.mobilepro.activity/com.etrade.mobilepro.activity.MobileProMain
[debug] [ADB] Getting install status for com.etrade.mobilepro.activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.etrade.mobilepro.activity'
[debug] [ADB] App is installed
[debug] [ADB] Getting install status for com.etrade.mobilepro.activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.etrade.mobilepro.activity'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'com.etrade.mobilepro.activity'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.etrade.mobilepro.activity'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[debug] [ADB] The installed 'com.etrade.mobilepro.activity' package does not require upgrade ('6.5.0' >= '6.5.0')
[AndroidDriver] Performing fast reset on 'com.etrade.mobilepro.activity'
[debug] [ADB] Getting install status for com.etrade.mobilepro.activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.etrade.mobilepro.activity'
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.etrade.mobilepro.activity'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm clear com.etrade.mobilepro.activity'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.etrade.mobilepro.activity' application (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell rm -rf /data/local/tmp/strings.json'
[debug] [AndroidDriver] Extracting strings from apk
[debug] [AndroidDriver] C:\Users\Vnishal\eclipse-workspace\Etrade\src\MobilePro-uat.apk
[debug] [AndroidDriver] null
[debug] [AndroidDriver] C:\Users\Vnishal\AppData\Local\Temp\com.etrade.mobilepro.activity
[debug] [ADB] Extracting strings for language: default
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\Vnishal\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[ADB] Successfully extracted 1597 strings from 'C:\Users\Vnishal\eclipse-workspace\Etrade\src\MobilePro-uat.apk' resources for '(default)' configuration
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 push C\:\\Users\\Vnishal\\AppData\\Local\\Temp\\com.etrade.mobilepro.activity\\strings.json /data/local/tmp'
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 push C\:\\Users\\Vnishal\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.etrade.mobilepro.activity","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.etrade.mobilepro.activity/com.etrade.mobilepro.activity.MobileProMain -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.etrade.mobilepro.activity' and activity: 'com.etrade.mobilepro.activity.MobileProMain' to be focused
[debug] [ADB] Possible activities, to be checked: 'com.etrade.mobilepro.activity.MobileProMain', 'com.etrade.mobilepro.activity.com.etrade.mobilepro.activity.MobileProMain'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vnishal\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows'
[debug] [ADB] Found package: 'com.etrade.mobilepro.activity' and fully qualified activity name : 'com.etrade.mobilepro.activity.MobileProMain'
[Appium] New AndroidDriver session created successfully, session 4cb91d76-aed3-4d01-b5a1-2c653e43880e added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1527193683173 (13:28:03 GMT-0700 (Pacific Daylight Time))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"emulator-5554","deviceUDID":"emulator-5554","platformVersion":"7.1.1","deviceScreenSize":"1440x2560","deviceModel":"Android SDK built for x86","deviceManufacturer":"Google","appWaitPackage":"com.etrade.mobilepro.activity","appActivity":"com.etrade.mobilepro.activity.MobileProMain","appWaitActivity":"com.etrade.mobilepro.activity.MobileProMain"}
[HTTP] <-- POST /wd/hub/session 200 24397 ms - 965
[HTTP]
[HTTP] --> GET /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["4cb91d76-aed3-4d01-b5a1-2c653e43880e"]
[debug] [W3C] Responding to client with driver.getSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"emulator-5554","deviceUDID":"emulator-5554","platformVersion":"7.1.1","deviceScreenSize":"1440x2560","deviceModel":"Android SDK built for x86","deviceManufacturer":"Google","appWaitPackage":"com.etrade.mobilepro.activity","appActivity":"com.etrade.mobilepro.activity.MobileProMain","appWaitActivity":"com.etrade.mobilepro.activity.MobileProMain"}
[HTTP] <-- GET /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e 200 94 ms - 965
[HTTP]
[HTTP] --> GET /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["4cb91d76-aed3-4d01-b5a1-2c653e43880e"]
[debug] [W3C] Responding to client with driver.getSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"Nisha_Emulator"},"app":"C:\\Users\\Vnishal\\eclipse-workspace\\Etrade\\src\\MobilePro-uat.apk","appPackage":"com.etrade.mobilepro.activity","platformName":"Android","deviceName":"emulator-5554","deviceUDID":"emulator-5554","platformVersion":"7.1.1","deviceScreenSize":"1440x2560","deviceModel":"Android SDK built for x86","deviceManufacturer":"Google","appWaitPackage":"com.etrade.mobilepro.activity","appActivity":"com.etrade.mobilepro.activity.MobileProMain","appWaitActivity":"com.etrade.mobilepro.activity.MobileProMain"}
[HTTP] <-- GET /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e 200 20 ms - 965
[HTTP]
[HTTP] --> POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/timeouts
[HTTP] {"type":"implicit","ms":10000}
[debug] [W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":10000}
[HTTP] <-- POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/timeouts 400 528 ms - 5372
[HTTP]
[HTTP] --> POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/element
[HTTP] {"using":"-android uiautomator","value":"text(\"I AGREE\")"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["-android uiautomator","text(\"I AGREE\")","4cb91d76-aed3-4d01-b5a1-2c653e43880e"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"text(\"I AGREE\")","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"text(\"I AGREE\")","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'text("I AGREE")' using 'ANDROID_UIAUTOMATOR' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing selector: text("I AGREE")
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: class java.lang.String arg: "I AGREE"
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[TEXT=I AGREE]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
[debug] [W3C] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
[HTTP] <-- POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/element 200 99 ms - 87
[HTTP]
[HTTP] --> POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/element/1/click
[HTTP] {"id":"1"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["1","4cb91d76-aed3-4d01-b5a1-2c653e43880e"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [W3C] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/element/1/click 200 3203 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/element
[HTTP] {"using":"-android uiautomator","value":"new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/txtUsername\")"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/txtUsername\")","4cb91d76-aed3-4d01-b5a1-2c653e43880e"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/txtUsername\")","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"com.etrade.mobilepro.activity:id/txtUsername\")","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'new UiSelector().resourceId("com.etrade.mobilepro.activity:id/txtUsername")' using 'ANDROID_UIAUTOMATOR' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing selector: new UiSelector().resourceId("com.etrade.mobilepro.activity:id/txtUsername")
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: class java.lang.String arg: "com.etrade.mobilepro.activity:id/txtUsername"
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.etrade.mobilepro.activity:id/txtUsername]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'new UiSelector().resourceId("com.etrade.mobilepro.activity:id/txtUsername")' using 'ANDROID_UIAUTOMATOR' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing selector: new UiSelector().resourceId("com.etrade.mobilepro.activity:id/txtUsername")
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: class java.lang.String arg: "com.etrade.mobilepro.activity:id/txtUsername"
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.etrade.mobilepro.activity:id/txtUsername]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[HTTP] <-- POST /wd/hub/session/4cb91d76-aed3-4d01-b5a1-2c653e43880e/element 404 8470 ms - 1127
[HTTP]

**Here is the error in the eclipse console:-**

May 24, 2018 1:28:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidDriver.callee$0$0$ (C:\Users\Vnishal\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:69:13)
    at tryCatch (C:\Users\Vnishal\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Vnishal\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Vnishal\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Vnishal\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>, error=no such element, message=An element could not be located on the page using the given search parameters.}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-GP8HJ8T', ip: '10.0.0.243', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:423)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at io.appium.java_client.FindsByAndroidUIAutomator.findElementByAndroidUIAutomator(FindsByAndroidUIAutomator.java:38)
	at dashtest.main(dashtest.java:24)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:421)
	... 5 more

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/903
