### ISSUE TITLE
io.appium.java_client.events.EventFiringObjectFactory.lambda$0(List,Listener)boolean/invokeStatic

### ISSUE THREAD

**Issue by iAgentur** [appium/java-client#915]
I have integrated the one of the my android project to integrate to Appium and I have used below jar file. like
 implementation files('libs/java-client-6.0.0.jar')
    implementation files('libs/client-combined-3.12.0-sources.jar')
    implementation files('libs/client-combined-3.12.0.jar')
    implementation files('libs/byte-buddy-1.8.3.jar')
    implementation files('libs/commons-codec-1.10.jar')
    implementation files('libs/commons-exec-1.3.jar')
    implementation files('libs/commons-logging-1.2.jar')
    implementation files('libs/gson-2.8.2.jar')
    implementation files('libs/guava-23.6-jre.jar')
    implementation files('libs/httpclient-4.5.3.jar')
    implementation files('libs/httpcore-4.4.6.jar')
    implementation files('libs/okhttp-3.9.1.jar')
    implementation files('libs/okio-1.13.0.jar')
And when I compile the code then i got the error on build .gradle like
```
Caused by: java.lang.IllegalAccessException: no such method: io.appium.java_client.events.EventFiringObjectFactory.lambda$0(List,Listener)boolean/invokeStatic
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/support/AbstractApplicationContext
Caused by: java.lang.ClassNotFoundException: Class org.springframework.context.support.AbstractApplicationContext not found
```
 I have already used below code on my gradle file.
```
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
And Inside project I have used lambda expression like
```
fabStart.setOnClickListener(view -> {
     ........         
 });
```
Something like library did not support lambda expressions is it correct??

**Comment by iAgentur** [comment]
That issue seems like backward compatibility issue on the library for a lambda expression

So, I have used retrolambda then issue fixed.

**Comment by ashutoshdobhal** [comment]
how to use retrolamda, i am getting this after adding java client 6.1   and jdk1.8...
I have not started coding yet but just after rebuild getting this issue.

Please let me know the process to configure Appium in android studio..

**Comment by ashutoshdobhal** [comment]
Do we really require to Rebuild to execute TC?
Put our test cases inside src ->main-> Java folder instead of the src-> test case and execute test cases it will work.
