### ISSUE TITLE
can not find element with page object pattern

### ISSUE THREAD

**Issue by WenRui13** [appium/java-client#918]
## Description

can not find element with page object pattern，the UI is bellow
![image](https://user-images.githubusercontent.com/6370420/40641510-837dfdbc-634c-11e8-8d0c-239289e675b1.png)

`
public class CategoryScreen extends  BaseScreen {
……
@AndroidFindBy(xpath = "//*[@id='list_goods']/*[@class='android.widget.RelativeLayout' and @NAF='true']")
    @WithTimeout(time = 10,chronoUnit = SECONDS)
    private List<CategorySku> categorySkus;
……
}

public class CategorySku extends Widget {
    @AndroidFindBy(id = "iv_goods_icon")
    private MobileElement iv_goods_icon;

    @AndroidFindBy(id = "tv_goods_name")
    private MobileElement tv_goods_name;

    @AndroidFindBy(id = "price")
    private MobileElement price;

    @AndroidFindBy(id = "im_add_to_shoppingcart")
    private MobileElement im_add_to_shoppingcart;

    public void add2cart() {
        im_add_to_shoppingcart.click();
    }

    public void viewSku() {
        iv_goods_icon.click();
    }

    protected CategorySku(WebElement element) {
        super(element);
    }
}`

but the test bellow fail:
`    @Test
    public void testCategory2() throws Exception {

        getApp().homeScreen().accessTab("分类");
        
        getApp().categoryGridScreen().getCategorys().accessCategoryByName("鲜花烘焙");

        Assert.assertTrue(getApp().categoryScreen().getCategorySkus().size() > 0);

        System.out.println(getApp().categoryScreen().getCategorySkus().size());
    }`

## Environment

appium  v1.8.0 beta4
java-client  v6.0.0

## Link to Appium logs
https://gist.github.com/WenRui13/642246b5491661ee211ae76796b945a5

**Comment by SrinivasanTarget** [comment]
@WenRui13 Please raise this in appium discuss forum. Looking at code sorry we couldn't help.
