### ISSUE TITLE
GetPlatform API not working for Android

### ISSUE THREAD

**Issue by VinnieM** [appium/java-client#919]
## Description

The API appiumDriver.getCapabilities().getPlatform().is(Platform.ANDROID)) is returning false even if the Phone is Android.

## Environment

* java client build version or git revision if you use some shapshot:5.0.4
* Appium server version or git revision if you use some shapshot: 1.7.2
* Desktop OS/version used to run Appium if necessary: Mac OS, 10.13.4
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.11.1
* Mobile platform/version under test: Android, Samsung Note8, 7.1.1 
* Real device or emulator/simulator: Real Device

## Details

I have set the following capabilities.
DEVICE_NAME, UDID, ACCEPT_SSL_CERTS, AUTO_WEBVIEW, NEW_COMMAND_TIMEOUT, APPIUM_VERSION, FULL_RESET, NO_RESET, PLATFORM_NAME, AUTO_GRANT_PERMISSIONS, APP_PACKAGE and APP_ACTIVITY. 

Calling the API appiumDriver.getCapabilities().getPlatform().is(Platform.ANDROID)) is returning false even if the Phone is Android.

**Comment by SrinivasanTarget** [comment]
I don't think that API is meant for that, it will give system platform not device platform. I would suggest you to check the platformName in `driver.getSessionDetails()`

**Comment by VinnieM** [comment]
If it does give the system platform why does the the Enum Platform (refer package org.openqa.selenium) have Windows, Android, iOS, Linux and other options?
