### ISSUE TITLE
wait.until(ExpectedConditions.invisibilityOf(elementName)) not working 

### ISSUE THREAD

**Issue by zuzeac** [appium/java-client#929]
## Description

I'm trying to stop the test until the loading bar is no longer displayed.
I tried different approaches but no success, since the method keeps searching for the element I suspect it might be an issue 
## Environment

* java client : 6.0.0
* Appium : 1.7.2
* Desktop OS/version used to run Appium if necessary: Win 10 x64
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v8.9.4
* Mobile platform/version under test: android 6.0
* Real device or emulator/simulator: Real Device Samsung S6

## Details

I have a loading bar which I don't know exactly how long will be visible in the page.
When I use the "ExpectedConditions.invisibilityOf(elementName)" the method returns true as long as the loading bar is displayed, but when is no longer displayed, the method keeps to search for the element.
Sometimes, if the driver synchronize with the progress bar disappearance, it will catch that is no longer visible and continue with the test. But most of the times, the bar is no longer visible and the driver keeps searching for it and throws no element found.

I also tried with invisibilityOfElementLocated, stalnessOf and still the same issue.

## Code To Reproduce Issue [ Good To Have ]
My code:
```
public boolean isElementNotPresent(WebElement element) {
		try {
			WebDriverWait wait = new WebDriverWait(driver, 10);
			wait.until(ExpectedConditions.invisibilityOf(element));
			// wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("progress_bar")));
			return false;
		} catch (NoSuchElementException e) {
			return true;
		}

```
a second approach would be this:
```
public boolean NotPresent(WebElement element) {

		try {
			final Wait<AndroidDriver<AndroidElement>> wait = new AppiumFluentWait<>(driver, new SystemClock(),
					duration -> {
						Assert.assertEquals(duration.getSeconds(), 1L);
						Thread.sleep(duration.toMillis());
					}).withPollingStrategy(AppiumFluentWait.IterationInfo::getInterval).withTimeout(ofSeconds(10))
							.pollingEvery(ofSeconds(1));
			wait.until(ExpectedConditions.invisibilityOf(element));

			return false;
		} catch (NoSuchElementException expected) {
			return true;
		}
	}

```
## Ecxeption stacktraces

gist:79e2eec6fb808b2941705b7cd14aea1a

## Link to Appium logs

gist:223a3ca03827670753c8273e242572f0

**Comment by zuzeac** [comment]
@SrinivasanTarget I just update appium to 1.8.1 and still the same issue. Same logs.
The driver keeps searching for the element which is no longer displayed.

**Comment by SrinivasanTarget** [comment]
@zuzeac thanks for getting back. will look into it today

**Comment by SrinivasanTarget** [comment]
@zuzeac I dont see any logs above.

**Comment by zuzeac** [comment]
Can you open this?
https://gist.github.com/zuzeac/79e2eec6fb808b2941705b7cd14aea1a
https://gist.github.com/zuzeac/223a3ca03827670753c8273e242572f0

**Comment by SrinivasanTarget** [comment]
@zuzeac Switch to UIA2 backend and give a try.

**Comment by zuzeac** [comment]
@SrinivasanTarget I already tried, unfortunately same behavior.

https://gist.github.com/zuzeac/9e9865b77758f26373efff34d6a998b5
https://gist.github.com/zuzeac/aecae1fd6d5c3d0c548961c87eed0412

**Comment by vikramvi** [comment]
@zuzeac what's the value for implicit wait in your test ? IMO this is happening as you might have higher value for implicit wait. I suggest try to keep implicit value minimum and pass custom explicit value for each of the elements to be found / not found instead of hard coding to 10 sec.

Refer to accepted answer https://stackoverflow.com/questions/10404160/when-to-use-explicit-wait-vs-implicit-wait-in-selenium-webdriver

**Comment by zuzeac** [comment]
@vikramvi Indeed, i had the implicit wait bigger that explicit.
I changed now the implicit wait to 5 secs, and explicit wait wich is used in my method to wait for the element to disappear to 10 sec.
I tried also with UIA2 and still no luck.
It worked one time only, as I said above I think if the search for the element is done exactly when this is disappearing the method will work as expected.

**Comment by vikramvi** [comment]
can you check solution mentioned in https://github.com/appium/java-client/issues/617#issuecomment-396693300

**Comment by zuzeac** [comment]
I have checked the topic, It's not applicable for my problem.
My implementation is the same only the method used is different, i use invisibilityOf... in #617 (comment) is used presenceOf...
Since I have selenium 3.12.0 where the fix is already implemented. 

I intend to believe it might be a problem in the ExpectedConditions class with the invisibilityOfElement method.
