### ISSUE TITLE
Can't locate element with UiAutomator2 and appium 1.8.0

### ISSUE THREAD

**Issue by PascalBe07** [appium/java-client#930]
## Description

Can't locate elements after upgrading to java-client 6. When I try to locate an element, I get an exception which seems to me like a version problem. 

## Environment

* java client: 6.0.0
* org.seleniumhq.selenium (selenium-java): 3.12.0
* Appium server: 1.8.0
* Desktop OS/version: mac OS 10.13.4
* Node.js version: 9.7.1
* Mobile platform/version under test: android API 26 (using ui automator)
* Real device or emulator/simulator: emulator

## Code To Reproduce Issue [ Good To Have ]

// driver creation
    this.driver = ne AndroidDriver<>(serverUrl, capabilities)
// element location
    @AndroidFindBy(id = "supportedCountryButton")
    MobileElement selectCountryOrRegionButton;
// capabilities
    platformName=android
    automationName=uiautomator2
    udid=emulator-5554
    deviceName=android

## Exception stacktraces
[gist](https://gist.github.com/PascalBe07/213b4c855aed9932c597295ca7e1fa90)

## Link to Appium logs
Can be updated if needed.

**Comment by SrinivasanTarget** [comment]
@PascalBe07 Please try with latest appium server 1.8.1 with 6.0.0 Java client. It should be resolved there.

**Comment by PascalBe07** [comment]
@SrinivasanTarget This resolved the issue, yes. Thanks. 
Is there any documentation about which versions fit together in general? I think sometimes, this might help a lot.

**Comment by SrinivasanTarget** [comment]
Its preferred to use latest version as it comes with lot of bug fixes and enhancements usually.
