### ISSUE TITLE
Appium 1.8.0 - Appium inspector is not working, when we attach to the session appium session get closed

### ISSUE THREAD

**Issue by githubdilip** [appium/java-client#931]
## Description

Using Appium 1.8.0 for iOS native app automation. In the appium inspector when we attach to session, the Appium session get closed and the appium window get closed. Kindly do the needful

## Environment

* java client build version or git revision if you use some shapshot:6.0.0
* Appium server version or git revision if you use some shapshot:1.8.0
* Desktop OS/version used to run Appium if necessary:Mac 10.13
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:Appium.app
* Mobile platform/version under test:11.2.5
* Real device or emulator/simulator:Real device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

(https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by java.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by SrinivasanTarget** [comment]
@githubdilip Please raise these in appium discuss forum
