### ISSUE TITLE
5.4.0 and forward causes excessive getSession() calls

### ISSUE THREAD

**Issue by FilipWennerdahlSopraSteria** [appium/java-client#937]
## Description

With Java client 5.4.0 and forward there have been issues where getSession() gets executed between almost every command, severely slowing down iOS testing. This only occurs on iOS as far as i can see.
I suspect is has something to do with this commit: https://github.com/appium/java-client/pull/733
but i could use some advice on what exactly is going wrong. I've provided two appium log examples to show the difference between the versions, the ONLY thing changed between the two runs is the upgrade of Java Client from 5.3.0 to 6.0.0 (5.4.0 yields the same results).

If any further information is needed i will be happy to provide it.

## Environment

* java client build version or git revision if you use some shapshot: **6.0.0**
* Appium server version or git revision if you use some shapshot: **1.8.1**
* Desktop OS/version used to run Appium if necessary: **MacOS**
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: **9.5.0**
* Mobile platform/version under test: **iOS 11.2.5 hybrid app**
* Real device or emulator/simulator: **Real device**
* **Xcode version 9.2**
* **selenium-java 3.12.0**

## Link to Appium logs

* Appium log using java client 5.3.0
Test time 1m 7s
[gist](https://gist.github.com/FilipWennerdahlSopraSteria/1bd28f0788b297ab905c210c0a4bf756)

* Appium log using java client 6.0.0 (same result as using v5.4.0)
Test time 7m 30s
[gist](https://gist.github.com/FilipWennerdahlSopraSteria/d8da5a137dfaf7a2e2d3e3db6ce85de6)

**Comment by grvermeulen** [comment]
I've seen the same issue when i updated Appium from 1.7.2 to 1.8.1 with the same java client version.

**Comment by FilipWennerdahlSopraSteria** [comment]
@saikrishna321 When using the latest Java Client version 6.1.0 and the latest Appium 1.8.2-beta version everything seems to run fine and test execution times are back down to acceptable parameters. Thanks for the help!
