### ISSUE TITLE
Appium failed to find element in Android Oreo

### ISSUE THREAD

**Issue by sanojqa** [appium/java-client#940]
appium failed to find element in Android Oreo. 

I am using appium 1.7.2, Android Version: 8.0.0 and java-client: 5.0.4

**Comment by SrinivasanTarget** [comment]
@sanojqa Above info doesn't lead us anywhere. Fill the proper issue template and before that try the latest appium server and client versions. Also we are running our tests on Oreo without issues. Feel free to raise an issue with proper logs as gist. Hope you will update the duplicated server issue with all data requested.
