### ISSUE TITLE
Failed to start appium server programmatically with ios device

### ISSUE THREAD

**Issue by dancyzheng** [appium/java-client#946]
## Description

I could start appium server when running test with android device , but failed with ios device

## Environment

*java-client: 6.0.0
* Appium server: 1.8.0
* Desktop OS/version used to run Appium if necessary:
* Node.js : v8.11.2
* Mobile platform/version under test: ios 11.4
* Real device or emulator/simulator: real device ipad mini

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
AppiumDriverLocalService service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().withEnvironment(env)
				.usingDriverExecutable(new File(EnvironmentVariables.pathNode))
				.withAppiumJS(new File(EnvironmentVariables.pathAppium))
				.withIPAddress(EnvironmentVariables.defaultAddress).usingPort(EnvironmentVariables.defaultPort));
		service.start();

		if (service == null || !service.isRunning()) {
			throw new AppiumServerHasNotBeenStartedLocallyException("An appium server node is not started!");
		}
		
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", platformName);
		capabilities.setCapability("deviceName", deviceName);
		capabilities.setCapability("platformVersion", platformVersion);
		capabilities.setCapability("automationName", automationName);
		capabilities.setCapability("xcodeOrgId", xcodeOrgId);
		capabilities.setCapability("xcodeSigningId", xcodeSigningId);
		capabilities.setCapability("udid", udid);
		File app = new File(System.getProperty("user.dir") + "/apps/"+EnvironmentVariables.iosAppName);
		capabilities.setCapability("app", app.getAbsolutePath());
		driver = new IOSDriver(service, capabilities);
##Exception
log: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

## Link to Appium logs

https://gist.github.com/dancyzheng/4aac98187d18c19aac6b72f0b9324afc

**Comment by saikrishna321** [comment]
@dancyzheng 

> Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '9.3' 
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

Please install xcode-select

**Comment by dancyzheng** [comment]
I installed xcode command line, and add path to environment variables "PATH", then it works.

**Comment by saikrishna321** [comment]
closing as resolved
