### ISSUE TITLE
runAppInBackground() gives webdriverExeption saying that a java.util.HashMap cannot be cast to java.lang.Long 

### ISSUE THREAD

**Issue by mjm987mj** [appium/java-client#950]
## Description
Whenever I try to execute: getDriver().getAppiumDriver().runAppInBackground(Duration.ofSeconds(10));

I get the following exception:
org.openqa.selenium.WebDriverException: java.util.HashMap cannot be cast to java.lang.Long

## Environment
* java client build version: 6.0.0
* Desktop OS/version used to run Appium if necessary: N/A
* Mobile platform/version under test: iOS and Android
* Real device or emulator/simulator: Real Device

## Code To Reproduce Issue [ Good To Have ]
getDriver().getAppiumDriver().runAppInBackground(Duration.ofSeconds(10));

## Ecxeption stacktraces
org.openqa.selenium.WebDriverException: java.util.HashMap cannot be cast to java.lang.Long

## Link to Appium logs
https://gist.github.com/mjm987mj/e28970d02c4d67e4b65e1e1930cbe3f1

**Comment by saikrishna321** [comment]
@mjm987mj can you tell which version of java-client your using and the server version ?

**Comment by mjm987mj** [comment]
<groupId>io.appium</groupId>
<artifactId>java-client</artifactId>
<version>6.0.0</version>

Server version: 
I'm using Perfecto Mobile (v. 18.7.0.6) which is a cloud provider, so I'm not sure which appium version they use.

**Comment by mykola-mokhnach** [comment]
Did you try to contact Perfecto's customer support?

**Comment by mykola-mokhnach** [comment]
> Yes and they said that to use their own implementation for running the app in background. However I would like to use the one provided by Appium.

Then just stick to their suggestion or don't use their environment otherwise.
Closed as not an issue.
