### ISSUE TITLE
Is Pagefactory going to be deprecated in near future?

### ISSUE THREAD

**Issue by Gocoollnath** [appium/java-client#956]
## Description

https://github.com/appium/appium/issues/10906

**Comment by TikhomirovSergey** [comment]
@Gocoollnath it depends on Selenium team

**Comment by Gocoollnath** [comment]
@TikhomirovSergey In Selenium it is already. Whether in Appium it is going be done in any near future?

**Comment by vikramvi** [comment]
@Gocoollnath can you give reference for Pagefactory being removed from Selenium ? I'm curious to know the reasons behind it, for many automation engineers this is quite useful feature.

**Comment by saikrishna321** [comment]
@vikramvi https://github.com/SeleniumHQ/selenium/issues/4387#issuecomment-370502866

Further questions please ask in SeleniumHQ forum
