### ISSUE TITLE
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information) in Java client 6.1.0

### ISSUE THREAD

**Issue by alkaffkhanvrv** [appium/java-client#957]
AndroidBatteryInfo androidBatteryInfo = ((AndroidDriver<WebElement>) driver).getBatteryInfo();
double expectedBatteryLevel = androidBatteryInfo.getLevel();

I am getting the following error

org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information) in this line AndroidBatteryInfo androidBatteryInfo = ((AndroidDriver<WebElement>) driver).getBatteryInfo();

I have update to Java-client 6.1.0

Appium log is [here](https://gist.github.com/alkaffkhanvrv/53216853c56adfc1d5e7ecb7f881d364)

**Comment by mykola-mokhnach** [comment]
you must update the server as well

**Comment by alkaffkhanvrv** [comment]
I have updated my appium server to 1.8.1 but now I am getting this error

org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "batteryInfo". Only shell,startLogsBroadcast,stopLogsBroadcast commands are supported.

**Comment by mykola-mokhnach** [comment]
It's in appium@beta

**Comment by alkaffkhanvrv** [comment]
Still I am getting the same error after downgrading to 1.8.0

org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "batteryInfo". Only shell,startLogsBroadcast,stopLogsBroadcast comman

[debug] [W3C] Calling AppiumDriver.execute() with args: ["mobile: batteryInfo",[],"a8ada969-d7b9-4c72-9b93-269f799a1fa0"]
[HTTP] <-- POST /wd/hub/session/a8ada969-d7b9-4c72-9b93-269f799a1fa0/execute/sync 404 12 ms - 4358
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/a8ada969-d7b9-4c72-9b93-269f799a1fa0
[HTTP] {}

appium -v
1.8.0

**Comment by alkaffkhanvrv** [comment]
@mykola-mokhnach  May I know why it is still failing.

**Comment by mykola-mokhnach** [comment]
because 1.8.0 != beta

**Comment by alkaffkhanvrv** [comment]
After updated to 1.8.2-beta also throwing the same error
appium -v
1.8.2-beta

**Comment by mykola-mokhnach** [comment]
You must use UIAtomator2 backend. This endpoint does not work for UAI1

**Comment by alkaffkhanvrv** [comment]
Yeah Ok thanks.
