### ISSUE TITLE
AppiumDriverLocalService raises error [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by DiegoNovati** [appium/java-client#962]
## Description

When starting Appium programmatically with the following code

        private void startServer() {
		//Set Capabilities
		desiredCapabilities = new DesiredCapabilities();
		desiredCapabilities.setCapability("noReset", "false");
		
		//Build the Appium service
		appiumServiceBuilder = new AppiumServiceBuilder();
		appiumServiceBuilder.withIPAddress("127.0.0.1");
		appiumServiceBuilder.usingPort(4723);
		appiumServiceBuilder.withCapabilities(desiredCapabilities);
		appiumServiceBuilder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
		appiumServiceBuilder.withArgument(GeneralServerFlag.LOG_LEVEL,"error");
		
		//Start the server with the builder
		appiumDriverLocalService = AppiumDriverLocalService.buildService(appiumServiceBuilder);
		appiumDriverLocalService.start();
	}

I get the following error:

(node:80666) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

## Environment

Java: 
    Java(TM) SE Runtime Environment 18.3 (build 10+46)
    Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
Appium: 
   6.1.0
Desktop OS/version used to run Appium if necessary: 
   macOS High Sierra 10.13.5
* Node.js version:
   v10.5.0
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Code To Reproduce Issue [ Good To Have ]

public class CommonTest {

	@BeforeSuite
	public void setupEnvironment() {
		System.out.println("**** Starting Appium Server ****");
		startServer();
	}
	
	@AfterSuite
	public void tearDownEnvironment() {
		System.out.println("**** Stopping Appium Server ****");
		stopServer();
	}
	
	private void startServer() {
		//Set Capabilities
		desiredCapabilities = new DesiredCapabilities();
		desiredCapabilities.setCapability("noReset", "false");
		
		//Build the Appium service
		appiumServiceBuilder = new AppiumServiceBuilder();
		appiumServiceBuilder.withIPAddress("127.0.0.1");
		appiumServiceBuilder.usingPort(4723);
		appiumServiceBuilder.withCapabilities(desiredCapabilities);
		appiumServiceBuilder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
		appiumServiceBuilder.withArgument(GeneralServerFlag.LOG_LEVEL,"error");
		
		//Start the server with the builder
		appiumDriverLocalService = AppiumDriverLocalService.buildService(appiumServiceBuilder);
		appiumDriverLocalService.start();
	}
	
	private void stopServer() {
		if (appiumDriverLocalService != null) {
			appiumDriverLocalService.stop();
		}
	}
	
	private AppiumDriverLocalService appiumDriverLocalService;
	private AppiumServiceBuilder appiumServiceBuilder;
	private DesiredCapabilities desiredCapabilities;
}

Execute with TestNG

## Exception stacktraces

(node:80666) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

## Link to Appium logs

**Comment by saikrishna321** [comment]
@DiegoNovati Please provide full server logs to get help.

**Comment by DiegoNovati** [comment]
@saikrishna321 I cannot provide the server log because the error happens when trying to start the server using 

	//Start the server with the builder
	appiumDriverLocalService = AppiumDriverLocalService.buildService(appiumServiceBuilder);
	appiumDriverLocalService.start()

**Comment by saikrishna321** [comment]
I'm not able to re-produce this. Looks more a node.js issue. 

Whats version of appium server and node ?

**Comment by DiegoNovati** [comment]
After a search with Google it's clear that this is a node.js issue with the tar-streaming library (Appium is using an old version creating the error with node 10).

This is the output starting Appium:

....$ appium
(node:81502) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

Appium: 1.8.1
Node: v10.5.0
Npm: 6.1.0

**Comment by DiegoNovati** [comment]
The @beta version works !

Thank you
