### ISSUE TITLE
Not all entries of ElementMap are reachable by getElementClass

### ISSUE THREAD

**Issue by joerg1985** [appium/java-client#965]
## Description

The class io.appium.java_client.internal.ElementMap uses a internal map to provide fast access to all entries. The value of ElementMap.WINDOWS is not reachable by getElementClass, becase the get call to this map does a toLowerCase on the key (ElementMap.java:82) and the value written is not transformed to lower keys (ElementMap.java:82 / ElementMap.java:40).

This might fix the issue described in #774, because the correct element should be instantiated.

## Environment

* java client build version: 6.1.0
* Appium server version: WinAppDriver
* Desktop OS/version: Windows 10

**Comment by linyayu** [comment]
Why hasn't anyone solved it!!

**Comment by jenniferhuang** [comment]
which java client version?
