### ISSUE TITLE
[Android]Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by hsqzggg** [appium/java-client#97]
appium verison:1.2.2
java client version:1.6.2

when i run it ,the error threw like this"Unsupported major.minor version 51.0"

But if i change java client version to 1.4.0,it is OK!

**Comment by Tulseja** [comment]
I am getting the same error. I have selenium 2.47 and java client 2.1.0 and Latest version of appium. 
I am using JDK 8 . Should i downgrade jdk to 1.7 ? What are other options for cross platform mobile apps testing ?
