### ISSUE TITLE
Switch window in android chrome using appium not working

### ISSUE THREAD

**Issue by milesHero** [appium/java-client#970]
## Description

I am trying to convert a working selenium web automated testing to android automated testing. However, I encountered problem in switching to new window. There are two open window after the automated link clicked but when after doing the driver.switchTo().window(currentHandle), I'm still getting the url and title of the first window even though the window handle's name is changing from CDwindow-0 TO CDwindow-1 using java client 6.1.0,. I am encountering this error from 6.1.0 down to java-client 6.0.0-BETA5 but when I switched my java client version to 6.0.0-BETA4. Window switching worked as expected.

## Environment

* java client build version or git revision if you use some shapshot: 6.1.0
* Appium server version or git revision if you use some shapshot: 1.6.2
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device - Samsunng Galaxy A7

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/milesHero/f5eb6510619773f198dc2927742a18ca#file-switch-to-window-code
https://gist.github.com/milesHero/f5eb6510619773f198dc2927742a18ca#file-desired-capabilities

## Ecxeption stacktraces

https://gist.github.com/milesHero/f5eb6510619773f198dc2927742a18ca#file-console-logs

## Link to Appium logs

https://gist.github.com/milesHero/f5eb6510619773f198dc2927742a18ca#file-appium-logs

**Comment by milesHero** [comment]
Hi @mykola-mokhnach do you have any updates on this? Is the switch window function already working on java-client 6.1.0? Thank you.

**Comment by SimonBaars** [comment]
@milesHero No, 6.1.0 is still not working.

**Comment by surajgupta7175** [comment]
Any update till when this issue will be fixed? Facing issue.. :(

**Comment by SrinivasanTarget** [comment]
@surajgupta7175 I think its a problem with chromedriver in w3c mode. please set `forceMjsonwp` capability as true, it should work fine. Chrome hasn't fully supported w3c mode yet.
