### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=33000000-0000-0000-6139-000000000000}

### ISSUE THREAD

**Issue by bkumar08** [appium/java-client#971]
Getting following error when i running the test against IOS devices on Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '10.0.1

Exception in thread "main" org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=33000000-0000-0000-6139-000000000000}

## Environment

* java client jar version : java-client-5.0.2.jar
* Appium desktop server version : 1.8.1
* Desktop OS/version used to run Appium if necessary: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '10.0.1'
* Selenium jar version : 2.45.0 
* Real device or emulator/simulator: simulator

## Details

{code}
Exception in thread "main" org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=33000000-0000-0000-6139-000000000000}
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'asm-3.local', ip: '172.16.0.80', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '10.0.1'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at io.appium.java_client.FindsByAccessibilityId.findElementByAccessibilityId(FindsByAccessibilityId.java:31)
	at testlastpack.IOSTest.main(IOSTest.java:13)
Caused by: java.lang.ClassCastException: java.base/java.util.HashMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
	... 5 more
{code}

## Code To Reproduce Issue :

package testlastpack;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.IOSElement;
import io.appium.java_client.remote.AutomationName;
import io.appium.java_client.remote.MobileCapabilityType;

public class TestLast {
	static IOSDriver<IOSElement> driver;
	public static IOSDriver<IOSElement> capabilities() throws MalformedURLException 
	{
		
		DesiredCapabilities obj = new DesiredCapabilities();
		obj.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 8");
		obj.setCapability(MobileCapabilityType.PLATFORM_NAME,"IOS");
		obj.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
		obj.setCapability(MobileCapabilityType.APP,"/Users/bkumar/Desktop/UICatalog.app");
		driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),obj);
		driver.manage().timeouts().implicitlyWait(15,TimeUnit.SECONDS);
		return driver;		
	}

}
==========================================================
Main method class 

package testlastpack;

import java.net.MalformedURLException;

import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.IOSElement;

public class IOSTest extends TestLast{

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		IOSDriver<IOSElement>driver = capabilities();
		driver.findElementByAccessibilityId ("Alert Views").click();
		driver.findElementByXPath ("//*[@value='Text Enter']").click();
		driver.findElementByClassName ("XCUIElementTypeTextField").sendKeys("hellob");
		driver.findElementByAccessibilityId ("Ok").click();
	}

}

##  Appium logs
XCUITest] Log file for xcodebuild test: /var/folders/bk/shl67gl17zqd764mf8fk5y080000gp/T/com.apple.dt.XCTest/IDETestRunSession-C038F5E8-4613-40D0-A776-6D819C9C7E59/WebDriverAgentRunner-BD6341E8-BF2F-4345-827A-278241ABB675/Session-WebDriverAgentRunner-2018-07-11_182446-1QGKGm.log
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Shutting down because we waited 60 seconds for a command
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[XCUITest] Deleting simulator created for this run (udid: '326AFF5B-CDA7-49FA-B9B7-4F84C927A764')
[XCUITest] Killing running processes 'xcodebuild.*326AFF5B-CDA7-49FA-B9B7-4F84C927A764, 326AFF5B-CDA7-49FA-B9B7-4F84C927A764.*XCTRunner' for the device 326AFF5B-CDA7-49FA-B9B7-4F84C927A764...
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session b7957590-376d-4465-ac6b-a86c937ee50d from our master session list
[XCUITest] 'pgrep -nif xcodebuild.*326AFF5B-CDA7-49FA-B9B7-4F84C927A764' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif 326AFF5B-CDA7-49FA-B9B7-4F84C927A764.*XCTRunner' didn't detect any matching processes. Return code: 1

**Comment by SrinivasanTarget** [comment]
@bkumar08 I would suggest to use latest version of appium server 1.8.2-beta and latest java client 6.1.0 and give a try. Feel free to raise with detailed logs if you hit the same.

**Comment by bkumar08** [comment]
@SrinivasanTarget , Thanks for quick reply !  i tried to download appium server 1.8.2. but didn't appium desktop 1.8.2-beta for mac OS.
Could you please help me to get appium desktop 1.8.2 for MAC OS. 

i fund appium server 1.8.2-beta for WINDOWS system. but i am using the MAC system

**Comment by saikrishna321** [comment]
> [XCUITest] xcodebuild exited with code '65'

you have code signing issue with WDA.

**Comment by vietlq4** [comment]
Dear @SrinivasanTarget do you resolved this issue?
