### ISSUE TITLE
Not able to select/enter a date in date picker

### ISSUE THREAD

**Issue by Ram-Raghu** [appium/java-client#973]
Dear all,

I am using API 28 and using native android app. I am unable to select a date using the below code. 

dateElement.sendKeys("11").

When I use the above method to select date, it appears to click and select the date but not entering the input date.

**Environment**

* java client version - 5.0.4
* Appium server version - 1.6.2
* Desktop OS/version used to run Appium if necessary: 1.6.2 (OSX)
* Mobile platform/version under test: 9.0
* Real device or emulator/simulator: Simulator

Anyone has solved this problem of selecting a date, month and year in a datepicker (android.widget.NumberPicker)?

**Comment by SrinivasanTarget** [comment]
@Ram-Raghu I think you should probably ask this question in Appium Discuss forum.

**Comment by SrinivasanTarget** [comment]
@Ram-Raghu Also i suggest you to try latest Appium client and Server versions.
