### ISSUE TITLE
Element doesn't appear in elements tree

### ISSUE THREAD

**Issue by radikpsb** [appium/java-client#974]
## Description

I have a problem with locating an element on screen. This element doesn’t exist in the page structure that available from java client, but it exists in the appium inspector. I have to notice that this element appears dynamically when there is an error with validation. If appium inspector is connected to test’s session it can’t see the element so the problem not in timeouts etc. It seems to me that problem is in configuration of java client, but I have completely the same desired capabilities on both clients. The issue doesn’t reproduce with other screens so far, but it permanently reproducible on the specific screen.

## Environment

* java client version: 6.1.0
* Appium server version: 1.8.1
* Desktop OS version: macOS Sierra
* Appium.app version: 1.6.2
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: simulator

## Ecxeption stacktraces

[stacktrace of exception thrown by java](https://gist.github.com/radikpsb/d50ff73dc5f62dab452bc8ab7e3bdc22)

## Link to Appium logs

[_full_ Appium logs](https://gist.github.com/radikpsb/4585e3bf0821755e9889012fdaf0b1eb)

**Comment by SrinivasanTarget** [comment]
@radikpsb Were you able to see in page source?

**Comment by radikpsb** [comment]
The element is not presented in page source.

**Comment by SrinivasanTarget** [comment]
@radikpsb then appium can't do anything

**Comment by radikpsb** [comment]
@SrinivasanTarget it works fine from desktop app so the element shows without any additional actions

**Comment by SrinivasanTarget** [comment]
@radikpsb Did you checked which verison of appium does your desktop use and which version of appium does your terminal env use?

**Comment by radikpsb** [comment]
@SrinivasanTarget yeah, I always start server through appium desktop and connect to it from test environment. The version is 1.8.1

**Comment by SrinivasanTarget** [comment]
@radikpsb Install latest appium server beta through `npm install -g appium@beta` and give a try.

**Comment by SrinivasanTarget** [comment]
@radikpsb Once you try latest appium server version. Check `driver.getPageSource` and check if the element is there. Its more of a code issue at your side.

**Comment by radikpsb** [comment]
@SrinivasanTarget unfortunately it didn't help

**Comment by SrinivasanTarget** [comment]
@radikpsb If you couldn't find in pageSource then nothing that i could help.

**Comment by radikpsb** [comment]
@SrinivasanTarget Any ideas why appium desktop shows the element without any additional actions? Are there options for WebDriverAgent or XCUI that can help? I've tried `simpleIsVisibleCheck=false`, but it had no effect.

**Comment by radikpsb** [comment]
I've tried to get source from WebDriverAgent itself by running it from Xcode and using query like `curl -X GET -H "Content-Type: applications/json" http://localhost:54246/source`. Well it shows source with the element. It works fine with either Appium desktop's WebDriverAgent and Appium 1.8.2 beta's WebDriverAgent.

**Comment by radikpsb** [comment]
@SrinivasanTarget you're right, the problem is in the WebDriverAgent. When I do actions from test script, using HTTP queries, page source doesn't contain desired element. It's important that actions must be done using queries but not using mouse taps in simulator. I've created the [issue](https://github.com/facebook/WebDriverAgent/issues/966).

Thanks for your helping.
