### ISSUE TITLE
CAN NOT use sendKeys() to input chinese words in react native 

### ISSUE THREAD

**Issue by 317174106** [appium/java-client#975]
## Description

I want to input some Chinese words into Android textbox. 
But the text inputted is encoded, not the real text.
I set the unicodeKeyboard=true, it still doesn't work.
why?

Btw, it's a react native page

## Environment

* java client 6.1.0
* Appium server 1.8.1
* Windows
* Mobile platform : 5.1.0
* emulator

## Code To Reproduce Issue [ Good To Have ]

[MJSONWP] Calling AppiumDriver.setValue() with args: [["咸超"],"2","277ff3c4-9b01-4a23-9d97-665090d09014"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"2","text":"咸超","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"2","text":"咸超","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 2
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text remains after clearing, but it appears to be hint text.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text not cleared. Assuming remainder is hint text.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending Unicode text to element: 咸超
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Encoded text: &VLiNhQ-

**Comment by SrinivasanTarget** [comment]
@317174106 Try UIA2 mode.
