### ISSUE TITLE
No such element error is not converted to a proper NoSuchElementException

### ISSUE THREAD

**Issue by vmuzikar** [appium/java-client#976]
## Description

Using WebDriver and Google Chrome, try to find some non-existing element in a test and try-catch the `NoSuchElementException`. Instead, a `WebDriverException` is thrown due to wrong conversion from the Appium Server response.

## Environment

* java client build version: 6.1.0
* Appium server version: 1.8.1
* Desktop OS/version: macOS 10.13.6
* Node.js version: 8.11.3
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: emulator

## Details
Happens specifically only with Android/Chrome, iOS works just fine.

## Code To Reproduce Issue

```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Appium");
capabilities.setCapability(AndroidMobileCapabilityType.AVD, "Nexus_5X_API_27");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "blabla");

driver = new AndroidDriver(capabilities);

driver.navigate().to("http://www.google.com");
try {
    driver.findElement(By.id("non-existing-id"));
}
catch (NoSuchElementException e) {
    System.out.println("Jupiii!"); // this never executes because WebDriverException is thrown
}
Thread.sleep(5000);
```

## Ecxeption stacktraces

https://gist.github.com/vmuzikar/8c74c3354ad14462af56cd5998f8cbeb

## Link to Appium logs

https://gist.github.com/vmuzikar/419f293ff3905d5abe94ab4368cac3ee

**Comment by mykola-mokhnach** [comment]
This should be addressed in appium@beta

**Comment by vmuzikar** [comment]
@mykola-mokhnach Thanks for your reply! Do you mean Appium Server beta (i.e. 1.8.2)? So this is not an Appium Client issue?

**Comment by vmuzikar** [comment]
I've just tested it with Appium Server v1.8.2-beta with the same result.

**Comment by mykola-mokhnach** [comment]
Can you attach the updated server log?

**Comment by vmuzikar** [comment]
The log from v1.8.2-beta: https://gist.github.com/vmuzikar/1ac10eee2d3f039547fede14af877897

**Comment by mykola-mokhnach** [comment]
Thanks, this is definitely the problem of the server side. 

```
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/edc92c6a-581e-4727-8a12-b6fdb73b638c/element[39m
[35m[HTTP][39m [90m{"using":"id","value":"blahblah"}[39m
[35m[W3C][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Proxying [POST /wd/hub/session/edc92c6a-581e-4727-8a12-b6fdb73b638c/element] to [POST http://127.0.0.1:8000/wd/hub/session/c7efc7eea10f57f9d5dbefd93d8872cd/element] with body: {"using":"id","value":"blahblah"}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"c7efc7eea10f57f9d5dbefd93d8872cd","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"id\",\"selector\":\"blahblah\"}\n  (Session info: chrome=67.0.3396.87)\n  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)"}}
[35m[JSONWP Proxy][39m Replacing sessionId c7efc7eea10f57f9d5dbefd93d8872cd with edc92c6a-581e-4727-8a12-b6fdb73b638c
[35m[HTTP][39m [37m<-- POST /wd/hub/session/edc92c6a-581e-4727-8a12-b6fdb73b638c/element [39m[32m200[39m [90m111 ms - 332[39m
```

I would not expect the last response code to be equal to 200.

@imurchie @dpgraham Would you like to take a look?
