### ISSUE TITLE
NullPointerException on instantiating AndroidDriver

### ISSUE THREAD

**Issue by kameshbabu** [appium/java-client#979]
## Description
NullPointerException thrown during instantiating AndroidDriver after updating to latest java_client library 6.1.0.

## Environment

* java client build version: 6.1.0
*  Node.js version: v10.1.0
* Mobile platform/version under test: 4.1.2
* Real device or emulator/simulator: Real Android device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName.trim());
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, platformName); /* Mandatory */
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformVer); /* Mandatory */
capabilities.setCapability(MobileCapabilityType.UDID, deviceName.trim()); /* Mandatory */
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 60 * 5);
capabilities.setCapability("appPackage", appPackage);
capabilities.setCapability("appActivity", appActivity);
capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, appActivity);
driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);// NPE thrown here.
```

## Ecxeption stacktraces

 [StackTrace](https://gist.github.com/kameshbabu/a0984bc9095b191a9c0097b1008339ad)

**Comment by ashishranjanJN** [comment]
I am also facing this issue and it is woking well if WebDriver is used(instead of AndroidDriver).
But with WebDriver, I am not able to perform several API calls such as KeyStroke.
Let me know how to resolve this issue

**Comment by saikrishna321** [comment]
I'm unable to reproduce this issue. can you pls try reproducing it with [sample-code](https://github.com/appium/appium/tree/master/sample-code/java)

**Comment by saikrishna321** [comment]
Closing as inactive
