### ISSUE TITLE
Element visible  in Appium inspector but not in test code

### ISSUE THREAD

**Issue by hujosh** [appium/java-client#981]
## Description

I have a section in my android app, call it a. I first use the Appium Inspector to get the IDs of the elements on a. So far so good. Then, when I use those IDs in the  code that tests section a, the IDs no longer work.

The only thing I can think of is that the Android app changes the xml of a after Appium has taken its snapshopt of a. 

I could test this theory by refreshing the snapshot, but when I try to do that (in python) i get "this method is not implemented."

## Environment

* Appium 1.8.1
* Android 7.0
* Galaxy S6 (real device)
* Node 10.6.0
* Java Info *
* java version 1.8.0_171
* Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
* Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by navneet-kumar** [comment]
This happened it with me once..
>> I first use the Appium Inspector to get the IDs of the elements
after this step make sure you cross verify it in the inspector first befor you use it 

something like this >>
![screen shot 2018-07-25 at 15 43 53](https://user-images.githubusercontent.com/19570353/43183895-af6eeee8-9021-11e8-9343-abb2a6b8b1d3.png)

**Comment by hujosh** [comment]
@navneet-kumar 

hi, I have already tried that. The IDs work when I cross verify them, so it's not that.

**Comment by navneet-kumar** [comment]
@hujosh , could you please provide
1. appium logs
2. source xml ( when you execute the app and when you inspect both)

**Comment by zuzeac** [comment]
I'm confront with this issue often when I'm running the test on Android 7 and 8.
suddenly and randomly, the driver cannot find an element which is for sure visible.
On android 6.0 works perfectly.
Might be and issue with the android version and the driver.

**Comment by hujosh** [comment]
I think I know what the problem is.

When I print the XML that Appium is using for the snapshot, I can see that it's different to the XML that the Appium Inspector uses. I don't know how the same section of the app could return two different XML snapshots. I think though that it has something to do with the throbber (loading bar). 

I would like to be able to refresh the snapshot of the XML that appium uses, but the refresh function in Python doesn't work. Is there another way?

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/974

**Comment by shrutikahilale** [comment]
> [navneet-kumar](/navneet-kumar)

Hi navneet, I am facing the issue, when I locate that element in the page source I can find it, but not able to search via the search bar.
PFA
<img width="1439" alt="Screenshot 2024-04-24 at 5 02 58 PM" src="https://github.com/appium/java-client/assets/102667828/fda1a047-1039-44db-8d5e-8954940b5103">

not able to find
<img width="1439" alt="Screenshot 2024-04-24 at 5 03 50 PM" src="https://github.com/appium/java-client/assets/102667828/66ab36a3-43c3-41a6-a7aa-fc4312219dbf">
<img width="1439" alt="Screenshot 2024-04-24 at 5 03 55 PM" src="https://github.com/appium/java-client/assets/102667828/758a6d90-c61d-4b1c-b021-8a1471dd3617">

Please help here.

**Comment by eglitise** [comment]
@shrutikahilale you may want to check if the element is actually visible on the device itself. You can see the warning in the Selected Element panel - 'Interactions are not available for this element'. This often means that by the time the element was selected in the app source, it had already disappeared.
Also, the warning behavior is adjusted in newer Inspector versions, so I would suggest updating it.

**Comment by shrutikahilale** [comment]
> @shrutikahilale you may want to check if the element is actually visible on the device itself. You can see the warning in the Selected Element panel - 'Interactions are not available for this element'. This often means that by the time the element was selected in the app source, it had already disappeared. Also, the warning behavior is adjusted in newer Inspector versions, so I would suggest updating it.

Thanks for your prompt reply. 
I have enabled the "allowInvisibleElements" to true and "enableMultiWindows" to true. After which I was able to see for these elements in the page source. But now I am encountering an issue that, the first 2 dropdown options are detected by xpath (and not by uiautomator) which is fine, but the thirst option (Completed) is not detected by any method.
