### ISSUE TITLE
Unhandled endpoint: /session/F9109D8A-8197-47E8-9A44-F27363C40A1A/wda/screen

### ISSUE THREAD

**Issue by Chiliwey** [appium/java-client#982]
## Description

When I try to create a new session for IOS it creates the new session but it doesn't find the session that was created for the phone. 

## Environment
Appium server - 1.8.1
Java-Client - 6.1.0
Selenium - 3.12.0
MAC - 10.13.6
Real Device
Iphone X - version 11.3.1
Iphone 6 - version 11.4.1

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
public DesiredCapabilities initLocalIOS() {
        DesiredCapabilities dc =  new DesiredCapabilities();
        String deviceName, platform, automationName, bundleId, app, udid;
        device = json.getJSONObject("LocalIOS");
        platform = getCapabilitie("platform");
        deviceName = getCapabilitie("deviceName");
        automationName = getCapabilitie("automationName");
        bundleId = getCapabilitie("bundleId");
        udid = getCapabilitie("udid");
        app = getCapabilitie("app");

        File appPath = new File(app);

        dc.setCapability("deviceName", deviceName);
        dc.setCapability("platformName", platform );
        dc.setCapability("automationName", automationName);
        dc.setCapability("bundleId",bundleId);
        dc.setCapability("app",appPath.getAbsolutePath());
        dc.setCapability("udid", udid);
        dc.setCapability("networkConnectionEnabled", true);

        return dc;
    }

 public static IOSDriver initIOS(DesiredCapabilities dc) throws MalformedURLException{
        IOSDriver<MobileElement> id = new IOSDriver<MobileElement>(new URL(service.getURL), dc);
        return id;
    }

## Exception stacktraces
Java log:
https://gist.github.com/Chiliwey/92cdc9d0a3cfdd9e47343a6ae3dc380e

## Link to Appium logs
https://gist.github.com/Chiliwey/5b0073277fffe696366ec7667a83c88b

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/search?q=%22%2Fwda%2Fscreen%22&unscoped_q=%22%2Fwda%2Fscreen%22&type=Issues

**Comment by saikrishna321** [comment]
@Chiliwey you have outdated WDA binary. Please install the latest.

**Comment by lbCognits** [comment]
Appium manage the WDA right?
I have been trying all the solutions on the link of mykola and none of it fixed it.
I already uninstall and install appium to get the latest, also I unisntall manual the WDA from the phone and then restarted it.

**Comment by Chiliwey** [comment]
Appium manage the WDA right?
I have been trying all the solutions on the link of mykola and none of it fixed it.
I already uninstall and install appium to get the latest, also I unisntall manual the WDA from the phone and then restarted it.

**Comment by Chiliwey** [comment]
I make it work, I found a useful script to erase everything on the xcode cache because doing clean on xcode didn't work.

Link:
https://gist.github.com/maciekish/66b6deaa7bc979d0a16c50784e16d697

Btw when you run the script you need to set the credentials again to the WDA Runner in xcode. If you don't do it you will get "xcodebuild failed with code 65".
