### ISSUE TITLE
This is not an bug/issue. A Question. Need help!!!

### ISSUE THREAD

**Issue by Akshaj** [appium/java-client#989]
Hi All,

I am trying to create a Maven project in eclipse and add the Appium client to the project using maven dependencies.

I am trying to add V5.0.4 dependencies in the pom.xml file.
The following link says that for V5.0.4, Selenium 3.6.0 has to be used:
https://github.com/appium/java-client/releases

So ,along with V5.0.4 I am using Selenium 3.6.0.

As soon as I add the dependencies and build the project, it shows an error on the pom.xml file.
In eclipse , beside the "Console" tab, there will be tab called "Markers" tab, it shows the following errors:
Errors pasted in the attached file.
[ErrorsInMarkersTab.txt](https://github.com/appium/java-client/files/2257399/ErrorsInMarkersTab.txt)

Because of this, I am unable to proceed ahead at all. Need help in this. Someone please let me know how to proceed with V5.0.4 using Maven.

NOTE: Once the error is shown, I tried removing the appium V5.0.4 dependency and build again. No errors at all. Something is wrong with the appium dependency only.

Regards,
Akshaj.

**Comment by amitjaincoer191** [comment]
You can try following resolutions as error says caching issue.

**Comment by saikrishna321** [comment]
Please ask for the question in discuss.appium.io. This place is for issues.

**Comment by Akshaj** [comment]
Hi Amit,

Thanks for responding. But that did not work.
When I right click on the project and go to Build Path -> Configure Build Path It shows errors on the jars which got downloaded by maven. Not sure why. See the screenshot Attached.
![error](https://user-images.githubusercontent.com/37771056/43674875-ce1445fe-97f7-11e8-8db2-3b186ab7e196.png)
