### ISSUE TITLE
Press search button from soft keyboard

### ISSUE THREAD

**Issue by arpan88** [appium/java-client#99]
Hi all,

I was writing an automation example with appium for android (with latest appium server and java client). I tried to press a search button from the soft keyboard but unable to do so.

```java

WebElement searchQueryText = driver.findElement(By.id("android:id/search_src_text"));		
		searchQueryText.sendKeys("Spring tutorial");
((AppiumDriver)driver).sendKeyEvent(0x00000054);
```
key event reference taken from here
http://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_SEARCH

It didn't work. But, when I sent "s" from soft keyboard in the same way it worked and the character "s" was shown in the searchbox successfully

```java
((AppiumDriver)driver).sendKeyEvent(0x0000002f);
```
So what am I missiing here ?

Thanks
Arpan

**Comment by vietnq254** [comment]
If the Search button is focused you can send the key Enter by this way:
```
AndroidDriver dr;
dr.sendKeyEvent(AndroidKeyCode.ENTER);
```

Generally if you want to use Id to find element, you must be sure you can see its ID by using ```UIAutomator (uiautomatorviewer)``` and then use ```click()```.

**Comment by ShruthiSudhanva** [comment]
Hi @arpan88 ,

We are experiencing the same issue with sendKeyEvent. Were you able to find any solution to this issue? Or any workaround?

Thanks!

**Comment by aniket-21** [comment]
Could you paste the server trace? What happens when you send a key event. Is there any error?

**Comment by TikhomirovSergey** [comment]
@arpan88 
Please reopen this ticket or onen a new one.
